### ISSUE TITLE
Question: Is it possible to specify a target that is not part of the input set?

### ISSUE THREAD

**Issue by arniwesth** [unit8co/darts#1004]
What I would like is to specify a target that is not part of the input time series. Say I have time series **ts_0**, **ts_1**, ... and I want to forecast **ts_y** where **ts_y** not in {**ts_0**, **ts_1**, ...} (for when eg **ts_y** is not directly observable). Is this possible with darts? Any examples?

**Comment by hrzn** [comment]
I am not sure what you mean by input set, but as shown for example [in the quickstart](https://unit8co.github.io/darts/quickstart/00-quickstart.html#A-toy-example-with-two-series), it is possible to forecast a series that is not part of the training set, doing `my_pred = my_model.predict(series=ts_y, n=...)`.
