### ISSUE TITLE
timeseries.from_dataframe adding additional dates and values[BUG]

### ISSUE THREAD

**Issue by maheshs11** [unit8co/darts#1006]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7268915/173266798-4a750d3b-b84f-450e-b7a5-1f7524c553f7.png)
![image](https://user-images.githubusercontent.com/7268915/173266895-3de4d197-bba2-4cef-a47e-79f384c6d51c.png)
 
my dataset contains data only till 2022-05 but after passing it through the function it is adding dates and random values till 2023-01. 

 - Python version: [e.g. 3.8]
 - darts version [e.g. 0.19.0]

**Additional context**
And also i have missing values in prices , i have used fillna (method= ffill ), not getting the expected result , how to handle this?
![image](https://user-images.githubusercontent.com/7268915/173267437-c1479648-6515-4920-bdac-e38adf664fb1.png)

**Comment by brunnedu** [comment]
Hi @maheshs11, judging from your second image, the datetimeindex of your dataframe actually extends until `2022-12-05 22:00`. So the `TimeSeries.from_dataframe` method doesn't seem to add any additional dates. Maybe you can try filling the missing values directly in the `TimeSeries.from_dataframe()` method by calling `TimeSeries.from_dataframe(df, time_col='date', fill_missing_dates=True, freq='1H', fillna_value=0)`.

**Comment by maheshs11** [comment]
> Hi @maheshs11, judging from your second image, the datetimeindex of your dataframe actually extends until `2022-12-05 22:00`. So the `TimeSeries.from_dataframe` method doesn't seem to add any additional dates. Maybe you can try filling the missing values directly in the `TimeSeries.from_dataframe()` method by calling `TimeSeries.from_dataframe(df, time_col='date', fill_missing_dates=True, freq='1H', fillna_value=0)`.

as you can see in in dataframe df4 it is only till "2022-12-05" and see the figure plotted till 2023.
![image](https://user-images.githubusercontent.com/7268915/173710095-bddb3c6c-8c43-4c0b-be87-67e3c5a39d2d.png)
the first figure data is original plotted data ,after passing it to function i get fig 2.

https://www.cryptodatadownload.com/cdd/Binance_BTCUSDT_1h.csv
my dataset
