### ISSUE TITLE
[BUG] Temporal transformer with only past covariates and add_relative_index

### ISSUE THREAD

**Issue by martinb-bb** [unit8co/darts#1009]
**Describe the bug**
I cannot train a Temporal Transformer with only providing `past_covariates` and setting `add_relative_index=False`

**How to reproduce**
From tutorial on site:
![image](https://user-images.githubusercontent.com/105685594/173976188-bd813514-80fb-4d2e-a999-b08d945ebc35.png)

No future covariates are passed. 
`add_relative_index`: adds a scaled integer position relative to the prediction point for each encoder-decoder chunk (this might be useful if you really don’t want to use any future covariates. The position values remain constant over all chunks and do not add additional information).

Therefore following the same advice:
```python 
tft_model = TFTModel(
        input_chunk_length=input_chunk_length,
        output_chunk_length=output_chunk_length,
        hidden_size=hidden_size,
        lstm_layers=lstm_layers,
        num_attention_heads=num_attention_heads,
        full_attention=full_attention,
        dropout=dropout,
        hidden_continuous_size=hidden_continuous_size,
        model_name=model_save_name,
        force_reset=force_reset,
        save_checkpoints=save_checkpoints,
        random_state=42,
        n_epochs=n_epochs,
        batch_size=batch_size,
        pl_trainer_kwargs=pl_trainer_kwargs,
        likelihood=QuantileRegression(
            quantiles=quantiles
        ),  # QuantileRegression is set per default
        add_relative_index=False, 
    )

```

Gives me the error:
```
Error: TFTModel requires future covariates. The model applies multi-head attention queries on future inputs. Consider specifying a future encoder with `add_encoders` or setting `add_relative_index` to `True` at model creation (read TFT model docs for more information). These will automatically generate `future_covariates` from indexes.
```

**Comment by shaido987** [comment]
You probably meant to use `add_relative_index=True` (as proposed in the error message)?

**Comment by martinb-bb** [comment]
I don't want to use 'add_relative_index=True` because I do not have future covariates.

**Comment by dennisbader** [comment]
When you have `future_covariates` then you don't have to use `add_relative_index` or `add_encoders`.

When you don't have `future_covariates`, you must either set `add_relative_index=True` or use a "future"-encoder with `add_encoders` (as done in the tutorial). In your example you give neither of them which is why it raises an error.

**Comment by martinb-bb** [comment]
@dennisbader  Thank you for the explanation! That clears it up. 👍
