### ISSUE TITLE
num_loader_workers not passed to TorchForechastingModel.predict_from_dataset()

### ISSUE THREAD

**Issue by ludomitch** [unit8co/darts#1014]
**Describe the bug**
`venv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:241: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.`

The bug is due to the fact that in `darts/models/forecasting/torch_forecasting_model.py`, in the `predict` method, `num_loader_workers` is not being passed into `predict_from_dataset` and is thus not being used anywhere. Fixed by changing the code with:

`        predictions = self.predict_from_dataset(
            n,
            dataset,
            trainer=trainer,
            verbose=verbose,
            batch_size=batch_size,
            n_jobs=n_jobs,
            roll_size=roll_size,
            num_samples=num_samples,
            num_loader_workers=num_loader_workers
        )`

**To Reproduce**
Run `predict()` on any of the deep learning models that make use of the `TorchForecastingModel` class.

**Expected behavior**
If I set `num_loader_workers=1` as an argument in predict, this warning should not appear.

**System (please complete the following information):**
 - Python version: 3.8.10
 - darts version 0.19.0

**Additional context**
Suggestion: Running something like pylint on the whole code to catch these errors.

**Comment by dennisbader** [comment]
Hi @ludomitch and thanks for reporting that! Would you be willing to open a PR with the fix? :)

**Comment by hrzn** [comment]
This was fixed in 0.20.0
