### ISSUE TITLE
Static Covariates example 

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#1016]
**Is your feature request related to a current problem? Please describe.**
@dennisbader Could you add a static covariates example? I tried looking through the test code, but I had trouble converting it to a real-world example.

**Comment by martinb-bb** [comment]
Second this! 😃

**Comment by dennisbader** [comment]
I am out of office this and the next two weeks. 
Happy to do it when I get back :)

For the meantime, you can check out  `TimeSeries.from_group_dataframe()`, the [satallion beer /sales dataset](https://www.kaggle.com/datasets/utathya/future-volume-prediction), and use `TFTModel` (currently the only one that supports static covariates.

**Comment by irenasb** [comment]
Hi everyone,
I was playing with the functionalities for static covariates in the last days while waiting for the official example :) so I created an exemplary notebook - perhaps someone is still looking for it? I have to say I am not 100% confident that this is the way it should be done (I know it's definitely not the only way), so I would be happy if someone wants to review and perhaps confirm it makes sense.
https://github.com/irenasb/darts/blob/isb/static-example/examples/15-static-covariates.ipynb
I figured one can have as an input a **list of time series**, or **one time series with multiple components**. I included both ways in the notebook. It's not so difficult to now generalize the cases to real data. If I have time I would try the Beeristan set from kaggle soon.

**Comment by dennisbader** [comment]
Hey everyone, #1081 adds some more features surrounding static covariate and also a tutorial on static covariates.
You can find the notebook [here](https://github.com/unit8co/darts/blob/feat/tft_static_categorical/examples/15-static-covariates.ipynb). Note that running the notebook requires the new branch from #1081.

Give it a read if you have time and let me know if there is anything missing to get you going with static covariates :)

@irenasb thanks a lot sharing this. It looks like you were already on the right track! My only remark would be that you don't have to add static covariates to the past or future covariates, as only static covariates embedded in the `target` series are used by the models.

**Comment by gdevos010** [comment]
Thanks for creating this! I will be back at my computer in a few days and I will look it over them.

**Comment by dennisbader** [comment]
Closing as added in #1081. You can find the notebook in the repo [here](https://github.com/unit8co/darts/blob/master/examples/15-static-covariates.ipynb) and when releasing the new darts version also in our docs' [examples section](https://unit8co.github.io/darts/examples.html).
