### ISSUE TITLE
[BUG] Darts Installation Errors on Colab

### ISSUE THREAD

**Issue by hsalkhatib** [unit8co/darts#1017]
**Describe the bug**
I tried to install the 'Darts' package on Google-Colab but its seems it has some issues. It returned warning as some the current packages are not compatible. Attached is an image of the error messages. Any suggestions?

![image](https://user-images.githubusercontent.com/24516650/174459373-554bf5be-3338-4f49-9615-f9dc8476b332.png)

**Comment by tomasvanpottelbergh** [comment]
The cause seems to be Darts' `ipython>=7.0.0` requirement. Do you think this could be lowered to `ipython>=5.5.0` (which is used by Colab) @hrzn?
In the meantime you could install Darts without the dependencies: `pip install darts --no-deps`, and install all but the IPython dependencies manually.

**Comment by hrzn** [comment]
We should test with an adaptation of the ipython dependency.
