### ISSUE TITLE
Missing base dir when loading TorchForecastingModel from different device

### ISSUE THREAD

**Issue by Kotya2001** [unit8co/darts#1022]
**Problem**
After training the model, it is saved using the save_model() function. In addition to the model itself, its meta-data is stored, to which weights, some configuration parameters and paths of the directory and the user who trained this model are stored. When trying to call a saved model from ppt.tar extension files on another local machine, an error about the absence of a path occurs, respectively. How is it possible to change the path or specify it optionally when saving parameters?

structure of direction:

    blockrnnmodel_new_ptl-ckpt.pth.tar - model parameters
    blockrnnmodel_new.pth.tar - model structure  
some code

    # load model
    model = BlockRNNModel.load_model('path to blockrnnmodel_new.pth.tar')
but here

    pred_series = model.predict(n=2, series=val, past_covariates=val_covariates)

this problem occurs: 

    OSError: [Errno 45] Operation not supported: '/home/dimot322'. 
    The above exception was the direct cause of the following exception. where '/home/dimot322' is not my directory.
    And, in the result: ValueError: you tried to log -1 which is currently not supported. Try a dict or a scalar/tensor.

**Idea**
I tried to change the location path to relative manually, but maybe there is some parameter in the save_model function that a file was formed in advance and dynamically, where the paths will be relative to the folder where the model is saved.

**Expected behavior**
It will be possible to set paths independently or form them relative to the working directory.

**System settings**
 - Python version: 3.7
 - darts version 0.19.0

**Comment by dennisbader** [comment]
Could you try following the steps described in #925?
