### ISSUE TITLE
How can I load data with custom data loaders and accelerators during training ?

### ISSUE THREAD

**Issue by shamanez** [unit8co/darts#1026]
I have very large dataset and I can't use pandas . Is there any way that I can use a custom dataloader and update the training loop. 

I would also like to know can I  customize the GPU training, with something like PyTorch-lightning ?

Thanks a lot.

**Comment by hrzn** [comment]
> I have very large dataset and I can't use pandas . Is there any way that I can use a custom dataloader and update the training loop.

Yes you can, at least for neural networks. The `fit()` function expects a Python `Sequence` of `TimeSeries`. So you can do something like this:
```python
class MySeq(Sequence):
    ...
    def __getitem__(i):
        # read data from disk for the i-th series
        # build and return the i-th TimeSeries object
    def __len__():
        # return total number of series
        
my_series_seq = MySeq(...)

my_model.fit(my_series_seq)
```

> I would also like to know can I customize the GPU training, with something like PyTorch-lightning ?

Yes you can. Refer for instance to the [user guide](https://unit8co.github.io/darts/userguide/gpu_and_tpu_usage.html).

**Comment by hrzn** [comment]
> Thanks a lot. So basically I can pass a custom data loader to the fit function right ?

Yes, as shown in my example, you can pass any custom `Sequence` implementation as a data loader.
