### ISSUE TITLE
[Question] Can forecasting functions generate numbers beyond float64 if input TimeSeries is float64?

### ISSUE THREAD

**Issue by marduk2** [unit8co/darts#1033]
I am feeding darts several TimeSeries with very large numbers but still (barely) within float64 format. **In this scenario, can any darts forecasting model/function generate a number that is beyond float64 format? Is there something to limit or prevent this, or at least to warn the user that an output is in a different numeric format?** I have been scanning the code but can't seem to find anything.

Thanks in advance (also for the latest release - brilliant!)

**Comment by hrzn** [comment]
Hi @marduk2 and thanks!
It is in principles possible yes, and that would cause overflow errors and most likely give you some NaNs in the forecasts. There's no explicit checks for this. If I were you I would investigate options to scale the time series differently, as it sounds you are in a dangerous position with such scales.

**Comment by marduk2** [comment]
Understood, thanks for the advice @hrzn !
