### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by salsa360** [unit8co/darts#1037]
**Describe the bug**
When running ARIMA, I get an error message - TypeError: __new__() got an unexpected keyword argument 'p'.

**To Reproduce**
model_arima = ARIMA(p=0, d=2, q=2)

model_arima.fit(train)
prediction_arima = model_arima.predict(len(val))

**System (please complete the following information):**
 - darts==0.8.1
 - The system version is 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]

**Comment by hrzn** [comment]
Could you update Darts doing
pip install -U darts

**Comment by salsa360** [comment]
I updated Darts as suggested but the same issue persists even with running DARTS in Google Colab.

**Comment by hrzn** [comment]
Could you then provide a fully self-contained code snippet to reproduce the issue, as well as the full stacktrace of the error you obtain?
Are you sure the `ARIMA` symbol is really the Darts model and not another import?

**Comment by salsa360** [comment]
Hi Julien,

Thanks for responding.

Attached is my ipynb file and input date file.  Listed below are the error
messages I am getting.


*ERROR MESSAGE 1*

ImportError                               Traceback (most recent call last)

<ipython-input-1-300c28dd0c71> <https://localhost:8080/#> in <module>
   14      15 from darts import TimeSeries
---> 16 from darts.models import (     17     NBEATSModel,     18     TCNModel,


ImportError: cannot import name 'Prophet' from 'darts.models'
(/usr/local/lib/python3.7/dist-packages/darts/models/__init__.py)




*ERROR MESSAGE 2*

model_arima = ARIMA(p = ARIMA_results1.get_params().get("order")[0],
                    d = ARIMA_results1.get_params().get("order")[1],
                    q = ARIMA_results1.get_params().get("order")[2],
                    trend='ct'
                   )

model_arima.fit(train)
prediction_arima = model_arima.predict(len(val))

series.plot(label='Actual')
prediction_arima.plot(label='ARIMA Forecasting', lw=2)
plt.legend()
plt.show()

print("Coefficient of Variation for ARIMA: {:.1f}%.".format
(coefficient_of_variation(val, prediction_arima))) # CoV (% Error)
print("Mean Absolute Scaled Error for ARIMA: {:.1f}%.".format
(mase(val, prediction_arima, train)))            # MASE


TypeError                                 Traceback (most recent call last)

<ipython-input-96-fe87dec8094d> in <module>      4
d = ARIMA_results1.get_params().get("order")[1],      5
     q = ARIMA_results1.get_params().get("order")[2],
----> 6                     trend='ct'      7                    )      8

TypeError: __init__() got an unexpected keyword argument 'p'



Thank you.


Regards
Kushwant
