### ISSUE TITLE
[QUESTION] Filter a time series based on time of the day

### ISSUE THREAD

**Issue by pamparana34** [unit8co/darts#1043]
Is there an easy way to filter a time series object to extract the values only within a specified hours in the day. So, I have a time series spanning a few months and I would only like to compute metrics and plot the predictions for specific times of the day (5 PM to 5 AM for example).

I am having trouble figuring out how to create the subset time series.

**EDIT**
So, I can do something like:

```
from darts.utils.timeseries_generation import constant_timeseries
x = constant_timeseries(length=10)
idx = x.time_index > pd.Timestamp("2000-01-02")
```

Now, this `idx` is a boolean array and now I want to filter the time series based on these indexes but doing something like:

```
x[idx] 
```
results in: `IndexError: The type of your index was not matched.`

**Comment by hrzn** [comment]
You can try `x[idx]` with `idx` being a `DatetimeIndex` containing the timestamps of your choice. In this case I think `idx` is simply an array which is why it doesn't work.
