### ISSUE TITLE
past_covariate_lag is not dynamic for different spots in the forecast horizon for tree-based-regressors

### ISSUE THREAD

**Issue by kyleke1998** [unit8co/darts#1050]
This is the code I ran to forecast 7 days ahead using lag 7, lag 8, and lag 9 of my past covariates [prev_cnt', 'days_since_replen']
![image](https://user-images.githubusercontent.com/64662601/176527761-4d811fa1-5ea3-430b-97a4-f845e3291174.png)

This works. I am assuming at each recursive time step, it is using the respective lags 7,8, and 9 like this:

![image](https://user-images.githubusercontent.com/64662601/176529660-45eaf714-65f3-4eec-bda8-4114e8ade89a.png)

However, I really would like the first day forecast Nov 23 2021 to be able to use past_covariate_lags 1 and 2 with respect to that date, and the second day forecast Nov 24 2021 to be able to use past_covariate_lags 2 and 3 with respect to that date.

Is it possible to change the Recursive multi-step forecasting wrapper to support more dynamic past_covariate_lags like described above?

**Comment by hrzn** [comment]
Hi, I'm not sure I completely understand your question, are you trying to dynamically adapt the lags being used as a function of the timestamp being predicted?

**Comment by kyleke1998** [comment]
> Hi, I'm not sure I completely understand your question, are you trying to dynamically adapt the lags being used as a function of the timestamp being predicted?

Yes, that is what I mean

**Comment by hrzn** [comment]
This is currently not possible. We might add a feature like this at some point in the future, but that would be a long-term thing, and we would need a strong reason to do it. I'll close it for now.
