### ISSUE TITLE
Solve train/load issues with PTL: persisting training independently of paths, training on GPU, loading on CPU, etc.

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1068]
Do not resort always to torch.save(), rather save state_dict.

**Comment by hrzn** [comment]
@dennisbader could we close this one?

**Comment by dennisbader** [comment]
Yes, we solved:
- saving on GPU, loading on CPU
- avoid saving model twice (once the entire TorchForecastingModel) and once through trainer checkpoint
- loading weights only
