### ISSUE TITLE
[BUG] Wrong parameter name in TimeSeries.concatenate: ignore_time_axes

### ISSUE THREAD

**Issue by thomktz** [unit8co/darts#1072]
**Describe the bug**
TimeSeries.concatenate has a `ignore_time_axes` parameter.
Yet, error messages indicate to `ignore_time_axis`.
This is because ___main__.concatenate() does have a 'ignore_time_axis' parameter

**To Reproduce**
Not really a need for reproductability since everything can be found in the source code

Calling TimeSeries.concatenate(*args, **kwargs) can yield 
ValueError: When concatenating along component or sample dimensions, all the series must have the same time axes (unless `**ignore_time_axis**` is True), or time axes of same lengths (if `**ignore_time_axis**` is True), and all series must have the same number of samples (if concatenating along component dimension), or the same number of components (if concatenating along sample dimension).

But TimeSeries.concatenate does not have a `ignore_time_axis` argument.

**Expected behavior**
Renaming all `ignore_time_axes` to `ignore_time_axis` in TimeSeries.concatenate()

**System (please complete the following information):**
 - Python version: 3.9.2
 - darts version 0.20.0

**Comment by hrzn** [comment]
Good catch, thanks. Would you be willing to make a contribution to fix it?
