### ISSUE TITLE
Darts.datasets.dataset_loaders.DatasetLoadingException: Could not download the dataset. Reason:SSLError

### ISSUE THREAD

**Issue by mazhaojing** [unit8co/darts#1077]
question:
darts.datasets.dataset_loaders.DatasetLoadingException: Could not download the dataset. Reason:SSLError(MaxRetryError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /unit8co/darts/master/datasets/ice_cream_heater.csv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"))

In the TFT example, downloading the dataset of ice cream fails.How should I solve this problem,thanks.

**Comment by LISANXING** [comment]
我也遇到了同样的问题，请问你如何解决的
