### ISSUE TITLE
PyData talk 

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#1078]
**Is your feature request related to a current problem? Please describe.**
This recent PyData talk goes though time series features engineering and shoes how to implement them in darts. Do we want to add the link to the readme?

https://youtu.be/9QtL7m3YS9I

**Comment by hrzn** [comment]
Great talk, I wasn't aware. Thanks for linking! I would not put it in the readme as it's not about Darts per-se, but we could maybe setup another page referencing useful resources at some point. For now I would rather have us improve our docs, and (when we find the time) release another tutorial video :)
