### ISSUE TITLE
"one-shot" RegressionModels

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1080]
Currently, our RegressionModels will create `k` internal models when `output_chunk_length=k`. This can scale poorly for larger values of `k`. 

Another option, which (AFAIK) is often used in Kaggle competitions, is to train only one model, taking as input features that can all be computed at least `k` time steps in advance such as:
* Sufficiently old lags
* Sufficiently old window features
* Future covariates

Pros:
* Seems to work very well in many cases (often relying on good future covariates capturing time axis too)
* Scales very well

Cons:
* Cannot access recent lags, but this does not always matter

It'd be nice to provide such an option in Darts. It could be either an option in `RegressionModel`, or potentially a new kind of `RegressionModel` altogether.

It might be nice to couple it with adding `encoders` for RegressionModels, which could dynamically create the future covariates (e.g., time axis features) on the fly.

**Comment by benitocm** [comment]
Please, could you elaborate a bit more por provide a link to a kaggle example?
