### ISSUE TITLE
About "TimeSeries.from_dataframe"

### ISSUE THREAD

**Issue by spytensor** [unit8co/darts#1084]
My code :
```python
series = TimeSeries.from_dataframe(data,
                                   time_col="time",
                                   freq="B",
                                   fill_missing_dates=False,
                                   value_cols=['open', 'high', 'low', 'close', 'volume', 'label', 'timeoftime'])
```
my freq like: 
```python
2016-01-04 11:00:00, 1
2016-01-04 11:30:00, 2
2016-01-05 13:00:00, 3
2016-01-05 13:30:00, 4
```
But this is correct, and after I use TimeSeries.from_dataframe, it will fill missing dates any
way, and get values as bellow. So anyone knows how to fill it?
```python
2016-01-04 11:00:00, 1
2016-01-04 11:30:00, 2
2016-01-04 12:00:00, nan
2016-01-04 12:30:00, nan
2016-01-05 13:00:00, 3
2016-01-05 13:30:00, 4
```

**Comment by dennisbader** [comment]
Have a look at [MissingValuesFiller](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html#darts.dataprocessing.transformers.missing_values_filler.MissingValuesFiller) :)
