### ISSUE TITLE
Unable to use darts on Azure Machine Learning

### ISSUE THREAD

**Issue by HonglingLei** [unit8co/darts#1085]
Dear darts development team,

Thank you for creating such a convenient and powerful tool. I tried to use it on Azure ML but running "from darts.models import NBEATSModel" (or any other model in darts) always crashed my kernel. 

![image](https://user-images.githubusercontent.com/47043780/179527441-8ff30b7d-37d7-4766-ac4c-802ca838b153.png)

Installing the package and even importing darts.datasets worked fine. I tried a larger compute with a 56G-RAM GPU but it still crashed. However, I was able to use darts on Google Colab without error. 

I wonder if there's some compatibility issue between darts and Azure ML... If so, solving this issue can benefit lots of people because Azure ML is a common enterprise computing platform.

Looking forward to any help/advice. Thank you so much!

**Comment by hrzn** [comment]
Hi, this is quite strange, as there should be nothing specific to Darts restraining it to work on Azure ML. Do you have a way to retrieve more details about the error? Maybe your environment, even if running on a large VM, doesn't have access to enough memory for some reason (e.g. if running inside a container)?

**Comment by HonglingLei** [comment]
Thank you for the quick response! This is very helpful. I will look into the details as you suggested and try to figure out why:)
