### ISSUE TITLE
Using torch models or custom deep learning structures in darts

### ISSUE THREAD

**Issue by Hatermal** [unit8co/darts#1087]
Hi, 

I'm not sure if this is the correct place for this question: but I was wondering if it's possible to use custom made pytorch models in Darts, and how? 

My reason for asking is that I am looking into transfer learning and want to be able to freeze specific layers of my model. I'm not sure how to combine several deep learning structures into one module using only the darts forecasting models. I know there's the method .requires_grad_() just like in pytorch but I have been unsuccessful so far in applying this to a darts model structure. 

What I want to do, for example is:
- RNN
- Fully connected layer
-> Freeze RNN

Is this possible with Darts?

**Comment by hrzn** [comment]
Hi, yes it should be possible. You'd have to write your own model inheriting from `TorchForecastingModel`. I would recommend you take a look at the implementations e.g., of [RNNs](https://github.com/unit8co/darts/blob/master/darts/models/forecasting/rnn_model.py) or [N-BEATS](https://github.com/unit8co/darts/blob/master/darts/models/forecasting/nbeats.py).

**Comment by hrzn** [comment]
I'll close this issue for now, please re-open if needed.
