### ISSUE TITLE
[BUG] TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by hemantnyadav** [unit8co/darts#1091]
**Describe the bug**
When importing "from darts import TimeSeries" it gives error.

TypeError           Traceback (most recent call last) in <module>
      7 import matplotlib.pyplot as plt
     9 from darts import TimeSeries
     10 from darts.datasets import AirPassengersDataset frames

     19 with open(fn) as f:
---> 20     defaults = yaml.load(f)
     21 
     22 dask.config.update_defaults(defaults)

TypeError: load() missing 1 required positional argument: 'Loader'

**To Reproduce**
Open google colab
!pip install darts
from darts import TimeSeries

**Expected behavior**
It should import from darts import TimeSeries

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.14.0]

**Additional context**

**Comment by tk42** [comment]
Hi! @hemantnyadav. This error is caused by an incompatible pyyaml on Colab.
The quickest workaround is
```
!pip install pyyaml==5.4.1
```
For more details, [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation)
