### ISSUE TITLE
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class]

### ISSUE THREAD

**Issue by Mosw5871** [unit8co/darts#1092]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

**Expected behavior**

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.14.0]

**Additional context**

**Comment by mylesholley888** [comment]
Describe the bug:
Get this error message when trying to import pyspedas and pytplot:
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class

To Reproduce
`import pyspedas
from pytplot import tplot`

Expected behavior
Expected it to import without a hitch

System (please complete the following information):

Python version: [JupyterLab: Version 3.2.1]

Additional context:
Want to import data from MMS mission

**Comment by mylesholley888** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior, preferably code snippet.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **System (please complete the following information):**
> 
> * Python version: [e.g. 3.7]
> * darts version [e.g. 0.14.0]
> 
> **Additional context** Add any other context about the problem here.

Describe the bug:
Get this error message when trying to import pyspedas and pytplot:
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class

To Reproduce
import pyspedas from pytplot import tplot

Expected behavior
Expected it to import without a hitch

System (please complete the following information):

Python version: [JupyterLab: Version 3.2.1]

Additional context:
Want to import data from MMS mission

**Comment by OmarHory** [comment]
Same issue. Can't use darts.

**Comment by OmarHory** [comment]
![image](https://user-images.githubusercontent.com/43903002/180647945-eb304330-5008-4b2f-ae4a-5bac15576aa1.png)

The problem appears to be from **xarray**, as xarray have updated their package as in https://pypi.org/project/xarray/#history

**Comment by mylesholley888** [comment]
> ![image](https://user-images.githubusercontent.com/43903002/180647945-eb304330-5008-4b2f-ae4a-5bac15576aa1.png)
> 
> The problem appears to be from **xarray**, as xarray have updated their package as in https://pypi.org/project/xarray/#history

To resolve the issue did you just download the uodates package?

**Comment by mylesholley888** [comment]
Attempted to update but I already have latest version of xarray:
I ran this:
!pip install --upgrade xarray

And got this output:
Requirement already satisfied: xarray in ./opt/anaconda3/lib/python3.9/site-packages (2022.6.0)

**Comment by OmarHory** [comment]
> Attempted to update but I already have latest version of xarray:
> 
> I ran this:
> 
> !pip install --upgrade xarray
> 
> 
> 
> And got this output:
> 
> Requirement already satisfied: xarray in ./opt/anaconda3/lib/python3.9/site-packages (2022.6.0)
> 
> 

The problem is still not resolved, I have been trying out with the packages ever since without promising results.
I installed Darts 0.8.0 and the import worked but there are a lot of functionalities that I need in which do not exist like the BlockRNN and the covariates.

**Comment by mylesholley888** [comment]
> > Attempted to update but I already have latest version of xarray:
> > I ran this:
> > !pip install --upgrade xarray
> > And got this output:
> > Requirement already satisfied: xarray in ./opt/anaconda3/lib/python3.9/site-packages (2022.6.0)
> 
> The problem is still not resolved, I have been trying out with the packages ever since without promising results. I installed Darts 0.8.0 and the import worked but there are a lot of functionalities that I need in which do not exist like the BlockRNN and the covariates.

Yea I'm in the same boat:
`import pyspedas
from pytplot import tplot`

Resulted in a new error:
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class

**Comment by hrzn** [comment]
Hi, I'm not sure how to reproduce, and whether this is an issue with Darts.
`import pyspedas from pytplot import tplot` is not a valid command. Could you please let us know how to reproduce the issue?

**Comment by OmarHory** [comment]
`pip install xarray==0.20.2` 
Worked for me, today is a good day.

**Comment by mylesholley888** [comment]
> Hi, I'm not sure how to reproduce, and whether this is an issue with Darts. `import pyspedas from pytplot import tplot` is not a valid command. Could you please let us know how to reproduce the issue?

Really? I am new to this.
I was following the documentation here:
https://github.com/spedas/mms-examples/blob/master/webinars/Analyzing_MMS_Data_with_pySPEDAS_1Dec2021.ipynb

**Comment by mylesholley888** [comment]
> pip install xarray==0.20.2
This worked for me too! Thank you so much!

**Comment by Attol8** [comment]
> `pip install xarray==0.20.2` Worked for me, today is a good day.

I have run into the same issue and this comment from @OmarHory worked for me too

**Comment by Mosw5871** [comment]
OH! GOD! Do you konw how I sloved this problem? I Reset my Mac! 555555. Everything is gone, so I can have a new start!

**Comment by benoit-cty** [comment]
Thanks for the workaroud, here is the issue in xarray https://github.com/pydata/xarray/issues/6818.

**Comment by hrzn** [comment]
Hi, is any
