### ISSUE TITLE
[BUG] Scaler fitted on multivariate series can't be reverted on univariate subset

### ISSUE THREAD

**Issue by zora-no** [unit8co/darts#1096]
I have a multivariate time series with 5 components that I specified a scaler for. The docs say "When the scaler is applied on multivariate series, the scaling is done per-component."

After fitting a univariate model to one component of the scaled series, I want to revert the scaling. The component has the same name as in the multivariate series. I expected this to work since the scaler works per-component. However, I get the error "non-broadcastable output operand with shape (13,1) doesn't match the broadcast shape (13,5)".

**Comment by dennisbader** [comment]
The dimensions of the series you used to fit the scaler must be the same as the dimensions of the series you want to transform.

Per component here means that each of the 5 components will be fit/transformed independently.

So when fitting the sclaer on a 5 component series you can only transform series with 5 components.

**Comment by twobitunicorn** [comment]
@dennisbader Is there a way to do the transformation on the 5 components and then select which columns of the timeseries  we want to inverse transform?  Lets say I have two components `a` and `b` in my timeseries `t`.  I would love to do the transformation on the `t` and then when I get a prediction out of a model, specifically for `b` it would be rad if I could do something like `scaler.inverse_transform(t, on_columns=["b"])`.  Is this possible to do?

**Comment by jdonzallaz** [comment]
Hi, any update on this ? The use-case presented by @twobitunicorn is very common.

I have the same problem. I want to apply the scaler on the target and its covariates, and only `inverse_transform` on the prediction. I couldn't find a clean way of doing this right now.
