### ISSUE TITLE
Question: Is there an API to update a fitted/trained model with new data?

### ISSUE THREAD

**Issue by vincetran96** [unit8co/darts#1100]
Thank you for creating this project. I'm considering using it for our organization. One question that rose from the consideration is whether Darts has an API to save fitted/trained models and also update them with new data? I have looked at the User Guide and API Reference pages in the main documentation page and found no mentioning about such an API.

**Comment by hrzn** [comment]
Hi, thanks for the feedback!
Yes, Darts supports updating models with new data - by simply calling `fit()` again. That's for deep learning models; the other models don't support this "partial training" modes. It should also work with models that have been previously saved.
In addition, we are working on generic save/load methods (you can follow it here: https://github.com/unit8co/darts/pull/1070)

**Comment by vincetran96** [comment]
Thank you @hrzn for the quick response! In the meantime, if we train a model and want to store it to use later, do you suggest us to simply use `joblib` or `pickle` to save it?

**Comment by hrzn** [comment]
I'm closing for now - feel free to re-open if you have more questions.
