### ISSUE TITLE
Implement min_train_series_length() method for the FourTheta model

### ISSUE THREAD

**Issue by rijkvandermeulen** [unit8co/darts#1101]
**Is your feature request related to a current problem? Please describe.**
The FourTheta model extends the ForecastingModel class which has a class property defining the minimum required length for the training series (min_train_series_length). This property defautlts to 3 but can be overriden for each child class inherenting from ForecastingModel . Now, I'm missing the method that overrides this min_train_series_length in the case of the FourTheta model. I'm pretty sure the Theta model requires at least 2 * seasonality_period in case seasonality is used (i.e. season_mode != SeasonalityMode.NONE).

When you currently try to fit a seasonal FourTheta model when you have < 2*seasonality_period observations, it errors out when it tries to do a seasonal_decomposition in extract_trend_and_seasonality(). Would it be an idea to already capture this in an earlier stage by implementing the min_train_series_length() method 

**Describe proposed solution**
Implement min_train_series_length() method for the FourTheta model overwriting the default of 3. Something like: 

`
        if self.season_mode.value:
            return self.seasonality_period * 2
        else:
            return 3
`
Might be a bit more nuance to the abovementioned solution since seasonality_period is an optional param and can also be retrieved from the time series. Hence, if seasonality_period=None we need to first retrieve the seasonality_period.

**Describe potential alternatives**

**Additional context**

**Comment by hrzn** [comment]
Thanks, that makes sense. Would you be willing to open a PR with this change?

**Comment by rijkvandermeulen** [comment]
Sure, let me give that a try!
