### ISSUE TITLE
[BUG] / Question Cannot Use Prophet Despite Installing it separately

### ISSUE THREAD

**Issue by ArchanGhosh** [unit8co/darts#1102]
After seeing the new method to use prophet I had tried the same on Google Colab, but I am still getting an error as 

"Darts Module has no instance name Prophet"

I did:
!pip install darts
followed by
!pip install prophet  alternatively I also tried python -m pip install prophet 

but it didn't work either way.

If someone can help me that would be great as where I am going wrong.

**Comment by dennisbader** [comment]
How did import prophet? this is the correct way:
```
from darts.models import Prophet
```

**Comment by ArchanGhosh** [comment]
Yes I did. the problem I guess is solved, because I had to first install prophet followed by darts and it worked. On the other hand when I installed Darts and then Prophet it was not working at all.
