### ISSUE TITLE
Croston Forecaster needs extra argument "fitted" [BUG]

### ISSUE THREAD

**Issue by JensvandeZande** [unit8co/darts#1104]
**Describe the bug**
When trying to fit a Croston Forecaster it returns a TypeError: not enough arguments: expected 4, got 3

**To Reproduce**
```python
from darts.datasets import AirPassengersDataset
from darts.models import Croston

passengers = AirPassengersDataset()
y = passengers.load()

train = y[:-12]
val = y[-12:]

model = Croston()
model.fit(train)
```

**Expected behavior**
A fitted model without errors

**System (please complete the following information):**
 - Python version: [3.19.13]
 - darts version [0.20.0]

**Comment by hrzn** [comment]
I just tried and for me it works:
![image](https://user-images.githubusercontent.com/4806678/181989767-ee1b6256-ae80-49bc-8b3e-df9eddaef1de.png)

Could you try again in a blank virtual environment?

**Comment by dennisbader** [comment]
@JensvandeZande , statsforecasting released a new version with some breaking changes. 

Try downgrading the package to see uf ut fixes the issue:

```
pip install --upgrade statsforecast==0.6.0
```
