### ISSUE TITLE
backfill, forwardfill for missing values

### ISSUE THREAD

**Issue by OmarHory** [unit8co/darts#1107]
Is there any feature for backfill and forwardfill for `fill_missing_values` from the `utils`, or by `TimeSeries.from_dataframe` ?
The default for the fill value is the pd.interpolate, and I would like to have backfill as the filling function.

Darts version: 0.20.0

**Comment by hrzn** [comment]
You can do it with `fill_missing_values()` by specifying the same kwargs you'd provide to `DataFrame.interpolate()`.

Example
```python
import numpy as np
from darts import TimeSeries
from darts.utils.missing_values import fill_missing_values

values = np.array([0.5, np.nan, np.nan, 1])
series = TimeSeries.from_values(values)
new_series = fill_missing_values(series, method="bfill", limit_direction="backward")
```

**Comment by OmarHory** [comment]
Thanks a lot!
Sorry for being a newbie.
