### ISSUE TITLE
Can't use Early Stopping with GridSearch

### ISSUE THREAD

**Issue by OmarHory** [unit8co/darts#1108]
I am trying to Use Early Stopping in NBEATS GridSearch:

![image](https://user-images.githubusercontent.com/43903002/182029446-cff8cc63-4204-4ff5-8472-3721b9bb19d3.png)

![image](https://user-images.githubusercontent.com/43903002/182029487-c8308e31-26b1-4a77-a23b-16fec7d9b1e3.png)

This is the error:
`__deepcopy__() takes 1 positional argument but 2 were given`

Is this possible or am I missing anything?

Darts Version: 0.20.0

**Comment by hrzn** [comment]
gridsearch is very naive in Darts, and does not support early stopping. Checkout [this example](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#hyperparameter-tuning-with-ray-tune) for an example using Ray Tune with early stopping for hyper-parameter optimization.

**Comment by OmarHory** [comment]
Kindly check this implementation of NBEATS using HyperOpt, uploaded the snippets on CodePile:

[https://www.codepile.net/pile/Kz9Ld6Vn?s=0](url)

I have tested it and works really well on my end.
