### ISSUE TITLE
Just a small typo

### ISSUE THREAD

**Issue by blacksnail789521** [unit8co/darts#1115]
https://github.com/unit8co/darts/blob/caccce1dc71f58180142d96e70bf06024d68798f/darts/timeseries.py#L652

It would be 

> ValueError: If time_col is not specified, the DataFrame must be indexed either witha DatetimeIndex, or with a RangeIndex.

, which `witha` should be `with a`.

**Comment by hrzn** [comment]
Thank you, could you transform this into a PR directly?
