### ISSUE TITLE
[BUG] Trouble installing on MacOS

### ISSUE THREAD

**Issue by Dekermanjian** [unit8co/darts#1117]
**Describe the bug**
I have followed the installation instructions and can not install darts on MacOS M1 chip.

**To Reproduce**
Follow the current installation instructions for a clean Conda virtual env. However `conda install -c conda-forge -c pytorch u8darts-all` does not work. So I had to install using `pip install darts` instead.

**Expected behavior**
After following the installation requirements darts will be properly installed.

**System (please complete the following information):**
 - Python version: 3.8
 - darts version 0.20.0

**Additional context**
I keep getting an OSerror when trying to import any darts model. The following is the error message that I get when trying to import any darts model:

`OSError: dlopen(/Users/dekermanjian/opt/anaconda3/envs/darts/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/dekermanjian/opt/anaconda3/envs/darts/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)`

I have followed the installation instructions and ran: 

`wget https://raw.githubusercontent.com/Homebrew/homebrew-core/fb8323f2b170bd4ae97e1bac9bf3e2983af3fdb0/Formula/libomp.rb
brew unlink libomp
brew install libomp.rb`

This does not resolve the error.

I have also tried installing LightGBM using `brew install lightgbm` but still this does not resolve the error. 

Any assistance would be appreciated. Thank you.

**Comment by Dekermanjian** [comment]
I was able to get this installed correctly. You need to install it using Conda. The problem is that it takes around 25 minutes on a clean environment for it to solve the environment. Is this typical?

**Comment by hrzn** [comment]
25 minutes sounds too long to install Darts with Conda, however if that's a one time issue I would close it for now. Let's re-open if other people observe similar issues.

**Comment by Dekermanjian** [comment]
Yes, 25 minutes is too long. I can confirm that this is not an issue on Windows OS, though.

**Comment by eirikbaekkelund** [comment]
I'm having the same trouble with MacOS with M1 Chip. Have also gone through all the steps of installing lightgbm with brew and creating a symlink to try and find it. Still facing the issue (this is through pip install as conda is taking forever)
