### ISSUE TITLE
[BUG] multiple timeseries

### ISSUE THREAD

**Issue by mandar-avhad** [unit8co/darts#1122]
HI, I'm working with multiple timeseries data.
I want to perform tuning on this data to find and apply best parameters on it.

Can you please suggest a way to do this?
As gridsearch is not possible for multiple ts, is there any other way?

Thanks!

**Comment by gdevos010** [comment]
you can use Ray Tune. Heres a simple example  https://github.com/unit8co/darts/blob/master/docs/userguide/torch_forecasting_models.md#hyperparameter-tuning-with-ray-tune

**Comment by hrzn** [comment]
Thanks - I'm closing (and removing the "bug" label ;)
