### ISSUE TITLE
[BUG] Multiple timeseries: Size of train dataset grows exponentially

### ISSUE THREAD

**Issue by Hatermal** [unit8co/darts#1123]
**Describe the bug**
I include a dataset with 52k samples and one with 4.4k samples. When I fit the model it says that I now have 105k samples to train on. If i include another dataset of 4.4k samples: 157k samples to train on. Dataset 1 is from 2012 to 2018, dataset 2 is from 2019 to 2020.

**Code snippet:**

```
diverse_model = BlockRNNModel(
    input_chunk_length=24,
    output_chunk_length=24,
    ...
)
```

`[train_transformed_short,train_transformedO6M1Y]`

```
[<TimeSeries (DataArray) (time: 52609, component: 1, sample: 1)>
 array([[[0.]],
 
        [[0.]],
 
        [[0.]],
 
        ...,
 
        [[0.]],
 
        [[0.]],
 
        [[0.]]], dtype=float32)
 Coordinates:
   * time       (time) datetime64[ns] 2012-01-01T00:11:00 ... 2018-01-01T00:11:00
   * component  (component) object 'P'
 Dimensions without coordinates: sample
 Attributes:
     static_covariates:  None
     hierarchy:          None,
 <TimeSeries (DataArray) (time: 4416, component: 1, sample: 1)>
 array([[[0.]],
 
        [[0.]],
 
        [[0.]],
 
        ...,
 
        [[0.]],
 
        [[0.]],
 
        [[0.]]], dtype=float32)
 Coordinates:
   * time       (time) datetime64[ns] 2019-07-01T01:00:00 ... 2020-01-01
   * component  (component) object 'P'
 Dimensions without coordinates: sample
 Attributes:
     static_covariates:  None
     hierarchy:          None]
```

`diverse_model.fit(
    [train_transformed_short,train_transformedO6M1Y],
    val_series=[test_transformed_short, test_transformedO6M1Y],
    verbose=True,
)`

_2022-08-05 17:02:09 darts.models.forecasting.torch_forecasting_model INFO: Train dataset contains 105124 samples._

**Expected behavior**
Sample size should be 56.4k samples

**System (please complete the following information):**
Python 3.9.12
Darts 0.20.0

**Comment by dennisbader** [comment]
Have a look at [this section](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#top-level-look-at-training-and-predicting-with-chunks) from our user guide which explains how one sample is extracted from your input data.

Each of your target series is split into sub sequences (samples) with an input chunk of length `input_chunk_length` (and output chunk of length `output_chunk_length`).

Hope it helps.

**Comment by hrzn** [comment]
Here by "dataset" I think you refer a single time series. Darts models can be trained on multiple time series of different lengths, and they will each be split in a set of input/output sub-sequences (as pointed out by @dennisbader) to produce the actual training dataset used to train the model. You can set the `max_samples_per_ts=N` when calling `fit()` if you want to limit the size of this training set to only the last `N` input/output sequences in each time series. I'm closing the issue for now, assuming that answers the question

**Comment by Hatermal** [comment]
Hi both,

Yes, this does answer the question. Thanks for explaining, feel free to close!
