### ISSUE TITLE
Simplify install flavours

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1133]
One possibility would be:
* `u8darts` --> core (i.e., without pytorch)
* `u8darts[all]` --> all (i.e., with pytorch)

Shall we drop `u8darts[torch]` ?

**Comment by dennisbader** [comment]
I guess we can give it a try and if we get too many complaints, we can still revert?

**Comment by hrzn** [comment]
I'm thinking of maybe keeping `u8darts[torch]` as an "alias" for at least a bit of time but mentioning in the documentation that it is deprecated. WDYT?

**Comment by hrzn** [comment]
`u8darts[torch]` is kept for the time being
