### ISSUE TITLE
Generate hierarchy automatically in `from_group_dataframe()`

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1135]

**Comment by madtoinou** [comment]
I started working on this new feature and would like to discuss the specification just to make sure I understood the idea correctly. From my understanding, the user would provide a `pd.DataFrame` in long format (redundant values in the timestamps, ideally overlapping) and grouping columns, which should correspond to columns containing categorical information that would allow to identify the various sub-timeseries (outputs of the`df.groupby` method). The columns affected by the hierarchical relationship are assumed to be all the columns except the static and the grouping columns.

From this situation, several scenario are possible:
- there is hierarchy inside each sub-timeserie. the corresponding total column can be provided (strict or weak hierarchy) or computed from the sub-timeserie columns (resulting in a strict hierarchy)
- there is hierarchy across the sub-timeseries as well, which can be computed from the total column mentioned above or that could eventually be provided by the user (kind of unlikely in my opinion if the input is in long format, as it would require some data-preprocessing by the user, who could probably have obtained the `TimeSeries` using another factory method more easily).
- there is hierarchy between somes of the sub-timeseries, which cannot be automatically computed unless the users gives some additional information.

The output would be a single `TimeSeries`, made out of the `pd.DataFrame` pivoted into wide format, with a hierarchy attribute liking some of its columns (in opposition to the current output, which is a list of `TimeSeries`, one per `pd.GroupBy` object)

What is your opinion/expectation for this feature?

**Comment by hrzn** [comment]
As discussed, let's park this one for now. Not sure it makes sense.
