### ISSUE TITLE
How to add hierarchy to TimeSeries results in error

### ISSUE THREAD

**Issue by Dekermanjian** [unit8co/darts#1137]
**Is your feature request related to a current problem? Please describe.**
Could not find documented example on how to add hierarchy to TimeSeries object

**Describe proposed solution**
Provide a small example on how to achieve the hierarchy

**Describe potential alternatives**
unknown

**Additional context**
Here is a reproducible example:
```
import pandas as pd
import numpy as np
from darts import TimeSeries
time1 = pd.date_range('2022-07-03', '2022-08-01', freq='d')
time2 = pd.date_range('2022-07-03', '2022-08-01', freq='d')
group1 = np.repeat(['a', 'b', 'c'], 10)
group2 = np.repeat(['d', 'e', 'f'], 10)
value = np.arange(0, 60)*np.random.rand()
df = pd.DataFrame({'Time':time1.tolist() + time2.tolist(), 'Group':group1.tolist() + group2.tolist(), 'Value':value})
```

I want to add the Group variable in df as a level 1 hierarchy that should reconcile to the total. I am able to construct a TimeSeries object using the `from_group_dataframe()` method, however that does not allow you to set a hierarchy. If I try to use the `from_dataframe()` method I receive a value error because I have the same date for multiple groups ie. non-unique index. What is the proper way to do this?

**Comment by dennisbader** [comment]
We are working on an example and user guide section for hierarchical reconciliation in #1059.
Stay tuned!
