### ISSUE TITLE
Unable to load TFT model with Gaussian loss

### ISSUE THREAD

**Issue by AakarSharmaHME** [unit8co/darts#1151]
**Describe the bug**
I have created a TFT model with GaussianLikelihood loss. When I am trying to load the checkpoint using this command.
```
model = TransformerModel.load_from_checkpoint(f'tft-322-food-hpo-lstm-{lstm_layers}-hidden-{hidden_size}-attention-{num_attention_heads}')
```
I am getting this error.
```
__init__() missing 1 required positional argument: 'categorical_embedding_sizes'
```
This is working fine with QuantileLikelihood Loss.

**To Reproduce**
Create any TFT model with GaussianLikelihood loss, save checkpoints. Once trained, try to load the saved checkpoints.

**Expected behavior**
The model should load exactly like happening with QuantileLikelihood loss.

**System (please complete the following information):**
 - Python version: [e.g. 3.8]
 - darts version [e.g. 0.21.0]

**Comment by dennisbader** [comment]
You are loading a TransformerModel, not a TFTModel.

Try `model = TFTModel.load_from_checkpoint(...)`

**Comment by AakarSharmaHME** [comment]
Even with TFTModel same issues is happening. @dennisbader

**Comment by dennisbader** [comment]
Could you add a minimal code snippet to reproduce the issue? Thanks!
