### ISSUE TITLE
Question: Possible to create constraints for forecast values?

### ISSUE THREAD

**Issue by vincetran96** [unit8co/darts#1153]
I trained a [LinearRegression] model to forecast sales values, and some of the generated forecast numbers are negative - which does not make sense. Is it possible to force the forecast numbers to stay within a range/stay positive - maybe not just for this class of models but also for others?

Thanks!

**Comment by hrzn** [comment]
Hi, this is not directly possible, except for probabilistic forecasters, if you enforce a positive distribution. For instance `likelihood="poisson"` for `LinearRegressionModel` or `Poisson()` likelihood for deep learning models (for instance).

**Comment by vincetran96** [comment]
@hrzn Thank you for your response! I understood.

As a note, I'm aware that Greykite (LinkedIn's forecast library) has the functionality to indicate minimum and maximum forecast values, mapping any value outside the desired range back to such values. Details [here](https://linkedin.github.io/greykite/docs/0.4.0/html/pages/model_components/0600_custom.html#forecast-limits).
