### ISSUE TITLE
Limit Verbosity of Models

### ISSUE THREAD

**Issue by colin99d** [unit8co/darts#1160]
**Is your feature request related to a current problem? Please describe.**
When running models in Jupyterlab there is a lot of output. This limits our ability to make clean dashboards.

**Describe proposed solution**
Add a `verbosity` argument so that messages can be hidden.

**Additional context**
Below is an example of a dashboard being crowded out by information
<img width="1221" alt="Screen Shot 2022-08-19 at 4 08 31 PM" src="https://user-images.githubusercontent.com/72827203/185699243-e28d1f1c-1201-4752-8f82-35cc0191d8b5.png">

**Comment by gdevos010** [comment]
Some print out can be removed by disabling the `enable_progress_bar` in the  `pl_trainer_kwargs`. I'm not sure which parts you are trying to remove but most of the printouts you see there come from PyTorch Lightning. 


```
 model(
          pl_trainer_kwargs={
              "accelerator": "gpu",
              "enable_progress_bar": False,
          },
```
Other print outs can be limited as described in issue #927

**Comment by hrzn** [comment]
> Some print out can be removed by disabling the `enable_progress_bar` in the `pl_trainer_kwargs`. I'm not sure which parts you are trying to remove but most of the printouts you see there come from PyTorch Lightning.
> 
> ```
>  model(
>           pl_trainer_kwargs={
>               "accelerator": "gpu",
>               "enable_progress_bar": False,
>           },
> ```
> 
> Other print outs can be limited as described in issue #927

@colin99d could you give a try to these solutions and let us know if that works for you?

**Comment by colin99d** [comment]
That does help, is there any way to block this stuff as well?
<img width="1270" alt="Screen Shot 2022-08-22 at 4 46 00 PM" src="https://user-images.githubusercontent.com/72827203/186015615-f2f3de22-c631-4019-9e0d-eb4afaa7c58a.png">

**Comment by TamerAbdelmigid** [comment]
@colin99d try
```
pl_trainer_kwargs={
            "enable_model_summary": False,
        },
```

**Comment by colin99d** [comment]
I should have follow up. I currently have this:
        "logger": False,
        # "enable_progress_bar": False,
        "enable_model_summary": False,
<img width="1693" alt="Screen Shot 2022-08-27 at 3 11 41 PM" src="https://user-images.githubusercontent.com/72827203/187044795-11cef5ab-c366-4e74-8a26-7486dfef7e99.png">

And im still getting a lot of output. However, this looks like its more of a pytorch-lightning issue. Should I go ahead and close this issue?

**Comment by TamerAbdelmigid** [comment]
@colin99d 
I'm currently using this:
```
warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.CRITICAL)
logging.getLogger("darts.models").setLevel(logging.CRITICAL)
logging.getLogger("pytorch_lightning").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.pl_forecasting_module").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.tcn_model").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.nbeats").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.NHiTSModel").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.nhits").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.torch_forecasting_model").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.forecasting_model").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.baselines").setLevel(logging.CRITICAL)
logging.getLogger("pytorch_lightning.accelerators.gpu").setLevel(logging.CRITICAL)
logging.getLogger("darts.timeseries").setLevel(logging.CRITICAL)
logging.getLogger("darts.utils.utils").setLevel(logging.CRITICAL)
logging.getLogger("darts.utils.torch").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.tft_model").setLevel(logging.CRITICAL)
logging.getLogger("darts.models.forecasting.tft_submodels").setLevel(logging.CRITICAL)
logging.getLogger("darts.utils.data.training_dataset").setLevel(logging.CRITICAL)
logging.getLogger("darts.utils.data.horizon_based_dataset").setLevel(logging.CRITICAL)
logging.getLogger("darts.utils.statistics").setLevel(logging.CRITICAL)
logging.getLogger("darts.dataprocessing.transformers.scaler").setLevel(logging.CRITICAL)
logging.getLogger("darts.dataprocessing.transformers.fittable_data_transformer").setLevel(logging.CRITICAL)
```
alongside that:
```
pl_trainer_kwargs={
            "enable_model_summary": False,
            "enable_progress_bar": False,
        },
```
If you use various models, try add all of them in 
`logging.getLogger("darts.models.forecasting.XXXXXXXX").setLevel(logging.CRITICAL)`

another trick is to use:
```
import IPython
import IPython.display
......
Model.historical_forecasts()
IPython.display.clear_output()
```

Hope this helps.

**Comment by colin99d** [comment]
Thank you for all of this!!
