### ISSUE TITLE
Direct Forecasting Strategy

### ISSUE THREAD

**Issue by cerlymarco** [unit8co/darts#1161]
As I understood, darts provide a _recursive forecasting strategy_ using `RegressionModel`.

For the _recursive strategy_, a single estimator is fit for a one-step-ahead forecasting horizon and then called iteratively to predict multiple steps ahead

**Does darts implements also a _direct forecasting strategy_???** (like in [sktime](https://www.sktime.org/en/stable/api_reference/auto_generated/sktime.forecasting.compose.DirectTabularRegressionForecaster.html))

For the _direct strategy_, a separate forecaster is fitted for each step ahead of the forecasting horizon.

**Comment by hrzn** [comment]
Yes, the direct forecasting length is determined by `output_chunk_length`.
For instance, if you build a model with `output_chunk_length = 2` and then call `predict()` with a horizon `n = 2`, the underlying two models will each predict one time steps once. If you call `predict()` with `n > 2`, the recursive strategy is used and the models will consume their own past forecasts auto-regressively. (small note: this is for a univariate example. There will be more than 2 models in this example if the series are multivariate).
Hope this helps.

**Comment by cerlymarco** [comment]
Thanks! It's clear
