### ISSUE TITLE
Linear Regression Model forecast

### ISSUE THREAD

**Issue by mandar-avhad** [unit8co/darts#1163]
I'm training a Linear Regression model using a dataset that I have.
But the forecast generated using this model looks weird. It either forecasts extremely high negative/positive values which are not even close to the data. Refer to the below image.

![Screenshot from 2022-08-22 13-51-01](https://user-images.githubusercontent.com/61730638/185875259-5f859a94-f25a-444b-b48e-a7d458a657d7.png)

Can you suggest what's might be the issue or what I might be doing wrong?

**Comment by hrzn** [comment]
Hi, could you send a self-contained code snippet, including everything required to reproduce (incl. a way to generate/import a toy dataset on which the issue occurs)?
