### ISSUE TITLE
Suppress Historical Forecast output

### ISSUE THREAD

**Issue by martinb-bb** [unit8co/darts#1167]
Hello,

How does one suppress Hist Fcast output while it is doing backtesting? 
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/105685594/186491821-18c4bce5-33cd-4d9c-8a07-22542c257ac0.png">

It would be nice to either have it as one progress bar or even be able to disable the progress bar. I ask this because it prints out many lines.

Thanks!

**Comment by dennisbader** [comment]
Hi @martinb-bb, could you apply what was suggested in #1160?

**Comment by martinb-bb** [comment]
Hi @dennisbader Thanks for checking in. 

No it does not work because I am not retraining the models when doing the historical forecasting. 

This is my call: 
```python 
historical_fcast = best_model.historical_forecasts(
            ticker_series,
            start=train_split,
            forecast_horizon=forecast_horizon,
            retrain=False,
            verbose=True,
        )
```

Is there a different args I should set to have it remove those 100's of progress bars besides the following? It does not work with `historical_forecasts()`:
```python
pl_trainer_kwargs={
                 "enable_progress_bar": False,
            },
```

**Comment by dennisbader** [comment]
Okay, then you can force the model to create a new PyTorch lightning trainer with updated parameters.

Add the following lines before calling `historical_forecasts`:
```
best_model.trainer = None
best_model.trainer_params["enable_progress_bar"] = False
```

If you want to disable the new device info that is printed by the new trainer object, you can add the folowing lines:
```
import logging
logging.getLogger("pytorch_lightning").setLevel(logging.CRITICAL)
```

**Comment by martinb-bb** [comment]
@dennisbader Works like a charm! 😍 

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/105685594/187512368-217f4298-8ebb-4031-8934-61dced3896c5.png">

But I did not have to put in the following line: `logging.getLogger("pytorch_lightning").setLevel(logging.CRITICAL)`

It doesn't seem to print out anything to do with new device info.. is that expected?
