### ISSUE TITLE
[BUG] model.residuals() not working with covariates

### ISSUE THREAD

**Issue by wregter** [unit8co/darts#1173]
**Describe the bug**
Using model.residuals() does not seem to work when including past_covariates or future_covariates in model.fit(). Perhaps past_covariates or future_covariates could also be passed to model.residuals().

**To Reproduce**
```
import numpy as np
from darts.datasets import AirPassengersDataset
from darts import TimeSeries
from darts.models import RandomForest

series = AirPassengersDataset().load()
covariates = TimeSeries.from_dataframe(series
    .pd_dataframe()
    .drop('#Passengers', axis=1)
    .assign(x = np.random.normal(10, 1, len(series)))
)
model = RandomForest(lags=[-1], lags_past_covariates=[-1])
model.fit(series=series, past_covariates=covariates)
model.residuals(series=series)
```
**Expected behavior**
No error when trying to produce residuals for models with covariates.

**System (please complete the following information):**
 - Python version: 3.8.13
 - darts version 0.21.0
 - numpy version: 1.22.4

**Comment by wregter** [comment]
I found out that this is already on the roadmap. Sorry for opening another issue about it.

**Comment by hrzn** [comment]
No worries, thanks!
