### ISSUE TITLE
AttributeError: 'NBEATSModel' object has no attribute 'width'

### ISSUE THREAD

**Issue by francksa** [unit8co/darts#1174]
Hi

trying Nbeats for the first time. Produces a 'nice' model, but when wanting to extract the Mape value (print("MAPE = {:.2f}%".format(mape(model, prediction)))) - i get the error noted in subject. 
I am not really sure why that is, have you come across this ? thanks

**Comment by dennisbader** [comment]
Hi @francksa, you need to pass the target series with the actual values `actual_series` and the prediction series `prediction` to mape:

```
mape(actual_series, prediction)
```
