### ISSUE TITLE
Can the input_chunk length of target series and covariate series be different? 

### ISSUE THREAD

**Issue by lk1983823** [unit8co/darts#1176]
**Is your feature request related to a current problem? Please describe.**

I am building on a time series forecast model, which needs to take into consideration of the control variable. However, the input length of that variable is only 1, and the input length of the target series is 10. 
For example, the input shape of the target series is (10, 4), and the input shape of the past  (or future) covariates is (1, 3), where 4 and 3 stand for the number of dimensions of the target series and covariates. 
So, I wonder if such kinds of two inputs with different lengths can be feed into the model?   Thanks!

**Comment by lk1983823** [comment]
> Long story short: it depends on the kind of model. Deep learning models relying on input/output chunk lengths have fixed architecture and require fixed input dimensions. But models relying on tabularization (RegressionModels, incl LGBM, RandomForest, CatBoost, LinearRegression etc) can accept different `lags` for the target and the covariates. Control signals are often well represented by future covariates with a lag of 0 (i.e., the value of the control signal at the time of the prediction is taken in input).

Thanks!

**Comment by lk1983823** [comment]
>

**Comment by lk1983823** [comment]
> Long story short: it depends on the kind of model. Deep learning models relying on input/output chunk lengths have fixed architecture and require fixed input dimensions. But models relying on tabularization (RegressionModels, incl LGBM, RandomForest, CatBoost, LinearRegression etc) can accept different `lags` for the target and the covariates. Control signals are often well represented by future covariates with a lag of 0 (i.e., the value of the control signal at the time of the prediction is taken in input).

Thank you. 
The input length of my control signal is only 1, whereas the targets length is 10. Does it mean that even the control signal is repsented by future covariate, I still can't use deep learning model?

**Comment by hrzn** [comment]
You can use the control signal as future covariates in e.g., the TFTModel. In this case all the values of the control applied over the forecast horizon will be used as inputs (e.g., if your forecast horizon is 1, only 1 time step of future covariates will be consumed for each forecast).

**Comment by lk1983823** [comment]
> You can use the control signal as future covariates in e.g., the TFTModel. In this case all the values of the control applied over the forecast horizon will be used as inputs (e.g., if your forecast horizon is 1, only 1 time step of future covariates will be consumed for each forecast).

Thanks.
