### ISSUE TITLE
regresion_model predict with past_covariates fails[BUG]

### ISSUE THREAD

**Issue by miannini** [unit8co/darts#1179]
with the new darts 0.21.0 version, the predict method is failing for the regression_model.py (LinearRegressionModel)
the past_covariates[0] has no width property as has been listed and is not anymore a timeseries (line587)

I think that a solution is to not list the past_covariates (look at line 579)
past_covariates = past_covariates if past_covariates is not None else None

in that way, I was able to get the predictions for regression models, butwould prefer if you take a look.

 - Python version: 3.7
 - darts version 0.21.0

I'm fitting a regression model over a multi-time series Y target, and passing multi-timeseries past covariates.

**Comment by hrzn** [comment]
Hi, this is intended, if there is at least one past covariates, then `past_covariates[0]` should be defined and have a `width`. Could you share a code snippet to reproduce the issue?
