### ISSUE TITLE
Auto Time Series Feature

### ISSUE THREAD

**Issue by Khanifsaleh** [unit8co/darts#1184]
I don't found feature to run auto time series which is can run multiple models and select best one in few lines code only.

**Comment by hrzn** [comment]
Hi, there's no such feature. If you want to perform model selection,I recommend e.g. looking at [hyperparameter optimization](https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html) (the model itself can be seen as a hyperparameter).
