### ISSUE TITLE
Add component selection to TimeSeries

### ISSUE THREAD

**Issue by javitausia** [unit8co/darts#1187]
I don't think there is any option of selecting different components within a TimeSeries object, and I think it might be helpful to implement, as a lot of the models work with multivariate data. The idea is to just implement the .sel() and .isel() xarray methods, so user don't have to convert TimeSeries object to xarray, to do this selection, and then go back again. Maybe it is already implemented, but I couldn't find it, thanks in advance

**Comment by dennisbader** [comment]
You can select components similarly to how you select column with pandas:

`comp_series = series[["comp1", "comp2"]]`

**Comment by javitausia** [comment]
thanks, problem solved!!
