### ISSUE TITLE
Make importing library faster

### ISSUE THREAD

**Issue by marduk2** [unit8co/darts#1194]
Hi everyone,

I find that **importing the darts library is rather slow (i.e. a few seconds, but more than one would like). Is there a way to speed this up?**

For example, I tested the following example lines on several machines and they always take a while (5-20 seconds):

```
from darts import TimeSeries
from darts.utils.utils import ModelMode, SeasonalityMode
from darts.models import ExponentialSmoothing, RandomForest, FFT, NaiveMean, LinearRegressionModel
```

Thanks in advance!

**Comment by hrzn** [comment]
Hi, I'm not aware of any simple way, but that could perhaps warrant a little research. Do you have suggestions to speed this up @marduk2 ?

**Comment by marduk2** [comment]
Hi there @hrzn,

Finally found time to have a look, and found out the library already offers alternative installation options (viz. "u8darts") without the heavier dependencies (mainly PyTorch). That helped a lot, so thanks! :)
