### ISSUE TITLE
LightGBM Model Doesn't Converge for High-dimensional Multivariate Time Series Forecasting

### ISSUE THREAD

**Issue by parshinsh** [unit8co/darts#1198]
I've used LightGBM on the multivariate time series (MVTS) data with d < 30 and all functions (e.g., `.fit()`,`.predict()`,`historical_forecasts()` ) work great. I was just trying to use LightGBM on higher dimensional MVTS Forecasting (e.g., 100-500) and noticed that the LightGBM doesn't converge in this case. It takes a long time to run the model without any errors or stopping. Just wondering it is normal or not. Is there any way to relax the convergence threshold?

**Comment by hrzn** [comment]
Hi, the dataset might be too large. You can try specifying some `max_samples_per_ts` value in order to limit this.
