### ISSUE TITLE
[Question] Categorical features

### ISSUE THREAD

**Issue by soroosh-rz** [unit8co/darts#1199]
Hello,

It is mainly a question. I have a sequential/time-series dataset with two numerical features and one categorical features. The sampling is irregular. I wonder if I can use darts for prediction?

- Which model should I use?
- how should I handle categorical feature? one-hot encoding?
- How to handle missing element since it is irregular?

Thanks,
Soroosh

**Comment by sotte** [comment]
@soroosh-rz one-hot-encode your categorical feature and turn it into time series.

Let's say your cat feature has "a", "b", and "c". Turn this into three time series, one which is hot if "a", one which is hot if "b", one which is hot is "c". You can use this as one `TimeSeries` objects for covariates.

Missing values: this is domain specific. You could just set it to 0 if you don't know anything.

Model: as always, start with a baseline (!), then increase the complexity of the models.

**Comment by hrzn** [comment]
Also checkout [this example](https://unit8co.github.io/darts/examples/15-static-covariates.html) for an example of how to transform/encode categorical static covariates.
