### ISSUE TITLE
Outlier detection

### ISSUE THREAD

**Issue by pennfranc** [unit8co/darts#120]
**Problem.**
Currently there is no functionality to spot outliers of specific entries within a given TimeSeries instance.

**Proposed solution**
One way to spot outliers could be to use one or more of the existing forecasting models (possibly as an ensemble) to produce a historic forecast, and look at the deviations of the forecasts from the actual data. Large deviations might be indicators for outliers.
Inspiration: https://towardsdatascience.com/anomaly-detection-with-time-series-forecasting-c34c6d04b24a

**Comment by Seirdy** [comment]
I'm currently using darts in [clogstats](https://github.com/Seirdy/clogstats), and plan to add anomaly-detection features to notify users when an IRC channel exhibits an uptick in popularity.

I've used the proposed solution you described in the past, comparing present values with past predictions; it worked well for Holt-Winters forecasts and could probably also work well with Prophet. I might give this a shot in a couple weeks.

**Comment by hrzn** [comment]
Thanks for the update @Seirdy, and cool to see you're using Darts in your own project! Let us know if you have more learnings. In the meantime we anyway keep outlier detection on our agenda.

**Comment by phaabe** [comment]
It may make sense to integrate the work of others. Anomaly Detection Tool Kit has a very good approach, I believe:
https://adtk.readthedocs.io/en/stable/index.html

Quote: 
_Anomaly Detection Toolkit (ADTK) is a Python package for unsupervised / rule-based time series anomaly detection. As the nature of anomaly varies over different cases, a model may not work universally for all anomaly detection problems. Choosing and combining detection algorithms (detectors), feature engineering methods (transformers), and ensemble methods (aggregators) properly is the key to build an effective anomaly detection model._

Working with time series anomaly detection for a while, I find ADTK's approach really good. Also using the library is pure feel good.

**Comment by hrzn** [comment]
Cool, thanks a lot for the suggestion @phaabe, we'll take a look at this one.

**Comment by hrzn** [comment]
`darts.ad` released in v0.23.0 🚀
