### ISSUE TITLE
[BUG] Loading pandas dataframe with multiple data points pr. day as a TimeSeries

### ISSUE THREAD

**Issue by sindre-bouvet** [unit8co/darts#1205]
**Describe the bug**
I am having trouble loading a pandas Dataframe as a TimeSeries, where there are multiple data points pr. date.

**To Reproduce**
Download data from the playground Kaggle competition [Tabular Playground Series - Sep 2022](https://www.kaggle.com/competitions/tabular-playground-series-sep-2022/data)

Load the train.csv using regular pd.read_csv.

Set the 'date' column as datetime64 type:
df_train['date'] = pd.to_datetime(df_train['date'])

Set the 'date' column as the index of the Dataframe:
df_train.set_index('date', inplace=True)

Drop all of the columns not being 'date' and the dependent variable 'num_sold':
df_train = df_train.drop(columns=['row_id', 'country', 'store', 'product'])

Load the Dataframe as a TimeSeries:
df_train_dart = TimeSeries.from_dataframe(df_train)

**Expected behavior**
Expect the pandas Dataframe to be loaded as a TimeSeries.

**System (please complete the following information):**
 - Python version: 3.8.13
 - darts version [e.g. 0.21.0]

**Additional context**
Error message:

ValueError: The time index of the provided DataArray is missing the freq attribute, and the frequency could not be directly inferred. This probably comes from inconsistent date frequencies with missing dates. If you know the actual frequency, try setting `fill_missing_dates=True, freq=actual_frequency`. If not, try setting `fill_missing_dates=True, freq=None` to see if a frequency can be inferred.

Image of the data:
![image](https://user-images.githubusercontent.com/73282798/189541332-ea504e70-677d-4879-8c6c-2712cd85a850.png)

As we can see here, there are multiple data points pr. date. Would I need to create one Darts model pr. grouping of data points? For this particular data set this would mean:
6 different countries * 2 different stores * 4 different products = 48 different models?

**Comment by dennisbader** [comment]
Hi, you can use `TimSeries.from_group_dataframe()` which automatically extracts a list of time series grouped by some `group_cols` (see docs [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.from_group_dataframe)). You can set `group_cols = ['country', 'store', 'product']` which should give you a list of 48 series.

All our GlobalForecastingModels (GFM) support multiple TimeSeries (list of series) for training and prediction. You can find a list of our GFMS [here](https://unit8co.github.io/darts/userguide/covariates.html#global-forecasting-models-gfms).

**Comment by sindre-bouvet** [comment]
That is great, thank you for that detailed response!
