### ISSUE TITLE
LSTM Autoencoder with attention mechanisms

### ISSUE THREAD

**Issue by JulesBelveze** [unit8co/darts#122]
**Problem**
Adding LSTM-autoencoder with attention mechanisms for forecasting.

**Solution**
The solution is an implementation of the following [paper](https://arxiv.org/abs/1704.02971). It will be possible to activate and deactivate both attention mechanisms.

**Comment by TheMP** [comment]
Hello @JulesBelveze, thank you for sending us the paper. 

Have you tried using basic LSTM from our RNN model for your usecase https://github.com/unit8co/darts/blob/master/darts/models/rnn_model.py?

Would you be interested in contributing the implementation with attention from the paper described by you?

**Comment by JulesBelveze** [comment]
Hey @TheMP, yes I did and it works actually pretty fine for low dimensional time series! :) 
I would actually like contributing to this paper's implementation. It has shown to be pretty performant when working with high dimensional time series.

I'll fork the repo and the start working on it !

**Comment by TheMP** [comment]
Great, thank you! As a reminder, a few rules (will be added to Contributing section soon):

A good starting point is here https://github.com/unit8co/darts#contribute. If you are up for pushing a change with a new model, please have a look at some of our implementations here https://github.com/unit8co/darts/tree/master/darts/models and make sure that the planned change is conforming to the API. We consider a new model for a merge if:

1. It has been implemented accordingly with our standards (inherits and follows an API of UnivariateForecastingModel/MultivariateForecastingModel).
2. There are at least a few rudimentary unit tests https://github.com/unit8co/darts/tree/master/darts/tests
3. Preferably there is a jupyter notebook attached with sample execution and results. 

Please do not hesitate in case of any questions, and we hope you will find some time to work on the library with us :).

**Comment by hrzn** [comment]
Closing for now. We keep DA-RNN on our radar though.

**Comment by inad9300** [comment]
Autoencoders would be a great addition to Darts.
