### ISSUE TITLE
[BUG] Loading a model doesn't work

### ISSUE THREAD

**Issue by Theo-Clavel** [unit8co/darts#1231]
**Describe the bug**
I trained a RNN model and saved it. When I restart my Databricks cluster and load the model, the predict function raises an error : "'Trainer' object has no attribute '_accelerator_connector'".

**To Reproduce**
model.save("model.pt")
model = RNNModel.load("model.pt")
model.predict(series=ts, n=30)

**Comment by dennisbader** [comment]
Hi @Theo-Clavel , which darts version are you using?
Do you use the same device (GPU/CPU) for the different runs?

If you use the same device, then a solution might be to just pass a new trainer object with the same parameters to `predict()`. This will give you the same prediction results as with the old/broken trainer :

```
import pytorch_lightning as pl

model.save("model.pt")
model = RNNModel.load("model.pt")

trainer = pl.Trainer(**model.trainer_params)
model.predict(series=ts, n=30, trainer=trainer)
```
