### ISSUE TITLE
ValueError requesting longer covariates when using TFTmodel but why?

### ISSUE THREAD

**Issue by cnr0724** [unit8co/darts#1234]
```num_samples=1

figsize=(9,6)
lowest_q,low_q,high_q,highest_q=0.01,0.1,0.9,0.99
quantiles = [
    0.01,
    0.05,
    0.1,
    0.15,
    0.2,
    0.25,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.75,
    0.8,
    0.85,
    0.9,
    0.95,
    0.99,
]
input_chunk_length = 1
forecast_horizon = 1
my_model = tft_model.TFTModel(
    input_chunk_length=input_chunk_length,
    output_chunk_length=forecast_horizon,
    hidden_size=64,
    lstm_layers=1,
    num_attention_heads=4,
    dropout=0.1,
    batch_size=16,
    n_epochs=300,
    add_relative_index=False,
    add_encoders=None,
    likelihood=QuantileRegression(
        quantiles=quantiles
    ),  # QuantileRegression is set per default
    # loss_fn=MSELoss(),
    random_state=42,
    save_checkpoints=True,
    model_name="TFT_base"
)
```

This is the configuration of the model I wanted to use. During training process, everything seemed to be going well. However, when I try to predict a time series that only has one row, this kind of error happens.

```ValueError: For the given forecasting horizon `n=1`, the provided future covariates at dataset index `0` do not extend far enough into the future. As `n <= output_chunk_length` the future covariates must end at time step `2022-07-05 15:43:21`, whereas now they end at time step `2022-07-05 15:43:20`.```

What should I do in order to get the prediction result?

**Comment by dennisbader** [comment]
Hey, for the given `n` steps you want to predict, you have to provide more data for your future covariates (should extend more into the future).

We explain the minimum required time spans for covariates [here](https://unit8co.github.io/darts/userguide/covariates.html#covariate-time-span-requirements-for-local-and-global-forecasting-models). `TFTModel` belongs to the `GlobalForecastingModels`.
