### ISSUE TITLE
Add returns transformation to preprocessing 

### ISSUE THREAD

**Issue by SvenSerneels** [unit8co/darts#1235]
Many financial forecasting models will work better when applied to returns instead of prices. This feature request is simple: add a function to the preprocessing module similar to `Scaler()` , e.g. `Returns()`, that will transform the time series to the corresponding returns at specified frequency and provide inverse transform functionality. Ideally, provide options for different types of returns, e.g. `method = ['absolute', 'percent', 'log']`.

**Comment by hrzn** [comment]
Hi @SvenSerneels, could check [this latest addition](https://github.com/unit8co/darts/blob/master/darts/dataprocessing/transformers/diff.py) (Differencing transformer) and let us know if that could be helpful for you?
