### ISSUE TITLE
[BUG] when resample a TS, first sample is nan in some situations.

### ISSUE THREAD

**Issue by dumjax** [unit8co/darts#1237]
**Describe the bug**
When I use resample, the first element of the resampled time series can be nan.

**To Reproduce**
`from darts import TimeSeries
from darts.utils.timeseries_generation import gaussian_timeseries
import pandas as pd
# starting at 23h works fine
ts = gaussian_timeseries(0, 1, start=pd.Timestamp(2020,1,1, 23, 0, 0), length=1000, freq='15T')
ts.resample(freq= '1h')

# starting at 23:30h gives a nan in the first element of the ts, as it takes as starting point 23h
ts = gaussian_timeseries(0, 1, start=pd.Timestamp(2020,1,1, 23, 30, 0), length=1000, freq='15T')
ts.resample(freq= '1h')
`

**Expected behavior**
Expected behavior would be to sample without nan in the first value. Also, here should we resample from 23:30, (00:30, 1:30, ...) or 00:00 (01:00, )?

**Comment by dennisbader** [comment]
True, we should support more of xarray's resample arguments.
`loffset` would probably do the trick here.
Params that we should add are: `closed`, `label`, `base`, and `loffset`
