### ISSUE TITLE
[BUG] Some Models return a straight-line

### ISSUE THREAD

**Issue by ArchanGhosh** [unit8co/darts#1238]
**Describe the bug**
I am trying to get some predictions and for that I have used around 3 model(AutoArima, FFT, Theta) and now I choose the one with the lowest MAPE value. But sometimes it is only giving a single value over a range of predictions, and the outcome is a straight-line.

**Expected behavior**
if the Mape value is low hence it should produce atleast some pattern

**System (please complete the following information):**
 - Python version: 3.7
 - darts version 0.21.0

**Comment by hrzn** [comment]
Yes, models performing badly happen all the time :) More often than not it is a modelling issue rather than a bug.
If you suspect a bug please provide a reproducible code snippet.
