### ISSUE TITLE
ARIMA Model: how to get forecast value for training set as well

### ISSUE THREAD

**Issue by Insiyaa** [unit8co/darts#1239]
I have a train series and test series and future covariates for both. I fit the model on train series. I am interested in model's output for train series too.

**Comment by dennisbader** [comment]
Hey @Insiyaa, you can use `model.historical_forecasts()` for that. Here is a link to the docs: https://unit8co.github.io/darts/generated_api/darts.models.forecasting.arima.html#darts.models.forecasting.arima.ARIMA.historical_forecasts

**Comment by hrzn** [comment]
There's also the `residuals()` method which could be of interest.
