### ISSUE TITLE
[BUG] Deep learning problems with M1

### ISSUE THREAD

**Issue by SirPopiel** [unit8co/darts#1240]
Hello, 
I am trying to use your library on my M1 powered Mac. I installed it by creating an x64 emulated env and then through conda-forge as detailed in instructions (as with pip I got problems with lightgbm, despite trying to follow the procedure). 

The library works okay, apart from the deep learning-based models. In this case, if I pass cpu as a device my jupyter notebook instantly dies without detailing why. At the same time, if instead i try to use a GPU, it does not find it, and, if i explicitly pass in the trainer mps as accelerator. This, however, does not happen with base pytorch, which i am able to use just fine.

If i do not create a x64 environment then instead nothing seems to work and the library cannot be installed, as there are many conflicts.

Do you have any instructions for this? Thanks

 - Python version: 3.9.13
 - darts version 0.21

**Comment by dennisbader** [comment]
Hi @SirPopiel, did you follow this installation guide? https://github.com/unit8co/darts/blob/master/INSTALL.md#macos-issues-with-lightgbm

**Comment by SirPopiel** [comment]
Yes, but I still had problems (even though I also did the procedure in the link). So, I tried with conda.
Thanks

**Comment by dennisbader** [comment]
Sorry, does that mean it works now? :) 
One note is that if you use the x64 emulated environment, I believe it's not possible to use the built-in GPU with the deep learning models. You would need conda's ARM distribution for that (which might cause issues with other packages such as lightgbm).

**Comment by SirPopiel** [comment]
Okay, thanks, this could be the issue. In fact, I either have lightgbm broken or the deep learning models broken. So, I guess full comaptibility
I will try again on Monday and let you know if I can make sense of it. 
Ps on a different note,

**Comment by dennisbader** [comment]
- With all models, you could increase the `n` at prediction time to predict longer time horizons from the same prediction points (end of your target series let's say beginning of the week after you fitted the models).
- Our `GlobalForcestingModels` (GFM) accept a `series` as input for `predict()` which makes a forecast starting at the end of provided target `series`. So you can add the new values you receive during the week to the target series and then pass it to `predict()`. [This guide](https://unit8co.github.io/darts/userguide/covariates.html#global-forecasting-models-gfms) lists all available GFMs.

**Comment by SirPopiel** [comment]
Okay, thanks, I was indeed searching for the second solution.
