### ISSUE TITLE
Why is .save_model() not working?

### ISSUE THREAD

**Issue by BraytonJSanders** [unit8co/darts#1248]
**Describe the bug**
model.save() is not working for any darts model. The error message is, "AttributeError: 'RegressionModel' object has no attribute 'save_model'." I get this message for every model I've tried.

**To Reproduce**
`from darts.models import RegressionModel
model = RegressionModel(lags=4)
model.save("my_model.pkl")`

**Expected behavior**
Save my darts model.

**System (please complete the following information):**
 - Python version: 3.10
 - darts version: 0.20.0

**Additional context**
![Screen Shot 2022-09-27 at 5 55 49 PM](https://user-images.githubusercontent.com/56480441/192657664-1b280b01-5850-4167-a871-8cd48c09ad14.png)

**Comment by dennisbader** [comment]
You have to use `model.save()` like you wrote in the example to reproduce.
