### ISSUE TITLE
Deploy model to production!

### ISSUE THREAD

**Issue by stefanstoeckigt** [unit8co/darts#1250]
What would be the best way to deploy a dart model in production?
I am looking for something similar to [Torchserve ](https://www.tensorflow.org/tfx/serving/api_rest) or [TensorFlow ModelServer](https://www.tensorflow.org/tfx/serving/api_rest). 
If I save the model as *.pt would it work with the TorchServe?

**Comment by hrzn** [comment]
Hi, at the moment there's no serving framework supported out of the box. You would have to wrap Darts' models in a framework manually.
