### ISSUE TITLE
Logs disappearing

### ISSUE THREAD

**Issue by AlexDugheria** [unit8co/darts#1252]
Everytime I try to import any of the models, all of my logs disappear. 

```
if __name__ == '__main__':

    # Define logger parameters
    handler = logging.StreamHandler()
    filehandler = logging.FileHandler('kpi_forecast/log/log.txt', mode='w', encoding=None, delay=False)
    handler.setFormatter(CustomFormatter())
    logging.basicConfig(
            level=logging.INFO,
            handlers=[handler,
                      filehandler]
        )
```

i define the logger as usual, but then when i do import the class responsible for training and testing one of the models of the library, all the logs are dead and only the print statements remain. The problem persists even if the class that hosts the model it's not called, but only by importing it.
The project includes a Flask app, might it be that there's some incompatibility between model logs and flask logger?

I'm utilizing:
    darts==.0.21 
    MacOs==12.6
    python==3.8.13
    Flask==2.2.2
    flask_restful==0.3.9

**Comment by JeroenPeterBos** [comment]
I ran into the same issue. These are the steps I take to produce a minimal example:

```
conda create -n tmp python=3.8 pip
pip install darts==0.22.0
python log_test.py
```

Where `log_test.py` contains:
```
import logging

import darts.models

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.info("HELLO")
```

I'm on an M1 MacBook with macOS 12.5

**Comment by JeroenPeterBos** [comment]
I did some investigation and it turns out the `statsforecast` package was the culprit. Somehow they decided it was a good idea to make a call to `logging.basicConfig` in the import...

Quick (but ugly) fix is to setup your logging at the top of your file in a `if __name__ == '__main__':` section before you import darts.models, instead of at the bottom. I'll submit an issue / PR to the folks as `statsforecast`.

**Comment by hrzn** [comment]
Closing here, hopefully https://github.com/Nixtla/statsforecast/pull/275 will fix this one. Thanks for looking into it @JeroenPeterBos.
