### ISSUE TITLE
Feature importance and selection

### ISSUE THREAD

**Issue by nik-stan** [unit8co/darts#1253]
Is it possible to implement feature importance algorithms like MDA, Shap etc?

**Comment by dennisbader** [comment]
We are currently working on shap support for our RegressionModels. This will be released in the coming weeks :)

**Comment by nik-stan** [comment]
Thanks Dennis! Looking forward to it. :)

**Comment by dclipca** [comment]
> We are currently working on shap support for our RegressionModels. This will be released in the coming weeks :)

Based. Looking forwarding to it.

**Comment by dennisbader** [comment]
It was released in version 0.22.0!

**Comment by martinb-bb** [comment]
@dennisbader Thanks for the release. Looks and works great. 

I have the following output: 
![image](https://user-images.githubusercontent.com/105685594/194920780-0735b11c-64ee-4927-b360-ea6869c15636.png)

Is there also a way I can get that data into a raw DF to analyze the numbers?
