### ISSUE TITLE
A way to benchmark/explain features (past covariates) for SOTA models

### ISSUE THREAD

**Issue by dclipca** [unit8co/darts#1259]
**Is your feature request related to a current problem? Please describe.**
Data selection is the most important problem when creating a performant model. Ideally, Darts should provide extensive solutions for benchmarking best features. The [Shap Explainer](https://unit8co.github.io/darts/generated_api/darts.explainability.shap_explainer.html) is promising but SOTA models like N-BEATS don't work with it, right?

**Describe proposed solution**
Ideally the Shap Explainer would work with N-Beats and other SOTA models.

**Comment by dennisbader** [comment]
#1270

**Comment by hrzn** [comment]
closing this one.
