### ISSUE TITLE
[BUG] __init__() missing 1 required positional argument: 'norm_type' for Loading TFT Model

### ISSUE THREAD

**Issue by ynusinovich** [unit8co/darts#1266]
**Describe the bug**
I trained 3 temporal fusion transformer models in Google Colab last week for a practice project. Last week, they were loading fine from the saved model file in Google Drive. This week, I am unable to load them, even if I downgrade to darts==0.21.0 (the version of darts from the date that I trained them).
The error for all three says `TypeError: __init__() missing 1 required positional argument: 'norm_type'`. How do I fix this?

**To Reproduce**
`model_loaded = TFTModel.load("/content/gdrive/MyDrive/Work Shared/AISC/2022-06-16 Streamflow Prediction/darts_tftmodel_version_2.pt")`
Please see the notebook here: https://colab.research.google.com/drive/1heKmcC_3wbhYFt31uptro4eRFZTEjDDw?usp=sharing
Side note 1: Specifiying a 'norm_type' when loading did not work.
Side note 2: I am still able to load all RNN models I trained, but not the TFT models.

**Expected behavior**
I would expect the model to load.

**System (please complete the following information):**
 - Python version: 3.7.14
 - darts version: 0.21.0 (also tried with the newer one, 0.22.0)

**Comment by dennisbader** [comment]
Hey @ynusinovich, `norm_type` was added to our transformer models (not RNN models for example) in v0.22.0.
Something must have gone wrong when you installed darts==0.21.0. I also see in your notebook that pip could not fully install all required packages.

You can check which darts version you have after installing with `print(darts.__version__)`

**Comment by ynusinovich** [comment]
@dennisbader Thank you! I actually ended up changing nothing except to add `print(darts.__version__)`, and it started working for some reason. Maybe there were some updates on the Colab end in the past few days.
