### ISSUE TITLE
CatBoost on GPUs

### ISSUE THREAD

**Issue by dclipca** [unit8co/darts#1268]
**Is your feature request related to a current problem? Please describe.**
Training CatBoost models on GPUs.

**Describe proposed solution**
Use https://catboost.ai/en/docs/features/training-on-gpu to implement this into the Darts library.

**Comment by dennisbader** [comment]
Hi @dclipca. You can already pass these GPU parameters as kwargs to `CatBoostModel`.

Have you tried it out?

**Comment by dclipca** [comment]
> Hi @dclipca. You can already pass these GPU parameters as kwargs to `CatBoostModel`.
> 
> Have you tried it out?

No because it wasn't mentioned in the documentation directly per my memory. Will report if it works. Thank you.

**Comment by dclipca** [comment]
Only `task_type="GPU"` did the trick as per the CatBoost docs at https://catboost.ai/en/docs/features/training-on-gpu. Thank you.
