### ISSUE TITLE
Empty time series allowed

### ISSUE THREAD

**Issue by dumjax** [unit8co/darts#1279]
Instead of crashing when we call a TimeSeries[a:b] and there are no points between a and b, we get an empty timeseries.

**Comment by madtoinou** [comment]
Reopening the issue, @connesy reported that the fix does not work for [TimeSeries with DatetimeIndex](https://github.com/unit8co/darts/issues/1359#issuecomment-1368991139_).

Found a fix, taking a bit of time to write the corresponding tests and make sure to not forget any case this time.
