### ISSUE TITLE
historical_forecast last_point_only = True -> generalisation

### ISSUE THREAD

**Issue by dumjax** [unit8co/darts#1282]
Create a new class returned by historical forecast, which gives the horizon predicted TimeSeries we are interested in.

historical_forecasts = m.historical_forecast(series, forecast_horizon = 24)

historical_forecasts.get_forecast(horizon = 12) # gives a TimeSeries of the horizon = 12 predictions 

historical_forecast.get_forecast(timestamp = date) # gives a TimeSeries of the 24 horizon forecast at timestamp date

historical_forecast.get_all() gives the current output

**Comment by hrzn** [comment]
This would break the API so we would need a strong motivation to do it.

**Comment by semlen** [comment]
This improvement is exactly what I was looking for. It would be very helpful to store all the historical forecasts up to forecast_horizon to have an averaged validation metric with predictions up to historical forecasts. This is helpful as users might be interesting in their model performance up to forecast_horizon, and not only for the forecast_horizon.
Is there any other way around it to store historical forecasts up to the forecast_horizon with a sliding window approach?
