### ISSUE TITLE
Convert multivariate time series to supervised learning

### ISSUE THREAD

**Issue by PARODBE** [unit8co/darts#1285]
Hi,

I am new in this so awsome library. Are there any function here to convert multivariate time series to supervised learning? 

Something like that:

# convert series to supervised learning
def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
        cols.append(df.shift(i))
        names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

And after use a supervised learning model?

Thanks! And sorry if the question is too evident but I didn't find the function.

Pablo

**Comment by hrzn** [comment]
Hi, not sure exactly what you mean here, but internally Darts is doing tabularization to convert the TimeSeries to training samples. It's not planned to expose that at the moment, though - hope that answers your question.
