### ISSUE TITLE
Regarding predicting multivariate series data

### ISSUE THREAD

**Issue by thom966** [unit8co/darts#1290]
Hello, I am new to the time-series forecasting problem and I am having hard time how to formulate the model's prediction output.

My problem is predicting the number of sold item for each of 18 items for each store.
For example, my data has information about how many items each 10 stores sold.
And I want to predict the number of each item will be sold for each store in the future.
How should I formulate the input and output to achieve my task?

Thank you for your help.

**Comment by RodgervanderHeijden** [comment]
Were you able to replicate (and understand) the basics of the extensive [Quickstart](https://unit8co.github.io/darts/quickstart/00-quickstart.html)? If not, at what step does your issue start? Perhaps you could start by ignoring the item category and store id for now, and simply try to predict the total number of sales on a day. That might give you a bit of an intuition on how time series work and get you up to speed with them in general and darts specifically.

Also, what is the nature of your problem? Seeing as you're new to time series forecasting, are you struggling in defining the model (conceptually)? Or does the issue lie in preparing the data such that darts can interpret it correctly? Are you having difficulties with predicting the future, after having trained the model?

**Comment by hrzn** [comment]
Hi, on top of what was said, I would recommend you look at the [userguide](https://unit8co.github.io/darts/userguide.html) (start reading about TimeSeries and forecasting models there). It contains information about how to model your problem. if you series are hierarchical, take a look at [this example](https://unit8co.github.io/darts/examples/16-hierarchical-reconciliation.html).

**Comment by hrzn** [comment]
There is now a new [example section](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-and-Forecasting-Multivariate-TimeSeries) showing how to forecast multivariate series.
