### ISSUE TITLE
[BUG] log_tensorboard=True is creating SIGSEGV segmentation problem in Azure ML Pipeline

### ISSUE THREAD

**Issue by Anurag-Celebal** [unit8co/darts#1296]
**Describe the bug**
Azure ML Pipeline not working for Darts in Tensorboard when `log_tensorboard` is True

Calling from Azure Pipeline
`
from azureml.tensorboard import Tensorboard
from azureml.core import Workspace
from azureml.core.compute import AmlCompute
from azureml.core import Environment
from azureml.core.conda_dependencies import CondaDependencies
from azureml.core import Experiment
from azureml.core import ScriptRunConfig
from azureml.core.compute_target import ComputeTargetException
from azureml.core import ComputeTarget
from azureml.pipeline.core import Pipeline
from azureml.pipeline.core import StepSequence
from azureml.pipeline.steps import PythonScriptStep
from azureml.core.runconfig import RunConfiguration

import pathlib
import argparse
import yaml
import logging
import ast
import os
import time

step = PythonScriptStep(name="Tensorboard",
                     script_name="DartsTCN.py", 
                     compute_target=mycompute, 
                     source_directory='.',
                     runconfig=run_config,
                     allow_reuse=True)

#===================Build the pipeline===================
steps = StepSequence(steps=[step])#
myPipeline = Pipeline(workspace=ws, steps=steps)

#===================Submit the pipeline to be run===================  
pipeline_run = experiment.submit(myPipeline,continue_on_step_failure=True)

#===================Start tensorboard===================  
tb = Tensorboard([pipeline_run], local_root='./darts_logs')
tb.start()

pipeline_run.wait_for_completion(show_output=True, timeout_seconds=train_pipeline_config.get('timeout'), raise_on_error=True)

#===================Stop tensorboard===================  
tb.stop()
`

**DartsTCN.py file** contains following code

`from darts.models import TCNModel
from darts.datasets import AirPassengersDataset, MonthlyMilkDataset
import pickle

model = TCNModel(
    24,
    6,
    log_tensorboard=True
)
air_series = AirPassengersDataset().load() 
milk_series = MonthlyMilkDataset().load()
model.fit(air_series)
trainer = model.trainer
name = 'TCNModel'
modelFilePath='TCNModel'+'.pkl'
data = [trainer, model]

with open(modelFilePath, 'wb') as f:
    for d in data:
        pickle.dump(d, f)
`

**To Reproduce**
`[2022-10-17 17:14:55Z] Job failed, job RunId is fce61588-f5d2-4ff1-b788-57b7e1ae28bb. Error: {"Error":{"Code":"UserError","Severity":null,"Message":"{\"NonCompliant\":\"Process '/azureml-envs/azureml_371515ad520423cc86a88eabea3c7b76/bin/python' exited with code -2 and error message 'Execution failed. Process terminated by signal with name SIGSEGV. There's segmentation fault possibly caused by out of memory. Error: /azureml-envs/azureml_371515ad520423cc86a88eabea3c7b76/lib/python3.8/site-packages/dask/dataframe/utils.py:367: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.\\n  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)\\n/azureml-envs/azureml_371515ad520423cc86a88eabea3c7b76/lib/python3.8/site-packages/dask/dataframe/utils.py:367: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.\\n  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)\\n[2022-10-17 17:14:46,686] INFO | darts.models.forecasting.torch_forecasting_model | Train dataset contains 115 samples.\\n[2022-10-17 17:14:46,686] INFO | darts.models.forecasting.torch_forecasting_model | Train dataset contains 115 samples.\\n2022-10-17 17:14:46 darts.models.forecasting.torch_forecasting_model INFO: Train dataset contains 115 samples.\\n[2022-10-17 17:14:46,879] INFO | darts.models.forecasting.tcn_model | Number of layers chosen: 3\\n[2022-10-17 17:14:46,879] INFO | darts.models.forecasting.tcn_model | Number of layers chosen: 3\\n2022-10-17 17:14:46 darts.models.forecasting.tcn_model INFO: Number of layers chosen: 3\\n[2022-10-17 17:14:46,881] INFO | darts.models.forecasting.torch_forecasting_model | Time series values are 64-bits; casting model to float64.\\n[2022-10-17 17:14:46,881] INFO | darts.models.forecasting.torch_forecasting_model | Time series values are 64-bits; casting model to float64.\\n2022-10-17 17:14:46 darts.models.forecasting.torch_forecasting_model INFO: Time series values are 64-bits; casting model to float64.\\n[2022-10-17 17:14:46,881] WARNING | darts.models.forecasting.torch_forecasting_model | DeprecationWarning: kwarg `verbose` is deprecated and will be removed in a future Darts version. Instead, control verbosity with PyTorch Lightning Trainer parameters `enable_progress_bar`, `progress_bar_refresh_rate` and `enable_model_summary` in the `pl_trainer_kwargs` dict at model creation.\\n[2022-10-17 17:14:46,881] WARNING | darts.models.forecasting.torch_forecasting_model | DeprecationWarning: kwarg `verbose` is deprecated and will be removed in a future Darts version. Instead, control verbosity with PyTorch Lightning Trainer parameters `enable_progress_bar`, `progress_bar_refresh_rate` and `enable_model_summary` in the `pl_trainer_kwargs` dict at model creation.\\n2022-10-17 17:14:46 darts.models.forecasting.torch_forecasting_model WARNING: DeprecationWarning: kwarg `verbose` is deprecated and will be removed in a future Darts version. Instead, control verbosity with PyTorch Lightning","MessageFormat":null,"MessageParameters":{},"ReferenceCode":null,"DetailsUri":null,"Target":null,"Details":[],"InnerError":null,"DebugInfo":null,"AdditionalInfo":null},"Correlation":null,"Environment":null,"Location":null,"Time":"0001-01-01T00:00:00+00:00","ComponentName":null}`

**Expected behavior**
Pipeline should run without creating above error.

**System (please complete the following information):**
 - Python version:  Python 3.7.9
 - darts version: 0.22.0

**Additional context**
With "log tensorboard=True" in the local system, the Darts TCN model runs flawlessly, but it fails with the Azure ML Tensorboard Pipeline and generates SIGSEGV. There is a segmentation problem that could be brought on by memory issues.

**Comment by madtoinou** [comment]
Hi @Anurag-Celebal,

PyTorch Lightning, which is responsible for the logging during the DL models training in darts, now relies on TensorboardX instead of Tensorboard. Can you please check if the problem still occurs with darts 0.23.1?

**Comment by hrzn** [comment]
Closing for now, please reopen if needed.
