### ISSUE TITLE
Documentation update regarding global models

### ISSUE THREAD

**Issue by juliuskittler** [unit8co/darts#1297]
Currently, [this page A](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html) (section "Global Forecasting Models") says that there are 5 "global models" which support training on multiple series. However, [this page B](https://unit8co.github.io/darts/README.html) (section "Forecasting Models") has a tabular overview of all the forecasting models, where 12 models have a checkmark for "Multiple series training" (incl. RegressionModel, RandomForest, LinearRegressionModel etc.)

Could you please confirm that page A is out of date? My understanding is that the 12 models from page B are indeed global models, i.e. 1 model is trained that uses knowledge from multiple time series, _not_ multiple models are trained with one model specifically for each time series? 

It might make sense to update page A and refer to page B for a list of the global models. 

PS.: This is not a bug but a request regarding the documentation. There was no such option when creating a new issue.

**Comment by hrzn** [comment]
Thanks @juliuskittler. Would you be interested in proposing this fix and updating the notebook?
