### ISSUE TITLE
Make transformers show warning or exception when there is mismatch between number of series used for fit() and and transform()

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1300]
see #1288.

- We should raise a warning or even an exception when we have a mismatch in number of series used for transformer.fit() and transformer.transform()
- we could also add a mappable or indices of the specific series we want to transform

**Comment by madtoinou** [comment]
This should be solved by #1409, which implements a mappable to match the `fit()` and the `transform()` series and raises an error in case of mismatch [code snippet in the PR](https://github.com/unit8co/darts/pull/1409/files#diff-5249055987cc2108cf8d2e208cd50247c61be5bcbe6a8061e42f92d021cdef6bR375-R381)
