### ISSUE TITLE
[BUG] AttributeError: 'TimeSeries' object has no attribute 'describe'

### ISSUE THREAD

**Issue by osmandolu** [unit8co/darts#1303]
**Describe the bug**
When I run the series.describe() command it does not work. Each time it gives this error:

<< AttributeError: 'TimeSeries' object has no attribute 'describe' >>

**Expected behavior**
Normally I would expect to see the min, max, mean, and other describe statistics of the data but this function does not work. 

**System (please complete the following information):**
-Both my Python and Darts software are up-to-date.

**Comment by hrzn** [comment]
Hi, this is because a `TimeSeries` is *not* a pandas DataFrame and it does not have such a method. If your time series is deterministic, the simplest thing you can do instead is `my_series.pd_dataframe().describe()`.
