### ISSUE TITLE
[BUG] Forecasting horizon explodes with gridsearch on NBEATSModel

### ISSUE THREAD

**Issue by sam-cms** [unit8co/darts#1304]
**Description**
Forecasting horizon keeps on increasing unintentionally in gridsearch, and search process breaks with n value explosion after a couple of hours.
Here is a error 
"For the given forecasting horizon `n=11000`, the provided past covariates at dataset index `0` do not extend far enough into the future"

**code used for reproducibility**
parameters = {
    "input_chunk_length": [12, 18],
    "output_chunk_length": [6 ],
    "num_stacks": [5, 10, 16, 30],
    "num_blocks": [1, 2, 10, 32],
    "num_layers": [2, 3, 4 , 6],
    "layer_widths": [ 64, 256],
    "n_epochs": [50],
    "random_state": [0],
    "nr_epochs_val_period": [1],
    "batch_size": [128],
    "model_name": ["nbeats_run"],
}

res = NBEATSModel.gridsearch(
    parameters=parameters,
    series=ts_train,
    past_covariates=cov_train,
    val_series=ts_test,
    last_points_only=False,
    reduction=np.mean,
    n_jobs=3,
    n_random_samples=0.99,  
    verbose=True,
)
"""After a couple of hours, the search breaks and the error message is : """

ValueError: For the given forecasting horizon `n=11000`, the provided past covariates at dataset index `0` do not extend far enough into the future. As `n > output_chunk_length` the past covariates must end at time step `20XX-XX-XX XX:XX:XX`, whereas now they end at time step `20XX-XX-XX XX:XX:XX`.

**Expected behavior**
Note that the simple prediction with the specified  "input_chunk_length" and "output_chunk_length" works just fine.

**System (please complete the following information):**
 - Python version: 3.9.12
 - darts version 0.21.0

Not sure if this is just for Nbeats or if this happens with other models as well.

**Comment by hrzn** [comment]
Hi, there is no increase in the forecasting horizon. It seems that your training dataset might be too large (hence the time it takes before raising the first issue), and gridsearch is using split-mode which means it'll attempt to predict for the whole length of the validation series (11,000 points) that you passed. I would recommend you try to loop yourself over the combinations of hyper-parameters you're interested in (perhaps using a library like Optuna) and avoid relying on gridsearch, which will anyway not scale to the number of hyper-parameters you're having. Doing it yourself will also allow you to control the size of the training set using `max_samples_per_ts` when calling `fit()`.
