### ISSUE TITLE
Make predictions for unseen future data 

### ISSUE THREAD

**Issue by thom966** [unit8co/darts#1313]
Hello, I have a question regarding producing future predictions of unseen data.
Is it possible to produce the future of three months without providing the model future dataset?
For instance, I have data until 2022-03-01 and want to produce future data predictions for 2022-04, 2022-05, 2022-06, which are not included in the dataset.

Thank you for your help.

**Comment by dclipca** [comment]
https://unit8co.github.io/darts/_images/covariates-highlevel.png

Can you explain a bit more in terms of Darts-specific slang? i.e.  target, past and future covariates.

**Comment by thom966** [comment]
My dataset has target, past covariates, and future covariates until 2022-03-01.
And I would like to make the model produces target series without feeding any past covariates and only feeding future covariates, which could be only dates.
Is there any way to achieve this?

**Comment by dennisbader** [comment]
Yes that's possible.

You have two options:
- use a forecasting model which only supports future covariates (you could not use your past covariates)
- use a GlobalForecastingModel which support past and future covariates, and set `ouptu_chunk_length = 3` months. Like this you can always predict up to the next 3 three months using all your available data.


You can find a list of models with their covariate support in [this user guide](https://unit8co.github.io/darts/userguide/covariates.html#forecasting-model-covariate-support).
