### ISSUE TITLE
why does sMAPE for particular series increase when fitting on multiple series?

### ISSUE THREAD

**Issue by alejandrogomez97** [unit8co/darts#1323]
There's an issue with the function fit() of LinearRegressionModel and it might affect the fit() functions of other models.

The fit() function allows a TimeSeries object or a List of TimeSeries objects as the series input. However, we've noticed that, when a list of TimeSeries objects is given, the smape error of a particular series increases with the number of total series in the list, as we can see in the attached plot.

Thank you in advance.

![smape_vs_nTimeSeries](https://user-images.githubusercontent.com/116890811/198590686-53c326f3-6fe3-493b-bf69-0b817ffd2162.png)

**Comment by dennisbader** [comment]
The model tries to generalize over all series that you supply. It's completely normal that the error for a single series can increase. 

You have to look at all series together. You want to find one model which yields good predictions for different time series, rather than a model which only produces good forecasts for a single series and performs bad on all the others.

You could experiment with fitting a new model only on a single time series and then assessing the performance on all remaining unseen series. I would assume that it performs worse than you global (multi series) model.

**Comment by alejandrogomez97** [comment]
> The model tries to generalize over all series that you supply. It's completely normal that the error for a single series can increase.
> 
> You have to look at all series together. You want to find one model which yields good predictions for different time series, rather than a model which only produces good forecasts for a single series and performs bad on all the others.
> 
> You could experiment with fitting a new model only on a single time series and then assessing the performance on all remaining unseen series. I would assume that it performs worse than you global (multi series) model.

Thank you very much for the fast reply, I appreciate it very much :) I have a follow up question to try to get a better understanding of the functioning of the tool:

So imagine I have a list of two time series objects [_ts1_, _ts2_]. Now I learn a linear regression model using Darts. I get that I learn an unique model to predict _ts1_ and _ts2_, but, is this model using _ts1_ and _ts2_ to predict _ts1_? and consequently using _ts1_ and _ts2_ to predict _ts2_? Or is it just using _ts1_ to predict _ts1_ and consequently _ts2_ to predict _ts2_?

Thanks in advance.

**Comment by dennisbader** [comment]
In your case (a list of multiple target time series) it only uses ts1 (and past/future covariates1) to predict ts1, ts2 to predict ts2, etc. When you fit, the model uses sample chunks from both ts1 and ts2.

In the multivariate case (target series with multiple components/colums) it uses all components of ts1 to predict ts1. 
Let's assume your ts1 and ts2 have the same time index. You can stack them together into one series `ts = ts1.stack(ts2)`. This is a multivariate series with two components ts1, and ts2.
