### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1325]

**Comment by Loudegaste** [comment]
Statsforecast depends on numba which doesn't support python 3.11

**Comment by hrzn** [comment]
We are dependent on
- [ ] https://github.com/numba/numba/issues/8304
- [ ] https://github.com/pytorch/pytorch/issues/86566

**Comment by wouterbles** [comment]
Release candidate of Numba with Python 3.11 support is tracked here:
- [ ] https://github.com/numba/numba/issues/8841

**Comment by wouterbles** [comment]
Update: new numba version has been released. Although I think it's also necessary to wait until statsforecast has updated to support 3.11?

https://github.com/Nixtla/statsforecast/pull/425
