### ISSUE TITLE
Does darts support multi-horizon forecasting?

### ISSUE THREAD

**Issue by cvnlp-dl** [unit8co/darts#1335]
I am new to darts, and from the documentation, I cannot understand if multi-horizon forecasting is supported by darts.

`predict(n[, series, past_covariates, ...])`
>Predict the n time step following the end of the training series, or of the specified series.

When predicting the `n` time steps, `n` is the first parameter in the `predict()` function. is it **an iterative one-step prediction in the future**, or other settings, like **output n time steps altogether**? 

For the iterative one-step prediction, for the n=1, it should use **input_chunk_length** true values to predict the **n=1 value**. However, for n=2, how did it get the second value? Will it use input_chunk_length true values (substitute n=1 prediction with the true value), or [***(input_chunk_length -1)* true values + 1 *predicted value***] to get the 2nd prediction?

How to get the performance of 1-horizon errors, 2-horizon errors, and 12-horizon errors? the performance at each time step into the future?

Hope someone can clarify on this. Thanks.

**Comment by shisi-cc** [comment]
I have the same question. How does darts make the prediction? I looked at the predicted and actual curves, and the bigger the n, the worse the deviation
