### ISSUE TITLE
[BUG] Unable to load models 

### ISSUE THREAD

**Issue by adelgadof** [unit8co/darts#1336]
Hi, I have been using TFT model for a while and I have usually saved these models using torch features. However I have not been able to load these models.

When I load model (`TFTRegressor = torch.load(<ModelPath>)`) I receive the following error:

> AttributeError: module 'darts.utils.data.encoder_base' has no attribute 'ReferenceIndexType'

These models have been useful just until now, I tried loading these models from a clean environment but I received the same error. Models were originally saved following usual methods (`torch.save(TFTRegressor,<ModelPath>`). 

Different versions of Darts (0.22, 0.21, 0.20) have been tried but the error keeps being reproduced.

**Comment by dennisbader** [comment]
Two things:
- Models should be saved/loaded with our dedicated API: `model.save(...)` and `loaded_model = TFTModel.load(...)`
- ReferenceIndexType was removed in Darts version 0.22.0, so version 0.21.0 should work. It should work if you install darts==0.21.0 directly in a new environment (i.e. don't install different version one after the other in the same env).
