### ISSUE TITLE
[BUG] verbose=False does not affect in predict of RNNModel

### ISSUE THREAD

**Issue by vpozdnyakov** [unit8co/darts#1337]
**Describe the bug**
When I set `verbose=False` in `predict` method of RNNModel it still shows the progress bar.

**To Reproduce**
```python
from darts.timeseries import TimeSeries
from darts.models import RNNModel
model = RNNModel(
    input_chunk_length=100,
    output_chunk_length=1,
    n_epochs=1,
)
ts = TimeSeries.from_values(np.random.randn(1000))
model.fit(ts, verbose=True)
pred = model.predict(n=1, series=ts, verbose=False)
```

<img src='https://user-images.githubusercontent.com/12996098/200109957-6e9995fa-b8de-428e-8ae2-479d64dd22ca.png' width=700>

**Expected behavior**
Progress bar is not displayed.

**System:**
 - Python version: 3.7.15
 - darts version: 0.22.0

**Comment by vpozdnyakov** [comment]
The rough solution is to drop the trainer after fitting:
```python
from darts.timeseries import TimeSeries
from darts.models import RNNModel
model = RNNModel(
    input_chunk_length=100,
    output_chunk_length=1,
    n_epochs=1,
)
ts = TimeSeries.from_values(np.random.randn(1000))
model.fit(ts, verbose=True)
model.trainer = None
pred = model.predict(n=1, series=ts, verbose=False)
```

**Comment by hrzn** [comment]
This has been fixed in the latest release
