### ISSUE TITLE
[BUG] Model.fit printing Validation: 0it [00:00, ?it/s] on new lines for every epoch (or x epochs)(no bar progression)

### ISSUE THREAD

**Issue by Fuchio** [unit8co/darts#1342]
**Describe the bug**
Models keep printing new line that just says `Validation: 0it [00:00, ?it/s]` instead of a TQDM bar or epoch progress.

**To Reproduce**
I am not sure how this occured as I believe this did not happen when I started using Darts. However, I have seen it occur for some others (for example on Kaggle: https://www.kaggle.com/code/komalnalawade/n-beats-for-forecast-using-darts). In their notebook the NBEATS model behaves the same.

For me it runs on pretty much every model, with the most basic example:
```
model = TFTModel(
    random_state=0,
    input_chunk_length=24,
    output_chunk_length=12,
    n_epochs=1000,
    pl_trainer_kwargs=pl_trainer_kwargs,
)
```
```
model.fit(train_solar, future_covariates=future_train_cov, past_covariates=past_train_cov, verbose=True)
```

**Expected behavior**
TQDM bar showing progress of the epoch progression.
For example: https://youtu.be/sXNXI2mE8DU?t=515

**System (please complete the following information):**
 - Python version: 3.10.4
 - darts version 0.22.0
 - 
**Additional context**
If anyone knows how to fix this it would be really helpful. Doing quick testing without having any idea of the progression of the model is starting to get to me.

**Comment by dennisbader** [comment]
Hey @Fuchio, could you try following #830 that solved a similar issue?

**Comment by dennisbader** [comment]
With that you mean you couldn't try yet or that it doesn't work? 
Try either [this](https://github.com/unit8co/darts/issues/830#issuecomment-1186533157) or [this](https://github.com/unit8co/darts/issues/830#issuecomment-1186573300)
