### ISSUE TITLE
Getting shap_explain.summary_plot() in a python list rarther than an image

### ISSUE THREAD

**Issue by dclipca** [unit8co/darts#1353]
The output of ```shap_explain.summary_plot()``` is an image. How can I get the data in the image in a python-accesible format, say a list? ```ExplainabilityResult``` is a ```TimeSeries``` but I am more interested in a simple list of the average change in prediction for every feature (same numbers in in the ```shap_explain.summary_plot()```, just accessible in python).

**Comment by hrzn** [comment]
@dumjax do you think it's doable?
