### ISSUE TITLE
[BUG] Future Covariates for KalmanForecaster

### ISSUE THREAD

**Issue by kiran-kumar95** [unit8co/darts#1354]
**Describe the bug**
When training a KalmanForecaster model with additional future covariates it throws error during prediction. 

**To Reproduce**
model = KalmanForecaster()
if covariates:
    model.fit(train_transformed, future_covariates = cov_transformed)
    prediction = model.predict(n=12, num_samples=100, future_covariates = cov_transformed)

**System (please complete the following information):**
 - Python version: 3.7
 - darts version: 0.22.0

**Additional context**
No error is thrown during model.fit() process. Only during prediction time we get the error as shown below

/opt/conda/lib/python3.7/site-packages/darts/models/forecasting/forecasting_model.py in predict(self, n, future_covariates, num_samples, **kwargs)
   1500 
   1501         return self._predict(
-> 1502             n, future_covariates=future_covariates, num_samples=num_samples, **kwargs
   1503         )
   1504 

/opt/conda/lib/python3.7/site-packages/darts/models/forecasting/kalman_forecaster.py in _predict(self, n, future_covariates, num_samples)
     86         whole_series = self.training_series.append(series_future)
     87         filtered_series = self.darts_kf.filter(
---> 88             whole_series, covariates=future_covariates, num_samples=num_samples
     89         )
     90 

/opt/conda/lib/python3.7/site-packages/darts/models/filtering/kalman_filter.py in filter(self, series, covariates, num_samples)
    200             raise_if_not(
    201                 series.has_same_time_as(covariates),
--> 202                 "The number of timesteps in the series and the covariates must match.",
    203             )
    204 

/opt/conda/lib/python3.7/site-packages/darts/logging.py in raise_if_not(condition, message, logger)
     76     if not condition:
     77         logger.error("ValueError: " + message)
---> 78         raise ValueError(message)
     79 
     80 

**ValueError: The number of timesteps in the series and the covariates must match.**

**Comment by dennisbader** [comment]
Your covariates must include the next `n=12` time steps after the end of your training series.

**Comment by kiran-kumar95** [comment]
The covariates provided in example already have data 4 times than the requirement. i.e (four years in advance for n=12)

**Comment by dennisbader** [comment]
Can you try slicing your covariates so that it has exactly all time steps from `train_transform` plus the next `n` time steps?

We have done some improvements for KalmanForecaster which should do this automatically (will be released in a few weeks with the next Darts version)
