### ISSUE TITLE
Conda-forge recipe request

### ISSUE THREAD

**Issue by owenlamont** [unit8co/darts#136]
**Is your feature request related to a current problem? Please describe.**
I'd like to be able to conda install darts

**Describe proposed solution**
Create a conda-forge recipe and link it to the PyPi package or GitHub release. 

**Describe potential alternatives**
Pip installing to a conda environment works but PyPi and conda packages don't always play nice together when upgrading.

**Comment by hrzn** [comment]
Yes, this is a good point, we'll address it.

**Comment by hrzn** [comment]
I've been giving it a try in this branch: https://github.com/unit8co/darts/tree/feat/conda-package
but so far without success (building with `conda build` with my `meta.yaml` file gives me a whole bunch of dubious dependency conflicts errors). If anyone more knowledgeable than me with conda wants to give it a shot that would be very welcome...

**Comment by xfiderek** [comment]
Hey! I've been giving a try today. Please follow [this PR](https://github.com/unit8co/darts/pull/403)

**Comment by tomasvanpottelbergh** [comment]
We have published `u8darts` and `u8darts-all` on conda-forge, which we will soon add to the documentation. There is still an issue with `u8darts-all` on Python 3.9 because of the `pmdarima` dependency, but this will hopefully be resolved soon.

**Comment by owenlamont** [comment]
Thanks very much for all your work on this.

**Comment by tomasvanpottelbergh** [comment]
You're very welcome! It would be great if you could test the packages and let us know if there are any issues.

**Comment by hrzn** [comment]
I'm closing this issue since there is now a conda-forge (even though it's not yet perfectly supported on all versions of Python, and it is also released later than the Pypi version).
