### ISSUE TITLE
Annotate TimeSeries method returns with Self type

### ISSUE THREAD

**Issue by connesy** [unit8co/darts#1361]
Many TimeSeries-methods are annotated with a return type `-> "TimeSeries"` even though they use `self` or `self.__class__`, e.g. `head`:
```python
# timeseries.py
class TimeSeries:
    ...
    def head(
        self, size: Optional[int] = 5, axis: Optional[Union[int, str]] = 0
    ) -> "TimeSeries":
```
This makes it difficult to subclass `TimeSeries`, since that annotation prevails:
```python
import inspect
from darts.timeseries import TimeSeries
class Child(TimeSeries):
    pass

print(inspect.get_annotations(Child.head))
{'size': typing.Optional[int], 'axis': typing.Union[int, str, NoneType], 'return': 'TimeSeries'}
```
even though `Child.head` actually returns an instance of `Child`.

If one would change `head` (and the other `TimeSeries` methods) to be annotated with `typing.Self`, then this would not be an issue.

**Comment by connesy** [comment]
Sorry for the long silence, I realized that `typing.Self` is only introduced in python 3.11. So a solution would be to add
```python
import sys
if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self
```

Would that be acceptable?

**Comment by hrzn** [comment]
> Sorry for the long silence, I realized that `typing.Self` was introduced in python 3.11. So a solution would be to add
> 
> ```python
> import sys
> if sys.version_info >= (3, 11):
>     from typing import Self
> else:
>     from typing_extensions import Self
> ```
> 
> to enable using the `Self`-annotation. Would that be acceptable?

Unfortunately we have to be backward compatible (currently with 3.7+ versions) so we cannot have code making use of 3.11 features.

**Comment by connesy** [comment]
I get that, which is why I suggest using the `Self` from `typing_extensions` for versions below `3.11`.

**Comment by hrzn** [comment]
> I get that, which is why I suggest using the `Self` from `typing_extensions` for versions below `3.11`.

Oh sorry I read your comment too fast :)
That looks good then, yes.

**Comment by connesy** [comment]
Great, I'll have a crack at a PR then.
