### ISSUE TITLE
Why does NBEATSModel.load_from_checkpoint fail when using a custom pl.Trainer?

### ISSUE THREAD

**Issue by MichaelALong** [unit8co/darts#1362]
**Describe the bug**
A fitted NBEATS model, saved with darts checkpointing, fails to load with error 
2022-11-14 15:52:37 darts.models.forecasting.torch_forecasting_model ERROR: FileNotFoundError: There is no file matching prefix best-* in mydir/mymodel/checkpoints

**To Reproduce**

model = NBEATSModel(
    input_chunk_length=4,
    output_chunk_length=8,
    random_state=42,
    num_stacks=4,
    layer_widths=32,
    expansion_coefficient_dim=3,
    optimizer_kwargs={"lr":1e-4},
    batch_size=32,
    save_checkpoints=True,
    work_dir="mydir",
    model_name="mymodel",
    pl_trainer_kwargs={"accelerator": "gpu", "devices": -1, "auto_select_gpus": True,
                        "lr_scheduler_cls": optim.lr_scheduler.ReduceLROnPlateau,
                        "lr_scheduler_kwargs": {'mode':'min', 'factor':0.1, 'patience':5, 'threshold':0.0001, 'threshold_mode':'rel', 'cooldown':5, 'min_lr':0, 'eps':1e-08,}
                      },
)

model = model.fit(train_tgt_list, past_covariates=train_cov_list, val_series=val_tgt_list[:500], val_past_covariates=val_cov_list[:500],
                  verbose=True, num_loader_workers=4,
         trainer = pl.Trainer(
                              precision=64, accelerator='gpu', devices=1,
                             max_epochs=10, enable_progress_bar=False)
    )

model = NBEATSModel.load_from_checkpoint(model_name="mymodel", work_dir="mydir", file_name=None, best=True)

**Expected behavior**
The best NBeats model should load.

**System (please complete the following information):**
 - Python version: 3.7
 - darts version 0.22.0
 - Running in Jupyter notebook in google cloud, using GPUs for fitting

**Additional context**
The fitting process creates a file (mydir/mymodel/_model.pth.tar). I zipped and attached this file in case it helps.
[_model.pth.zip](https://github.com/unit8co/darts/files/10004887/_model.pth.zip)

**Comment by dennisbader** [comment]
The problem is that you pass a custom PyTorch Lightning trainer to `model.fit()` that has no checkpointing implemented.
The Darts API handles everything for you in the background so you don't have to give a new trainer to fit/predict.
Whenever a custom trainer is passed to fit/predict, it is left to the user to
