### ISSUE TITLE
Looking to use this library for regression problem

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [unit8co/darts#1368]
Hello everyone, thanks for creating this amazing repo. I am working on a problem where I have 70 features and one target. The data has been captured with respect to time (in 5MS) but timestamp doesn't really matter. I am looking forward to use this repo for regression problem but after going through the documentation and examples, it looks like, to use this repo, we need to have to have a column with time information. Please let me know if there is any workaround for this problem where I am not required to pass the time information.

I am looking forward to your best guidance.

Thanks

**Comment by deltamacht** [comment]
It sounds like you would pretty easily have the timestamps needed to create a timestamp column? In any case, see the `time_col` argument in the `TimeSeries.from_dataframe()` method. Seems you should be able to pass integers rather than timestamps if that's more convenient for some reason.

**Comment by HasnainKhanNiazi** [comment]
@deltamacht I have `70` features and `1` target and in the case of `TimeSeries.from_dataframe()`, I can only pass one feature in `time_col` instead of passing timestamps. The problem is that I wanna use `70` features as model input and one target variable. So passing only one feature instead of `timestamp` will not work for me.

**Comment by deltamacht** [comment]
`time_col` is not where you would place features. It sounds like you are looking for adding covariates (either past or future). I suggest you look at the examples and documentation regarding those.

**Comment by HasnainKhanNiazi** [comment]
I already had a very detailed look at the documentation and `time_col` is the only field that is being considered by the model as `feature` and rest of the columns are being used as targets. I already did multiple experiments and this is how things are working in Darts,I believe but I could be wrong too.

**Comment by madtoinou** [comment]
You need to use the `past_covariate` and/or `future_covariate` arguments of the `fit` method in order to indicate to the model that you're not trying to forecast all the columns of your multivariate TimeSeries (TimeSeries with more than 1 column/component), but rather use 69 of them to help predicting the target.
