### ISSUE TITLE
 Illegal instruction (core dumped) when running import darts.models

### ISSUE THREAD

**Issue by ruben-rosa** [unit8co/darts#1372]
**Describe the bug**

Created a clean environment and installed Darts using PIP and python version 3.9.15
Running this example : https://unit8co.github.io/darts/quickstart/00-quickstart.html#Encoders:-using-covariates-for-free

When I tried to : from darts.models import NaiveSeasonal
I got : Illegal instruction (core dumped)

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

I ran python -v and this is what I got:

# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/__pycache__/core.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/core.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/__pycache__/core.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/__pycache__/plot_helpers.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/plot_helpers.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/catboost/__pycache__/plot_helpers.cpython-39.pyc'
Illegal instruction (core dumped)

I seems catboost is having the issue here but I do not know how to fix it.

**Expected behavior**

**System (please complete the following information):**
 - Python version: [3.9.15]
 - darts version [0.22]
- Distributor ID:	Ubuntu
- Description:	Ubuntu 20.04.5 LTS
- Release:	20.04
- Codename:	focal

**Additional context**

Any help is highly appreciated

**Comment by alexcolpitts96** [comment]
What is the output of these:
1. > python -v
2. > which python
3. > python -c "import darts; print(darts.__version__)"
4. > python -c "from darts.models import NaiveSeasonal"

**Comment by ruben-rosa** [comment]
output of python -v

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__init__.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/codecs.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/codecs.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/codecs.cpython-39.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e77670>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/aliases.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e11c10>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e77490>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/utf_8.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e778b0>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/latin_1.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e11d00>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/io.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/io.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/io.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/abc.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/abc.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/abc.cpython-39.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e291f0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e11ee0>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/site.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/site.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/os.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/os.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/os.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/stat.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/stat.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/stat.cpython-39.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732dc6a60>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/_collections_abc.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732dc6af0>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/posixpath.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/posixpath.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/posixpath.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/genericpath.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/genericpath.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/genericpath.cpython-39.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d59160>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732dc6a30>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e3c190>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/_sitebuiltins.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e3ca60>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/_bootlocale.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/_bootlocale.cpython-39.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d59610>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/_distutils_hack/__init__.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc'
import '_distutils_hack' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d59a90>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/types.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/types.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/types.cpython-39.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d76d90>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__init__.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/__init__.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/warnings.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/warnings.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/warnings.cpython-39.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d77be0>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d77f40>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/util.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/util.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/abc.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/abc.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/machinery.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/importlib/__pycache__/machinery.cpython-39.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d78310>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/typing.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/typing.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/typing.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/__init__.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/__pycache__/__init__.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/heapq.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/heapq.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/heapq.cpython-39.pyc'
# extension module '_heapq' loaded from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/lib-dynload/_heapq.cpython-39-x86_64-linux-gnu.so'
# extension module '_heapq' executed from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/lib-dynload/_heapq.cpython-39-x86_64-linux-gnu.so'
import '_heapq' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7f3732ce12b0>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d58d60>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/keyword.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/keyword.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/keyword.cpython-39.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732ce13a0>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/operator.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/operator.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/operator.cpython-39.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732ce1460>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/reprlib.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/reprlib.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/reprlib.cpython-39.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732ce1520>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d3d220>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/abc.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/collections/__pycache__/abc.cpython-39.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d3d5b0>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/contextlib.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/contextlib.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/contextlib.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/functools.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/functools.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/functools.cpython-39.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732ceee80>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d3d7c0>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/re.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/re.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/re.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/enum.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/enum.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/enum.cpython-39.pyc'
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d13e20>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/sre_compile.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_compile.cpython-39.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/sre_parse.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_parse.cpython-39.pyc'
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/sre_constants.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/sre_constants.cpython-39.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732cc1910>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732cb2ee0>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732cb2670>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/copyreg.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/copyreg.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/copyreg.cpython-39.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732c5a340>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732ce1f10>
import 'typing' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d78040>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d67d30>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d77d90>
# possible namespace for /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/google
# possible namespace for /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/mpl_toolkits
# possible namespace for /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/site-packages/google
# destroy google
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732e299d0>
Python 3.9.15 (main, Nov  4 2022, 16:13:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-linux-gnu.so'
# extension module 'readline' executed from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-linux-gnu.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7f3732d78f10>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc matches /home/ruben/anaconda3/envs/darts_py39/lib/python3.9/rlcompleter.py
# code object from '/home/ruben/anaconda3/envs/darts_py39/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x7f3732d78d90>

**Comment by ruben-rosa** [comment]
output of which python: /home/ruben/anaconda3/envs/darts_py39/bin/python

darts_py39) ruben@icex360:~$ python -c "import darts; print(darts.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'darts' has no attribute 'version'
(darts_py39) ruben@icex360:~$ 

(darts_py39) ruben@icex360:~$ python -c "from darts.models import NaiveSeasonal"
Illegal instruction (core dumped)
(darts_py39) ruben@icex360:~$

**Comment by alexcolpitts96** [comment]
My guess is that your python installation is broken. 

If you haven't, I would suggest creating a new conda environment from scratch and see if the issue persists. I was able to get this working in a Docker container.

**Comment by ruben-rosa** [comment]
Hi,

I found out the issue.  I have an OLD 4 processors CPU that do not support SSE4.2 and AVX & AVX2 vector instruction so CATBOOST crashed.  ¿Is there a way to install DARTS without CATBOOST?

Thanks,

**Comment by hrzn** [comment]
@ruben-rosa starting in 0.23.0 Darts should be working even if you don't have Catboost installed.
I'll close this issue for now but let us know if you have any further comment on this.
