### ISSUE TITLE
Seaborn import

### ISSUE THREAD

**Issue by lucfra** [unit8co/darts#1381]
Dear authors, 

first of all, congrats for the package! Really like it. 

Secondarily, would be possible to make the seaborn package import optional?

Thanks!
Luca

**Comment by hrzn** [comment]
Hi @lucfra and thanks for the feedback.
Where do you see seaborn imported? It's not a dependency of Darts, and should not be used anywhere in the code base. It might be a dependency of one of our dependencies, in which case I'd be happy if you provide me with a full stracktrace, so I can check whether this is something we could potentially remove.

**Comment by lucfra** [comment]
Hi @hrzn , 

thanks! Here's a very minimal example of what I mean. 
![image](https://user-images.githubusercontent.com/24814823/205740215-74c9acf1-6c66-497d-a98b-b4528190b5bb.png)

Not really sure how to print the stacktrace of an import statement. 

Best wishes, 
Luca

**Comment by hrzn** [comment]
Oh, that's not due to seaborn, it's due to Darts currently redefining some of matplotlib's defaults.
You can disable this behavior setting the environment variable: `DARTS_CONFIGURE_MATPLOTLIB=0`.
See: https://github.com/unit8co/darts/pull/924
Hopefully that solves the issue.

**Comment by lucfra** [comment]
Ok thanks!
Would be nice to have the change of style as an opt-in feature probably.

Anyway, thanks again. 

Cheers, 
Luca
