### ISSUE TITLE
[BUG] Decrease in performance for historical_forecasts

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#1393]
**Describe the bug**
@hrzn I was working with the NLinear model this weekend on the master branch and noticed a drop in performance when using `historical_forecasts` compared to when I first did the performance analysis for the models (predict still performs the same). I've been able to narrow it down to these two commits, but can't seem to run any of the commits in between them since I get a mat multi error. Also, this error is not probabilistic (Quantile regression) related. I can create a simple script to reproduce this error later this week, but Im not doing anything fancy. 

### https://github.com/unit8co/darts/pull/1292/commits/b753fb41395e749576505a6d424fc2fa7b1e989a
![Backtest_Air Passengers NLinear (QR)](https://user-images.githubusercontent.com/15316026/204174175-111dce46-9353-442b-885c-7a4c582e120d.png)

### https://github.com/unit8co/darts/pull/1292/commits/237f4b4d099fd4d1a9f335e60a365f5ca22a7fb3
![Backtest_Air Passengers NLinear (QR)](https://user-images.githubusercontent.com/15316026/204174197-446e3a9a-a0fc-4f2f-92c6-b80625f99e9b.png)

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

**Comment by hrzn** [comment]
Hi @gdevos010, thanks for reporting. This is really strange, because `historical_forecasts()` relies on `predict()`. Are you sure that `predict()` is returning the same thing? Are you retraining in `historical_forecasts()`? Between the two commits you mention, I have added support for future and static covariates. Are you using covariates? How do you conclude that the error is not related to quantile regression? If you have a script to reproduce the issue that would be helpful.

**Comment by gdevos010** [comment]
@hrzn It is future covariates related. I forgot I had future covariates in my encoders. Here are some experiments run on master. I haven't had time to make a simple script yet.

### Without Future covariates
```python
  encoders = {
      "datetime_attribute": {"past": ["month", "year"]},
      "position": {"past": ["relative"]},
      "transformer": Scaler(StandardScaler(), n_jobs=-1),
  }
```

![Forecast_Air Passengers NLinear ()](https://user-images.githubusercontent.com/15316026/204397894-5c52fc99-d7af-47d2-89bc-c4e577fd56aa.png)
![Backtest_Air Passengers NLinear ()](https://user-images.githubusercontent.com/15316026/204397880-4cd3f2df-e867-4de7-84e1-6c796febf44d.png)

### With Future covariates
```python
  encoders = {
      "datetime_attribute": {"past": ["month", "year"], "future": ["month", "year"]},
      "position": {"past": ["relative"], "future": ["relative"]},
      "transformer": Scaler(StandardScaler(), n_jobs=-1),
  }
```


![Forecast_Air Passengers NLinear ()](https://user-images.githubusercontent.com/15316026/204397928-5f12cf21-c6d8-47f6-b399-2645ebf4b071.png)
![Backtest_Air Passengers NLinear ()](https://user-images.githubusercontent.com/15316026/204397911-7299e144-b5d3-4e8a-b212-9926b77c0eed.png)


It is interesting that `predict()` performs much better with the future covariates but much worse with the `historical_forecasts()`

**Comment by gdevos010** [comment]
Here's a script. You can switch the encoders to toggle the future covariates.

```Python
    from darts.models import NLinearModel
    from darts.datasets import AirPassengersDataset
    import pandas as pd
    from darts.dataprocessing.transformers import Scaler
    from pytorch_lightning.callbacks import EarlyStopping
    from darts.metrics import mse
    from matplotlib import pyplot as plt
    from sklearn.preprocessing import StandardScaler
    from torchmetrics import MeanSquaredError
    from torchmetrics import MetricCollection

    # Read data:
    series = AirPassengersDataset().load()

    # Create training and validation sets:
    cutoff = pd.Timestamp(year=1957, month=12, day=1)
    train, val = series.split_after(cutoff)

    # Normalize the time series (note: we avoid fitting the transformer on the validation set)
    transformer = Scaler(StandardScaler(), n_jobs=-1)
    transformer.fit(train)
    series = transformer.transform(series)
    train = transformer.transform(train)
    val = transformer.transform(val)

    encoders = {
        "datetime_attribute": {"past": ["month", "year"]},
        "position": {"past": ["relative"]},
        "transformer": Scaler(StandardScaler(), n_jobs=-1),
    }

    # encoders = {
    #     "datetime_attribute": {"past": ["month", "year"], "future": ["month", "year"]},
    #     "position": {"past": ["relative"], "future": ["relative"]},
    #     "transformer": Scaler(StandardScaler(), n_jobs=-1),
    # }


    # Early stop callback

    early_stop = EarlyStopping(
        monitor="val_MeanSquaredError",
        patience=30,
        min_delta=0.05,
        mode="min",
    )
    pl_trainer_kwargs = {"callbacks": [early_stop], "accelerator": "gpu", "devices": -1, "auto_select_gpus": True}

    # Create the model

    model = NLinearModel(
        input_chunk_length=24,
        output_chunk_length=12,
        batch_size=32,
        add_encoders=encoders,
        torch_metrics=MetricCollection([MeanSquaredError()]),
        pl_trainer_kwargs=pl_trainer_kwargs,
        n_epochs=5000, )

    model.fit(
        series=train,
        val_series=val,
    )

    backtest = model.historical_forecasts(
        series=series,
        start=cutoff,
        forecast_horizon=6,
        num_samples=1,
        retrain=False,
        verbose=True,
    )
    forcast = model.predict(
        n=36,
        series=train,
        num_samples=1,
        n_jobs=-1,
    )

    series.plot(label="actual")
    forcast.plot(label="predict")
    backtest.plot(label="historical_forecasts")

    plt.legend()

    plt.show()
    print(
        f"predict: MSE = {mse(series, backtest):.3f}"
    )
    print(
        f"forcast: MSE = {mse(series, forcast):.3f}"
    )
```

**Comment by hrzn** [comment]
Thanks for the example @gdevos010. I've looked into it and I know what the issue is. When calling `predict()` with `n >= output_chunk_length`, the full future covariates are available to the forward pass. However, when `n < output_chunk_length` (as is the case when calling `historical_forecasts()` with `forecast_horizon=6`), only `n` values of the future covariates are available, and the remaining `n - output_chunk_length` are 0-padded, which in this cases causes a bias in the resulting output. I think a fix would be to make the treatment of future covariates "causal" - i.e., so that the output at time t does not require the future covariates for any time step larger than t. I'll work on this and propose something.
