### ISSUE TITLE
Future Covariates? How to predict with future covariates?

### ISSUE THREAD

**Issue by optionsraghu** [unit8co/darts#1395]
Hi,

I was following your excellent documentation on the Air/Milk example on building covariates model using the RNN. I am stuck at one thing as follows: I am unable to predict the target values in the future based on the future covariate values (which we saved earlier by splitting into train and val). I tried the following but I get this error. Am I understanding the prediction incorrectly?

Given a model that is trained with a couple of covriates in the past, please predict the future target values based on the future covariates. This is what I am trying to achieve...
*************************************************************************************************

pred_covrnn = model_covrnn.predict(n=10, series=val_air, future_covariates=air_val_covariates)

series_air_scaled.plot(label="actual")
pred_cov.plot(label="forecast")
plt.legend()

ValueError: The model has been trained with past covariates. Some matching past_covariates have to be provided to `predict()`.

Thank you
Raghu

**Comment by eliane-maalouf** [comment]
hello, 
the error seems to be related to the fact that the model was trained with past covariates which are not provided at prediction time. This error would occur if your horizon length n is larger than the output chunk length with which you have created the model, is this the case? maybe this [article ](https://unit8.com/resources/time-series-forecasting-using-past-and-future-external-data-with-darts/) could also be of interest to you.

**Comment by optionsraghu** [comment]
Hi @eliane-maalouf , many thanks for response. What I am unable to understand is where do you pass the validation set in fitting the model please? I saw from the documentation tutotials that while there is a split happening between train/validation data sets , at the time of fitting you are only using the train dataset. Does Darts take care of this internally please?
In a similar context if you look at how pytorch-lightning fits a stack model such as this, the fit method takes the validation dataset also as an argument. Hence the confusion. Can you pls explain? Thanks a lot.

**Comment by eliane-maalouf** [comment]
hello, are you working with a specific model ? 
In general, at prediction time, the features and the covariates (past and/or future) are passed as arguments to the predict() function of the model. Please refer to the documentation of the model you are interested in to see what type of covariate it accepts for prediction. Furthermore, indeed Darts allows to select the split for the target only, but it automatically selects the correct covariates at time of training or prediction (it intersects the time indices between the different series).

**Comment by optionsraghu** [comment]
Thank you @eliane-maalouf  and @hrzn . I am still getting used to the lingo of Darts. I am getting stuck in my understanding when I am predicting with a model. However, I will send a detailed script re that this week. Meanwhile, I am stuck at an more mundane level which is this. I inittially thought of posting this in stackoverflow but I realized that there is an unanswered Darts question for about 5 months on Stackoverflow. Here is my issue:

![image](https://user-images.githubusercontent.com/15772927/208241403-01ac5aab-a0e5-44af-a754-368e64cb1c6d.png)

I have a date column as you see which is pd datetime on a df. When I tried converting into series I get :
ValueError: The time index of the provided DataArray is missing the freq attribute, and the frequency could not be directly inferred. This probably comes from inconsistent date frequencies with missing dates. If you know the actual frequency, try setting `fill_missing_dates=True, freq=actual_frequency`. If not, try setting `fill_missing_dates=True, freq=None` to see if a frequency can be inferred.

These are company specific dates so the freq is Business day . When I tried to force it to business days it complains. Can you please guide me on this?

Thank you

**Comment by optionsraghu** [comment]
Hi @hrzn @eliane-maalouf ; I am new to Darts and still playing with it. I have a basic query. I am using deeptcn to predict a simple time series with covariates. After fitting when I predict, I use three different arguments each time to see prediction values. The arguments for past_covariates I use are , train_covariates, all_covariates and None. The results of prediction in each case is different. I am confused as to how the model treats each of these input arguments in prediction. 
![tcn_covariates_arguments](https://user-images.githubusercontent.com/15772927/210282021-b57800e7-e6f6-48a3-b6ee-fca4d96a2d3b.jpg)

PLease can you kindly explain how does the model treat these arguments? Interestingly, I used a similar approach to N-Beats and in that context the prediction results are same. 

Thank you for your kind guidance.

**Comment by hrzn** [comment]
> Thank you @eliane-maalouf and @hrzn . I am still getting used to the lingo of Darts. I am getting stuck in my understanding when I am predicting with a model. However, I will send a detailed script re that this week. Meanwhile, I am stuck at an more mundane level which is this. I inittially thought of posting this in stackoverflow but I realized that there is an unanswered Darts question for about 5 months on Stackoverflow. Here is my issue:
> 
> ![image](https://user-images.githubusercontent.com/15772927/208241403-01ac5aab-a0e5-44af-a754-368e64cb1c6d.png)
> 
> I have a date column as you see which is pd datetime on a df. When I tried converting into series I get : ValueError: The time index of the provided DataArray is missing the freq attribute, and the frequency could not be directly inferred. This probably comes from inconsistent date frequencies with missing dates. If you know the actual frequency, try setting `fill_missing_dates=True, freq=actual_frequency`. If not, try setting `fill_missing_dates=True, freq=None` to see if a frequency can be inferred.
> 
> These are company specific dates so the freq is Business day . When I tried to force it to business days it complains. Can you please guide me on this?
> 
> Thank you

This is probably because your dataframe has some missing dates and so does not conform to a Business day frequency. You could maybe try `fill_missing_dates=True, freq=actual_frequency` which (if it works) will fill the missing dates with NaN.



> Hi @hrzn @eliane-maalouf ; I am new to Darts and still playing with it. I have a basic query. I am using deeptcn to predict a simple time series with covariates. After fitting when I predict, I use three different arguments each time to see prediction values. The arguments for past_covariates I use are , train_covariates, all_covariates and None. The results of prediction in each case is different. I am confused as to how the model treats each of these input arguments in prediction. ![tcn_covariates_arguments](https://user-images.githubusercontent.com/15772927/210282021-b57800e7-e6f6-48a3-b6ee-fca4d96a2d3b.jpg)
> 
> PLease can you kindly explain how does the model treat these arguments? Interestingly, I used a similar approach to N-Beats and in that context the prediction results are same.
> 
> Thank you for your kind guidance.

We would need a reproducible code snippet to understand what's happening. Note that fitting deep learning model is in general stochastic due to random initialisation.
