### ISSUE TITLE
"Encoders"-code in the Quickstart tutorial is not working

### ISSUE THREAD

**Issue by Quaterion** [unit8co/darts#1396]
The code from the quickstart tutorial on [encoders](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Encoders:-using-covariates-for-free) trains Nbeats on "Air" and "Milk" time series. Only the forecasts for "Air" are shown in the tutorial. For the Milk data the forecasts are erratic. Is there are reason for this? 

[See the plot of the forecasts](https://freeimage.host/i/HKPbELF)

The code is like in the tutorial but both series are plotted: 

        import numpy as np
        from darts.datasets import AirPassengersDataset, MonthlyMilkDataset
        import matplotlib.pyplot as plt
        from darts.dataprocessing.transformers import Scaler
        from darts.models import NBEATSModel
        
        series_air = AirPassengersDataset().load().astype(np.float32)
        series_milk = MonthlyMilkDataset().load().astype(np.float32)
        
        # set aside last 36 months of each series as validation set:
        train_air, val_air = series_air[:-36], series_air[-36:]
        train_milk, val_milk = series_milk[:-36], series_milk[-36:]
        
        scaler = Scaler()
        train_air_scaled, train_milk_scaled = scaler.fit_transform([train_air, train_milk])
        
        encoders = {'datetime_attribute': {'past': ['month', 'year']}, 'transformer': Scaler()}
        
        model = NBEATSModel(
            input_chunk_length=24,
            output_chunk_length=12,
            add_encoders=encoders,
            random_state=42,
        )
        
        model.fit([train_air_scaled, train_milk_scaled], epochs=50, verbose=True)
        
        pred_air = model.predict(series=train_air_scaled, n=36)
        pred_milk = model.predict(series=train_milk_scaled, n=36)
        pred_air, pred_milk = scaler.inverse_transform([pred_air, pred_milk])
        
        plt.figure(figsize=(10, 6))
        series_air.plot(label="actual (air)")
        series_milk.plot(label="actual (milk)")
        pred_air.plot(label="forecast (air)")
        pred_milk.plot(label="forecast (milk)")

**Comment by Quaterion** [comment]
Using version 0.22 everything is fine like you describe. Using version 0.21 though gives me the output that I generated above. 
Thanks.

**Comment by mkpds** [comment]
I am trying scaler.inverse_transform for my predicted series, but it gives a broadcasting error for shape . As my inputvis one series and output is same series how can there be a shape error. Need help to fix

**Comment by alexcolpitts96** [comment]
@mkpds can't help without code.

**Comment by mkpds** [comment]
thank you for your quick reply
here goes the code
#### converting dataframe to timeseries ####

series_revenue = TimeSeries.from_dataframe(df2, time_col ='Date', value_cols='logRevenue')
series_sessions = TimeSeries.from_dataframe(df3, time_col ='Date', value_cols='logSessions')
series_transactions = TimeSeries.from_dataframe(df4, time_col ='Date', value_cols='logTransactions')
series_holidays = TimeSeries.from_dataframe(df_holidays, time_col ='date', value_cols='holidays')
series_covid = TimeSeries.from_dataframe(df_covid, time_col ='date', value_cols='covid')

### stacking both covariates together ###
series_holidays =series_holidays.stack(series_covid)

### Normalaising data timeseries to same scale a splitting data to test and train ###


train_rev, val_rev = series_revenue[:-50], series_revenue[-50:]
train_ses, val_ses =series_sessions [:-50], series_sessions[-50:]
train_tran,val_tran =series_transactions[:-50],series_transactions[-50:]
print(train_rev.has_datetime_index)

# Normalize the time series (note: we avoid fitting the transformer on the validation set)
transformer = Scaler(MaxAbsScaler())
train_rev_transformed = transformer.fit_transform(train_rev)
val_rev_transformed= transformer.fit_transform(val_rev)
series_rev_transformed = transformer.transform(series_revenue)
print(train_rev_transformed.head())


train_ses_transformed = transformer.fit_transform(train_ses)
val_ses_transformed = transformer.transform(val_ses)
series_ses_transformed = transformer.transform(series_sessions)


train_tran_transformed = transformer.fit_transform(train_tran)
val_tran_transformed = transformer.transform(val_tran)
series_tran_transformed = transformer.transform(series_transactions)

###normalising covariates ####
holidays_scaled = transformer.fit_transform(series_holidays)
training_holidays_scaled = holidays_scaled[:-10]

model_lreg = LinearRegressionModel(lags=[-65], 
    lags_past_covariates=[-5,-4, -3, -2, -1], 
    lags_future_covariates=[-3,-2,-1, 0], 
    output_chunk_length=10, 
    likelihood=None,
    quantiles=None, 
    random_state=0, 
    multi_models=True
)


## fitiing the model on timeseries ##

model_lreg.fit(series=[train_rev_transformed,train_ses_transformed, train_tran_transformed], past_covariates=[training_holidays_scaled, training_holidays_scaled, training_holidays_scaled], future_covariates=[holidays_scaled ,holidays_scaled ,holidays_scaled ] ) 


pred_rev_l = model_lreg.predict(n = 50, series = train_rev_transformed, past_covariates=training_holidays_scaled, future_covariates=holidays_scaled )
print(len(pred_rev_l))
pred_ses_l = model_lreg.predict(n =50, series = train_ses_transformed, past_covariates=training_holidays_scaled, future_covariates=holidays_scaled )
pred_tra_l = model_lreg.predict(n =50, series = train_tran_transformed,past_covariates=training_holidays_scaled,future_covariates=holidays_scaled )

### works well up until here ###

# # Predictions denormalised  throws error###

revenue_logpredict1 = transformer.inverse_transform( pred_rev_l)

error "ValueError: non-broadcastable output operand with shape (50,1) doesn't match the broadcast shape (50,2)"

I am  unable to resolve this error

**Comment by mkpds** [comment]
Resolved thanks anyways
