### ISSUE TITLE
[BUG] Pandas FutureWarning in TimeSeries.from_group_dataframe(...)

### ISSUE THREAD

**Issue by felixdivo** [unit8co/darts#1410]
**Describe the bug**
A `FutureWarning` is produced by pandas. This is just a "heads-up".

**To Reproduce**
Use `TimeSeries.from_group_dataframe` with `len(group_cols) == 1`. [This line](https://github.com/unit8co/darts/blob/0.22.0/darts/timeseries.py#L744) then triggers this warning:
```
/opt/conda/lib/python3.10/site-packages/darts/timeseries.py:744: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for static_cov_vals, group in df.groupby(group_cols):
```

**Expected behavior**
No warning is printed.

**System (please complete the following information):**
 - Python version: `3.10`
 - darts version `0.22.0`
 - pandas version `1.5.2`

**Comment by dennisbader** [comment]
@felixdivo thanks for the heads up.
Will be fixed with #1416
