### ISSUE TITLE
About Forecast Range Values

### ISSUE THREAD

**Issue by Lufffya** [unit8co/darts#1414]
According to the training of the model, I got the prediction of the model for the future, but it is a specific value. If I also want to get the prediction of the model for the value range, what should I do?
I observed that there are models with range prediction, like Probabilistic RNN, is the range prediction only for the specified model, or can any model predict the range?
Thank you!!!

**Comment by dennisbader** [comment]
Hey @Luffffffy . You can find a table for which models support probabilistic forecasts [here](https://unit8co.github.io/darts/index.html#forecasting-models).

You can follow the guides [here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Probabilistic-forecasts) and [here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#With-neural-networks) on how to get stochastic forecasts.
