### ISSUE TITLE
Covariates Argument to MixedCovariatesSequentialDataset[BUG]

### ISSUE THREAD

**Issue by nilsleh** [unit8co/darts#1417]
**Describe the bug**
Based on the [documentation](https://unit8co.github.io/darts/generated_api/darts.utils.data.sequential_dataset.html#darts.utils.data.sequential_dataset.MixedCovariatesSequentialDataset), `MixedCovariatesSequentialDataset` accepts `covariates` as a parameter, but that does not work as the [source code](https://github.com/unit8co/darts/blob/7d8143c055dac6281e7e587117709d5b94250a0c/darts/utils/data/sequential_dataset.py#L271) expects `past_covariates` and `future_covariates`. I think I have the correct version of the documentation since it is the link from this github repo. Looking at the source code, the parameter section contains `covariates` but the function accepts `past_covariates` and `future_covariates`. If this is confirmed I could open a PR to correct this.

**To Reproduce**
```
from darts.utils.data.sequential_dataset import MixedCovariatesSequentialDataset
ds = MixedCovariatesSequentialDataset(target_series=targets, covariates=covariate_series)
```

**Expected behavior**
Consistency between the documentation and source code.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version 0.22.0

**Comment by dennisbader** [comment]
Hey @nilsleh , and thanks for reporting this.
`MixedCovariatesSequentialDatasat` indeed accepts `past_covariates` and `future_covariates`. 
The docstring is wrong.

Yes, we would be happy to receive a PR on this :) Thanks!
You can use `SplitCovariatesSequentialDataset` as a reference.
