### ISSUE TITLE
Custom data freq issue when using TimeSeries

### ISSUE THREAD

**Issue by Niharikajo** [unit8co/darts#1418]
Hello,

I am trying to do multivariate time series forecasting on a custom dataset.

My dataset has a frequency of 2min but there are some variations in milliseconds as well in the dataset. So when I set the 
`freq=2min`, I am getting  `ValueError: Could not find a unique inferred frequency (not constant).`
This is the  [dataset](https://github.com/unit8co/darts/files/10191647/calce_channel_61_1.xlsx).
Is there any way to get around this?

Can you please help with this issue

Thank you
Niharika Joshi

**Comment by dennisbader** [comment]
Hi @Niharikajo. In the dataset, there are also other irregularities in the 2min frequency even when ignoring the seconds.

For example only a 1m-min step after 06/03/208 19:39:42.000 which doesn't happen every day.
In general, the minutes recorded each differ from each other.

If each day has the same number of time steps, and there are no drastic changes from these 1-minute shifts across the individual days, I would suggest to ignore the DatetimeIndex and use a RangeIndex instead.

For this, you can index your dataframe with a RangeIndex and then use `TimeSeries.from_dataframe(df, value_cols=my_value_cols, ...)`. You don't have to pass a `time_col` and make sure to remove the timestep column from `my_value_cols`.
