### ISSUE TITLE
Regarding lags used in forecasting

### ISSUE THREAD

**Issue by luizfysouza** [unit8co/darts#1421]
In many models, such as TCN, I have to provide "input_chunk_length" and "output_chunk_length".

Output is fine, I want to predict my target variable using the other variables (multivariate) in t+1.

However, I'd like to use variables in t to predict target in t+1, and I am not able to do that.

If i set "input_chunk_length"  = 1, the model complains that kernel size must be strictly smaller than input_chunk, so it is not possible.

Is there some way to use exogenous variables in t to predict target in t+1?

**Comment by alexcolpitts96** [comment]
Correct me if I am wrong, but you are looking to use covariate (or exogenous) features to predict your target variable without the need to have targe variable history? In other words, you might be wanting to predict shovel sails based on snow fall?

To my knowledge darts doesn't natively support this; however, you can easily write a custom dataloader and pass that to a model for training. All of the models I have looked at have model.fit_from_dataset() which takes a darts.utils.data.TrainingDataset. 

If you are familiar with torch or pytorch-lightning dataloader classes, darts' implementation is almost identical. 
https://unit8co.github.io/darts/_modules/darts/utils/data/training_dataset.html#TrainingDataset
