### ISSUE TITLE
How to obtain the range value predicted by the probability model？

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1425]
The result I obtained by using the probability model forecast, but I don't know how to get the value of the upper and lower boundaries of the probability from the result, the value in the document gives the result in the plot, I don't know how to get
![image](https://user-images.githubusercontent.com/49063302/207002359-3789e3ba-849c-4e2e-b7f9-ea1c9c372a24.png)

**Comment by dennisbader** [comment]
You can use `TimeSeries.min()` from [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.min) and `TimeSeries.max()` from [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.max).
