### ISSUE TITLE
How to Change the Bounding Range of Probabilistic Forecasts？

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1426]
In this plot example
![image](https://user-images.githubusercontent.com/49063302/207009169-71323ecb-78d5-4e7c-b71c-cb17f1a6b948.png)
I want to change the range of the light blue forecast(Make its range very wide or very narrow, in specific scenarios), how do I need to do it

In the case of probabilistic predictions:
`pred[0].map(lambda x: x)` at this time, x is Probabilistic values
`x = pred[0].values()`  x is Forecasts values
they have different dimensions，why is this?

**Comment by dennisbader** [comment]
You can use `TimeSerie.all_values()` to get all values, see the [docs here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.all_values).

For plotting specific quantile ranges, please read the `TimeSeries.plot()` docs [from here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.plot).
