### ISSUE TITLE
[BUG] TorchForecastingModel save and load checkpoint

### ISSUE THREAD

**Issue by nilsleh** [unit8co/darts#1430]
**Describe the bug**
I am not sure whether this is a bug or stemming from a lack of understanding from the documentation. I also don't know if it is related to  #1424. As I want to train a TorchForecastingModel on a large collection of time-series datasets, I need to save and load checkpoints. I have tried the code snippet in the [documentation](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#saving-and-loading-model-states) of saving and loading model states, hower, that suggestion yields `FileNotFoundError: There is no file matching prefix best-* in work_dir/my_model/checkpoints`. Leaving out the `best=True` flag to `my_model.load_from_checkpoint()` yields the same error.  Additionally, the docmentation states that setting `save_checkpoints=True`, "keeps track of the best performing model on the validation set and the latest 5 epochs", but what validation metric is being tracked and is there any control over that?

There is also [documentation](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.pl_forecasting_module.html?highlight=modelcheckpoint#darts.models.forecasting.pl_forecasting_module.PLMixedCovariatesModule.configure_callbacks) about using pytorchLighting's `ModelCheckpoint`, however, when using that with `darts_model.fit(..., trainer=pl_trainer)` and then trying `darts_model.load_from_checkpoint(path_to_lighting_ckpt)` I get `ValueError: Could not find base model save file '_model.pth.tar' in checkpoint_path`. If I do `darts_model.model.load_from_checkpoint(path_to_lightning_ckpt)` there is no error, but it does not seem like the weights were loaded because if I inspect the weights before and after loading they are the same.

**To Reproduce**
I have made a `save_checkpoint=True` [gist](https://gist.github.com/nilsleh/e6d095c3f0419bf5fb3e6b011b926321) with a small example based on the [TFT example](https://unit8co.github.io/darts/examples/13-TFT-examples.html) and a vers ion with pytorch lightning`ModelCheckpoint` [gist](https://gist.github.com/nilsleh/d3c35985ab23a3ada433d0cd4b5a0d7e).

**Expected behavior**
Be able to load a model checkpoint from a "ckpt_path" and be able to specify based on what metric a best model checkpoint is saved during training.

**System (please complete the following information):**
 - Python version:  3.9
 - darts version 0.22.0

**Additional context**
I think I searched the documentation fairly extensively on how to properly save and load checkpoints but could not find that information or get it to work. However, it's of course possible that I missed it or that there is a simple suggested way to do this for TorchForecastingModels, in which case I'd be grateful to find out.

**Comment by dennisbader** [comment]
Hi @nilsleh. It should work if you pass the work_dir you set at model creation to `load_from_checkpoint()` in gist 1 :) 

Also for reference, see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.load_from_checkpoint).

**Comment by nilsleh** [comment]
Thank you for your reply. Sorry I had missed the work_dir part. Is there control over which metric is being tracked when using `save_predictions=True`?

**Comment by dennisbader** [comment]
With the built in  `save_checkpoints=True` it will automatically use the `val_loss` if available, otherwise `train_loss`
