### ISSUE TITLE
Getting prediction as NaN for all models. 

### ISSUE THREAD

**Issue by whoopydev** [unit8co/darts#1438]
Hey guys, 

I've just started using Darts and I'm getting NaN for all my predictions and loss function. I've tried with NBeats, Theta and TFM, and I'm getting the same results for all. 

I've read the issues here and I understand that non-continuous data might be a problem since my data is non-continuous. However, I used the following method to fill the gaps: 

```
series_dow = TimeSeries.from_dataframe(df1, "Date", " Close", fill_missing_dates=True, freq="B")
```
Don't know if this helps, but this is what Colab recommended. 

For reference, my dataset it the dow-jones from 2000-2022 (daily), so all the missing dates are bank-holidays/weekends.

Any help would be greatly appreciated, thanks!

**Comment by dennisbader** [comment]
`fill_missing_dates` inserts missing dates (time stamps) into the index. The values for the new entries are set to NaN.

You can check out [this here](https://unit8co.github.io/darts/generated_api/darts.utils.missing_values.html#utils-for-filling-missing-values) to learn more about how you can fill the missing values.

**Comment by whoopydev** [comment]
Thank you so much!
