### ISSUE TITLE
[BUG] TqdmDeprecationWarning

### ISSUE THREAD

**Issue by betizad** [unit8co/darts#144]
When fitting a LSTM Model I get the folowing warning which I guess can be overcome by an update of the library. Nothing serious as everything runs so far. Just could be an issue in the 5.0 release of tqdm.

`lib/python3.6/site-packages/darts/utils/utils.py:74: TqdmDeprecationWarning:`

`This function will be removed in tqdm==5.0.0`
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`

 - Python version: [e.g. 3.6]
 - darts version [e.g. 0.2.1]

**Comment by TheMP** [comment]
Hello @betizad, than you for your input! The PR #147 was merged to develop, and it will resolve the issues in the next release of Darts - version 0.3.0.
