### ISSUE TITLE
[BUG] Loading Torch model created with 0.22.0 in 0.23.0 fails

### ISSUE THREAD

**Issue by solalatus** [unit8co/darts#1443]
**Describe the bug**
Loading Torch model created with 0.22.0 in 0.23.0 fails

**To Reproduce**
Get a previous checkpoint that was saved with 0.22.0 and try ton use `load_from_checkpoint`. 

The error will be: `ModuleNotFoundError: No module named 'darts.utils.data.encoders'
`

**Expected behavior**
Load the model without a problem

**System (please complete the following information):**
 - Python Current Version:- 3.8.16 (default, Dec  7 2022, 01:12:13)  [GCC 7.5.0] - Colab Default
 - darts version: 0.23.0

**Additional context**

**Comment by dennisbader** [comment]
This is expected, you would have to train/save the model again with darts==0.23.0 to be able to load it in v0.23.0.

We changed the encoder module path in v0.23.0. Also, we made some improvements to saving/loading with our TorchForecastingModels.

We try to continuously improve the library and cannot always guarantee backwards compatibility for save files (yet). If you rely on this save file, you can revert the darts version to 0.22.0

**Comment by solalatus** [comment]
I see. Thanks for the input. Can you think of any way to transfer a 0.22 loaded model to 0.23? The backtest on multiple series feature is rather nice, I would definitely use it! (Model trains for over a week, so not really happy to retrain...)

**Comment by dennisbader** [comment]
Hmm.. There might be a way (haven't tested it though).

When you use `save_checkpoints=True` at model creation, Darts will generate at least two files:
1) TorchForecastingModel file **_model.pth.tar**: you need to replace this file from v22 with one from v23.
2) some checkpoints files in **checkpoints** ending with **.ckpt**: you can continue using the ones from v22 in v23. Just pick the one you actually load when calling `load_from_checkpoint()`

Now for point 1):
- **In v23** just setup the model the same way you did when you fit the model in v22 (`save_checkpoints` must be enabled).
Make sure you give it a different `work_dir` or `model_name` for it to not overwrite the previous model save.
- start fitting the model. You will see, that darts generates the file from 1) just before beginning the training process. Now you can cancel training.
- replace the **_model.pth.tar** in your v22 model dir with the one just created by v23.
- try loading the model again

Hope this helps.

**Comment by solalatus** [comment]
Thanks for the input!

I tried it, and sadly, the result is the same: `ModuleNotFoundError: No module named 'darts.utils.data.encoders'` 

Which I interpret: some more hacking inside the _model.pth.tar is the only way maybe?

**Comment by solalatus** [comment]
Thanks for the input, it works!

**Comment by solalatus** [comment]
Curious, though, that when I use 0.22.0 or the above detailed method, there are differences in the predictions on the same data. Not drastic, but absolutely not negligable. Since this is a hacky use case, I am not complaining at all, just wanted to inform - maybe of interest.

**Comment by dennisbader** [comment]
If using a probabilistic forecasts, it probably has to do with the random state of the v22 saved model vs v23.
Even two consecutive predictions calls can give slighty different results.

**Comment by solalatus** [comment]
I use a NHiTS model with no probabilistic output.
