### ISSUE TITLE
[BUG] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by johnnyb1509** [unit8co/darts#1446]
**Describe the bug**
I have trained the model TFT using GPU by specified the config in pl_kwags

```
pl_kwarg = {"accelerator": "gpu",
            "log_every_n_steps":30}
```
Then, after I restart the kernel and call the model as well as data by the code below 
```
exogs_test = TimeSeries.from_dataframe(data_use[exogs])
endogs_test = TimeSeries.from_series(data_use[endog])

model = TFTModel(
                              input_chunk_length = 18, 
                               output_chunk_length=3
                             ).load_from_checkpoint('my-path-to-repository/darts_logs/experiment_11', best = True)

pred = model.historical_forecasts(series = endogs_test, past_covariates = exogs_test, forecast_horizon= 3, stride = 1, retrain = True)
```
It produced the Runtime Error 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I'm actually not sure this problem is a bug or if I have any wrong code

**To Reproduce**
Just try the code above

**Expected behavior**
Expect it will run and retrain the model on the given dataset

**System (please complete the following information):**
 - Python version: 3.9
 - darts version 0.22

**Additional context**
I'm wondering that, how to save the retrained model. For example, I have the model ```model``` which is trained on ```dataset_A```, then after I run successfully the ```model.historical forecasts(series = dataset_B, retrain=True)``` using ```dataset_B```, it then produces the new checkpoint in the model saving directory. Finally, I would like to save the model which it contains updated weights on ```dataset_B``` only. So how can I save the model? Which checkpoint will it use to save to the <modelName>.pt?

**Comment by dennisbader** [comment]
The RunTimeError is already fixed in darts==0.23.0. If you update your darts version it should work.

About historical forecasts: with retrain=True, it creates a new model object and trains it on the iteration's corresponding input time window. So if you just want to train on dataset B, I would recommend calling fit() again.

For saving and loading, you can find the documentation [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.save), and [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.load).

**Comment by johnnyb1509** [comment]
> The RunTimeError is already fixed in darts==0.23.0. If you update your darts version it should work.
> 
> About historical forecasts: with retrain=True, it creates a new model object and trains it on the iteration's corresponding input time window. So if you just want to train on dataset B, I would recommend calling fit() instead.
> 
> For saving and loading, you can find the documentation [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.save), and [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.load).

I have updated to 0.23.0 but it still renders this error

**Comment by dennisbader** [comment]
Are you loading from a checkpoint that was created in darts 0.22.0 or are you reacreating it in 0.23.0?

Also, can you verify that it is indeed using 0.23.0?

```
import darts

print(darts.__version__)
```

**Comment by johnnyb1509** [comment]
> Are you loading from a checkpoint that was created in darts 0.22.0 or are you reacreating it in 0.23.0?
> 
> Also, can you verify that it is indeed using 0.23.0?
> 
> ```
> import darts
> 
> print(darts.__version__)
> ```

Yes, I rerun all the training process on version 0.23 instead reuse the pretrained model on 0.22.

I event train the model on several dataset, and the ```RunTimeError``` is occured whenever call the model from the last checkpoint to continuously train on new dataset. Specifically, the code is as below

```
is_first = True
new_epoch = n_epochs
for i in range(len(dataCache['endog_train'])):
    time_start = dt.strftime("%Y-%m-%d %H:%M:%S")
    logging.info(f"----- TRAINING ON DATASET {i}")
    logging.info(f" ----- is 1st run {is_first}")
    if is_first==True:
        model.fit(
            series= dataCache['endog_train'][i],
            past_covariates = dataCache['exogs_train'][i],
            val_series = dataCache['endog_valid'][i],
            val_past_covariates = dataCache['exogs_valid'][i],
            verbose = True
                )
        is_first = False
    elif is_first == False:
        logging.info(f"----- CONTINUE TRAINING FROM THE LAST CHECKPOINT")
        model = TFTModel.load_from_checkpoint(os.path.join(os.getcwd(), f"darts_logs/{modelName}"), best=False)
        model.fit(
                series= dataCache['endog_train'][i],
                past_covariates = dataCache['exogs_train'][i],
                val_series = dataCache['endog_valid'][i],
                val_past_covariates = dataCache['exogs_valid'][i],
                verbose = True,
                epochs = new_epoch
                    )
    new_epoch += n_epochs
```

It produces the Error
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)

File ~/anaconda3/envs/model_build/lib/python3.9/site-packages/darts/utils/torch.py:112, in random_method.<locals>.decorator(self, *args, **kwargs)
    110 with fork_rng():
    111     manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
--> 112     return decorated(self, *args, **kwargs)

File ~/anaconda3/envs/model_build/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py:755, in TorchForecastingModel.fit(self, series, past_covariates, future_covariates, val_series, val_past_covariates, val_future_covariates, trainer, verbose, epochs, max_samples_per_ts, num_loader_workers)
    747 logger.info(f"Train dataset contains {len(train_dataset)} samples.")
    749 super().fit(
    750     series=seq2series(series),
    751     past_covariates=seq2series(past_covariates),
...
-> 1123     (self.quantiles_tensor - 1) * errors, self.quantiles_tensor * errors
   1124 )
   1126 return losses.sum(dim=dim_q).mean()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by dennisbader** [comment]
Loading the model directly to gpu should fix it:

```
import torch
...
        model = TFTModel.load_from_checkpoint(
            os.path.join(os.getcwd(),
            f"darts_logs/{modelName}"),
            best=False,
            map_location=torch.device("cuda:0"),
)
```

**Comment by johnnyb1509** [comment]
> Loading the model directly to gpu should fix it:
> 
> ```
> import torch
> 
> ...
>         model = TFTModel.load_from_checkpoint(
>             model_name=my_model_name,
>             work_dir=my_model_work_dir,
>             best=False,
>             map_location=torch.device("cuda:0"),
>         )
> ```

Thank you so much, the thread is closed here!
