### ISSUE TITLE
Make StatsForecastETS probabilistic

### ISSUE THREAD

**Issue by Beerstabr** [unit8co/darts#1448]
I really like the recent addition of StatsForecastETS to Darts because it's fast and allows for future covariates. Moreover, I'm looking forward to the inclusion of more StatsForecast models like AutoTheta (and I wouldn't mind helping out since it seems to be within my coding grasp). 

However, currently StatsForecastETS is not probabilistic while the Statsforecast implementation does allow for it. Would it be possible to make in probabilistic in Darts too? That seems doable? Or am I missing something?

**Comment by Beerstabr** [comment]
Couldn't it be solved in the same way as with [StatsForecastARIMA](https://unit8co.github.io/darts/_modules/darts/models/forecasting/sf_auto_arima.html#StatsForecastAutoARIMA):

```python
def _predict(
        self,
        n: int,
        future_covariates: Optional[TimeSeries] = None,
        num_samples: int = 1,
        verbose: bool = False,
    ):
        super()._predict(n, future_covariates, num_samples)
        forecast_df = self.model.predict(
            h=n,
            X=future_covariates.values(copy=False) if future_covariates else None,
            level=(68.27,),  # ask one std for the confidence interval.
        )

        mu = forecast_df["mean"]
        if num_samples > 1:
            std = forecast_df["hi-68.27"] - mu
            samples = np.random.normal(loc=mu, scale=std, size=(num_samples, n)).T
            samples = np.expand_dims(samples, axis=1)
        else:
            samples = mu

        return self._build_forecast_series(samples)
```

**Comment by hrzn** [comment]
> Couldn't it be solved in the same way as with [StatsForecastAutoARIMA](https://unit8co.github.io/darts/_modules/darts/models/forecasting/sf_auto_arima.html#StatsForecastAutoARIMA):
> 
> ```python
> def _predict(
>         self,
>         n: int,
>         future_covariates: Optional[TimeSeries] = None,
>         num_samples: int = 1,
>         verbose: bool = False,
>     ):
>         super()._predict(n, future_covariates, num_samples)
>         forecast_df = self.model.predict(
>             h=n,
>             X=future_covariates.values(copy=False) if future_covariates else None,
>             level=(68.27,),  # ask one std for the confidence interval.
>         )
> 
>         mu = forecast_df["mean"]
>         if num_samples > 1:
>             std = forecast_df["hi-68.27"] - mu
>             samples = np.random.normal(loc=mu, scale=std, size=(num_samples, n)).T
>             samples = np.expand_dims(samples, axis=1)
>         else:
>             samples = mu
> 
>         return self._build_forecast_series(samples)
> ```

Hi @Beerstabr, definitely! I'm not quite sure this approach worked with statsforecast at the time when I implemented `StatsForecastETS`. But if it works now, by all means we should do it. Would you be willing to open a PR with your proposed change? That would be very welcome.
Bonus: we could perhaps factor out some of the code needed to call & handle the statsforecast models somewhere (maybe by regrouping all the SF models in a single file and extracting a couple of functions).
Adding more SF models is also welcome too :) We have an item on our backlog for this: https://github.com/unit8co/darts/issues/1402 But a simple PR to make ETS stochastic would already be nice.

**Comment by Beerstabr** [comment]
Great! I'll work on it. Making ETS stochastic should definitely work out. 
And I could also add AutoTheta and AutoCES.

While doing that I could take care of making the code a bit more efficient -as you proposed- by putting them all in one file and extracting some function.
