### ISSUE TITLE
[BUG] StatsForecastETS does not really use future covariates

### ISSUE THREAD

**Issue by Beerstabr** [unit8co/darts#1452]
I was interested in using StatsForecastETS whilst including future covariates. 

So I started looking at the source code for the Statsforecast package. And it seems that they do accept X as an argument, but do not use it in their code. So I suspect the future covariates are not really used by the StatsForecastETS model as well even though they're accepted.

I might be mistaken, but as far as I could see X is not used in the Statsforecast's AutoETS/ETS.

**Comment by Beerstabr** [comment]
I asked the people form StatsForecast and they say only AutoARIMA and MSTL are able to handle exogenous variables.

**Comment by hrzn** [comment]
Mmhh interesting, thanks for investigating. This is confusing as indeed they accept this argument. I would suggest we remove our support for future covariates for this model.
