### ISSUE TITLE
[QUESTION] How does one deal with updating/republishing forecasts as historical future covariates

### ISSUE THREAD

**Issue by frederikgnie** [unit8co/darts#1453]
Hi Darts Team,

I understand that external forecasts can be used as a future and historical future covariates, but how does one incorporate the fact that forecasts are typically republished at a given frequency when making a backtest?

E.g. following the example of River flow forecasting at https://medium.com/unit8-machine-learning-publication/time-series-forecasting-using-past-and-future-external-data-with-darts-1f0539585993, let's say one wants to do a backtest applying rolling window predictions, and assume that there is a new rain weather forecast every day. 
How does one "use" the historical forecasts, such that the model will utilize the newest forecast at the prediction point, but not a forecast which hasn't been released yet at that time.
Put in other words, is it somehow possible to state the publish time of a historical future covariate, and instruct Darts to only use the information available at that time when making predictions in a backtest.

**Comment by hrzn** [comment]
Hi, this is a very good question.
The simplest way to do this is probably to first build a proper dataset containing the "historical forecasts" of the weather forecasts, for each historical date d for d+1, d+2, etc. So we need a dataset containing D x 10 values if the weather forecasts are 10 days in advance for D dates in the past. Then backtesting would have to happen on different series, depending on the start date of the forecast, so we wouldn't be able to rely on `historical_forecasts()` as such. It would have to be done manually instead. The simplest would be to loop over the dates, build the right `TimeSeries` objects, and keep track of the results.
