### ISSUE TITLE
Add support for static covariates to ShapExplainer

### ISSUE THREAD

**Issue by dennisbader** [unit8co/darts#1457]
RegressionModels now support static covariates, so we have to add it to ShapExplainer as well.

Also, see #1450, #1638.

**Comment by chalendony** [comment]
Would be very nice to have this feature!

**Comment by anne-devries** [comment]
@dennisbader I will start working on this ticket :)

**Comment by dennisbader** [comment]
@anne-devries that's awesome, thanks a lot! I assigned the ticket to you.

Let us know if you need any support :)

**Comment by madtoinou** [comment]
Fixed by #1803, thank you @anne-devries for the work 🚀
