### ISSUE TITLE
Option for automatically forecasting covariates

### ISSUE THREAD

**Issue by Beerstabr** [unit8co/darts#1458]
It would be great to have an option for automatically forecasting the covariates using for example exponential smoothing.

**Comment by dennisbader** [comment]
Hi @Beerstabr, where would you want to use this automatic forecasting of covariates? For fitting/prediction?
IMO, forecasting covariates is a non-trivial (if something different than some date time attributes, etc..) and should be regarded as its own/separate forecasting task. 

Additionally, this would make the overall forecasting logic much more complex, and, with everything happening under the hood, the the users would not be aware of the actual covariates predictions or how well the covariates model is performing.

**Comment by Beerstabr** [comment]
@dennisbader mmm, you are right. When you put it like that, it doesn't sound like a good idea.

**Comment by hrzn** [comment]
I also agree with what's being said: having only the targets being forecasted in Darts is a very useful invariant that I think we should keep. If we start forecasting the covariates it will drastically increase the complexity of the framework and also would cause some conceptual issues I think (covariates are precisely defined as pieces of data that are *not* being forecast). Forecasting covariates may make sense for some problems, in which case it means they should be regarded as targets (of some forecasting problem) before being regarder as covariates (of the final forecasting problem) - but this is a modelling decision that is best left to users.
