### ISSUE TITLE
ARIMA / AutoARIMA : Support exogenous variables

### ISSUE THREAD

**Issue by alexrblohm** [unit8co/darts#146]
**Is your feature request related to a current problem? Please describe.**
Nope

**Describe proposed solution**
I LOVE this package and think it's very well-written!  I'd love to add covariates for forecasting like in some other packages to go from ARIMA to ARIMAX.  I'm assuming this would be an easy addition since I've seen it done elsewhere.  Thanks!

**Describe potential alternatives**
A clear and concise description of any alternative solutions or existing features that might solve it.

**Additional context**

**Comment by alexrblohm** [comment]
BTW here is what I'm talking about covariates=exogenous https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.auto_arima.html

**Comment by hrzn** [comment]
That's a good one. We currently have autoARIMA but only as a `UnivariateForecastingModel`. We should implement the multivariate variant (wrapping either around pdmarima or statsmodels, or both) to include exogeneous variables.

**Comment by LeoTafti** [comment]
Our implementations of ARIMA and AutoARIMA are simple wrappers around models from statsmodel (for ARIMA) and pmdarima (for AutoARIMA), which both support specifying exogenous variables, so I wouldn't expect this to be a very hard fix indeed. Marking this as "Good first issue"
