### ISSUE TITLE
[BUG] KalmanForecaster says number of timesteps in series and covariates don't match

### ISSUE THREAD

**Issue by Beerstabr** [unit8co/darts#1463]
**Describe the bug**
When backtesting a KalmanForecaster with the use of future_covariates it gives an error saying the covariates and the series don't match. When I supply exactly the same input to StatsForecastAutoARIMA.backtest() it does work. I think it has to do with the '_predict()' method of the KalmanForecaster, where it combines the 'series' and the 'series_future' and then tries to match it to the covariates.

**To Reproduce**
```python

# set backtest params
backtest_start = 0.8
backtest_stride = 4
backtest_forecast_horizon = 8

with open(path_X, "rb") as f:
    X = pickle.load(f)

with open(path_y, "rb") as f:
    y = pickle.load(f)

# models to test
models = [
    StatsForecastAutoARIMA(),
    KalmanForecaster(),
]

model_names = [
    "AutoARIMA",
    "Kalman",
]

# backtest per series and model
results = {}
for model, name in zip(models, model_names):
    print(name)
    model_results = []
    model_results += [
        model.backtest(
            series=y_i,
            future_covariates=X_i,
            start=backtest_start,
            stride=backtest_stride,
            forecast_horizon=backtest_forecast_horizon,
            metric=smape,
        )
        for y_i, X_i in zip(y, X)
    ]
    results[name] = model_results
```

Error:
ValueError: The number of timesteps in the series and the covariates must match.

**Comment by dennisbader** [comment]
Hey @Beerstabr, which darts version are you using?

**Comment by dennisbader** [comment]
We made an improvement to KalmanForecaster covariates handling in darts v0.23.0 -> I tested this with dummy input and it works.

Can you upgrade to darts==0.23.0, and see if it resolves the issue?

**Comment by hrzn** [comment]
Closing as it should work in 0.23.0.
