### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Lufffya** [unit8co/darts#1464]
Hi，I encountered some problems when using darts

1, When I use the model to train all time series and predict the last time period for each time series, its prediction is reasonable，
But when I only train a part of the all time series and back test(`historical_forecasts`) another part of the time series without training, the prediction seems to be much worse?

2, When I use the darts framework to predict, how often do I need to train the model, or do I need to use new data to train the model every day(Time series data is dimensioned by days)？

Thanks!!!!

**Comment by hrzn** [comment]
> 1, When I use the model to train all time series and predict the last time period for each time series, its prediction is reasonable，
> But when I only train a part of the all time series and back test(`historical_forecasts`) another part of the time series without training, the prediction seems to be much worse?

Unfortunately this is difficult to answer without some code to reproduce. Models having bad performance happen all the time :)


> 2, When I use the darts framework to predict, how often do I need to train the model, or do I need to use new data to train the model every day(Time series data is dimensioned by days)？

You can either train the model once, or call `fit()` again on the entire dataset once you have new data. On deep learning models calling `fit()` multiple times resumes training. On all other models it starts from scratch.
