### ISSUE TITLE
Restore code highlighting in the examples and quick start

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#1468]
For some reason the highlighting seems to be gone from the notebook-generated pages.

**Comment by mabilton** [comment]
Hey @hrzn. Looks like this is caused by a bug associated with `ipython==8.7.0`  - see spatialaudio/nbsphinx#687. When I upgraded to `ipython==8.8.0` then rebuilt the docs locally, syntax highlighting appeared to be restored.
