### ISSUE TITLE
Can static_cols be modified in from_group_dataframe?

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1478]
In this code: `ts_List = TimeSeries.from_group_dataframe(df, time_col='date', group_cols=['col_a','col_b'], value_cols='col_c')`

In `ts_List `, each time series static covariates is col_a and col_b, can be remove col_a and keep only col_b?

Because I need to use col_a and col_b to group, but I don't need col_a as a static covariates, so waht should I do?

Thanks!!!

**Comment by fred-navruzov** [comment]
+1 here, after creating dataset with `group_cols` I want to get read of them in the most framework-friendly way. Unfortunately, I didn't find out how to do it out-of-the box

However, I found a workaround - of course, it's a way less convenient, still it may be of use to you, @Luffffffy :

```python
from darts import TimeSeries
from joblib import Parallel, delayed
from tqdm.auto import tqdm
from os import cpu_count


n_jobs = cpu_count()
id_col = 'timeseries_id'
value_cols = [...]
time_col = 'date'
freq = ...
use_static_cov = True
unique_timeseries_id = df[id_col].nunique()
static_covariates_cols = [...]
target_cols = [...]

ts = Parallel(n_jobs=min(2, n_jobs), backend="multiprocessing")(
    delayed(TimeSeries.from_dataframe)(
        df=df[df[id_col] == ui],
        value_cols=value_cols,
        time_col=time_col,
        freq=freq,
        static_covariates=(
            None
            if not use_static_cov
            else df.loc[df[id_col] == ui, static_covariates_cols].head(
                len(target_cols)
            )
        ),
    )
    for ui in tqdm(unique_ids, total=len(unique_timeseries_ids), desc="creating list dataset...")
)
```

**Comment by dennisbader** [comment]
It is not possible to do directly with `TimeSeries.from_group_dataframe()`.

You could loop over the list of returned TimeSeries and adapt the covariates with `TimeSeries.with_static_covariates()`

A simple example:

```
series_groups = TimeSeries.from_group_dataframe(...)
series_groups = [series.with_static_covariates(series.static_covariates["col_b"]) for series in series_groups]
```

**Comment by Luffffffy** [comment]
@dennisbader Thank you. It's very simple and useful to me！！！
