### ISSUE TITLE
[BUG] TImeSeries.from_group_dataframe incorrect return type

### ISSUE THREAD

**Issue by connesy** [unit8co/darts#1484]
`TimeSeries.from_group_dataframe` is annotated with return type `Union["TImeSeries", List["TimeSeries"]`, however it always returns a `list[TimeSeries]`: https://github.com/unit8co/darts/blob/0.23.1/darts/timeseries.py#L801-L813.

This makes it annoying to use in typed code, as one has to cast the result to `List[TimeSeries]` even though this is guarantied.

**System:**
 - Python version: 3.10
 - darts version: 0.23.1

**Comment by dennisbader** [comment]
Hi @connesy and thanks for raising this.

Would you be willing to open a PR to make the changes?

**Comment by connesy** [comment]
Sure!
