### ISSUE TITLE
Autoregressive forecasting

### ISSUE THREAD

**Issue by martins0n** [unit8co/darts#149]
Nice work, guys!

It's a common place to use features generated from timeseries itself like lags, rolling statistics and etc.
I've seen [some approaches](https://github.com/EthanRosenthal/skits) like using sklearn transformers and pipelines for fitting, and forecasting via recursive procedure( iteratively generating one step ahead predictions ) 

Have you any ideas about it? 
I think it would be nice feature.

**Comment by pennfranc** [comment]
Thanks for your inputs, we will put this on our radar! It might indeed be nice to have a subclass of `ForecastingModel` that can take any regression model to produce predictions using autoregression. In the meantime, if you're interested in contributing to Darts, please check out [this post](https://github.com/unit8co/darts/issues/122#issuecomment-655344527) for guidelines to implement a new model. Also, please let us know if you have any other ideas!

**Comment by hrzn** [comment]
Here are some elements of answers:
Some models are auto-regressive in nature (e.g AR(I)MA) and so this is already embedded in some models. Some other models such as neural networks are not (always) auto-regressive in nature but rather work by predicting fixed-length outputs. For these cases (neural networks), Darts now provides a native auto-regressive functionality, which will recursively call the neural net on its own outputs until predictions of a certain horizon length are obtained.
As auto-regressive forecasting is a somewhat "abstract" feature that is quite model-dependent, I'm closing this issue. Thanks for the comment @martins0n
