### ISSUE TITLE
Docs: transformation of target TS for autoregressive model

### ISSUE THREAD

**Issue by overvalidated** [unit8co/darts#1490]
Hello!

The task is pretty simple: I need to train RandomForest and want to use ratio of 7 days before prediction day (let's call it window 1) and 7 days before window 1. Since model is autoregressive I have to feed predictions into transformer as they are created.
It is probably what's encoders can be used for, but I'm not sure how to use it for this.

I didn't manage to find information about this in documentation and issues. Sorry if it is already documented somewhere.

Thank you for your time and this amazing tool!

**Comment by hrzn** [comment]
Hi, what you're asking is to have a window transformation applying the same way encoders are applied. This is not possible yet in Darts out of the box and would have to be done by hand (i.e., you should build your auto-regressive forecasts yourself, and call the window transformer in between each call). We were having this in mind but it was not properly tracked; i've added a new task to track this: https://github.com/unit8co/darts/issues/1515
I'll close this one in the meantime, we can use #1515 for discussion if needed.
