### ISSUE TITLE
ModuleNotFoundError: No module named 'darts'

### ISSUE THREAD

**Issue by lucasaos52** [unit8co/darts#151]
I installed all  the dependencies packages on anaconda (as well as  fbprophet and torch), and later I installed
darts, by "pip install u8darts", saying that all "Rerquirement alread satisfied".

However, When  I try to import dart on python, it doesnt find the module.

Does Anybody knows what might be the problem?

 - Python version: [e.g. 3.6.5]

![image](https://user-images.githubusercontent.com/43455146/87692906-acea9a80-c762-11ea-812f-a64c86bc1c58.png)

**Comment by lucasaos52** [comment]
Found the issue. This module  doesnt work for python < 6.5.10

**Comment by TheMP** [comment]
Hi @lucasaos52, thank you for reporting the issue and glad that you managed to find a solution that works for you.

**Comment by cosmerodolfo** [comment]
Hi @lucasaos52, could you pls clarify which version of python is not supported?
I am in doubt of the version you mentioned (6.5.10), because python version goes up to 3.9. Tks.

**Comment by rishikeshkushwaha** [comment]
Same issue i am facing

**Comment by hrzn** [comment]
@rishikeshkushwaha can you confirm that you installed the package?
What do you obtain when typing `pip freeze |grep darts` ?

**Comment by rishikeshkushwaha** [comment]
C:\Users\rishikesh.kushwaha>pip install darts
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: darts in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (0.0.1.post1)
Requirement already satisfied: torch in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (1.8.1)
Requirement already satisfied: ipython in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (7.21.0)
Requirement already satisfied: scikit-image in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (0.18.1)
Requirement already satisfied: matplotlib in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (3.3.4)
Requirement already satisfied: scipy in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from darts) (1.6.2)
Requirement already satisfied: numpy in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from darts) (1.19.5)
Requirement already satisfied: pandas in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (1.2.3)
Requirement already satisfied: scikit-learn in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from darts) (0.24.1)
Requirement already satisfied: Pillow in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (8.1.2)
Requirement already satisfied: nibabel in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (3.2.1)
Requirement already satisfied: gdown in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (3.13.0)
Requirement already satisfied: torchvision in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from darts) (0.9.1)
Requirement already satisfied: filelock in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from gdown->darts) (3.0.12)
Requirement already satisfied: six in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from gdown->darts) (1.15.0)
Requirement already satisfied: tqdm in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from gdown->darts) (4.60.0)
Requirement already satisfied: requests[socks]>=2.12.0 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from gdown->darts) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from requests[socks]>=2.12.0->gdown->darts) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from requests[socks]>=2.12.0->gdown->darts) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from requests[socks]>=2.12.0->gdown->darts) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from requests[socks]>=2.12.0->gdown->darts) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from requests[socks]>=2.12.0->gdown->darts) (1.7.1)
Requirement already satisfied: pickleshare in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (0.7.5)
Requirement already satisfied: decorator in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (56.2.0)
Requirement already satisfied: pygments in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (2.8.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (3.0.17)
Requirement already satisfied: backcall in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (0.2.0)
Requirement already satisfied: colorama in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (0.4.4)
Requirement already satisfied: traitlets>=4.2 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (5.0.5)
Requirement already satisfied: jedi>=0.16 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from ipython->darts) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from jedi>=0.16->ipython->darts) (0.8.1)
Requirement already satisfied: wcwidth in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->darts) (0.2.5)
Requirement already satisfied: ipython-genutils in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from traitlets>=4.2->ipython->darts) (0.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->darts) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->darts) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->darts) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->darts) (1.3.1)
Requirement already satisfied: packaging>=14.3 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from nibabel->darts) (20.9)
Requirement already satisfied: pytz>=2017.3 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from pandas->darts) (2021.1)
Requirement already satisfied: imageio>=2.3.0 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->darts) (2.9.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from scikit-image->darts) (1.1.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->darts) (2021.4.8)
Requirement already satisfied: networkx>=2.0 in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from scikit-image->darts) (2.5.1)
Requirement already satisfied: joblib>=0.11 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->darts) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rishikesh.kushwaha\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn->darts) (2.1.0)
Requirement already satisfied: typing-extensions in c:\users\rishikesh.kushwaha\appdata\roaming\python\python39\site-packages (from torch->darts) (3.7.4.3)

C:\Users\rishikesh.kushwaha>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import darts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'darts'
>>>

C:\Users\rishikesh.kushwaha>pip freeze search grep
absl-py==0.12.0
alembic==1.4.1
anyio==2.2.0
argon2-cffi==20.1.0
astor==0.8.1
astunparse==1.6.3
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.3.0
blis==0.7.4
Boruta==0.3
Bottleneck==1.3.2
cachetools==4.2.2
catalogue==1.0.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
colorlover==0.3.0
convertdate==2.3.2
cufflinks==0.17.3
cycler==0.10.0
cymem==2.0.5
DARTS==0.0.1.post1
databricks-cli==0.14.3
decorator==4.4.2
defusedxml==0.7.1
docker==5.0.0
entrypoints==0.3
filelock==3.0.12
Flask==1.1.2
flatbuffers==1.12
funcy==1.16
future==0.18.2
gast==0.4.0
gdown==3.13.0
gensim==3.8.3
gitdb==4.0.7
GitPython==3.1.17
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
greenlet==1.1.0
grpcio==1.34.1
h5py==3.1.0
hijri-converter==2.1.1
htmlmin==0.1.12
idna==2.10
ImageHash==4.2.0
imageio==2.9.0
imbalanced-learn==0.7.0
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-contrib-core==0.3.3
jupyter-core==4.7.1
jupyter-nbextensions-configurator==0.4.1
jupyter-packaging==0.7.12
jupyter-server==1.4.1
jupyterlab==3.0.10
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-widgets==1.0.0
Keras-Applications==1.0.8
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
kmodes==0.11.0
korean-lunar-calendar==0.2.1
lightgbm==3.2.1
llvmlite==0.36.0
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==1.1.1
matplotlib==3.3.4
missingno==0.4.2
mistune==0.8.4
mlflow==1.17.0
mlxtend==0.18.0
multimethod==1.4
murmurhash==1.0.5
nbclassic==0.2.6
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5.1
nibabel==3.2.1
nltk==3.6.2
nose==1.3.7
notebook==6.2.0
numba==0.53.1
numexpr==2.7.3
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.3
pandas-profiling==3.0.0
pandocfilters==1.4.3
parso==0.8.1
patsy==0.5.1
phik==0.11.2
pickleshare==0.7.5
Pillow==8.1.2
plac==1.1.3
plotly==4.14.3
ply==3.11
preshed==3.0.5
prometheus-client==0.9.0
prometheus-flask-exporter==0.18.2
prompt-toolkit==3.0.17
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycaret==2.3.1
pycparser==2.20
pydantic==1.8.2
Pygments==2.8.1
pyLDAvis==3.2.2
PyMeeus==0.5.11
pynndescent==0.5.2
pyod==0.8.8
Pyomo==5.7.3
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks==1.7.1
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2021.1
PyUtilib==6.0.0
PyWavelets==1.1.1
pywin32==227
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==22.0.3
querystring-parser==1.2.4
regex==2021.4.4
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
scikit-image==0.18.1
scikit-learn==0.24.1
scikit-plot==0.3.7
scikit-surprise==1.1.1
scipy==1.6.2
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
sklearn==0.0
smart-open==5.0.0
smmap==4.0.0
sniffio==1.2.0
spacy==2.3.5
SQLAlchemy==1.4.15
sqlparse==0.4.1
srsly==1.0.5
stats==0.1.2a0
statsmodels==0.12.2
surprise==0.1
tabulate==0.8.9
tangled-up-in-unicode==0.1.0
tensorboard==2.5.0
tensorboard-data-server==0.6.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0rc2
tensorflow-estimator==2.5.0rc0
termcolor==1.1.0
terminado==0.9.2
testpath==0.4.4
textblob==0.15.3
thinc==7.4.5
threadpoolctl==2.1.0
tifffile==2021.4.8
torch==1.8.1
torchvision==0.9.1
tornado==6.1
tqdm==4.60.0
traitlets==5.0.5
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.26.3
utilmy==0.1.16211830
visions==0.7.1
waitress==2.0.0
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.59.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wordcloud==1.8.1
wrapt==1.12.1
xgboost==1.4.2
yellowbrick==1.3.post1

C:\Users\rishikesh.kushwaha>pip freeze darts
absl-py==0.12.0
alembic==1.4.1
anyio==2.2.0
argon2-cffi==20.1.0
astor==0.8.1
astunparse==1.6.3
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.3.0
blis==0.7.4
Boruta==0.3
Bottleneck==1.3.2
cachetools==4.2.2
catalogue==1.0.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
colorlover==0.3.0
convertdate==2.3.2
cufflinks==0.17.3
cycler==0.10.0
cymem==2.0.5
DARTS==0.0.1.post1
databricks-cli==0.14.3
decorator==4.4.2
defusedxml==0.7.1
docker==5.0.0
entrypoints==0.3
filelock==3.0.12
Flask==1.1.2
flatbuffers==1.12
funcy==1.16
future==0.18.2
gast==0.4.0
gdown==3.13.0
gensim==3.8.3
gitdb==4.0.7
GitPython==3.1.17
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
greenlet==1.1.0
grpcio==1.34.1
h5py==3.1.0
hijri-converter==2.1.1
htmlmin==0.1.12
idna==2.10
ImageHash==4.2.0
imageio==2.9.0
imbalanced-learn==0.7.0
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-contrib-core==0.3.3
jupyter-core==4.7.1
jupyter-nbextensions-configurator==0.4.1
jupyter-packaging==0.7.12
jupyter-server==1.4.1
jupyterlab==3.0.10
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-widgets==1.0.0
Keras-Applications==1.0.8
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
kmodes==0.11.0
korean-lunar-calendar==0.2.1
lightgbm==3.2.1
llvmlite==0.36.0
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==1.1.1
matplotlib==3.3.4
missingno==0.4.2
mistune==0.8.4
mlflow==1.17.0
mlxtend==0.18.0
multimethod==1.4
murmurhash==1.0.5
nbclassic==0.2.6
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5.1
nibabel==3.2.1
nltk==3.6.2
nose==1.3.7
notebook==6.2.0
numba==0.53.1
numexpr==2.7.3
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.3
pandas-profiling==3.0.0
pandocfilters==1.4.3
parso==0.8.1
patsy==0.5.1
phik==0.11.2
pickleshare==0.7.5
Pillow==8.1.2
plac==1.1.3
plotly==4.14.3
ply==3.11
preshed==3.0.5
prometheus-client==0.9.0
prometheus-flask-exporter==0.18.2
prompt-toolkit==3.0.17
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycaret==2.3.1
pycparser==2.20
pydantic==1.8.2
Pygments==2.8.1
pyLDAvis==3.2.2
PyMeeus==0.5.11
pynndescent==0.5.2
pyod==0.8.8
Pyomo==5.7.3
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks==1.7.1
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2021.1
PyUtilib==6.0.0
PyWavelets==1.1.1
pywin32==227
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==22.0.3
querystring-parser==1.2.4
regex==2021.4.4
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
scikit-image==0.18.1
scikit-learn==0.24.1
scikit-plot==0.3.7
scikit-surprise==1.1.1
scipy==1.6.2
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
sklearn==0.0
smart-open==5.0.0
smmap==4.0.0
sniffio==1.2.0
spacy==2.3.5
SQLAlchemy==1.4.15
sqlparse==0.4.1
srsly==1.0.5
stats==0.1.2a0
statsmodels==0.12.2
surprise==0.1
tabulate==0.8.9
tangled-up-in-unicode==0.1.0
tensorboard==2.5.0
tensorboard-data-server==0.6.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0rc2
tensorflow-estimator==2.5.0rc0
termcolor==1.1.0
terminado==0.9.2
testpath==0.4.4
textblob==0.15.3
thinc==7.4.5
threadpoolctl==2.1.0
tifffile==2021.4.8
torch==1.8.1
torchvision==0.9.1
tornado==6.1
tqdm==4.60.0
traitlets==5.0.5
typing-extensions==3.7.4.3
umap-learn==0.5.1
urllib3==1.26.3
utilmy==0.1.16211830
visions==0.7.1
waitress==2.0.0
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.59.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wordcloud==1.8.1
wrapt==1.12.1
xgboost==1.4.2
yellowbrick==1.3.post1

**Comment by rishikeshkushwaha** [comment]
Python 3.7.4
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-56ee85cb7d97> in <module>
----> 1 model_air.fit(train_data, verbose=True)

~/environment/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             decorated(self, *args, **kwargs)
     66     return decorator

~/environment/lib/python3.8/site-packages/darts/models/torch_forecasting_model.py in fit(self, series, covariates, val_series, val_covariates, verbose)
    288                                                         train_set_dim, val_set_dim))
    289 
--> 290         train_dataset = self._build_train_dataset(series, covariates)
    291         val_dataset = self._build_train_dataset(val_series, val_covariates) if val_series is not None else None
    292 

~/environment/lib/python3.8/site-packages/darts/models/torch_forecasting_model.py in _build_train_dataset(self, target, covariates)
    239                              target: Sequence[TimeSeries],
    240                              covariates: Optional[Sequence[TimeSeries]]) -> TrainingDataset:
--> 241         return SequentialDataset(target_series=target,
    242                                  covariates=covariates,
    243                                  input_chunk_length=self.input_chunk_length,

~/environment/lib/python3.8/site-packages/darts/utils/data/sequential_dataset.py in __init__(self, target_series, covariates, input_chunk_length, output_chunk_length, max_samples_per_ts)
     70         if self.max_samples_per_ts is None:
     71             # read all time series to get the maximum size
---> 72             self.max_samples_per_ts = max(len(ts) for ts in self.target_series) - \
     73                                       self.output_chunk_length - self.input_chunk_length + 1
     74 

~/environment/lib/python3.8/site-packages/darts/utils/data/sequential_dataset.py in <genexpr>(.0)
     70         if self.max_samples_per_ts is None:
     71             # read all time series to get the maximum size
---> 72             self.max_samples_per_ts = max(len(ts) for ts in self.target_series) - \
     73                                       self.output_chunk_length - self.input_chunk_length + 1
     74 

TypeError: object of type 'float' has no len()

**Comment by A-Candace** [comment]
I had gotten the same message. When I add the following, it works:

!pip install darts

from darts import TimeSeries

import warnings

warnings.filterwarnings("ignore")
import logging

logging.disable(logging.CRITICAL)
