### ISSUE TITLE
[BUG] Documentation: `darts-intro.ipynb` / `01-darts-intro.ipynb` missing?

### ISSUE THREAD

**Issue by turbotimon** [unit8co/darts#1512]
**Describe the bug**

In [13-TFT-examples](https://unit8co.github.io/darts/examples/13-TFT-examples.html?highlight=darts-intro.ipynb) it is stated:
> we recommend you first follow the `darts-intro.ipynb` notebook

However, i can not find this file in this repo or elsewhere?

**Additional context**

Other pages mentioning this file:
https://unit8co.github.io/darts/search.html?q=darts-intro.ipynb#

one of them as `01-darts-intro.ipynb` but i wasn't able to find that either

You may want provide a valid link to this file instead of formatting the filename as `code`

(I apologize if I am just too stupid to find the file)

**Comment by madtoinou** [comment]
Hi,

Thank you for reporting this typo. The notebook mentioned is most likely [01-multi-time-series-and-covariates.ipynb](https://github.com/unit8co/darts/blob/master/examples/01-multi-time-series-and-covariates.ipynb) which cover most of the basic functionalities of darts (in a model agnostic way).

**Comment by hrzn** [comment]
We renamed and reshuffled some of the notebooks, and forgot to track these changes in TFT examples notebook. Any PR to clean this reference would be welcome indeed :)

**Comment by turbotimon** [comment]
I'll try to do it if i find time. 

Meanwhile, to you guys agree with to following correction (also [TFT exmaple](https://unit8co.github.io/darts/examples/13-TFT-examples.html?highlight=endoded#Create-a-model)):

Is
> They generate endoded temporal data is used as future covariates.

Probably should be:
>  They generate **encoded** temporal data **that** is used as future covariates.

**Comment by dennisbader** [comment]
Hey @turbotimon, yes agreed!

**Comment by turbotimon** [comment]
i made a mr: https://github.com/unit8co/darts/pull/1526

**Comment by hrzn** [comment]
The correct notebook should be [00-quickstart.ipynb](https://github.com/unit8co/darts/blob/master/examples/00-quickstart.ipynb)
