### ISSUE TITLE
Saving the computaitonal graph for visualization with Tensorboard

### ISSUE THREAD

**Issue by solalatus** [unit8co/darts#1519]
**Is your feature request related to a current problem? Please describe.**
As [here](https://www.pytorchlightning.ai/blog/tensorboard-with-pytorch-lightning) described, it is possible to use Tensorboard to log the model graph for later visualization. This is a pretty practical feature if one would like to take a closer look and understand Torch models (let alone debug them maybe).

**Describe proposed solution**
The original usage is as follows:

`self.logger.experiment.add_graph(myModel(),sample_data)`

(Assumed: `myModel()` represents a complete Lightning module)

**Describe potential alternatives**
This would be easy to implement. Two places for it come in mind:
1. separate function called `on_epoch_start` or even `on_fit_start`
2. just a call inside `training_step` [here](https://github.com/unit8co/darts/blob/master/darts/models/forecasting/pl_forecasting_module.py#L146), where we already have a batch of input in our hands, so no sample creation is even needed. Naturally, in this case the call should only execute once at the first batch of the first epoch.

**Comment by alexcolpitts96** [comment]
I do not use Tensorboard, however, you can get access to the underlying model by going 
`myModel(**init_args).model`.

Give that a try and I expect it will work.

**Comment by solalatus** [comment]
As a workaround:

```
!pip install graphviz torchview

OLD_MODEL_NAME = ""#?????
WORK_DIR = ""#????

from darts.models.forecasting.nhits import NHiTSModel

loaded_model = NHiTSModel.load_from_checkpoint(model_name=OLD_MODEL_NAME,work_dir=WORK_DIR)#, best=True)

batch = 2
shape = (batch, loaded_model.model.input_dim, loaded_model.model.input_chunk_length_multi, 1)

from torchview import draw_graph

model_graph = draw_graph(loaded_model.model, input_size=shape,dtypes=[loaded_model.model.dtype], device='meta', save_graph=True)
model_graph.visual_graph
```
