### ISSUE TITLE
[BUG] converting Pandas DataFrame into TimeSeries object

### ISSUE THREAD

**Issue by Nikodemski2002** [unit8co/darts#1522]
**Describe the bug**
Hi, I have a problem with converting Pandas DataFrame into Darts TimeSeries object namely, my Pandas DataFrame consists of the datetime64 index and 4 columns of float64 data I want to have in the TimeSeries object. After executing below code, I get an error: `coordinate component has dimensions ('_field',), but these are not a subset of the DataArray dimensions ('_time', 'component', 'sample')`

**To Reproduce**
`TSDF = TimeSeries.from_dataframe(modeldf)`

**Expected behavior**
Getting a Darts TimeSeries object.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version 0.23.1

**Additional context**
![image](https://user-images.githubusercontent.com/19575525/215319290-82e11393-ac2a-48b0-b882-cfc82d78eb91.png)

Kind regards
Nikodem

**Comment by alexcolpitts96** [comment]
It is hard to infer what is going on from the provided info; however, here is a minimal example that should work:
```
import darts
import pandas as pd
import numpy as np

df = pd.DataFrame(
            data=np.random.randint(0, 100, size=(100, 4)), columns=list("ABCD"),
            index=pd.date_range(start=0, periods=100, freq='1D'),
        )

ts = darts.TimeSeries.from_dataframe(df)
```

If that works and your code is still not working, you should provide more information about your code. I also will recommend reinstalling darts or creating a new venv, conda env, etc. To avoid having to create a new environment, you can force reinstall darts using 
> pip install darts --ignore-installed

**Comment by hrzn** [comment]
+1, the code `TSDF = TimeSeries.from_dataframe(modeldf)` is not reproducible. Please provide a fully self-contained code snippet.

**Comment by mhadi4194** [comment]
I ran into same issue. 
looks like issue is because of column name index.
here is code to reproduce:

```
df2 = pd.DataFrame(
            data=np.random.randint(0, 100, size=(100, 1))
            ,index=pd.date_range(start=0, periods=100, freq='1D'),columns=['y']
        ).reset_index()
df2 = df2[df2['index'].dt.day != 2] # data has incomplete date
df2['id'] = list("ABCD") * 25 # multiple time series
df2 = df2.pivot(columns='id',values='y',index='index').fillna(value=0).reset_index()

series = TimeSeries.from_dataframe(df2
                                   ,time_col='index'
                                   ,fill_missing_dates=True
                                   ,freq='1day'
                                   
                                   ,fillna_value=0
                                  )

```

Error message:
```
ValueError: coordinate component has dimensions ('id',), but these are not a subset of the DataArray dimensions ('index', 'component', 'sample')

```

solutions:
remove column index name:

```
df2.columns.name = None
```

**Comment by madtoinou** [comment]
Thank you @mhadi4194 for pinpointing the source of the error and suggesting a solution, I opened a PR with a fix.
