### ISSUE TITLE
[Bug/Feature?] RNNModel and BlockRNNModel custom model constructor

### ISSUE THREAD

**Issue by alexcolpitts96** [unit8co/darts#1523]
I have encountered a partial bug/missing feature with the BlockRNNModel and RNNModel classes. To use a custom model, you have to create an instance of the custom model and pass it to the darts model class.

From the documentation:
> model (Union[str, Module]) – Either a string specifying the RNN module type (“RNN”, “LSTM” or “GRU”), or a PyTorch module with the same specifications as darts.models.rnn_model._RNNModule.

The feature part of this is that I think it would be beneficial to move the custom model initialization into the darts model classes (i.e. RNNModel._create_model. I have written code to do this and can submit a PR as needed. Since the documentation says it has to have the same specifications as _RNNModule, it makes sense to do this.

The bug component of this is that when using custom models the torchmetrics collections do not get logged properly.
```
model = _BlockRNNModule(
                name=self.rnn_type_or_module,
                input_size=input_dim,
                target_size=output_dim,
                nr_params=nr_params,
                hidden_dim=self.hidden_dim,
                num_layers=self.n_rnn_layers,
                num_layers_out_fc=hidden_fc_sizes,
                dropout=self.dropout,
                **self.pl_module_params,
            )
```
A custom external model needs a lot of wrangling to get into this form and it seems to be coming from the user not having easy access to pl_module_params. It makes a lot of extra work to get custom models into darts.

**Comment by hrzn** [comment]
Thanks for flagging @alexcolpitts96. It indeed seems we have something to solve here.
I'm thinking that for custom modules, rather than requiring they have same specifications as `_RNNModule`, we should probably rather require that they conform to the PyTorch underlying RNN module specifications. If we do that, we should be able to swap the `rnn` attribute of `_RNNModule` by that provided by the user, which would seem more natural to me. WDYT?

**Comment by alexcolpitts96** [comment]
I like the idea of getting rid of the requirement to use _RNNModule or _BlockRNNModule in order to use external modules.

That functionality could potentially be moved to a new class (CustomPLModule?) that inherits from PLForecastingModule. If that were done, it would essentially act like a pytorch-lightning module except it is wrapped in darts. Users could then override things as needed.

**Comment by tilly111** [comment]
Hello, is there any example of including a custom module? I was assuming the structure of the custom module looks something like this: 
```
  class CustomModule(nn.Module):
      def __init__(self):
          super().__init__()
          self.conv1 = nn.Conv2d(1, 20, 5)
          self.conv2 = nn.Conv2d(20, 20, 5)

      def forward(self, x):
          x = F.relu(self.conv1(x))
          return F.relu(self.conv2(x))
```
and can be used like 
```
model = RNNModel(..., model= CustomModule(), ...)
model.fit(...)
```
Is this the correct/intended usage?
