### ISSUE TITLE
Can darts handles missing time data?

### ISSUE THREAD

**Issue by lk1983823** [unit8co/darts#1533]
I want to do a time series forecasting task and some raw data that losses some timestamps. So the date-time is not always continuous. In addition, the missing data is too much. So I want to train the whole data separately. For example,  set the continuous data into different groups and let the model train the data group by group. Does anyone know if the darts handle it automatically?

**Comment by alexcolpitts96** [comment]
Darts does have a built in missing values filler: [MissingValuesFiller](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html?highlight=missingvalue#darts.dataprocessing.transformers.missing_values_filler.MissingValuesFiller)

TimeSeries objects have a method, [longest_contiguous_slice](https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=timeseries#darts.timeseries.TimeSeries.longest_contiguous_slice), that can be used to extract chunks of the time series. This could be used in a loop to extract the chunks of interest:
1. get contiguous slice (you can set the allowable gap size)
2. remove the extracted slice from the original TimeSeries
3. repeate 1 until there are no more chunks to extract

**Comment by dennisbader** [comment]
Just want to add that if your data has a well defined frequency (if the wholes were filled), you can use `fill_missing_dates=True` and `freq=your_freq` in the `TimesSeries.from_*()` time series creation methods

**Comment by lk1983823** [comment]
> Darts does have a built in missing values filler: [MissingValuesFiller](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html?highlight=missingvalue#darts.dataprocessing.transformers.missing_values_filler.MissingValuesFiller)
> 
> TimeSeries objects have a method, [longest_contiguous_slice](https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=timeseries#darts.timeseries.TimeSeries.longest_contiguous_slice), that can be used to extract chunks of the time series. This could be used in a loop to extract the chunks of interest:
> 
> 1. get contiguous slice (you can set the allowable gap size)
> 2. remove the extracted slice from the original TimeSeries
> 3. repeate 1 until there are no more chunks to extract

@alexcolpitts96  Thanks. Is there any example that shows how to do this during a TFT model training process?

**Comment by lk1983823** [comment]
> Thanks @alexcolpitts96!
> 
> Just want to add that if your data has a well defined frequency (if the wholes were filled), you can use `fill_missing_dates=True` and `freq=your_freq` in the `TimesSeries.from_*()` to insert the missing time stamps into the index. The values will be empty.

@dennisbader Thanks. Can the TFT model train the time series time data filled with NANs directly?

**Comment by dennisbader** [comment]
No, the models won't work with NaNs.
