### ISSUE TITLE
Multiple timeseries regression training with large number of features

### ISSUE THREAD

**Issue by albin02t** [unit8co/darts#1537]
Hi, 
I am currently working on a usecase wherein it is related to generating forecasts for energy generated by turbines in a windfarm. There are total 5 turbines data for months which makes it a multiple timeseries data and also a multivariate timeseries as there are other independent features. 
The original data was at an interval of 10 min which i have resampled at an hourly frequency to then train the linear regression and random forest multiple timeseries models.
The initial data had a total of around 299 independent features and the target of enery produced. Most of the features were related to each other.

I am doing the training using a flask and celery server. Training for random forest takes a lot of time and eventually crashes the celery server due to timeout. What could be the issue there?
Training for linear regression works but the errors come up in the range of 10^5. After applying scaling the errors come in the range of 200-300 but there are negative terms in the forecast which does not make sense.
Are there any methods or techniques to apply feature selection and/or improve the base model performance?  

Would really appreciate it if you can help me, Thank you!

**Comment by hrzn** [comment]
Hi, scaling is always a good idea in case of doubts. It seems you have a large datasets; maybe you can try to first limit the number of training samples (and training time) by e.g. specifying `max_samples_per_ts` when calling `fit()`. RandomForest does not scale very well and it is reasonable to try LinearRegressionModel first. If you're still hitting performance issues, try one of the simply deep learning models (DLinear, NLinear or maybe TCN), which can scale better to large datasets. A GPU would help for those, but is not mandatory.
Hope this helps.

**Comment by madtoinou** [comment]
Hi @albin02t,

I am closing this for now, feel free to reopen it if you have additional information or question about this use-case.
