### ISSUE TITLE
Does the RegionEnsembleModel support models of different covariates types?

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1544]
For example: `RegressionEnsembleModel(forecasting_models=[LSTM_Model, NHiTS_Model], regression_train_n_points=12)`

I want to use LSTM Model(Future-known covariates) and NHiTS Model(Past-observed covariates) to regression
But they have different covariates types, so whether it can work?

![image](https://user-images.githubusercontent.com/49063302/217470378-59a9d7ad-8422-4e88-93fa-798426bf0852.png)
![image](https://user-images.githubusercontent.com/49063302/217470427-6c93e29d-dd53-49a9-adbf-f57c7c1d807d.png)
![image](https://user-images.githubusercontent.com/49063302/217470497-3b69c478-0d34-4dae-845d-1b3018b01541.png)

**Comment by dennisbader** [comment]
You can use the two models but only without covariates. 
Only the intersection of supported covariates types across the models is supported.
I.e. TFTModel and NHiTSModel would support past covariates but not future covariates, as only TFTModel supports those.

**Comment by Luffffffy** [comment]
I see, thank you!!!
