### ISSUE TITLE
Add feature values and SHAP explanation object to ExplainabityResult

### ISSUE THREAD

**Issue by rijkvandermeulen** [unit8co/darts#1545]
Currently the ExplainabilityResult object only contains the explained forecast (i.e., the shapley values for each prediction). I think it would be useful to also store the corresponding feature values and potentially also the SHAP explanation object itself. This will give the end user more options to work with the forecasts that are explained.

**Comment by hrzn** [comment]
Sounds like a good idea to me, adding to backlog.

**Comment by dennisbader** [comment]
Fixed in #1546
