### ISSUE TITLE
Add interpolate to TimeSeries class

### ISSUE THREAD

**Issue by fawolfmann** [unit8co/darts#155]
**Problem**
dataframe with missing dates. 
TimeSeries fill missing dates, but add `nan` value to the filled date
And almost all model will fail when `fit`

**Solution**
Add interpolate function from pandas when this occurs. Let the user define the interpolate method.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html#pandas.Series.interpolate

By the way: pretty cool lib!

**Comment by hrzn** [comment]
Hi @fawolfmann, did you see the method `auto_fillna()`? https://unit8co.github.io/darts/generated_api/darts.utils.missing_values.html
I think it might already be doing what you want.

**Comment by fawolfmann** [comment]
Yes Thanks!
