### ISSUE TITLE
[BUG] Series with Similar Values Produce ValueError in Quantile Detection

### ISSUE THREAD

**Issue by philippspengler** [unit8co/darts#1551]
**Describe the bug**
The QuantileDetector class raises an error during fitting when the timeseries has low variaton.

**To Reproduce**
```
series = TimeSeries.from_series(pd.Series([96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 96.0, 93.0]))
quantile_detector = QuantileDetector(low_quantile=0.05, high_quantile=0.95)
quantile_detector.fit(series)
```

**Expected behavior**
Expect the quantile detector to fit without an error.

**System (please complete the following information):**
 - Python version: 3.8.5
 - darts version 0.23.1

**Comment by dennisbader** [comment]
@julien12234 could you give this a look?
