### ISSUE TITLE
[BUG] Documentation: The current example of Hyperparameter optimization using Optuna produces an error

### ISSUE THREAD

**Issue by JLC827** [unit8co/darts#1556]
**Describe the bug**
Attempting to run [the Optuna hyperparameter optimization example found here](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html) produces the exception 'The on_init_start callback hook was deprecated in v1.6 and is no longer supported as of v1.8'.

**To Reproduce**
Run [the Optuna hyperparameter optimization example found here](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html).

**Expected behavior**
The code should run without throwing an exception. 

**System (please complete the following information):**
 - Python version: 3.10
 - darts version 0.23.1

**Additional context**
This is an issue with the Optuna library not supporting the latest version of PytorchLightning. Until Optuna fix it on their end, the problem can be solved by defining PyTorchLightningPruningCallback using the snippet found in [this github issue](https://github.com/optuna/optuna-examples/issues/166), rather than importing PyTorchLightningPruningCallback from the Optuna library. This new definition could be added to [the example Optuna code snippet on the hyperparameter optimization page.](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html)

**Comment by dennisbader** [comment]
Hi @JLC827 and thanks for raising this. Should get fixed with #1575.
