### ISSUE TITLE
Does Prophet implementation through Darts is different from official Prophet package or any other package that supports Prophet model?

### ISSUE THREAD

**Issue by AbisheikNavaneethan** [unit8co/darts#1564]
I'm trying to compare different models from different packages. Prophet model from Darts is giving totally a different result from Prophet from different package. Is the underlying implementation of Prophet in Darts is modified or is it same as official Prophet code from Facebook?

**Comment by dennisbader** [comment]
It is a wrapper around the original facebook prophet model, including some extra functionality to make it easier for the user to soecify seasonalities and others.

So in theory it should produce the same results as the original model.
