### ISSUE TITLE
[BUG] Scaler does not check that input is TimeSeries object

### ISSUE THREAD

**Issue by JLC827** [unit8co/darts#1567]
**Describe the bug**
If passing the wrong type to a `Scaler` object, for example using `transform` or `inverse_transform`, no type checking is performed. This results in confusing error messages. For example, if passing a pandas DataFrame the error log output is "AttributeError: 'str' object has no attribute 'n_components'". This bug probably applies to all transformer objects.

**To Reproduce**
```python
from darts.dataprocessing.transformers import Scaler
from darts.datasets import AirPassengersDataset
import numpy as np

series_air = AirPassengersDataset().load().astype(np.float32)
series_air = series_air.pd_dataframe()
scaler = Scaler()
series_air_scaled = scaler.fit_transform(series_air)

```

**Expected behavior**
Output along the lines of "Expected type 'darts.TimeSeries', got 'pandas.DataFrame' instead".

**System (please complete the following information):**
- Python version: 3.10
- darts version 0.23.1
- Windows 10.0.19045

**Comment by dennisbader** [comment]
We use type hinting instead of actual type checks. The type of `series` is well defined for the Scaler: 
https://github.com/unit8co/darts/blob/690b6f409de32fa728e4fa419a63436604ac4ccc/darts/dataprocessing/transformers/fittable_data_transformer.py#L135-L137

**Comment by JLC827** [comment]
Ah sorry I should have checked the source before submitting this issue. I am surprised my IDE (pycharm) did not raise a warning. But yes, happy to close this as as you say users should really be expecting to use the TimeSeries type.
