### ISSUE TITLE
Add transformer that converts higher frequency time series to lower frequency

### ISSUE THREAD

**Issue by Beerstabr** [unit8co/darts#1570]
In time series forecasting sometimes you come across a situation in which the frequency of your target doesn't match the frequency of your covariates. 

For example, your target might be quarterly while some of your covariates are monthly. 

A simple way of dealing with this is up- or downsampling your data. However, doing this means that you either lose some data (e.g. when you go from a monthly to a quarterly frequency) or it can lead to information leakage (e.g. when you go from quarterly to monthly). 

It might be nice to incorporate some other way of dealing with this in Darts. One way of addressing low frequency targets in combination with high frequency covariates is called [mixed-data sampling (MIDAS)](https://en.wikipedia.org/wiki/Mixed-data_sampling). In the case of quarterly targets and monthly covariates, it would mean creating three columns for each monthly covariate, each containing different lags and relating those to the quarterly targets.

Would this be a worthwhile addition to Darts or would it add too much complexity?
It could be part of data processing or it could somehow be incorporated in e.g. RegressionModel.

**Comment by dennisbader** [comment]
Hi @Beerstabr and thanks for this feature request. I think that indeed this would be a worthwhile addition to Darts.
We could add a new transformer for this to `darts.dataprocessing.transformers` which would transform higher frequency time series into a lower frequency by adding new components/columns that capture that higher frequency data.

I add this to our backlog. Would you be willing to contribute to this?

**Comment by Beerstabr** [comment]
Hi @dennisbader, yes no problem, I would definitely like to help out. 

And I think adding a transformer is indeed the way to go!
