### ISSUE TITLE
Minimum Train Length for Random Forest

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#1574]
**Describe the bug**
I am trying to use optuna to tune the hyperparameters in the random forest regressor model in Darts. I initially thought that as long as the training length is > the minimum lags in the target and past covariates, then the model should run because it will have sufficient information about the lagged variables. For example, if my target lags and past covariate lags are between -50 to -28, having a training length of 90 time steps should be enough to cover these values. However, I am getting an error saying that the training length is insufficient to run the model.

**To Reproduce**
These are the parameters that I am tuning for:
    train_length = trial.suggest_int('train_length', 200, 1000)
    target_lags_lower_bound = trial.suggest_int('target_lags_lower_bound', -50, -28)
    past_cov_lags_lower_bound = trial.suggest_int('past_cov_lags_lower_bound', -50, -28)
    future_cov_lags_lower_bound = trial.suggest_int('future_cov_lags_lower_bound', 0, 13)
    max_depth = trial.suggest_int('max_depth', 5, 50)
    n_estimators = trial.suggest_int('n_estimators', 50, 1000)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    
    model = RandomForest(lags = list(range(target_lags_lower_bound, -27)), 
                         lags_past_covariates = list(range(past_cov_lags_lower_bound, -27)), 
                         lags_future_covariates = list(range(future_cov_lags_lower_bound, 14)), 
                         max_depth = max_depth, 
                         n_estimators = n_estimators,
                         min_samples_split = min_samples_split,
                         min_samples_leaf = min_samples_leaf,
                         output_chunk_length = 45, 
                         n_jobs=-1
                        )

**Comment by dennisbader** [comment]
Having a minimum target lag of `-50` and `output_chunk_length=45` would require a target series of length 95 for a single observation.

**Comment by ETTAN93** [comment]
@dennisbader Thanks for the reply. Can you explain to me what is the logic behind that? I originally thought that a target lag of -50 would just mean that you need a train_length of at least 50 to cover those target lags. Why would you need to add that number with the output_chunk_length?

Also I am slightly confused by output_chunk_length and forecast_horizon. I saw in the documentation where it said for example, if your forecast_horizon is > output_chunk_length, then you would need to provide the future past covariates.

Thanks in advance.

**Comment by hrzn** [comment]
> @dennisbader Thanks for the reply. Can you explain to me what is the logic behind that? I originally thought that a target lag of -50 would just mean that you need a train_length of at least 50 to cover those target lags. Why would you need to add that number with the output_chunk_length?
> 
> Also I am slightly confused by output_chunk_length and forecast_horizon. I saw in the documentation where it said for example, if your forecast_horizon is > output_chunk_length, then you would need to provide the future past covariates.
> 
> Thanks in advance.

With lags=50 and output_chunk_length=45, you need a series for which the "history" of the series (what comes before the prediction point) to be of length at least 50, and the "future" (what comes after the prediction point) to be of length 45. This is required to create _one_ example training data point, containing a single instance of an input/output training sample. Arguably any serious model would require longer series in order to be trained on multiple samples.

`output_chunk_length` is the the number of future time steps that the model can produce in one go at some forecasting time T, if the past covariates extend up until T. If you want to produce forecasts for a horizon beyond that, you also have to provide past covariates extending beyond T.

**Comment by dennisbader** [comment]
Let's say `output_chunk_length=1`, `target_lag=-50`, and in total you have a target series of length 100. The models create the training examples behind the hood:

1. The first training example will use the first 50 time steps from target (indices 0 until 49) as an input (comparable to `X` from sklearn) and the 51st time step as the actual outcome (comparable to `y` from sklearn). 
2. The next example will be shifted by `output_chunk_length`, i.e. it will use time steps at indices 1 until 50 as an input, and 52nd time step as the actual outcome.
3. This is repeated until all of the target series data was used.

**Comment by ETTAN93** [comment]
@dennisbader Just to make sure I got it right:
Assume I have a `target series of length 25`, `output_chunk_length = 1`, `target_lag = [-10]`, `past_covariate_lag = [-10]`, `future_covariate_lag = [0]`. 

When I am trying to predict point 26, the model will use the target value (time step 16), past covariate value (time step 16) and future covariate value (time step 26) as defined by my lags. Assuming I do not define my train length, then the training examples will be:

1st: Target (Time 10, Training y1) = Target Lag (Time 0, training x11) + Past Covariate (Time 0, training x12) + Future Covariate (Time 10, training x13)
2nd:Target at time step 11 (Time 11, training y2) = Target Lag (Time 1, training x21) + Past Covariate (Time 1, training x22) + Future Covariate (Time 11, training x23)
.... etc.

Is that a correct representation? I attached a picture below if that makes the example clearer.

![image](https://user-images.githubusercontent.com/59031005/221364801-bd6f3347-6054-4492-bef0-39911c1b4a92.png)

**Comment by dennisbader** [comment]
@ETTAN93, yes that is correct for both prediction and training.

**Comment by ETTAN93** [comment]
@dennisbader , do I need to specify the add_encoders parameter as below for darts to know where the lags are relative to the prediction time point?
```
add_encoders={
    'position': {'past': ['relative'], 'future': ['relative']}
}
```

From the documentation I can see this explanation:
![image](https://user-images.githubusercontent.com/59031005/225002431-bb28aab5-fbe7-49d5-a020-c98956174cc5.png)

Or does darts automatically know how it works based on the time series index of the dataframe?
