### ISSUE TITLE
[BUG]LinAlgError: Matrix is not positive definite

### ISSUE THREAD

**Issue by NamrataRade** [unit8co/darts#1579]
**Describe the bug**
I am using VARIMA model from darts package for time series forecasting. After running model.fit(train_ts) command getting this LinAlgError. train_ts is obtained by first creating train series (using timeseries.from_group_dataframes) and then concatenating. train_ts contains list of matrices and the size of all matrices is 3 x 1. Input data has three columns namely date, unique_id(represents hierarchy) and sales_value. For small sample e.g 325 data points, I am not getting this error but RMSE is very bad.

**To Reproduce**
from darts import concatenate, TimeSeries
train_ts=TimeSeries.from_group_dataframe(train_data, group_cols = ['unique_id'], time_col = 'time', value_cols= ['sales_value'])
train_ts=concatenate(train_ts,axis=1)
model = VARIMA()
model.fit(train_ts)

**Expected behavior**
forecast for time series

**System (please complete the following information):**
 - Python version: 3.8.13
 - darts version 0.23.1

**Comment by hrzn** [comment]
Hi, this is most likely an issue not with Darts, but with the underlying VARIMA model which is either not suitable for your data or badly configured. Please post a minimal reproduce code snippet if you want us to have a look. In the meantime i'll close the issue - pls re-open if needed.

**Comment by NamrataRade** [comment]
Hello,
Input data has product informations at different levels. Goal is to do hirarchical time series forecasting. Before passing input data, I am performing log transformation and stationary check. inut data size=289065. Model is able to provide forecast for 400 data points at a time but not for entire data.
Data columns (total 13 columns):

 0   lvl1         289065 non-null  category      
 1   lvl2         289065 non-null  category      
 2   lvl3         289065 non-null  category      
 3   lvl4         289065 non-null  category      
 4   lvl5         289065 non-null  category      
 5   lvl6         289065 non-null  category      
 6   lvl7         289065 non-null  category      
 7   lvl8         289065 non-null  category      
 8   lvl9         289065 non-null  category      
 9   area_id      289065 non-null  int16         
 10  time         289065 non-null  datetime64[ns]
 11  sales_value  289065 non-null  float16       
 12  unique_id    289065 non-null  int32         
dtypes: category(9), datetime64[ns](1), float16(1), int16(1), int32(1)
memory usage: 7.5 MB

#sample code
horizon="2022-02-28"
y_val = 'sales_value'
time_col= 'time'
hier_columns = ['unique_id','area_id','lvl1','lvl2','lvl3','lvl4','lvl5','lvl6','lvl7','lvl8','lvl9']
hier_df = df_monthly_new[hier_columns + [y_val] + [time_col]]
df_final=hier_df.copy()
df_final.shape
train_df = df_final[df_final['time']<horizon]
valid_df = df_final[df_final['time']>=horizon]
#Create timeseries from dataframes
train_ts = TimeSeries.from_group_dataframe(train_df,group_cols = hier_columns , time_col = time_col, value_cols= y_val) 
valid_ts = TimeSeries.from_group_dataframe(valid_df, group_cols = hier_columns , time_col = time_col, value_cols= y_val) 
from darts import concatenate
train_ts = concatenate(train_ts, axis=1)
valid_ts = concatenate(valid_ts, axis=1)
def fit_and_pred(model, training, validation):
    model.fit(training)
    forecast = model.predict(len(validation))
    print("model {} obtains MAPE: {:.2f}%".format(model, mape(valid_ts, forecast)))
    print("model {} obtains RMSE: {:.2f}%".format(model, rmse(valid_ts, forecast)))
    print("model {} obtains MAE: {:.2f}%".format(model, mae(valid_ts, forecast)))
    return forecast
forecast=fit_and_pred(VARIMA(), train_ts, valid_ts)

**Comment by NamrataRade** [comment]
Input Columns: Output-forecast for sales_value
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   lvl1         289065 non-null  category      
 1   lvl2         289065 non-null  category      
 2   lvl3         289065 non-null  category      
 3   lvl4         289065 non-null  category      
 4   lvl5         289065 non-null  category      
 5   lvl6         289065 non-null  category      
 6   lvl7         289065 non-null  category      
 7   lvl8         289065 non-null  category      
 8   lvl9         289065 non-null  category      
 9   area_id      289065 non-null  int16         
 10  time         289065 non-null  datetime64[ns]
 11  sales_value  289065 non-null  float16       
 12  unique_id    289065 non-null  int32         
dtypes: category(9), datetime64[ns](1), float16(1), int16(1), int32(1)

**Comment by felixdivo** [comment]
I got the same error and it is a bit tricky to pin down.
