### ISSUE TITLE
Add an example notebook for the FB Prophet model

### ISSUE THREAD

**Issue by sarikayamerts** [unit8co/darts#158]
**Is your feature request related to a current problem? Please describe.**
Currently, I couldn't see an example to demonstrate fbprophet usage through darts. I am opening this issue to create an example notebook for prophet usage.

**Describe proposed solution**
Adding a new jupyter notebook to examples folder to show the usage of fbprophet with different seasonal frequencies & holidays.

**Comment by TheMP** [comment]
Hi @sarikayamerts, 

Thank you for your help in contributing to the library! We'd be more than happy to review your PR regarding example usage of prophet. 

Please feel free to work on that, we would also be grateful if the new notebook was consistent in style/format with other notebooks we already provide and preferably work on the same data. 

Thanks!
