### ISSUE TITLE
Allow for usage of native way of dealing with categorical features RegressionModels

### ISSUE THREAD

**Issue by rijkvandermeulen** [unit8co/darts#1580]
**Summary**
@hrzn in line with the earlier discussion we had on gitter (see link below), I'd like to propose the following functionality: for RegressionModels that have a native way of dealing with categorical features (especially gradient boosted trees models such as LightGBM, Catboost) enable the usage of this parameter throught the Darts API. Ideally this would work for all kinds of covariates (past, fut and static).

**Link to gitter discussion for more detailed explanation**
https://matrix.to/#/!uumevxjBaNJhovFYgj:gitter.im/$w1tobiqP8nxHN1hQmRKJU9_inojDwfZkFHSSt4B0tlY?via=gitter.im&via=matrix.org&via=matrix.thegolem.cz

Do you still see the added value of this? If so, I can also give this a go.

**Comment by hrzn** [comment]
Hi @rijkvandermeulen , we definitely still see a lot of value in this :) Many thanks for the PR! We'll take a look asap.
