### ISSUE TITLE
[BUG] Unhelpful error message on TimeSeries.with_hierarchy

### ISSUE THREAD

**Issue by DavidKleindienst** [unit8co/darts#1581]
**Describe the bug**
When encoding the hierarchy the time series hierarchy we need to construct a hierarchy dict of the format `{child_node: [parent_node1, parent_node2, ...]}`. 
However, if there is only one parent node in the whole TimeSeries it is easy to make the mistake of constructing a dict `{child_node: parent_node}` instead of `{child_node: [parent_node}`. 
Doing so leads to the following rather unhelpful error message:
`ValueError: The values of the hierarchy must only contain component names matching those of the series.`

**To Reproduce**
```python
dates = pd.date_range("2020-01-01", "2020-12-31", freq="D")
nr_dates = len(dates)
t1 = TimeSeries.from_times_and_values(dates, 3 * np.ones(nr_dates), columns=["T1"])
t2 = TimeSeries.from_times_and_values(dates, 5 * np.ones(nr_dates), columns=["T2"])
t3 = TimeSeries.from_times_and_values(dates, np.ones(nr_dates), columns=["T3"])
tsum = TimeSeries.from_times_and_values(dates, 9 * np.ones(nr_dates), columns=["T_sum"])

ts = concatenate([t1, t2, t3, tsum], axis="component")
hierarchy = {"T1": "T_sum", "T2": "T_sum", "T3": "T_sum"}
ts = ts.with_hierarchy(hierarchy)
```

**Expected behavior**
Either it should simply detect that one component was specified rather than a list and internally convert it to a list, or a helpful error message should be issued

**System (please complete the following information):**
 - Python version: 3.10.6
 - darts version: master

**Additional context**
I think there's two possibilities to solve this
- Detect strings and convert them to a list of one string
- Raise an error message that instructs the user to use `["string"]` instead of `"string"` when constructing the hierarchy dict

I'm happy to submit a PR if you let me know which of these options is preferred

**Comment by madtoinou** [comment]
Hi @DavidKleindienst,

I think that the approach used in a lot of places is to detect the string using `isinstance` and convert it into a single element list (example in [`from_dataframe`](https://github.com/unit8co/darts/blob/master/darts/timeseries.py#L600)).

Your PR is very welcome!
