### ISSUE TITLE
[Feature Request] Recursive prediction 

### ISSUE THREAD

**Issue by alphabetagamer** [unit8co/darts#1596]
Currently, forecasting is one-shot. We should have the option to predict iteratively where predictions from previous steps are stacked on the train set before predicting the next window. 

![image](https://user-images.githubusercontent.com/34796341/221187506-ce23628e-b536-496e-82d2-0c1e52cd0de4.png)

**Comment by dennisbader** [comment]
Our `GlobalForecastingModels` already predict in an auto-regressive (your recursive) way whenever your forecasting horizon `n` (used when forecasting with [`predict()`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.linear_regression_model.html#darts.models.forecasting.linear_regression_model.LinearRegressionModel.predict)) is larger than the `output_chunk_length` used at model creation.

You can find a list of our GlobalForecastingModels [here](https://unit8co.github.io/darts/userguide/covariates.html#global-forecasting-models-gfms).
