### ISSUE TITLE
Multivariate Time Series in TCN

### ISSUE THREAD

**Issue by asifmustafa87** [unit8co/darts#1599]
Hi,

I want to apply TCN for multivariate time series. Does Darts allow this? If so, where can I find such an example?

**Comment by dennisbader** [comment]
Hi @asifmustafa87, yes `TCNModel` supports multivariate forecasting. In [this table](https://unit8co.github.io/darts/index.html#forecasting-models) you can find all of our forecasting models and what they support.

- [Here](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-and-Forecasting-Multivariate-TimeSeries) is a general example on how to training and forecasting works with multivariate target series.
- [Here](https://unit8co.github.io/darts/examples/09-DeepTCN-examples.html) is an example of how to use a TCNModel (on a univariate target series)
- [Here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Building-and-manipulating-TimeSeries) is an example of how to build the `TimeSeries`
