### ISSUE TITLE
In sample predictions

### ISSUE THREAD

**Issue by patrick-dd** [unit8co/darts#160]
I would like to have in sample prediction as an option. 

This will help collect model errors so users can diagnose models.

**Describe proposed solution**
An extra method to the model. `predict_in_sample`

`in_sample_prediction = model.predict_in_sample(training_data)`

**Describe potential alternatives**
Modifying `predict` method to be `forecast` and generalising `predict` like in [Statsmodels ARIMA](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMAResults.predict.html#statsmodels.tsa.arima_model.ARIMAResults.predict)

**Comment by pennfranc** [comment]
This would indeed be a useful feature, we will put this on our to-do list! We have a function called [forecasting_residuals](https://unit8co.github.io/darts/generated_api/darts.backtesting.backtesting.html?highlight=forecasting_residuals#darts.backtesting.backtesting.forecasting_residuals) that provides something in the direction you're suggesting, although it still involves out-of-sample predictions, so it's not quite the same. I'm not quite sure if a `predict_in_sample` method would be feasible for every single forecasting model, so we would have to think about how this method should be implemented exactly. In the meantime, if you'd like to give this problem a shot, please check out our README for instructions about how to contribute.

**Comment by patrick-dd** [comment]
Cheers @pennfranc, will let you know how I go

**Comment by TheMP** [comment]
@patrick-dd hi Patrick, any luck working on this issue?

**Comment by patrick-dd** [comment]
Hey @TheMP, no I didn't get around to this.
