### ISSUE TITLE
How to correctly cut the predicted range distribution？

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1603]
```
preds = Model.predict(n=30, series=series, past_covariates=past_covariates, num_samples=10000) 
for i in range(len(preds)):
    _forecasts = np.squeeze(preds[i].values()) # The dimension of _forecasts is [30]
    _samples = np.squeeze(preds[i]._xa.values) # The dimension of _samples is [30, 10000]
    q2, q8 = np.quantile(_samples, 0.2, axis=-1),  np.quantile(_samples, 0.8, axis=-1)
```
In the above code, I want to build an upper and lower boundary range for the predicted value(`preds`), 
so I chose 0.2 and 0.8 to make this range smaller than the original one(`forecasts[i]._xa.values`). 
But I found a problem that the predicted value is sometimes not included in the boundary. 
Is this normal? Or is there something wrong with me?

**Comment by dennisbader** [comment]
Just wanted to add that you can simply use for example  `preds.quantile(0.2)` for this.

**Comment by Luffffffy** [comment]
@madtoinou 
Yes, I have specified `Likelihood=GaussianLikelihood()` for my model.
I just want to reduce the prediction range for my preds data as the effect of the following figure.
![image](https://user-images.githubusercontent.com/49063302/222026782-d411f7ad-11c9-4b98-ac05-3e1f9155455c.png)
