### ISSUE TITLE
[BUG]-Multiple timeseries(Global models) fails for Random Forest and Regression Models

### ISSUE THREAD

**Issue by pshetty44** [unit8co/darts#1605]
**Describe the bug**
Random Forest or Regression fit fails when you pass a multiple time series object where the group_cols is of string type.

**To Reproduce**
```
import pandas as pd
from darts import TimeSeries
from darts.models import (
    RandomForest,
    RegressionModel
)

data = [['item1',  '01-01-2023', 10],
        ['item1',  '01-02-2023', 20],
        ['item1',  '01-03-2023', 30],
        ['item2',  '01-01-2023', 100],
        ['item2',  '01-02-2023', 200],
        ['item2',  '01-03-2023', 300]
       ]
df = pd.DataFrame(data, columns=['item' , 'sale_date', 'units'])
df['sale_date'] = pd.to_datetime(df['sale_date'])

item_list = TimeSeries.from_group_dataframe(df, group_cols = 'item', value_cols = 'units', time_col = 'sale_date')

model = RandomForest(lags=1,
                     output_chunk_length=1
                    )
model.fit(item_list)

predict = model.predict(n = 1, series = item_list)
```
Error: ValueError: could not convert string to float: 'item1'

**Expected behavior**
Model should be able to fit and predict without any error.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.23.1

**Additional context**
Multiple timeseries works for any neural net algorithms like RNN or N-Hits. Also note that, the fit for RandomForest works fine if the group_col is of type int or float.

**Comment by madtoinou** [comment]
Hi,

This error message is due to the fact that darts assumes that the grouping column is a static covariate and the model then struggles to convert it into values it can actually consume.

Depending on what you need, you might need to call `series.with_static_covariates(None)` to remove them prior to `fit()`/`predict()` or you could convert them before calling `from_group_dataframe`.

I am not sure if darts should add a more meaningful error message or try to handle this kind of situation in the function.

**Comment by dennisbader** [comment]
Hey @pshetty44, currently the only model that support categorical static covariates is `TFTModel`.
We are working on adding categorical support for selected regression models that support it (LightGBM, Catboos, ..) for example in #1585.

You can use our `StaticCovariatesTransformer` to transform the categorical data into numeric, see the docs [here](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.static_covariates_transformer.html#darts.dataprocessing.transformers.static_covariates_transformer.StaticCovariatesTransformer).

Extending your example:
```
from darts.dataprocessing.transformers import StaticCovariatesTransformer

item_list = TimeSeries.from_group_dataframe(df, group_cols='item', value_cols='units', time_col='sale_date')
transformer = StaticCovariatesTransformer(
    cols_num=[]  # don't scale any numeric columns, only the categorical ones
)
item_list_static_transformed = transformer.fit_transform(item_list)
```

You can see that now your static covariates are all numeric:

```
for series in item_list_static_transformed:
    print(series.static_covariates)
```

Gives:
```
static_covariates  item
component              
units               0.0 

static_covariates  item
component              
units               1.0 
```

**Comment by pshetty44** [comment]
Categorical static covariates also works for most of the neural nets like `N-Beats`, `N-Hits`, `RNN` etc. I was explicitly converting the categorical static covariates to numeric for RF and Regression models. Good to know I can do this via `StaticCovariatesTransformer`. Thanks @dennisbader. You can close this issue since the team is already working on adding categorical support for other models and a related PR is open.

**Comment by dennisbader** [comment]
@pshetty44, these models actually do not use static covariates at all yet.
You can find which models support static covariates in [this table](https://unit8co.github.io/darts/#forecasting-models).

**Comment by pshetty44** [comment]
Thanks for clarifying this @dennisbader.
