### ISSUE TITLE
Accessing AutoARIMA order

### ISSUE THREAD

**Issue by bgrey001** [unit8co/darts#1608]
Hi there,

Apologies if I have missed the answer to this in the documentation but I've looked - how can I access the model order for AutoARIMA?

I would also like to know how to access model summaries in general - is this a feature? 

Thanks

**Comment by dennisbader** [comment]
You can access the underlying model after fitting with `ForecastingModel.model`:

```
from darts.models import AutoARIMA
model = AutoARIMA()
model.fit(...)

# access underlying model under `ForecastingModel.model`
print(model.model.summary())
```

**Comment by bgrey001** [comment]
Thank you!
