### ISSUE TITLE
How can the TFT model trained sequence to sequence.

### ISSUE THREAD

**Issue by lk1983823** [unit8co/darts#1610]
When reading the instruction of "https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#forecast-prediction", I find if  n > output_chunk_length, the model can work in an auto-regressive fashion. Can this be achieved in the training process?

**Comment by dennisbader** [comment]
@lk1983823, no this is currently not possible. The model is trained by minimizing the loss between `output_chunk_lentgh` predictions and actual values per example.
