### ISSUE TITLE
How to get the range of predicted values correctly

### ISSUE THREAD

**Issue by Luffffffy** [unit8co/darts#1611]
I recently encountered a problem that has troubled me for a long time:

1. I need the model to predict a range, so I have specified `Likelihood=GaussianLikelihood()` for my model.
2. I hope the effect is like this figure
![image](https://user-images.githubusercontent.com/49063302/222651880-0eed5222-2cb3-4176-aa78-77231da562a0.png)
3. But when I specify the `low_quantile`and `high_quantile`thresholds and hope to get the same effect, I get this result
![image](https://user-images.githubusercontent.com/49063302/222652031-643e6d5a-022c-432a-8e87-ee198caa8e97.png)
4. the bule line is actual values, the red line is predict values(`_forecasts`), and deep colour area is predict range values(`_q2 and _q8`),  with my code:
```
preds = Model.predict(n=30, series=series, past_covariates=past_covariates, num_samples=10000) 
for i in range(len(preds)):
    _forecasts = preds[i].values()
   _q2, _q8 = preds[i].quantile(0.2), preds[i].quantile(0.8)
```
Is there something wrong with me?

I just found that in the first figure, the median is displayed, according to the document:
`By default TimeSeries.plot() shows the median as well as the 5th and 95th percentiles (of the marginal distributions, if the TimeSeries is multivariate). It is possible to control this:`

But there is another problem: `preds[i].values()` is not equal `preds[i].quantile(0.5)`
According to the result of Figure 2, it seems that the former is better than `preds[i].quantile(0.5)`
So how can I add the forecast range to the red line in Figure 2?

**Comment by dennisbader** [comment]
`TimeSeries.values()` returns only a single sample (of your `num_samples=10000`) per time step and component.
Use `TimeSeries.all_values()` instead to get all samples.

Even easier to use Darts' built-in `TimeSeries.quantile()`from [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.quantile).

Also, regarding your `_forecasts`, you are probably looking for the 0.5 quantile:
I'd suggest doing something like this:

```
forecasts = preds.quantile(0.5)
q2, q8 = preds.quantile(0.2), preds.quantile(0.8)
```

You could now convert the values into a numpy array with for example `q2.values()`, as those are single-sample time series.

**Comment by Luffffffy** [comment]
@dennisbader 
Oh, I see. I see. 
I was wrong from the beginning.
It means that if my model predicts a probability distribution, we should use `quantile(0.5)` to get the predicted value from `TimeSeries.all_values()`, otherwise use `TimeSeries.values()` to get the determined predicted value, right?
