### ISSUE TITLE
Exclude tests from packaging installation

### ISSUE THREAD

**Issue by FBruzzesi** [unit8co/darts#1612]
Currently darts installs its tests into `*/site-packages/darts/tests/*`.

If this is not intended behaviour, it should be enough to change line 40 of `setup.py` to `packages=find_packages(exclude=['*tests*']),` to avoid the installation.

**Comment by dennisbader** [comment]
Is there a specific reason why you would want to exclude the tests?
I think we can leave it like that. Most popular libraries do it like that (for example pandas and numpy).

**Comment by FBruzzesi** [comment]
I wanted to check if this was intentional or not. 
In general I would try to keep size as low as possible whenever I can (for darts this is almost irrelevant, but I still don't see why tests should be part of installable).
