### ISSUE TITLE
Update model?

### ISSUE THREAD

**Issue by jmrichardson** [unit8co/darts#162]
**Is your feature request related to a current problem? Please describe.**
Is it possible to update an existing model after it has been trained?  For example, a TCN model?

**Additional context**
As new training data arrives, I would like to be able to pickup the training from the last time.

Thanks for any advice

BTW, this package is really nice!  So easy to use and intuitive :)

**Comment by pennfranc** [comment]
Models that are subclasses of `TorchForecastingModel`, such as `TCNModel` do indeed allow for multiple calls to the `fit` function without losing the progress made from previous calls to `fit` (if you are using the same model instance, of course). So what you can to is train your model with the currently available data, then once you get new data, append it to the current training time series, and then call `fit` again on this newly extended time series. 

One limitation right now, however, is the fact that the number of training epochs is defined when creating the model, so all `fit` function calls will by default train the model for the same number of epochs. If needed, this can currently be circumvented by manually changing the model's `n_epochs` attribute.

This is definitely something that we can still improve, so thanks for making us aware of this! Also, please let us know if approach outlined above works for you.

**Comment by jmrichardson** [comment]
@pennfranc 

Thank you for the fast response and will give your suggestion a try and report back soon.  Thanks :)

**Comment by TheMP** [comment]
hi @jmrichardson , did you decide to give it a try in the end?

**Comment by zhangzw16** [comment]
I hope that you can add this feature to all models. Especially in ARIMA, like [pmdarima,](https://alkaline-ml.com/pmdarima/usecases/stocks.html#updating-the-model) they allow users to add new training points to re-fit the model, rather than training the model from scratch.
