### ISSUE TITLE
[BUG-FIX] RegressionEnsembleModel : Error when trying to predict with FutureCovariates | Suggested With Code Fix

### ISSUE THREAD

**Issue by Rajesh4AI** [unit8co/darts#1621]
I use darts and love it. Here is  a bug I noticed and suggested possible fix in RegressionEnsembleModel

```

from darts.models import RegressionEnsembleModel,AutoARIMA,Prophet
from darts.datasets import AirPassengersDataset
import numpy as np
series_air = AirPassengersDataset().load()
models = [Prophet(),AutoARIMA()]
ensemble_model = RegressionEnsembleModel(forecasting_models=models,regression_train_n_points=12)

#### This would run
ensemble_model.fit(series=series_air[:-36] 
                   ,future_covariates=series_air
                   )
##### Error: Predict would fail as Fit doesn't fit the models on future covariate due to bug
pred_air=ensemble_model.predict(n=36,series=series_air[:-36],future_covariates=series_air)

```
![image](https://user-images.githubusercontent.com/49446538/222972223-b254da87-cbaf-474e-ae6f-ca011bb50f63.png)

Proposed Code Fix in RegressionEnsembleModel (line number 147) :

![image](https://user-images.githubusercontent.com/49446538/222972260-e8064492-b0e9-4312-b96a-da5eeb61bc51.png)

**Comment by madtoinou** [comment]
Hi,

Sorry for the delay, and thank you for investigating the source of the problem and suggest a fix!

Could you open a pull request with the change mentioned above so that reviewers can comment it and merge the fix? If you don't have the bandwidth, I would be happy to do it for you.

**Comment by Rajesh2rajer** [comment]
Sure Madtoinou. Happy to do the same!
