### ISSUE TITLE
Unable to load darts v0.22.0 model without GPU

### ISSUE THREAD

**Issue by aiwithsap** [unit8co/darts#1624]
Hi
I have been using darts v0.22.0 for the last few months. I had trained my model on a GPU machine and saved it via model.save(). Now when I'm trying to deploy it on a CPU only machine, I used the following code to place the model on CPU. 

```
  model = torch.load(home + "model.txt.ckpt", map_location=torch.device('cpu'))
```
The model loads ok but when I use model.historical_forecasts() the below dump is shown. It seems the model is still looking for a GPU. 
A lot of my work will be lost if I don't find a way around this. Any help will be highly appreciated.

Thanks

Adeel

`No supported gpu backend found! Traceback (most recent call last):\n  File "/code/central/temp/onykz6rv/968/model/darts_class.py", line 171, in run_testing\n    preds = model.historical_forecasts(series=lst_test[t], past_covariates=lst_test_cov[t], retrain=False, forecast_horizon=horizon)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/utils/utils.py", line 172, in sanitized_method\n    return method_to_sanitize(self, *only_args.values(), **only_kwargs)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/forecasting_model.py", line 500, in historical_forecasts\n    forecast = self._predict_wrapper(\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/forecasting_model.py", line 1228, in _predict_wrapper\n    return self.predict(\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/utils/torch.py", line 112, in decorator\n    return decorated(self, *args, **kwargs)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1051, in predict\n    predictions = self.predict_from_dataset(\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/utils/torch.py", line 112, in decorator\n    return decorated(self, *args, **kwargs)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1178, in predict_from_dataset\n    self._setup_trainer(trainer=trainer, verbose=verbose, epochs=self.n_epochs)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 457, in _setup_trainer\n    self._init_trainer(trainer_params=trainer_params, max_epochs=epochs)\n  File "/root/miniconda3/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 471, in _init_trainer\n    return pl.Trainer(**trainer_params_copy)\n  File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 340, in insert_env_defaults\n    return fn(self, **kwargs)\n  File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 414, in __init__\n    self._accelerator_connector = AcceleratorConnector(\n  File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 206, in __init__\n    self._accelerator_flag = self._choose_gpu_accelerator_backend()\n  File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 512, in _choose_gpu_accelerator_backend\n    raise MisconfigurationException("No supported gpu backend found!")\nlightning_lite.utilities.exceptions.MisconfigurationException: No supported gpu backend found!`

**Comment by dennisbader** [comment]
Hi @aiwithsap, we have a dedicated save/load API for our TorchForecasting models:
For example for a TFTModel:
- save models: see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.save)
```
model.save("my_model.pt")
```
- load models: see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.load)
```
model_loaded = TFTModel.load("my_model.pt" map_location="cpu")
# move model to cpu
model_loaded.to_cpu()
```

**Comment by aiwithsap** [comment]
Hi @dennisbader 

Thanks for your response. Here is the error I get when using load function.

```
model = NHiTSModel.load( home + "/model/vision_model.txt", map_location="cpu")
TypeError: load() got an unexpected keyword argument 'map_location'
```

Perhaps in v0.22.0 of darts, map_location parameter was not present.

Cheers

Adeel

**Comment by dennisbader** [comment]
Yes, that's true. If you want to continue using 0.22.0, could you try the proposed solution [here](https://github.com/unit8co/darts/issues/1245)?

**Comment by aiwithsap** [comment]
Hi @dennisbader 
My sincere thanks for your help. You saved me a lot of trouble by helping those saved models to work. The solution that worked for me is as follows.

```
            model = torch.load("/model/vision_model.txt", map_location=torch.device('cpu'))
            torch.save(model, "/model/vision_model.txt")
            from darts.models import NHiTSModel
            model = NHiTSModel.load( "/model/vision_model.txt")  # , map_location="CPU" cannot be used with darts v0.22.0 as discussed

            cpu_params = {
                "accelerator": "cpu",
                "gpus": None,  # use "devices" instead of "gpus" for PyTorch Lightning >= 1.7.
                "auto_select_gpus": False
            }
            model.trainer_params.update(cpu_params)
```

**Comment by simonweppe** [comment]
Hi there,
Thanks for the infos, this allowed me to properly load a model trained on GPU to be used on CPU, However, when I try to predict Im getting using that loaded model I get :
```
model_TCN = TCNModel.load(mod_name, map_location = 'cpu') 
model_TCN.to_cpu()
pred = model_TCN.predict(30, series=train_trf, past_covariates=None)


*** ValueError: 
 you tried to log -1 which is currently not supported. Try a dict or a scalar/tensor.
```

Any suggestions on what I might be  ?
