### ISSUE TITLE
Pytorch lightning version[BUG]

### ISSUE THREAD

**Issue by gitbooo** [unit8co/darts#1626]
**Describe the bug**
I'm getting this error `TypeError: Trainer.__init__() got an unexpected keyword argument 'progress_bar_refresh_rate` after running the predict function on trained model 

**System (please complete the following information):**
 - Python version: [e.g. 3.10]
 - darts version [e.g. 0.23.1]

**Comment by dennisbader** [comment]
Hi @gitbooo, could you provide a minimum reproducible example?
Also, which Darts (I assume it's not 0.14.0) and PyTorch Lightning version are you using?

**Comment by dennisbader** [comment]
This example is still not reproducible. I tried to replicate the example as much as I could (I can't use a comet logger, gpu).
See my adapted example below (I commented changes with "# change"

Also: could it be that you trained the model on an older Darts version and now you're loading in the new version?
This can very likely be the issue as we refactored the code quite a bit which doesn't offer backwards compatibility.

```
import os

from darts.models import BlockRNNModel
from darts.datasets import AirPassengersDataset
from pytorch_lightning.callbacks.early_stopping import EarlyStopping
from pytorch_lightning.loggers import TensorBoardLogger


ts = AirPassengersDataset().load()  # change
my_stopper = EarlyStopping(monitor="val_loss")  # change
pl_trainer_kwargs = {
    "callbacks": [my_stopper],
    "logger": TensorBoardLogger(
        save_dir=os.path.join(os.getcwd(), "darts_logs/LSTM/"),
        name="logs",
    )  # change
}

model=BlockRNNModel(
    input_chunk_length=12,
    output_chunk_length=6,
    model='LSTM',
    n_rnn_layers=2,
    dropout=.2,
    batch_size=16,
    pl_trainer_kwargs=pl_trainer_kwargs,
    model_name="LSTM",  # change
    save_checkpoints=True,  # change
    force_reset=True,  # change
)

model.fit(series=ts, val_series=ts[-40:])
best_model = BlockRNNModel.load_from_checkpoint(model_name='LSTM', best=True)
best_model.predict(n=6, series=ts)
```
