### ISSUE TITLE
Can plot function use plotly library as options?

### ISSUE THREAD

**Issue by joshua-xia** [unit8co/darts#1631]
can all plot function use plotly library to plot the interactive picture in html format.

plotly see: https://plotly.com/python/

Thanks!

**Comment by madtoinou** [comment]
Hi,

This is not natively supported by darts; the `TimeSeries.plot()` method is a wrapper around `xarray.DataArray.plot()` which is in turn, relying on `matplotlib.pyplot`.

You should however be able to use `plotly` as a rendering engine after converting your `TimeSeries` to `pd.DataFrame` using the following code snippet:
```python
df = pd.DataFrame(series.values(), index=series.time_index.values, columns=list(series.components))
```
