### ISSUE TITLE
Does saving predictions not exist?

### ISSUE THREAD

**Issue by chengyineng38** [unit8co/darts#1632]
I used 3+ hours to produce my `historical_forecasts`. Is there no way to persist these predictions? All the examples show only metric calculations.

**Comment by dennisbader** [comment]
Apart from that, there is also always the easy option to just pickle the output of historical forecasts (of course only if your use can handle all the cons/drawbacks of pickling)

**Comment by chengyineng38** [comment]
Thanks, both! I need to do a lot more processing than `TimeSeries` alone because I have multivariate time series and I have groups of TimeSeries. In general, the documentation is lacking end-to-end examples for grouped Time Series.

**Comment by madtoinou** [comment]
@chengyineng38 is this problem solved or do you still have troubles exporting your `TimeSeries` to memory?

**Comment by chengyineng38** [comment]
The problem is resolved.
