### ISSUE TITLE
[BUG] Unable to run method .predict(num_steps, num_samples = 1000) for StatsforecastETS model

### ISSUE THREAD

**Issue by rllyryan** [unit8co/darts#1636]
**Describe the bug**
I ran into an error as shown below:
```
FutureWarning: `ETS` will be deprecated in future versions of `StatsForecast`. Please use `AutoETS` instead.
  ETS._warn()
Time taken to fit model: 0:00:10.398431
ValueError: `num_samples > 1` is only supported for probabilistic models.
Traceback (most recent call last):
  File "forecast_compilation_v2.py", line 321, in <module>
    forecast = forecast_compilation_object.run_selected_forecasting_algorithm(chosen_algorithm_id = 2, num_steps_to_forecast = 16, confidence_interval = 97.5)
  File "forecast_compilation_v2.py", line 177, in run_selected_forecasting_algorithm
    return self.forecasting_algorithms_dictionary[chosen_algorithm_id](num_steps_to_forecast = num_steps_to_forecast)
  File "forecast_compilation_v2.py", line 248, in execute_statsforecast_ets
    prediction_timeseries = forecast_model.predict(num_steps_to_forecast, num_samples=1000)
  File "/home/rllyryan/.local/lib/python3.8/site-packages/darts/models/forecasting/forecasting_model.py", line 1924, in predict
    super().predict(n, num_samples)
  File "/home/rllyryan/.local/lib/python3.8/site-packages/darts/models/forecasting/forecasting_model.py", line 239, in predict
    raise_log(
  File "/home/rllyryan/.local/lib/python3.8/site-packages/darts/logging.py", line 129, in raise_log
    raise exception
ValueError: `num_samples > 1` is only supported for probabilistic models.

```
With reference to the error "**ValueError: `num_samples > 1` is only supported for probabilistic models.**", I would like to clarify whether the model is actually probabilistic or not? The StatsforecastAutoETS model on Nixtla's repository states that it is probabilistic and that prediction intervals can be extracted.

**To Reproduce**
My code is too long to reproduce, but simply run the `predict()` method with `num_samples > 1`.

```python
forecast_model = StatsForecastETS(season_length=12)
forecast_model.fit(timeseries)
prediction_timeseries = forecast_model.predict(num_steps_to_forecast, num_samples=1000)
```

**Expected behavior**
A predicted timeseries was expected to be returned.

**System (please complete the following information):**
 - Python version: [3.8.10 64-bit]
 - darts version [0.23.1]

**Additional context**
NIL

**Comment by madtoinou** [comment]
Hi,

The next release of darts will include the latest version of the statsforecast's models, notably AutoETS which can be probabilistic but 0.23.1 is still relying on the "old" StatsForecast ETS that do not support it.

The table at the bottom of the [readme](https://unit8co.github.io/darts/README.html) summarize which model are probabilistic in the latest release.

**Comment by rllyryan** [comment]
Hi!

Excited for the next release! Is there a rough estimate for the date of release for this new version?

**Comment by madtoinou** [comment]
We plan to release it in the upcoming weeks, hopefully before the end of March!
