### ISSUE TITLE
[BUG] Documentation states that VARIMA supports univariate time series, but attempting to fit a VARIMA model on a univariate time series throws an exception.

### ISSUE THREAD

**Issue by JLC827** [unit8co/darts#1641]
**Describe the bug**
Hi, attempting to fit a VARIMA model on a univariate series throws the exception `raise ValueError("Only gave one variable to VAR")`. Current documentation incorrectly states that the VARIMA model supports univariate time series.

This occurs whether future covariates are used or not.

**To Reproduce**

``` python
from darts.datasets import AirPassengersDataset
from darts.models import VARIMA

series_air = AirPassengersDataset().load()
model = VARIMA(p=1, d=1, q=1)
model.fit(series=series_air)
```

**Expected behavior**
Either the VARIMA model should just function as an ARIMA model when used with a univariate time series, or documentation should be corrected/updated to specify that VARIMA does not support univariate time series.

For example, this chart on the[ darts main page](https://unit8co.github.io/darts/) states that VARIMA supports univariate time series. [This other documentation states that a fitted time series 'can be multivariate', not that it must be.](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.varima.html?highlight=varima#darts.models.forecasting.varima.VARIMA.fit)

![image](https://user-images.githubusercontent.com/38880886/224418407-e544f201-7704-4eec-ae49-c4a6c3c61198.png)

**System (please complete the following information):**
- Python version: 3.10
- darts version 0.23.1
- Windows 10.0.19045

**Additional context**
I'm not aware of any reason you would want to use a VARIMA model on a univariate time series, it makes more sense to just use an ARIMA model. But there may be specific use cases where the number of target parameters of a model is unknown ahead of time.

Thanks!

**Comment by dennisbader** [comment]
Hi @JLC827 and thanks for raising this. Will be fixed with #1657.
