### ISSUE TITLE
What does multimodels do?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#1646]
I saw on github documentation that the definition of multi_models is as below:
        Optionally, specifies whether the regression model predicts multiple timesteps into the future. If `True`,
        then the regression model is assumed to predict all of the timesteps from time `t` to `t+output_chunk_length`.
        If `False`, then the regression model is assumed to predict *only* the timestep at `t+output_chunk_length`.
Does this mean that only 1 model is trained on the training set and the only difference is whether it predicts the entire output chunk length or just the last point in the output chunk length?

Is there a difference in how the training set is constructed when multi_models = True/ multi_models = False?

How are the predictions done differently?

**Comment by ETTAN93** [comment]
thanks dennis, that makes sense. so if multi_models = False, even if you set target_lag = [-1] for example, when doing the predictions with n=3, only t+3 is predicted using target_lag = [-1], t+2 is actually predicted using target_lag = [-2]

**Comment by dennisbader** [comment]
Exactly 👍

**Comment by ETTAN93** [comment]
@dennisbader In a similar thread, do I need to specify the add_encoders parameter as below for darts to know where the lags are relative to the prediction time point?

add_encoders={
    'position': {'past': ['relative'], 'future': ['relative']}
}
From the documentation I can see this explanation:
![image](https://user-images.githubusercontent.com/59031005/228050534-9822696c-7dbe-443c-823c-ca9e930b65a0.png)

Or does darts automatically know how it works based on the time series index of the dataframe?

**Comment by dennisbader** [comment]
Yes, that is correct. Depending on your past_covariates_lags and future_covariates_lags, it could be that adding "relative" encoding for "past" and "future" leads to duplicate values though (as negative lags_future_covariates are in the past).
