### ISSUE TITLE
[BUG] 01-multi-time-series-and-covariates: wrong value in notebook

### ISSUE THREAD

**Issue by allansuzuki** [unit8co/darts#1647]
Isn't the `future_covariates` supposed to receive the val_covariates?  
`future_covariates = [air_val_covariates, milk_val_covariates],`

error in cell 16:
```
model_futcov = RNNModel(
    model="LSTM",
    hidden_dim=20,
    batch_size=8,
    n_epochs=100,
    random_state=0,
    training_length=36,
    input_chunk_length=24,
    force_reset=True,
)

model_futcov.fit(
    series=[train_air, train_milk],
    future_covariates=[air_train_covariates, milk_train_covariates],
    verbose=False,
);
```

**Comment by dennisbader** [comment]
No, this is correct. You can read in ou [user guide](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#in-depth-look-at-how-input-data-is-used-when-training-and-predicting-with-tfms) how the future covariates are used during training.
