### ISSUE TITLE
[BUG] NaN with every model I tried (TFT, DLinear, NBEATS)

### ISSUE THREAD

**Issue by vmajor** [unit8co/darts#1650]
**Describe the bug**
NaN during training and as an output of forecast series

**To Reproduce**
I made a short code example that results in NaN. This is not my main project, that is now a convoluted tortured mess where I am trying to somehow persuade it not to make any more NaN:

```
import pandas as pd
from darts import TimeSeries
from darts.models import NBEATSModel
from darts.metrics import mape
import torch
from sklearn.preprocessing import MinMaxScaler

# Import the required libraries only once
# Remove the duplicate imports
# Combine the two df variable definitions into one
df = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1262563200&period2=1609372800&interval=1d&events=history&includeAdjustedClose=true')\
    .merge(pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/MSFT?period1=1262563200&period2=1609372800&interval=1d&events=history&includeAdjustedClose=true'),on='Date',suffixes=('_AAPL','_MSFT'))\
    [['Date','Adj Close_AAPL','Adj Close_MSFT']]

# Convert the Date column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Get the summary statistics of the original data
summary_original = df.describe()
print('Original data summary:')
print(summary_original)

# Check for NaN values in the DataFrame
print('NaN values in the original DataFrame:')
print(df.isna().sum())

# Scale the data using MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
scaled_values = scaler.fit_transform(df.drop(['Date'],axis=1))
df.iloc[:,1:3] = scaled_values

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
torch.set_float32_matmul_precision('high')

# Convert the DataFrame to a TimeSeries object and split into train and validation sets
series = TimeSeries.from_dataframe(df, 'Date', freq='D')
train, val = series.split_after(pd.Timestamp('2019-12-31'))

# Define the model with the correct pl_trainer_kwargs assignment
model = NBEATSModel(input_chunk_length=30, output_chunk_length=10, n_epochs=5, pl_trainer_kwargs={'accelerator':'gpu','gpus':[0]}, optimizer_kwargs={'lr':1e-05})

# Fit the model to the training data
model.fit(train)

# Make predictions on the validation data and calculate the MAPE
prediction = model.predict(len(val))
print('MAPE:', mape(prediction, val))
```

**Expected behavior**
A non NaN forecast

**System (please complete the following information):**
 - Python version: 3.10.9
 - darts version: 0.23.1

**Additional context**
Help.

**Comment by vmajor** [comment]
Indeed. Thank you for looking at this and pointing out the obvious issue. While the original dataframe does not show any NaN, darts expects a frequency and markets are not open on weekends and holidays.

I am presently attempting to make use of pandas-market-calendars to construct a custom frequency, and failing, but I am (still) convinced that this is possible since it stands to reason that darts can handle sources will genuinely irregular frequencies without having to fill the blank values with approximations, or NaN.

**Comment by vmajor** [comment]
Solved the issue now thanks to your and Piotr's help. It took some effort to intersect the dataframe with NYSE open days (closed days in fact) and we (GPT-4, Bing AI, Copilot, Safurai, and me :) did manage to set a custom frequency using Pandas CustomBudinessDay function. 

This is what ended up working after hours of trying to figure out a way through the rabbit hole that is panads_market_calendars and giving up:
```
class NYSE_Calendar(AbstractHolidayCalendar):
    rules = [
        Holiday("New Years Day", month=1, day=1, observance=nearest_workday),
        USMartinLutherKingJr,
        USPresidentsDay,
        GoodFriday,
        USMemorialDay,
        Holiday("US Independence Day", month=7, day=4, observance=nearest_workday),
        USLaborDay,
        USThanksgivingDay,
        Holiday("Christmas", month=12, day=25, observance=nearest_workday),
        Holiday("National Day of Mourning for President George H. W. Bush",
                year=2018, month=12, day=5),
    ]

def create_custom_calendar():
    nyse_cal = NYSE_Calendar()
    nyse_cday = CustomBusinessDay(weekmask='Mon Tue Wed Thu Fri', holidays=nyse_cal.holidays())
    return nyse_cday
```

**Comment by madtoinou** [comment]
Happy to hear that it's working and thanks for sharing your (you, GPT4, Binge AI, Copilot and Safurai) solution!

**Comment by AjinkyaBankar** [comment]
> Solved the issue now thanks to your and Piotr's help. It took some effort to intersect the dataframe with NYSE open days (closed days in fact) and we (GPT-4, Bing AI, Copilot, Safurai, and me :) did manage to set a custom frequency using Pandas CustomBusinessDay function.
> 
> This is what ended up working after hours of trying to figure out a way through the rabbit hole that is pandas_market_calendars and giving up:
> 
> ```
> class NYSE_Calendar(AbstractHolidayCalendar):
>     rules = [
>         Holiday("New Years Day", month=1, day=1, observance=nearest_workday),
>         USMartinLutherKingJr,
>         USPresidentsDay,
>         GoodFriday,
>         USMemorialDay,
>         Holiday("US Independence Day", month=7, day=4, observance=nearest_workday),
>         USLaborDay,
>         USThanksgivingDay,
>         Holiday("Christmas", month=12, day=25, observance=nearest_workday),
>         Holiday("National Day of Mourning for President George H. W. Bush",
>                 year=2018, month=12, day=5),
>     ]
> 
> def create_custom_calendar():
>     nyse_cal = NYSE_Calendar()
>     nyse_cday = CustomBusinessDay(weekmask='Mon Tue Wed Thu Fri', holidays=nyse_cal.holidays())
>     return nyse_cday
> ```

Its great to know that you made it work! Can you please share a code snippet demonstrating how to use this `nyse_cday` in your original code?

**Comment by ivelin** [comment]
> Solved the issue now thanks to your and Piotr's help. It took some effort to intersect the dataframe with NYSE open days (closed days in fact) and we (GPT-4, Bing AI, Copilot, Safurai, and me :) did manage to set a custom frequency using Pandas CustomBusinessDay function.
> 
> This is what ended up working after hours of trying to figure out a way through the rabbit hole that is pandas_market_calendars and giving up:
> 
> ```
> class NYSE_Calendar(AbstractHolidayCalendar):
>     rules = [
>         Holiday("New Years Day", month=1, day=1, observance=nearest_workday),
>         USMartinLutherKingJr,
>         USPresidentsDay,
>         GoodFriday,
>         USMemorialDay,
>         Holiday("US Independence Day", month=7, day=4, observance=nearest_workday),
>         USLaborDay,
>         USThanksgivingDay,
>         Holiday("Christmas", month=12, day=25, observance=nearest_workday),
>         Holiday("National Day of Mourning for President George H. W. Bush",
>                 year=2018, month=12, day=5),
>     ]
> 
> def create_custom_calendar():
>     nyse_cal = NYSE_Calendar()
>     nyse_cday = CustomBusinessDay(weekmask='Mon Tue Wed Thu Fri', holidays=nyse_cal.holidays())
>     return nyse_cday
> ```

I came across this python lib that seems to focus on these custom market calendars. Have you tried it?
https://pypi.org/project/pandas-market-calendars/

Could you please share how specifically you pass a custom calendar to the Darts Timeseries constructor? 
I have been using freq='B' with holidays as future covariates, but the real goal is to use a market calendars.  Darts seems to only accept a string letter for frequency and when I pass a dataframe with custom datetimeindex with its own custom frequency, Darts errors when it tries to infer it.

Thank you!

**Comment by vmajor** [comment]
Sorry for the lack of replies, but I moved on to GluonMX as I kept running into knowledge and capability issues when trying to use Darts for my project. I needed a better way to handle covariates.

ie. I have no working Darts code right now.

**Comment by madtoinou** [comment]
> Its great to know that you made it work! Can you please share a code snippet demonstrating how to use this `nyse_cday` in your original code?

This is how you can use the custom calendar.

```python
import pandas as pd
from pandas.tseries.holiday import Holiday, USMartinLutherKingJr, USPresidentsDay, GoodFriday, USMemorialDay, USLaborDay, USThanksgivingDay
from pandas.tseries.holiday import AbstractHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

import numpy as np
from darts import TimeSeries

# copy-paste code above

custom_freq = create_custom_calendar()
times = pd.date_range("2000-01-01", "2001-01-01", freq=custom_freq)
ts = TimeSeries.from_times_and_values(values = np.random.randint(0, 10, len(times)), times = times)
```

If your dataframe has a custom datetimeindex, it must be converted to a custom calendar before trying to create the `TimeSeries`

**Comment by ivelin** [comment]
Thank you for sharing the specific code example. I thought from_dataframe only allows the string version of freq ('D', 'B'). Let me give this another try.

**Comment by ivelin** [comment]
> > Its great to know that you made it work! Can you please share a code snippet demonstrating how to use this `nyse_cday` in your original code?
> 
> This is how you can use the custom calendar.
> 
> ```python
> import pandas as pd
> from pandas.tseries.holiday import Holiday, USMartinLutherKingJr, USPresidentsDay, GoodFriday, USMemorialDay, USLaborDay, USThanksgivingDay
> from pandas.tseries.holiday import AbstractHolidayCalendar
> from pandas.tseries.offsets import CustomBusinessDay
> 
> import numpy as np
> from darts import TimeSeries
> 
> # copy-paste code above
> 
> custom_freq = create_custom_calendar()
> times = pd.date_range("2000-01-01", "2001-01-01", freq=custom_freq)
> ts = TimeSeries.from_times_and_values(values = np.random.randint(0, 10, len(times)), times = times, freq=custom_freq)
> ts = TimeSeries.from_dataframe(df, "timecol", freq=custom_freq)
> ```
> 
> If your dataframe has a custom datetimeindex, it must be converted to a custom calendar before trying to create the `TimeSeries`

@madtoinou  , which version of Darts TimeSeries.from_dataframe supports custom calendars. It looks like the latest code in the main branch still insists on str or int value for freq.
https://github.com/unit8co/darts/blob/962fd78cb526887c47bddc33bea4b731adf72a87/darts/timeseries.py#L551

**Comment by AjinkyaBankar** [comment]
> Sorry for the lack of replies, but I moved on to GluonMX as I kept running into knowledge and capability issues when trying to use Darts for my project. I needed a better way to handle covariates.
> 
> ie. I have no working Darts code right now.

Hello @vmajor may I know what is GluonMX? Can you please provide appropriate link?

**Comment by AjinkyaBankar** [comment]
> > Its great to know that you made it work! Can you please share a code snippet demonstrating how to use this `nyse_cday` in your original code?
> 
> This is how you can use the custom calendar.
> 
> ```python
> import pandas as pd
> from pandas.tseries.holiday import Holiday, USMartinLutherKingJr, USPresidentsDay, GoodFriday, USMemorialDay, USLaborDay, USThanksgivingDay
> from pandas.tseries.holiday import AbstractHolidayCalendar
> from pandas.tseries.offsets import CustomBusinessDay
> 
> import numpy as np
> from darts import TimeSeries
> 
> # copy-paste code above
> 
> custom_freq = create_custom_calendar()
> times = pd.date_range("2000-01-01", "2001-01-01", freq=custom_freq)
> ts = TimeSeries.from_times_and_values(values = np.random.randint(0, 10, len(times)), times = times, freq=custom_freq)
> ts = TimeSeries.from_dataframe(df, "timecol", freq=custom_freq)
> ```
> 
> If your dataframe has a custom datetimeindex, it must be converted to a custom calendar before trying to create the `TimeSeries`

This helped. Thanks @madtoinou.
