### ISSUE TITLE
[BUG] Historical forecast with retrain=Callable forecasts wrong dates

### ISSUE THREAD

**Issue by DavidKleindienst** [unit8co/darts#1655]
**Describe the bug**
When providing a `Callable` as `retrain` attribute, `CatBoostModel.historical_forecasts` creates a historical forecast for the wrong dates.
This wrong behaviour only happens when `output_chunk_length` is set to a value `>=3`. Setting `retrain=False` leads to correct results.
Interestingly, `retrain=False` and `retrain=lambda *args: False` produce different results, which is quite unexpected.

**To Reproduce**
```python
from darts.models import CatBoostModel
from darts import TimeSeries
import pandas as pd
import numpy as np

dates = pd.date_range("2021-02-01", "2021-04-19", freq="W-Mon")
series = TimeSeries.from_times_and_values(dates, np.sin(np.arange(len(dates))))
future_cov = TimeSeries.from_times_and_values(dates, np.cos(np.arange(len(dates))))

model = CatBoostModel(lags_future_covariates=(0, 1), output_chunk_length=10)
model.fit(series, future_covariates=future_cov)


hist_fc = model.historical_forecasts(series, future_covariates=future_cov, start=pd.Timestamp("2021-02-11"), retrain=lambda *args: False)
print(hist_fc.start_time())
# >> 2021-04-12 00:00:00

hist_fc2 = model.historical_forecasts(series, future_covariates=future_cov, start=pd.Timestamp("2021-02-11"), retrain=False)
print(hist_fc2.start_time())
# >> 2021-02-15 00:00:00
```
**Expected behavior**
`model.historical_forecasts` should honor the `start` parameter and start forecasting at the first timepoint after `start`, also when `retrain` is set to a callable. Further, historical_forecasts with `retrain=False` and `retrain=lambda *args: False` should return the same results (except maybe for some randomness in the forecast)

**System (please complete the following information):**
 - Python version: 3.10
 - darts version: 0.23.1 & master

**Additional context**

**Comment by dennisbader** [comment]
Hi @DavidKleindienst, and thanks for raising this. This is indeed a bug. A added it to our backlog.
