### ISSUE TITLE
[BUG] `plot_residuals_analysis` raises ValueError for len(TimeSeries) <= 24

### ISSUE THREAD

**Issue by VivCh14** [unit8co/darts#1659]
**Describe the bug**
In the function `plot_residuals_analysis` from the `darts.utils.statistics` library, the `max_lag` argument in the ACF plot uses the default value of 24. This causes a `ValueError` if the `len(residuals)  <= 24`. 
**To Reproduce**
1. Start with a TimeSeries `train` of len <= 24
2. Fit a model on `train`
3. Call `plot_residuals_analysis(model.residuals(train))`
4. Throws `ValueError` from the `plot_acf` call

**Expected behavior**
Irrespective of the TimeSeries length, `plot_residuals_analysis(model.residuals(train))` should produce the residual analysis results.
**System (please complete the following information):**
 - Python version: 3.9.16
 - darts version: 0.23.1

**Additional context**
Having `max_lag = len(residuals)-1` as the argument to `plot_acf()` when called within `plot_residuals_analysis` will fix the issue.

**Comment by Loudegaste** [comment]
Hi @VivCh14 , thanks a lot for pointing it out :) I added PR #1857 to fix this issue

**Comment by VivCh14** [comment]
Hi @Loudegaste, Thank you for adding a PR to fix this issue, highly appreciated :)
