### ISSUE TITLE
Forecast horizon for TCN model

### ISSUE THREAD

**Issue by misterspook** [unit8co/darts#1665]
Hi,

I have a question regarding the input data and the forecasting horizon for the TCN model. I have a data based on a time index (0-35) and group based input values. My setup is as follows:

`series_en_train = TimeSeries.from_group_dataframe(df_train_sample, "group", time_col = "time_idx", 
                                                  value_cols = "NDVI", 
                                                  static_cols=["region"])

series_en_val = TimeSeries.from_group_dataframe(df_validation_sample, "group", time_col = "time_idx", value_cols =[ "NDVI", "TEMPERATURE_AVG", "SMI", "RADIATION", "gdd"], static_cols=["region"])

TCN = TCNModel(
    input_chunk_length=20,
    output_chunk_length=16,
    n_epochs=20,
    dropout=0.1,
    dilation_base=2,
    weight_norm=True,
    kernel_size=4,
    num_filters=3,
    random_state=0,
)

TCN.fit(
    series=series_en_train ,
    val_series=series_en_val ,
    verbose=True,
)

backtest = TCN.historical_forecasts(
    series=series_en_val ,
    start=19, # this is the start of the prediction?
    forecast_horizon=16,
    stride=3,
    retrain=False,
    verbose=True,
)

backtest[0]

TimeSeries (DataArray)

    time: 1component: 1sample: 1

    array([[[0.48676585]]])

    Coordinates:
        time
        (time)
        int64
        35
        component
        (component)
        object
        'NDVI'
    Indexes: (2)
    Attributes:

    static_covariates :
        static_covariates  group region
        component                      
        NDVI                16.0   FR10
    hierarchy :
        None

`

I was expecting that the outputs will have a length of 16 because of the forecast_horizon but, instead, the output is of length 1 and at index 35. This means that it is forecasting one point at the forecast horizon = 16 and not a sequence. I am a bit puzzled. This is a sequence to sequence forecasting task.  

thanks for your help

**Comment by dennisbader** [comment]
Hi @misterspook, for simple predictions/forecasts, use `model.predict(n=16, series=series_train)`. This will return the predictions for the next 16 time stamps after the end of `series_train`.

For more information on predict and historical forecasts, see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tcn_model.html#darts.models.forecasting.tcn_model.TCNModel.predict) and [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tcn_model.html#darts.models.forecasting.tcn_model.TCNModel.historical_forecasts).

**Comment by misterspook** [comment]
Hi @dennisbader, ok , thanks for your suggestion!
