### ISSUE TITLE
[BUG] Constant Predictions for Multivariate Probabilistic XGBoost with Quantile Likelihood.

### ISSUE THREAD

**Issue by adamkells** [unit8co/darts#1669]
**Describe the bug**
When I run an XGBoost model on a multivariate dataset using the quantile likelihood, the predictions returned are all constant (across every timestep and series). The issue does not arise using Poisson likelihood, the predictions are reasonable and of the same magnitude as the relevant time series.

### Poisson
![poisson](https://user-images.githubusercontent.com/19709277/227503814-08c323ff-71c0-4078-a566-33f1be11e2b0.png)
### Quantile
![quantile](https://user-images.githubusercontent.com/19709277/227503851-44f707fb-7ce7-4802-a280-4aa3ddb3647d.png)

When I look closer at the returned quantile model using:
```
model._model_container[0.01].estimator.predict()
```

I get an error that the model has not been fitted: `NotFittedError: need to call fit or load_model beforehand`.

**To Reproduce**
The data is dummy data of the following format:
<img width="741" alt="Screenshot 2023-03-24 at 11 01 02" src="https://user-images.githubusercontent.com/19709277/227504288-1c2842a3-66a5-4d31-bd2e-d14c95ae3994.png">

The code run is:

```
from darts.models import XGBModel
import matplotlib.pyplot as plt

model = XGBModel(lags=10, likelihood='quantile')
train, val = darts_ts_data[:-36], darts_ts_data[-36:]
model.fit(train)
probabilistic_forecast = model.predict(len(val), num_samples=1000)

plt.figure(figsize=(20,10))
darts_ts_data.plot(label="actual", linestyle='--')
probabilistic_forecast.plot(label="probabilistic forecast")
plt.legend()
plt.show()
```

**Expected behavior**
Quantile and Poisson likelihoods are expected to give results of similar magnitude.

**System (please complete the following information):**
 - Python version: 3.9.16
 - darts version 0.23.1

**Comment by dennisbader** [comment]
You actually get probabilistic forecasts, but they are on the bottom right of your plot.
There seems to be an issue with XGBoost quantile regression, with large values and non-centered data.
We'll keep an eye on this.

For now I'd suggest to use another regression model for quantile regression: LinearRegressionModel, LightGBMModel, or CatBoostModel

**Comment by AhmetZamanis** [comment]
Hi was this issue fixed? I'm still having a similar issue, where the 0.95 quantile predictions are correct but the 0.05 quantile predictions are too low.

If the issue still exists, I'll switch to another model for now. I can provide a reproducible example later.

**Comment by dennisbader** [comment]
Hi @AhmetZamanis, the issue has not been fixed yet. I'd suggest to use another model for now.

**Comment by AhmetZamanis** [comment]
Thank you for the quick reply.
