### ISSUE TITLE
[Feature] Regression Ensemble based on Learned Weighted Average 

### ISSUE THREAD

**Issue by Rajesh4AI** [unit8co/darts#1684]
**Is your feature request related to a current problem? Please describe.**
Regression ensemble model uses Linear Regression as meta learner.. I would like to suggest an alternative Learned Weighted Average. It might be good alternative to current default

**Describe proposed solution**
In some cases linear regression as meta learner is not good fit. Weighted average of models can be simple but effective alternative.  I can write code to learn the weights with constraint that weight should be positive and should sum to 1. ( Error weighted is also additional option) 

**Additional context**
Such weighted regressor and changing weights can help data scientist understand the changing behaviour of time series with time.

Will share a working code example if you feel this might be valid.

**Comment by madtoinou** [comment]
Hi,
User should be able to use any kind of regression model by passing them to the `RegressionEnsembleModel` using the `regression_model` argument in the constructor. It's possible to use sklearn models or custom models, inheriting from `LocalForecastingModel`.

I am not sure to understand how this "Learned Weighted Average" is different from a `LinearRegression` but if you could describe an example, it would be helpful to better understand the feature.

**Comment by Rajesh4AI** [comment]
I understand why current ```LinearRegression (Intercept=False)``` is smart choice. But will share examples of how minor modifaction to LR  would improve accuracies by next week in some valid cases. 

(```LearnedWeightedAverage = contrained Linear Regression``` _(constraints: Coef should be positve and sum to 1)_.

**Comment by madtoinou** [comment]
Closing this issue, en example of Weighted Average implementation is included in the Annexes of the [RegressionModel example notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Custom-model) which could then be used as `regression_model` in the ensemble.

If a lot of additional logic is required to make it work, feel free to reopen this issue and share a code snipped/open a PR.
