### ISSUE TITLE
[QUESTION] Consume a multivariate dataset and produce an univariate timeseries

### ISSUE THREAD

**Issue by alessiosavi** [unit8co/darts#1687]
Hi all, it's possible to use multiple feature in order to forecast a single feature of the input dataset?
I cannot find an example

**Comment by JanFidor** [comment]
Hi @alessiosavi ! 
First I'll drop 2 examples:
1) https://github.com/unit8co/darts/blob/master/examples/00-quickstart.ipynb -> go to the "Covariates: using external data"
2) https://github.com/unit8co/darts/blob/master/examples/01-multi-time-series-and-covariates.ipynb -> go to the "Global Forecasting Models"

And here's how I understand it: you have target series (one or many) and covariates. Covariates are divided into past, future and static ones, they're exactly what you're looking for -> data that can help us make predictions we're interested in: 
1) Past covariates are additional historical data features you can use to make better predictions on your target series. At prediction time you only get them up to your current time and no further to avoid data leakage
2) Future covariates are a stellar opposite, they'll include data from the future, usually it'll be parameters associated with time (month, day of year etc.), but they can also include predictions from other models
3) Static covariates are basically features that don't change with time (ex. coordinates for which you predict temperature)

Important note, I'm not 100% certain, but I think that main difference between target series and past covariates is that you can't make autoregressive predictions with them -> if we have a large forecast window, we need to have them all the way until the end, while target series can be infered from the models output, @madtoinou could you verify?
