### ISSUE TITLE
Transformer Forecasting Model

### ISSUE THREAD

**Issue by Splizard** [unit8co/darts#171]
With the recent popularity of GPT3, it got me thinking about how a Transformer model could be applied to time-serires forecasting.
Could this sort of  model be put on the 'wishlist' for Darts? 

There was a discussion on Kaggle recently about this and it links to more information about the suject.
https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/142833

I believe the Attention mechanisim of the model is capable of discovering certain patterns that other models struggle with and this could be a better model for certain domains of time-series forecasting.

There is a pytorch implementation here:
https://github.com/maxjcohen/transformer

a recent paper on the subject: 
Deep Transformer Models for Time Series Forecasting:The Influenza Prevalence Case
https://arxiv.org/pdf/2001.08317

**Comment by pennfranc** [comment]
This indeed looks like a very cool possibility, thanks for putting this on our radar! This could be a subclass of our `TorchForecastingModel` class.  If you're up for the challenge, you can always consider giving this a shot yourself too (check out [this](https://github.com/unit8co/darts/issues/122#issuecomment-655344527) post for guidelines regarding implementing a new model). For now we will put this on our backlog.

**Comment by inverniz** [comment]
This seems interesting to me as well! I am currently giving it a try (still working on it locally). I will let you know how it goes!

**Comment by LeoTafti** [comment]
Will be part of the next release!
