### ISSUE TITLE
[BUG] Looking for GPU when running on CPU

### ISSUE THREAD

**Issue by SebastienMc** [unit8co/darts#1710]
**Describe the bug**
I've been following and reproducing the Quickstart page of the darts website. I reached the part where we train an NBEATS model. 

An unclear `TypeError` has appeared when calling the `.fit()` method of the NBEATSModel. The error message that appears is as follows:

`TypeError: __init__() got an unexpected keyword argument 'gpus'`

I'm wondering if it is linked to pytorch lightning? My machine does not have a GPU so I have added a `pl_trainer_kwargs` argument to tell the script I am running on a CPU, but to no avail.

I do not believe this issue is limited to the NBEATSModel. The same error appears when I try a TCNModel instead.

**To Reproduce**
```
import darts
import pandas as pd
from darts.datasets import EnergyDataset
from darts.dataprocessing.transformers import Scaler
from darts.models import NBEATSModel

energy_ts = EnergyDataset().load()
load = energy_ts.pd_dataframe().iloc[:, 25]
load_ts = darts.TimeSeries.from_series(load)

start_tstamp = '3 Sep 2018 00:00'  # monday
n_tstamps = 3 * 168                # three weeks

test_ts = load_ts.slice_n_points_after(pd.Timestamp(start_tstamp), n_tstamps)
test_ts = test_ts.resample('6H')

train, val = test_ts.split_before(0.82)  # arbitraty cutoff for this example

scaler = Scaler()
train_scaled = scaler.fit_transform(train)

model = NBEATSModel(
    input_chunk_length=24, output_chunk_length=12, 
    random_state=42, pl_trainer_kwargs={"accelerator": "cpu"}
)
model.fit(train_scaled, epochs=50, verbose=True)
```

**Expected behavior**
The model should start fitting, but is seemingly looking for a new 'gpus' argument.

**System (please complete the following information):**
 - Python version: 3.9.12
 - darts version: 0.20.0

**Comment by madtoinou** [comment]
Hi @SebastienMc,

Thank you for this detailed issue. Could you try to upgrade your darts version? I just tried to run the snipped with 0.24.0 and it works just fine. Also, the notebooks are usually updated to match the latest release and keeping the library up-to-date will reduce the risk of encountering errors when running the code.

By default PytorchLightning (thus darts) uses the "cpu" by default and tries to leverage the "gpu" only if it's detect one, you should not need to specify it.

**Comment by SebastienMc** [comment]
OK this seems to cover it. Simple as that! Thank you.
