### ISSUE TITLE
TFT custom dataset shape?

### ISSUE THREAD

**Issue by asadabbas09** [unit8co/darts#1714]
I'm new to this library and want to do forecasting on the following data shape:

```
input: train_X (n_samples, n_steps, n_features) (10,000, 36, 15)
labels: train_Y (n_samples, n_outputs) (10,000, 12)
```

This means I want to use the past `36` months and  `15` features available as input.

I want to predict the future `12` months. 

I want to use the TFT model, but I'm not sure how to do I set up my model config and timeseries data shapes.

Do I need to use `input_chunk_length=36`, and `output_chunk_length=12`?

And for the `fit` method:

`model.fit(train_y, past_covariate=train_X)
`

and for 'predict' 

`model.predict(n=12)
`

**Comment by madtoinou** [comment]
Hi @asadabbas09,
What is the frequency of your data? If it's monthly, then yes, the parameters corresponding your descriptions is `input_chunk_length=36` (model will look at the last 36 months for each forward pass) and `output_chunk_length=12` (model will predict 12 months at a time).

Not sure of what you mean by `n_steps` for your `train_x` variable but you don't need to preprocess the dataset, darts will take care of it for you (creating "batches/slices" for each epoch/step). Your `TimeSeries` should have the following dimensions: [time, features, num_samples].

The `fit()/predict()` calls are correct. If you use n>12, the model will consume its own predictions in a auto-regressive way.

Note: `TFTModel` requires future covariates, you will have to see if in the 15 features you mentioned, some can be forecasted (for ex. weather?) for the future.

**Comment by asadabbas09** [comment]
Thanks @madtoinou 

n_steps means past 36 months in this case. 

As mentioned above my data shape is `(10,000 (sample), 36 (months), 15 (features))`

So how do I convert it to `[time = (36), features = (15), num_samples = (10,000)]` ? Do I just need to reshape it and also this time series will be my past covariates?

Also, my target series has shape  `(10,000, 12)`, do i also need to reshape it in some way?

I don't have any future covariates available, so this means I cant use `TFTModel`?

**Comment by asadabbas09** [comment]
@madtoinou 

Following up, I have created two-time series 

target series: `(time: 12 component: 1 sample: 10,000)`

past covariates:  `(time: 36 component: 15 sample: 10,000)`

In `TFTModel` I have set: 

```
input_chunk_length = 36
output_chunk_length = 12
add_relative_index = True

```

But `model.fit` gives me an error:

```
ValueError: The train dataset does not contain even one training sample. This is likely due to the provided training series being too short. This model expect series of length at least 48.
```
Why is model expecting series length of `48` in this case? I want to train the model to predict `target series` based on `past covariates`.

**Comment by dennisbader** [comment]
Hi @asadabbas09 , we actually have a user guide about our TorchForecastingModels (Darts' deep learning based models). You can find it [here](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html).

And [this section](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#in-depth-look-at-how-input-data-is-used-when-training-and-predicting-with-tfms) explains how your input data is used during training and prediction.

Regarding the original question, you need:
- Are your samples from the same time series or multiple different ones? Darts' handles the extraction of target input and output, so both input chunk and output chunk are from the same time series.
  - For the first case you need a univariate target TimeSeries. If your 10k samples are from shifted windows of a single time series, convert it back to original natural time series format.
  - For the latter case you need a list of 10k (sample) univariate target TimeSeries. To be able to train the model, each series must be of length `input_chunk_length+output_chunk_length=48`.
- a multivariate past covariates series (15 features) which includes (at least) all time steps from your target series. Darts' handles the input extraction of covariates automatically.
- you can use TFTModel's `add_relative_index=True` or `add_encoders` (with a future encoder) at model creation - see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html). This generates some future input to be able to use the model.

**Comment by asadabbas09** [comment]
Thanks @dennisbader It was really helpful.

I dug down, into how this data was constructed upstream. It turns out It was made from shifted windows of multiple time series. 

It has prices of over `4000` commodities spanned over `120` months. We want to use `36` months `(input_chunk_length)` to predict/forecast `12` months `(output_chunk_length)`

Each time series has `15` covariates as well. 

So should we treat it as a multiple `(4000)` time series or a single time series? 

How should I reshape or feed data into TFT in this case?

**Comment by asadabbas09** [comment]
Thanks @dennisbader @madtoinou 

I have converted my data to time series which looks like

`Timesteps:120, Components:15, Samples: 4000`

Is this a correct way of training for `input_chunk_length=36` and `output_chunk_length=12` for all `4000` commodities?

**Comment by dennisbader** [comment]
I believe what you want is:
- target series: a list/sequence of 4000 series each with shape `Timesteps:120, Components:1 (the target), Samples: 1`
  - static information about the commodities can be embedded in the target series
  - this is what you actually want to forecast
- past or future covariates: a list/sequence of 4000 series each with shape `Timesteps:120, components:14 (the covariates), samples: 1`
  - the covariates are not predicted themselves but used to help improve forecasts of the target series.    

For more information about this, here is our user guide on [covariates](https://unit8co.github.io/darts/userguide/covariates.html)
