### ISSUE TITLE
Train and test cutsom dataset

### ISSUE THREAD

**Issue by daihaozxn** [unit8co/darts#1723]
Excuse me, may I have an example for describing how to train and test custom dataset by model.fit_from_dataset and model.predict_from_dataset?

**Comment by alexcolpitts96** [comment]
fit_from_dataset and predict_from_dataset from dataset use two different dataloaders. 

[Inference datasets](https://unit8co.github.io/darts/generated_api/darts.utils.data.inference_dataset.html) are used for predict_from_dataset.

[Training datasets](https://unit8co.github.io/darts/generated_api/darts.utils.data.training_dataset.html) are used for fit_from_dataset.

Without knowing the types of models and covariates you want to use it is hard to provide guidance; however, using the dataset-based approach is very similar to using `TimeSeries` for predict/fit. It is possible to build your own dataset this way, but I will highly recommend you stick with the `TimeSeries`-based methods. They are much easier to use and do not require you to do a ton of work already done in the backend of the fit/predict methods.

**Comment by daihaozxn** [comment]
> fit_from_dataset and predict_from_dataset from dataset use two different dataloaders.
> 
> [Inference datasets](https://unit8co.github.io/darts/generated_api/darts.utils.data.inference_dataset.html) are used for predict_from_dataset.
> 
> [Training datasets](https://unit8co.github.io/darts/generated_api/darts.utils.data.training_dataset.html) are used for fit_from_dataset.
> 
> Without knowing the types of models and covariates you want to use it is hard to provide guidance; however, using the dataset-based approach is very similar to using `TimeSeries` for predict/fit. It is possible to build your own dataset this way, but I will highly recommend you stick with the `TimeSeries`-based methods. They are much easier to use and do not require you to do a ton of work already done in the backend of the fit/predict methods.

OK. Thank you for the quick reply.
