### ISSUE TITLE
[BUG] Cannot import TBATS

### ISSUE THREAD

**Issue by edevog** [unit8co/darts#1724]
**Describe the bug**
When I try to run:
`from darts.models.forecasting.tbats_model import TBATS`

I get the error:
> ModuleNotFoundError: No module named 'darts.models.forecasting.tbats_model'

**System (please complete the following information):**
 - Python version: 3.10.9
 - darts version: 0.20.0

**Additional context**
I tried updating to 0.21.0, but the conda install just hangs and the pip install only gives 0.20.0

**Comment by JanFidor** [comment]
Hi @edevog !
Have you tried using this import `from darts.models import TBATS` ?
I think that going further than `darts.models` will lead you to specific implementations which might not be the actual models intended for use

**Comment by alexcolpitts96** [comment]
Both of the following worked for me with Python 3.10:
`from darts.models import TBATS`
`from darts.models.forecasting.tbats_model import TBATS`

I will suggest you create a new conda environment and try reinstalling.
