### ISSUE TITLE
[BUG] TorchForecastingModel load_weights_from_checkpoint fails to load

### ISSUE THREAD

**Issue by evanwrm** [unit8co/darts#1725]
**Describe the bug**
When attempting to finetune a TFT model, I've run into a coulple issues regarding the `load_weights_from_checkpoint` and was unsure if I'm misusing one/both of these, or if there is any workarounds. 

1. If you include a likelihood model (e.g. QuantileRegression), when calling `load_weights_from_checkpoint` it complains of the checkpoint and instantiated value being different. In the below case it is fine since the likelihood could be set to None to achieve the same effect, but was wondering there is a better way to go about this?

2. Another issue is when using `add_encoders`, we get a `ValueError: The provided 'past_covariates' must have equal dimensionality as the 'past_covariates' used for training the model.` This doesn't occur if we don't include anything in encoders field (or complains of future_covariates if we include these as "future").

**To Reproduce**
```python
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from darts import TimeSeries
from darts import models
from darts.datasets import AirPassengersDataset

# create fake dataset
series_air = AirPassengersDataset().load().astype(np.float32)
past_covs = series_air
future_covs = series_air
target_series = series_air

tft_accelerator = (
    {"accelerator": "gpu", "devices": -1, "auto_select_gpus": True}
    if torch.cuda.is_available()
    else {"accelerator": "cpu"}
)
def create_model(model_name: str):
    return models.TFTModel(
        input_chunk_length=4,
        output_chunk_length=4,
        add_encoders={                        # <--- error when included
            "cyclic": {"past": ["month"]},
            "datetime_attribute": {
                "past": ["hour"],
            },
            "transformer": Scaler(),
        },
        # likelihood=likelihood_models.QuantileRegression(), # <--- error if uncommented
        n_epochs=10,
        model_name=model_name,
        work_dir="models",
        force_reset=True,
        save_checkpoints=True,
        pl_trainer_kwargs={**tft_accelerator},
    )

model = create_model("TFTModel")
model.fit(
    target_series, 
    past_covariates=past_covs,
    future_covariates=future_covs,
)

model = create_model("TFTModel_finetune")
model.load_weights_from_checkpoint(
    model_name="TFTModel",
    work_dir="models",
    best=False,
)

model.historical_forecasts(
    target_series, 
    past_covariates=past_covs,
    future_covariates=future_covs,
    start=0.9,
    retrain=False,
)
```

**Expected behavior**
Both likelihood models, and add_encoders should be allowed when using `load_weights_from_checkpoint`. 

**System (please complete the following information):**
 - Python version: 3.9.16
 - darts version 0.24.0

**Comment by dennisbader** [comment]
Thanks @evanwrm for this nicely written reproducible example.

You are correct, this raises an error because of the encoders.
Since we only load the weights from the checkpoint, the encoders are not yet initialized when calling predict (they get initialized just before fitting the model). We thought of loading the weights primarily for fine-tuning a model (e.g. calling `fit()` again), but we should also offer full support for direct inference/prediction.

I can add a flag to the weights loading, whether the user wants to load the encoders as well. By default this would be True. It could be beneficial to give the option so users could try out different encoders for fine tuning, assuming their dimensionality is correct.

For loading a model only for inference, you can also use `model = TFTmodel.load_from_checkpoint()` for now which should work.

**Comment by evanwrm** [comment]
Thanks for the quick response and fixes. Just wanted to add another possible snippet/test case when finetuning. When attempting to load the model with `best=True` from both `load_weights_from_checkpoint`, and `load_from_checkpoint`:

```python
import torch
import numpy as np

from darts import models
from darts.datasets import AirPassengersDataset
from darts.dataprocessing.transformers import Scaler

# create fake dataset
series_air = AirPassengersDataset().load().astype(np.float32)
past_covs = series_air
future_covs = series_air
target_series = series_air

tft_accelerator = (
    {"accelerator": "gpu", "devices": -1, "auto_select_gpus": True}
    if torch.cuda.is_available()
    else {"accelerator": "cpu"}
)
def create_model(model_name: str):
    return models.TFTModel(
        input_chunk_length=4,
        output_chunk_length=4,
        add_encoders={
            "cyclic": {"past": ["month"]},
            "datetime_attribute": {
                "past": ["hour"],
            },
            "transformer": Scaler(),
        },
        n_epochs=10,
        model_name=model_name,
        work_dir="models",
        force_reset=True,
        save_checkpoints=True,
        pl_trainer_kwargs={**tft_accelerator},
    )

# pretraining
model = create_model("TFTModel")
model.fit(
    target_series, 
    past_covariates=past_covs,
    future_covariates=future_covs,
    val_series=target_series,
    val_past_covariates=past_covs,
    val_future_covariates=future_covs,
)

# finetuning
model = create_model("TFTModel_finetune")
model.load_weights_from_checkpoint(
    model_name="TFTModel",
    work_dir="models",
    best=True,
)
model.fit(
    target_series,
    past_covariates=past_covs,
    future_covariates=future_covs,
    val_series=target_series,
    val_past_covariates=past_covs,
    val_future_covariates=future_covs,
)

# prediction
model = model.load_from_checkpoint(
    model_name="TFTModel_finetune",
    work_dir="models",
    best=True,
)
model.historical_forecasts(
    target_series, 
    past_covariates=past_covs,
    future_covariates=future_covs,
    start=0.9,
    retrain=False,
)
```

**Comment by madtoinou** [comment]
Thank you @evanwrm for sharing these code snippets, the PR should resolve the bug for the two pipelines (and the unit-tests have been updated accordingly).

**Comment by leedrake5** [comment]
Hi all,

There is a significant bug that I can't get around when using load_from_checkpoint. My example is pretty identical to the above, though a different model. 

```
>>> clf = TiDEModel.load_from_checkpoint("/Users/<user>/GitHub/milAI/outputs/TiDE/d18O_tide")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1842, in load_from_checkpoint
    model: TorchForecastingModel = torch.load(
                                   ^^^^^^^^^^^
  File "/Users/<user>/miniconda3/lib/python3.11/site-packages/torch/serialization.py", line 1464, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.random._pickle.__randomstate_ctor was not an allowed global by default. Please use `torch.serialization.add_safe_globals([__randomstate_ctor])` or the `torch.serialization.safe_globals([__randomstate_ctor])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
```
I have read the issue with malicious code being stuck in models, so it makes sense to do weights only. But all the same, do functions need to be updated to work? Passing weights_only=True/False doesn't change the error at all.

**Comment by madtoinou** [comment]
Hi @leedrake5,

The `weights_only` argument is not exposed but you could easily edit the method's code to modify it and set it to `False` (if you believe you can trust the source of the model checkpoint), you will find it in `darts/models/forecasting/torch_forecasting_model.py`.

Depending on when the model was trained and the number of release between the training version and the loading version, you might have to perform addition manipulations to be able to load your model's weights, we are very sorry for that.
