### ISSUE TITLE
`pip install u8darts` tries to install prophet

### ISSUE THREAD

**Issue by TueLindhart** [unit8co/darts#1728]
**Describe the bug**
When using `pip install u8darts`,  it also tries to install prophet even though the documentation  says it will not install prophet. Installation fails when it tries to install prophet and I would therefore like to avoid installing it as I dont need it. 

**To Reproduce**
Run `pip install u8darts`

**Expected behavior**
Expected it does not try to install prophet

**System (please complete the following information):**
 - Python version:  3.9.11
 - darts version 0.24.0

**Additional context**
I have a a MacOS with M2 chip running on MacOS 13.2.1.

**Comment by Coolnesss** [comment]
+1. Same applies to `u8darts[torch]`

**Comment by dennisbader** [comment]
You are right, we included prophet back to the core requirements a while ago as they fixed many of the previous installation issues.
We currently have a discussion/PR about this [here](https://github.com/unit8co/darts/pull/1589) with some users explaining how they got it to work on M1/M2.

**Comment by madtoinou** [comment]
I just checked locally, `darts`, `u8darts` and `u8darts[torch]` do not install `prophet` anymore.

Closing this for now, @Coolnesss & @TueLindhart feel free to reopen if the problem persists on your side.
