### ISSUE TITLE
[BUG] TCN Model and Optuna

### ISSUE THREAD

**Issue by ale-dg** [unit8co/darts#1731]
**Describe the bug**
While following the tutorial for [Hyper-parameters Optimization for Electricity Load Forecasting](https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html) an error happens in the section [Using Optuna](https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html#Using-Optuna). After ending the epoch0, it sends this error: AttributeError: 'TCNModel' object has no attribute '_model_call'

**To Reproduce**
Follow the tutorial mentioned above

**Expected behavior**
It should have run normally, according to the tutorial

**System (please complete the following information):**
 - Python version: 3.10.9
 - darts version 0.24.0
 - Optuna version 3.1.1

**Additional context**
Nothing additional

**Comment by ale-dg** [comment]
Sorry... forgot to add that I am running on a Mac M1, macOS 13.3.1

Thanks!

Best

**Comment by dennisbader** [comment]
Hi @ale-dg , I tried reproducing your issue but for me it works fine.
It could be that your Darts installation got corrupted. Maybe try a fresh install in a new environment?

Also, when you get it to work, you will have to use the PyTorchLightningPruningCallback implementation from [here](https://github.com/optuna/optuna-examples/issues/166#issuecomment-1403112861) (optuna currently doesn't support support higher PyTorch-Lightning>=1.8)

**Comment by ale-dg** [comment]
Hi @dennisbader 

Sorry for the delay in my answer, my computer was in the hospital. It worked as you mentioned (new environment + pruning callback from the link). 

Just a quick info... the Jupyter version installed with pip darts includes an "old" version which doesn't let the dataset to load, hence I had to update the Jupyter package for it to work.

Thanks for the help! I am closing the issue now.

Best

**Comment by floriansiepe** [comment]
@ale-dg I am currently experiencing the same issue with the NBeats model. Would you mind to share your working notebook so I can verify, if this is working on my machine?

**Comment by ale-dg** [comment]
> @ale-dg I am currently experiencing the same issue with the NBeats model. Would you mind to share your working notebook so I can verify, if this is working on my machine?

Hi, 

I have followed this tutorial https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html, exactly as it is there. Have you tried it or do you still have an issue? If the second, let me know and I can share my notebook through GitHub. 

Best

**Comment by floriansiepe** [comment]
> > @ale-dg I am currently experiencing the same issue with the NBeats model. Would you mind to share your working notebook so I can verify, if this is working on my machine?
> 
> Hi,
> 
> I have followed this tutorial https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html, exactly as it is there. Have you tried it or do you still have an issue? If the second, let me know and I can share my notebook through GitHub.
> 
> Best

Hi, thanks for the quick response. I'm trying now the latest version of the notebook from the repo (https://github.com/unit8co/darts/blob/master/examples/17-hyperparameter-optimization.ipynb) but it takes some time to run on the M1. Keep you updated!

**Comment by ale-dg** [comment]
I have those versions as well... I guess the issue is with the implementation of the pruner from PyTorchLightningPruningCallback. Did you use the link mentioned above by dennisbader? Otherwise, I leave you below the code of how the pruner should be implemented:

`
from pytorch_lightning import LightningModule
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import Callback

class PyTorchLightningPruningCallback(Callback):
    """PyTorch Lightning callback to prune unpromising trials.
    See `the example <https://github.com/optuna/optuna-examples/blob/
    main/pytorch/pytorch_lightning_simple.py>`__
    if you want to add a pruning callback which observes accuracy.
    Args:
        trial:
            A :class:`~optuna.trial.Trial` corresponding to the current evaluation of the
            objective function.
        monitor:
            An evaluation metric for pruning, e.g., ``val_loss`` or
            ``val_acc``. The metrics are obtained from the returned dictionaries from e.g.
            ``pytorch_lightning.LightningModule.training_step`` or
            ``pytorch_lightning.LightningModule.validation_epoch_end`` and the names thus depend on
            how this dictionary is formatted.
    """

    def __init__(self, trial: optuna.trial.Trial, monitor: str) -> None:
        super().__init__()

        self._trial = trial
        self.monitor = monitor

    def on_validation_end(self, trainer: Trainer, pl_module: LightningModule) -> None:
        # When the trainer calls `on_validation_end` for sanity check,
        # do not call `trial.report` to avoid calling `trial.report` multiple times
        # at epoch 0. The related page is
        # https://github.com/PyTorchLightning/pytorch-lightning/issues/1391.
        if trainer.sanity_checking:
            return

        epoch = pl_module.current_epoch

        current_score = trainer.callback_metrics.get(self.monitor)
        if current_score is None:
            message = (
                "The metric '{}' is not in the evaluation logs for pruning. "
                "Please make sure you set the correct metric name.".format(self.monitor)
            )
            warnings.warn(message)
            return

        self._trial.report(current_score, step=epoch)
        if self._trial.should_prune():
            message = "Trial was pruned at epoch {}.".format(epoch)
            raise optuna.TrialPruned(message)
`

Best,

**Comment by ale-dg** [comment]
from pytorch_lightning import LightningModule
      from pytorch_lightning import Trainer
      from pytorch_lightning.callbacks import Callback
      
      class PyTorchLightningPruningCallback(Callback):
          """PyTorch Lightning callback to prune unpromising trials.
          See `the example <https://github.com/optuna/optuna-examples/blob/
          main/pytorch/pytorch_lightning_simple.py>`__
          if you want to add a pruning callback which observes accuracy.
          Args:
              trial:
                  A :class:`~optuna.trial.Trial` corresponding to the current evaluation of the
                  objective function.
              monitor:
                  An evaluation metric for pruning, e.g., ``val_loss`` or
                  ``val_acc``. The metrics are obtained from the returned dictionaries from e.g.
                  ``pytorch_lightning.LightningModule.training_step`` or
                  ``pytorch_lightning.LightningModule.validation_epoch_end`` and the names thus depend on
                  how this dictionary is formatted.
          """
      
          def __init__(self, trial: optuna.trial.Trial, monitor: str) -> None:
              super().__init__()
      
              self._trial = trial
              self.monitor = monitor
      
          def on_validation_end(self, trainer: Trainer, pl_module: LightningModule) -> None:
              # When the trainer calls `on_validation_end` for sanity check,
              # do not call `trial.report` to avoid calling `trial.report` multiple times
              # at epoch 0. The related page is
              # https://github.com/PyTorchLightning/pytorch-lightning/issues/1391.
              if trainer.sanity_checking:
                  return
      
              epoch = pl_module.current_epoch
      
              current_score = trainer.callback_metrics.get(self.monitor)
              if current_score is None:
                  message = (
                      "The metric '{}' is not in the evaluation logs for pruning. "
                      "Please make sure you set the correct metric name.".format(self.monitor)
                  )
                  warnings.warn(message)
                  return
      
              self._trial.report(current_score, step=epoch)
              if self._trial.should_prune():
                  message = "Trial was pruned at epoch {}.".format(epoch)
                  raise optuna.TrialPruned(message)



There... I guess it's easier to copy it this way 😅

**Comment by floriansiepe** [comment]
Seems to work now. Thanks a lot!

**Comment by pfk-beta** [comment]
Hello,
I have similar issue with TFT model and optuna. I have pytorch-lightning==2.0.6 and torch==1.12.1. I have used callback which you mentioned as pl_trainer_kwargs' callback. But I'm still getting the same error.
