### ISSUE TITLE
How is get_historical_forecastable_time_index end date computed?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#1734]
Why is the end date of the _get_historical_forecastable_time_index = series.end_time() + 1 as per the screenshot below:
![image](https://user-images.githubusercontent.com/59031005/234577466-d92ea911-2a67-4916-a6ae-d35b08ad54ce.png)

I tried an example as per below:
![image](https://user-images.githubusercontent.com/59031005/234577716-c9d948f8-c6c0-44ed-a33a-f0cff2babfed.png)

What I don't understand is why 11/1/2000 is included in both the training set for is_training=True and is_training=False when the training set only goes from 1/1/2000 to 10/1/2000.

**Comment by dennisbader** [comment]
`get_historical_forecastable_time_index` gives all possible **first prediction points** for which we have the required input (either for training or prediction). This is why we call it "forecastable". 
It doesn't mean that we cannot predict further into the future, e.g. when using forecasting_horizon > 1. The last index just refers to the first prediction point in the last possible `predict()` call.

The input of the target series ends one time step before the forecastable time index (ignoring the target lags for regression models). 

Now in `get_historical_forecastable_time_index`, we first compute all possible forecastable time  steps only considering the target series (ignoring at this point other parameters such as `overlap_end`, `start`, ...)
Therefore, the last forecastable time index (according to definition above) is one time step after the end of the target series. 

Later on we also include the past/future covariates and the rest of the historical_forecasts parameters.
