### ISSUE TITLE
The speed of the predict and historical_forecasts functions

### ISSUE THREAD

**Issue by linbingkong** [unit8co/darts#1736]
The running time of the predict and historical_forecasts functions is much longer than the training time. I would like to ask if this is normal

**Comment by linbingkong** [comment]
fit time：1m19.7s
predict time:20m+

**Comment by dennisbader** [comment]
Hi @linbingkong , adding a reproducible example always helps to better answer to issues.
`predict()` vs. `fit()` should not be longer. `historical_forecasts()` (with retrain=True) vs. `fit()` is expected to take much longer as it goes through multiple fit/predict iterations.
You can find the documentation [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.linear_regression_model.html#darts.models.forecasting.linear_regression_model.LinearRegressionModel.historical_forecasts).

We are also working on optimizing historical_forecasts (if the parameters and model allow it) as explained in [this issue](https://github.com/unit8co/darts/issues/1703#issuecomment-1505126318).

**Comment by linbingkong** [comment]
@dennisbader 
thank you for your reply. I implemented it according to the Nbeats_model.ipynb,I change the historical_forecasts function into 'pred_series = model_nbeats.predict(7)  display_forecast(pred_series, series, "7 day", start_date=pd.Timestamp("20170901"))',the model fit spend 39.2s ,but predict spend 7m+

**Comment by linbingkong** [comment]
@dennisbader Sorry .It's the compiler's problem, it's very slow when I use vscode, but pycharm is normal.Thank you
