### ISSUE TITLE
ValueError: Model `Croston` only supports univariate TimeSeries instances

### ISSUE THREAD

**Issue by NamrataRade** [unit8co/darts#1737]
**Describe the bug**
getting ValueError: Model `Croston` only supports univariate TimeSeries instances - this error while fitting the Croston model

hier_columns = ['area_id','lvl1','lvl2','lvl3','lvl4','lvl5','lvl6']
y_val = 'y' #This column has sales value
time_col= 'ds'

train_ts = TimeSeries.from_group_dataframe(train_df,group_cols = hier_columns , time_col = time_col, value_cols= y_val) 
valid_ts = TimeSeries.from_group_dataframe(valid_df, group_cols = hier_columns , time_col = time_col, value_cols= y_val)
train_ts_ = concatenate(train_ts, axis=1)
valid_ts_ = concatenate(valid_ts, axis=1)
model= Croston()
model.fit(train_ts_)

**Expected behavior**
Want forecasted values for the input

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.14.0]

**Additional context**

**Comment by dennisbader** [comment]
Croston is a univariate forecasting model. You can find which models support multivariate forecasting in our documentation [here](https://unit8co.github.io/darts/#forecasting-models).

**Comment by NamrataRade** [comment]
I am passing univariate data but model is considering it as a multivariate. I need forecast only for y i.e sales value

**Comment by dennisbader** [comment]
`from_group_dataframe()` gives you a list of time series groups based on `group_cols`.
When you concatenate the list, you create a multivariate time series -> the model fails.
