### ISSUE TITLE
Documentation missing the csv file

### ISSUE THREAD

**Issue by ravi160822** [unit8co/darts#1740]
as a new user I would like to go to the documentation, copy and run the code, but there is this csv which I don't have.
please include examples which I can directly run.

https://unit8co.github.io/darts/README.html
```
df = pd.read_csv("AirPassengers.csv", delimiter=",")
```

I don't know what should be in this csv, what all columns should be in it.
please don't include examples like this in the documentation.

**Comment by dennisbader** [comment]
Hi @ravi160822 , you can directly load the air passengers series as described jn our Quickstart guide from [here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Read-data-and-build-a-TimeSeries).
