### ISSUE TITLE
Write user guide section and examples on Anomaly Detection

### ISSUE THREAD

**Issue by TamerAbdelmigid** [unit8co/darts#1750]
First of all, truly thank you for such a remarkable library.

I know you are busy with bug fixes and implementing awesome new features, but I wish if you also include a user guide section and example with every new release ensuring the library documentation are up to date and teaching the users how to harness its full potential. I hope next you include a user guide and examples on Anomaly Detection module.

Thanks again and best of luck.

**Comment by madtoinou** [comment]
Hi,

This is currently under work in the PR #1518, which will hopefully be wrapped up and merged in the upcoming weeks. You're indeed right, the documentation should be updated as the features are released, we'll do our best for the upcoming ones.

In the meantime, you could rely on the [notebook](https://github.com/unit8co/darts/blob/example/anomaly_detection_example/examples/XX-anomaly-detection.ipynb) in the PR or read the [article](https://unit8.com/resources/anomaly-detection-in-healthcare-data-with-darts/) about anomaly detection in healthcare that was published on Unit8 website.

Sorry for the wait!

**Comment by TamerAbdelmigid** [comment]
Thanks a lot for you prompt response and effort in this PR.
