### ISSUE TITLE
RuntimeError: No precision set in model.fit()

### ISSUE THREAD

**Issue by ziyit** [unit8co/darts#1752]
**Describe the bug**
"RuntimeError: No precision set" error observed (during model.fit(series)) while replicating the N-BEATS code from example (https://github.com/unit8co/darts/blob/master/examples/07-NBEATS-examples.ipynb).

**To Reproduce**
Please follow example located at https://github.com/unit8co/darts/blob/master/examples/07-NBEATS-examples.ipynb.

**Expected behavior**
model.fit() function allows single or multiple series fitting.

**System (please complete the following information):**
 - Python version: 3.7
 - darts version: 0.24.0

**Additional context**

**Comment by madtoinou** [comment]
Hi,

It' probably a duplicate of #1718; the solution is to upgrade PyTorchLightning to a more recent version (2.0 or the version just before). Let me know if it works for you

**Comment by ziyit** [comment]
Thank you for the feedback. Kindly refer to #1718 per @madtoinou suggestion for solution, close this issue for now.
