### ISSUE TITLE
darts.models import LinearRegressionModel

### ISSUE THREAD

**Issue by weibinxu86** [unit8co/darts#1769]
**Describe the bug**
When I ran the above script or import any model, it gave me this error

from darts.models import LinearRegressionModel

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

It worked all fine before even yesterday

**System (please complete the following information):**
 - Python version: 3.10.8
 - darts version 0.24.0

**Comment by peronopuedo** [comment]
It seems like an issue with [Prophet](https://github.com/facebook/prophet/issues/2432), which itself is inherited from an issue with the [python-holidays package](https://github.com/dr-prodigy/python-holidays/issues/1188). I'm not sure if other models are affected by this directly, but I've noticed I can't import ANY models from darts as a result.

**Comment by weibinxu86** [comment]
> It seems like an issue with [Prophet](https://github.com/facebook/prophet/issues/2432), which itself is inherited from an issue with the [python-holidays package](https://github.com/dr-prodigy/python-holidays/issues/1188). I'm not sure if other models are affected by this directly, but I've noticed I can't import ANY models from darts as a result.

Thanks. Have you found a solution to it?

**Comment by dennisbader** [comment]
Yes, you can install holidays==0.24.0 then it should work.

**Comment by weibinxu86** [comment]
> Yes, you can install holidays==0.24.0 then it should work.

Thank you so much! It now works for me!

**Comment by erosinnocenti** [comment]
Thanks! Same here. Downgraded to 0.24.0 and now it's working.
