### ISSUE TITLE
[BUG] Cannot predict from loaded model

### ISSUE THREAD

**Issue by aruasouza** [unit8co/darts#1773]
**Describe the bug**
When I call model.predict using past covariates i receive the following error:
AttributeError: 'BlockRNNModel' object has no attribute '_uses_static_covariates'. Did you mean: 'uses_static_covariates'?

**To Reproduce**
model = BlockRNNModel.load('model.pt')
prediction = model.predict(n = steps,series = main_data,past_covariates = extra_data)

**System (please complete the following information):**
 - Python version: 3.11
 - darts version 0.24.0

**Additional context**
This error is from the latest version only. I was able to fix the error by swiching to the previous version.

**Comment by dennisbader** [comment]
Yes, this comes from saving the model in an older darts version and loading it now in v0.24.0.
The saving/laoding got a major overhaul in v0.24.0 and is unfortunately not backwards/forwards-compatible.

There might be a possibility to retrieve it though (although I haven't tested this):

From darts==0.24.0 (the new version)
```
import copy

model = BlockRNNModel.load('model.pt')

# save a copy of the model in darts24 (this might fail though)
model.save("model_copy.pt")

# create a fresh darts24 model using the same parameters from loaded model
new_model = BlockRNNModel(**copy.deepcopy(model.model_params))
# load only the weights from the model
new_model.load_weights("model_copy.pt")
```

**Comment by madtoinou** [comment]
Closing for now, @aruasouza feel free to reopen the issue if the problem persists.
