### ISSUE TITLE
Add support for pre-trained models in EnsembleModel (first step)

### ISSUE THREAD

**Issue by mg10011** [unit8co/darts#1775]
- Do you guys have any documentation (in terms of papers) as to how this model works?
- If we save this model at a checkpoint, are the all of the individual components of this model also saved or do we have to save those separately?  IOW, how do we load up and call this model from another program?

**Comment by dennisbader** [comment]
Hi @mg10011, and thanks for writing.
- you can find an explanation [here](https://github.com/unit8co/darts/issues/1600#issuecomment-1453355230) and in the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.regression_ensemble_model.html#darts.models.forecasting.regression_ensemble_model.RegressionEnsembleModel).
- yes, it saves/loads all models. Use the `save()`/`load()` API from [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.regression_ensemble_model.html#darts.models.forecasting.regression_ensemble_model.RegressionEnsembleModel.save).

**Comment by mg10011** [comment]
Thanks for your response.  One follow up question:

Suppose I have 3 models in my ensemble.  If model 1 and model 2 have already been fitted, but model 3 has not been fitten.  If I then call `ensemble_model.fit()`, will the ensemble model **first** fit model 3 and then stack and fit the ensemble, or will it go back and fit all 3 models first?  IOW, how can I tell the ensemble to use an existing forecasting model in its ensemble **without** re-fitting it?

**Comment by asadabbas09** [comment]
Similar question: I have an XGBoost model and a TFT model already fitted and I want to make the ensemble. 

Do I need to refit the already-trained models? Or can I use the output predictions of the fitted models to create the ensemble without retraining?

**Comment by dennisbader** [comment]
Currently yes, there is no way around refitting them all.
We could add support for pre-trained models. 
To avoid data leakage we would support the following as a first step:
- to bypass EnsembleModel fitting all models, all of the models must to be of type `GlobalForecastingModel` (`RegressionModel` and/or `TorchForecastingModel`) and must be trained before.
- otherwise, all of the models will be fit/trained by the ensemble model
