### ISSUE TITLE
Several future covariates with different future lags known for each

### ISSUE THREAD

**Issue by LucasPzt** [unit8co/darts#1777]
Hi, 

I'm trying to implement univariates forecasting. Each of my univariate time serie target has several past and future covariates. The future covariates I'm working with don't all have all the same known future lags (I'm working at monthly frequency, some are known 1 months in the future, others 2 or 3 and so on...). Maybe I'm misunderstanding the doc, but it seems we are restricted for only one choice for the known number of lags for all my future covariates. Is it the case ?

Thanks.

**Comment by madtoinou** [comment]
Hi @LucasPzt,

Darts' models use indeed use the same lags values for all the timeseries passed at training and inference time.

You could either try to resample your past/future covariates so that they share the same frequency or train one model per target.
