### ISSUE TITLE
Accept Prophet with `growth='logistic'`

### ISSUE THREAD

**Issue by felipedram** [unit8co/darts#178]
**Proplem**
To use Prophet with `growth='logistic'`, the dataframe provided must have a column named 'cap'.

**Describe proposed solution**
Accept 'cap' and 'floor' as arrays provided as parametes on the model initialization.

**Describe potential alternatives**
Do not consider TimeSeries to be always multivariate and rename the columns in order.

**Comment by TheMP** [comment]
Hi @felipedram, thanks for raising the issue - it's actually part of the bigger design thing to tackle mentioned in #180, we will try to find a solution that works for everyone.

**Comment by LeoTafti** [comment]
Hi @felipedram , sorry for the delay.

This is a good point. Unfortunately I do not see an easy and clean way of fixing this at the moment.

- Adding `cap` and `floor` parameters that would only be used when `growth='logistic'` is also given doesn't seem very clean to me
- `fit()` in `Prophet` calls `UnivariateForecastingModel.fit()`, which itself check `series._assert_univariate()`. I don't think we can prevent this from happening without either treating `growth='logistic'` as a special case or making `Prophet` a `MultivariateForecastingModel` (but this isn't an easy task either)

I'm not sure that accepting `growth='logistic'` justifies the tradeoffs listed above, but if you have another suggestion I'd love to hear it.

**Comment by madtoinou** [comment]
Implemented by #1419.
