### ISSUE TITLE
[Question] About construct covariates for 3-D to multivariate stochastic series

### ISSUE THREAD

**Issue by haison19952013** [unit8co/darts#1786]
## Problem Description
- Suppose I have 2 datasets: `dataset1` and `dataset2`. Both of them contain:
     + Number of timesteps: 100
     + Measurements of 4 velocities in different directions:  `u, v, p ,r`
     + 2 control inputs (which can be known in the future): rudder angle (`dr`), elevator angle (`de`)

- The goal is to train a forecaster using both `dataset1` and `dataset2`. This trained forecaster will predict the four velocities based on past values of `u, v, p, r` and `dr, de`, as well as future values of `dr, de`

- The data is structured as follows:
![image](https://github.com/unit8co/darts/assets/56432608/894ba961-df1c-4b1b-83ed-50a832e1767e)

## Questions
1. I am unsure whether constructing the ready-to-train dataset from the two datasets as follows is correct:
   - For `u, v, w, p, q, r` (considered as target time series), create a three-dimensional array with the size of **timestep $\times$ components $\times$ samples**. In my case, the array size would be: **100 timesteps $\times$ 4 velocities $\times$ 2 samples**
    - For `dr, de` (considered as future/past covariates), create a three-dimensional array with the size of **timestep  $\times$ components $\times$ samples**. In my case, the array size would be: **100 timesteps $\times$ 2 control inputs $\times$ 2 samples**

2. Are there any previous works similar to my problem that I can refer to for guidance?

**Comment by madtoinou** [comment]
Hi @haison19952013,

`TimeSeries` containing several samples are called `probabilistic` in darts, and I don't think that they are meant to be used to train models. The description of your problem would correspond to "multi-timeseries training" in darts terminology ([documentation](https://unit8co.github.io/darts/userguide/forecasting_overview.html#handling-multiple-series) and [toy example](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Machine-learning-and-global-models)).

Since your data seems to be stored in `pd.DataFrame`, you could probably do something like:

```python
train_columns = ["u", "v", "p", "r"]
ts_train1 = TimeSeries.from_dataframe(dataset1[train_columns])
ts_train2 = TimeSeries.from_dataframe(dataset2[train_columns])

fut_covs_columns = ["dr", "de"]
fut_covs1 = TimeSeries.from_dataframe(dataset1[fut_covs_columns])
fut_covs2 = TimeSeries.from_dataframe(dataset2[fut_covs_columns])

# see the table in the README to see which models are global
model = GlobalForecastingModelClass(...)
model.fit(series=[ts_train1, ts_train2], future_covariates=[fut_covs1, fut_covs2])
```

Let me know if it works for you

**Comment by haison19952013** [comment]
> Hi @haison19952013,
> 
> `TimeSeries` containing several samples are called `probabilistic` in darts, and I don't think that they are meant to be used to train models. The description of your problem would correspond to "multi-timeseries training" in darts terminology ([documentation](https://unit8co.github.io/darts/userguide/forecasting_overview.html#handling-multiple-series) and [toy example](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Machine-learning-and-global-models)). Since you want to predict several values as once (u, v, p, r), your problem is also multivariate and it supported out of the box in darts.
> 
> Since your data seems to be stored in `pd.DataFrame`, you could probably do something like:
> 
> ```python
> train_columns = ["u", "v", "p", "r"]
> ts_train1 = TimeSeries.from_dataframe(dataset1[train_columns])
> ts_train2 = TimeSeries.from_dataframe(dataset2[train_columns])
> 
> fut_covs_columns = ["dr", "de"]
> fut_covs1 = TimeSeries.from_dataframe(dataset1[fut_covs_columns])
> fut_covs2 = TimeSeries.from_dataframe(dataset2[fut_covs_columns])
> 
> # see the table in the README to see which models are global
> model = GlobalForecastingModelClass(...)
> model.fit(series=[ts_train1, ts_train2], future_covariates=[fut_covs1, fut_covs2])
> ```
> 
> Let me know if it works for you

Thanks for your prompt reply. In reference to the [multi-series tutorial](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-on-Both-Air-Traffic-and-Milk-Series), I understand that the Air Traffic and Milk Series are distinct entities. However, in my problem, `dataset1` and `dataset2` represent the same underlying phenomenon (let's assume data from the same machine but at different time periods and with different control inputs). Given this, would it be reasonable to frame my problem in a similar manner to the [multi-series tutorial](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html#Training-on-Both-Air-Traffic-and-Milk-Series)?

**Comment by madtoinou** [comment]
Yep, it's even better: you are doing meta-learning on two processes that are highly similar. This is what a store owner with several product would do as well; product might have different release dates (hence non-overlapping time indexes), sales period, location but overall correspond to similar phenomenon.

If your two datasets have a lot of overlapping time index, you could eventually use the multivariate approach (concatenate the two ts series into one with two components for each variable, as you described in your original message) but it means that the features from `dataset1` might influence the predictions for `dataset2` (and vice-versa) which sounds awfully like data leakage (and not applicable to your case since its the same machine, not two machines that can communicate).

**Comment by haison19952013** [comment]
- Sorry, I'm still not clear. My purpose to put  `dataset1` and  `dataset2` together is to help tune the forecaster simultaneously because they come from the same machine. Therefore, they will have a very high correlation. However, the multi-series model in `Darts` seems to be designed to work on (maybe) totally separate series such as the temperatures of the 2 different machines. 
- One more thing, in the prediction phase of the multi-series model, I have to specify which series I wish to make the prediction on.  If that, I will have to select between the series of `dataset1` or `dataset2`. This is weird in my case.

**Comment by madtoinou** [comment]
Multi-series can have several use, from meta-learning (several ts describing different phenomenon) to training with several ts with non-overlapping time index (and probably a lot of other use cases). I don't think that the correlation between your 2 datasets is a problem but you could try to see if training with one or the two series is improving the results (keeping the end of each ts as validation for example, or just the end of `dataset2`). 

I am not sure to understand why it's weird; they don't have the same timestamps (and might not be at the same stage of the phenomenon) so the model needs to know which values of "u", "v", "p" and "r" it can rely on to generate the forecast.

**Comment by haison19952013** [comment]
- I really appreciate your response to my question. I think I have understood the idea. The steps to deal with my problem are as below: 
   + Step 1: Train the forecaster by using the two series `data1' and `data2'. 
   + Step 2: To make a forecast on a totally new series (let's say, `data3`), extract the past data of `u,v,p,r` and `dr, de` (up to the designed lags) PLUS the future data of `dr, de` (as long as I want) as the input to the forecaster.

- Could you plz tell me if the above steps are correct? Thank you!

**Comment by madtoinou** [comment]
The steps seem correct, a few small comments:
- you should not have to worry about the lags as darts will slice the ts appropriately if it's too long and complain if the new series `data3` is too short to run inference
- `predict(n)` will predict the `n` timestamps after the last time index in `data3`
-  the ts containing the values of `dr` and `de` need to be passed as `future_covariates`, and darts will perform the slicing for you (will complain if it's too short for the desired horizon forecast)

**Comment by haison19952013** [comment]
I appreciate your valuable advice. I will close the issue now and proceed to work on some toy problems using my data. If any issues arise during the process, I will provide further updates. Once again, I want to express my gratitude to you and your team for developing such an outstanding library.
