### ISSUE TITLE
[BUG] Training does not start

### ISSUE THREAD

**Issue by hassanuiuc** [unit8co/darts#1796]
Hello!

**Describe the bug**
I am a beginner in using darts. I was trying forecasting using this [tutorial](https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html
):
The training does not start, not even for one epoch, in the jupyternotebook.

**To Reproduce**

Same as tutorial:
```
series_air = AirPassengersDataset().load()
series_milk = MonthlyMilkDataset().load()

series_air.plot(label="Number of air passengers")
series_milk.plot(label="Pounds of milk produced per cow")
plt.legend();
scaler_air, scaler_milk = Scaler(), Scaler()
series_air_scaled = scaler_air.fit_transform(series_air)
series_milk_scaled = scaler_milk.fit_transform(series_milk)

series_air_scaled.plot(label="air")
series_milk_scaled.plot(label="milk")
plt.legend();
train_air, val_air = series_air_scaled[:-36], series_air_scaled[-36:]
train_milk, val_milk = series_milk_scaled[:-36], series_milk_scaled[-36:]
model_air = NBEATSModel(
    input_chunk_length=24, output_chunk_length=12, n_epochs=2, random_state=0
)
model_air.fit(train_air, verbose=True);
```
**Expected behavior**
training is stuck, shows no progress

**System :**
 - Python version: 3.9.16
 - darts version : 0.24.0

**Additional context**
A similar [issue](https://github.com/unit8co/darts/issues/830) raised before suggested:` jupyter nbextension enable --py widgetsnbextension`
I ran this in the darts conda env but the issue persists.

Any help appreciated!

**Comment by madtoinou** [comment]
Hi @hassanuiuc,

The mentioned issue suggest to uninstall ipywidgets, does the problem persist after removing it from your conda darts environment?

**Comment by hassanuiuc** [comment]
Uninstalling did not help and somehow caused a few other packages to downgrade in conda. But the issue disappeared once I reinstalled everything in a fresh environment.

Thanks for the suggestion!
