### ISSUE TITLE
How to specify exogenous variables for TCN or Torch

### ISSUE THREAD

**Issue by arpanseth** [unit8co/darts#180]
Looking at the API for multivariate models, I am not sure how I can provide exogenous time series (input values known in the future) to the predict function. 
Please advise.

**Comment by pennfranc** [comment]
Unfortunately this functionality is not supported at the moment. What you can do is use the `StandardRegressionModel` class to try to predict the target time series `train_target` in combination with multiple model forecasts and exogenous variables as `train_features`.
Adding support for exogenous variables for forecasting is definitely on our radar, but not available right now.

**Comment by hrzn** [comment]
There also another way, which consists of shifting your time series of known future values, and bundle it with your other features as a multi-variate time series. For instance, say that you know the weather temperature 7 days in advance, you can create (up to) 7 new time series, which for time step t would represent the temperature at t+1, t+2, ... t+7.
The "interpretation" of such a new time series at time step t should be interpreted as "the estimate known at time t of the temperature at time t+1".
