### ISSUE TITLE
[BUG] loaded trained model can not predict() without fit()

### ISSUE THREAD

**Issue by AmyWorkspace** [unit8co/darts#1804]
**Describe the bug**
I train a TCN model, and save it. Then I load it to predict some series. But I get the following error:
ValueError: The model must be fit before calling predict(). For global models, if predict() is called without specifying a series, the model must have been fit on a single training series.

**To Reproduce**
model = TCNModel(
    input_chunk_length=2016,
    output_chunk_length=288,
    n_epochs=10,
    dropout=0.1,
    dilation_base=2,
    weight_norm=True,
    kernel_size=5,
    num_filters=3,
    random_state=0,
)

model.fit(
     series=train,
     past_covariates=train_month,
     val_series=val,
     val_past_covariates=val_month,
     verbose=True,
)

model.save(file_path)

model.load(file_path)
pred = model.predict(series=train, n=288, num_samples=100)

**Expected behavior**
It should predict based on the series I provided. 

**System (please complete the following information):**
 - Python version: Python 3.10.11
 - darts version 0.24.0

**Additional context**

**Comment by dennisbader** [comment]
Hi @AmyWorkspace, I tried to reproduce your issue, but it runs fine on my side.
Could it be that you're loading a model that was saved in an earlier darts version?

**Comment by AmyWorkspace** [comment]
It is trained and saved in the same darts version.
I just tried to add load_weights() and it seems work well now.

model.load(file_path)
model.load_weights(file_path)

**Comment by dennisbader** [comment]
Ah sorry, for loading the model manually you should use:
```
model_loaded = TCNModel.load(file_path)
```

**Comment by haison19952013** [comment]
@AmyWorkspace: Did your code work well with a separate .py without `model.fit()` ?, I used TFT model and met the same problem when I tried to use `model.load()` in a separate .py without `model.fit()`.

**Comment by dennisbader** [comment]
@haison19952013 again, `model.load()` is not the way to load a model. Use the example from my response above.

**Comment by haison19952013** [comment]
@dennisbader I got the idea..thanks for your support..It works for me..
