### ISSUE TITLE
Accessing the model weights in Darts TFT Model

### ISSUE THREAD

**Issue by sargamg99** [unit8co/darts#1809]
I am using the Darts TFT Model with the inbuilt Traffic Dataset. I am not able to access the weights of the trained TFT model? I have tried using model.load_weights() but it is repeatedly giving me a value error "ValueError: The values of the hyper parameter likelihood should be identical between the instantiated model (<darts.utils.likelihood_models.QuantileRegression object at 0x1553d1d571c0>) and the loaded checkpoint (<darts.utils.likelihood_models.QuantileRegression object at 0x15533c4df550>). Please adjust the model accordingly."
How can I get the weights of the trained TFTModel?

**Comment by dennisbader** [comment]
This is a bug that we fixed in tge current master and will be released in the version.

You should still be able to load the model with `TFTModel.load()`.
If you're interested in the weights/model parametets, they can be accessed after loading with `model.model.named_parameters()`

**Comment by sargamg99** [comment]
Thank you so much. It works.
