### ISSUE TITLE
XGBoost fitted model should be able to output 'get_score()' to determine feature importance

### ISSUE THREAD

**Issue by mg10011** [unit8co/darts#1826]
**Is your feature request related to a current problem? Please describe.**
When running a time series forecasting model on many past covariates, it might be helpful in iteratively build the model by selecting covariates that are "more important".  In the original XGBoost library, there is a 'get_score()' method that gives a ranking of the importance of the features in the forecast.  It would be useful to have access to this. 

**Describe proposed solution**
Some additional code that calls the existing XGBoost method and prints it out or creates an attribute for 'XGBModel.fit()' that includes this data.

**Comment by madtoinou** [comment]
Hi @mg10011,

You can call `feature_importances_` to get the importance of the features as follow:

```python
model = XGBModel(lags=3)
model.fit(series=ts)
model.model.feature_importances_
```

**Comment by mg10011** [comment]
Your solution does not work.  It would be easy, otherwise.  I called my XGBModel by model['XGBoost'].  So, when I set the following:

`mod = models['XGBoost'].model`

and called

`mod.feature_importance_`

I got the following:

```
In [10]: mod.feature_importance_()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 mod.feature_importance_()

AttributeError: 'MultiOutputRegressor' object has no attribute 'feature_importance_'
```

**Comment by madtoinou** [comment]
Can you please share a reproducible example? The error suggests that you're using the model with either a multivariate timeseries or `output_chunk_length>1`.

If you do so, the model is wrapped in a `MultiOutputRegressor` and you need to do a little bit of unpacking:
```python
for i in range(len(model.model.estimators_)):
    print(model.model.estimators_[i].feature_importances_)
```

**Comment by mg10011** [comment]
This worked.  Thank you.
