### ISSUE TITLE
[New model] TimesNet

### ISSUE THREAD

**Issue by NQevxvEtg** [unit8co/darts#1827]
Apparently the new number one is here. 

https://github.com/thuml/TimesNet

**Comment by alexcolpitts96** [comment]
Interesting model. I will say the results are displayed in a way to make it look like their model is the best. I only compared ETTm2, but N-HiTS beats in MSE and MAE (see table 2). 

I believe some of the devs had talked about creating a table of all models in terms of accuracy metrics. It might be interesting to try and add computational performance as well (like their Table 11). Computational complexity analysis like in the N-HiTS paper is nice, but (un)fortunately we don't have infinitely long sequences. 🙃 

Model repo:
https://github.com/thuml/Time-Series-Library/tree/main/models

Might be interesting to ingest other models from here such as PatchTST.

**Comment by ohenepee** [comment]
Why was this issue closed?
