### ISSUE TITLE
Support float seasonal_periods in Prophet

### ISSUE THREAD

**Issue by gregorp90** [unit8co/darts#1828]
**Is your feature request related to a current problem? Please describe.**
I would like to add a custom seasonality to the Prophet model. For example, weekly data with yearly seasonality. This set up requires 52.18 periods. But Darts requires the `seasonal_periods` to be an integer and raises an exception if a float is provided, while base Prophet allows floats.

At the moment we can only use 52, which will shift the seasonality if we are forecasting over a longer period, which is wrong.

**Describe proposed solution**
Change the `seasonality_properties` dictionary in `_store_add_seasonality_call` in the [Prophet model](https://unit8co.github.io/darts/_modules/darts/models/forecasting/prophet_model.html) so that `seasonal_periods` can be a float.

**Comment by madtoinou** [comment]
Fixed by #1829.
