### ISSUE TITLE
Visualisation with plotly / plotly express

### ISSUE THREAD

**Issue by PitS99** [unit8co/darts#183]
Is there any way, how to do a visualisation of a forecast (and original data) with plotly or plotly express instead of matplotlib?

from darts.models import ExponentialSmoothing
train, val = series.split_before(pd.Timestamp('2020-05-01'))
model = ExponentialSmoothing()
model.fit(train)
prediction = model.predict(len(val))

Is there any way, how to store the forecast values to dataframe?

**Comment by pennfranc** [comment]
`prediction.pd_dataframe()` should give you the `pandas.DataFrame` instance you're looking for!

**Comment by PitS99** [comment]
Thank you so much. It works perfectly!
