### ISSUE TITLE
Can Darts work with inconsistent time frequency?

### ISSUE THREAD

**Issue by nogamosc** [unit8co/darts#1838]
I'm trying to use Darts in order to solve classification problem.
I have dataset with many patients (thousands) and for each patient I have many sequential tests (each test contains the same (and many) values such as blood pressure etc.).
Each test was performed in different time (can be any time). All patients have label as Sick or Not Sick.

I'm working for a long time now trying to understand how to convert my data to TimeSeries object correctly and use Darts to try to solve it.

According to this answer [here](https://github.com/unit8co/darts/issues/128#issuecomment-655421905) Darts doesn't support Time Series data with inconsistent frequencies, is this still the case? Because In my data there is not fix time for the tests of the patients.
I couldn't figure this out from the [doc](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#).

Can anyone help?

**Comment by nogamosc** [comment]
Thanks for the answer, I'll follow the track you mentioned for future works :)
Also, I think it may be nice to add this constraint to the docs. It may seem obvious but nowhere in the documents is it written that the ts must be with regular frequency.

**Comment by madtoinou** [comment]
It's written in documentation, in the comment at the top of  TimeSeries.py and the associated [documentation page](https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=timeseries#module-darts.timeseries): 

"_Have a well defined frequency (`date offset aliases <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases>` for ``DateTimeIndex``, and step size for ``RangeIndex``)_".

But I would agree that "well defined" does not directly mean "constant/consistent" frequency for everyone. Any suggesting of better wording?
