### ISSUE TITLE
Question: multivariate TimeSeries with multiple samples/day 

### ISSUE THREAD

**Issue by jmcrtp** [unit8co/darts#1839]
I’ve reviewed the documentation and examples and it is not clear if it is possible to provide input data with multiple daily samples and have the training only use input and output chunks from the same day?  I can work around it by providing a single day to train I suppose but I would like to use much more data.  

For example if I have 100 samples in a day and I would like to train using input_chunk_size 15, and output chunk_size 10 is it possible to train this way to instruct it to keep everything within the same day?

If not would it be reasonable to assume I could provide many sets of daily data and have it train on all of them sequentially in a loop?  

Thank you!

**Comment by madtoinou** [comment]
Hi @jmcrtp,

What do you mean by 100 samples in a day? Do you have 100 shops selling the same product? If it's the case, your problem can be considered either as a single multivariate series where each column correspond to a shop (they all share the same time index) or a "multi-series" where each shop corresponds to an univariate series (with potentially different time indexes).

With a multivariate ts and `input_chunk_size=15` with `output_chunk_length=10`, the model will consume the values from the 15 steps in the past to predict 10 values in the future of all the columns at once (they will interact with each other). 

In darts, "samples" are used in probabilistic forecasts, when the model is trained to predict the parameters of a distribution instead of the most likely value of the target in the future. I don't think that it corresponds to your situation.

Let me know if you need additional information

**Comment by FalcoAlitiq** [comment]
I guess it is meant that when I use `model.predict()` with let's say `n=300` and my `output_chunk_length=15`. I have my `series` (the past target) set to end at a specific point in time `'2021-12-29T00:00:00'`. Then +300h equals `2022-01-10T11:00:00`. My `past_covariates` and `future_covariates` are far enough into the future such that there is no problem at all. 

The result that I get is shaped `(time: 300, component: 1, sample: 1)` so I get only 1h predictions in 285 cases and the last one is the actual 15h prediction that I expected. 

To sum that up: I do not get the sequenced predicted target or better say: I do not know what is internally concatenated in the `predict` method that results in `times=300`. Shouldn't it be `(time: 300, component: 1, sample: 1, window=15)` where window denotes the index of the sequence (or "chunk" in darts vocabulary)?

**Comment by madtoinou** [comment]
`output_chunk_length` is the number of values predicted "at once" by the model, if `n>output_chunk_length`, the model will rely on its own predictions to perform the next `output_chunk_length` predictions. All the `output_chunk_length` are concatenated to obtain `n` predicted timestamps.

If you want a probabilistic forecast for 15 steps, with 300 samples at each index value, you need to use `n=15`, `num_samples=300`.

**Comment by FalcoAlitiq** [comment]
They thanks for the fast answer! Still I have the question in my mind which method is being used to concatenate the predictions. The model is trained to output `output_chunk_length` from last layer or we can define something less here which means that it is just cut off. Thus this is the first product to receive when running `predict_step` in lightning terms. So are like so many "`n=1`" prediction steps evaluated until `n=285` is reached and the those are concatenated? Or are the overlapping time-stamps in predictions, when they are created at one step overlapped by some statistic like a mean?

**Comment by madtoinou** [comment]
There are not overlapping predictions when using `predict()`, the "output_chunks" can be directly concatenated.

If you want to have overlapping predictions and aggregate them yourself, you could eventually use `historical_forecasts()` ([doc](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.linear_regression_model.html?highlight=historical#darts.models.forecasting.linear_regression_model.LinearRegressionModel.historical_forecasts)) with `last_points_only=False` but you won't be able to go beyond the series time index.

**Comment by FalcoAlitiq** [comment]
I just answered the question myself. There is a parameter in the prediction method that determines how to act in rolling predictions. I also now use `num_samples` and I am simply blown away of the power of the framework. Great work! 👏🎩

`roll_size (Optional[int]) – For self-consuming predictions, i.e. n > output_chunk_length, determines how many outputs of the model are fed back into it at every iteration of feeding the predicted target (and optionally future covariates) back into the model. If this parameter is not provided, it will be set output_chunk_length by default.
`
