### ISSUE TITLE
TimeSeries creates missing values that are not available in Original data

### ISSUE THREAD

**Issue by Kamal-Moha** [unit8co/darts#1854]
**Describe the bug**
TimeSeries creates missing values that are not available in original data. I'm using the darts TimeSeries so that I can use those series for forecasting. Here's how I'm creating the TimeSeries.
```
import pandas as pd
from darts import TimeSeries
import matplotlib.pyplot as plt
import datetime as dt
import yfinance as yf

company = 'AAPL'
start = dt.datetime(2018,1,1)
end =  dt.datetime(2020,12,2)
aapl = yf.download(company, start , end)

series = TimeSeries.from_series(aapl['Close'], freq='D')

series
```
When I check `series`, I find that it has missing values. I'm very sure the original data I used to create the TimeSeries doesn't have any missing values. I have checked for it with this code `aapl['Close'].isna().sum()`and its 0.

Well, I don't want my `series` to have missing value because it will mess up my modeling and my predictions.

I have also realized that darts `TimeSeries` creates duplicates and that's why missing values are being created.

**Expected behavior**
I want my series to have the exact values of `aapl['Close']`. I don't want missing value in my TimeSeries

**System (please complete the following information):**
 - Python version: [e.g. 3.10.12]
 - darts version [e.g. 0.24.0]

**Additional context**
I'm running this code on Google Colab with has the lastest version of python and darts

I have figured out that `darts.datasets` like `AirPassengersDataset().load()` doesn't have any missing values. So the question is how do you guys create the TimeSeries for these datasets. Share the template so that I can follow that.

**Note**
Please help because this has taken a lot of my time

**Comment by madtoinou** [comment]
Hi @Kamal-Moha,

After quick inspection of the dataset you're using, the time index frequency is not `"D"` (day) but `"B"` (business days). Since you provide `freq="D"`, darts created a time index with the weekends included and fill these dates with `NaN`.

```python
series = TimeSeries.from_series(aapl['Close'], freq='D')
pd.isna(series.values()).sum()
>>> 330
series = TimeSeries.from_series(aapl['Close'], freq='B')
pd.isna(series.values()).sum()
>>> 26
```
Since some dates are still missing after using the default business day, you will have to defined a custom one to add the holidays used by `yfinance`. You can find some instructions to do so [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-custombusinessdays))

**Comment by Kamal-Moha** [comment]
Thank you @madtoinou for the comment. 

I had initially tried to use `freq='B'`, but it also produced missing values as you also observed.
The the option of creating a custom business day is definitely the way to solve this and thanks for providing the link to further explore that.

**Comment by madtoinou** [comment]
Closing this for now, don't hesitate to reopen the issue if you still encounter problems on this topic
