### ISSUE TITLE
documentation typo in `TimeSeries.median`?

### ISSUE THREAD

**Issue by jjhbw** [unit8co/darts#1855]
I think the time axis is referred to as `axis=1` in the documentation of this function, while it should be `axis=0`, right? The components axis is already referred to as `axis=1`.
https://github.com/unit8co/darts/blob/8e93720e6277726089058cf4d039b97de0f57c34/darts/timeseries.py#L3978

**Comment by madtoinou** [comment]
Hi @jjhbw,

Thank you for spotting this typo in the documentation, `axis=1` indeed correpond to the components and the time index is on the `index=0`. Would you be interested in opening a PR to fix it?

**Comment by jjhbw** [comment]
Sure thing. Created https://github.com/unit8co/darts/pull/1856

**Comment by dennisbader** [comment]
Fixed with #1856
