### ISSUE TITLE
[BUG] RegressionModelWithCategoricalCovariates with categorical_future_covariates throws an error

### ISSUE THREAD

**Issue by msedluk** [unit8co/darts#1877]
I have included a simple example calling RegressionModelWithCategoricalCovariates.fit() with categorical_future_covariates and it later calls LinearRegression.fit() with the unexpected keyword argument 'categorical_feature'

    from darts.models.forecasting.regression_model import RegressionModelWithCategoricalCovariates
    from darts import TimeSeries

    past_targets_np = np.array( [ [ 0.1 ], [ 0.2 ], [ 0.3 ], [ 0.4 ], [ 0.5 ] ] )
    future_covariates_np = np.array( [ [ 1.0, 0.1 ], [ 2.0, 0.2 ], [ 1.0, 0.3 ], [ 2.0, 0.4 ], [ 3.0, 0.5 ], [ 3.0, 0.5 ], [ 3.0, 0.6 ] ] )

    past_targets = TimeSeries.from_values( past_targets_np )
    future_covariates = TimeSeries.from_values( future_covariates_np, columns=[ 'x_0', 'x_1' ] )

    low_level_model = RegressionModelWithCategoricalCovariates( lags=[ -1 ], lags_past_covariates=None, lags_future_covariates=[ -1 ], categorical_future_covariates=[ 'x_0' ] )

    low_level_model.fit( past_targets, future_covariates=future_covariates )

    # Line 418 in regression_model.py, kwargs is { 'categorical_feature': [1] }     TypeError: LinearRegression.fit()   got an unexpected keyword argument 'categorical_feature'

    # self.model.fit( training_samples, training_labels, **kwargs )

The data in this example is not very useful but the same error is present with real data.

I am using Python 3.11 with Darts 0.24.0

**Comment by alexcolpitts96** [comment]
Here is a tweaked version that fixes the issue. The problem is that you are calling a model constructor that isn't a top-level model. `RegressionModelWithCategoricalCovariates` is not something you call directly. If you check the `README.md` of the [documentation webpage](https://unit8co.github.io/darts/index.html) you will see a list of top level models that you can call.

In your case, all that needed to be done was change `RegressionModelWithCategoricalCovariates` to `RegressionModel`. This allows darts to do the heavy lifting.

```
import numpy as np

from darts import TimeSeries
from darts.models import RegressionModel

past_targets_np = np.array([[0.1], [0.2], [0.3], [0.4], [0.5]])
future_covariates_np = np.array(
    [[1.0, 0.1], [2.0, 0.2], [1.0, 0.3], [2.0, 0.4], [3.0, 0.5], [3.0, 0.5], [3.0, 0.6]]
)

past_targets = TimeSeries.from_values(past_targets_np)
future_covariates = TimeSeries.from_values(future_covariates_np, columns=["x_0", "x_1"])

low_level_model = RegressionModel(
    lags=[-1],
    lags_future_covariates=[-1],
)

low_level_model.fit(
    series=past_targets,
    future_covariates=future_covariates,
)

pred = low_level_model.predict(
    n=1,
)

```

**Comment by msedluk** [comment]
Thanks
