### ISSUE TITLE
[BUG] Error while importing forecasting model

### ISSUE THREAD

**Issue by Jonathan-87** [unit8co/darts#1882]
**Describe the bug**
When I try to import models from Darts like this :

from darts.models import NaiveSeasonal
from darts.models import KalmanForecaster
from darts.models import StatsForecastAutoCES
from darts.models import StatsForecastAutoETS

I get the folloing error : 

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

But it seems to work if I downgrade protobu like this : 

pip install protobuf==3.19.4

**System (please complete the following information):**
 - Python version: 3.9.5
 - Darts version 0.24.0
 - Databricks runtime 12.2 LTS for machine learning (https://docs.databricks.com/release-notes/runtime/12.2ml.html)

**Comment by madtoinou** [comment]
Hi @Jonathan-87,

Thank you for reporting this bug and sharing a fix.

My guess is that the protobuf release (with a breaking change) occurred in May whereas the last darts releases was in April. I hope that the next release (hopefully by the end of July) will solve this issue without having to pin the protobuf version.

**Comment by madtoinou** [comment]
As darts 0.25.0 was released today, this issue should be fixed.

I am going to close this, @Jonathan-87 please reopen it if the problem persists.
