### ISSUE TITLE
Two time series of different frequency

### ISSUE THREAD

**Issue by matteoarcangeli99** [unit8co/darts#1884]
Hello,
I'm using the TFT model; I have two series (target and covariates), each with a different frequency; the target series has a monthly frequency, whereas the covariates series has a daily frequency.
When I try to setup TFT model I got this error:

**The dataset contains past covariates whose time axis doesn't allow to obtain the input (or output) chunk relative to the target series.**

How can I fix it?

**Comment by dennisbader** [comment]
Your target and covariates series must have the same frequency. 
The only way to do this (from daily frequency to monthly frequency) is to aggregate your covariates on a monthly frequency in a preprocessing step.
