### ISSUE TITLE
Use a TPU on Colab

### ISSUE THREAD

**Issue by bonchae** [unit8co/darts#1886]
I'm trying to use a TPU available on Google Colab. According to the Darts [documentation](https://unit8co.github.io/darts/userguide/gpu_and_tpu_usage.html), I need to install the following first. It looks the codes below are outdated. Can anyone share the updated codes? Thanks.

```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl
!pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchtext==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html
!pip install pyyaml==5.4.1
```

**Comment by madtoinou** [comment]
Hi @bonchae,

Thank you for pointing this out. Can you please check if TPU are supported without additional installation?

**Comment by Kudisika** [comment]
> Hi @bonchae,
> 
> Thank you for pointing this out. Can you please check if TPU are supported without additional installation?

No its is not, I've tried it

**Comment by leoniewgnr** [comment]
@madtoinou I have the same problem, would greatly appreciate a solution!

**Comment by leoniewgnr** [comment]
So I tried several combinations, the closest working one was:
'''
# Uninstalling existing versions of PyTorch and TorchAudio to avoid conflicts
!pip uninstall -y torch torchvision torchaudio

# Installing PyTorch and TorchVision compatible with CUDA 11.7
!pip install torch==2.0.0+cu117 torchvision==0.15.1 -f https://download.pytorch.org/whl/torch_stable.html

# Installing compatible version of TorchAudio
!pip install torchaudio

# Installing PyTorch/XLA for TPU support
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl

# Restart the runtime after installation
import os
os.kill(os.getpid(), 9)
'''

But then I get this error when trying to run TFT model: 'ModuleNotFoundError: Module not found: 'torch_xla'. HINT: Try running `pip install -U torch_xla`' 

But just running this command also not works. Does anyone have ideas?

**Comment by leoniewgnr** [comment]
I found the solution!

1. Install this:
```
# Uninstall existing versions to avoid conflicts
!pip uninstall -y torch torchvision torchaudio torch_xla

!pip install cloud-tpu-client==0.10

# Install PyTorch compatible with CUDA 11.7
!pip install "torch==2.0.0+cu117" -f https://download.pytorch.org/whl/torch_stable.html

# Install TorchVision compatible with PyTorch
!pip install "torchvision==0.15.1" -f https://download.pytorch.org/whl/torch_stable.html

# Install PyTorch/XLA for TPU support (using the available compatible version)
!pip install https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl

# Restart the runtime to apply changes
import os
os.kill(os.getpid(), 9)
```

2. Convert your time series to float32
`ts = ts.astype(dtype=np.float32)`

3. Set precision to 32 in your model, eg
```
model = TFTModel(
    output_chunk_length = 24,
    n_epochs=5,
    **config,
    pl_trainer_kwargs={
      "accelerator": "tpu",
      "devices":"auto",
      "precision": '32-true',
    },
)
```

This worked for me!
