### ISSUE TITLE
[BUG] After installing Darts, I activate the virtual environment, it will pop "SET CMDSTAN="

### ISSUE THREAD

**Issue by havanoname** [unit8co/darts#1900]
**Describe the bug**
First, I activate my virtual environment: `conda activate PHM`
then, I am install Darts with `conda install -c conda-forge -c pytorch u8darts-all`
After that, every time I activate virtual environment: `conda activate PHM`, it will pop:
```
C:\Users\un>SET CMDSTAN_OLD=
C:\Users\un>SET CMDSTAN=C:/MyApp/Anconda3/envs/PHM\Library\bin\cmdstan\
```

**To Reproduce**
![image](https://github.com/unit8co/darts/assets/42195455/59dcd4ac-14c2-41fe-96b7-a33449e1a9a4)

**Expected behavior**
Darts seems to be working properly, but it's annoying to have this prompt popping up every time. How can I get rid of this prompt?

**System:**
 - Python version [3.9.10]
 - darts version [0.24.0]
 - OS [windows 11]

**Comment by madtoinou** [comment]
Hi @havanoname,

Is this also occurring with your other conda environment? Can you try to reinstall cmdstan in the environment so that these variables are correctly set?

**Comment by yigitcancomlek** [comment]
Hello @madtoinou,

I am not the one who posted the issue but in my case it still persists with different environments. I have multiple environments with darts package and issue seems to be persistent in all environments when activating/deactivating the environments. I have tried to reinstall cmdstan but the issue is still there.  Please let us know if there's anything else I can provide to help you!

Thanks

**Comment by madtoinou** [comment]
The only thing I could find is this stackoverflow [post](https://stackoverflow.com/questions/75775293/error-activating-environment-via-powershell) but there is no solution yet.

I would start with a clean conda environment, follow the instruction from the [cdmstan documentation](https://mc-stan.org/docs/2_28/cmdstan-guide/cmdstan-installation.html#cmdstan-installation) and then install darts. If the problem persists, you could open an issue in cmdstanpy [repository](https://github.com/stan-dev/cmdstanpy) and see what they suggest.

**Comment by havanoname** [comment]
In a new conda environment, I tried to install Darts and still had this problem. I will try to install the older version later to see if this problem occurs.

- Python version [3.10.9]
- darts version [0.26.0]
- OS [windows 11]
