### ISSUE TITLE
[BUG] Stochastic TimeSeries Plotting on Multiple Axes

### ISSUE THREAD

**Issue by ahowe42** [unit8co/darts#1911]
**Describe the bug**
Often, I want to plot multiple `TimeSeries` and / or multiple model predictions on several axes in the same matplotlib figure using subplots(). If I'm plotting a stochastic series - predictions with `num_samples` > 1 into a specific axis, the `central_quantile` series plots on the specified axis. However, the CI specified by the `low_quantile` and `high_quantile` will plot on the last axis of the figure.

**To Reproduce**
```
# imports
import matplotlib.pyplot as plt
from darts.datasets import AirPassengersDataset
from darts.models import ExponentialSmoothing
# load the data
airData = AirPassengersDataset().load()
# fit & predict with naive drift model
modl = ExponentialSmoothing()
modl.fit(airData)
preds = modl.predict(len(airData), num_samples=500)
# plot
fig, axs = plt.subplots(1, 3, figsize=[10,4])
airData.plot(label='Airline Passengers', ax=axs[0])
preds.plot(label='Predictions', ax=axs[0])
```
This produces a figure (and warning) as shown in the attached screenshot.
![bug](https://github.com/unit8co/darts/assets/18550216/f07a33d9-79eb-4dd9-839d-e70d22d53da6)

**Expected behavior**
I expect the entire stochastic series (central, low, high quantiles) to plot on the specified axis.

**System (please complete the following information):**
 - Python version: 3.8.5
 - darts version: 0.24.0

**Comment by jocapinho** [comment]
Hello, ahowe42

Seems to be a bug with preds.plot. The quantiles stick to the last subplot of the figure.
Either plot multiple figures or stick the preds plot to the last subplot

![image](https://github.com/unit8co/darts/assets/89033179/2c670632-26a8-493e-9109-30bd54f3f9ed)


![image](https://github.com/unit8co/darts/assets/89033179/eaaeaa03-c8e3-488e-8562-18996dfde5eb)

**Comment by ahowe42** [comment]
Thanks Jocapinho. In my case, I was plotting the probabilistic predictions from multiple models on the same subplots figure, so the workaround (use last axis) wouldn't work :-).
