### ISSUE TITLE
[Question] Regression models ignore past/future encoders.

### ISSUE THREAD

**Issue by RodrigoZepeda** [unit8co/darts#1912]
**Describe the bug**
When fitting a `RegressionModel`, a `LinearRegressionModel` or `LightGBM` with past and future encoders the program throws a warning:

```
Specified past encoders in `add_encoders` at model creation but model does not accept past covariates. past encoders will be ignored.
Specified future encoders in `add_encoders` at model creation but model does not accept future covariates. future encoders will be ignored.
```

However the [documentation](https://unit8co.github.io/darts/README.html#forecasting-models) and the `supports_past_covariates/supports_future_covariates` attributes say they should. Maybe I am specifying the encoders incorrectly?

**To Reproduce**

```
from darts.models import RegressionModel, LinearRegressionModel, LightGBMModel
import darts.utils.timeseries_generation as tg

# Generate fake time series
ts = tg.sine_timeseries(value_frequency=0.05, length=100) + 0.1 * tg.gaussian_timeseries(length=100)

# Encoders 
encoders = {"cyclic": {"past": ["month"], "future": ["month"]}}

# Models
model_1 = RegressionModel(lags=1, add_encoders=encoders)
model_2 = LinearRegressionModel(lags=1, add_encoders=encoders)
model_3 = LightGBMModel(lags=1, add_encoders=encoders)

# Warnings
model_1.fit(ts)
model_2.fit(ts)
model_3.fit(ts)

# They all support
print(model_1.supports_past_covariates)
print(model_2.supports_past_covariates)
print(model_3.supports_past_covariates)
print(model_1.supports_future_covariates)
print(model_2.supports_future_covariates)
print(model_3.supports_future_covariates)
```

**Expected behavior**
I'm not sure on how to run a LinearRegression model with encoders creating the covariates. 

**System (please complete the following information):**
 - Python 3.10.12
 - darts 0.24.0

**Comment by dennisbader** [comment]
Hi @RodrigoZepeda. You need to add `lags_past_covariates` and/or `lags_future_covariates` at model creation for the regression models to use the encodings and covariates.

**Comment by RodrigoZepeda** [comment]
Thanks for the clarification @dennisbader I'm closing the issue now.
