### ISSUE TITLE
[Question] TFT Multi-targets: Quantile Regression, are samples generated independently or dependently

### ISSUE THREAD

**Issue by zachyattack23** [unit8co/darts#1914]
Hello, I've been using darts tft model for about a week, and its been fantastic: much easier to use than pytorch-forecasting. My timeseries dataset has multiple targets, and I'm wondering that when I predict and set a sample size, are the samples generated independently or dependently. For example, I might have two target columns, Lebron James points and Anthony Davis points. I was wondering if the effect of Lebron James points also affects Anthony Davis' points. for example, Lebron James might score 50 points, which in theory should make Anthony Davis average to go down as its harder for him to score points as there are probably less scoring opportunities. If the multi targets are generated independently, then the sample of Lebron James points wont affect Anthony Davis points. I was wondering if there could be support created for targets that are generated dependently, or if you have any suggestions on solutions to this matter?

**Comment by dennisbader** [comment]
Hi @zachyattack23, and thanks for the nice words.

- If your `n` targets are stacked in one multivariate (multi-column/component) TimeSeries, then the targets are generated dependently with TFTModel. In other words we have a `n`-dimensional problem (or for quantile regression `n*q` dimensional with q being the number of quantiles).
- If your targets are passed as a sequence (list) of univariate (single component) TimeSeries, then the targets are generated independently. In other words we have `n` one-dimensional problems (or for quantile regression `n` `q`- dimensional probelms)

**Comment by zachyattack23** [comment]
Thanks for the response!

**Comment by zachyattack23** [comment]
This I believe is actually wrong. I ran a multivariate dataset that I know has correlation between outputs, but then when I called the predict method with a sufficient sample, and tested the correlation (r-value) between predicted outputs, everything came up with r-values that were close to 0, meaning the model is most likely generating outputs independently or something is wrong where it is unable to see the correlation between multivariate outputs that should be fairly obvious

**Comment by madtoinou** [comment]
Hi @zachyattack23,

Would it be possible to share a code snippet with a dummy/public dataset so that we can offer an answer closer to your use-case?
