### ISSUE TITLE
[BUG] RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by rishi-a** [unit8co/darts#1919]
**Describe the bug**
I'm trying to run the [TCNModel](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tcn_model.html) with the following parameters.
`my_model = TCNModel(
    input_chunk_length=50,
    output_chunk_length=1,
    kernel_size=3,
    num_filters=5,
    dilation_base=4,
    num_layers=2,
    dropout=0.25,
    batch_size=5,
    n_epochs=25,
    optimizer_kwargs={"lr": 0.0045},
    log_tensorboard=True,
    random_state=42,
    force_reset=True,
    pl_trainer_kwargs={
      "accelerator": "gpu"
    },
)`

But I get an error which reads, `RuntimeError: GET was unable to find an engine to execute this computation
`

**To Reproduce**
Followed the [steps listed here](https://github.com/unit8co/darts/issues/new?assignees=&labels=bug%2C+triage&projects=&template=bug_report.md&title=%5BBUG%5D) to create a new conda environment and used `pip` to install darts. 

**Expected behavior**
Expected the model to start traning. Infact it works fine when I try to run in the CPU

**System Information:**
 - Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)
 - darts version: 0.24.0
 - CPU Architecture: x86_64
 - GPU: Titan XP (12 GB)
 - CUDA: Version 12.0 as per `nvidia-smi`
 - Driver Version: Driver Version: 525.105.17 
 - CPU: Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz
 - OS: Ubuntu 18.04 LTS

**Comment by alexcolpitts96** [comment]
I was unable to replicate on the current main branch.

Could you post the full code to replicate the problem?

**Comment by rishi-a** [comment]
Sure, 

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from darts import TimeSeries
from darts.models import TCNModel, RNNModel
from darts.dataprocessing.transformers import Scaler
from darts.utils.timeseries_generation import datetime_attribute_timeseries
from darts.metrics import mape, r2_score
from darts.utils.missing_values import fill_missing_values
from darts.datasets import AirPassengersDataset, SunspotsDataset, EnergyDataset

# Read data:
ts = AirPassengersDataset().load()
scaler = Scaler()
ts = scaler.fit_transform(
    ts
)  # scale the whole time series not caring about train/val split...

# We'll use the month as a covariate
month_series = datetime_attribute_timeseries(ts, attribute="month", one_hot=True)
scaler_month = Scaler()
month_series = scaler_month.fit_transform(month_series)

# Create training and validation sets:
train, val = ts.split_after(pd.Timestamp("19580801"))
train_month, val_month = month_series.split_after(pd.Timestamp("19580801"))


model_air = TCNModel(
    input_chunk_length=13,
    output_chunk_length=12,
    n_epochs=500,
    dropout=0.1,
    dilation_base=2,
    weight_norm=True,
    kernel_size=5,
    num_filters=3,
    random_state=0,
    pl_trainer_kwargs={
        "accelerator": "gpu",
        "devices": [0]
    }
)

model_air.fit(
    series=train,
    past_covariates=train_month,
    val_series=val,
    val_past_covariates=val_month,
    verbose=True,
)

```


I get the following warning before the GET error

```
home/rishiraj.a/anaconda3/envs/jouleseye/lib/python3.9/site-packages/lightning_fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/rishiraj.a/anaconda3/envs/jouleseye/lib/python ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/rishiraj.a/anaconda3/envs/jouleseye/lib/python3.9/site-packages/lightning_fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/rishiraj.a/anaconda3/envs/jouleseye/lib/python ...
  rank_zero_warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type              | Params
----------------------------------------------------
0 | criterion     | MSELoss           | 0     
1 | train_metrics | MetricCollection  | 0     
2 | val_metrics   | MetricCollection  | 0     
3 | dropout       | MonteCarloDropout | 0     
4 | res_blocks    | ModuleList        | 366   
----------------------------------------------------
366       Trainable params
0         Non-trainable params
366       Total params
0.001     Total estimated model params size (MB)
```

The error
`RuntimeError: GET was unable to find an engine to execute this computation`

**Comment by dennisbader** [comment]
Hi @rishi-a, this error comes from the pytorch/cuDNN side. It looks very similar to [this one](https://discuss.pytorch.org/t/cudnn-version-incompatibility/180642/4) issue which might solve yours as well.
