### ISSUE TITLE
Support for probabilistic predictions with historical_forecasts 

### ISSUE THREAD

**Issue by ramiyaari** [unit8co/darts#1924]
I want to use the historical_forecasts method instead of calling fit and predict to evaluate the forecasting models over the whole timeseries. However, in this method there is no support for setting num_samples to obtain a probablistic prediction like in the predict method. So the timeseries returned by historical_forecasts doesn't support calling quantile_df like the timeseries returned by predict. Is that a missing feature by the package or is there a way to overcome this limitation? Is there a reason for this limitation?

**Comment by madtoinou** [comment]
Hi, which version of darts are you using?

In the latest version (0.24.0 at the time of writing), `historical_forecasts()` does have an argument `num_samples` ([doc]( https://unit8co.github.io/darts/generated_api/darts.models.forecasting.dlinear.html?highlight=historical_forecasts#darts.models.forecasting.dlinear.DLinearModel.historical_forecasts)) that allows you to obtain a probabilistic forecasts.

**Comment by ramiyaari** [comment]
Thank you. Apparently, either I was looking at an older version or I missed it somehow.
