### ISSUE TITLE
[Question] snapshots based time series forecasting

### ISSUE THREAD

**Issue by jacktang** [unit8co/darts#1926]
Hello,

First of all, thanks for the great framework to make time series forecasting easy! I am now building time series forecasting model based on the snapshots. Each snapshot are independent and contains 100 time steps, also 12 input controls(past and future covariates) and 2 targets. And 200 training samples in total. So I will organise the `X_train` as  (200, 12, 100) and `y_train` as (200, 2, 100). Is that right to darts? Thanks!

**Comment by madtoinou** [comment]
Hi,

What do you mean by snapshot? Same question for training samples: do they correspond to the recording of the same features for 200 different entities or something else? If you can generate 200 `TimeSeries` containing 100 timestamps for the 2 targets, then you could use "multiple series" training ([doc](https://unit8co.github.io/darts/userguide/timeseries.html#multivariate-time-series-vs-multiple-time-series)). In darts, "samples" generally refers to probabilistic forecasting ([doc](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Probabilistic-forecasts)).

If there are independent datasets, and you want to train on a single one of them, you will need to create the target/covariates `TimeSeries` and pass them to the model as follow:

```python
# multivariate target, model will predict both columns. shape : (100, 2, 1)
ts_target = TimeSeries...
# past covariates, not known beyond the first forecasted timestamp. shape : (100, p, 1)
ts_past = ...
# future covariates, available for the entire forecasted period.  shape : (100, n, 1)
ts_future = ...

model = ...
model.fit(series=ts_target, past_covariates=past_ts, future_covariates=future_ts)
# prediction shape will be (10, 2, 1)
model.predict(n=10, past_covariates=..., future_covariates=...)
```

**Comment by jacktang** [comment]
@madtoinou Thanks for your informative reply. The `snapshot` in my case is very similar to `Example of multiple series: The blood pressure and heart rate of multiple patients; potentially measured at different times for different patients (one multivariate series with 2 components per patient)`. I will try your suggestions and update it later. Thanks!

**Comment by madtoinou** [comment]
Thank you for this clear explanation of what `snapshot` stands for.

If you want to train a single model to support all the snapshots, I really think that you should use multiple series training. I will try to break down the other approaches and explain why they seem less appropriate:
- Concatenating all the snapshots together on the time axis: darts will complain as they do no correspond to a single continuous time frame and filling the missing timestamps will considerably affect the performance.
- Concatenating all the snapshots on the components axis: this will require using a dummy time index as these snapshots were acquired at different $Time$. Furthermore, it means that independent snapshots will influence each other forecast.

Let me know what you think.

**Comment by jacktang** [comment]
> ```python
> # multivariate target, model will predict both columns. shape : (100, 2, 1)
> ts_target = TimeSeries...
> # past covariates, not known beyond the first forecasted timestamp. shape : (100, p, 1)
> ts_past = ...
> # future covariates, available for the entire forecasted period.  shape : (100, n, 1)
> ts_future = ...
> 
> model = ...
> model.fit(series=ts_target, past_covariates=past_ts, future_covariates=future_ts)
> # prediction shape will be (10, 2, 1)
> model.predict(n=10, past_covariates=..., future_covariates=...)
> ```

Hello @madtoinou ! I followed the code suggested, and I think it is right :), I mean the `predict` function takes `future_covariates` only, and forecast the snapshot (the series) from the very beginning. But it comes up the error:

```
from darts.models import RNNModel

y_train_snapshots = [y_ts_1, ...., y_ts_200] #  flow rate at Z
X_train_snapshots = [x_ts_1, ..., x_ts_200] # flow rate of 12 branches

model = RNNModel(input_chunk_length=24, 
                 training_length=24, 
                 n_rnn_layers=2)

model.fit(y_train_snapshots, 
          future_covariates=X_train_snapshots, 
          epochs=100, 
          verbose=True)

one_y_test = TimeSeries.from_values(y_test[0])
one_x_test = TimeSeries.from_values(X_test[0])

pred = model.predict(n=24,  future_covariates=one_x_test)

one_y_test.plot(label="actual")
pred.plot(label="forecast")
plt.legend()
print("MAPE = {:.2f}%".format(mape(one_y_test, pred)))
```

And the error:

```
ValueError: Input `series` must be provided. This is the result either from fitting on multiple series, or from not having fit the model yet.
```

Could you please give me some suggestions? Thanks!

**Comment by madtoinou** [comment]
As suggested by the error message, when a model is trained on several series, the "ts to forecast" must be passed to the `predict()` method (so that the appropriate past target values are processed and the appropriate time index is generated for the forecast). In your case, the beginning of the snapshot to forecast:

```python
# y_ts contain the flow rate a z and its last timestamp is just before the first timestamp to predict
pred = model.predict(n=72,  series=y_ts, future_covariates=one_x_test)
```

**Comment by jacktang** [comment]
@madtoinou Thanks for your kindly suggestion! I set the `input_chunk_length = 1` in the model and `predict` next 71 time steps. It works!
