### ISSUE TITLE
What model is closest to pyDLMs BSTS (Bayesian Structural Time Series) Models?

### ISSUE THREAD

**Issue by Vaslo** [unit8co/darts#1930]
We worked with a large consulting firm before I joined my team and this firm was tasked with providing some sales models vs. a number of economic indicators as covariants.  They were getting some of their best results using BSTS models they appear to work with from a Python package called PyDLM.   I don't see that package or BSTS in relation to darts but I know there are lots of other models per the front page of the site.  Is there any model that would be similar so that I can somewhat compare results between what they have achieved vs similar models in darts?

Thanks.

**Comment by madtoinou** [comment]
Hi @Vaslo,

As per the documentation of PyDLM, this library seems to implement a modified version of the Kalman filter (which is available in darts, [doc](https://unit8co.github.io/darts/generated_api/darts.models.filtering.kalman_filter.html?highlight=kalman#module-darts.models.filtering.kalman_filter).

On top of the filter, there are some modelling components that can be added : "trend, seasonality, dynamic and auto-regressive" which correspond respectively to `NaiveDrift`, `NaiveSeasonal`, past/future covariates, and `LinearRegressionModel`. These models could then be grouped using a `RegressionEnsembleModel` to combine their forecasts (models will be trained with the stacking technique).

This is in my opinion what would be the closest to the PyDLM's approach, but you could probably compare it with any of the darts `RegressionModel` or `LocalForecastingModel`.

**Comment by Vaslo** [comment]
Thanks for the quick reply!  I didn't know it was that simple to compare the two.  I'll give the Kalman filter a shot to compare.  I'll also compare to the other ones you recommended as soon as possible.
