### ISSUE TITLE
Latest pmdarima (1.7.1) requires statsmodels (>=0.11,<0.12)

### ISSUE THREAD

**Issue by norihitoishida** [unit8co/darts#194]
Latest pmdarima (1.7.1) requires statsmodels>=0.11,<0.12(latest), because latest statsmodels seems to have bugs.
 - https://github.com/alkaline-ml/pmdarima/issues/376
 - https://github.com/alkaline-ml/pmdarima/blob/master/requirements.txt

If users follow [the official instructions](https://github.com/unit8co/darts#running-the-examples-only-without-installing) for setting up Docker, they will end up with the latest statsmodels(0.12) installed.
So, should we fix requirements/main.txt  like this?
```
- statsmodels>=0.11.1
+ statsmodels>=0.11.1, <0.12 
```
https://github.com/unit8co/darts/blob/master/requirements/main.txt

I would like to get your opinion. Thanks!

**Comment by hrzn** [comment]
Hi @norihitoishida , thanks for pointing this out! The next release should have `statsmodels==0.11.1` (we are moving to `==` everywhere. In addition, we are also considering moving pmdarima to an optional extra dependency of Darts.

**Comment by norihitoishida** [comment]
Hi @hrzn , thanks for your reply. Sounds good!
