### ISSUE TITLE
Exploring Multi-GPU Training: Challenges and Observations in Initiating Model Training

### ISSUE THREAD

**Issue by 1404971870** [unit8co/darts#1940]
While attempting to utilize multiple GPUs for training, I encounter a challenge in commencing the training of the model. Curiously, there is no apparent error reported. However, it seems that Python has indeed been allocated to the GPU, as evidenced by the presence of two Python processes consuming 309MB of VRAM each on my dual GPUs. Notably, when employing a solitary GPU for training, the execution proceeds without issue. Nonetheless, when utilizing both GPUs, the output remains as follows, with the commencement of training being conspicuously delayed:
The catboost module could not be imported. To enable support for CatBoostRegressor, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
Support for LightGBM not available. To enable LightGBM support in Darts, follow the detailed install instructions for LightGBM in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
The prophet module could not be imported. To enable support for Prophet model, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
The catboost module could not be imported. To enable support for CatBoostModel model, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
/data/sunys/miniconda3/envs/lstm7/lib/python3.9/site-packages/torch/random.py:107: UserWarning: CUDA reports that you have 4 available devices, and you have used fork_rng without explicitly specifying which devices are being used. For safety, we initialize *every* CUDA device by default, which can be quite slow if you have a lot of GPUs.  If you know that you are only making use of a few CUDA devices, set the environment variable CUDA_VISIBLE_DEVICES or the 'devices' keyword argument of fork_rng with the set of devices you are actually using.  For example, if you are using CPU only, set CUDA_VISIBLE_DEVICES= or devices=[]; if you are using GPU 0 only, set CUDA_VISIBLE_DEVICES=0 or devices=[0].  To initialize all devices and suppress this warning, set the 'devices' keyword argument to `range(torch.cuda.device_count())`.
  warnings.warn(
/data/sunys/miniconda3/envs/lstm7/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:196: UserWarning: Attribute 'loss_fn' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['loss_fn'])`.
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
The catboost module could not be imported. To enable support for CatBoostRegressor, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
Support for LightGBM not available. To enable LightGBM support in Darts, follow the detailed install instructions for LightGBM in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
The prophet module could not be imported. To enable support for Prophet model, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
The catboost module could not be imported. To enable support for CatBoostModel model, follow the instruction in the README: https://github.com/unit8co/darts/blob/master/INSTALL.md
/data/sunys/miniconda3/envs/lstm7/lib/python3.9/site-packages/torch/random.py:107: UserWarning: CUDA reports that you have 4 available devices, and you have used fork_rng without explicitly specifying which devices are being used. For safety, we initialize *every* CUDA device by default, which can be quite slow if you have a lot of GPUs.  If you know that you are only making use of a few CUDA devices, set the environment variable CUDA_VISIBLE_DEVICES or the 'devices' keyword argument of fork_rng with the set of devices you are actually using.  For example, if you are using CPU only, set CUDA_VISIBLE_DEVICES= or devices=[]; if you are using GPU 0 only, set CUDA_VISIBLE_DEVICES=0 or devices=[0].  To initialize all devices and suppress this warning, set the 'devices' keyword argument to `range(torch.cuda.device_count())`.
  warnings.warn(
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2

distributed_backend=nccl
All distributed processes registered. Starting with 2 processes

**Comment by 1404971870** [comment]
Hello,

I hope this message finds you well. Firstly, I want to express that I have thoroughly reviewed the guidelines and have configured the pl_trainer_kwargs as follows: "accelerator": "gpu", "devices": [0, 1], "strategy": "ddp". Additionally, I have ensured that my Darts version is 0.25.0.

I am currently facing an issue where my training process is not progressing beyond the point where the output displays "distributed_backend=nccl All distributed processes registered. Starting with 2 processes." It appears that the training process is stuck at this step, before the actual model training begins. For your convenience, I have attached my code to provide a clearer understanding of the situation.

Thank you for your time and assistance.

my code:
```
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import shutil
from sklearn.preprocessing import MinMaxScaler
from tqdm import tqdm_notebook as tqdm
import matplotlib.pyplot as plt

from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler
from darts.models import RNNModel
from darts.metrics import mape
from darts.utils.statistics import check_seasonality, plot_acf
from darts.utils.timeseries_generation import datetime_attribute_timeseries
from darts import concatenate
import os
os.environ["TORCH_USE_RTLD_GLOBAL"] = "1"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"
os.environ["NCCL_DEBUG"] = "WARN"

if __name__ == '__main__':
    torch.multiprocessing.freeze_support()
   series_is = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols='number_IS')

    co_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['CO'])
    co_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['CO_24h'])
    no2_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['NO2'])
    no2_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['NO2_24h'])
    o3_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['O3'])
    o3_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['O3_24h'])
    o3_8h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['O3_8h'])
    pm10_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['PM10'])
    pm10_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['PM10_24h'])
    pm25_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['PM2.5'])
    pm25_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['PM2.5_24h'])
    so2_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['SO2'])
    so2_24h_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['SO2_24h'])
    low_tem_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['low_tem'])
    high_tem_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['high_tem'])
    tem_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['tem'])
    hum_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['hum'])
    wind_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['wind'])
    windy_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['windy'])
    rain_cov = TimeSeries.from_csv('/data/sunys/program/lstm/darts-master/my/data_3201.csv', time_col='date', value_cols=['rain'])

    train_series, val_series = series_is.split_after(pd.Timestamp("2020-5-23"))

    scaler = Scaler()

    training_scaled = scaler.fit_transform(train_series)
    val_scaled = scaler.transform(val_series)

    scaler_cov = Scaler()

    covs = concatenate([co_cov, co_24h_cov, no2_cov, no2_24h_cov, o3_cov, o3_24h_cov, o3_8h_cov, pm10_cov, pm10_24h_cov, pm25_cov, pm25_24h_cov, so2_cov, so2_24h_cov, low_tem_cov, high_tem_cov, tem_cov, hum_cov, wind_cov, windy_cov, rain_cov], axis=1)

    scaled_covs = scaler_cov.fit_transform(covs)

    scaled_train_covs, scaled_val_covs = scaled_covs.split_after(pd.Timestamp("2020-5-23"))

    my_model = RNNModel(
        model="LSTM",
        hidden_dim=1,
        n_rnn_layers=1,
        dropout=0,
        batch_size=100,
        n_epochs=100,
        optimizer_kwargs={"lr": 1e-3},
        model_name="single_1_RNN_param_mape",
        log_tensorboard=True,
        random_state=42,
        training_length=140,
        input_chunk_length=140,
        pl_trainer_kwargs={"accelerator": "gpu", "devices": [0,1], "strategy":"ddp"},
        force_reset=True,
        save_checkpoints=True,
    )
    my_model.fit(
        training_scaled,
        future_covariates=scaled_covs,
        val_series=val_scaled,
        val_future_covariates=scaled_covs,
        verbose=True,
    )
```

**Comment by dennisbader** [comment]
Alirght, I would suggest doing the following things to boil down where the problem comes from:
- try if it works without setting the environment variables at the beginning (not sure if they're required). Usually pytorch-lightning handles all of this behind the hood.
- use only a small dataset (you might have to lower `training_length` and `input_chunk_length`, note also that `training_length` should be higher than `input_chunk_length` as described [in the docs](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.rnn_model.html#recurrent-neural-networks)):
  ```
  from darts.datasets import AirPassengersDataset
  s = AirPassengersDataset().load()
  model.fit(series=s)
  ```
- try if it works using only a single GPU, e.g. `pl_trainer_kwargs={"accelerator": "gpu", "devices": [0]}`

**Comment by dennisbader** [comment]
Closing as stale
