### ISSUE TITLE
[BUG] TFT model load failed from saved model.

### ISSUE THREAD

**Issue by heury** [unit8co/darts#1946]
**Describe the bug**

I get following error when I try to load TFT model from file.

ValueError: The values of the hyper parameter categorical_embedding_sizes should be identical between the instantiated model (None) and the loaded checkpoint ({}). Please adjust the model accordingly.

**To Reproduce**
I just save trained model and load it from file. 
And I get following error when I try to load model from file.

ValueError: The values of the hyper parameter categorical_embedding_sizes should be identical between the instantiated model (None) and the loaded checkpoint ({}). Please adjust the model accordingly.

This error is gone when I add following parameter to the model.

categorical_embedding_sizes={}

**Expected behavior**

**System (please complete the following information):**
 - Python version: 3.10
 - darts version: 0.25

**Additional context**

**Comment by dennisbader** [comment]
Hi @heury and thanks pointing this out. It's indeed a bug and we'll fix it soon.
