### ISSUE TITLE
[BUG] dataset link is broken

### ISSUE THREAD

**Issue by bigchou** [unit8co/darts#1948]
I try to run the example [here](https://unit8co.github.io/darts/examples/14-transfer-learning.html) but the dataset link is broken. May you fix the link? Thank you!

~~~~
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/m3_dataset.xls\?raw\=true -o m3_dataset.xls
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/passengers.pkl\?raw\=true -o passengers.pkl
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/m4_monthly_scaled.pkl\?raw\=true -o m4_monthly_scaled.pkl
~~~~

**Comment by madtoinou** [comment]
Hi @bigchou,

Thank you for reporting this bug, we will correct these links so that they won't depend on the amld2022 repository (which visibility changed to private). It might take a little bit of time as this notebook also need to be updated for the latest version of darts.

**Comment by llofberg** [comment]
Would anyone be able to provide a working link to these data?

**Comment by kshitiz305** [comment]
Hi I want to take this. Please let me know what is the appropriate link for replacement.
