### ISSUE TITLE
Missing values in TFT model

### ISSUE THREAD

**Issue by dagap** [unit8co/darts#1954]
I am new to using DL for time series and have been using Prophet which is pretty good at handling missing values.
For my current use case, I am looking into models that can train and predict on multiple time series simultaneously. These refer to measurements from multiple sensors.

In real life, sensors break or malfunction sometime and I have time series where there can be missing values. So the input time series has missing (NA) values. 

Can the TFT or any other models that can handle multiple time series and deal with past and future covariates deal with missing values?

**Comment by madtoinou** [comment]
Hi @dagap,

`NaN` values in the timeseries tend to induce additional `NaN` in both the models weights and forecasts. To prevent this, darts had a method to fill the missing values, you can find detailed information in the [documentation](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html?highlight=missing%20values).

**Comment by dagap** [comment]
Thank you. So one does need to do data imputation.
