### ISSUE TITLE
Consider holiday calendar for training and forecasting

### ISSUE THREAD

**Issue by raj5287** [unit8co/darts#1959]
Hi

Is there a way to consider holiday calendar while model training and forecasting future data? like let's say around some of the holidays my sales goes up, or I gave discounts on some of the days. So is there a way to give this information to model?

**Comment by madtoinou** [comment]
Hi @raj5287,

Yes, you can use the `future_covariates` to pass such information to the models supporting it.

Darts also provides some methods to automatically build this series : [`holidays_timeseries`](https://unit8co.github.io/darts/generated_api/darts.utils.timeseries_generation.html?highlight=holidays#darts.utils.timeseries_generation.holidays_timeseries).
