### ISSUE TITLE
[Question] "dynamic" past_covariates to label possibly unknown historical anomalies?

### ISSUE THREAD

**Issue by maksimt** [unit8co/darts#1961]
Hey, the timeseries I'm trying to forecast on has periods affected by anomalies. I'd like to forecast what the timeseries would be if there were no anomalies.

I believe the supported method to do this is to use various interpolation techniques (e.g. Gaussian Processes) to fill historically anomalous periods.

I'd like to try adding a timeseries of anomaly labels as a past covariate. The tricky thing is that on day d, we don't know whether a few historical days were anomalous yet, we have to wait to be sure. I.e. for a given day d, we don't know whether days [d-1, d-2, ..., d-7] have anomalies, but we do know whether days [d-8, d-9, ...] had anomalies or not. Essentially I'd like to create a past covariates time series of enums {had anomaly, didn't have anomaly, don't know}. The tricky thing is that I'd like the "don't know" to be emulated in the `.fit()` call on historical data...

Curious to hear if there's a way to achieve this, or whether there are better ways to handle (but still use) anomalous historical data.

**Comment by madtoinou** [comment]
Hi @maksimt,

I think that the easiest way to do what you're describing is to use a model with past covariates lags greater than -7. This way, you can use the true "anomaly label" during training without having the model to look at the "we don't know" period.

The downside of this approach is that if you have other past covariates, darts does not allow component-specific lags at the moment and you would have to use the same for all of them.
