### ISSUE TITLE
Does Grid Search works with Regression Model, Like scikit learn Model and its parameters to be tuned??

### ISSUE THREAD

**Issue by keyanatmotorola** [unit8co/darts#1970]

**Comment by dennisbader** [comment]
Hi @keyanatmotorola, yes it does. However, we recommend hyper parameter optimization with optuna or ray tune. We have an example for this [here](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html#hyperparameter-optimization-in-darts).

**Comment by keyanatmotorola** [comment]
@dennisbader Grid Search will not explicity work if the params in the Model in the RegressionModel class, it will be done seperately, I did it seperately and customized to first do the grid search first and find the best model and get that best model defined in Model param of RegressionModel.

FYR. Thanks!
