### ISSUE TITLE
Use Sklearn's LassoLars Regression with Darts's Linear Regression model

### ISSUE THREAD

**Issue by carlosg-m** [unit8co/darts#1971]
According to Sklearn's documentation:
> Least-angle regression (LARS) is a regression algorithm for high-dimensional data, developed by Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani. LARS is similar to forward stepwise regression. At each step, it finds the feature most correlated with the target. When there are multiple features having equal correlation, instead of continuing along the same feature, it proceeds in a direction equiangular between the features. [LassoLars](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoLars.html#sklearn.linear_model.LassoLars) is a lasso model implemented using the LARS algorithm, and unlike the implementation based on coordinate descent, this yields the exact solution, which is piecewise linear as a function of the norm of its coefficients.

When taking lags out of a time-series, specially in series with high sample frequency we end up with a high dimensionality dataset, where some features are not relevant and others are very correlated with each other (collinear features). 

Sklearns LarsLasso deals with all of these issues and is extremely fast.

Example:

```
def sklearn_autoreg(pd_ts, lags, alpha, forecast_horizon):
    # Sklearn's LassoLars with Autoregression

    assert np.min(lags) > 0, 'lags have to be greather than zero'

    if isinstance(lags, (int, float)):
        lags_selected = np.arange(lags)
    else:
        lags_selected = np.array(lags) - 1
        lags = np.max(lags)

    ytrain = pd_ts.values
    ytrain_mask = ~np.isnan(ytrain)

    xtrain = np.concatenate([np.repeat(np.array(np.nan).astype(np.float32), lags), pd_ts.values], axis=0)
    xtrain = np.lib.stride_tricks.sliding_window_view(xtrain[:-1], window_shape=(lags,))
    xtrain = xtrain[:,lags_selected]
    
    model = Pipeline([('imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
                      ('scaler', StandardScaler()),
                      ('model', LassoLars(alpha=alpha))])
    
    model.fit(xtrain[ytrain_mask], ytrain[ytrain_mask])
    xtrain = model.predict(xtrain)

    xpred = pd_ts.values[-lags:]
    for _ in np.arange(forecast_horizon):
        xpred_append = xpred[-lags:]
        xpred_append = xpred_append[lags_selected]
        xpred_append = xpred_append.reshape(1,-1)
        xpred_append = model.predict(xpred_append)
        xpred = np.concatenate([xpred, xpred_append], axis=0)
    xpred = xpred[-forecast_horizon:]

    xtrain = pd.Series(xtrain, index=pd_ts.index)
    xpred = pd.Series(xpred, index=pd.date_range(start=pd_ts.index[-1], 
                                                 periods=forecast_horizon+1, 
                                                 freq=pd_ts.index.freq, inclusive='right'))
    
    return pd.concat((xtrain, xpred), axis=0)
```

**Comment by dennisbader** [comment]
Hi @carlosg-m, is your issue related to integrating LassoLars to Darts?
Darts `RegressionModel` accepts any sklearn regressor with model creation parameter `model`. You can find the documentation [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.regression_model.html#darts.models.forecasting.regression_model.RegressionModel).
