### ISSUE TITLE
WARNING about dependecies which were removed with darts 0.25.0

### ISSUE THREAD

**Issue by MichalRIcar** [unit8co/darts#1972]
Hello,

I've just installed 
Python 3.11.4
darts 0.25.0

on Windows 11 via pip install darts

everything works OK, however, Python is printing following WARNINGs

WARNING:darts.models.utils:The `Prophet` module could not be imported. To enable Prophet support in Darts, follow the detailed instructions in the installation guide: https://github.com/unit8co/darts/blob/master/INSTALL.md

WARNING:darts.models.utils:The `CatBoost` module could not be imported. To enable CatBoost support in Darts, follow the detailed instructions in the installation guide: https://github.com/unit8co/darts/blob/master/INSTALL.md

When reading Your installation instructions:
Enabling Optional Dependencies
By default, as of 0.25.0, darts does not have  Prophet, CatBoost, and LightGBM as dependencies anymore...

I am wondering if the WARNINGs above are appropriate under the last change? 

Best,
Michal

**Comment by dennisbader** [comment]
Hi @MichalRIcar, do you mean that we should not raise these warnings when importing somethiing from Darts?

The model wrappers are still supported in Darts after installing the dependencies. So I think we will continue to log the warnings for now.
You can also install `pip install u8darts[all]`, or `conda install -c conda-forge u8darts-all` which will install all the dependencies and remove this warning.

**Comment by MichalRIcar** [comment]
Hello @dennisbader, 

I am referring to the fact that default installation design is to not install Prophet, CatBoost, LightGBM. 
"By default, as of 0.25.0, darts does not have Prophet, CatBoost, and LightGBM as dependencies anymore..."

When user with default installation run any operation from darts lib then he/she sees these 3 WARNINGs from WARNING:darts.models.utils all the time and these are referring just to the new design of >= v.0.25.0.

I was thinking that it would be nice to rise an error describing/instructing the user to install opt packages - only when user explicitely asks for these opt packages (call them) which are not included rather than rising warnings all the time. I know I can supress it, but in general I believe that warning should be a real warning not a note referring to some options.

**Comment by dennisbader** [comment]
Hi @MichalRIcar, agreed. #1986 removes the warnings and raises an error when trying to create a model with missing dependency
