### ISSUE TITLE
SHAP Time series force_plots.

### ISSUE THREAD

**Issue by nomadicsenseis** [unit8co/darts#1980]
It would be very nice to have a function or force_plot() parameter that allows the representatios of force_plots for a given time series (kind of ploting verticarly the force_plot for a given timestamp and stacking all those plots together). If it is already implemented, would you mind providing me with an example?

**Comment by madtoinou** [comment]
Hi @nomadicsenseis,

This feature is actually already implemented and documented [here](https://unit8co.github.io/darts/generated_api/darts.explainability.shap_explainer.html?highlight=force_plot_from_ts#darts.explainability.shap_explainer.ShapExplainer.force_plot_from_ts).

A very basic example:
```python
import shap
from darts.models import LinearRegressionModel
from darts.datasets import AirPassengersDataset
from darts.explainability import ShapExplainer

ts = AirPassengersDataset.load()
model = LinearRegressionModel(lags=6)
model.fit(ts)
explainer = ShapExplainer(model)
explainer.force_plot_from_ts(ts)
```

**Comment by nomadicsenseis** [comment]
Thank you, that was great :) In case of wanting to select single dates, what would be the right approach? I have tried to use a single timeseries timestamp, something like _ts[-12]_ but so far unsuccesfully.

**Comment by madtoinou** [comment]
You need to slice the `TimeSeries` passed to `forace_plot_from_ts` so that the model can predict only one timestamp (based on its lags and the value of the `multi_models` parameter) but you might encounter the bug tracked by #1875 (different context but same error message).
