### ISSUE TITLE
Cumulative Sum on Timeseries class

### ISSUE THREAD

**Issue by Eliotdoesprogramming** [unit8co/darts#1981]
I make frequent use of the TimeSeries.diff() function for forecasting, I was hoping to add the reverse of the function `cumulative sum aka cumsum` to the TimeSeries class in order to provide opposite functionality. I've found this useful in conjunction with baseline models such as NaiveMovingAverage in order to provide decent baselines.

optionally something that I would propose to add is a `starting value` which could be a value to start with when using cumsum. This is again useful with baseline predictions on differenced values.

example psudocode:

```python
ts = TimeSeries.from_values([1,2,3,4,5])
diffs = ts.diff() # [1,1,1,1]
reversed_diff = diffs.cumsum() # [1,2,3,4]

model = NaiveMovingAverage()
model.fit(diffs)
average_diffs = model.predict(5) # [1,1,1,1,1]
baseline_prediction = average_diffs.cumsum(starting_value=ts[-1]) # starting value of 5
# baseline prediction w/ NaiveMovingAverage would be [6,7,8,9,10]

```

**Describe proposed solution**
I would implement the above pseudocode by mirroring the implementation of diff, except I would use the underlying xarray implementation of cumsum() (which relies on the numpy implementation of cumsum). 

**Describe potential alternatives**
Alternatively if this doesnt seem useful, its always possible to use the xarray implementation, but it requires a little bit more massaging. I figured it might be nice to have the reverse operation of `diff` as it was something that I found myself implementing at work.
 
**Additional context**
I'd be happy to contribute this issue if this is something the maintainers think would be a good addition! I already have a solution that I use, would just be modifying it & adding test cases to ensure functionality.

**Comment by madtoinou** [comment]
Hi @Eliotdoesprogramming,

`Diff()` is a invertible data transformer, meaning that it's already possible to retrieve the original series:

```python
from darts.dataprocessing.transformers import Diff

tr_diff = Diff()
ts_diff = tr_diff.fit_transform(ts)
ts_inv_diff = tr_diff.inverse_transform(ts_diff)
# noticed that the components' name are lost during the inverse transform, going to open a PR for this
ts.time_index == ts_inv_diff.time_index
ts.values() == ts_inv_diff.values()
```

Does the `cumsum()` method have others use-cases that would justify its implementation, WDYT @dennisbader ?

**Comment by dennisbader** [comment]
Hi @Eliotdoesprogramming, and thanks for this feature request. I think adding a `cumsum` method makes sense. 
It should have a signature similar to the pandas/numpy implementation.
I'd probably leave the `starting_value` support out of the method as we can do this with a simply addition:

```
baseline_prediction = average_diffs.cumsum() + ts.last_value()
```
