### ISSUE TITLE
encoders are not working for regressions

### ISSUE THREAD

**Issue by reidGP** [unit8co/darts#1983]
**Describe the bug**
encoders are not working for regressions

**To Reproduce**
Code:
```
from darts.datasets import AirPassengersDataset
from darts.models import LinearRegressionModel

series_air = AirPassengersDataset().load()

lr = LinearRegressionModel(
    lags=1,
    add_encoders={"cyclic": {"future": ["month"]}}
)

lr.fit(series=series_air)

print(lr.model.coef_)
```

Out:
Specified future encoders in `add_encoders` at model creation but model does not accept future covariates. future encoders will be ignored.
[0.95893198]

**Expected behavior**
The docstrs in the regression modules make it seem like I can use encoders. There was also a previous issue/question where it appears that regressions could use encoders. However, I have tried both past and future encoders and they don't seem to be supported for regressions. Is this expected or a bug?

**System (please complete the following information):**
 - Python version: 3.11
 - darts version: 0.25.0

**Additional context**
If not supported, how to add seasonality covariates to regressions?

**Comment by dennisbader** [comment]
Hi @reidGP, you need to set `lags_future_covariates` at model creation for the model to use the future covariates/encodings.

**Comment by reidGP** [comment]
Thanks for the quick response! I had just assumed that they would work with no lag, but I understand how this works as you say. The error message is a little unclear but hopefully people can see this Issue if they have a similar question. Thanks for clarifying.

Now that I have it working, it looks like when I add quarterly encoders they are encoded ordinally (i.e. taking values of 1, 2, 3, 4) but wouldn't it be a better default to create 3 quarterly dummy variables?
