### ISSUE TITLE
[BUG] Wrong link at the hosted docs

### ISSUE THREAD

**Issue by niklasdiehm** [unit8co/darts#1992]
**Describe the bug**
When viewing the darts documentation, the link at unit8co for Prophet and FTF are broken (see the image)
![grafik](https://github.com/unit8co/darts/assets/31044401/b794ab16-bce0-4ac2-aba0-c8a7cbb5e019)

**To Reproduce**
1. open the documentation at https://unit8co.github.io/darts/#features
2. hover on the link for FTF or Prophet

**Expected behavior**
It should redirect to the right site, like with all the other features.

**System (please complete the following information):**
- i think this should not make a difference

**Additional context**

**Comment by dennisbader** [comment]
Thanks for pointing this out @niklasdiehm.
We have already fixed this in #1969 and will be part of the next release.
