### ISSUE TITLE
[Question] Standard error for ARIMA

### ISSUE THREAD

**Issue by ZitongYang** [unit8co/darts#1997]
Does the current implementation supports computing the standard error of the ARIMA model? It is said in the documentation that probabilistic models support sampling from the future forecast. For these models, especially ARIMA, a standard practice is to also give the standard error of the prediction, along with the prediction itself.

**Comment by madtoinou** [comment]
Hi @ZitongYang,

Since `ARIMA` supports probabilistic forecasts, you should be able to pick an arbitrary large `n` value for `predict()` and then compute the standard error from the samples.
