### ISSUE TITLE
[BUG] TypeError: _nanquantile_dispatcher() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by levalencia** [unit8co/darts#2003]
**Describe the bug**
I have a pandaas dataframe with about 6k rows, with a timestamp column which is hourly and a value which is a float.

I am using DARTS for prediction and plotting

    import pandas as pd
    from darts import TimeSeries
    df = dfTienen_final.toPandas()
    df_no_duplicates = df.drop_duplicates(subset=['belgium_time'])
    
    series = TimeSeries.from_dataframe(df_no_duplicates, "belgium_time", "avg_value", freq="H")
    # Determine the number of rows in the DataFrame
    num_rows = len(series)
    
    # Set aside a percentage of the rows for validation (e.g., 10%)
    validation_percentage = 10  # Adjust as needed
    num_validation_points = (validation_percentage * num_rows) // 100  # Calculate the number of validation points
    
    # Set aside the calculated number of rows as a validation series
    train, val = series[:-num_validation_points], series[-num_validation_points:]
    
    from darts.models import ExponentialSmoothing
    
    model = ExponentialSmoothing()
    model.fit(train)
    prediction = model.predict(len(val), num_samples=1000)

and then this:

    import matplotlib.pyplot as plt
    
    series.plot()
    prediction.plot(label="forecast", low_quantile=0.05, high_quantile=0.95)
    plt.legend()

However I get this error in the plot

_nanquantile_dispatcher() got an unexpected keyword argument 'method'

traceback

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    File <command-3591413550716749>, line 4
          1 import matplotlib.pyplot as plt
          3 series.plot()
    ----> 4 prediction.plot(label="forecast", low_quantile=0.05, high_quantile=0.95)
          5 plt.legend()
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/darts/timeseries.py:3820, in TimeSeries.plot(self, new_plot, central_quantile, low_quantile, high_quantile, default_formatting, label, max_nr_components, ax, *args, **kwargs)
       3818         central_series = comp.mean(dim=DIMS[2])
       3819     else:
    -> 3820         central_series = comp.quantile(q=central_quantile, dim=DIMS[2])
       3821 else:
       3822     central_series = comp.mean(dim=DIMS[2])
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/dataarray.py:5123, in DataArray.quantile(self, q, dim, method, keep_attrs, skipna, interpolation)
       5015 def quantile(
       5016     self: T_DataArray,
       5017     q: ArrayLike,
       (...)
       5022     interpolation: QuantileMethods | None = None,
       5023 ) -> T_DataArray:
       5024     """Compute the qth quantile of the data along the specified dimension.
       5025 
       5026     Returns the qth quantiles(s) of the array elements.
       (...)
       5120        The American Statistician, 50(4), pp. 361-365, 1996
       5121     """
    -> 5123     ds = self._to_temp_dataset().quantile(
       5124         q,
       5125         dim=dim,
       5126         keep_attrs=keep_attrs,
       5127         method=method,
       5128         skipna=skipna,
       5129         interpolation=interpolation,
       5130     )
       5131     return self._from_temp_dataset(ds)
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/dataset.py:8035, in Dataset.quantile(self, q, dim, method, numeric_only, keep_attrs, skipna, interpolation)
       8029     if name not in self.coords:
       8030         if (
       8031             not numeric_only
       8032             or np.issubdtype(var.dtype, np.number)
       8033             or var.dtype == np.bool_
       8034         ):
    -> 8035             variables[name] = var.quantile(
       8036                 q,
       8037                 dim=reduce_dims,
       8038                 method=method,
       8039                 keep_attrs=keep_attrs,
       8040                 skipna=skipna,
       8041             )
       8043 else:
       8044     variables[name] = var
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/variable.py:2292, in Variable.quantile(self, q, dim, method, keep_attrs, skipna, interpolation)
       2288 axis = np.arange(-1, -1 * len(dim) - 1, -1)
       2290 kwargs = {"q": q, "axis": axis, "method": method}
    -> 2292 result = apply_ufunc(
       2293     _wrapper,
       2294     self,
       2295     input_core_dims=[dim],
       2296     exclude_dims=set(dim),
       2297     output_core_dims=[["quantile"]],
       2298     output_dtypes=[np.float64],
       2299     dask_gufunc_kwargs=dict(output_sizes={"quantile": len(q)}),
       2300     dask="parallelized",
       2301     kwargs=kwargs,
       2302 )
       2304 # for backward compatibility
       2305 result = result.transpose("quantile", ...)
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/computation.py:1207, in apply_ufunc(func, input_core_dims, output_core_dims, exclude_dims, vectorize, join, dataset_join, dataset_fill_value, keep_attrs, kwargs, dask, output_dtypes, output_sizes, meta, dask_gufunc_kwargs, *args)
       1205 # feed Variables directly through apply_variable_ufunc
       1206 elif any(isinstance(a, Variable) for a in args):
    -> 1207     return variables_vfunc(*args)
       1208 else:
       1209     # feed anything else through apply_array_ufunc
       1210     return apply_array_ufunc(func, *args, dask=dask)
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/computation.py:761, in apply_variable_ufunc(func, signature, exclude_dims, dask, output_dtypes, vectorize, keep_attrs, dask_gufunc_kwargs, *args)
        756     if vectorize:
        757         func = _vectorize(
        758             func, signature, output_dtypes=output_dtypes, exclude_dims=exclude_dims
        759         )
    --> 761 result_data = func(*input_data)
        763 if signature.num_outputs == 1:
        764     result_data = (result_data,)
    
    File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c1295c6b-8422-4d69-982b-173176ff6a3d/lib/python3.10/site-packages/xarray/core/variable.py:2286, in Variable.quantile.<locals>._wrapper(npa, **kwargs)
       2284 def _wrapper(npa, **kwargs):
       2285     # move quantile axis to end. required for apply_ufunc
    -> 2286     return np.moveaxis(_quantile_func(npa, **kwargs), 0, -1)
    
    File <__array_function__ internals>:4, in nanquantile(*args, **kwargs)
    
    TypeError: _nanquantile_dispatcher() got an unexpected keyword argument 'method'

**System (please complete the following information):**
 - Python version: [e.g. 3.8]
 - darts version u8darts                      0.26.0
pandas                       1.4.4
numpy                        1.21.5
Python 3.10.12

**Additional context**

**Comment by madtoinou** [comment]
Hi @levalencia,

I could not reproduce you issue with the code snippet below. Can you try to reproduce it with a synthetic dataset?

```python
import pandas as pd
from darts.datasets import AirPassengersDataset
series = AirPassengersDataset().load()
series = series.resample(freq="H")

# Determine the number of rows in the DataFrame
num_rows = len(series)

# Set aside a percentage of the rows for validation (e.g., 10%)
validation_percentage = 10  # Adjust as needed
num_validation_points = (validation_percentage * num_rows) // 100  # Calculate the number of validation points

# Set aside the calculated number of rows as a validation series
train, val = series[:-num_validation_points], series[-num_validation_points:]

from darts.models import ExponentialSmoothing

model = ExponentialSmoothing()
model.fit(train)
prediction = model.predict(len(val), num_samples=1000)
```
