### ISSUE TITLE
Cannot get the TFTExplainer to work when following tutorial as well as manually changing[BUG]

### ISSUE THREAD

**Issue by gvas7** [unit8co/darts#2007]
**Describe the bug**
Getting an error when trying to import TFTExplainer when using the directions for the model in the examples documentation.

**To Reproduce**
The code in the documents located [here ](https://unit8co.github.io/darts/examples/13-TFT-examples.html) advise to use the command `from darts.explainability import TFTExplainer`.  This leads to the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[c:\DS\darts_exp\km_darts\new](file:///C:/DS/darts_exp/km_darts/new) residential\nr_TFT.ipynb Cell 29 line 1
----> [1](vscode-notebook-cell:/c%3A/DS/darts_exp/km_darts/nr_TFT.ipynb#X22sZmlsZQ%3D%3D?line=0) from darts.explainability import TFTExplainer

ImportError: cannot import name 'TFTExplainer' from 'darts.explainability'
```

Further exploration shows that the module paths in of the package may have changed.  When I try this command to address the changes:
`from darts.explainability.tft_explainer import TFTExplainer` I get the following error:
`ImportError: cannot import name 'TFTExplainabilityResult' from 'darts.explainability'`

**Expected behavior**
I would expect when the import is run the TFTExplainer is available for use in a developed model without any import errors.

**System (please complete the following information):**
 - Python version: 3.10.2
 - darts version 0.26

**Additional context**
Is there better documentation for me to use here?  Or has something changed recently?  Thanks!

**Comment by dennisbader** [comment]
Hi @gvas7, can you verify that you indeed have darts version 0.26.0 installed?

```
print(darts.__version__)
```

Also sometimes installing darts in a fresh environment resolves these issues.

```
pip install darts==0.26.0
```

**Comment by gvas7** [comment]
Ok - I did a fresh install of it and restarted code and it worked.  Thanks for the suggestion!
