### ISSUE TITLE
Prediction varys when repeatedly call predict API

### ISSUE THREAD

**Issue by xlsi** [unit8co/darts#2017]
Hi Team,

The predictions vary a lot when I repeatedly call predict API. May I ask how to deal with it?

Thanks

**Comment by dennisbader** [comment]
Hi @xlsi, I assume you use a probabilistic model. Have a look at this answer [here](https://github.com/unit8co/darts/issues/1779#issuecomment-1559234091) which describes the reproducibility of the Darts models.

Deterministic models on the other hand always produce identical predictions for the same input.
