### ISSUE TITLE
Timeseries definitions precission

### ISSUE THREAD

**Issue by VincentMagn** [unit8co/darts#2018]
**Update time series definitions of guaranteed**
in the chapter, '*TimeSeries are guaranteed to:*', you said that '*Have a monotonically increasing time index, without holes (without missing dates)*'. 

I guess it should be said "*strictly monotonically*" otherwise, it does not assure that timestamps are uniques. 
And may also be added that it is unique.  

Hope it will be taken into account, kinds regards

**Comment by dennisbader** [comment]
Hi @VincentMagn and thanks for pointing this out. Yes, you are correct. Would you be willing to contribute with the changes?

**Comment by VincentMagn** [comment]
Hi, if it is enough to be mentions as contributor why not. Thank you, @dennisbader

**Comment by dennisbader** [comment]
It probably will not make it into the CHANGELOG.md but you will be automatically added to the Contributors tab on GitHub as soon as your PR gezs merged @VincentMagn. 
If that‘s okay with you let me know!

**Comment by VincentMagn** [comment]
Yes, perfect, thank you
