### ISSUE TITLE
Option to pass "smoothing_level" to ES model

### ISSUE THREAD

**Issue by nitesh4it** [unit8co/darts#2024]
**Is your feature request related to a current problem? Please describe.**
Yes, we are using ES model to predict the value of the timeseries, now when the next point is being predicted, it is giving a very high weightage to the last point(s). So say if there was a drop in actual data for the last 2 points only, the predicted value goes down

**Describe proposed solution**
Exponential smoothing model provides the option to pass "smoothing_level"  bounds which is not in Darts. If we get the option to pass this smoothing_level to ES via darts. It would probably resolve the issue. we can have a cap to restrict the weightage.

**Comment by dennisbader** [comment]
Hi @nitesh4it, and thanks for writing.

We support the `fit_kwargs` at model creation where you can add the `smoothing_level` see the Darts docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.exponential_smoothing.html#darts.models.forecasting.exponential_smoothing.ExponentialSmoothing) and the ES fit docs [here](https://www.statsmodels.org/stable/generated/statsmodels.tsa.holtwinters.ExponentialSmoothing.fit.html#statsmodels.tsa.holtwinters.ExponentialSmoothing.fit).

**Comment by nitesh4it** [comment]
Thanks for the suggestion. On further checking i found that we can pass a value as smoothing_level in the kw_args and that same value is picked
But what i meant to ask was, when i init ES model i do have the option to pass a range to it and an optimised value for smoothing_level is picked from that range. I wanted to have that bounds option in darts as well. Is that already supported? Am i missing something here?

es = ExponentialSmoothing(
            timeseries.values(),
            seasonal=model.model_params['seasonal'].value,
            trend=model.model_params['trend'].value,
            seasonal_periods=model.model_params['seasonal_periods'],
            freq=timeseries.freq,
            dates=timeseries.time_index,
            bounds={"smoothing_level": (0, 0.7)}
        )
        
I have the option to pass bounds={"smoothing_level": (0, 0.7)} in it. and an optimal value is then picked from the range

**Comment by nitesh4it** [comment]
@dennisbader @madtoinou

**Comment by madtoinou** [comment]
Hi @nitesh4it,

Please avoid pinging us with such a short delay after the last message.

The `bounds` parameter of the statsmodel implementation of Exponential smoothing is not exposed by Darts, but it could easily be implemented.

I am reopening this issue and will open an PR to address it soon.
