### ISSUE TITLE
historical_forecasts function in the TFT example code has an error

### ISSUE THREAD

**Issue by Hansol-S** [unit8co/darts#2025]
**Describe the bug**
When I run the example code for Air Passenger, the historical_forecasts function behaves strangely. The input data is clearly up to December 1960, but the backtest_series is only forecasting up to January 1960. Even when I try changing the forecast_horizon and stride, the forecast only goes to January 1960.

**To Reproduce**
See ./darts/examples/13-TFT-examples.ipynb on GitHub.

**Expected behavior**
Since the input data runs through December 1960, the forecast should also run through December 1960.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.26.0
 - numpy version: 1.24.1
 - pandas version: 2.1.1

**Comment by dennisbader** [comment]
Hi @Hansol-S, and thanks for pointing this out. This is indeed a bug and we'll fix it as soon as possible.

In the meantime, for this specific example you can set `overlap_end=True` when calling `historical_forecasts`, to get the expected results.
