### ISSUE TITLE
Multivariate Clarification

### ISSUE THREAD

**Issue by superichmann** [unit8co/darts#2026]
Hi, I saw the project and it is very interesting!

I tried to understand what exactly the multivariate capability is doing, it it just training a model foreach time series or as well sharing some learning between the time series?

Except for some comments on the documentation I couldn't find the answer so I post here :]

Thanks!

**Comment by madtoinou** [comment]
Hi @superichmann,

A model supporting multivariate series will be able to share learning across the components (columns) of the target series and will generate forecasts for all the columns at once during inference. Furthermore, a regression model that does not support it will wrapped in a sklearn `MultiOutputRegressor` under the hood and several models are effectively used.

I hope that it clarifies it, we will try to explicitly mention this aspect in the documentation.

**Comment by superichmann** [comment]
Hi thanks man :]

I might not have been fully clear in my question, what I meant is lets say you have 10 different time series that you group together in groups of 5, you have now 2 models, each model have 5 time series.

Will the 2 different models share information between each other? (now I am pretty sure the answer is no but would be nice to confirm ;))

**Comment by madtoinou** [comment]
Ok, so you do "multiple series" training, not "multivariate".

There is no explicit mechanism to make these two models share information, and depending on the series that you use to train each one of them, they might share similar features but there is absolutely no guarantee of that.

**Comment by superichmann** [comment]
again thanks! so inside the training of each group, the time series might share information between each other.

I am asking since I am working in c# and not python :[ but I cannot get same results as with darts (my benchmark is a kaggle competition)

I am banging my head against it, ultimately, I am using the same data and the same models so I cannot understand why its not the same score, trying to figure out what I am missing.

**Comment by superichmann** [comment]
Thanks @madtoinou , looking into it.

**Comment by superichmann** [comment]
Hi again @madtoinou, I have managed to understand the differences.

Now I noticed that darts is operating very fast even with large amount of lagged columns, how is that made possible? are the columns not being replicated in memory and just used from their original placement in the table?

Thanks so much for your answers ;]

**Comment by madtoinou** [comment]
Hi @superichmann,

The code relies on views of the underlying arrays to minimize the memory footprint and speed-up things. You can check the files in `darts/utils/data/` if you want to see how it's done.
