### ISSUE TITLE
Finer control of verbosity in historical forecasts

### ISSUE THREAD

**Issue by eivindeb** [unit8co/darts#2027]
**Is your feature request related to a current problem? Please describe.**
When calling model.historical_forecasts with verbose=True, Darts will output both an overall progress bar showing current number of predictions made vs total predictions (as desired), but also for each prediction that is made it will output a message: "Predicting DataLoader 0 ... " that will flood the logs and does not yield any useful information. The console / logs will therefore look like:

Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  8.72it/s]
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 100.27it/s]
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]
 19%|█▉        | 3/16 [00:08<00:36,  2.83s/it]

I want to be able to show the overall progress bar but not the progress bars for each individual prediction.

**Describe proposed solution**

The "Predicting DataLoader 0" message seems to stem from a pytorch lightning callback (pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar), which is automatically added to the pl.Trainer when verbose=True:

    def _setup_trainer(
        self,
        trainer: Optional[pl.Trainer],
        model: PLForecastingModule,
        verbose: Optional[bool] = None,
        epochs: int = 0,
    ) -> pl.Trainer:
        """Sets up a PyTorch-Lightning trainer (if not already provided) for training or prediction."""
        if trainer is not None:
            return trainer

        trainer_params = {key: val for key, val in self.trainer_params.items()}
        if verbose is not None:
            trainer_params["enable_model_summary"] = (
                verbose if model.epochs_trained == 0 else False
            )
            trainer_params["enable_progress_bar"] = verbose   <---- HERE

        return self._init_trainer(trainer_params=trainer_params, max_epochs=epochs) 
        
While the model.predict_from_dataset function containing the call to _setup_trainer does accept a trainer argument such that _setup_trainer would return the user provided trainer, model.historical_forecasts does not take a trainer argument and simply calls model.predict_from_dataset (through other wrapper/helper functions) with trainer=None and verbose equal to the verbose argument given to model.historical_forecasts. Thus, there is no way to get just the progress bar in model.historical_forecasts but not the "Predicting DataLoader 0:" message from each prediction.

One solution could be that _setup_trainer checks if the self.trainer argument is not None, allowing the user to configure the trainer as desired and setting model.trainer before calling historical_forecasts:

    def _setup_trainer(
        self,
        trainer: Optional[pl.Trainer],
        model: PLForecastingModule,
        verbose: Optional[bool] = None,
        epochs: int = 0,
    ) -> pl.Trainer:
        """Sets up a PyTorch-Lightning trainer (if not already provided) for training or prediction."""
        if trainer is not None:
            return trainer
        elif self.trainer is not None:  (or should it be model.trainer?)
            return self.trainer
        ....

**Describe potential alternatives**
Otherwise, one could differentiate verbosity levels. E.g. verbose=1 for just the overall progress bar and verbosity=2 for additional / full information, including the progress bar for each prediction. This could be implemented by having the main historical_forecasts function only passing the verbose argument along if verbose > 1

A third solution could be that model.historical_forecasts could accept a trainer argument that it passes along, but seeing as many models do not use a pl.Trainer this does not seem like a good solution.

**Additional context**

**Comment by dennisbader** [comment]
Hi @eivindeb, we actually just merged a PR this morning that adds the `darts.utils.callbacks.TFMProgressBar` where you can customize verbosity for training, validation, prediction at model creation.

This will ship with the next darts release.

**Comment by eivindeb** [comment]
Awesome! I will close this issue for now and see if the new callback satisfies my needs then :)
