### ISSUE TITLE
[KalmanForecast] Needs more detail explanation

### ISSUE THREAD

**Issue by Monica2511** [unit8co/darts#2041]
I tested the KalmanForecaster model and its results were actually better than expected. I'm quite confused about how it actually works or in other words the theory behind it. I have read about Kalman Filter, it is not a simple theory, (I am still in the process of learning it). I would like a brief explanation of 
1. The idea of why we use the kalman filter here 
2. With future covariates, how do we include it in the model? Use future covariates as control vector u_t?
3. Do we only use 1 Kalman filter for multi-step forecasting? Is the strategy here recursive forecasting?
4. What is the mission of the N4SID algorithm? 
![image](https://github.com/unit8co/darts/assets/46559607/e07808aa-8f0d-46b8-8662-66fa4723beb6)

**Comment by PeterPirog** [comment]
@Monica2511  This is the best explanation of kalman filter I have found in Youtube. It has 55 parts and each step is explained in details. I can recommend if  You want to understand how kalman filter works in each single step:
[Special Topics - The Kalman Filter (1 of 55) What is a Kalman Filter?](https://www.youtube.com/watch?v=CaCcOwJPytQ&list=PLk4mwFjvagV3NdW8nsVS7Sr1WJjCw2npD&index=1)
