### ISSUE TITLE
[BUG] NaiveEnsemble - Model Trained w/o Future Covariates Error

### ISSUE THREAD

**Issue by negodfre** [unit8co/darts#2053]
**Describe the bug**
When using NaiveEnsembleModel with future covariates, it errors and states that the model wasn't trained with them even though the future covariates were passed into the fit() method.

**To Reproduce**
```from typing import List
import numpy as np

from darts import TimeSeries
from darts.models import StatsForecastAutoARIMA, StatsForecastAutoETS, NaiveEnsembleModel

# Create Dummy Data

shift = np.zeros((64,))
shift[18:] = 1

x = np.random.normal(size=(36,))
x[18:] += 10

ts = TimeSeries.from_values(x)
ts_shift = TimeSeries.from_values(shift)

# This Works
model = StatsForecastAutoARIMA(season_length=12, seasonal=True)
model.fit(ts,
          ts_shift)

# This Errors Out
models = [StatsForecastAutoARIMA(season_length=12, seasonal=True),
          StatsForecastAutoETS(season_length=12, model='ZAA')]
model = NaiveEnsembleModel(models)
model.fit(ts,
          future_covariates=ts_shift)

ts.plot()
model.predict(12, future_covariates=ts_shift).plot()
```

**Expected behavior**
I expected a NaiveEnsembleModel of both models averaged together using the future covariate information

**System (please complete the following information):**
 - Python version: [3.9]
 - darts version [0.24.0]

**Additional context**
Is this a bug or do you need to pass the future covariates differently with the NaiveEnsembleModel?

**Comment by madtoinou** [comment]
Hi @negodfre,

The bug fix was released in 0.25.0, I just checked with 0.26.0 and the code snippet ran just fine. Can you update Darts and see if the problem persists?
