### ISSUE TITLE
Seeking Advice on Modeling Systolic and Diastolic Blood Pressure with Exogenous Variables

### ISSUE THREAD

**Issue by PeterPirog** [unit8co/darts#2055]
Hello,

I'm currently working on predicting future values for systolic and diastolic blood pressure (SBP and DBP). I have collected a dataset comprising approximately 200 multivariate time series instances, and I'm looking to incorporate the following exogenous variables into the model:

    Pulse (as a time series)
    Age (numerical)
    Gender (numerical/categorical)
    Additional categorical variables

Based on initial analysis, there's a significant correlation and covariance between SBP, DBP, and pulse rates.

I'm interested in constructing confidence intervals for the predicted values of SBP and DBP. I would appreciate any insights or suggestions on how to effectively integrate these exogenous factors into the predictive model.

Here are some specific points where I’m seeking guidance:

**Model Selection:** I'm considering a Vector Autoregressive Integrated Moving Average (VARIMA) model to start with. Would this be a suitable choice given the nature of the data? Are there other models you would recommend that are robust to multivariate time series forecasting, especially in medical data contexts?

**Probabilistic Approach:** I'm also looking for probabilistic methods to address this problem. Usually, I use TensorFlow Probability for machine learning tasks; however, I feel my dataset might be too small for this approach. Could you suggest alternative probabilistic frameworks or methodologies that are well-suited for limited datasets?

**Incorporating Exogenous Data:** What are the best practices for including exogenous variables like pulse, age, and gender in time series forecasting models? Any examples or references to similar work would be extremely helpful.

**Handling Small Datasets:** Since the data is relatively limited, what techniques would you recommend for ensuring the robustness of the predictions?

Any advice, resources, or pointers towards relevant literature would be immensely helpful.

Thank you for your time and assistance

**Comment by madtoinou** [comment]
Hi @PeterPirog,

Sorry for the delay, I wanted to take the time to properly answer your questions.

**Model selection** : Statistical models are a good start, I would definitely recommend trying regression models as well ([example notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html))

**Probabilistic forecasting** : You can easily make regression models probabilistic using the `likelihood` parameter. Some of statistical models also support probabilistic forecasting (see table in the [README](https://unit8co.github.io/darts/index.html#forecasting-models)), there is this [example notebook](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Probabilistic-forecasts)

**Exogenous data** : They are called covariates in Darts, you can find examples [here](https://unit8co.github.io/darts/userguide/covariates.html) and [there](https://unit8co.github.io/darts/examples/15-static-covariates.html?highlight=static#Static-Covariates)

For the ones you explicetly mentioned, I would do the following:
- Pulse : past covariates, you cannot know it in advance for the period you're trying to forecast
- Age (numerical) : static covariate
- Gender (numerical/categorical) : static covariate
- Additional categorical variables : static covariate

**Small datasets** : Make sure to use reasonably small models to make sure to not overfit and use train/validation/test split. Apply the usual good practice of data science.

I would recommend going through some the example notebooks that are available in the documentation, starting with the [Quickstart](https://unit8co.github.io/darts/quickstart/00-quickstart.html) as it could give you ideas on how to tackle your problem.
