### ISSUE TITLE
Progress bar for historical forecast does not show

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2061]
I have updated my darts version to the latest version: 
![image](https://github.com/unit8co/darts/assets/59031005/4239be84-f604-4555-8527-673a02d98894)

According to what I was told in another thread, to print out the progress bar, "I need to set verbose=False when calling fit() and then, set verbose=True when calling historical_forecasts()."

However when I try to add verbose = False to my fit(), it gives the error below:
![image](https://github.com/unit8co/darts/assets/59031005/a3ef55ce-7ae5-49a0-8ae4-79f33fd9b7e7)
![image](https://github.com/unit8co/darts/assets/59031005/1b0311e7-eafe-47d3-8d73-db610aa9b267)

Am I running something wrongly?

**Comment by dennisbader** [comment]
Hi @ETTAN93, since optimized historical forecasts for regression models, there is no longer a progress bar displayed.
If you still want to see the progress bar at the cost of computational time, you can set `enable_optimization=False` when calling historical forecasts.

@madtoinou, we could include the progress bar in the optimized subroutine at least for displaying the progress when using multiple series?

**Comment by ETTAN93** [comment]
@dennisbader thanks for clarifying. Is there not a way to include some sort of progress bar even with the optimized method? Some historical forecasts takes a while and it makes it a lot harder to determine how long it's going to take without the previous progress bar that was quite convenient

**Comment by dennisbader** [comment]
It would only be possible if you pass multiple timeseries and we could show the progress by the how many series were already processed.

Since the operation is vectorized now, we can not show the progress for a single series anymore.

**Comment by madtoinou** [comment]
@dennisbader Yup, no problem, should be trivial to implement a progress bar when there are several series.

@ETTAN93 `verbose` is only supported by `TorchForecastingModel.fit()`, `RegressionModel` verbosity is usually defined in the constructor. 

What is approximately the size of the series you are forecasting and how long does it take (with `forecast_horizon<output_chunk_length and retrain=False`)?

**Comment by dennisbader** [comment]
Hmm.. That seems suspiciously slow for historical forecasts with a pretrained regression model (optimized with `forecast_horizon < output_chunk_length`) with the settings you shared in your code snippet.

Can you maybe share how you create the model and how you call historical forecasts?

**Comment by dennisbader** [comment]
Just tested below code on my machine following your description (2 years training data, 1 year validation data - both 15 minutes frequency). Result in a total process time of 1.86 seconds.

```
import time

import pandas as pd

from darts.utils.timeseries_generation import sine_timeseries
from darts.models import LinearRegressionModel

st = time.time()
series_train = sine_timeseries(start=pd.Timestamp("2000-01-01"), end=pd.Timestamp("2002-01-01"), freq="15T")
series_val = sine_timeseries(start=pd.Timestamp("2002-01-01"), end=pd.Timestamp("2003-01-01"), freq="15T")

model = LinearRegressionModel(
    lags=[-1],
    lags_future_covariates=[-2, -1, 0],
    output_chunk_length=24,
    n_jobs=-1,
)

model.fit(series_train, future_covariates=series_train)
preds = model.historical_forecasts(
    series=series_val,
    future_covariates=series_val,
    retrain=False,
    forecast_horizon=24,
)
print(time.time() - st)


```

**Comment by ETTAN93** [comment]
@dennisbader 

In my actual use case, I just double checked and I have:
i. 18 future covariates
ii. 37 past covariates. 
iii. All data is at 15min granularity.
iv. 3 years of training data and 1.5 years of test data

It takes around 1min or so for the historical forecast itself which I guess is expected for that amount of data?

The other time in the initially mentioned 10 min was actually due to another procedure.



`

**Comment by dennisbader** [comment]
Hi @ETTAN93, I still think it's rather slow:

I reproduced your setup (I assume you have samiliar lags/output_chunk_lenght as described at the beginning of the issue)

```
import time

import pandas as pd

from darts import concatenate
from darts.utils.timeseries_generation import sine_timeseries
from darts.models import LinearRegressionModel

st = time.time()

# reproduce 3 years training series, 1.5 years validation
series_train = sine_timeseries(start=pd.Timestamp("2000-01-01"), end=pd.Timestamp("2003-01-01"), freq="15T")
series_val = sine_timeseries(start=pd.Timestamp("2003-01-01"), end=pd.Timestamp("2004-07-01"), freq="15T")

# past covariates with 37 features
past_covs_train = concatenate([series_train] * 37, axis=1)
past_covs_val = concatenate([series_val] * 37, axis=1)

# future covariates with 18 features
future_covs_train = concatenate([series_train] * 18, axis=1)
future_covs_val = concatenate([series_val] * 18, axis=1)

model = LinearRegressionModel(
    lags=[-1],
    lags_future_covariates=[-2, -1, 0],
    lags_past_covariates=[-2, -1],
    output_chunk_length=24,
    n_jobs=-1,
)

model.fit(
    series_train,
    past_covariates=past_covs_train,
    future_covariates=future_covs_train
)

st_hfc = time.time()
preds = model.historical_forecasts(
    series=series_val,
    past_covariates=past_covs_val,
    future_covariates=future_covs_val,
    retrain=False,
    forecast_horizon=24,
)
end_time = time.time()

print("len train", len(series_train), "len test", len(series_val))
print("n past covariates features", past_covs_train.n_components)
print("n future covariates features", future_covs_train.n_components)
print("n model features", len(model.lagged_feature_names))
print("predicted steps", len(preds))
print("total time", end_time - st)
print("hfc time", end_time - st_hfc)
```

This prints (historical fc time: roughly 0.05 seconds):

```
len train 105217 len test 52513
n past covariates features 37
n future covariates features 18
n model features 129
predicted steps 52488
total time 2.5120739936828613
hfc time 0.05277204513549805
```

**Comment by ETTAN93** [comment]
@dennisbader the lags that I used are:
forecast_horizon = 3
target_lags = None
past_cov_lags = list(range(-8, 0))
future_cov_lags = list(range(-22, 21))
