### ISSUE TITLE
Odd Behaviour with new dictionary format to define lags

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2062]
I am trying out the new dict format to define lags in the latest version of darts: 0.26.0

However, there seems to be some odd behaviour which I can't figure out why:

The way I define my covariates and the data:
![image](https://github.com/unit8co/darts/assets/59031005/5f572b00-3939-4919-808c-529de395acdb)

The way the model and lags are initialized:
![image](https://github.com/unit8co/darts/assets/59031005/9bae778f-aecb-409c-b34e-751f89ed1c89)

The way historical forecast is run:
![image](https://github.com/unit8co/darts/assets/59031005/3fd72a0c-b0fa-4b9c-aff9-f1f2d71bb39a)

This works completely fine when I define the lags in this way. 

However, when I take out any features from the dataset as well the lags, e.g.
![image](https://github.com/unit8co/darts/assets/59031005/e6ed3d8d-ad1b-437b-8208-3168acd5d15f)
![image](https://github.com/unit8co/darts/assets/59031005/241bcec5-e4c5-4c8d-a385-37f91a862752)

I get an error:
![image](https://github.com/unit8co/darts/assets/59031005/b2458542-d365-4f96-ba15-ecb7b517a516)

**Comment by dennisbader** [comment]
Hi @ETTAN93, can you provide a minimal reproducible example that we can run to reproduce the bug (e.g. not a picture, and code to recreate the time series, you can use TimeSeries.from_times_and_values() to generate some example series)?

Also, we might have fixed this bug in #2040 that resolved a similar issue.

**Comment by dennisbader** [comment]
Yes, we aim to release within the next 1-2 weeks.

**Comment by ETTAN93** [comment]
@dennisbader Please see below the code example of my reproduced error. Seems like it is not taking into account the future cov lags at 0 when it is calculating the number of features X is providing 
`import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import LinearRegressionModel

dates = pd.date_range(start='2020-08-30 10:00:00', end='2020-09-01 11:00:00', freq='1H')

feature_1 = np.random.randint(1,10,50)
feature_2 = np.random.randint(1,10,50)
feature_3 = np.random.randint(1,10,50)
target = np.random.randint(1,10,50)

data_df = pd.DataFrame({'feature1': feature_1, 
                        'feature2': feature_2, 
                        'feature3': feature_3, 
                        'target': target}, index = dates)

target_series = TimeSeries.from_dataframe(data_df[['target']])
future_cov_series = TimeSeries.from_dataframe(data_df[['feature1', 'feature2', 'feature3']])

start_date = pd.Timestamp("2020-08-30 10:00:00")
split_date = pd.Timestamp("2020-08-31 20:00:00") 
end_date = pd.Timestamp("2020-09-01 11:00:00")
test_set_start_date =  split_date + relativedelta(hours = 1)

target_series_sample = target_series.slice(start_date, end_date)
future_cov_sample = future_cov_series.slice(start_date, end_date)
target_series_fit = target_series.slice(start_date, split_date)
future_cov_fit = future_cov_series.slice(start_date, split_date)

lr_model = LinearRegressionModel(
    lags = [-1],
    lags_future_covariates= {
        'feature1': [-2, -1, 0], 
        'feature2': [-1, 0], 
        'feature3': [-3, -2, -1, 0], 
    },
    lags_past_covariates=None,
    output_chunk_length = 24,
    n_jobs=-1,
    random_state=42,
    multi_models=True
)

lr_model.fit(
    series = target_series_fit,
    future_covariates = future_cov_fit,
)

hf_results = lr_model.historical_forecasts(
    series = target_series_sample, 
    past_covariates = None,
    future_covariates = future_cov_sample,
    start = test_set_start_date, 
    retrain = False,
    forecast_horizon = 2,
    stride = 1,
    train_length = None,
    verbose = True,
    last_points_only = False,
)`

**Comment by madtoinou** [comment]
I just checked on the master branch, #2040 indeed fixes this problem and will be part of the next release.

Closing this issue, don't hesitate to reopen if it persists after updating darts to the latest version after the release.
