### ISSUE TITLE
Understanding probabilistic forecasting and num_samples

### ISSUE THREAD

**Issue by SaltedfishLZX** [unit8co/darts#2066]
Hi, considering the requirements of my work, I am interested in obtaining the prediction interval for my forecasting, and this project helps me a lot.

As someone new to the field of probabilistic forecasting, I find myself puzzled about the rationale behind using "num_samples" and how it works. Taking quantile regression as an example, it appears that we can obtain results directly at each quantile, and it seems unnecessary to employ sampling.

I would greatly appreciate it if you could recommend some papers that is helpful to understand probabilistic forecasting in Darts. Thank you.

**Comment by dennisbader** [comment]
Hi, @SaltedfishLZX, the probabilistic forecasting works like this:

For local forecasting models (all models except regression models and torch forecasting models):
- we use the model's native probabilistic support if available. Probabilistic forecasting is enabled with `num_sample > 1`.

For regression models and torch forecasting models:
- we  fit the the likelihood/distribution parameters that was set using `likelihood` at model creation. Then we offer two ways of probabilistic forecasting:
  - when `num_samples > 1` we use Monte Carlo sampling to generate samples based on the fitted distribution parameters.
  - directly return the fitted distribution parameters `predict_likelihood_parameters=True` when calling `predict()`

**Comment by SaltedfishLZX** [comment]
> Hi, @SaltedfishLZX, the probabilistic forecasting works like this:
> 
> For local forecasting models (all models except regression models and torch forecasting models):
> 
> * we use the model's native probabilistic support if available. Probabilistic forecasting is enabled with `num_sample > 1`.
> 
> For regression models and torch forecasting models:
> 
> * we  fit the the likelihood/distribution parameters that was set using `likelihood` at model creation. Then we offer two ways of probabilistic forecasting:
>   
>   * when `num_samples > 1` we use Monte Carlo sampling to generate samples based on the fitted distribution parameters.
>   * directly return the fitted distribution parameters with `predict_likelihood_parameters=True` when calling `predict()`

Thank you for your reply. I have another question: How can Monte Carlo sampling be employed in the quantile method? Is it necessary to assume a default distribution?

**Comment by PeterPirog** [comment]
@SaltedfishLZX  I'm not experienced in pytorch  because I focused on tensorflow but I can recommend You some some useful sources about probabilistic deep learning:
1. [Probabilistic Deep Learning With Python, Keras and TensorFlow Probability](https://www.manning.com/books/probabilistic-deep-learning?gclid=EAIaIQobChMIwLCq88b24wIVgUOGCh2NLwMcEAYYASABEgJ1ufD_BwE) - great book about probabilistic deep learning
2. [MIT 6.S191: Evidential Deep Learning and Uncertainty](https://www.youtube.com/watch?v=toTcf7tZK8c)  and github [repo](https://github.com/aamini/evidential-deep-learning) for it

**Comment by SaltedfishLZX** [comment]
> @SaltedfishLZX I'm not experienced in pytorch because I focused on tensorflow but I can recommend You some some useful sources about probabilistic deep learning:
> 
> 1. [Probabilistic Deep Learning With Python, Keras and TensorFlow Probability](https://www.manning.com/books/probabilistic-deep-learning?gclid=EAIaIQobChMIwLCq88b24wIVgUOGCh2NLwMcEAYYASABEgJ1ufD_BwE) - great book about probabilistic deep learning
> 2. [MIT 6.S191: Evidential Deep Learning and Uncertainty](https://www.youtube.com/watch?v=toTcf7tZK8c)  and github [repo](https://github.com/aamini/evidential-deep-learning) for it

Thanks! these sources are helpful
