### ISSUE TITLE
What other variables need to be passed to the TFTExplainer

### ISSUE THREAD

**Issue by gvas7** [unit8co/darts#2071]
I am trying to run a TFTExplainer in an Optuna callback.  I did this with Shap and the linear regression models and had no issue.  I created an Optuna callback like this for Shap:
```
def print_callback(study, trial):
    trial_value = trial.values
    mape, backtest_mape = trial_value[0], trial_value[1]
    model = trial.user_attrs['model']
    hf.shap_LR_explainer(model)
```
And shap_LR_explainer is a function that runs the boilerplate shap code I find throughout the docs.

However when I do the same thing and pull the model out through a `trial.user_attrs` for TFT:
```
def print_callback(study, trial):
    trial_value = trial.values
    mape, backtest_mape = trial_value[0], trial_value[1]
    model = trial.user_attrs['model']
    explainer = TFTExplainer(model)
    results = explainer.explain()
    explainer.plot_variable_selection(explainability_result)
```
I get the following error:
`AttributeError: 'NoneType' object has no attribute 'set_predict_parameters'`
I'm not clear what other attributes I should grab from the study so that they can be passed to the explainer?  I have tried this outside the study and the callback in the main workbook and the explainer works fine.  I looked at the code for the `set_predict_parameter` but not sure what it is missing.

If this is the wrong way to approach let me know.  Thank you.

Using Darts 0.26
Using Python 3.10.2

**Comment by dennisbader** [comment]
Hi @gvas7, can you provide a minimal reproducible example so we can investigate?
