### ISSUE TITLE
Is possible to add STL and MSTL  forecast models?

### ISSUE THREAD

**Issue by PeterPirog** [unit8co/darts#2074]
Is possible to add [STL](https://www.statsmodels.org/devel/generated/statsmodels.tsa.seasonal.STL.html#statsmodels.tsa.seasonal.STL) and [MSTL](https://www.statsmodels.org/devel/generated/statsmodels.tsa.seasonal.MSTL.html#statsmodels.tsa.seasonal.MSTL) forecast  models in darts?
These models are very useful to find trend and seasonality for univariate time series.
STL is for single seasonality and MSTL is for multiple seasonalities.

STL [decomposition](https://www.statsmodels.org/devel/generated/statsmodels.tsa.seasonal.seasonal_decompose.html#statsmodels.tsa.seasonal.seasonal_decompose) with ARIMA model can be used for [forecasting](https://www.statsmodels.org/dev/generated/statsmodels.tsa.forecasting.stl.STLForecast.html)

In some tasks is important to separate trend and seasonality to detect general direction of the process.

**Comment by madtoinou** [comment]
Hi @PeterPirog,

STL and MSTL are already implemented and accessible in the `extract_trend_and_seasonality()` method ([documentation](https://unit8co.github.io/darts/generated_api/darts.utils.statistics.html?highlight=stl)).

**Comment by PeterPirog** [comment]
@madtoinou , Thank You very much.
