### ISSUE TITLE
[BUG] The result of N-BEATS and N-HITS is not reproducible

### ISSUE THREAD

**Issue by timofeytkachenko** [unit8co/darts#2076]
I trained the model and  used the **historical_forecasts** method to predict the validation series and after it I used method **predict** to do the same and had different results. with different R2 and MAPE. I dont understand the reason why it works like that.

pred_series = model_nbeats.historical_forecasts(
    series_scaled,
    start=split_date,
    forecast_horizon=10,
    stride=10,
    last_points_only=False,
    retrain=False,
    verbose=False,
)
pred_series = concatenate(pred_series)

<img width="772" alt="historical_forecasts" src="https://github.com/unit8co/darts/assets/49156804/708f8fcd-03c8-48c1-9260-6ec6cdb689aa">

forecast = model_nbeats.predict(n=len(val_scaled))

<img width="772" alt="predict" src="https://github.com/unit8co/darts/assets/49156804/8557b86c-1c49-477b-82df-adc7de9c8a0c">

**Comment by madtoinou** [comment]
Hi @timofeytkachenko,

These two methods don't have to the same logic, which is detailed in their respective docstring:
- `predict()` is used to forecast `n` values after the end of the provided `series`. If `n>output_chunk_length`, the function will rely on auto-regression (consume its own forecasts) to generate the remaining time steps.
- `historical_forecasts()` is used to mimic how the model would have performed if it was trained "in the past" and used to forecast a `series` over time. After each forecast, the ground-truth is made available to the model for the next forecast (limited auto-regression, only if `forecast_horizon>output_chunk_length`). Performance is expected to be better.

I hope that the difference is clearer.

**Comment by timofeytkachenko** [comment]
Thank you in advance
