### ISSUE TITLE
Time Series slicing with Stride

### ISSUE THREAD

**Issue by MohammadHaidarAW** [unit8co/darts#2084]
Hello, 
I am new to Darts and I am trying to use time series models to fit my data which is sampled on quarter-hours (15 minutes).

Lets assume my time series is one dimensional with length n*96 meaning n days. 
I want to use  input_chunk_length=96*7 which is one week, and output_chunk_length=96 which is one day. But my problem is that I want the slicing to have strides=96 instead of shifting by one sample to create the slices. 
The reason is that I want every input and output to start at the beginning of the day.

**Comment by dennisbader** [comment]
Hi @MohammadHaidarAW, you are referring to model training, right?

For training, this is currently not possible out of the box. Only for our `TorchForecastingModels` (the neural network-based models) you could define a new `TrainingDataset` with the desired logic and then pass it to `TorchForecastingModel.fit_from_dataset()`.

**Comment by MohammadHaidarAW** [comment]
Thank you for the reply!
I think I have to fit from dataset then.
