### ISSUE TITLE
[BUG] how to set mc_dropout for historical_forecasts

### ISSUE THREAD

**Issue by SaltedfishLZX** [unit8co/darts#2097]
I am attempting to enable Monte Carlo Dropout for predictions in TFT. I have configured the `predict_kwargs` parameter for `historical_forecasts` as follows:

```
predict_kwargs={
    "mc_dropout": True,
}
predict_series = my_model.historical_forecasts(test_series[target_val],retrain=False,num_samples=2,predict_kwargs=predict_kwargs)
```

However, the results indicate that the samples are the same. And after executing the code multiple times there is still no any variation.

I have two specific questions:
1. How should I properly set up Monte Carlo Dropout (mc_dropout)?
2. When using historical_forecasts with `num_samples > 1` and `mc_dropout = True`, should I expect to obtain different samples in each run?

**Comment by dennisbader** [comment]
Hi @SaltedfishLZX, and thanks for raising this issue. It's indeed a bug as the mc_dropout won't get passed to the model's `predict()` method.

We'll have a fix soon.
