### ISSUE TITLE
Covariates with mixed frequencies.

### ISSUE THREAD

**Issue by mg10011** [unit8co/darts#2098]
**Is your feature request related to a current problem? Please describe.**
I don't know if this feature is available or not.  To my knowledge perusing the documentation, it is not, so I will ask for it.  Is it possible to have the main time series be a univariate daily series that has calendar days ('B') as its frequency and many past covariates and future covariates:
  -- some of the past covariates are also daily data with the same frequency as the main data series.
  -- some of the past covariates are measured and sampled only on a weekly, monthly, or quarterly basis
  -- some of the future covariates, like day of the week or day of the month are sampled daily, including non-business days.
  
Please let me know if your library can handle this.

**Describe proposed solution**
A way to downsample the covariates (from monthly to daily, for example) where it is impossible to "peak ahead".

**Comment by dennisbader** [comment]
Hi @mg10011. In Darts, you need to convert all series (`past_covariates` and `future_covariates`) to the same frequency as your target `series`.  

prior to creating a time series, you can do some preprocessing (e.g. with pandas):
- for data with daily frequency, you could exclude weekends and non business days.
- for lower frequency data (weekly, monthly, ...) you would have to upsample to "B" frequency
- for converting from higher frequency to lower frequency, we recently added the MIDAS transformer (see  Is it possible for the model to make predictions over the training period?)

**Comment by dennisbader** [comment]
Closing, as MIDAS was added in #1820
