### ISSUE TITLE
numpy version incompatibility using Darts and Tensorflow

### ISSUE THREAD

**Issue by alexiaatidot** [unit8co/darts#210]
DARTS depends on numpy 1.19.0 and Tensorflow requires numpy<1.19.0 

If DARTS will require numpy<1.19.0 it will be possible to have DARTS and Tensorflow in the same environment.

**Comment by LeoTafti** [comment]
Hi @alexiaatidot 

We'll have to check that requiring numpy<1.19.0 doesn't break anything first, but we'll try to address it. Thanks for reporting!
