### ISSUE TITLE
Applying sample weights to the training process

### ISSUE THREAD

**Issue by zhoujs93** [unit8co/darts#2107]
**Is your feature request related to a current problem? Please describe.**
A clear and concise description of what the problem is.

Hi, I was wondering if its possible to provide sample weights of certain observations when making predictions

**Describe proposed solution**
A clear and concise description of what the library should provide to solve missing functionality.

Providing sample weights to the training function 

**Describe potential alternatives**
A clear and concise description of any alternative solutions or existing features that might solve it.

**Additional context**

**Comment by madtoinou** [comment]
Hi @zhoujs93,

This feature is already tracked by issue #1175, where some workarounds are also shared.

I started working on it but the end of the year is quite busy and I have to find more time in order to finish it.

**Comment by zhoujs93** [comment]
> Hi @zhoujs93,
> 
> This feature is already tracked by issue #1175, where some workarounds are also shared.
> 
> I started working on it but the end of the year is quite busy and I have to find more time in order to finish it.

Hi are you referring to this post ? 

https://github.com/unit8co/darts/issues/1175#issuecomment-1744613535

It’s not very clear how I should go about applying weights in this case. 

Thanks !
