### ISSUE TITLE
How to use darts libraries with PySpark?

### ISSUE THREAD

**Issue by AyushBhardwaj321** [unit8co/darts#2111]
Hello all,
I'm trying to integrate darts library with PySpark session to make my application perform time-series prediction in parallelism.
I referred this blog [Time-Series Forecasting with Spark and Prophet](https://medium.com/@y.s.yoon/scalable-time-series-forecasting-in-spark-prophet-cnn-lstm-and-sarima-a5306153711e) inplace of Prophet i was trying using darts.

Is this a good approch? or any other suggestion for prediction in parallelism ?

**Comment by madtoinou** [comment]
Hi @AyushBhardwaj321,

The steps describe with this blog article can also be used with Darts, there is not difference. You might just need to add some logic to convert the `spark.dataframe` into a `TimeSeries`.
