### ISSUE TITLE
Static covariates with an array of multivariate time series

### ISSUE THREAD

**Issue by matteoarcangeli99** [unit8co/darts#2117]
Good morning,

I am looking to train a Tide model using an array of multivariate series, each with varying columns. In addition, I need to define static covariates for each series.
However, I need help inputting static covariates into the different sequences and training the model due to different column numbers. To resolve this issue, I have coded the static covariates as future covariates.

Is this the correct approach?

Thank you

**Comment by matteoarcangeli99** [comment]
> Hi @matteoarcangeli99,
> 
> What do you mean by "varying columns"? Do you have several multivariate series with a different number of components?
> 
> Since `TiDE` supports static covariates (as per the [models table](https://github.com/unit8co/darts#forecasting-models)), they should be stored in the corresponding attribute of the `TimeSeries`, using the `with_static_covariates()` method ([doc](https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=with_static#darts.timeseries.TimeSeries.with_static_covariates). Passing them as `future_covariates` would work but is not ideal (should eventually be considered for models that do not support the static covariates).

Yes, I have got  several multivariate series with a different number of components, so when i try to train the model I have this error
`ValueError: Concatenation of multiple TimeSeries with static covariates requires all `static_covariates` DataFrames to have identical columns (static variable names), and the number of each TimeSeries' components must match the number of corresponding static covariate components (the number of rows in `series.static_covariates`).`

**Comment by matteoarcangeli99** [comment]
> The `TimeSeries` used to train a single model must have the same number of components (they can theoretically correspond to different "amount/variables", but this is not recommended). You can think of it like a regression problem: all the samples must have the same number of features (in the same order) or there will be an ambiguity when fitting/applying the model's weights.
> 
> You could solve this issue by grouping the series by number of components, then training one model for each or identify components shared across all the series, separate them from the target series and using them as covariates for example.
> 
> If you don't mind sharing your code snippet (with dummy data of appropriate shape), I could try to see if the problem arise from something else.

Thank you for your response. The issue I am facing is that each time series has different dimensions. 

In some cases, specific columns are not present because no value has been entered. I wonder if it's possible to insert 'n' columns with a value of 0 to account for missing data or if this would compromise accuracy by introducing too many NaNs. The data structure underlying each series is the same; it's just that, in some cases, several fields remain unassigned.

**Comment by madtoinou** [comment]
Introducing empty columns like this is very likely to compromise the accuracy (even with model capable of handling `NaNs`), it would probably be better to only keep the columns that are common across all the time series.

**Comment by matteoarcangeli99** [comment]
> Introducing empty columns like this is very likely to compromise the accuracy (even with model capable of handling `NaNs`), it would probably be better to only keep the columns that are common across all the time series.

Unfortunately, I can't have the same components in each time series; therefore, in your opinion, is it better to use static covariates properly adding many nans, or use them as future covariates?

**Comment by madtoinou** [comment]
Since this is outside of the intended use of the model (as you have different components across series), I would not be able to provide any recommendation.
