### ISSUE TITLE
Cannot get val_series to work whilst using past_covariates

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2118]
Hello there. this is the first time for me to make a github issue. Since the response here seems to be very good i decided to give it a shot!

Ok so  i will show what i think is the relevant code. I have tried numerous different combinations but none of them have worked so clearly I am missing something. I always get the same error:

edfs.head(3) # this shows:
<html><body>

  | Interval_Sum | GreenInterval_Sum | KWh_total | RedInterval_Sum | dt
-- | -- | -- | -- | -- | --

0.047759 | 0.0 | 0.000000 | 0.092251 | 2022-03-04 12:00:00
0.096301 | 0.0 | 0.000038 | 0.149446 | 2022-03-04 13:00:00
0.119789 | 0.0 | 0.000080 | 0.177122 | 2022-03-04 14:00:00

</body>
</html>

# convert dataFrame to darts timeseries object
ts = TimeSeries.from_dataframe(edfs, 'dt', ['Interval_Sum', 	'GreenInterval_Sum',
                                    'KWh_total', 	'RedInterval_Sum'])

# if you want to train on less data
ts = ts.drop_before(pd.Timestamp("2023-02-01"))

# if you want to use validation set during trainng (but i cant get it to work with the past-covariates)
ts_train, ts_val = ts.split_after(pd.Timestamp("2023-09-30"))

model_nhits_covariates_with_validation = NHiTSModel(
    input_chunk_length=30,
    output_chunk_length=7,
    num_stacks=4, # >4 helps but increase time alot
    num_blocks=1, # >1 helps. increase time alot
    num_layers=4,
    layer_widths=512, # big effect
    n_epochs=15, # at least 20
    nr_epochs_val_period=1,
    batch_size=400,
    model_name="nhits_run",
)

model_nhits_covariates.fit(
    ts_train["Interval_Sum"],
    val_series=ts_val["Interval_Sum"],
    past_covariates=ts[['GreenInterval_Sum','KWh_total','RedInterval_Sum']],

I always get the same error:
ValueError: The dimensions of the series in the training set and the validation set do not match.

If convert all covariates into its own timeSeries object i still get the same error.

PS. i cant find out how to add the Question tag. Also, should i upload a code file instead?

**Comment by Allena101** [comment]
i want to add that it works when i am not trying to use any val_series. I have noticed that almost all (if not all) examples on your site does not use va_sereis when fitting the model when you are also using covariates and when you are using val_series then you are usually using univaraite data. I might have missed somewhere in your guides and vidoe tutorials where you state that this is by design.

**Comment by dennisbader** [comment]
Hi @Allena101 and thanks for your first issue.

You simply have to pass `val_past_covariates` to `fit()` as well.

**Comment by Allena101** [comment]
> Hi @Allena101 and thanks for your first issue.
> 
> You simply have to pass `val_past_covariates` to `fit()` as well.
> 
> [Here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nhits.html#darts.models.forecasting.nhits.NHiTSModel.fit)'s also the documentation with more information.

wow , i dont know how i missed it since i spent hours testing stuff and reading the docs... 
Thanks for the help, Dennis!

how do i get/view the val score? i know in sklearn and tensorflow you can train and use X_val as your criteria for early stoppig

**Comment by dennisbader** [comment]
Hi @Allena101, yes you can do that with Darts as well.
We documented this in our TorchForecastingModel user guide [here](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#id10).
What you're looking for is Early Stopping and the Custom Callback that stores the losses over the training process.

**Comment by Allena101** [comment]
> Hi @Allena101, yes you can do that with Darts as well. We documented this in our TorchForecastingModel user guide [here](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#id10). What you're looking for is Early Stopping and the Custom Callback that stores the losses over the training process.

Thanks alot Dennis! I tested it and it worked. Next step is to figure out how get the tensorboard part working 😁
