### ISSUE TITLE
Seeking Suggestions for Suitable Model for Multivariate Anomaly Detection

### ISSUE THREAD

**Issue by SaltedfishLZX** [unit8co/darts#2120]
Hi 

I'm trying multivariate anomaly detection using Darts model. My task involves sensor fault monitoring, where a single variable (sensor) may exhibit sustained anomalies. Ideally, I want the predictions to stay relatively normal when one variable goes wrong, as long as the other variables are fine.

I've experimented with models like RNN, but the output tends to mimic the trend of the individual faulted variable itself, making it less resistant to anomalies. On the other hand, TFT seems to handle these situations better, which can predict relatively normal data from a faulted sensor(variable).

I'm well aware that Darts isn't specifically designed for anomaly detection, but I'm interesting about which models within the Darts framework will makes better theoretically

I'd appreciate your recommendations！Thanks a bunch

**Comment by piaz97** [comment]
Hello!

As you mentioned, Darts models were not designed for Anomaly Detection, but we instead mostly rely on the predictions from our forecasting models as a starting point. Those models, in the multivariate setup, have no restriction on which other dimensions (sensors) they can attend while forecasting each dimension (sensor). Thus, usually, when the sensors are of a similar type (e.g., temperature sensors) and are spatially correlated, it can happen that the model forecasts of a sensor mostly rely on the spatially close sensors. 

In a more general case, each time the model is learning a relationship between two sensors - let’s say sensor A is used for forecasting sensor B - then an anomaly on sensor A, will cause an anomaly on sensor B. This is totally fine if there happen to be a causal relationship (i.e., the anomaly on A is causing an anomaly on B also in real life). On the other side, in case of correlation without a causal relationship, we will detect a false positive on sensor B in case of an anomaly on sensor A.

From some personal tests I did in the past, I can tell you that in my use case, N-BEATS was coming up with more meaningful forecasts compared to TCN for instance, but the behavior might change from dataset to dataset; and we also added quite a few models in the meantime (that I didn’t test back at the time). So, in your setup, unfortunately, I can only suggest testing as many models as you can. Again, in this way you still won’t have any “causal guarantees” on the detection of the real sources of the anomaly, and on a general case, you will be able to spot the real faulty sensor together with other false positives.

Another approach to the problem, in case you know precisely the causal relationship graph between your sensors, can be instantiating one model for each target sensor, selecting as input dimensions for each sensor forecast, only the subset of sensors that can have a causal impact on it in real-life (yeah I know, in complex systems this won’t be easy to define). In this way, you have more control over the forecasts and can prevent, for instance, the attendance to correlated sensors information, reducing the false positives. A couple of notes on this approach:

-  You need to be careful about the quality of the forecasts: the anomaly detection framework relies on the good quality of the forecasts, so, if the quality deteriorates too much using only a subset of sensors, the whole detection will worsen overall.
- The approach scales linearly with the number of target sensors you want to monitor, so might not scale well with a large number of sensors.
