### ISSUE TITLE
Am not understanding how darts implements past_covariates for models such as XGBoost and LightGBM  

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2123]
I think i might have seen an explanation of this when reading your docs, but i cannot find it now and i do remember that i did not really understand it back then anyhow. 

The official xgboost and lightgbm can only use future_covariates. Is the darts version implemented such that the model internally predicts each covariate in the future and uses that as a basis for predictions (i.e. recursive)?

**Comment by madtoinou** [comment]
Hi @Allena101,

The two relevant parts of the documentation are the covariates section of the [quickstart notebook](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Covariates:-using-external-data) and the [regression models notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html).

xgboost and lightgbm both supports exogeneous variables. The distinction between `past` and `future` covariates is specific to Darts terminology, and they are both supported by these models. The input series are just tabularized and then passed to the model, which never forecasts the covariates.

**Comment by Allena101** [comment]
> Hi @Allena101,
> 
> The two relevant parts of the documentation are the covariates section of the [quickstart notebook](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Covariates:-using-external-data) and the [regression models notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html).
> 
> xgboost and lightgbm both supports exogeneous variables. The distinction between `past` and `future` covariates is specific to Darts terminology, and they are both supported by these models. The input series are just tabularized and then passed to the model, which never forecasts the covariates.

Hi! Thanks for the response! 
I know that past and future covariates is darts' terminology, but i was using it since i thought it explained my confusion. 

If you use lightgbm by itself (without darts) then you cannot use future covariates. lets say i use rolling average as a covariate/feature during training, then the model will need that feature during inference or else i get error that those features are missing. If you can predict with lightGBM, without having to provide the extra exogeneous variables, then that is great but also not something i can find any documentation of. 

So back to my question then of why it is possible in darts? I read both the notebooks that you linked. I don't think it explains what i am wondering. It explains the difference between future and past covariates (which i feel that i have a pretty good understanding of), but does not explain how a model like lightGBM can use it in darts (using the equivalent of future covariates) but not the standalone lightGBM. 

Sorry, i don't get the intuition of future covariates being tabularized.

**Comment by Allena101** [comment]
> Hi @Allena101,
> 
> The two relevant parts of the documentation are the covariates section of the [quickstart notebook](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Covariates:-using-external-data) and the [regression models notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html).
> 
> xgboost and lightgbm both supports exogeneous variables. The distinction between `past` and `future` covariates is specific to Darts terminology, and they are both supported by these models. The input series are just tabularized and then passed to the model, which never forecasts the covariates.

to clarify a bit more. I dont understand why it is possible to use covariates during training and then you dont have to supply those same features during inference (model.predcit()). Using lightGBM without darts, then if i dont supply all the features that the model was trained on in fit, then it will give me error an error and ask for those features. With darts though, if you use past covariates then it works to use model.predcit withotu having to supply the extra features. 

Is my misunderstanding due to it actually being possible to train lightGBM (without darts) and somehow not needing to provide all the features together with predict? When i search on examples using lightGBM (without darts) then there are no examples i can find where the covariates does not have to be supplied at inference. Would be awesome if you guys could link such an occurrence so that i could realize my mistake.

**Comment by madtoinou** [comment]
Hi @Allena101,

You do have to provide the same number of features at training and inference, Darts' model just store the training series (and covariates) so that you can directly call `predict()` without having to provide the series again. It might be the source of your confusion?

If `n > output_chunk_length`, the model will require future values of both the past and future covariates. If the covariates provided during training are not long enough, an error will be raised. 

Tabularization is the process of converting a 1D array into a 2D array. When the model is training with target, past and future covariates, the lags are simply extracted and concatenated as features (columns in the samples array). As long as the time-index of the time series are long enough, everything can be transformed for the model to train/predict.

Do it answer your question or is something still unclear?
