### ISSUE TITLE
Feature importance not computed in any model on darts

### ISSUE THREAD

**Issue by JuanesRurall** [unit8co/darts#2125]
**Is your feature request related to a current problem? Please describe.**
Currently using darts there is no option to perform a feature importance and also get the final training_labels or training_samples, there should be an option to get both from model attributes, since there is no option to double-check feature develop behind the function, so the user has to believe the model is implementing what he or she enter as an input. As an example of feature importance on xgboost library there is this method

base on this article:
[link](https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html#plot-feature-importance)

![imagen](https://github.com/unit8co/darts/assets/128072445/d140971e-11ab-4a13-9023-50292685889e)

**Describe proposed solution**
Implement from sklearn pr xgboost feature importance. 

**Describe potential alternatives**
create a built in function on this library to get both feature importance plot and feature importance dataframe. 

**Additional context**
This is a tool that enable us to perform feature engineering.

**Comment by dennisbader** [comment]
Hi @JuanesRurall. Have a look at #1826. You can get the feature names with `model.lagged_feature_names`.
