### ISSUE TITLE
Is there a Slimmer Production only Minimal Version of Darts? 

### ISSUE THREAD

**Issue by barmanroys** [unit8co/darts#2130]
Using darts for some model training and inference. But as it is, I am using darts inside a docker container (with debian base image and some other pip dependencies such as sql alchemy, fastapi etc.) to serve a model via HTTP requests. 

The point is, I am using only the category boost model in Darts, and not really generating any visualisation or implementing in neural networks using pytorch etc. But darts is installing a huge number of dependencies such as pytorch, matplotlib etc. most of which I suspect are not necessary in my service. 

So just wondering if there is a more minimal version of darts for just backend serving, which does away with the pytorch and plotting extensions to compress the docker image? 

Also, is there a more darts specific forum where I can ask this?

**Comment by dennisbader** [comment]
Hi @barmanroys, yes we have lighter Darts flavors. `u8darts` for [pip](https://github.com/unit8co/darts/blob/master/INSTALL.md#from-pypi) and [conda-forge](https://github.com/unit8co/darts/blob/master/INSTALL.md#from-conda-forge) ship without torch, lightgbm, prophet and catboost. You can install the boosting models you use before installing Darts.

If you don't care about Prophet being installed with the rest, you can also use the `u8darts-notorch` (conda) or `u8darts[notorch]` (pip) flavors.

We don't have a flavor without matplotlib.
