### ISSUE TITLE
Adding a new undefined metric to backtesting 

### ISSUE THREAD

**Issue by AndrewJGroves** [unit8co/darts#2131]
Hi

How do I add a metric not defined in darts to backtesting? I am wanting directional bias

Thanks
Andrew

**Comment by madtoinou** [comment]
Hi, you can pass a `Callable` to the `metric` argument of `backtest`. The callable must accept two `TimeSeries` as input and return a single float values ([documentation](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.regression_model.html?highlight=backtest#darts.models.forecasting.regression_model.RegressionModel.backtest))
