### ISSUE TITLE
How to include scalers as part of the historical forecast method easily

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2134]
Hi,

Assuming I have **hourly data** from 2022-01-01 to 2022-12-31. I want to train on 9 months of data (2022-01-01 to 2022-08-31) and do a historical backtest on the last 3 months of data (2022-09-01 to 2022-12-31). If I retrain every day on the past 90 days of data (`retrain = True, stride = 24, train_length = 2160`) and have a forecast horizon of 24, i.e. 24 hours, **how would I include refitting my scaler as my training set changes for every iteration of the historical forecast method?** Is there some sort of params I can call?

Currently, I am initialising my scaler via the method below.
```
scaler = MinMaxScaler()
target_transformer = Scaler(scaler)
future_cov_transformer = Scaler(scaler)
target_series_fit_scaled = target_transformer.fit_transform(target_series_fit) #target_series_fit contains data from 2022-09-01 to 2022-12-31
future_cov_fit_scaled = future_cov_transformer.fit_transform(future_cov_fit)

target_series_sample_scaled = target_transformer.transform(target_series_sample) #target_series_sample contains data from 2022-09-01 to 2022-12-31
future_cov_sample_scaled = future_cov_transformer.transform(future_cov_sample)
```

Currently when I do the historical forecast, I first fit the model on target_series_fit_scaled and future_cov_fit_scaled then pass target_series_sample_scaled and future_cov_sample_scaled to the historical forecast method. However, this does not include refitting of the scaler as the training set changes.
```
model_estimator.fit(
            series = target_series_fit_scaled ,
            future_covariates= future_cov_fit_scaled 
        )

hf_results = model_estimator.historical_forecasts(
      series=target_series_sample_scaled , 
      future_covariates= future_cov_sample_scaled,
      start=2022-09-01, 
      retrain=True,
      forecast_horizon=24,
      stride=24,
      train_length = 2160,
      verbose=True,
      last_points_only=False,
  )
```

**Comment by madtoinou** [comment]
Hi @ETTAN93,

At the moment `historical_forecasts/backtest` do not accept data transformer and the series is used as is to train the model (with the associated information leakage if the series are scaled), there is no argument to change this.

The feature request is already tracked by #1540 and the PR #2021 started to implement it, I am going to close this issue to limit duplicates.

**Comment by ETTAN93** [comment]
Hi, I just wanted to check if the feature has already been implemented and is live? I see in the PR that there is still some conflicts so I assume it is not fully completed yet?

**Comment by madtoinou** [comment]
The feature is not yet implemented, it will be when the PR is merged.
