### ISSUE TITLE
Get the errors of all parameters and cross validation splits when using `gridsearch()` (and `backtest()`)

### ISSUE THREAD

**Issue by afonsomota** [unit8co/darts#2145]
**Is your feature request related to a current problem? Please describe.**
When making a gridsearch only the best model parameters and error values are presented. The lack of a form of output that gives us the error per parameter chosen or validation window, limits the scope of analysis we can do on our model selection process. Scikit Learn CV grid search feature returns a dataframe with different errors for all parameters and validation windows. This would help the analysis of the gridsearch method and enhance different use cases that can explore this information.

**Describe proposed solution**
Similarly to what is done in SciKit's CV grid search method, I would propose that the `gridsearch()` method has the ability to give the user information on the error metrics for all parameter combination tested, as well as every validation window tested with the help of `backtest()`. I propose myself to implement this (already have some code for that), but would like to know what is your preference in how the values are returned to the user. I have three proposals

1. A dataframe as and additional output: is the cleanest, but has the issue of making an API change in the gridsearch/backtest method
2. Pass an empty dataframe (or new object, for example `GridSearchReport`) as reference to gridsearch (and backtest) that is filled inside these methods: provides backwards compatibility, but passing an argument as reference is not something I see normally in Python
3. A wrapper `detailed_gridsearch()` that outputs the dataframe. We change the core functionality to a `_gridsearch` method and both `gridsearch` (with the API preserved) and `detailed_gridsearch`

My personal opinion is number 2 with the new object type:

```python
report = GridSearchReport()
same_grid_search_return_tuple = model_class.gridsearch(
    ...
    report_instance = report
)
df = report.get_dataframe()
```

If you use gridsearch in multiple models to do some kind of AutoML with different models, the information of each gridsearch can be appended to the same report.

**Describe potential alternatives**
From what I looked into the code, the errors of individual parameters are kept locally, so there is not an alternate way of getting them. 

**Additional context**
An example of the dataframe in Scikit's CV gridsearch can be seen here: https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_stats.html#statistical-comparison-of-models-using-grid-search

**Comment by dennisbader** [comment]
Hi @afonsomota and thanks for raising this issue.

Darts' gridsearch indeed only provides very basic hyper-parameter search. For the forseeable future we actually want to keep it this way because there are other great libraries dedicated to performing hyperparameter tuning that you can use. 

If you haven't seen it already, I would recommend reading our [user guide on hp tuning with using Optuna or RayTune](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html).
