### ISSUE TITLE
[Question] Future covariates series length requirements when ocl > 1

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2147]
**Describe the bug**
I have a problem with the following scenario (this is my real scenario):

I have a monthly training dataset up to 31-05-2018.
I want to forecast 7 months with `output_chunk_length`=7.
So, my future index is ['2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31'].

```{python}
forecaster = RegressionModel(lags=12, 
                             lags_past_covariates=None, 
                             lags_future_covariates=[12], 
                             output_chunk_length=7, 
                             add_encoders=None, 
                             model=KNeighborsRegressor(p=1), 
                             multi_models=False, 
                             use_static_covariates=False)
```

When I call `forecaster.predict(n=7)` after `fit` I receive the following error:

```{python}
ValueError: The corresponding future_covariate of the series at index 0 isn't sufficiently long. Given horizon `n=7`, `min(lags_future_covariates)=12`, `max(lags_future_covariates)=12` and `output_chunk_length=7`, the future_covariate has to range from 2018-12-31 00:00:00 until 2019-06-30 00:00:00 (inclusive), but it ranges only from 2013-06-30 00:00:00 until 2018-12-31 00:00:00.
```

**To Reproduce**

```{python} 
from darts.datasets import WeatherDataset
from darts.models import RegressionModel
from sklearn.linear_model import Ridge
series = WeatherDataset().load()
# predicting atmospheric pressure
target = series['p (mbar)'][:100]
# optionally, use past observed rainfall (pretending to be unknown beyond index 100)
past_cov = series['rain (mm)'][:100]
# optionally, use future temperatures (pretending this component is a forecast)
future_cov = series['T (degC)'][:107]
# wrap around the sklearn Ridge model
model = RegressionModel(
    model=Ridge(),
    lags=12,
    lags_past_covariates=4,
    lags_future_covariates=[7], #if the lags_future_covariates is 7 or greater, the code fails. 7 is the output_chunk_length
    output_chunk_length=7
)
model.fit(target, past_covariates=past_cov, future_covariates=future_cov)
pred = model.predict(7)
pred.values()
```

If n <= n_output_chunk_length, for `future_covariates` I would need to provide at least the same time span as the target plus the maximum between the next `n` step and `lags_future_covariates` + 1.

**Expected behavior**
When using future_covariates, I only would need to provide the next `n=7` index from future_dataset. Right now, it is asking for an extra 13 days after 31-05-2018. 

I followed the documentation:

![image](https://github.com/unit8co/darts/assets/13880005/a705e03e-1457-4483-b60d-249261930a8c)

**System (please complete the following information):**
 - Python version: 3.9.12
 - darts version 0.27.1

**Comment by dennisbader** [comment]
Hi @guilhermeparreira. The future lags start at `0` corresponding to the first prediction time step (`output_chunk_length = 1`). So since the future covs are 7 steps longer than the target series, you can have a maximum lag of `7 - 1 = 6` 

The documentation you shared applies for TorchForecastingModels.

For RegressionModels, if `n<=output_chunk_length` you need to provide future covariates including the next `max_lag + 1` values after the end of the target series.

For `n>output_chunk_length`  additional `n - output_chunk_length` values.

**Comment by guilhermeparreira** [comment]
Thank you @dennisbader 

Now I understand!

If it is not asking too much, it would be great to include this information on [20-RegressionModel-examples.html notebook]
(https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html).

I am also wondering why there are these differences. But it may be related to the way that the models were constructed. And this is another topic.

Thanks again!
