### ISSUE TITLE
Minimum Example of hyperparameter optimization with RegressionEnsembleModel either Ray or Optuna

### ISSUE THREAD

**Issue by esnvidia** [unit8co/darts#2148]
How do I set the search space parameters for each submodel in the Regression Ensemble?

**Comment by dennisbader** [comment]
Hi @esnvidia. You can do it like you would using a single model. The code below is leaning on [our user guide on hyperparmeter tuning](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html#hyperparameter-optimization-with-optuna).

```
from darts.models import RegressionEnsembleModel, NaiveSeasonal, LinearRegressionModel


def objective(trial):
    k_m1 = trial.suggest_int("k_m1", 5, 7)
    lags_m2 = trial.suggest_int("lags_m2", 5, 7)

    series = AirPassengersDataset().load()
    model = RegressionEnsembleModel(
        forecasting_models=[
            NaiveSeasonal(K=k_m1),
            LinearRegressionModel(lags=lags_m2)
        ],
        regression_train_n_points=20
    )
...
```

Another way would be to perform tuning separately for each forecasting model and then later use the ensemble model with the best performing forecasting models (potentially tuning only the ensemble parameters again).

**Comment by esnvidia** [comment]
Awesome, thank you for the clarification. Wish a single trial ran in parallel across multi-gpus, currently multiple trials w/ multi-gpu. Similarly with training ensembles could be accelerated w/ 1 model per gpu, or if doing backtesting -- then training models in a round robin fashion w/ multi-GPU.
