### ISSUE TITLE
[BUG] Coefficient of Variation Calculation Between Two TimeSeries Intersection

### ISSUE THREAD

**Issue by HasanResul** [unit8co/darts#2157]
In the `coefficient_of_variation` function definition (`metrics.py` line 464) the RMSE value is divided by the mean of the all values of the actual series rather than only the intersection values. Is this the correct way to calculate the `Coefficient of Variation` for two timeseries that are overlapping in time without having the same time index ? Should we get the mean of only the intersection values from the actual series ?

```python
return (
        100
        * rmse(actual_series, pred_series, intersect)
        / actual_series.pd_dataframe(copy=False).mean().mean()
    )
```

**Comment by madtoinou** [comment]
Thank you @HasanResul for reporting this,

It looks like a bug, it should consider only the overlapping index in the denominator when `intersect=True`.
