### ISSUE TITLE
Adding conformal predictions functionnality

### ISSUE THREAD

**Issue by Jonathan-87** [unit8co/darts#2162]
I'm wondering if you are planning to add conformal predictions functionnality (example here : https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/prediction_intervals.html) ? Doing so it would be possible to add prediction intervals for example for regression models and get calibrated prediction intervals.

**Comment by dennisbader** [comment]
Hi @Jonathan-87, we're currently working on integrating conformal prediction. 
It's still in the early phases but we kicked of the planning.

**Comment by madtoinou** [comment]
Hi @Jonathan-87,

This feature is already tracked by #1704, closing this one to limit duplicates :)
