### ISSUE TITLE
Save every checkpoints? 

### ISSUE THREAD

**Issue by simonpun123** [unit8co/darts#2169]
Hello there, I understood that we can set save_checkpoins=True in order to save checkpoints from training. But I found that only when the best checkpoints (in terms of val_loss) are saved. How can I do if I want to save every checkpoint during training? Thanks.

**Comment by dennisbader** [comment]
Hi @simonpun123, when checkpointing is enabled, Darts saves/retain the **best** and **latest** checkpoints.

Is this already enough for your use case?

If not, there are ways to customize checkpointing with some additional code.

**Comment by simonpun123** [comment]
Thanks @dennisbader
