### ISSUE TITLE
[BUG] Table 1 and Table 2 of torch_forecasting_models are not printed in the documentation

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2171]
**Describe the bug**
Hi there!

Table 1 and Table 2 of torch_forecasting_models are not printed in the documentation.

https://unit8co.github.io/darts/userguide/torch_forecasting_models.html

**To Reproduce**
![image](https://github.com/unit8co/darts/assets/13880005/de1e512e-efb0-4119-a230-a8583e716b4d)

**Comment by dennisbader** [comment]
Hi @guilhermeparreira and thanks for pointing this out. We'll fix it soon.
