### ISSUE TITLE
how to save series plot and/or stream it from memory

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2175]
as title says, i want to save the plot prodcues by darts or send them. main goal in this case is to send using fastAPI. I saw that its possible to send matplotlib figures, and as i understand it, darts plots using matplotlib.

for example:

preds =  LGBM_Model.predict(15)
preds.plot()

How would I save the created plot to disc?
Also ,  I know its not your guys focus, but if you know how to send it with fastAPI then that would be great. 😁

**Comment by dennisbader** [comment]
Hi @Allena101, to store the matplotlib plot/figure you can do one of the two below:

- create a new figure with axes, plot on it and save it:
```
import matplotlib.pyplot as plt

fig, ax = plt.subplot()
preds.plot(ax=ax)
fig.savefig(...)
```

- or retrieve the current figure and then save it:
```
preds.plot()

fig = plt.gcf()
fig.savefig(...)
```

I'm not familiar with fastAPI but [this stackoverflow answer](https://stackoverflow.com/a/73754985) looks promising.

**Comment by Allena101** [comment]
> Hi @Allena101, to store the matplotlib plot/figure you can do one of the two below:
> 
> * create a new figure with axes, plot on it and save it:
> 
> ```
> import matplotlib.pyplot as plt
> 
> fig, ax = plt.subplots()
> preds.plot(ax=ax)
> fig.savefig(...)
> ```
> 
> * or retrieve the current figure and then save it:
> 
> ```
> preds.plot()
> 
> fig = plt.gcf()
> fig.savefig(...)
> ```
> 
> I'm not familiar with fastAPI but [this stackoverflow answer](https://stackoverflow.com/a/73754985) looks promising.

thanks alot for the help , Dennis !
