### ISSUE TITLE
Flattening input-output in N-Beats / NHiTS

### ISSUE THREAD

**Issue by simonpun123** [unit8co/darts#2182]
Hi there, I have been using N-Beats and NHiTS for univariate time series forecasting with several past covariates. When I read the documentation of N-Beats and/or NHiTS, it mentioned that 

> the implementation also supports multivariate series (and covariates) by flattening the model inputs to a 1-D series and reshaping the outputs to a tensor of appropriate dimensions. Furthermore, it also supports producing probabilistic forecasts (by specifying a likelihood parameter). 

I want to make sure my understanding is correct: assuming `input_chunk_length` is the length of the input time window,`num_target` is the dimension of the target time series (when it is univariate, `num_target=1`), `num_covariates` is the number of past covariates; each model-input is of the shape 

`(batch_size, input_chunk_length, num_target + num_covariates)`; 

then each input is reshaped/flattened so that the model actually takes input of shape 

`(batch_size, input_chunk_length*(num_target+num_covariates))` or, equivalently `(batch_size, input_chunk_length*(num_target+num_covariates), 1)`. 

Finally, if we consider the deterministic case (not considering any quantile-related output), then the model-output is of shape 

`(batch_size, output_chunk_length)` 

as we consider the univariate time series. Is my understanding about the model-input/output above correct? Thanks.

**Comment by madtoinou** [comment]
Hi @simonpun123,

Your understanding of what is happening under the hood is indeed correct: we "abuse" of the capacity of deep learning models to capture interactions across dimensions and just collapse all the dimensions (target, covariates, ...) into a single one. By reshaping the output into the desired shape, the model is effectively capable of forecasting any number of dimensions (target or distribution parameters in the context of probabilistic forecasting).

Closing this issue, feel free to open another one if you have further questions about the Darts, we will do our best to answer with more reasonable delays :)
