### ISSUE TITLE
[INFO] Fit multiple time series using `RegressionModels` with `static` and `past` covariates.

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2183]
**Describe the help**
I want to fit a `multiple time series` with `RegressionModels`. I was able to fit only with the targets (code in the end). When I tried to fit with `static` or `covariates` I always received error messages and could sort it out on my own.

I have the following `dados_target` `dataframe`:
![image](https://github.com/unit8co/darts/assets/13880005/316a2463-f565-4666-8bbc-589b62abfbbc)

Where the last two columns correspond to `static_covariates`. The first column corresponds to the date,  the second is the 'target', and the third is the `value` of the `target`.

I also have the following `data_past` `dataframe` with past covariates (same date range as the target dataframe):

![image](https://github.com/unit8co/darts/assets/13880005/40be8030-1b81-4654-97d2-26bb7a193c9a)

My attempt:

```python
dados_past = TimeSeries.from_dataframe(df = data_past)
dados_target_t = TimeSeries.from_group_dataframe(df = dados_target,
                                group_cols='hierarquia',
                                time_col='date',
                                value_cols='value',
                                static_cols=['Market', 'family'],
                                fill_missing_dates=False,
                                fillna_value=None)
model_params = {'alpha':1}
model = Lasso(**model_params)
forecaster = RegressionModel(
    model=model,
    lags=12,
    lags_past_covariates=4,
    output_chunk_length=7,
    use_static_covariates=True
)
forecaster.fit(series = dados_target_t, past_covariates= dados_past)
pred = forecaster.predict(n=7, series = dados_target_t)

# It converts the output to dataframe
dtot = pd.DataFrame()
for series, label in zip(pred, targets):
    dp = series.pd_dataframe().rename(columns={'value':label})
    dtot = pd.concat([dtot, dp], axis=1)
```

I receive the following error:

```python
main_logger ERROR ValueError: Must specify the same number of `TimeSeries` for each series input.
```

I tried to change the inputs to `RegressionModel`, `fit`, and `predict`, but I was unsuccessful.

I also tried to look for a full example like this in the docs but I did not find one that uses the data in the `long format`, it is useful when we have many targets.

**Code that works**

```python
dados_target_t = TimeSeries.from_group_dataframe(df = dados_target.iloc[:,:3],
                                group_cols='hierarquia',
                                time_col='date',
                                value_cols='value',
                                fill_missing_dates=False,
                                fillna_value=None)
model_params = {'alpha':1}
model = Lasso(**model_params)
forecaster = RegressionModel(
    model=model,
    lags=12,
    # lags_past_covariates=4,
    output_chunk_length=7,
    use_static_covariates=False
)
forecaster.fit(series = dados_target_t)
pred = forecaster.predict(n=7, series = dados_target_t)

# It converts the output to dataframe
dtot = pd.DataFrame()
for series, label in zip(pred, targets):
    dp = series.pd_dataframe().rename(columns={'value':label})
    dtot = pd.concat([dtot, dp], axis=1)
```

Thank you for your time and patience

**System**
 - Python version: 3.9
 - darts version 0.27.1

**Comment by dennisbader** [comment]
Hi @guilhermeparreira, [`TimeSeries.from_group_dataframe()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.from_group_dataframe) returns a list of TimeSeries of length `n`.
When using past and/or future covariates, the covariates must also be a list of TimeSeries of length `n`. Each element (TimeSeries) in the covariates series list maps to the corresponding element (TimeSeries) of the target series list.

If you can use the same past covariates `TimeSeries` for all target series, then you can simply create a list like below:

```
past_covariates = [dados_past for _ in range(len(dados_target_t))]
```

**Comment by guilhermeparreira** [comment]
Thank you! Good point, I fixed that:

```python
dados_past = TimeSeries.from_dataframe(df = data[aux_past_vars].dropna())
dados_target_t = TimeSeries.from_group_dataframe(df = dados_target,
                                group_cols='hierarquia',
                                time_col='date',
                                value_cols='value',
                                static_cols=['Market', 'family'],
                                fill_missing_dates=False,
                                fillna_value=None)
model_params = {'alpha':1}
model = Lasso(**model_params)
forecaster = RegressionModel(
    model=model,
    lags=12,
    lags_past_covariates=4,
    output_chunk_length=7,
    use_static_covariates=True
)
forecaster.fit(series = dados_target_t, past_covariates= [dados_past for _ in range(len(dados_target_t))])
```

And I received: 

![image](https://github.com/unit8co/darts/assets/13880005/255691f1-1067-49cc-a984-78317009a124)

**Comment by dennisbader-unit8** [comment]
Your static covariates contain strings. At the moment, Darts only supports numeric static covariates. 

- either transform them into numeric before creating the `TimeSeries` or
- use Darts `StaticCovariatesTransformer` as described [here](https://github.com/unit8co/darts/issues/1605#issuecomment-1451595398) or in the example notebook [here](https://unit8co.github.io/darts/examples/15-static-covariates.html#5.-Scaling/Encoding/Transforming-static-covariate-data).

**Comment by dennisbader** [comment]
Your static covariates contain strings. At the moment, Darts only supports numeric static covariates. 

- either transform them into numeric before creating the `TimeSeries` or
- use Darts `StaticCovariatesTransformer` as described [here](https://github.com/unit8co/darts/issues/1605#issuecomment-1451595398) or in the example notebook [here](https://unit8co.github.io/darts/examples/15-static-covariates.html#5.-Scaling/Encoding/Transforming-static-covariate-data).

**Comment by guilhermeparreira** [comment]
I see! I managed to convert the column `hierarquia` using the example in the other [issue](https://github.com/unit8co/darts/issues/1605)

```python
from darts.dataprocessing.transformers import StaticCovariatesTransformer
dados_past = TimeSeries.from_dataframe(df=data[aux_past_vars].dropna())
dados_target_t = TimeSeries.from_group_dataframe(
    # df=dados_target,
    df=dados_target,
    group_cols="hierarquia",
    time_col="date",
    value_cols="value",
    static_cols=["Market", "family"],
    fill_missing_dates=False,
    fillna_value=None,
)
# Convert Static to categorical
transformer = StaticCovariatesTransformer(
    cols_num=[]  # don't scale any numeric columns, only the categorical ones
)
dados_target_t = transformer.fit_transform(dados_target_t)
model_params = {"alpha": 1}
model = Lasso(**model_params)
forecaster = RegressionModel(
    model=model,
    lags=12,
    # lags_past_covariates=4,
    output_chunk_length=7,
    use_static_covariates=True,
)
forecaster.fit(
    series=dados_target_t,
    # past_covariates=[dados_past for _ in range(len(dados_target_t))],
)

raw_predictions = forecaster.predict(
    n=forecast_steps,
    series=dados_target_t,
    # past_covariates=[dados_past for _ in range(len(dados_target_t))],
)

# It convert the output to dataframe
dtot = pd.DataFrame()
for series, label in zip(raw_predictions, targets):
    dp = series.pd_dataframe().rename(columns={"value": label})
    dtot = pd.concat([dtot, dp], axis=1)
dtot
```

But I think that `hierarquia` is not a `covariate`. It is just a column to delimit where a `target` variable ends and  another `target` starts (instead of passing each target in a `for loop`) .

**Comment by dennisbader** [comment]
Hi @guilhermeparreira, you can create new series with updated static covariates (e.g. dropping the ones you don't want):

After `from_group_dataframe`:

```
dados_target_t = [s_.with_static_covariates(s_.static_covariates.drop(columns="hierarquia")) for s_ in dados_target_t]
```

I opened PR #2196  today which adds parameter `drop_group_cols` to `from_group_dataframe()` that allows to exclude some `group_cols` from the static covariates.
