### ISSUE TITLE
[BUG] Indexing issues in ForecastingModel.backtest()

### ISSUE THREAD

**Issue by Eliotdoesprogramming** [unit8co/darts#2184]
**Describe the bug**
With certain combinations of certain stride values, ts lengths and `last_points_only=True` , a value error will be raised from the metric function (default darts.metrics.mape)
**To Reproduce**
```python
from darts.models import NaiveDrift
from darts.utils.timeseries_generation import constant_timeseries
ts = constant_timeseries(length=35)
NaiveDrift().backtest(ts, forecast_horizon=26, stride=4, last_points_only=True)
```

`ValueError: Inferred frequency None from passed values does not conform to passed frequency D`

**Expected behavior**

I would expect that the historical forecast where the `last point` actual is not available to be ignored & to be returned error values.

**System (please complete the following information):**
 - Python version: 3.8.10
 - darts version: u8darts==0.26.0

**Comment by dennisbader** [comment]
Hi @Eliotdoesprogramming, I tried reproducing you issue with darts==0.27.2 and there everything works as expected (MAPE = 0.).
I'd recommend updating Darts to the latest version.

**Comment by Eliotdoesprogramming** [comment]
Thanks for the quick response! I'll do that.
