### ISSUE TITLE
 [QUESTION] Croston and add_encoders

### ISSUE THREAD

**Issue by sebros-sandvik** [unit8co/darts#2193]
Hi,

I cant get add_encoders functionality (for Croston) to work, see below

![image](https://github.com/unit8co/darts/assets/126782748/51e57b3b-976a-4b4c-b69b-749a1ffa34ff)

temporal_cv_lf basically just calls 

m = Croston(**params)

**m.historical_forecasts**(series=series,
                                                      forecast_horizon=forecast_horizon,
                                                      last_points_only=False,
                                                      overlap_end=False,
                                                      stride=1,
                                                      retrain=True))

Any help would be appreciated

**Comment by sebros-sandvik** [comment]
Hi,

Ok just fyi if this needs changing the:
![image](https://github.com/unit8co/darts/assets/126782748/0257bdcf-066e-4f17-881a-7e400287de3e)

**Comment by sebros-sandvik** [comment]
Hi,

of course sir:

import pandas as pd
from darts.models import Croston
from darts import TimeSeries, concatenate
import numpy as np

sales = [5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 0.0,
         0.0, 5.0, 0.0, 0.0, 0.0, 0.0]
dates = pd.date_range(start='2019-02-01', end='2023-03-01', freq='MS')
month = dates.month
np.random.seed(1)
noise = np.random.normal(0, 1, len(dates))
sales = month + noise
data = pd.DataFrame({'date': dates, 'sales': sales})
series = TimeSeries.from_dataframe(data, 'date', 'sales')

params1 = {'version': 'tsb', 'alpha_d': 0.7056278684620902, 'alpha_p': 0.12437058458227879}
params2 = {'version': 'tsb', 'alpha_d': 0.7056278684620902, 'alpha_p': 0.12437058458227879,
           'add_encoders': {'cyclic': {'future': ['month']}}}

m1 = Croston(**params1)
m2 = Croston(**params2)

pred1 = concatenate(m1.historical_forecasts(series=series,
                               forecast_horizon=1,
                               last_points_only=False,
                               #start=pad_n - 1,  # start at obs pad_n - 1
                               overlap_end=False,
                               stride=1,  # 3,
                               retrain=True))

pred2 = concatenate(m2.historical_forecasts(series=series,
                               forecast_horizon=1,
                               last_points_only=False,
                               #start=pad_n - 1,  # start at obs pad_n - 1
                               overlap_end=False,
                               stride=1,  # 3,
                               retrain=True))

print(pred1 == pred2)

**Comment by madtoinou** [comment]
Hi @sebros-sandvik,

After inspecting the implementation of Croston, it seems like the covariates (`X` in their API) is only used when using conformal prediction (not yet supported by Darts).

We will revert the changes to the table and update the constructor of this model to remove the `add_encoders` argument as it actually does not support future covariates.

Sorry for the confusion and the delay.
