### ISSUE TITLE
switch to Ruff instead of `flake8`

### ISSUE THREAD

**Issue by Borda** [unit8co/darts#2195]
**Is your feature request related to a current problem? Please describe.**
It would address linting speed, as Ruff is much faster, and eventually extensibility, as Ruff can cover multiple linting packages with almost no performance drop...

**Describe proposed solution**
replace linking with `flake8` preserving the same configuration

**Additional context**

Recently [Ruff](https://github.com/astral-sh/ruff) has become very popular among also mainstream projects for:
- much faster, they say 70x
- integrate several other tools under one roof, such as isort or bandit

**Comment by VascoSch92** [comment]
I think it is a super nice ideas. Moreover, Ruff enable rules for optimization, tipying and docstring.

Good look for the person which has to correct all the errors in the first Ruff PR ;-)

**Comment by Borda** [comment]
@madtoinou I see you added labels, does it mean that it is fine to send a PR? :rabbit:

**Comment by VascoSch92** [comment]
To make things clean: a first set of rules should be discussed here. Just my opinion

**Comment by Borda** [comment]
> To make things clean, a first set of rules should be discussed here to make things clean. Just my opinion

I would suggest enabling Ruff with only already used rules by `flake8`, no additional rules, so have a 1-to-1 switch, and eventually new rules shall be implemented as separate PRs

**Comment by Borda** [comment]
> Ruff looks indeed quite impressing...

One of the main benefits is fixing, meaning it is able to handle not complex issues instead of developers and when added later to a project it can resolve majority of low hanging issues...

**Comment by Borda** [comment]
@madtoinou @VascoSch92 does it mean :green_circle: to go?

**Comment by VascoSch92** [comment]
Some considerations:

- Ruff provides extensive control over various aspects, offering speed and dynamism. Furthermore, starting from version 0.3.0, Ruff includes formatting capabilities in addition to linting. You can configure Ruff in the pyproject.toml, eliminating the need for additional scripts in the project and potentially allowing the removal of Flake-8, thereby improving workflow efficiency. As the project grows in size, having a means to control the style becomes increasingly important.
- If you're considering introducing Ruff, I would recommend starting gradually and then adding rules on a case-by-case basis.

**Comment by madtoinou** [comment]
Hi @Borda,

Just had the opportunity to setup ruff for another project, very nice experience, especially the configuration.

The recently released formatting capabilities is definitely a requirement for darts I would say, and now that it's there, I think you can proceed with the PR, we just need to make sure that ruff is properly configured and the changes to the codebase are minimal.

**Comment by Borda** [comment]
> * If you're considering introducing Ruff, I would recommend starting gradually and then adding rules on a case-by-case basis.

That is for sure have first PR just to get parity with actual linting and anything extra as separate PRs...

**Comment by VascoSch92** [comment]
Hey @Borda
Is this still a thing?
Should I give a try? It should take no so much time ;)

**Comment by Borda** [comment]
> Is this still a thing?

well, I was waiting some kind of approval but here is the the PR #2323 and and then I can continue...

**Comment by VascoSch92** [comment]
ah sorry I didn't saw the PR

**Comment by Borda** [comment]
> ah sorry I didn't saw the PR

i created it just today :flamingo:
