### ISSUE TITLE
Are lags of all components utilized in multivariate forecasting (with XGBoost)?

### ISSUE THREAD

**Issue by dwolffram** [unit8co/darts#2199]
Hi everyone,

thanks a lot for this great package! Currently, I'm working on implementing an XGBoost model to predict a multivariate time series (influenza cases in various national states). I've read a lot of the documentation but I still have a question regarding the internal treatment of different components: The 'lags' parameter allows specifying which lags of the target series should be considered for prediction. However, I'm unsure whether this encompasses the lags of all components or just one. For instance, if the model is trained for state A, does it exclusively utilize the lagged values of state A, or does it also consider the lags of all other states? Alternatively, would it be advisable to include all components as past_covariates as well? 

Thanks for any insights you can provide!

**Comment by dennisbader** [comment]
Hi @dwolffram, it adds the lagged values of **all** target features for each target feature.
