### ISSUE TITLE
Get coefficients of Regression and RegressionEnsemble model

### ISSUE THREAD

**Issue by esnvidia** [unit8co/darts#2200]
Given N models, which are fit. In my case below I the models are already fit:

```
ensemble_probabilistic = RegressionEnsembleModel(forecasting_models=forecast_models, 
                                                 train_forecasting_models=False,
                                                 regression_train_n_points=-1,
                                                 train_using_historical_forecasts=False,
                                                 regression_model=LinearRegressionModel(
                                                     lags_future_covariates=[0],
                                                     lags=None, 
                                                     likelihood="quantile", quantiles=quantiles,
                                                    ),
                                                )

ensemble_probabilistic.fit(
        series=train_transformed,
        past_covariates=time_covariates_transformed,
        future_covariates=time_covariates_transformed,
)

pred_ens = ensemble_probabilistic.predict(len(val), num_samples=300)
```

It's not clear how to extract the N coefficients of the (probabilistic) Regression model.

I find that `len(ensemble_probabilistic.regression_model.model.estimators_)` == num_multivariate_ts ( or num of cols in the df)
but each of the `estimators_` is a `QuantileRegressor(quantile=0.9, solver='highs')` object. Even the first and last.

How can I extract the N coefficient weights? 
Separately, is there built in way to do pruning on the N models to select the K best? (K<=N) criteria like AIC, BIC, or an objective like MSE or MASE can work.

**Comment by madtoinou** [comment]
Hi @esnvidia,

`RegressionEnsemble` is particularly tricky has it can contain many levels of nested models/estimators. I tried to break down the different scenarios:
- If the regression model is deterministic, the coefficient will directly be available in the `.model.coef_` attribute for both uni- and multivariate series and the shape will be `(#component, #component * len(forecasting_models))`
- If the regression model is probabilistic, the `QuantileRegressors` are stored in the `._model_container` attribute  and you can access them by iterating on in : `[m.coef_ for q, m in model.regression_model._model_container.items()]` where q is the quantile value. The "last quantile" estimators contained in `self.model` are an artifact of the training, I am opening a PR to make this less ambiguous.
- `output_chunk_length > 1` and `multi_models=True`, there will be a different set of estimator for each position in the forecast horizon, adding a nested layer. You can find the coefficient with the following : `[(q, m.coef_) for q, e in model.regression_model._model_container.items() for m in e.estimators_]`
- `output_chunk_length > 1` and `multi_models=False` is not supported.

I hope that it helps!

At the moment, `RegressionEnsembleModel` does not support pruning the `forecasting models` to retain only the best ones. We could eventually add it to the roadmap, WDYT @dennisbader?

**Comment by esnvidia** [comment]
So then for a `RegressionEnsemble` one option may be to hyperparameter tune the entire ensemble (including forecasting models) together rather than HP tuning the individual forecasting models and using them as pretrained models. 

Also, two things:
- an example of using `fit_kwargs` would be helpful in the documentation
- `historical_forecasts` essentially employs walkforward validation, correct? So why isn't the `fitted` attribute true? The docs/example for RegressionEnsemble only show using `historical_forecasts`([example here](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Ensembling-models)) and not `fit` and `predict`

**Comment by madtoinou** [comment]
Hyper-parameters for `RegressionEnsemble`  is possible but the number of parameters present in this kind of model makes it quite computationally intensive. It's not a priority in the roadmap.

To answer your other points:
- `fit_kwargs` in `historical_forecasts()` is intented to be used to pass parameters such as `max_samples_per_ts` or model specific argument, such as `feature_weights` for `XGBModel` for example. The parameter is rather self-explanatory, but we will try to come up with a realistic example.
- `historical_forecasts()` does not modify the model it's called with. Hence, calling it on a untrained model with `train=True` will leave the model unfitted.
- You can find an example of `fit()`/`predict()` in this section of the documentation : [Ensembling model](https://unit8co.github.io/darts/examples/19-EnsembleModel-examples.html#Pre-trained-Ensembling).
