### ISSUE TITLE
Save and loaded model

### ISSUE THREAD

**Issue by marcelo-bn** [unit8co/darts#2208]
Hello, guys! I need some help.

I saved my TFT model using the code below:

```
import torch
torch.save(my_model, "my_model.pth")
```
And tried to loaded:

```
import torch
loaded_model = torch.load(my_model, "my_model.pth")
```

When a printed the type of loaded_model variable I got this:

```
darts.models.forecasting.tft_model.TFTModel
```
So, I presume that I save and load the model with the correct way.

BUT, when I run the code below I got the error: AttributeError: 'NoneType' object has no attribute 'set_predict_parameters'

```
series_multivar = TimeSeries.from_dataframe(df_aux, time_col=None, value_cols=df_aux.columns)
predictions = loaded_model.predict(n=24, series=series_multivar)
```

Where is my mistake? Help me, please!

**Comment by madtoinou** [comment]
Hi @marcelo-bn,

Please check out the example in the documentation about saving/loading of deep learning models : [here](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#advanced-functionnalities)

You should use the dedicated methods and not `torch.save/load` as additional logic is required to properly export the Darts models.

**Comment by marcelo-bn** [comment]
Ok, but once again I need to install all the libs just to use a package (I already discuss it in this [issue](https://github.com/unit8co/darts/issues/2206)).

The library requires a small installation for specific models. I'm creating a serverless service using Darts, **but unfortunately I'll have to change libraries because of this limitation.**
