### ISSUE TITLE
How to save underlying data forecast?

### ISSUE THREAD

**Issue by Lotte-V** [unit8co/darts#221]
Is it possible within Darts to not only save the graphs, but also save the underlying data of the forecast?

**Comment by LeoTafti** [comment]
Hi @Lotte-V,

A Darts' `TimeSeries` object is represented internally as a `pandas.DataFrame`, which you can access using `series.pd_dataframe()` (to get a copy of the `DataFrame`).

You can then use any method you'd like to save pandas dataframes, e.g. `pandas.DataFrame.to_csv()` or `pandas.DataFrame.to_pickle()`.

Also note that if you wish to avoid copying the dataframe to save it, you can also get the actual underlying dataframe using `series._df`. Be careful though, as modifying this dataframe in place will break the `TimeSeries` immutability.

**Comment by Lotte-V** [comment]
Thank you @LeoTafti !
