### ISSUE TITLE
Is it possible for covariates to have different time scale than the target feature? 

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2210]
Hi, again friends 👋

My target feature this time is electricity data for electricity data that has the frequency of "15t"
For my covariates features, the frequency is hourly , daily, and weekly.

The way i handled this before is that i merged the datasets on the 15t which works fine, but has the side effect of making the training take a long time. 

Is there any way to give different lags jumps for each past covariate? 
I know i can work around this by setting the lag= lags_past_covariates = list(range(0, -100, -4 ) , so here the past covariate lags would kind of be hourly since only one value will be the lag each hour (since the frequency is 15t).

The issue here is that then this will be the case for each covariate i have. I have not found a solution for saying that one covariate should have a daily frequency lag, and another should have an hourly freq lag and the last one should have a weekly freq lag etc.

So , as far as i can understand this, it can either be solved by somehow allowing the covariates to have different time freq index , which i dont think works. And the workaround would be to use range() to sample another frequency, but with this i dont know how to do it for more than one covariate. 

I hope my issue is clearly described :)

**Comment by madtoinou** [comment]
Hi @Allena101,

If you use a `RegressionModel`, you can specify component specific lags. Check the example in this [notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Component-specific-lags). In combination with using the higher frequency for all the covariates (using resampling if necessary), it should allow you to achieve what you want.

Since a TimeSeries has a unique time index, having a different time frequency for each component is not possible.

**Comment by Allena101** [comment]
> Hi @Allena101,
> 
> If you use a `RegressionModel`, you can specify component specific lags. Check the example in this [notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Component-specific-lags). In combination with using the higher frequency for all the covariates (using resampling if necessary), it should allow you to achieve what you want.
> 
> Since a TimeSeries has a unique time index, having a different time frequency for each component is not possible.

Thanks for the reply, Madtoinou! :)

Would this work as we discussed then (default is t15):

```py
LGBM_Model = LightGBMModel(
    lags=30,
    lags_past_covariates= {"default_lags": [-96 ,-5,-4,-3,-2,-1] , "15_min_component": list((range(-1, -96, -1))),
                           "hourly_component": list((range(-1, -96, -4))), "daily_component": list((range(-1, -672, -96)))},
```

**Comment by Allena101** [comment]
> Yep, this looks right for the component-wise lags definition.
> 
> Just be careful, your first lag is `-1` here so the "hourly/daily_component" for example is actually shifted by 15 minutes compared to the first predicted step. Furthermore, the second argument of `range` is excluded, so you need to subtract one to also include the last value. Overall, you might want to use `list(range(-4, -97, -4))` and `list(range(-96, -673, -96))` if you want the lags to be aligned with the first element of the forecasted period and include respectively the last 24 hours and 7 days.
> 
> Feel free to close the issue if you don't have additional question about this.

thanks alot for seeing the range issue! 

Yes , i will close the issue now :)

**Comment by Allena101** [comment]
thanks alot for seeing the range issue!

Yes , i will close the issue now :)
