### ISSUE TITLE
possible to use darts with .net and/or C# ?

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2215]
based on what i can read on your website and googling the question i am pretty sure you are just focus on python usage. I prefer using python myself , but a discussion came up of implementing a darts project with .net. 

 The other solution would be to just make a python api that dot net can connect to in some manner.

**Comment by madtoinou** [comment]
Hi @Allena101,

Darts is only available in python at the moment and we would recommend using frameworks such as FastAPI to expose endpoints for models that can then be used by other services.

**Comment by Allena101** [comment]
> madtoinou

thanks for teh great reply madtoinou!

I was thinking that using fastAPI would be the answer but i wanted to make sure i had not missed anything directly related to c# / .net .

i will close this issue since the questin is very clearly answered
