### ISSUE TITLE
Demo for Darts timeseries forecasting

### ISSUE THREAD

**Issue by ivelin** [unit8co/darts#2220]
**Lack of integration demo between Darts and Gradio**
Darts is becoming popular for timeseries forecasting. Currently there are no publicly available examples how to integrate Darts with Gradio demo spaces.

**Describe proposed solution**
A demo space would be great as a starting point for timeseries researchers and engineers.

**Additional context**
There are similar demos available for Darts and Streamlit, but Gradio app developers may prefer to continue working with Gradio.

**Comment by ivelin** [comment]
Live demo space here:
https://huggingface.co/spaces/ivelin/darts-demo

**Comment by madtoinou** [comment]
Hi @ivelin,

At the moment, we don't feel like maintaining a live demo of Darts on huggingface/gradio and prefer to focus on the documentation of the library with detailed example notebook which allow for more advanced examples and detailed explanations. 

Closing this for now, might reopen in the future if we find a nice idea of live demo.
