### ISSUE TITLE
Only using Past/Future Covariates for prediction

### ISSUE THREAD

**Issue by LouisEchard** [unit8co/darts#2231]
**Is your feature request related to a current problem? Please describe.**
To my knowledge, the current package doesn't allow us to say we want to predict future horizon 10 of target time-series y, using only past/future covariates (x/z), i.e. preventing the model from using the previous history of time-series y up to t to predict t => t+10.

**Describe proposed solution**
Without looking exactly at the implementation, I would assume it is possible to 0-out // replace by 0 the points/gradients of the historical time-series before passing it inside the model.

This problem arise when the target variable is not very directly seen or there is a delay to get the actual data. (Some data update for t in t+2, but you would like to infer it in t)

My first question is to confirm there is currently no way of doing it and if not see if that could be a future added feature. Some other packages have implemented a similar functionality.

**Comment by madtoinou** [comment]
Hi @LouisEchard,

This is supported by the `RegressionModel`; see [RegressionModel example notebook](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Using-only-covariates)).

The features request to extend it to Deep Learning models is tracked here #2151, it's on the roadmap but will require a considerable amount of work.

If the feature request that you proposed match the issue linked above, could you please close this issue to limit duplicate?
