### ISSUE TITLE
[BUG] Can't use metrics.mase in backtest

### ISSUE THREAD

**Issue by thomktz** [unit8co/darts#2233]
**Describe the bug**
metrics.mase needs an additional 'insample' argument, and thus can't be used in backtest methods, which always call metric(series, forecast) 

**To Reproduce**
backtest() method on any forecasting model, using metric=metrics.mase

**Expected behavior**
Have backtest (and gridsearch?) handle the special case of MASE and give it the right insample for each forecast window. We can't just have metrics_kwargs in backtest since the insample is different for each forecast.

 I think MASE deserves that special treatment since it's the fallback metric for MAPE and SMAPE when there are 0's in the series ("Consider using the Mean Absolute Scaled Error (MASE)..." in the docs). 

**System (please complete the following information):**
 - Python version: 3.11.5
 - darts version: 0.27.2

This issue is a bit similar to #1095, but it would be nice to have a way to do this from within darts. I can make a PR

**Comment by dennisbader** [comment]
Hi @thomktz, and sorry for the late response. This would indeed be great to have. Are you still up for the PR?

**Comment by thomktz** [comment]
Hi @dennisbader, I looked a bit into it, but not sure about the course of action. We need to have `historical_forecasts` (or a new method?) return the [list of `train_series`](https://github.com/unit8co/darts/blob/46004539b929176396310a9550457b6a14571c74/darts/models/forecasting/forecasting_model.py#L1005C13-L1015C22) used to generate the list of forecasts. If we do create a new method (historical_train_series?), then `historical_forecasts` could use it, instead of implementing the whole logic.

What do you think is the right way to do this?
