### ISSUE TITLE
[QUESTION]  Is there a way to remove a specific static_covariate in TimeSeries

### ISSUE THREAD

**Issue by seyni-diop** [unit8co/darts#2235]
Hi there,

I have a simple question. I have a list of `TimeSeries` and i would remove and specific static_covariates (not all).

Is there a method in TimeSeries to do it ? Or anyway

NB: 
I tried the method `TimeSeries.with_static_covariates(None)`, and it removes all static 

Thank you !

**Comment by madtoinou** [comment]
Hi @seyni-diop,

You should be able to use `with_static_covariates` and provide only the static covariates you would like to keep.

```python
import pandas as pd
import numpy as np
from darts import TimeSeries

ts = TimeSeries.from_values(
    np.array([[1,2,3,4,5,5], [2,3,4,1,4,2]]).T,
    static_covariates=pd.DataFrame.from_dict({"loc":[1,0], "cat":[1,2]},
    columns=["A", "B"]
)

# keep only the "loc" static covariate
ts2 = ts.with_static_covariates(ts.static_covariates["loc"])
```

Note that the representation (dataframe axes) of the static covariates will change depending on the number of covariates & components.

**Comment by seyni-diop** [comment]
Hi @madtoinou ,
Thank you for all. It's working well 👌
