### ISSUE TITLE
Scaler should be able to use global_fit on a multivariate series

### ISSUE THREAD

**Issue by dwolffram** [unit8co/darts#2239]
**Is your feature request related to a current problem? Please describe.**
Using [`Scaler`](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.scaler.html) with `global_fit=True` on a multivariate series is still done per-component.

**Describe proposed solution**
All components should be used to fit a single set of parameters if `global_fit=True`.

**Describe potential alternatives**
You could transform the multivariate series into a list of (component) series and after scaling them with `global_fit=True` concatenate them (which is a bit tedious).

**Comment by madtoinou** [comment]
Hi @dwolffram,

`global_fit` refers to single versus multiple series, not the number of components in the series. Fitting a `Scaler` on all the components of a multivariate series is not supported at the moment and would require a dedicated argument.

Since component-wise scaling performed by sklearn, you can actually obtain the desired behavior but implementing a little wrapper and some reshaping:

```python
from darts.dataprocessing.transformers import Scaler
from darts import TimeSeries
from sklearn.preprocessing import MinMaxScaler
import numpy as np

class CustomScaler():
    def __init__(self, scaler = None):
    """Wrapper around sklearn, reshape array to stack series components"""
        if scaler is None:
            self.scaler = MinMaxScaler()
        else:
            self.scaler = scaler

    def fit(self, X: np.ndarray):
        # X.shape = (n_timesteps * n_samples, n_components)
        self.scaler.fit(X.reshape(-1, 1))
        return self

    def transform(self, X: np.ndarray):
        # X.shape = (n_timesteps * n_samples, n_components)
        n_comp = X.shape[1]
        X_tr = self.scaler.transform(X.reshape(-1, 1))
        return X_tr.reshape(-1, n_comp)

    def inverse_transform(self, X: np.ndarray):
        # X.shape = (n_timesteps * n_samples, n_components)
        n_comp = X.shape[1]
        X_tr = self.scaler.inverse_transform(X.reshape(-1, 1))
        return X_tr.reshape(-1, n_comp)

# 2 components, with 2 different scales
x = np.array([[0]*5 + [10]*5, [1]*5 + [100]*5]).T
ts = TimeSeries.from_values(x)
scaler = Scaler(scaler=CustomScaler())
# 1st component goes from 0 to 0.1, 2nd component from 0.01 to 1.
ts_tr = scaler.fit_transform(ts)
```
