### ISSUE TITLE
Prophet return every prediction value

### ISSUE THREAD

**Issue by fawolfmann** [unit8co/darts#224]
**Is your feature request related to a current problem? Please describe.**
In order to create an outlier detection with Prophet, i need the full dataframe that's return Prophet

**Describe proposed solution**
Remove the hardcoded `["yhat"]` from `Prophet.predict` add a variable asking to return just `yhat` or all the predictions: `'yhat_lower', 'yhat_upper', etc..`
https://unit8co.github.io/darts/_modules/darts/models/prophet.html#Prophet.predict

Thanks very much! very useful framework

**Comment by LeoTafti** [comment]
Hi @fawolfmann,

Thanks for reporting.

I think that the solution you propose could indeed be a nice small tweak to the `predict()` method of `Prophet`. It would be nice to keep the current behavior as default though, so maybe adding something like `simple_prediction:bool = True` to the `Prophet.predict()` method could do the trick.

I'll add this to our backlog. In the meantime if you have a little time, feel free to [contribute](https://github.com/unit8co/darts#contribute)!

**Comment by fawolfmann** [comment]
Yes, will code it!

**Comment by enesgur** [comment]
Hello @LeoTafti,

Thanks for the library. It's very useful. Is there any update about this issue?

**Comment by dennisbader** [comment]
Hi @enesgur and thanks for writing and your PR as well.
We are currently working on expanding support for Prophet including this feature.
So stay tuned!

**Comment by enesgur** [comment]
Hi @dennisbader.

You saved me from pure Prophet codes. :) Thanks for your development.
