### ISSUE TITLE
UberTLCDataset load error

### ISSUE THREAD

**Issue by markwkiehl** [unit8co/darts#2240]
The following error is raised when an attempt is made to load the data:
darts.datasets.dataset_loaders.DatasetLoadingException: Expected hash for C:\Users\Mark Kiehl\.darts\datasets\uber_tlc_hourly.csv: 9ed84ebe0df4bc664748724b633b3fe6, got: 2e51cfcb0eaa0ef7bffb8b72a47ff40c

**To Reproduce**
from darts.datasets import (UberTLCDataset)
ts = UberTLCDataset().load()

**Expected behavior**
The data should be loaded into the assigned variable just as it does for all other Darts datasets.

**System (please complete the following information):**
 - Python version: 3.11.2
 - darts version u8darts                      0.26.0

**Additional context**

**Comment by madtoinou** [comment]
Hi @markwkiehl,

I just tried to reproduce the problem with the latest release (0.27.2) and everything went well.

Could it be that you modified the cached file, hence the difference in hash? I would recommend deleting C:\Users\Mark Kiehl.darts\datasets\uber_tlc_hourly.csv and see if downloading the dataset again solves the problem.
