### ISSUE TITLE
Handling Cycle-Based Time Series in Darts.

### ISSUE THREAD

**Issue by Vignesh-Sampat** [unit8co/darts#2244]
I have a cycle dataset which doesn't have a traditional date or time axis. Instead it has a cycle axis with cycle numbers [0,1,2,3,4,5,....n]. Is there any way to Handle Cycle-Based Time Series in Darts?

The cycle numbers are evenly spaced. I could convert cycle numbers to dates (e.g., using a starting date as a reference).
But this approach might introduce implicit seasonality assumptions.

**Comment by madtoinou** [comment]
Hi @Vignesh-Sampat,

You can index `TimeSeries` with `RangeIndex`, and if the cycle numbers don't have duplicates, the conversion should be seamless. See the [user guide](https://unit8co.github.io/darts/userguide/timeseries.html#creating-timeseries).
