### ISSUE TITLE
Q: How can I run this on AMD GPU?

### ISSUE THREAD

**Issue by Erik-02** [unit8co/darts#2252]
I have an AMD GPU, that does not have CUDA available, I am on Windows and do not want to switch to Linux. My GPU does have Directs 12 though and through the use of Microsoft's 'directml' I am able to use my GPU with TensorFlow algorithms. I have also tried other options such as installing 3rd party libraries such as webui and others. I also have tried to do this through an Ubuntu type of setup but still, darts says that there is no supported GPU backend found, I have also tried to install lighting separately, but still when I run 'torch.cuda.is_available()' it always returns False. Is there anything I can do or should I just switch to NVIDEA GPU?

**Comment by madtoinou** [comment]
Hi @Erik-02,

Darts delegates GPU detection/management entirely to Pytorch/Lightning. AMD GPUs should be supported ([official article](https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/)) and `torch.cuda.is_available()` is expected to return True when a GPU is detected.

Let me know if the information in the link above helped you solve the setup problem.

**Comment by Erik-02** [comment]
Hi @madtoinou ,
When looking at the link it shows that pytorch runs on ROCm, and looking at the ROCm website, it does not look like my GOU is supported under windows, I have a RX6500m. Am I missing something?

**Comment by Erik-02** [comment]
I tried it with directml install on windows in [here](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows), the install worked fine although torch.cuda.is_available() still returned false. I then tried doing the install on WSL using Ubuntu however it is unsuccessful due to numerous errors that I cannot resolve.

So I am  giving up for now. Thanks for your help.

**Comment by madtoinou** [comment]
Sorry that you could not fix your problem.

Closing the issue as it's outside of Darts control.
