### ISSUE TITLE
Partially known future_covariates

### ISSUE THREAD

**Issue by dwolffram** [unit8co/darts#2257]
Hi there!

I was wondering if it's possible to use `future_covariates` (in a TFT model) that are only partially known, e.g., if I want to forecast the next 4 weeks and a covariate is only known for the next 2 weeks. Is there perhaps a way to implement this with masking during training? Any advice or ideas would be appreciated. Thank you!

**Comment by dennisbader** [comment]
Hi @dwolffram, this is currently not supported in our `TFTModel` version. We use fixed lengths for the target and covariates. The `future_covariates` must be known `input_chunk_length` points in the past and `output_chunk_length` points in the future.

Adding support for variable lengths is already on our road map, but doesn't have a high priority now. But we're always happy about contributions :)
