### ISSUE TITLE
Getting P-values for linear regression features

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2258]
Is it possible to get evaluate the p-values for each feature in a linear regression model in darts? I can't seem to find the functionality.

**Comment by madtoinou** [comment]
Hi @ETTAN93,

As this is not specific to timeseries forecasting, I would recommend checking the `sklearn` (`sklearn.f_regression` seems to be what you are looking for), `statsmodel` or `scipy` documentation. A quick search yields a lot of code snippet.

You might need the method `model._create_lagged_data(target_series, past_covariates, future_covariates, max_samples_per_ts)` where `model` is an subclass of Darts' `RegressionModel`, which returns the lags and targets (`X` and `y` arrays in `sklearn` convetions). Note that this method is private and its arguments/returns might change without prior notice.

If a lot of users are interested in this, we could eventually add an example in the documentation but I don't have the impression that it's very common.
