### ISSUE TITLE
Inverse scaling for the list of series (different lengths handling)

### ISSUE THREAD

**Issue by alicjakrzeminska** [unit8co/darts#2260]
**Is your feature request related to a current problem? Please describe.**
Currently the Scaler object trained on the list of the TimeSeries doesn't support inverse scaling for the list of lists of TimeSeries with the structure returned by the `historical_forecasts` method (in case of having the list of series as an input).

**Describe proposed solution**
Let's assume that the Scaler is trained on the list of TimeSeries `[A, B, C]`. 
If the `historical_forecasts` is evaluated on the same list of TimeSeries, the example **output** could be:
`[[A_F1, A_F2, A_F3], [B_F1, B_F2], [C_F1, C_F2, C_F3]]` (here the TimeSeries `B` is an example of TimeSeries that is to short to produce 3 forecasts).
The Scaler trained on the mentioned above list of TimeSeries, can accept only triples of TimeSeries like `[A_FX, B_FX, C_FX]`. 

With this in mind, the following solution can be proposed: transformation of the **output** to the list of lists acceptable by the scaler, and iterating over them.

**Describe potential alternatives**
The potential alternative is that the user can write this function outside library, and transform the list of lists TimeSeries to the form acceptable by the Scaler.

**Comment by dennisbader** [comment]
Hi @alicjakrzeminska, this is a great point and will make it much easier to inverse transform the output of historical forecasts. Let's open a PR for this.
