### ISSUE TITLE
Allow passing kwargs to pytorch dataloader

### ISSUE THREAD

**Issue by Jex-y** [unit8co/darts#2271]
I am currently training a model using multiple dataloader workers, however these have a long overhead to start at the beginning of each epoch. Pytorch dataloaders allow persisting the workers and I would like to pass this argument through. 

**Describe proposed solution**
There are other useful arguments like pinning data so I think it would be best to allow arbitrary kwargs passed to the .fit method.

**Describe potential alternatives**
Allow passing a dataloader factory that returns a dataloader when passed the dataset.

**Comment by Jex-y** [comment]
Implementing this here: https://github.com/Jex-y/darts/tree/feature/allow-pt-dataloader-kwargs

**Comment by madtoinou** [comment]
Hi @Jex-y,

Thank you for taking the time to share your code, can you please open a PR with your branch so that it can be reviewed?
