### ISSUE TITLE
[BUG] `TimeSeries.from_group_dataframe` fails if data is not grouped

### ISSUE THREAD

**Issue by elyase** [unit8co/darts#2282]
**Describe the bug**
When creating a TimeSeries object using the `from_group_dataframe` method, the function fails with a ValueError if the input dataframe rows are not sorted by the group column.

**To Reproduce**
```
import pandas as pd
from darts import TimeSeries

df1 = pd.DataFrame( [
    ["item1", 10],
    ["item1", 20],
    ["item2", 100],
    ["item2", 200],
    ["item2", 300],
], columns=["items", "values"])

df2 = pd.DataFrame( [
    ["item1", 10],
    ["item2", 100],    # <--- same data with this element in a different position
    ["item1", 20],
    ["item2", 200],
    ["item2", 300],
], columns=["items", "values"])

# this works
TimeSeries.from_group_dataframe(df1, group_cols="items", value_cols="values")

# this fails with: 
# ValueError: Could not convert integer index to a pd.RangeIndex. Found non-unique step sizes/frequencies: {1, 2}
TimeSeries.from_group_dataframe(df2, group_cols="items", value_cols="values")
```

**Expected behavior**
Both should work

**System (please complete the following information):**
 - Python version: 3.11.6
 - darts version 0.28.0

**Workaround**
```
df2 = df2.sort_values(by=["items"]).reset_index()
```

**Comment by madtoinou** [comment]
Hi @elyase,

Thank you for reporting this and the detailed code snippet. The creation of the `TimeSeries` fails because since you do not provide a time column, the method is trying to use the index. However, the inconsistent spacing between entries make the frequency ambiguous, as both `1` and `2` appear as likely candidates for the `item2` group.

Since the workaround is rather straightforward, I would probably leave things as is to prevent unexpected results. WDYT @dennisbader ?

**Comment by elyase** [comment]
Thanks for your response @madtoinou. If a user doesn't specify a time column in `TimeSeries.from_group_dataframe`, does that mean that the frequency is assumed to be 1 within each group, rather than 2 as the frequency guessing code presumes?

**Comment by elyase** [comment]
make sense! thanks @madtoinou @dennisbader for the great library and taking the time to explain. As a user, I realize I may have had unrealistic regarding handling time columns automatically for ordered groups with gaps. My "logic" was if darts can work without me providing a time column (by magically using the df index) I was also expecting that to be also done for me in the case of ordered but discontinuous groups.

For future users with this use case I will add a second workaround after @dennisbader suggestion that doesn't involve sorting:

```
df2.set_index(df2.groupby("items").cumcount(), inplace=True)
```

I did receive a warning, although I am not certain if it is justified in this particular instance.

```
UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
```
