### ISSUE TITLE
is there a guide for Explainability?

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2291]
Can't figure out how to use this functionality from reading the docs. I have seen and used the guide for the TFTModel (which worked great).

**Comment by dennisbader** [comment]
Hi @Allena101, we don't have a guide yet for Explainability but it's on our backlog.

For `ShapExplainer` for our regression models, we have a little example in [this notebook section](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Explainability).

**Comment by Allena101** [comment]
thank you, Dennis. I will check the notebook out!
