### ISSUE TITLE
Translate the Darts documentation into Chinese

### ISSUE THREAD

**Issue by BrainCai** [unit8co/darts#2297]
**I want to translate Darts doc into Chinese , make this great repo more and more popular, anyone there work with me ?**
-> into Chinese:
想把Darts的文档，翻译成中文，有没有人一起，让Darts更加有影响力。

**Comment by CyAlcher** [comment]
anyone here? 有人吗？

**Comment by CyAlcher** [comment]
@madtoinou thanks for reply,I'm from China and want to translate into Chinese.The doc will post in my github.

**Comment by shandongpengyuyan** [comment]
您好，请教您一下darts的使用，用darts构建的模型，要在测试集上测试，应该怎么做呢？数据是2015年到2022年的里面包含协变量，用15年到21年的训练模型，设置的模型预测输出是一个月，调用.predict（12，past_cov=cov）使用预测出来的值继续往后滚动预测的，往后继续预测的时候能不能替换成真实的预测变量，来预测下一个月的。

**Comment by shandongpengyuyan** [comment]
> @madtoinou thanks for reply,I'm from China and want to translate into Chinese.The doc will post in my github.

您好，请教您一下darts的使用，用darts构建的模型，要在测试集上测试，应该怎么做呢？数据是2015年到2022年的里面包含协变量，用15年到21年的训练模型，设置的模型预测输出是一个月，调用.predict（12，past_cov=cov）使用预测出来的值继续往后滚动预测的，往后继续预测的时候能不能替换成真实的预测变量，来预测下一个月的。

**Comment by shandongpengyuyan** [comment]
> **I want to translate Darts doc into Chinese , make this great repo more and more popular, anyone there work with me ?** -> into Chinese: 想把Darts的文档，翻译成中文，有没有人一起，让Darts更加有影响力。

您好，请教您一下darts的使用，用darts构建的模型，要在测试集上测试，应该怎么做呢？数据是2015年到2022年的里面包含协变量，用15年到21年的训练模型，设置的模型预测输出是一个月，调用.predict（12，past_cov=cov）使用预测出来的值继续往后滚动预测的，往后继续预测的时候能不能替换成真实的预测变量，来预测下一个月的。

**Comment by CyAlcher** [comment]
1. ① 时间序列的训练、验证、测试 是按照时间划分的；② darts官方文档中有介绍，可以看下哈；

**Comment by CyAlcher** [comment]
@shandongpengyuyan 
1. ① 时间序列的训练、验证、测试 是按照时间划分的；② darts官方文档中有介绍，可以看下哈；
2. darts中有两类cov，① past_cov 是未来不可知的；② future_cov 是未来可知的；如果给的是past就不能替换为未来的；
Support for Covariates[¶](https://unit8co.github.io/darts/userguide/forecasting_overview.html#support-for-covariates)

**Comment by shandongpengyuyan** [comment]
@CyAlcher 谢谢您的解答，训练的时候设置的预测窗口是1，predict调用的窗口大于1，darts是会用上一步模型预测出来的值（这里能不能换成真实的预测变量，继续往下预测），再结合协变量往下预测直到预测到调用的窗口大小吗？

**Comment by CyAlcher** [comment]
@shandongpengyuyan 建议看下预测策略哈。预测未来T+2、T+3 ，是不能用真实的T+1替换模型输出T+1的预测值的，做了就是label的时间穿越了，虽然预测效果好，但是用了实际预测任务不能看到T+1的真值，模型上线预测会精度会下降而且会报错；未来已知协变量时可用的。
