### ISSUE TITLE
Add ExtraTreesRegressor

### ISSUE THREAD

**Issue by rijkvandermeulen** [unit8co/darts#2298]
Hey darts dev team!

For a specific use case I need to work with the (sklearn) [ExtraTreesRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesRegressor.html). The model is similar to the RandomForestRegressor with two (main) differences:

1. RF is using bootstrapping whereas ExtraTrees is using the whole sample. I guess even with a RF model this behaviour can be enforced though by setting the bootstrap parameter to False.
2. A more import difference is the selection of cut points in order to split nodes. RF chooses the optimum split while Extra Trees chooses it randomly (making it computationally faster). However, once the split points are selected, the two algorithms choose the best one between all the subset of features. Therefore, Extra Trees adds randomization but still has optimization.

Would you be open to adding the ExtraTreesRegressor to the darts api? I'm more than happy to pick this up myself and create a PR.

**Comment by madtoinou** [comment]
Hi @rijkvandermeulen,

`ExtraTreesRegressor` is already supported by wrapping it inside the `RegressionModel` class of Darts;
```python
from darts.datasets import AirPassengersDataset
from darts.models import RegressionModel
from sklearn.ensemble import ExtraTreesRegressor

ts = AirPassengersDataset().load()
train, test = ts.split_after(0.8)
model = RegressionModel(lags=3, model=ExtraTreesRegressor(n_estimators=50))
model.fit(train)
pred = model.predict(len(test))
```

Do you think that there is something that would justify creating a new model class specific to this sklearn model?

**Comment by rijkvandermeulen** [comment]
Hey @madtoinou,

Ah awesome, I was not aware of that functionality yet; that's very useful!! No, knowing this I'd say there is definitely no need to create a separate model class. I'll close the ticket.
