### ISSUE TITLE
Support for adding static covariates included in each row of time series

### ISSUE THREAD

**Issue by chododom** [unit8co/darts#2306]
I am confused by how the incorporation of covariates is supposed to work with the TimeSeries class.
I am trying to forecast weather data and for each row in my dataset, I have several of the target variables that I am predicting (temperature, humidity, etc.) and each row also has the covariates hour of day, day of year, etc.

I cannot figure out how to easily incorporate the covariates in the dataset during creation, I try to run the following:
```
# ts is my pandas dataframe with time series
statics = ts[['hour', 'quarter', 'dayofyear']]
train_ts = TimeSeries.from_dataframe(ts, 
                                         time_col='dt', 
                                         value_cols=['temperature', 'pressure', 'wind_dir', 'rel_humid'], 
                                         static_covariates=statics
                                        )
```

But this fails with `When passing a multi-row pandas DataFrame, the number of rows must match the number of components of the TimeSeries object (multi-component/multi-row static covariates must map to each TimeSeries component)` which I find somewhat unintuitive.

Additionally, I am trying to do this in a loop in order to create a couple of thousands of separate time series (one time series per measured sequence from a given weather station) to train the model on.

```
series = []
for i in station_ids:
    ts = data[data.station_id == i]
    statics = ts[['hour', 'quarter', 'dayofyear']]
       
    train_ts = TimeSeries.from_dataframe(ts, 
                                         time_col='dt', 
                                         value_cols=['temperature', 'pressure', 'wind_dir', 'rel_humid'], 
                                         static_covariates=statics
                                        )

    series.append(train_ts)

...

model.fit(series)
```

I would greatly appreciate any tips on figuring out a good best-practice way of doing this.

**Comment by madtoinou** [comment]
Hi @chododom,

The covariates should be stored in another `TimeSeries` that is called either "past" of "future" covariates, see this [illustration](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Covariates:-using-external-data). The static covariates attribute of the `TimeSeries` corresponds to values that remain constant over time/are independent of the index's timestamp.

You code should be something like:
```python
    # future covariates because the values can are known in the future
    future_cov = ts[['hour', 'quarter', 'dayofyear']]
    # extract the columns corresponding to the forecasted quantities.
    train_ts = TimeSeries.from_dataframe(ts, 
                                         time_col='dt', 
                                         value_cols=['temperature', 'pressure', 'wind_dir', 'rel_humid'], 
                                        )
```

I hope that this helps.

**Comment by dennisbader** [comment]
Hi @chododom, as @madtoinou said, you have to pass the hour, quarter, ... as `future_covariates` to model.fit()/predict() (or `past_covariates` if the model doesn't support future covs). This is because they are dynamic/time dependent.

Static covariates refer to constant characteristics of your target series, and would for example be the "station_id".

For your second example, you can use [`TimeSeries.from_group_dataframe()`](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.from_group_dataframe) with `group_col="station_id"`, which will return a list of series for all the different stations. This will also add the station ID as static covariates (if it's categorical you'll have to transform the static covariates to numeric as described [here](https://unit8co.github.io/darts/examples/15-static-covariates.html#5.-Scaling/Encoding/Transforming-static-covariate-data)). 

So with all of this, you can create your target series and future covariates as shown below:

```
target = TimeSeries.from_group_dataframe(
    ts,
    group_cols="station_id",
    time_col='dt',
    value_cols=['temperature', 'pressure', 'wind_dir', 'rel_humid'],
)

future_covariates = TimeSeries.from_group_dataframe(
    ts,
    group_cols="station_id",
    time_col='dt',
    value_cols=['hour', 'quarter', 'dayofyear'],
)
```

**Comment by chododom** [comment]
@madtoinou @dennisbader Thank you so much for the advice, it helped me move further along with my problem.

I ended up solving the time-based future covariates using:

```
month_series = datetime_attribute_timeseries(
    pd.date_range(start=ts.start_time(), end=ts.end_time(), freq="H"), attribute="month", one_hot=True
)
    
hour_series = datetime_attribute_timeseries(
    pd.date_range(start=ts.start_time(), end=ts.end_time(), freq="H"), attribute="hour", one_hot=True
)

ts_covariates = month_series.stack(hour_series)
```

Since I was getting errors when providing these covariates along with a multi-series data source, I ended up creating the covariates for months and hours per each training series created by grom_group_dataframe:

```
train_covariates = []
for ts in train_transformed:
    month_series = datetime_attribute_timeseries(
    pd.date_range(start=ts.start_time(), end=ts.end_time(), freq="H"), attribute="month", one_hot=True
    )
    
    hour_series = datetime_attribute_timeseries(
        pd.date_range(start=ts.start_time(), end=ts.end_time(), freq="H"), attribute="hour", one_hot=True
    )

    ts_covariates = month_series.stack(hour_series)
    train_covariates.append(ts_covariates)
```

I am posting this in case someone has a similar use case, but also if you have any feedback to implementing this in this way, I will gladly adjust the logic in accordance with your recommendations.

Thank you again, so far I am having a very positive experience with the library and its suppor :)
