### ISSUE TITLE
[QUESTION] How can I use shapExplainer when using multi_models=False?

### ISSUE THREAD

**Issue by guilhermeparreira** [unit8co/darts#2313]
Hi There! 

I want to use `shapExplainer` to understand how past and future covariates are related to the target. 

I am using:

 ```python
from darts.models import RegressionModel
model = RegressionModel(..., multi_models=False)
model.fit(...)
shap_explain = ShapExplainer(model)
```

And I got the error message, that is very clear to me:
```bash
ValueError: Invalid `multi_models` value `False`. Currently, ShapExplainer only supports RegressionModels with `multi_models=True`.
```

Is there a workaround for this?
Do you guys intend to implement the Shap for `multi_models=False`? (Does it make sense?)

Thanks in advance!

**Comment by madtoinou** [comment]
Hi @guilhermeparreira ,

This feature request is tracked in #1686. I started working on it a while ago (in branch `shap_multi_models`) but after discussing with the contributor who implemented the Darts Explainability module, I need to revert some of my changes and I did not have the time to go back to it, I hope to be able to do so soonish.

In the meantime, I would recommend using `multi_models=True`, even if it means that one model will be trained for each position in `output_chunk_shift`, you should still be able to extract meaningful information about the impact of each covariates (and potentially see if they have a different influence depending on the forecasted position).

**Comment by guilhermeparreira** [comment]
Alright!! Thank you!!
