### ISSUE TITLE
Add IQR Anomaly Detector

### ISSUE THREAD

**Issue by david-waterworth** [unit8co/darts#2319]
**Is your feature request related to a current problem? Please describe.**
I'd like to detect outliers using the Interquartile range (IQR) method, i.e. an outlier is a point that lies more than 1.5 * IQR above(below) the upper(lower) quartile

**Describe proposed solution**
Similar to the QuantileDetector but use calculation IQR = (Q3-Q1) where Q1 and Q3 are the 25th and 75th quartiles. Then set the upper fence at Q3 + 1.5*IQR and the lower fence to Q1 - 1.5*IQR

**Describe potential alternatives**
I'm not aware of any alternative.

**Additional context**

**Comment by u8-igor** [comment]
I'm on it
