### ISSUE TITLE
`inverse_transform` and multivariate time series

### ISSUE THREAD

**Issue by LeoTafti** [unit8co/darts#232]
`DataTransformer.inverse_transform` isn’t easy to use with multivariate time series in a “real” use case situation. I think a very common use case would be to:

1. transform the multivariate time series (e.g. re-scale using `scaler`)
2. make a prediction for a single main target variable: say `forecast` holds that prediction
3. inverse transform back to the original scale

For 3. I'd like to be able to call `scaler.inverse_transform(forecast)`, but there's a dimension mismatch: `inverse_transform()` expects a multivariate time series here (in particular a multivariate time series of the same width it was fitted with). The scaler cannot know which variable(s) the forecast corresponds to.

There are workarounds, but I couldn't come up with a clean and easy way… Can someone think of one?

**Comment by mazafi-dsg** [comment]
Hi guys, 
Is there any news about this feature?

**Comment by hrzn** [comment]
> Hi guys, Is there any news about this feature?

This is an older issue that was raised when Darts was handling dimensions differently. Normally now this case should not occur as such - forecasting on a multivariate target produces a multivariate forecast of the same dimensions, which can then seamlessly be inverse-transformed by a transformer fit on the target.
May I ask you what is your particular use-case where this causes an issue?
