### ISSUE TITLE
[BUG] FutureWarning: Series.fillna with 'method' is deprecated

### ISSUE THREAD

**Issue by FlorinAndrei** [unit8co/darts#2325]
**Describe the bug**
Running the hyperparameter optimization example https://unit8co.github.io/darts/examples/17-hyperparameter-optimization.html

In the Data Preparation section there is this code fragment:

```python
all_series = ElectricityDataset(multivariate=False).load()
NR_DAYS = 80
DAY_DURATION = 24 * 4  # 15 minutes frequency

all_series_fp32 = [
    s[-(NR_DAYS * DAY_DURATION) :].astype(np.float32) for s in tqdm(all_series)
]
```

It generates a large number of these warnings:

```
/Users/florin.andrei/Library/Python/3.11/lib/python/site-packages/darts/datasets/__init__.py:550: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  start_date = min(srs.fillna(method="ffill").dropna().index)
/Users/florin.andrei/Library/Python/3.11/lib/python/site-packages/darts/datasets/__init__.py:551: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  end_date = max(srs.fillna(method="bfill").dropna().index)
```

**To Reproduce**
Just run the example.

**Expected behavior**
No warnings should be thrown.

**System (please complete the following information):**
 - Python version: 3.11.9
 - darts version: 0.28.0

**Additional context**
- MacBook Pro
- Apple M3 Pro
- macOS Sonoma 14.4.1
- pandas 2.2.2
- tqdm 4.66.2

**Comment by dennisbader** [comment]
Hi @FlorinAndrei and thanks for raising this issue. Would you be willing to contribute a fix for this?

**Comment by FlorinAndrei** [comment]
Unfortunately I'm quite busy right now. If that changes, I may take a look at this issue, but that's unlikely.
