### ISSUE TITLE
While importing darts it  throws cannot import name 'TypeAliasType' from 'typing_extensions' error

### ISSUE THREAD

**Issue by anusonawane** [unit8co/darts#2328]
I'm encountering an ImportError while trying to import TypeAliasType from typing_extensions. Here's the traceback:

from darts import TimeSeries
  from darts.models import RandomForest, LinearRegressionModel

File "/home/env/lib/python3.11/site-packages/darts/utils/utils.py", line 13, in <module>
    from IPython import get_ipython
    
...
File "/home/env/lib/python3.11/site-packages/IPython/core/guarded_eval.py", line 40, in <module>
    from typing_extensions import TypeAliasType
    
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/env/lib/python3.11/site-packages/typing_extensions.py)
This error seems to be occurring within the context of the Darts library, specifically when importing TypeAliasType from typing_extensions. However, it appears that TypeAliasType is not present in the typing_extensions module.

I'm using Python 3.11 and have the following relevant packages installed:

u8darts: 0.18.0
IPython: 8.23.0
typing-extensions:4.5.0

Could someone please provide guidance on how to resolve this issue?

Thank you for your help!

**Comment by dennisbader** [comment]
Hi @anusonawane, you seem to be using an outdated Darts version (version 0.18.0 from March 2022). This was even before python 3.11 was released (October 2022). Is there a specific reason why you don't update to a newer Darts version? These issues should be solved by updating.
