### ISSUE TITLE
[Question] Extract training data and target from a model at timestep t

### ISSUE THREAD

**Issue by nkonts** [unit8co/darts#2331]
Hi,

I am currently exploring your library and working through some example notebooks.  To gain more confidence in what is happening under the hood, is there a possiblity to extract the X and y similar to what is shown as `resulting arrays` [in the Lagged data extraction image from the Regression Models example](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Lagged-data-extraction)?

I was not able to find a way while going through your API reference or inspecting the attributes of the LinearRegressionModel object.

**Comment by madtoinou** [comment]
Hi @nkonts,

The `RegressionModel._create_lagged_data()` method is responsible for creating the `X` and `y` arrays. Under the hood, it calls `create_lagged_training_data()` from the tabularization module ([doc](https://unit8co.github.io/darts/generated_api/darts.utils.data.tabularization.html?highlight=create_lagged#darts.utils.data.tabularization.create_lagged_training_data)).

I hope that it solves your problem.
