### ISSUE TITLE
[Question] How could I hide the "Finding best initial lr" message from pytorch_lightning when using Darts' Torch Forecasting Models?

### ISSUE THREAD

**Issue by fmerinocasallo** [unit8co/darts#2334]
I am unable to hide the `Finding best initial lr` message when calling the [`lr_find` method](https://github.com/unit8co/darts/blob/c3a611236690f0704ced6078982adf20b0a33886/darts/models/forecasting/torch_forecasting_model.py#L1111) associated with Darts' Torch `Forecasting Models`, such as `BlockRNNModel`:

![image](https://github.com/unit8co/darts/assets/469246/1e9a8603-72ec-44ef-b31c-0be04251b94d)

Based on my understanding, this message is generated by `pytorch-lightning`. In particular, by the [`on_train_batch_start` method](https://github.com/Lightning-AI/pytorch-lightning/blob/58ad56afece3ea7faec2f1b7f68d90195f316d78/src/lightning/pytorch/tuner/lr_finder.py#L384)  from the [`_LRCallback` class](https://github.com/Lightning-AI/pytorch-lightning/blob/58ad56afece3ea7faec2f1b7f68d90195f316d78/src/lightning/pytorch/tuner/lr_finder.py#L349). At least in this specific case :thinking: 

I have tried the following:
1. Including `verbose=False` when calling the `lr_find` method.
2. Passing a `TQDMProgressBar(refresh_rate=0)` instance through the `callbacks` list in the `pl_trainer_kwargs` dict passed to the `BlockRNNModel` constructor.
3. Including an `"enable_progress_bar": False` in the `pl_trainer_kwargs` dict passed to the `BlockRNNModel` constructor.

So far, no luck :disappointed: 

I don't know if I have misunderstood something or I am missing some critical bit of information :grimacing:

Could you help me solve this issue? :pray:

Any feedback would be much appreciated :relaxed: 

***

I am using:
- python 3.11.0
- darts 0.28.0
- pytorch_lightning 1.9.5

Let me know if there are any missing but relevant and clarifying details I should mention.

**Comment by dennisbader** [comment]
Hi @fmerinocasallo. Unfortunately, I think there is currently no built-in/easy way to disable the `lr_find` progress bar.
As you say, the progress bar comes from `pytorch_lightning`, spefically from [`pytorch_lightning.tuner.tuning.Tuner.lr_find()`](https://lightning.ai/docs/pytorch/stable/api/pytorch_lightning.tuner.tuning.Tuner.html#lightning.pytorch.tuner.tuning.Tuner.lr_find). It seems like `lr_find()` currently doesn't offer a way to disable the progress bar.

If this was supported by lightning, we can add support for it to Darts as well.
