### ISSUE TITLE
Can we add past_covariates and future_covariates to  support in  darts/darts/models/forecasting /exponential_smoothing.py ?

### ISSUE THREAD

**Issue by akshobhya95** [unit8co/darts#2349]
Hi Darts Team ,
                         I was using the exponential_smoothing time series forecasting model to forecast my univariate target variable with the support of exogenous feature variables for my dataset . But I see from the python script in  exponential_smoothing.py doesn't support historical_forecasts with past/ future_covariates in the library. I see few other models do support exogenous variables being supported would appreciate if you could add the same code logic to this model as well as it would be helpful for testing my case with exogenous variables

Also I was using other darts forecasting model asin Prophet(using only future_covariates) and SARIMA(using only future_covariates) I am interchangeably treating future_covariates as past_covariates in my case , But if the library code does give a physical meaning to what we use would appreciate to add past_covariate information to Prophet and ARIMA forecasting models.

Code Snippet:-
=============

[darts/utils/historical_forecasts/utils.py](https://github.com/unit8co/darts/blob/6f13a2f1554bd4fef06df44d287bbd51b6d76878/darts/utils/historical_forecasts/utils.py#L573)

<html>
<body>

series=series,
--
571 | forecast_horizon=forecast_horizon,
572 | overlap_end=overlap_end,
573 | past_covariates=past_covariates, ----->Needs support in ARIMA.py ,Prophet.py and Exponential Smoothing.py
574 | future_covariates=future_covariates,----> Needs support in Exponential Smoothing.py

</body>
</html>

Would appreciate your response on this !

-Thanks and Regards ,
Akshobhya.

**Comment by madtoinou** [comment]
Hi @akshobhya95,

By "design/definition", exponential smoothing does not support covariates at all. I don't know how you managed to pass it covariates?

Making Prophet and ARIMA support past covariates would be equivalent to developing new models, which is not in our priorities.

If you have some covariates at your disposition, I would recommend using focusing on models that already support them or use the other models without the covariates.

**Comment by akshobhya95** [comment]
Thanks for making it clear @madtoinou.
