### ISSUE TITLE
Does Darts provide methods for unsupervised anomaly detection models?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2355]
Based on the [darts documentation](https://unit8co.github.io/darts/generated_api/darts.ad.anomaly_model.html) on anomaly models, it seems like the 2 available ones - filtering anomaly model and forecasting anomaly model both require the model to be initially fitted to a series without anomalies, i.e. a supervised anomaly detection model.

Is my understanding correct? Does Darts offer any unsupervised models for anomaly detection?

**Comment by madtoinou** [comment]
Hi @ETTAN93,

At the moment, Darts does not offer any unsupervised models for anomaly detection but it can be added to the roadmap, especially if contributors propose architectures and open PRs.

**Comment by ETTAN93** [comment]
@madtoinou thanks for that.

Another thing to clarify, I used eval_accuracy in darts as part of the [quantile detector class](https://unit8co.github.io/darts/generated_api/darts.ad.detectors.quantile_detector.html) and compared it to the results I got from [sklearn's recall_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html).

I passed the same y_test and y_pred series to both:

```
qd_recall = qd.eval_accuracy(y_test_series, qd_y_pred_series, metric='recall')

sklearn_recall = recall_score(y_test_series.pd_series(), qd_y_pred_series.pd_series())
```

For some reason, I am getting the inverse of values from both, i.e. when I sum the two recall scores, I end up with 1.0. In this particular case, qd_recall from darts returns me 0.9946808510638298 whereas the recall_score from sklearn returns me 0.005319148936170213.

Am I passing in the wrong parameters to the darts function? As far as I understand, the anomaly_score parameter should be the  y_pred_series from the model? what does the window parameter do?

**Comment by dennisbader** [comment]
Hi @ETTAN93, `QuantileDetector.eval_accuracy()` expects the predicted scores from the Scorer and not the output of `QuantileDetector.detect()`.

The following should work:

```
# darts
td = QuantileDetector(high_quantile=0.5)
anom_pred = td.fit_detect(scores_pred)
td_recall = td.eval_accuracy(anom_true, scores_pred, metric="recall")

# sklearn
sl_recall = recall_score(
    anom_true.slice_intersect(anom_pred).pd_series(), 
    anom_pred.slice_intersect(anom_true).pd_series()
)

print(td_recall, sl_recall)
```

outputs: `(0.6923, 0.6923)`

**Comment by ETTAN93** [comment]
@dennisbader how is the `scores_pred `defined?

**Comment by dennisbader** [comment]
It can be any numeric non-binary input series. The detector converts non-binary to binary.
In the example above it was the output from [`KMeansScorer.score()`](https://unit8co.github.io/darts/generated_api/darts.ad.scorers.kmeans_scorer.html#darts.ad.scorers.kmeans_scorer.KMeansScorer). But you can also use it on other series as shown below:


```
from sklearn.metrics import recall_score

from darts import TimeSeries
from darts.ad import QuantileDetector
from darts.datasets import AirPassengersDataset

series = AirPassengersDataset().load()

# flag values above 400 as anomalies
anom_true = TimeSeries.from_dataframe(
    series.pd_dataframe() > 400
)

# darts
qd = QuantileDetector(high_quantile=0.95)
anom_pred = qd.fit_detect(series)
qd_recall = qd.eval_accuracy(anom_true, series, metric="recall")

# sklearn
sl_recall = recall_score(
    anom_true.slice_intersect(anom_pred).pd_series(),
    anom_pred.slice_intersect(anom_true).pd_series()
)

print(qd_recall, sl_recall)
```
gives `(0.2857, 0.2857)`
