### ISSUE TITLE
[Question] Are features scaled when using add_encoders?

### ISSUE THREAD

**Issue by AshwinPuri13** [unit8co/darts#2358]
When using add_encoders in model initialization, are the generated features scaled?

For example, say I want to fit a Ridge regression model with lags and an index variable:

```
from sklearn.linear_model import Ridge

add_encoders = {
    'position': {'future': ['relative']},
    'transformer': Scaler(),
}

lags = [-1,-2,-3]
model = RegressionModel(model = Ridge(), lags = lags, add_encoders = add_encoders, lags_future_covariates=[0])

```

Ideally I'd want the _position_ variable that was created from add_encoders to be scaled as well.

**Comment by dennisbader** [comment]
Hi @AshwinPuri13. Yes, the transformer (in your case `Scaler`) will transform the relative position values.
The transformer is fit on all relative position values generated by the encoder for the train split. If you're using multiple series (`series` is a sequence/list of `TimeSeries`), then the transformer is fit on the concatenated relative positions generated for all series.

**Comment by AshwinPuri13** [comment]
Ah so I can just check if the encoder has an accept_transformer attribute. Got it, thanks
