### ISSUE TITLE
[BUG] TimeSeries should support the fill_missing_dates=False without freq

### ISSUE THREAD

**Issue by joshua-xia** [unit8co/darts#2368]
**Describe the bug**
When I use TimeSeries.from_dataframe(df, value_cols='Close', fill_missing_dates=False) to create TimeSeries from dataframe.
It will fail because ValueError: The time index of the provided DataArray is missing the freq attribute.

I have to  create TimeSeries from dataframe by using TimeSeries.from_dataframe(df, value_cols='Close', fill_missing_dates=False, freq='B')

That will generate  TimeSeries with missing value(NaN) even though my original dataframe has no any NaN value, it may be fill_missing_dates according to 'B' freq.

But in my scenes, for example, the stock historical prices series, it is very hard to align the dates to freq='B' because the prices value is missing in holiday, I have to use fill_missing_values as workaround. In fact, It should not fill_missing_values because the interpolate will change the original data.

So I suggest TimeSeries.from_dataframe support keep all original data from dataframe, no interpolate need.

**Comment by dennisbader** [comment]
Hi @joshua-xia, have a read at #2149 where we explain the reasons behind this, and why we will not add support for it.
