### ISSUE TITLE
Rolling prediction ；validation model

### ISSUE THREAD

**Issue by shandongpengyuyan** [unit8co/darts#2371]
My data was collected on a monthly basis from 2015 to 2022, which includes exogenous variables that vary over time. The model was trained using data from 2015 to 2021, with a prediction window of one month. The model was validated on the data from 2022 (12 step prediction). How to input the real predictive variables into the model and predict together with exogenous variables when making downward predictions.

**Comment by dennisbader** [comment]
Hi @shandongpengyuyan, I'm not 100% sure I understand your question. 

[This section](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Model%E2%80%99s-output-chunk-length) in our Regression Model example notebook describes the difference between auto-regressive and one-shot forecasts, and also how exogenous variables are used (call `past_covariates` and `future_covariates` in Darts). The extraction of the correct covariates is done behind the hood by the models.
