### ISSUE TITLE
Tsmixer incorrect loss_fn/likelihood documentation 

### ISSUE THREAD

**Issue by tRosenflanz** [unit8co/darts#2372]
Tsmixer loss_fn/likelihood documentation is copied over from TFT model (even includes TFT in the words). This leads to the impression that TSMixer is a probabilistic model while the implementation is actually deterministic with MSE as loss_fn which is faithful to the paper

Reproduce:
1. Define model without specifying loss_fn or likelihood (which should be removed from the docs if I am reading the code right)
2. call `.fit` to initiate the model 
3. call `.model` 
Result
```
_TSMixerModule(
  (criterion): MSELoss()
```

**Comment by dennisbader** [comment]
Hi @tRosenflanz, and thanks for pointing this out. We'll fix it soon.
