### ISSUE TITLE
[BUG] darts should support re-training base on the old checkpoint, not reset the model

### ISSUE THREAD

**Issue by joshua-xia** [unit8co/darts#2378]
**Describe the bug**

I meet the following error:
if checkpoint_exists and save_checkpoints:
            raise_if_not(
                force_reset,
                f"Some model data already exists for `model_name` '{self.model_name}'. Either load model to continue "
                f"training or use `force_reset=True` to initialize anyway to start training from scratch and remove "
                f"all the model data",
                logger,
            )
            self.reset_model()

when I create model by using following setting to reload the old checkpoint and then re-train the model
 save_checkpoints=True,
 force_reset=False,
 model_name=self.name,
 work_dir=self._path,

I think we should support user load the old checkpoint automatically when create model and re-tain to generate the new checkpoint, ligthing support this behavior and it's ModelCheckpoint generate checkpoint with version number for example: my-checkpoint-v0,......my-checkpoint-v5 and so on.

Why we force to reset the model and lost all data from checkpoint.

**Comment by madtoinou** [comment]
Hi @joshua-xia,

In order to resume training from existing checkpoint, you should use the code snippet showed [in the documentation](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html):
```python
# model with identical architecture but different optimizer (default: torch.optim.Adam)
model_finetune = SomeTorchForecastingModel(
     ...,  # use identical parameters & values as in original model
     optimizer_cls=torch.optim.SGD,
     optimizer_kwargs={"lr": 0.001}
)
# load the weights from a checkpoint
model_finetune.load_weights_from_checkpoint(model_name='my_model', best=True)
# because the model has a different name, the checkpoints will not overlap
model_finetune.fit(...)
```

This will give your more control on the parameters and avoid unexpected behavior.

If you want to further customize the check-pointing behavior, you can still use the `ModelCheckpoint` callback. However, in order to load the resulting checkpoint, you'll need the `.pth.tar` file (which will not be exported by `ModelCheckpoint`, so you should keep the "default" checkpoints as well and then copy the file).

```python
# create the callback
checkpoint_callback = ModelCheckpoint(...)
# recreate the model architecture with the callback
model = DLinearModel(
    ...,
    save_checkpoints=True,
    pl_trainer_kwargs={"callbacks":[checkpoint_callback]}
)
# load the weights only
model.load_weights_from_checkpoint(base_model_name, best=True)
# fine-tune/retrain
model.fit(train, val_series=val, epochs=10)
```

Let me know if these workarounds work for you.

**Comment by joshua-xia** [comment]
> Hi @joshua-xia,
> 
> In order to resume training from existing checkpoint, you should use the code snippet showed [in the documentation](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html):
> 
> ```python
> # model with identical architecture but different optimizer (default: torch.optim.Adam)
> model_finetune = SomeTorchForecastingModel(
>      ...,  # use identical parameters & values as in original model
>      optimizer_cls=torch.optim.SGD,
>      optimizer_kwargs={"lr": 0.001}
> )
> # load the weights from a checkpoint
> model_finetune.load_weights_from_checkpoint(model_name='my_model', best=True)
> # because the model has a different name, the checkpoints will not overlap
> model_finetune.fit(...)
> ```
> 
> This will give your more control on the parameters and avoid unexpected behavior.
> 
> If you want to further customize the check-pointing behavior, you can still use the `ModelCheckpoint` callback. However, in order to load the resulting checkpoint, you'll need the `.pth.tar` file (which will not be exported by `ModelCheckpoint`, so you should keep the "default" checkpoints as well and then copy the file).
> 
> ```python
> # create the callback
> checkpoint_callback = ModelCheckpoint(...)
> # recreate the model architecture with the callback
> model = DLinearModel(
>     ...,
>     save_checkpoints=True,
>     pl_trainer_kwargs={"callbacks":[checkpoint_callback]}
> )
> # load the weights only
> model.load_weights_from_checkpoint(base_model_name, best=True)
> # fine-tune/retrain
> model.fit(train, val_series=val, epochs=10)
> ```
> 
> Let me know if these workarounds work for you.

@madtoinou Thanks!, I can load the checkpoint and reuse it! close this issure
