### ISSUE TITLE
u8darts on Torch v1.7

### ISSUE THREAD

**Issue by kusumy** [unit8co/darts#239]
Is possible to use u8darts with torch v1.7 ?

I have latest torch installed, and when i tried to install 'u8darts[all]', then error message shows :

ERROR: Could not find a version that satisfies the requirement torch==1.5.1;

Regards

**Comment by pennfranc** [comment]
Thanks for reporting! Currently torch version 1.5.1 is required. So at this stage I suggest you create a separate virtual environment to use darts. Sorry for the trouble, maybe in the future we can make this easier, please stay tuned for new releases of Darts.
