### ISSUE TITLE
[BUG] TFTModel does not store best model

### ISSUE THREAD

**Issue by akepa** [unit8co/darts#2394]
**Describe the bug**
I instantiate TFTModel with _save_checkpoints_ set to True.
After fitting the model, I see that ./dart_logs/{my_model}/checkpoints folder is created which contains the checkpoints created after all training epochs. However, it does not create the file best-epoch=xxx expected by _load_from_checkpoint_ method to load the best checkpoint, and therefore this method raises an error:
```
FileNotFoundError: There is no file matching prefix best-* in /home/jovyan/work/booking_forecast/darts_logs/tft_week_es/checkpoints

```

**To Reproduce**
```

my_model = TFTModel(
    input_chunk_length=64,
    output_chunk_length=8,
    hidden_size=32,
    lstm_layers=1,
    num_attention_heads=4,
    dropout=0.1,
    batch_size=64,
    n_epochs=300,
    add_relative_index=False,
    add_encoders={"cyclic": {"future": ["month"]}},
    likelihood=QuantileRegression(quantiles= [0.1, 0.5,0.9]), 
    random_state=42,
    pl_trainer_kwargs={"accelerator": "gpu", "devices": [0]},
    save_checkpoints=True, 
    model_name='tft_week_es',
    force_reset=True
)

my_model.fit(train_transformed, future_covariates=None, verbose=True)

best_model = my_model.load_from_checkpoint(model_name='tft_week_es', best=True, work_dir='/home/jovyan/work/booking_forecast/darts_logs')
```
**Expected behavior**
A file called best-epoch=xxx.ckpt should be stored along with the checkpoints. However, only checkpoint files are generated.

**System (please complete the following information):**
 - Python 3.11.8
 - darts==0.29.0

**Additional context**
I've tried with a different model (more precisely, I've run the following example notebook https://github.com/unit8co/darts/blob/master/examples/18-TiDE-examples.ipynb), and in this case the best model file is created as expected.

**Comment by dennisbader** [comment]
Hi @akepa, for the model to save the best checkpoint, you need to provide a validation set with `val_series`, `val_past/future_covarates` to `model.fit()` (as it is done in the example notebook). You can read more in the `fit()` documentation [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.fit).
