### ISSUE TITLE
Is there a Way to Represent Static Covariates and Also Different Items? 

### ISSUE THREAD

**Issue by barmanroys** [unit8co/darts#2406]
A very simple problem where I am trying to forecast sales of different items based on historical sales data. The table looks like 

![Screenshot from 2024-06-08 20-57-36](https://github.com/unit8co/darts/assets/24065857/b991b404-4af7-4a07-823e-24d4efa01720)
where the _DATE_ and _SKU_ columns together constitute joint primary keys, and trying to predict the _QUANTITY_ is the target series. 

How to represent such a dataframe via the darts timeseries abstraction? Also, should the _SKU_ column be treated as a static covariate? Any documentation on how to deal with this problem will be appreciated.

**Comment by dennisbader** [comment]
Hi @barmanroys, you can use `TimeSeries.from_group_dataframe()` to extract a list of series where each element is a time series from a single SKU (see the static covariates example notebook [here](https://unit8co.github.io/darts/examples/15-static-covariates.html#4.-Extract-a-list-of-time-series-by-groups-from-a-DataFrame-using-from_group_dataframe())).

I'd also recommend to quickly read through the example notebook as it explains how static covariates are handled in Darts.

It depends a bit on your use case if you should use the SKU as static cov or not:
- the SKUs from any prediction/forecast in the future must have been observed during training already (e.g. a fixed number of SKUs) 
- you have to transform the SKU (text) to numeric:
  - currently, only LightGBM and TFTModel support categorical static covariates (represented as integers)
  - for the other models, you would have to (for example) one-hot encode the SKUs, which can be problematic for a large number of SKUs
