### ISSUE TITLE
ConvergenceWarning: Optimization failed to converge. Check mle_retvals.

### ISSUE THREAD

**Issue by robomotic** [unit8co/darts#241]
**Describe the bug**
Simple Exponential Smoothing does not converge for the air passenger data as shown in the demo.

**To Reproduce**
Please check my Colab notebook: https://colab.research.google.com/drive/1H8Dqyx6lfe818PeHy_qdVgmoN3Btoiam?usp=sharing

**Expected behavior**
Exponential smoothing should converge for this very simple dataset.

**System (please complete the following information):**
 - Python version: 3.8
 - darts version 0.5.0

**Additional context**
The autocorr() function doesn't seem to exist.

**Comment by pennfranc** [comment]
Thanks for getting in touch! `TimeSeries.autocorr` is indeed out-of-date and should be updated or removed, good catch!
However, as far as I can tell this is unrelated to the fact that you get a convergence warning. Despite the warning, you should still get a fairly good forecast as can be seen here: https://github.com/unit8co/darts/blob/master/examples/darts-intro.ipynb
(we simply suppress the warning in that notebook). 
For the `ExponentialSmoothing` model we simply wrap the `statsmodels.tsa.holtwinters.ExponentialSmoothing` model, which is responsible for the warning.

**Comment by robomotic** [comment]
Thanks for the pointers, yes this is right the convergence warning comes from the optimizer. I guess by setting the error target value to a higher value that will disappear. For now I will just ignore them as you show in your examples.
Feel free to close once the autocorr documentation is removed.
Cheers.

**Comment by iakompor** [comment]
Not sure if this is proper etiquette but I decided to reply to this hoping someone can help, because I'm still getting this error today while backtesting, and unfortunately entropicbloom's github link with the solution leads to a 404. Would really appreciate some help on how to suppress this warning if possible in my case, thank you!
