### ISSUE TITLE
How to set lags for Darts Time Encodings?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2422]
How does the Time Encodings in Darts work?

For example if I add this dictionary to my model initialisation, i.e.
```
add_encoders = {
    'cyclic': {'future': ['month']},
    'tz': 'CET',
}

lgbm_model = lgbm(...., add_encoders=add_encoders, lags_future_covariates=[-5,5])
```

Does it mean that the encoders will follow the lags defined in my lags_future_covariates?

**Comment by dennisbader** [comment]
Hi @ETTAN93, yes with "future" encoders, it will use the `lags_future_covariates` ("past" will use `lags_past_covariates`).

You can also specify component specific lags for the encoders by passing a dict to `lags_future_covariates`. The component names of the generated encodings can be found [here](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.encoders.encoders.html#darts.dataprocessing.encoders.encoders.CallableIndexEncoder.base_component_name)

**Comment by ETTAN93** [comment]
Hi @dennisbader, got it thanks. Is there a way to print out all the future covariates of a fitted model rather than having to construct the name via the link you gave? e.g. lgbm.future_covariates or something. I tried

```
forecast_horizon = 3
target_lags = None
past_cov_lags = list(range(-8, 0))
future_cov_lags = list(range(-22, 21))
encoders = {'cyclic': {'future': ['hour', 'minute', 'second']}}

lgbm_model =  LightGBMModel(
    lags=target_lags,
    lags_past_covariates=past_cov_lags, 
    lags_future_covariates=future_cov_lags
    output_chunk_length=forecast_horizon,
    n_jobs=-1,
    random_state=42,
    multi_models=True,
    add_encoders = encoders
)

lgbm_model.fit(
    series = target_train_all,
    past_covariates= past_cov_train_all,
    future_covariates= future_cov_train_all
)
```
Running `lgbm_model.future_covariate_series` did not return anything.

**Comment by dennisbader** [comment]
Hi @ETTAN93, there is now built-in feature to get the component names of all future covariates.
But after fitting the model, you can access the encoder's component names with:

```
enc_comp_past, enc_comp_future = lgbm_model.encoders.components
```

This will give you the component names for the past and future encodings.
