### ISSUE TITLE
How to access and use functionalities of the underlying / wrapped regression models?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2427]
Is it possible to use methods/functions of the models which Darts wraps around?

For example for LGBM, is it possible to create a Darts LGBM model object but still use this [plot_importance](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.plot_importance.html#lightgbm.plot_importance) function from the original LGBM?

**Comment by dennisbader** [comment]
Hi @ETTAN93. Yes you can.

Assuming `model` is your trained `LightGBMModel`. You can use method [`get_estimator()`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.lgbm.html#darts.models.forecasting.lgbm.LightGBMModel.get_estimator) the got the underlying LGBMRegressor for each horizon and target component.

```
import lightgbm as lgb

# gives you the LGBMRegressor
lgb_model = model.get_estimator(horizon=0, target_dim=0)

# get importance
imp = lgb_model.booster_.feature_importance()

# get Darts' lagged feature names
features_names = lgbm_model.lagged_feature_names

# plot importance will give you the sorted features, so you would get the feature names shown in the plot like this:
[lgbm_model.lagged_feature_names[idx] for idx in np.argsort(imp)[::-1]]

# plot importance
lgb.plot_importance(lgb_model)
```
