### ISSUE TITLE
Rewrite Ray Tune Hyperparameter optimization to use current Tuner method

### ISSUE THREAD

**Issue by ru-ko** [unit8co/darts#2430]
Ray Tune switched from ```tune.run()``` to ```tune.Tuner.fit()``` a few years ago as part of a reorganization of the library's structure, with the Tuner now being the standard across their documentation for hyperparameter optimization. 

The darts library [user guide page on this](https://unit8co.github.io/darts/userguide/hyperparameter_optimization.html) should be updated or added to, to reflect the changes in ray.

I've personally been having trouble getting ray and darts to work how I'd like, but if I get it to work, I'll clean up my code and suggest an edit to the page! If anyone has code that they've written that uses Tuner with darts and would like to share, I'd love to take a look at it.

**Comment by cnhwl** [comment]
Hi! @ru-ko @madtoinou 
I've rewritten the "Hyperparameter optimization with Ray Tune" guide based on the `Ray==2.31.0` and made a pull request. Hope you can try to run the code and give me some valuable suggestions!  #2459
