### ISSUE TITLE
Update pytorch lightning import to work with Ray and other libraries.

### ISSUE THREAD

**Issue by ru-ko** [unit8co/darts#2432]
**Is your feature request related to a current problem? Please describe.**
Importing and using  `lightning.pytorch` and `pytorch_lightning` in the same program causes conflicts. Ray has migrated their tuning to `ray.tune.Tuner` and is deprecating `ray.tune.run`. Ray uses a conditional import, importing `pytorch_lightning` only if the other is not available. However, it will import `lightning.pytorch` first, where the darts `pl_forecasting_module` imports pytorch_lightning. This may also apply to other places. 

**Describe proposed solution**
Darts should incorporate a conditional import that matches this priority in `pl_forecasting_module`, `r_finder`, etc as follows:

```python
#import pytorch_lightning as pl
def import_lightning():  # noqa: F402
    try:
        import lightning.pytorch as pl
    except ModuleNotFoundError:
        import pytorch_lightning as pl
    return pl

pl = import_lightning()
```

**Describe potential alternatives**
Change imports of pytorch_lightning to lightning.pytorch

**Additional context**
I noticed this issue when attempting to use `ray.tune.Tuner` and `ray.train.torch.TorchTrainer` in conjunction with `RNNModel`. I solved it by making the change in the proposed solution.

**Comment by madtoinou** [comment]
Hi @ru-ko,

We are aware of this problem, it's already tracked by #2198. 

I like the approach you're proposing, would you be willing to open a PR to implement it and see if it solves the problem?

**Comment by ru-ko** [comment]
Ope, didn't realize it was tracked by that. I'll start a branch for it and make changes when I can, although it'll be slow going.
