### ISSUE TITLE
[BUG] Models that fit method do not support the parameter sample_weights cannot be fitted

### ISSUE THREAD

**Issue by cnhwl** [unit8co/darts#2439]
**Describe the bug**
In Darts version 0.30.0, the parameter sample_weights was added. However, there are some regressors in scikit-learn where the fit method does not support the parameter sample_weights. I have used the following code to list the models in scikit-learn where the fit method does or does not support the parameter sample_weights:
```python
from sklearn.utils import all_estimators
import inspect

for name, clf in all_estimators(type_filter='regressor'):
    try:
        # Try to instantiate the model and check the fit method
        model = clf()
        if 'sample_weight' in inspect.signature(model.fit).parameters:
            print(name, 'support sample_weight')
        else:
            print(name, 'not support sample_weight')
    except TypeError as e:
        # If a TypeError occurs during instantiation, it means that the model requires additional parameters, skip this model
       continue
```
If using `RegressionModel `with scikit-learn `GaussianProcessRegressor`、`GaussianProcessRegressor `or other models whose fit method does not support the parameter sample_weights, and run .fit(), TypeError would occur:
```
TypeError: fit() got an unexpected keyword argument 'sample_weight'
```

**To Reproduce**
Use `RegressionModel `with scikit-learn `GaussianProcessRegressor`、`GaussianProcessRegressor `or other models whose fit method does not support the parameter sample_weights, and run .fit().

**Expected behavior**
The errors should be gone.

**System (please complete the following information):**
 - Python version: 3.9.17
 - darts version 0.30.0

**Additional context**
I've made initial changes in **regression_model.py** to address this issue and have been able to get models whose fit methods don't support the sample_weights parameter to run successfully. As a dedicated user of the amazing darts library, and a newcomer to the open source community, I would be incredibly proud and excited to be allowed to contribute to this issue. I am looking forward to hearing more from you, thank you very much!
```python
import inspect
...
        if sample_weights is not None:
            fit_parameters = inspect.signature(self.model.fit).parameters
            if 'sample_weight' in fit_parameters:
                self.model.fit(
                    training_samples, training_labels, sample_weight=sample_weights, **kwargs
                )
            else:
                self.model.fit(
                    training_samples, training_labels, **kwargs
                )
```

**Comment by dennisbader** [comment]
Hi @cnhwl, and thanks for raising this issue. It is indeed a bug. Of course, we would be very happy about your contribution 🚀 

It would also be nice to raise a warning in case the user supplied `sample_weight` but the model doesn't support sample weights.

**Comment by cnhwl** [comment]
> Hi @cnhwl, and thanks for raising this issue. It is indeed a bug. Of course, we would be very happy about your contribution 🚀
> 
> It would also be nice to raise a warning in case the user supplied `sample_weight` but the model doesn't support sample weights.

Thank you very much for your reply! 🙏@dennisbader It's my honour to contribute to open source libraries! As you said, I also found it useful to include a warning message, the code might be as follows:
```
logger.warning("Provided `sample_weights` wasn't used.")
```
I'll open a pull request as soon as possible, but as I'm a rookie in contribution, this may take a while. Hope to keep in touch with you!🤝
