### ISSUE TITLE
[Question] should old versions of pandas be taken into account in PR

### ISSUE THREAD

**Issue by quant12345** [unit8co/darts#2440]
When I make a pull request, new versions of Pandas are used for tests:
```
tests (macos-13, 3.9, all)
tests (ubuntu-latest, 3.9, all)
```
 But when the merge happens, I see that they have old versions:

`tests (ubuntu-latest, 3.8, core) `

 that show failures, like [here.](https://github.com/unit8co/darts/commit/54f39f7727011a4d72f525bc838ff8cd9e2405d1)

Or is this some kind of internal implementation during the merge that is not important?

**Comment by dennisbader** [comment]
Hi @quant12345, yes they should be taken into account. We have "light weight" tests for PRs, and then as soon as we merge we check the minimum/maximum python versions, as well as the different Darts flavors (with/without pytorch, etc.)

We will have to fix the currently failing pipeline with another PR

**Comment by quant12345** [comment]
@dennisbader can I run all minimum/maximum python versions myself?
