### ISSUE TITLE
Global Vs Local Models and Multivariate vs Multiple Series Forecasting

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2444]
I am trying to understand better how a global model would work under the two different forecasting methods - multivariate forecast vs multiple series forecasting. Based on what was mentioned in [#2141](https://github.com/unit8co/darts/issues/2141), the method I am currently using below would fall under a multiple series forecasting approach:
```
start_date = pd.Timestamp("2019-09-01 00:00:00", tz="utc").tz_convert(None)
split_date = pd.Timestamp("2023-01-31 23:59:00", tz="utc").tz_convert(None) 
end_date =  pd.Timestamp("2024-04-15 23:59:00", tz="utc").tz_convert(None)

target_all_parks = []
future_cov_all_parks = []
past_cov_all_parks = []

target_train_all_parks = []
future_cov_train_all_parks = []
past_cov_train_all_parks = []

for park_name, park_data_df in park_data_dict.items():
    target_series = TimeSeries.from_dataframe(park_data_df[[config.data.target_col]])[start_date:end_date]
    future_cov_series = TimeSeries.from_dataframe(park_data_df[config.data.future_cov])[start_date:end_date]
    past_cov_series = TimeSeries.from_dataframe(park_data_df[config.data.past_cov])[start_date:end_date]
    
    target_series_train = target_series[start_date:split_date]
    future_cov_train = future_cov_series[start_date:split_date]
    past_cov_train = past_cov_series[start_date:split_date]
    
    target_all_parks.append(target_series)
    target_train_all_parks.append(target_series_train)
    future_cov_all_parks.append(future_cov_series)
    past_cov_all_parks.append(past_cov_series)
    future_cov_train_all_parks.append(future_cov_train)
    past_cov_train_all_parks.append(past_cov_train)
```
By passing a list of (for example) 3 separate target series paired with 3 independent past and future covariates, the LGBM model would be learning the relationship between each individual target and their respective covariates. When predicting the 3 targets, the model would then predict each target independently by passing a target_series to the series_argument, e.g. `lgbm_model.predict(n=36, series=train_park_1, past_covariates = past_cov_park_1, future_covariates = future_cov_park_1)`. 

1. Under multiple series forecasting method, assuming that there are no static covariates defined, how does the model know which park it is predicting for? Does it just depend on the series, past and future_covariates that are passed to it?

2. In this particular use case, would using a multivariate approach even make sense? i.e. passing all 3 target series as 1 dataframe with three columns and passing all past and future covariates together as well.

**Comment by dennisbader** [comment]
Hi @ETTAN93. Yes, your understanding is correct.

1. without static covariates, the model does not know which park it is. It only knows about the input features / lagged feature values extracted from the series, past and future covariates that you pass to predict.
2. In my opinion, your use case is indeed a multiple series use case (not multivariate). Multivariate is usually for target columns share a relationship with each other, and there is a guarantee that number of columns will not change. In your case, the parks are not necessarily related with each other and should be regarded as independent.
