### ISSUE TITLE
How to add a layer to the darts model? 

### ISSUE THREAD

**Issue by jainmilan** [unit8co/darts#2468]
I need to ensure that my model output is restricted between 0 and 1. For this, I want to add a Sigmoid activation in the last layer. I am new to darts and tried finding ways to do this. After much searching, I found I could use `<model>.model.add_module()` to append a layer on top of the existing model. However, the `model.model` is None until I don't call the predict function. How can I customize my darts model?

**Comment by eschibli** [comment]
Based on my experience your best bet is probably to subclass the `Model`, overwriting it's `_create_model` method, and it's corresponding `Module`, overwriting the `forward` method. Something like

```
class _BoundedDLinearModule(_DLinearModule)
   def forward(self, *args):
      x = super().forward(*args)
      return nn.functional.sigmoid(x)
      
class BoundedDLinearModel(DLinearModel):
# You need to copy the function signature, not just *args/*kwargs, as some code checks the exact sig for compatibility
    def __init__(
        self,
        input_chunk_length: int,
        output_chunk_length: int,
        output_chunk_shift: int = 0,
        shared_weights: bool = False,
        kernel_size: int = 25,
        const_init: bool = True,
        use_static_covariates: bool = True,
        **kwargs,
       ):
      super().init(input_chunk_length=input_chunk_length, ..., *args, **kwargs)


   def _create_model(...)
      # ...
      # the rest of the create function
      # ...

   
   return _BoundedDLinearModule(
            input_dim=input_dim,
            ...,
            **self.pl_module_params,
        )
```

**Comment by jainmilan** [comment]
I ended up doing the same way, but thanks for confirming. I was hoping that there might be a functionality to add/append modules to the existing functions.
