### ISSUE TITLE
[BUG] when i use 'load_from_checkpoint',it mentiond following faults

### ISSUE THREAD

**Issue by HAUNGTOFU** [unit8co/darts#2469]
I run 'model_nbeats = model4.load_from_checkpoint(model_name='lstm_test1',work_dir=r"C:\Users\86187\PycharmProjects\pythonProject1\true\darts_logs",best=True)' in Pycharm,but it shows'FileNotFoundError: There is no file matching prefix best-* in
C:\Users\86187\PycharmProjects\pythonProject1\true\darts_logs\lstm_test1\checkpoints'

**Comment by dennisbader** [comment]
Hi @HAUNGTOFU. My first guesses:
- did you activate `save_checkpoints=True` when creating the model?
- did you pass a validation set with `val_*` for series, past/future covariates to `model.fit()`?

If you did both of these and the error still remains, please add a minimal reproducible example.

**Comment by HAUNGTOFU** [comment]
Can the likelihood of all models be evaluated using 'quantile regression'? Could you explain the principle in detail?

**Comment by dennisbader** [comment]
`QuantileRegression` in Darts is a `Likelihood` object, and it can compute the loss on the validation set, just like any other likelihood (gaussian, laplace, ...). It uses the pinball loss. You can read more about Quantile Regression for example [here](https://en.wikipedia.org/wiki/Quantile_regression).
