### ISSUE TITLE
Examples for external regressors use

### ISSUE THREAD

**Issue by d1bevz** [unit8co/darts#247]
I read the description and it says there is an opportunity to use external regressors, but I cannot see any method like add_regressor() in the documentation. Am I missing something? Or can you please add example how to use external regressors and split model by each component (e.g. trend, seasonality, regressor a, regressor b etc.)

For example Facebook Prophet has native support for such method, cannot see anything except for fit predict methods.

**Comment by hrzn** [comment]
With some models of Darts, you can already differentiate which (potentially multivariate) time series should be used as features or as target (using train and target arguments of fit()). However, we are currently in the process of revamping and improving this part of Darts (see: https://github.com/unit8co/darts/pull/231), so I would recommend that you wait a little longer for the next release.
