### ISSUE TITLE
[Question] How to perform covariates-only based forecating?

### ISSUE THREAD

**Issue by benjamin-strath** [unit8co/darts#2471]
Hi there, I was wondering if anyone could help with a problem I am facing, any advice would be greatly appreciated!

**Background**
I am currently using a TFT model that is being trained on 10 different times series and I want to make a prediction on an 11th. The 11th series occurs over roughly the same time period as the 10 training series and so has roughly the same time indexes. I also know the covariates for the 11th timeseries. In other words I want to interpolate not extrapolate.

**Attempted Solution**
I have tried using the historical forecast method, with retrain set to false, and although this comes close to what I want, I have to specify the true values of the 11th time series before the model makes a prediction. I want to be able to make predictions without specify true values.

**Question**
Does darts have a feature that allows the user to make predictions on new timeseries (with the same time index as the training data) or is there an alternate way of using the "predict" method to achieve this?

Thanks

**Comment by dennisbader** [comment]
Hi, @benjamin-strath. Yes, you can do that with any pre-trained `GlobalForecastingModel` (you can find a list [here](https://unit8co.github.io/darts/#forecasting-models)).

If you don't want to use historical forecasts (this is just a simulation how your model would have performed over time in forecasting the 11th timeseries / with advancing forecasting points/times), then you can simply call `model.predict(n=horizon, series=series11)` (see the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.predict)). 
- if `horizon <= output_chunk_length`, it can generate the entire forecast in one go.
- if `horizon > output_chunk_length`, then the model will use auto-regression to produce the forecast (e.g. it consumes its own prediction, and future values of the covariates as model input for future predictions)

**Comment by benjamin-strath** [comment]
Hi @dennisbader, thank you very much for your answer. I have tried your solution and it is not quite what I was looking for. I think I did not explain myself very well however. I hope you don't mind if I re-phrase the question...

Say for instance I own 11 book shops all in different locations. 

For 10 of them I know the how many books were sold per day from day 1 to day 30 (e.g. 1st July to 31st July). I also know some factors that may affect the sale of books, for example the average daily temperature and the average daily rainfall, for the same period (days 1 to 30). So to clarify the target variable is the number of books sold per day, the timeframe is from 1-30, and the covariates are the average daily temperature and the average daily rainfall.

At the 11th location the number of books sold per day was not recorded for the days 1 to 30. However, I know what the average daily temperature, and average daily rainfall was at the location for the days 1 to 30.

Suppose I want to predict the book sales for the 11th location, which of the following two approaches would be the correct approach to fit the model?

The first approach would be to concatenate the book sales data for all 10 locations into a single long book sales time series and fit the model on this concatenated book sales time series (together with the concatenated covariate timeseries).

The second approach would be to create a list of 10 book sales time series corresponding to each location, and fit the model on this list of 10 time series (together with a list of the 10 covariate timeseries).

**Comment by dennisbader** [comment]
Do you have no information of the book sales of shop 11 (e.g. at least `input_chunk_length` points would have to be required as input for the `TFTModel` to make a prediction)?

If you want to train the model only on the values of the covariates (temperature and rainfall), then this is only supported by any of our `RegressionModel`. There you can perform covariates-only-based forecasting by setting the target lags `lags=None` and then providing at least one of `past_covariates_lags` or `future_covariates_lags`.

> The first approach would be to concatenate the book sales data for all 10 locations into a single long book sales time series and fit the model on this concatenated book sales time series (together with the concatenated covariate timeseries).

To me it sounds like you want to perform global training (your second approach). Depending on wether you have `input_chunk_length` points for shop 11 you can either use any global forecasting model (if YES) or only the Regression Models (if NO).

**Comment by benjamin-strath** [comment]
That's perfect! Thank you very much for your advice
