### ISSUE TITLE
[BUG] Cannot convert a MPS Tensor to float64 dtype as the MPS framework - GlobalNaiveAggregate

### ISSUE THREAD

**Issue by AvisP** [unit8co/darts#2477]
**Describe the bug**
When using the predict function of GlobalNaiveAggregate on mac M1 getting the error `TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.` The `fit` function is working fine following the suggestion stated [here](https://github.com/unit8co/darts/issues/2326) but `predict` is not.

**To Reproduce**
```
from darts.datasets import IceCreamHeaterDataset
from darts.models import GlobalNaiveAggregate
import numpy as np

series_1 = IceCreamHeaterDataset().load().astype(np.float32)
horizon, icl = 3, 60
model = GlobalNaiveAggregate(input_chunk_length=icl, output_chunk_length=horizon)

model.fit(series_1.astype(np.float32))

pred = model.predict(n=horizon, series=series_1.astype(np.float32))
```

**Expected behavior**
Should execute without error

**System (please complete the following information):**
 - Python version: [3.10.11]
 - darts version [0.30.0]

**Comment by dennisbader** [comment]
Hi @AvisP, I tried on my M1 and it works fine. What pytorch and pytorch lightning versions are you using?

My output (GPU/mps available and used shows it's on M1):

```
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 71.39it/s]
```

**Comment by AvisP** [comment]
It works now after restarting kernel. My pytorch version is `2.3.1` and pytorch-lightning is `2.3.3`. Thanks for validating on your end.

**Comment by dennisbader** [comment]
Great, closing in that case

**Comment by MATnani** [comment]
I'm getting the same error with the exact same pytorch and pytorch-lightning versions. I'm on Mac M3.
