### ISSUE TITLE
[BUG] DOC `series_reduction` explained twice in docstring

### ISSUE THREAD

**Issue by turbotimon** [unit8co/darts#2480]
**Describe the bug**
`series_reduction` is explained twice in docstring for all metrics. E.g.:

https://github.com/unit8co/darts/blob/479656cb0293a640dc1b99edd14cd34768e37f24/darts/metrics/metrics.py#L750-L759

**System (please complete the following information):**
 - darts version: master / 0.30

**Additional context**

I can make a PR but need to know which is the valid version.

**Comment by dennisbader** [comment]
Thanks @turbotimon for noting this. Hmm.. good question, maybe let's combine the two? E.g.

```
    series_reduction
        Optionally, a function to aggregate the metrics over multiple series. It must reduce a `np.ndarray`
        of shape `(s, t, c)` to a `np.ndarray` of shape `(t, c)` The function takes as input a ``np.ndarray`` and a
        parameter named `axis`, and returns the reduced array. The `axis` receives value `0` corresponding to the
        series axis. If `None`, will return a metric per series. With `np.nanmean`, will return the average over all 
        series metrics.
```

Of course, we'd be happy about the contribution. Thanks a lot! :) 

Could you maybe update the existing `series_reduction` as well for the metrics that only have it defined once? For example `err()` is such a case.

**Comment by turbotimon** [comment]
@dennisbader thanks, I updated all metrics in PR #2486
