### ISSUE TITLE
How to obtain quantiles from a probabilistic `TimeSeries`?

### ISSUE THREAD

**Issue by HAUNGTOFU** [unit8co/darts#2481]
I want to know how the quantile estimates are obtained based on these 100 num_samples, is it simply through the quantile calculation formula after sorting? 
In 

```
from darts import concatenate
from darts.metrics import mse, mae
pred_series2 = model4.historical_forecasts(
    series1,
    start=series1[400].start_time(),
    forecast_horizon=2,
    stride=2,
    num_samples=100,
    last_points_only=False,
    retrain=False,
    verbose=True,
)
pred_series2 = concatenate(pred_series2)
new=pred_series2.pd_dataframe()
new
```

**Comment by dennisbader** [comment]
Hu @HAUNGTOFU, for probabilistic series (with `num_samples>1`) you can use any of Darts `TimeSeries.quantile*()` methods (the methods can be found [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html#darts.timeseries.TimeSeries.quantile)).

If you use a model that supports a likelihood (some of our regression mdoels, and all torch /neural network-based forecasting models), and you chose Quantile Regression as the likelihood, then you can use `predict_likelihood_parameters=True` (in predict(), historical_forecasts(), ...) to directly get the predicted quantile values.
In that case the returned TimeSeries will not be probabilistic anymore (num_samples=1), but have the predicted quantiles as additional columns / components.
