### ISSUE TITLE
[BUG] sklearn KNeighborsRegressor can't be fitted with darts RegressionModel

### ISSUE THREAD

**Issue by erewl** [unit8co/darts#2495]
**Describe the bug**

With darts version 0.30.0 the `KNeighborsRegressor` model cannot be fitted using darts' `RegressionModel` wrapper and throws the error:

```
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: KNeighborsRegressor.fit() got an unexpected keyword argument 'sample_weight'
```
When I downgraded to darts 0.29.0 , `KNeighborsRegressor` has no issues with fitting and works as expected.

**To Reproduce**
```
import pandas as pd
from darts.datasets import ElectricityConsumptionZurichDataset
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsRegressor
import darts
import sklearn
from darts.models import RegressionModel

def get_data():
    ts_energy = ElectricityConsumptionZurichDataset().load()

    # extract values recorded between 2017 and 2019
    start_date = pd.Timestamp("2017-01-01")
    end_date = pd.Timestamp("2019-01-31")
    ts_energy = ts_energy[start_date:end_date]

    # resample to hourly frequency
    ts_energy = ts_energy.resample(freq="H")
    # extract households energy consumption
    ts_energy = ts_energy["Value_NE5"]

    # create train and validation splits
    validation_cutoff = pd.Timestamp("2018-10-31")
    return ts_energy.split_after(validation_cutoff)


def fit_regression(train, lags):
    print("Initializing model")
    reg_model = RegressionModel(lags=lags, output_chunk_length=1, model=Ridge(alpha=100.0), use_static_covariates=False)
    print("Fitting Ridge model")
    reg_model.fit(train)

def fit_neighbors(train, lags):
    print("Initializing model")
    knn_model = RegressionModel(lags=lags, output_chunk_length=1, model=KNeighborsRegressor())
    print("Fitting KNN model")
    knn_model.fit(train)


if __name__ == "__main__":
    print(f"Darts version: {darts.__version__}")
    print(f"Sklearn version: {sklearn.__version__}")

    print("Retrieving data")
    ts_energy_train, ts_energy_val = get_data()
    print("Starting")
    fit_regression(ts_energy_train, lags=24)
    fit_neighbors(ts_energy_train, lags=24)
```

**Expected behavior**

I would expect that both regression models (Ridge and KNeighborsRegressor ) can be used and fitted with the RegressionModel class. That it works with `darts==0.29.0` somewhat confirms my expectation.  

Since both models are inheriting from sklearn's `RegressorMixin` and are tailored towards a regression problem, I had the expectation that I can utilize them that way with `darts`. (If that's not the case, then the error was sitting in front of the computer, and this is easily resolved :-)) ) 

**System (please complete the following information):**
 - Python version: 3.11
 - darts version 0.30.0
 - sklean version: 1.4.1.post1

**Comment by cnhwl** [comment]
Hi! @erewl 

This bug might be similar to the one mentioned in #2439, I've made a pull request in #2445 and hope that helps!

**Comment by erewl** [comment]
> Hi! @erewl
> 
> This bug might be similar to the one mentioned in #2439, I've made a pull request in #2445 and hope that helps!

Amazing! And also thanks for mentioning it, I thought I looked properly through the issues, but apparently I didn't haha. 
Well spotted and great that you got a fix merged too, I appreciate that :-) 

I will close this issue then
