### ISSUE TITLE
[QUESTION] Behavior of TFT's .predict() method

### ISSUE THREAD

**Issue by valentin-fngr** [unit8co/darts#2502]
Hi, 

TFT is given a `output_chunk_length` which is the forecast horizon. Therefore, when training, I am teaching my model to forecast `output_chunk_length` data points in the future. 

 When calling `.predict(n=n, num_samples=100, future_covariates=future_covariates)`, what happens if `n` > `output_chunk_length` ? 
 
Thanks.

**Comment by madtoinou** [comment]
Hi @valentin-fngr,

If `n > output_chunk_length`, the model will consume its own prediction to generate the next forecasts in an auto-regressive manner.

I would recommend going through the [Quickstart Notebook](https://unit8co.github.io/darts/quickstart/00-quickstart.html?highlight=auto+regressive#Using-deep-learning:-example-with-N-BEATS) which will introduce you all the basics of Darts.

**Comment by valentin-fngr** [comment]
Hi @madtoinou, 

Thanks for your reply. Makes sense to me. 
Thanks for the guide as well.
