### ISSUE TITLE
[BUG]When the time_col parameter in TimeSeries.from_group_dataframe  contains integers, it is still converted to a DatetimeIndex

### ISSUE THREAD

**Issue by bravebird** [unit8co/darts#2503]
The description of the time_col parameter in TimeSeries.from_group_dataframe() mentions: "The time column name. If set, the column will be cast to a pandas DatetimeIndex (if it contains timestamps) or a RangeIndex (if it contains integers)." However, the source code does not account for the latter case (contains integers). When the time_col column contains integers, it is still converted to a DatetimeIndex. Regardless of the format of the time_col column, it is converted to a DatetimeIndex.

**System**
 - darts version [0.30.0]

**Comment by madtoinou** [comment]
Hi @bravebird,

This is already tracked by #2491, I am closing this one to avoid duplicates and will try to find to some to investigate this issue.
