### ISSUE TITLE
[QUESTION] Simple question regarding backtest() in Darts.

### ISSUE THREAD

**Issue by valentin-fngr** [unit8co/darts#2505]
Hi, 

I have a quick question regarding backtesting. 

Given a target serie of size **500**, I train on the **400** first points, and validate on the last **100**. I use a horizon of **5** and input_chunk of **10**. 

1) When backtesting on the entire dataset, when `retrain=False`, is the code loading the previous 10 data points from the given serie to compose my input_chunk or does it use the the previously 10 forecasted data points ? 

2) Same question when I add validation data to my model.fit(). Is the validation data used to compose my `input_chunk` during validation stage ? 
```
my_model.fit(
    series=train_target, 
    future_covariates=train_future_cov, 
    val_series=val_target, 
    val_future_covariates=val_future_cov,
    verbose=False, 
)
```

I know these might sound like stupid questions, but I just want to sure. 

Thanks a lot

**Comment by madtoinou** [comment]
Hi @valentin-fngr,

1. When using `backtest()/historical_forecasts()`, the code will iteratively load the ground truth series to perform the forecasts. The "previously predicted points" are only used when `forecast_horizon > output_chunk_length`.
2. When a validation series is used, only samples within the series is used (training series is not used at all).

Hope that it clarifies things.

**Comment by valentin-fngr** [comment]
got it, thanks.
