### ISSUE TITLE
[BUG] nbeats.py works better if you add .cuda() to each torch.zero

### ISSUE THREAD

**Issue by catskillsresearch** [unit8co/darts#251]
**Describe the bug**
It complains tensors are on GPU and CPU.  nbeats.py works better if you add .cuda() to each torch.zero

**To Reproduce**
Run NBEATS-examples notebook.

**Expected behavior**
Shouldn't do that.

**System (please complete the following information):**
 - Python version: 3.8
 - darts version: 0.5.0
 - PyTorch: 1.7.1 (I deleted all the dependencies and installed from scratch because otherwise nearly impossible to install on current Anaconda)

**Comment by hrzn** [comment]
Thanks for raising. We were aware of issues with N-Beats when using GPU. It should be solved in an upcoming release (being addressed here: https://github.com/unit8co/darts/pull/231)

**Comment by hrzn** [comment]
This one should be solved since 0.6.1, closing.
