### ISSUE TITLE
Ability to add regressors to a Prophet model in Python

### ISSUE THREAD

**Issue by BenJCross1995** [unit8co/darts#2514]
In the Facebook Prophet library there is the ability to add regressors prior to fitting the model, the ability to do that is missing in darts. We can only add seasonality, as far as i'm aware.

It would be great to have this capability included in the package with the add_regressors function. Thanks.

**Comment by dennisbader** [comment]
Hi @BenJCross1995, this is supported through the `future_covariates` in `fit()` and `predict()`.
