### ISSUE TITLE
[BUG]  Really hard to install with pip install darts[all]

### ISSUE THREAD

**Issue by catskillsresearch** [unit8co/darts#252]
**Describe the bug**
Package really hard to install on Ubuntu 20.04 with Anaconda 3 and Python 3.8 using "pip install darts[all]"

**To Reproduce**
Just lots of breakage inside the pip install.

**Expected behavior**
No breakage.

**System (please complete the following information):**
 - Python version: 3.8
 - darts version: 0.5.0

**Additional context**
I deleted all the dependencies in setup.py and then did this:
```
conda create -n darts python=3.8
conda activate darts
git clone https://github.com/unit8co/darts.git
cd darts
/bin/rm -rf requirements/     # Remove all the requirements
emacs setup.py&               # Remove all the requirements
python setup.py install
conda install pandas
conda install matplotlib
conda install pytorch torchvision torchaudio cudatoolkit=10.1 -c pytorch
conda install -c conda-forge fbprophet
conda install -c anaconda pytz
conda install plotly
conda install jupyter
conda install -c conda-forge statsmodels
conda install -c anaconda scikit-learn
conda install -c conda-forge pmdarima
conda install -c conda-forge tensorboard
python -m ipykernel install --user --name=darts
```

**Comment by hrzn** [comment]
Hi @catskillsresearch, do you still have logs of what goes wrong?
The command to install it should be `pip install 'u8darts[all]'` (mind the `'`)

**Comment by catskillsresearch** [comment]
I did some steps to reproduce and it's working OK:

On Ubuntu 20.04LTS with a prexisting Anaconda Python with some packages in it already, I did:

```
conda create --name test_darts
conda activate test_darts
pip install u8darts[all]
```
The install went OK but it pulled out some stuff it didn't like:
```
ERROR: tf-nightly 2.2.0.dev20200114 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.0 which is incompatible.
ERROR: nnunet 1.6.5 has requirement torch>=1.6.0a, but you'll have torch 1.5.1 which is incompatible.
ERROR: batchgenerators 0.21 has requirement pillow>=7.1.2, but you'll have pillow 7.0.0 which is incompatible.
ERROR: tdameritrade 0.1.1 has requirement requests>=2.23.0, but you'll have requests 2.22.0 which is incompatible.
Installing collected packages: tqdm, numpy, scipy, scikit-learn, pandas, matplotlib, holidays, ipython, statsmodels, tensorboard, Cython, pmdarima, cmdstanpy, fbprophet, torch, u8darts
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1
  Found existing installation: numpy 1.17.4
    Uninstalling numpy-1.17.4:
      Successfully uninstalled numpy-1.17.4
  Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Found existing installation: scikit-learn 0.22.1
    Uninstalling scikit-learn-0.22.1:
      Successfully uninstalled scikit-learn-0.22.1
  Found existing installation: pandas 1.2.0
    Uninstalling pandas-1.2.0:
      Successfully uninstalled pandas-1.2.0
  Found existing installation: matplotlib 3.1.1
    Uninstalling matplotlib-3.1.1:
      Successfully uninstalled matplotlib-3.1.1
  Found existing installation: holidays 0.10.4
    Uninstalling holidays-0.10.4:
      Successfully uninstalled holidays-0.10.4
  Found existing installation: ipython 7.11.1
    Uninstalling ipython-7.11.1:
      Successfully uninstalled ipython-7.11.1
  Found existing installation: statsmodels 0.10.1
    Uninstalling statsmodels-0.10.1:
      Successfully uninstalled statsmodels-0.10.1
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Found existing installation: Cython 0.29.21
    Uninstalling Cython-0.29.21:
      Successfully uninstalled Cython-0.29.21
  Found existing installation: cmdstanpy 0.9.5
    Uninstalling cmdstanpy-0.9.5:
      Successfully uninstalled cmdstanpy-0.9.5
  Found existing installation: torch 1.6.0
    Uninstalling torch-1.6.0:
      Successfully uninstalled torch-1.6.0
Successfully installed Cython-0.29.17 cmdstanpy-0.4.0 fbprophet-0.6 holidays-0.10.2 ipython-7.15.0 matplotlib-3.2.2 numpy-1.19.0 pandas-1.1.0 pmdarima-1.6.1 scikit-learn-0.23.2 scipy-1.5.0 statsmodels-0.11.1 tensorboard-2.2.2 torch-1.5.1 tqdm-4.46.1 u8darts-0.5.0
```
So I guess don't worry about it.

**Comment by LeoFH** [comment]
Is installation under windows possible?
(Darts) C:\Users\LeoFH>conda install darts
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

IF  
(Darts) C:\Users\LeoFH>pip install darts

Then:
 Building wheel for prophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\LeoFH\anaconda3\envs\Darts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LeoFH\\AppData\\Local\\Temp\\pip-install-kvqj0aw7\\prophet_a2b7feb3d8ee4263b6505edf592b2a08\\setup.py'"'"'; __file__='"'"'C:\\Users\\LeoFH\\AppData\\Local\\Temp\\pip-install-kvqj0aw7\\prophet_a2b7feb3d8ee4263b6505edf592b2a08\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LeoFH\AppData\Local\Temp\pip-wheel-gsr8ug7h'
       cwd: C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\prophet
  creating build\lib\prophet\stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\setup.py", line 150, in <module>
      long_description_content_type='text/markdown',
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\LeoFH\anaconda3\envs\Darts\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\setup.py", line 36, in build_models
      from prophet.models import StanBackendEnum
    File "C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\prophet\__init__.py", line 8, in <module>
      from prophet.forecaster import Prophet
    File "C:\Users\LeoFH\AppData\Local\Temp\pip-install-kvqj0aw7\prophet_a2b7feb3d8ee4263b6505edf592b2a08\prophet\forecaster.py", line 14, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for prophet

**Comment by LeoFH** [comment]
Found the way:

(Darts) C:\Users\LeoFH>conda install prophet 



Downloading and Extracting Packages
ephem-4.0.0.2        | 706 KB    | ############################################################################ | 100%
cftime-1.5.0         | 150 KB    | ############################################################################ | 100%
pillow-8.3.1         | 784 KB    | ############################################################################ | 100%
netcdf4-1.5.7        | 354 KB    | ############################################################################ | 100%
kiwisolver-1.3.1     | 58 KB     | ############################################################################ | 100%
tornado-6.1          | 648 KB    | ############################################################################ | 100%
matplotlib-base-3.4. | 7.2 MB    | ############################################################################ | 100%
cython-0.29.24       | 1.9 MB    | ############################################################################ | 100%
numpy-1.21.2         | 5.6 MB    | ############################################################################ | 100%
certifi-2021.5.30    | 142 KB    | ############################################################################ | 100%
scipy-1.7.1          | 24.4 MB   | ############################################################################ | 100%
pystan-2.19.1.1      | 35.8 MB   | ############################################################################ | 100%
pandas-1.3.2         | 10.8 MB   | ############################################################################ | 100%
libpython-2.0        | 47 KB     | ############################################################################ | 100%
prophet-1.0.1        | 570 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

and then:

(Darts) C:\Users\LeoFH>pip install darts

Python should be 3.7.  Under 3.8 - bug with this some .dll file in scipy
