### ISSUE TITLE
[BUG] Time index name is lost after using prepend_values

### ISSUE THREAD

**Issue by dwolffram** [unit8co/darts#2523]
**Describe the bug**
The name of the time_index changes to 'time' after using `prepend_values`.

**To Reproduce**
```python
import numpy as np
import pandas as pd
from darts import TimeSeries
from darts.utils.timeseries_generation import generate_index

start = pd.Timestamp("2000-01-01")
end = pd.Timestamp("2000-12-31")
freq = pd.Timedelta(weeks=1)

index = generate_index(start=start, end=end, freq=freq, name='date')
values = np.random.normal(0, 1, size=len(index))

ts = TimeSeries.from_times_and_values(index, values, freq=freq, columns=pd.Index(['value']))
ts2 = ts.prepend_values(np.repeat(0, 30))

ts.time_index.name, ts2.time_index.name # ('date', 'time')
```

**Expected behavior**
The name of the time_index should stay the same when values are prepended.

**Comment by dwolffram** [comment]
This is my workaround for now:

`ts3 = TimeSeries.from_xarray(ts2.data_array().rename({'time': ts.time_index.name}))`

Not sure if there's a more direct way to rename the time_index but maybe it helps.

**Comment by dennisbader** [comment]
Hi @dwolffram and thanks for spotting this bug. We'll fix it soon.

**Comment by AlessiopSymplectic** [comment]
@dennisbader sure, I can pick this up.
