### ISSUE TITLE
[BUG] Quantiles/samples are wrong when using enable_optimization=True (default!)

### ISSUE THREAD

**Issue by dwolffram** [unit8co/darts#2524]
**Describe the bug**
Hi there,
already for a while, I've been puzzled by the output of my XGBoost/LightGBM models because the forecasts were surprisingly "flat" and not really showing any trends. (Also see my previous issue https://github.com/unit8co/darts/issues/2382) 

![image](https://github.com/user-attachments/assets/4652e78c-7b42-4981-a62d-c6615f7b5cdd)

However, the forecasts looked much better when I trained the model to produce point predictions only by minimizing the absolute error. This is surprising because it should be equivalent to the 50%-quantile of the probabilistic forecasts.

![image](https://github.com/user-attachments/assets/33647ea6-fafd-4d6f-9247-ae4f5b6e6ec6)

But now I just realized that if I set `enable_optimization=False` in `historical_forecasts`, the forecasts look much better and more like what I would expect (the median predictions look the same as the point predictions from before.)

![image](https://github.com/user-attachments/assets/e89c0d8e-0a8b-4b30-afa9-888996de15be)

So I think there might be something wrong with the optimization or sampling (which might be somewhat related to another previous issue https://github.com/unit8co/darts/issues/2461#issuecomment-2232651569).

**To Reproduce**
```python
import matplotlib.pyplot as plt

from darts import concatenate
from darts.datasets import AirPassengersDataset
from darts.models import XGBModel

series = AirPassengersDataset().load()
target_end = 60
validation_start = 60
QUANTILES = [0.025, 0.25, 0.5, 0.75, 0.975]


# Probabilistic forecast
xgb = XGBModel(
    lags=12,
    output_chunk_length=6,
    use_static_covariates=True,
    likelihood="quantile",
    quantiles=QUANTILES
)

xgb.fit(series)

hfc = xgb.historical_forecasts(
    series=series,
    start=validation_start,
    forecast_horizon=6,
    stride=6,
    last_points_only=False,
    retrain=False,
    verbose=True,
    num_samples=200
)
hfc = concatenate(hfc, axis=0)


# Probabilistic forecast with enable_optimization=False
hfc2 = xgb.historical_forecasts(
    series=series,
    start=validation_start,
    forecast_horizon=6,
    stride=6,
    last_points_only=False,
    retrain=False,
    verbose=True,
    num_samples=200,
    enable_optimization=False
)
hfc2 = concatenate(hfc2, axis=0)


# Point forecast
xgb = XGBModel(
    lags=12,
    output_chunk_length=6,
    use_static_covariates=True,
    objective='reg:absoluteerror'
)

xgb.fit(series)

hfc_ae = xgb.historical_forecasts(
    series=series,
    start=validation_start,
    forecast_horizon=6,
    stride=6,
    last_points_only=False,
    retrain=False,
    verbose=True
)
hfc_ae = concatenate(hfc_ae, axis=0)


# Plots
series.plot()
hfc.plot()

series.plot(new_plot=True)
hfc2.plot()

series.plot(new_plot=True)
hfc_ae.plot()

```

**Additional context**
I'm not sure if this only affects the Regression Models or also the Pytorch-based Models (but there I haven't noticed any obvious issues so far).

**Comment by dwolffram** [comment]
I just noticed that in the example that I've copied, the model is trained on the whole series. But if you only train on a part of it, you can still clearly see the difference.

Here are also two plots (with and without optimization enabled) from my application to illustrate the issue:

![image](https://github.com/user-attachments/assets/bfb4b592-7dfc-412f-b4b8-13e9e1857eb2)

I also checked a TSMixer and a TFT model and there was no difference between enable_optimization=True/False, so I think the issue is only with Regression Models.

**Comment by madtoinou** [comment]
Hi @dwolffram,

Thank you for the detailed issues, I managed to reproduce the problem locally. It's probably related to the shape of the array used for the vectorized inference is incorrect (might have something to do with the order of the lags/features?), we will investigate.

As a side note, it's expected that the issue does not occur for the Torch-based forecasting model as they have their own optimized method which is much simpler than the regression-based models.

**Comment by dwolffram** [comment]
Thanks a lot for looking into this @dennisbader!
