### ISSUE TITLE
[BUG] ValueError: Time series must be indexed with a DatetimeIndex.

### ISSUE THREAD

**Issue by TremaMiguel** [unit8co/darts#253]
**Describe the bug**
Static Method `TimeSeries.from_series()` requires to pass an `DatetimeIndex` additional to a `pandas.Series` object. Otherwise it will throw the following error

```
raise_if_not(isinstance(df.index, pd.DatetimeIndex), 'Time series must be indexed with a DatetimeIndex.',
                     logger)
```
because a `DatetimeIndex` was not passed when creating the `TimeSeries` object (See [L520](https://github.com/unit8co/darts/blob/master/darts/timeseries.py#L520))

**To Reproduce**
Any pandas series without an index.

```python
import pandas as pd
from darts import TimeSeries

TimeSeries.from_series(pd.Series([1,2,3,4,5]))
>>> 
ValueError: Time series must be indexed with a DatetimeIndex.
```

**Expected behavior**
It will work if passing a DatetimeIndex when creating the `DataFrame` from `pd_series` and converting the series to a list, otherwise the value column will be `NaN` values

```python
TimeSeries(pd.DataFrame(data=pd.Series([1,2,3,4,5]).to_list(), index=pd.DatetimeIndex(range(5))))
```

**System (please complete the following information):**
 - Python version: [e.g. 3.6]
 - darts version [e.g. 0.5.0]

**Additional context**

**Comment by hrzn** [comment]
Thanks for the suggestion @TremaMiguel. We have on our to-do list to provide some default dummy time index when no other time index is provided. It should (hopefully) come in a future release.

**Comment by TremaMiguel** [comment]
@hrzn I think this is a quick fix cause the function `from_series` is only expecting a `pd.Series`, just need to make sure the `pd_series` argument is indeed a pandas Series and then call some helper function that creates the dummy index. Are you open to get a PR on this ?

**Comment by hrzn** [comment]
@TremaMiguel yes, definitely :)

**Comment by hrzn** [comment]
This will be fixed in the next release (see: https://github.com/unit8co/darts/blob/develop/darts/timeseries.py#L45)
