### ISSUE TITLE
[BUG] Section "Running the examples only, without installing" in readme depends on Prophet which is not delivered along the docker image

### ISSUE THREAD

**Issue by ajallooeian** [unit8co/darts#254]
**Describe the bug**
We have the section "Running the examples only, without installing" in the README.md. Following the instructing and installing with gradlew, the given Jupyter notebook `examples/darts-intro.ipynb` has a second cell:
```
from darts.models import (
    NaiveSeasonal,
    NaiveDrift,
    Prophet,
    ExponentialSmoothing,
    ARIMA,
    AutoARIMA,
    StandardRegressionModel,
    Theta,
    FFT
)
```
But prophet is not installed by default and you get:
```
ImportError: cannot import name 'Prophet' from 'darts.models' (/home/jovyan/work/darts/models/__init__.py)
```

**To Reproduce**
Follow the instruction on the section "Running the examples only, without installing" on a fresh environment. 

**Expected behavior**
The example to run without a need to manual installation. Or add a flag/condition to skip prophet if it is not installed. 

**System (please complete the following information):**
 - Python version: na
 - darts version: 0.5.0

**Comment by ajallooeian** [comment]
The same behaviour for `AutoARIMA`

**Comment by camilaagw** [comment]
@ajallooeian Julien fixed this issue. If you have some time, could you please check it works for you?

**Comment by PhilipMachineLearning** [comment]
Still an issue for me

**Comment by iamMaverick** [comment]
Still an issue.

![image](https://user-images.githubusercontent.com/25539320/179456946-df11bdef-94b5-4b52-9e78-722146f890aa.png)

**Comment by hrzn** [comment]
> Still an issue. @hrzn
> 
> ![image](https://user-images.githubusercontent.com/25539320/179456946-df11bdef-94b5-4b52-9e78-722146f890aa.png)

Please consult the [install guide section explaining how to enable Prophet](https://github.com/unit8co/darts/blob/master/INSTALL.md#enabling-support-for-facebook-prophet). In the next version (0.21.0) we will reinstate prophet as a dependency and this won't be necessary anymore.
