### ISSUE TITLE
What is multivariate prediction in darts, and how to use it?

### ISSUE THREAD

**Issue by coder-rakeshpaul** [unit8co/darts#2549]
Hi, 

I am a bit confused about what is considered multivariate in this library. Let me try to first put my understanding of what I feel multivariate is and please do correct me if I'm wrong and it's called something else.

Say I have 5 columns(features) in a dataframe, and want to predict the future 10 steps values of a particular column. In order to predict this I use the data of previous 50 steps of all the columns.

This is a multivariate problem right? where in I only have the previous values of all 5 columns and want to predict the future value of one of the column.

Then I came across this [page](https://unit8co.github.io/darts/userguide/forecasting_overview.html#support-for-multivariate-series) where they predict values of both the columns(features) which was present. They also stacked the series1 and series2. 

What is the actual way of doing the task I had defined earlier in Darts?

**Comment by coder-rakeshpaul** [comment]
Thanks @madtoinou . The definition of multivariate seems to differ from what I used to think of. I used to think multivariate is a type where we take into consideration multiple independent values to predict a single value similar to [this](https://www.ibm.com/docs/en/cognos-analytics/11.2.0?topic=models-creating-multivariate-forecast). Perhaps I am wrong in this interpretation or maybe something else.

Coming back to the question, yes I want to predict the values of one of the column, but note that I want to use all 5 columns in order to predict that. So as per your answer, does it do this? so like do I have to give the 4 covariates and 1 target or should I give 5 covariates and 1 target?

**Comment by madtoinou** [comment]
The two definitions are pretty much identical; in both cases, you try to leverage the interactions between several components to forecast one of them (and using some kind of symmetry, you can actually forecast all of them using all the others). In contrast of univariate, where you have only one column in the series.

The code should look roughly like this:

```python
# assuming the data is in a csv file
ts = TimeSeries.from_csv(...)

# separate the component that should be forecasted from the covariates/exogenous data
ts_target = ts[["target_col"]]
ts_covs = ts[["feat_0", "feat_1", "feat_2", "feat_3"]]

# output_chunk_length = 10 to forecast the period of interest in one go, without auto-regression
model = RegressionModel(lags=50, output_chunk_length=10)

# train the model
model.fit(series=ts_target, past_covariates=ts_covs)

# forecast the 10 steps after the end of ts_target
forecast = model.predict(n=10)
```

You should be able to find plenty of inspiration in one of the [example notebooks](https://unit8co.github.io/darts/examples.html). The API is identical for univariate and multivariate series.

**Comment by coder-rakeshpaul** [comment]
Thanks @madtoinou for the answer again. I have another question I now understand how to use past and future covariates a bit. I however have one more question. 

This page [here](https://unit8co.github.io/darts/userguide/covariates.html) says that we have to stack the past/ future covariates to use them. In the example you have given we didn't use stack operation, could you please shed some light on how and when to use stack?

**Comment by madtoinou** [comment]
Stacking them is not mandatory, just useful when the covariates come from different files and need to be combined into a single `TimeSeries` before passing them to `fit/predict`.

**Comment by coder-rakeshpaul** [comment]
hi, I followed what you said and am facing some issues. Below is my code
```

# preparing the data
data_series = TimeSeries.from_dataframe(data)

scaler_target = Scaler()
scaler_past_covs = Scaler()
scaler_future_covs = Scaler()

target = data_series[columns[1]]
target = scaler_target.fit_transform([target])
train_target, test_target = target[0].split_before(0.8)

past_covs = data_series[['feat1', 'feat2']]

past_covs = scaler_past_covs.fit_transform([past_covs])
train_past_covs, test_past_covs = past_covs[0].split_before(0.8)

future_covs = data_series[['feat3', 'feat4']]

future_covs = scaler_future_covs.fit_transform([future_covs])
train_future_covs, test_future_covs = future_covs[0].split_before(0.8)

model = DLinearModel(input_chunk_length=1800, output_chunk_length=300, n_epochs=1, batch_size=512)
model.fit(train_target, past_covariates=train_past_covs, future_covariates=train_future_covs)
model.save()

pred = model.predict(n=300, past_covariates=test_past_covs, future_covariates=test_future_covs)
print(pred)

```

and I get the following error

```
ValueError: For the given forecasting case, the provided past covariates at dataset index `0` do not extend far enough into the past. The past covariates must start at time step `1173596`, whereas now they start at time step `1175396`.
ValueError: For the given forecasting case, the provided past covariates at dataset index `0` do not extend far enough into the past. The past covariates must start at time step `1173596`, whereas now they start at time step `1175396`.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/user/Desktop/p006/new_data/nbeats.py", line 51, in <module>
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/torch.py", line 103, in decorator
[rank0]:     return decorated(self, *args, **kwargs)
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1465, in predict
[rank0]:     predictions = self.predict_from_dataset(
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/torch.py", line 103, in decorator
[rank0]:     return decorated(self, *args, **kwargs)
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1559, in predict_from_dataset
[rank0]:     self._verify_predict_sample(input_series_dataset[0])
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 710, in __getitem__
[rank0]:     ) = self.ds_past[idx]
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 418, in __getitem__
[rank0]:     return self.ds[idx]
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 291, in __getitem__
[rank0]:     covariate_start, covariate_end = self._covariate_indexer(
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 98, in _covariate_indexer
[rank0]:     raise_log(
[rank0]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/logging.py", line 132, in raise_log
[rank0]:     raise exception
[rank0]: ValueError: For the given forecasting case, the provided past covariates at dataset index `0` do not extend far enough into the past. The past covariates must start at time step `1173596`, whereas now they start at time step `1175396`.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/user/Desktop/p006/new_data/nbeats.py", line 51, in <module>
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/torch.py", line 103, in decorator
[rank1]:     return decorated(self, *args, **kwargs)
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1465, in predict
[rank1]:     predictions = self.predict_from_dataset(
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/torch.py", line 103, in decorator
[rank1]:     return decorated(self, *args, **kwargs)
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1559, in predict_from_dataset
[rank1]:     self._verify_predict_sample(input_series_dataset[0])
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 710, in __getitem__
[rank1]:     ) = self.ds_past[idx]
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 418, in __getitem__
[rank1]:     return self.ds[idx]
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 291, in __getitem__
[rank1]:     covariate_start, covariate_end = self._covariate_indexer(
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/utils/data/inference_dataset.py", line 98, in _covariate_indexer
[rank1]:     raise_log(
[rank1]:   File "/home/user/anaconda3/envs/ts_p006/lib/python3.10/site-packages/darts/logging.py", line 132, in raise_log
[rank1]:     raise exception
[rank1]: ValueError: For the given forecasting case, the provided past covariates at dataset index `0` do not extend far enough into the past. The past covariates must start at time step `1173596`, whereas now they start at time step `1175396`.
```

**Comment by madtoinou** [comment]
Since you use a huge value as `input_chunk_length` (1800 is really a lot, I would recommend starting with a smaller value), the target and covariates needs to extend far enough in the past for the model to be able to extract its input features/tensor. Since Darts is taking care of slicing the covariates, you actually need to split only the target series to create your train, validation and test splits.

If you want to be extra safe, you can keep your code like this and just concatenate the train and test series back together before generating the forecast (you won't be leaking data since the model already saw it during training). Keep in mind that the future covariates need to extend far enough into the future as well (at least `output_chunk_length` for deep learning models).

**Comment by coder-rakeshpaul** [comment]
> Since Darts is taking care of slicing the covariates, you actually need to split only the target series to create your train, validation and test splits.

could you explain this a bit more. Do you mean that I use `split_before() `only on the target series and not on the past and future covariates as this is taken care by Darts internally?

> Keep in mind that the future covariates need to extend far enough into the future as well (at least output_chunk_length for deep learning models).

yes, the data was from a dataframe and none of the rows had any missing value and were of the same length. Even I was skeptical about splitting the past_covariates, but wasn't sure about it. 

```
data_series = TimeSeries.from_dataframe(data)

scaler_target = Scaler()

target = data_series[columns[1]]
target = scaler_target.fit_transform([target])
train_target, test_target = target[0].split_before(0.8)

past_covs = data_series[['feat1', 'feat2']]
past_covs = scaler_past_covs.fit_transform([past_covs])

future_covs = data_series[['feat3', 'feat4']]
future_covs = scaler_future_covs.fit_transform([future_covs])


model = DLinearModel(input_chunk_length=1800, output_chunk_length=300, n_epochs=1, batch_size=512)
model.fit(train_target, past_covariates=train_past_covs, future_covariates=train_future_covs)
model.save()

pred = model.predict(n=300, past_covariates=test_past_covs, future_covariates=test_future_covs)
print(pred)
```

Also could you confirm my method of using Scaler() and then using split correct? I did it like this so that the testset is also in proper scale with what the trainset was. I'll tone down the input and output chunks to 100 and 30 for now and see what happens. But could you tell me if my method of using covariates and splitting the model correct? Also I would mostly save the model and then load the model to try out the predict on testset even in the future so would ideally like that to work in the future also when I have once stoped this code.

**Comment by madtoinou** [comment]
> could you explain this a bit more. Do you mean that I use `split_before() `only on the target series and not on the past and future covariates as this is taken care by Darts internally?

Yes.

> yes, the data was from a dataframe and none of the rows had any missing value and were of the same length. Even I was skeptical about splitting the past_covariates, but wasn't sure about it.

In order to avoid any issues during inference, make sure that you covariates are indeed past/future covariates based on their availability in the future and the definition provided in the documentation linked earlier in the thread.

> Also could you confirm my method of using Scaler() and then using split correct? 

Ok, so if you want to use `Scaler()`, you indeed need to split the covariates, fit the scaler on training split, then apply it to both splits before concatenaing them together in order to avoid data leakage from the future. Your data preprocessing would look like this

```python
from darts.timeseries import concatenate

data_series = TimeSeries.from_dataframe(data)

target = data_series[columns[1]]
train_target, test_target = target.split_before(0.8)
scaler_target = Scaler()
train_target = scaler_target.fit_transform(train_target)
test_target = scaler_target.transform(test_target)
target = concatenate([train_target, test_target])

# proceed the exact same way for the covariates
past_covs, future_covs = data_series[['feat1', 'feat2']], data_series[['feat3', 'feat4']]
covs_target = Scaler()
train_past_covs, test_past_covs = past_covs.split_before(0.8)
# since future covs can be known in advance, you might be able to scale them without splitting
train_future_covs, test_future_covs = future_covs.split_before(0.8)
# it's possible to fit and transform several series at the same time, the Scaler will use one scaler per series (sensible to the order of the arguments)
train_past_covs, train_future_covs =  covs_target.fit_transform([train_past_covs, train_future_covs])
test_past_covs, test_future_covs = covs_target.transform([test_past_covs, test_future_covs])
past_covs = concatenate([train_past_covs, test_past_covs])
future_covs = concatenate([future_past_covs, future_past_covs])
```

Yeah, the whole point of the checkpoint is to be able to easily load the weights and perform inference on any arbitrary series. Just need to make sure you have enough covariates for the new input series as well.

**Comment by coder-rakeshpaul** [comment]
One clarification, since I have the entire data, I have already have all the values of both past and future covariates. So for the past covariates

I should use this `train_past_covs, test_past_covs = past_covs.split_before(0.8)` but not concatenate them at the end right?`past_covs = concatenate([train_past_covs, test_past_covs])`

This is since they are past covariates and are not known in advance.

so the model will have only
```python

model = DLinearModel(input_chunk_length=1800, output_chunk_length=300, n_epochs=1, batch_size=512)
model.fit(train_target, past_covariates=train_past_covs, future_covariates=future_covs)
```

is this code correct? or should it have been `target` inplace of `train_target`?

**Comment by madtoinou** [comment]
> One clarification, since I have the entire data, I already have all the values of both past and future covariates. So for the past covariates
> 
> I should use this `train_past_covs, test_past_covs = past_covs.split_before(0.8)` but not concatenate them at the end right?`past_covs = concatenate([train_past_covs, test_past_covs])`

During training, the model will never try to get access to future values of the past covariates so you can safely concatenate them (but unnecessary when calling `fit()`). It's for inference (when you call `predict()`) that concatenating might be necessary (depending on the parameters of the model).

> ```python
> model = DLinearModel(input_chunk_length=1800, output_chunk_length=300, n_epochs=1, batch_size=512)
> model.fit(train_target, past_covariates=train_past_covs, future_covariates=future_covs)
> ```
 This code is correct.

> also when calling predict the only arguments to pass would be the number of steps and future_covs right? like
> 
> ```python
> pred = model.predict(n=100, future_convariates= future_covs)
> ```

Correct, because if you fit the model over one target series, it's stored in the model.

> ```python
> model = DLinearModel(input_chunk_length=200, output_chunk_length=100, n_epochs=1, batch_size=128)
> model.fit(target, past_covariates=past_covs, future_covariates=future_covs)
> model.save()
> model.predict(100, future_covariates=future_covs)
> ```

As indicated in the message, your future covariates does not extend far enough into the future to be able to predict 100 steps. Either extend it or use them as past covariates instead.

**Comment by coder-rakeshpaul** [comment]
I'm sorry to take up so much of your time, could you help me understand this with an example?

```python
import pandas as pd
import numpy as np

from darts.models import NBEATSModel, DLinearModel
from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler
from darts.timeseries import concatenate

np.random.seed(42)

data = {
    'feat1': np.random.rand(500) * 100,  # Random floats between 0 and 100
    'feat2': np.random.randint(1, 1000, size=500),  # Random integers between 1 and 999
    'feat3': np.random.randn(500) * 50 + 100,  # Random normal distribution, mean=100, std=50
    'feat4': np.random.uniform(100, 500, size=500),  # Random floats between 100 and 500
    'target': np.random.uniform(10, 500, size=500)  # Random floats between 100 and 500
}

df = pd.DataFrame(data)
data_series = TimeSeries.from_dataframe(df)

target = data_series['target']

train_target, test_target = target.split_before(0.8)
scaler_target = Scaler()

train_target = scaler_target.fit_transform(train_target)
test_target = scaler_target.transform(test_target)
target = concatenate([train_target, test_target])

past_covs = data_series[['feat1', 'feat2']]
future_covs = data_series[['feat3', 'feat4']]

covs_target = Scaler()
train_past_covs, test_past_covs = past_covs.split_before(0.8)
# since future covs can be known in advance, you might be able to scale them without splitting
train_future_covs, test_future_covs = future_covs.split_before(0.8)
train_past_covs, train_future_covs =  covs_target.fit_transform([train_past_covs, train_future_covs])
test_past_covs, test_future_covs = covs_target.transform([test_past_covs, test_future_covs])

past_covs = concatenate([train_past_covs, test_past_covs])
future_covs = concatenate([train_future_covs, test_future_covs])

model = DLinearModel(input_chunk_length=20, output_chunk_length=10, n_epochs=1, batch_size=128)
model.fit(target, past_covariates=past_covs, future_covariates=future_covs)

model.save()
model.predict(10, future_covariates=future_covs)
```

This is a short demo type of code which I created to help me re-create the issue which I'm facing. As you can see I initially have the entire data like the 500 in this case for all the columns. But, feat3 and feat4 are future covariates (meaning I can get this data through some calculations in the future, but for training and testing the model they are just 500 now). Past covariates are feat1 and feat2 (we can't know these values before hand, but for the completion of the dataset we have full 500 of these as well)

so when we split the data 400 is train and 100 is test. 
so at the moment (train_target, train_future_covs, train_past_covs) are all 400. and (test_target, test_future_covs, test_past_covs) are 100.

When the above code is ran, I still get the error when calling predict. Could you help me debug the issue with this test example?

**Comment by madtoinou** [comment]
Hi @coder-rakeshpaul,

I would really recommend going through the quickstart notebook, try to understand one of the examples and adapt one to your use-case. One of the key section is the one about the covariates; understand which indexes/lags are necessary to train & predict each step. That being said, the bug in your code is that you train the model on the entire target series (`target` instead of just the train split, `train_target`) making it so that when you call `predict()`, the model tries to forecast the steps 500 to 509, for which the future covariates are not defined (since the index in the DataFrame strops at 499).

Now that you should have everything to continue on your own, I am going to close this issue. Feel free to open a new one if you have questions about another topics.
