### ISSUE TITLE
Usage of plot_residuals_analysis function

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2550]
![image](https://github.com/user-attachments/assets/b8ada5ac-cdca-4fbc-96cd-4603602277d1)
Based on the description in the github repo above, what would happen if there are missing timestamps in the timeseries of interest? For example, in my specific use case, certain timestamps are not considered during the metrics calculation step due to use-case specific reasons. Hence, the rows are removed from my dataframe. When passing that dataframe to the function, e.g.
`fig = plot_residuals_analysis(TimeSeries.from_dataframe(validation_df[['mean_error']], fill_missing_dates=False, freq='15min'))`, results are still returned without any issues. 

However, the description of the function states that the plots might be displayed incorrectly if there are NaNs. 
![image](https://github.com/user-attachments/assets/8f78ac78-f98c-4e3e-9e72-a8628b77f63e)

**Comment by madtoinou** [comment]
Hi @ETTAN93,

The docstring indicates that the plot will be incorrect and we don't take "responsability" for the results.

If you want to check where the assumption of "no missing value" is critical, I invite you to check the source code of the method [here](https://github.com/unit8co/darts/blob/6c3571df01b75d1b564ca56efbdf1c9898e6a9f9/darts/utils/statistics.py#L998). After having a glimpse at the code, I could not find anything obvious (aside from the fact that the values plotting will implicitly/visually extrapolate values) and the histogram will be incorrectly normalized. Why wouldn't you just extrapolate the missing values for visualization purpose?

**Comment by ETTAN93** [comment]
@madtoinou, after looking at the code it does seem like it only affects the visualization of the code. I would just extrapolate the missing values. thanks
