### ISSUE TITLE
[BUG] Functions in darts.utils.statistics errors if freq="30min"

### ISSUE THREAD

**Issue by harishbalakrishnan3** [unit8co/darts#2556]
**Describe the bug**
The  `remove_trend()` and `extract_trend_and_seasonality()` functions error out when the timeseries frequency is `30min`.

**To Reproduce**
```python
from darts.datasets import TaxiNewYorkDataset

taxi_ny = TaxiNewYorkDataset().load()
detrended_ts = remove_trend(taxi_ny)
# Or
trend_ts, seasonality_ts = extract_trend_and_seasonality(taxi_ny)
```

Observation:

```bash
ValueError: freq MIN not understood. Please report if you think this is in error.
```

**Expected behavior**
No error should be thrown and the respective trend and/or seasonal TS should be returned

**System (please complete the following information):**
 - Python version: 3.12.1
 - darts version: 0.30.0

**Comment by cnhwl** [comment]
Hi! @harishbalakrishnan3 Maybe you could refer to this answer https://stackoverflow.com/a/71298710 
I have modified the code as follows and it works:
`trend_ts, seasonality_ts = extract_trend_and_seasonality(taxi_ny, freq = 2*24)`

**Comment by harishbalakrishnan3** [comment]
Thanks! This solves it. It would have been better if it didn't require us to know the seasonality beforehand.
The timeseries object has a *freq* property. These functions (* remove_trend*, * extract_trend_and_seasonality*) could make use of this property and pass in the appropriate *freq* parameter to the lower level TSA functions.
