### ISSUE TITLE
How to use predict with GPU:0 if the model was intially trained on GPU:1?

### ISSUE THREAD

**Issue by coder-rakeshpaul** [unit8co/darts#2557]
Hi,

I got this error when calling `pred = model.predict(len(test_target),future_covariates=future_covs)`
```
model: TorchForecastingModel = torch.load(
WARNING:darts.models.forecasting.forecasting_model:`predict()` was called with `n > output_chunk_length`: using auto-regression to forecast the values after `output_chunk_length` points. The model will access `(n - output_chunk_length)` future values of your `past_covariates` (relative to the first predicted time step). To hide this warning, set `show_warnings=False`.

---------------------------------------------------------------------------

MisconfigurationException                 Traceback (most recent call last)

[<ipython-input-19-1d090098e453>](https://localhost:8080/#) in <cell line: 6>()
      4     },)
      5 model = TSMixerModel.load('/content/interactive/TSMixerModel_2024-10-08_08_25_44.pt')
----> 6 pred = model.predict(len(test_target),future_covariates=future_covs)
      7 rmse_value = rmse(test_target, pred)
      8 print(f'RMSE: {rmse_value}')

12 frames

[/usr/local/lib/python3.10/dist-packages/lightning_fabric/utilities/device_parser.py](https://localhost:8080/#) in _sanitize_gpu_ids(gpus, include_cuda, include_mps)
    133     for gpu in gpus:
    134         if gpu not in all_available_gpus:
--> 135             raise MisconfigurationException(
    136                 f"You requested gpu: {gpus}\n But your machine only has: {all_available_gpus}"
    137             )

MisconfigurationException: You requested gpu: [1]
 But your machine only has: [0]
```

The model was originally trained on GPU:1, now I sent the model to another system which only has one GPU. Yes while saving the model I didn't do weight_only=True, so part of it is my mistake. 

Is there a way by which I could still use this?

**Comment by madtoinou** [comment]
Hi @coder-rakeshpaul,

In the documentation of `load` ([here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tsmixer_model.html?highlight=load#darts.models.forecasting.tsmixer_model.TSMixerModel.load)), you have actually access to the kwargs of the PytorchLightning method; one of them being `map_location` that allows to load the model onto a different device than the one from which it was saved.

Please try to check the documentation before opening an issue, we often try to include tips & tricks in it :)

**Comment by coder-rakeshpaul** [comment]
Hi @madtoinou , sorry for this. I opened the issue since I had already tried the map_location and it didn't work, guess I should have mentioned that previously so sorry for that.

here is a screenshot, it gives an error not only when I try "cuda:0", but also when I try "cpu" as well
![image](https://github.com/user-attachments/assets/144ff5fe-21e1-4442-94e5-2d4def207abe)

**Comment by dennisbader** [comment]
Hi @coder-rakeshpaul, to run it on cpu you have to call `model.to_cpu()` (as described in the docs).
To run it on gpu 0, could you try (after loading, before `predict()`):

```
model.trainer_params["devices"] = 0
```
