### ISSUE TITLE
[QUESTION] How does the output_chunk_shift parameter affect future time step predictions?

### ISSUE THREAD

**Issue by william1599** [unit8co/darts#2562]
Hello, thank you for the project. I have a question: what happens when the output_chunk_shift parameter in models like TFT is set to 1? Would the model be making a prediction for t+1 (the next value into the future after the end of input_chunk_length) or for t+2 (two steps into the future, with a gap of 1)? What is the difference between using output_chunk_shift set to 0 and 1?". 

Thank you in advance.

**Comment by dennisbader** [comment]
Hi @william1599, `output_chunk_shift` is the gap between the input and output chunk. So `0` has no gap, `1` has a gap of one (e.g. t+2 if t is the last step in the input chunk).

**Comment by william1599** [comment]
I understand, thank you for the response!
