### ISSUE TITLE
[QUESTION] How to handle irregular data intervals

### ISSUE THREAD

**Issue by MicahJSherry** [unit8co/darts#2564]
I am currently working on a Forecasting model that will predict when events will occur.  The end goal model is to have a that takes in some data about the state of an object and forecasts when events will occur to this object. One of my problems however is that I get data from the object at irregular intervals. Any suggestions for solutions to this problem? Also Any suggestions for models that would work well for this task?

this is the summary of how my input data is distributed across time
mean     0 days 01:21:40.160942611
std      0 days 03:08:45.910175375
min         0 days 00:00:00.085818
25%         0 days 00:16:53.688969
50%         0 days 00:25:15.661705
75%         0 days 00:51:43.378983
max         1 days 06:32:04.973988

**Comment by madtoinou** [comment]
Hi @MicahJSherry,

This kind of task is not yet supported by Darts, you can find some of the discussion in #1838 and #1571.

One possible workaround would be to resample the series at a higher frequency (resolution high enough to capture all the events), assign one class to the events, another one to "no event" and then, modify the Darts models to convert them into classifier and predict for each time-step if an event is going to happen or not.

**Comment by MicahJSherry** [comment]
thanks
