### ISSUE TITLE
[QUESTION] How to save a `darts.dataprocessing.pipeline.Pipeline` to disk so it can be reuse?

### ISSUE THREAD

**Issue by 40001277-FEA** [unit8co/darts#2568]
How to save a `darts.dataprocessing.pipeline.Pipeline` to disk so it can be reuse?

**Comment by dennisbader** [comment]
Hi @40001277-FEA, we don't have any dedicated storing support the `Pipeline`. You could always just pickle the object keeping in mind the caveats that come with it (or similar methods).
