### ISSUE TITLE
[BUG] create_lagged_component_names does not return target column names

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#2574]
![image](https://github.com/user-attachments/assets/139f8b1d-75e7-4a06-8e9d-abd36b377759)

From the documentation above, the function create_lagged_component_names is supposed to return the names of the target columns. However, when I run the function below, I get back an empty list:

```
from darts.utils.data.tabularization import create_lagged_component_names, create_lagged_training_data, create_lagged_prediction_data
target_lags = None
past_cov_lags = list(range(-8, 0))
future_cov_lags = list(range(-22, 21))

lagged_data_component_names = create_lagged_component_names(
    target_series=hf_data_dict['target_fit'],
    past_covariates=hf_data_dict['past_cov_fit'],
    future_covariates=hf_data_dict['future_cov_fit'],
    lags=target_lags,
    lags_past_covariates=past_cov_lags,
    lags_future_covariates=future_cov_lags,
    output_chunk_length=3,
    use_static_covariates=False
)
lagged_data_component_names[1]
```

This what my target_fit, past_cov_fit and future_cov_fit looks like:
![image](https://github.com/user-attachments/assets/b88f3b12-2aa2-4779-bb22-359d5ad5e92f)
![image](https://github.com/user-attachments/assets/def093fe-0f1e-4bc3-8825-417c495d2998)

As far as I understand the last n (forecast_horizon) names in `lagged_data_component_names[0][-forecast_horizon:]` should be equivalent to the output in `lagged_data_component_names[1]`? 

Since my target name is `edm_power_feed_in_diff `and my `output_chunk_length=3`, I would expect create_lagged_component_names[1] to return` [edm_power_feed_in_diff_hrz1, edm_power_feed_in_diff_hrz2, edm_power_feed_in_diff_hrz3]` ?

**Comment by dennisbader** [comment]
Hi @ETTAN93, your target lags are `None` so there will not be any lagged target feature.

**Comment by dennisbader** [comment]
Hi @ETTAN93 , it's indeed a bug that happens when `lags=None` (target lags). I'll open a fix soon.
