### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hassanbaablaki** [unit8co/darts#258]
**Describe the bug**
I have installed darts on a dedicated conda enviroment 
However it seems that package darts.dataprocessing is not installed even thought  used the pip install u8darts[all]

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.
conda create drt-env python=3.7
conda install -c conda-forge -c pytorch pip fbprophet pytorch cpuonly

python -c "import darts; import darts.models;print(dir(darts.models)); import  darts.dataprocessing.transformers; print(dir(darts))"
['ARIMA', 'AutoARIMA', 'ExponentialSmoothing', 'FFT', 'NaiveDrift', 'NaiveMean', 'NaiveSeasonal', 'Prophet', 'RNNModel', 'StandardRegressionModel', 'TCNModel', 'Theta', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'arima', 'baselines', 'exponential_smoothing', 'fft', 'forecasting_model', 'prophet', 'regression_model', 'rnn_model', 'standard_regression_model', 'tcn_model', 'theta', 'torch_forecasting_model']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'darts.dataprocessing'

**Expected behavior**
To be able to used the tansformers packager

**System :**
 - Python version: 3.7.9
 - darts version  propably 0.2.2 I got a warning when tried to reinstall darts using  pip install u8darts[all]
 - WARNING: u8darts 0.2.2 does not provide the extra 'all'

**Comment by hassanbaablaki** [comment]
After further research it seems that if the latest version of pythorch is installed (1.7.1) then the version 0.2.2 of darts is installed 
when using `pip install u8darts[all] `instead of the latest

When I tried to force install the version 0.5 
`pip install u8darts[all]=0.5.0`
I go and error as it required the version 1.5.1 of pythorch instead of the latest 1.7.1

And as suggested  by https://github.com/unit8co/darts/issues/235

`conda install -c conda-forge -c pytorch pip fbprophet pytorch==1.5.1 cpuonly`
then I was able to install the latest version of 
`pip install u8darts[all]=0.5.0`

**Comment by initeam** [comment]
> After further research it seems that if the latest version of pythorch is installed (1.7.1) then the version 0.2.2 of darts is installed when using `pip install u8darts[all] `instead of the latest
> 
> When I tried to force install the version 0.5 `pip install u8darts[all]=0.5.0` I go and error as it required the version 1.5.1 of pythorch instead of the latest 1.7.1
> 
> And as suggested by #235
> 
> `conda install -c conda-forge -c pytorch pip fbprophet pytorch==1.5.1 cpuonly` then I was able to install the latest version of `pip install u8darts[all]=0.5.0`

A small correction Hassan ie pip install u8darts[all]==0.5.0
