### ISSUE TITLE
[QUESTION] Static covariants have no effect on prediction with XGBoost model

### ISSUE THREAD

**Issue by skull3r7** [unit8co/darts#2587]
**Describe the issue linked to the documentation**
I have recreated the example of [https://unit8co.github.io/darts/examples/15-static-covariates.html](url) for static covariants with the XGBoost model. Here, the different covariants have an influence on the prediction, depending on how the covariants were selected. Now I have tried to apply static covariants to the WeatherDataset. However, the forecast does not change here, regardless of which values you choose for the static covariants. I had expected the forecast to change at least minimally, but it turns out exactly the same (identical RMSE score).

The code:
```
    from darts.datasets import WeatherDataset
    from darts.models import XGBModel
    from darts.dataprocessing.transformers import StaticCovariatesTransformer
    from darts.metrics import rmse

    series = WeatherDataset().load()
    target = series['p (mbar)'][:100]
    past_cov = series['rain (mm)'][:100]
    future_cov = series['T (degC)'][:106]
    transformer = StaticCovariatesTransformer()


    #Model without static covariants
    model = XGBModel(
        lags=12,
        output_chunk_length=6,
    )
    model.fit(target)
    pred = model.predict(20, series=target[:80])
    pred.values()
    target.plot()
    pred.plot()


    #Model with static covariants
    model = XGBModel(
        lags=12,
        output_chunk_length=6,
    )
    
    df = pd.DataFrame(data={'val1': [1000000], 'val2': [1006], 'val3': [0]})
    target = target.with_static_covariates(df)

    model.fit(target)
    pred2 = model.predict(20, series=target[:80])

    plt.show()

    print(pred.static_covariates)
    print(pred2.static_covariates)
    print(f'RMSE: {rmse(target, pred)}')
    print(f'RMSE: {rmse(target, pred2)}')
```

**Additional context**
darts==0.31.0

**Comment by dennisbader** [comment]
Hi @skull3r7, static covariates are only useful if you have multiple target series with different static cov values.
Otherwise, with only one series, your static covs are constant and do not provide any useful information.
