### ISSUE TITLE
[QUESTION]  ValueError: This model has been trained with `static_covariates`; some `static_covariates` of matching dimensionality are needed for prediction.

### ISSUE THREAD

**Issue by Manohar0077** [unit8co/darts#2599]
I encountered the error:

> ValueError: This model has been trained with `static_covariates`; some `static_covariates` of matching dimensionality are needed for prediction.

I trained, saved, and later loaded the model that was trained with a series containing static_covariates. During prediction, despite passing the same static_covariates (with matching dimensionality), I encounter the above error:

Thank you!

**Comment by madtoinou** [comment]
Hi @Manohar0077,

Can you please share a code snippet reproducing the issues so that we can investigate the issue? Thank you

**Comment by Manohar0077** [comment]
Thanks for the response @madtoinou . I was able to resolve it. Thanks.

**Comment by ajccon** [comment]
hi - I'm getting the same issue... can you share how was this resolved?

**Comment by madtoinou** [comment]
Hi @ajccon,

Double check that you use the same static covariates during training and inference, also, the number of components in the time-series should also be similar.

**Comment by Manohar0077** [comment]
Hey @ajccon, 
- For **Inference:** If the model is saved in `.pt` and `.ckpt` format, you can load it directly using `Model.load()` (e.g., `TiDEModel.load("saved_model_filename")`).

- For **Retraining or Fine-Tuning:** To retrain or fine-tune the model, first initialize it with the same parameters used during training, and then load the saved weights using `model_name.load_weights("saved_model_filename")`.


This is what worked for me.

**Comment by madtoinou** [comment]
Thank you @Manohar0077 for your answer.

@ajccon, there is detailed information about retraining and checkpointing of the torch-based models in [this page of the documentation](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#saving-and-loading-model-states).
