### ISSUE TITLE
[BUG] Cannot train with MeanSquaredError

### ISSUE THREAD

**Issue by strakehyr** [unit8co/darts#2600]
**Bug Description**

The bug is sprung by passing MeanSquaredError wrapped in MetricCollection to torch_metrics on the model and attempting to fit it. 
The error points to some interaction between darts utils and torchmetrics:

> RuntimeError                              Traceback (most recent call last)
> File site-packages\darts\utils\torch.py:103, in random_method.<locals>.decorator(self, *args, **kwargs)
>     101 with fork_rng():
>     102     manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
> --> 103     return decorated(self, *args, **kwargs)
> 
> [... additional trace lines with site-packages paths ...]
> 
> File site-packages\torchmetrics\regression\mse.py:102, in MeanSquaredError.update(self, preds, target)
>     100 def update(self, preds: Tensor, target: Tensor) -> None:
>     101     """Update state with predictions and targets."""
> --> 102     sum_squared_error, num_obs = _mean_squared_error_update(preds, target, num_outputs=self.num_outputs)
>     104     self.sum_squared_error += sum_squared_error
>     105     self.total += num_obs
> 
> File site-packages\torchmetrics\functional\regression\mse.py:36, in _mean_squared_error_update(preds, target, num_outputs)
>     34 if num_outputs == 1:
>     35     preds = preds.view(-1)
> ---> 36     target = target.view(-1)
>     37 diff = preds - target
>     38 sum_squared_error = torch.sum(diff * diff, dim=0)
> 
> RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**To Reproduce**

```
model = TSMixerModel(input_chunk_length=lookback, 
						output_chunk_length=horizon,
						activation = 'LeakyReLU',
						dropout = 0.2,
						batch_size = 512,
						use_static_covariates = False,
						use_reversible_instance_norm = True,
						pl_trainer_kwargs = {"gradient_clip_val": 1,
							"max_epochs": 300,
							"accelerator": "cuda",
							"logger": WandbLogger(log_model="all"),
							"callbacks": [EarlyStopping(
									monitor="val_loss",
									patience=10,
									min_delta=1e-6,
									mode="min"), 
								TFMProgressBar(enable_sanity_check_bar=False, 
									enable_validation_bar=False),
								LearningRateMonitor(logging_interval='epoch')],
						},
						optimizer_cls = torch.optim.SGD,
						optimizer_kwargs = {'lr': lr},
						torch_metrics = MetricCollection([MeanSquaredError()]), 
						lr_scheduler_cls = torch.optim.lr_scheduler.ReduceLROnPlateau, 
						lr_scheduler_kwargs = dict(mode='min',     
												factor=0.1,       
												patience=7,       
												threshold=0.0006, 
												min_lr=1e-7),   
						save_checkpoints = True)
						
						
model.fit(series = series,
			past_covariates = past_covariates,
			future_covariates = future_covariates,
			val_series = val_series,
			val_past_covariates = val_past_covariates,
			val_future_covariates = val_future_covariates)
```

**Expected behavior**

The same works with MAE, MAPE and others. It just doesn't work on MSE...

**System:**

- python: 3.11.5
- darts: 0.31.0
- torch: 2.4.1+cu124
- torchmetrics: 1.5.2
- pytorch_lightning: 2.4.0

**Comment by dennisbader** [comment]
Hi @strakehyr, this is already fixed in the current master branch, but not merged yet.
In the meantime before our next release, you can either downgrade torchmetrics to <1.5.0 or install darts from the current master.
