### ISSUE TITLE
[QUESTION] Reference on BlockRNN

### ISSUE THREAD

**Issue by kusumy** [unit8co/darts#2608]
Is there any reference regarding BlockRNN model that I can read? I am not a coding guy so i prefer reading documentation or articles than source code to know how BlockRNN works.

Thank you in advance

**Comment by madtoinou** [comment]
Hi @kusumy,

You can find some information about this model in its [documentation page](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.block_rnn_model.html): "this is a neural network model that uses an RNN encoder to encode fixed-length input chunks, and a fully connected network to produce fixed-length outputs.".

There is also more information disseminated in various threads such as #2563, #1623 or #546.
