### ISSUE TITLE
[QUESTION] Scaled data on BlockRNN

### ISSUE THREAD

**Issue by kusumy** [unit8co/darts#2615]
Is it ok to use scaled input data on BlockRNN?
I've read the RNN example notebook, and the input data for the model is scaled, and the output seems unscaled.
But on the BlockRNN example,  the input data is not scaled.

Thanks in Advance

**Comment by madtoinou** [comment]
Hi @kusumy,

This is a little mistake/overlook in the BlockRNN notebook; it is generally better to scale data before using any of the Torch-based (deep learning) models, including the BlockRNN one.
