### ISSUE TITLE
[BUG] optimized historical_forecasts has incorrect time indices under certain conditions

### ISSUE THREAD

**Issue by MattiasDC** [unit8co/darts#2633]
**Describe the bug**
When generating a historical forecast using regression model and last point forecasting on a model with `output_chunk_shift > 0`, time indices are not shifted according to the `output_chunk_shift`. This is only the case when doing an 'optimized' historical forecast (when you get into `darts.utils.historical_forecasts.optimized_historical_forecasts_regression._optimized_historical_forecasts_last_points_only`.

**To Reproduce**
```
from darts.datasets import AirPassengersDataset
from darts.models import RegressionModel

series = AirPassengersDataset().load()

model = RegressionModel(lags=20, output_chunk_shift=5)
model.fit(series)

historical = model.historical_forecasts(series=series,
                                        retrain=False,
                                        forecast_horizon=1)


series.plot(label="actual")
historical.plot(label="historical")
```

This will plot this image:
![image](https://github.com/user-attachments/assets/4b33c0c2-c527-4a42-90c4-7e19a56f1ac6)

**Expected behavior**
The returned historical series don´t have their time index shifted respecting the output chunk shift.
The following result would be correct:
![image](https://github.com/user-attachments/assets/05e885f6-9e44-4cdc-aa06-6c96e4eca06a)

**System (please complete the following information):**
 - Python version: 3.12
 - darts version 0.31.0

**Additional context**
I will create a PR for this.
I've also inspected `darts.utils.historical_forecasts.optimized_historical_forecasts_regression._optimized_historical_forecasts_all_points`, which does seem to always take into account the `output_chunk_shift` unconditionally. I also looked at `darts.utils.historical_forecasts.optimized_historical_forecasts_tocrch._optimized_historical_forecasts`, which also doesn´t seem affected.

**Comment by dennisbader** [comment]
Thanks a lot @MattiasDC for opening this issue, the well documented report and the PR 🚀 🚀 🚀 
Let's continue this thread in #2634
