### ISSUE TITLE
[BUG]: historical_forecasts() only returns N-1 predictions - last point missing

### ISSUE THREAD

**Issue by italobale** [unit8co/darts#271]
Looking at this notebook, for example:
https://unit8co.github.io/darts/examples/05-RNN-examples.html

one can see, for example in the plot produced in cell [12], that in the backtest_series the last point is missing (i.e. the prediction for the last point of the 'actual' time series is missing). 

Unless I misunderstood the historical_forecast() method, this seems to be a small bug.

Could you please, check/fix this issue?
Thanks

**Comment by camilaagw** [comment]
Hi @italobale,
Thank you for reporting this bug. I have checked the current behaviour of `historical_forecasts` and you are right, the prediction is missed for the last point. I have made a PR to fix this issue
