### ISSUE TITLE
input data issues

### ISSUE THREAD

**Issue by szncoin** [unit8co/darts#274]
I understand darts models take time-series dataframes as input data. Ideally, the input data is a sequence of time-ordered data points (time series), if occasionally some data points are missing, darts have some strategies to fill the missing data. However, my time series data consists of multiple segments of time series, e.g.: one segment from 2020-01-01 to 2020-01-05, the next segment is from 2020-01-07 to 2020-01-10 (i.e., 2020-01-06 data is not included). I need to construct time series data within a segment, e.g., build time series ONLY from 2020-01-01 to 2020-01-05 range, or from 2020-01-07 to 2020-01-10 range. NOTE: 2020-01-06 is not used and NO NEED TO FILL THE MISSING DATA of 2020-01-06. So does darts support such data modeling? if yes, how to set the relevant parameters?

**Comment by camilaagw** [comment]
Hi @szncoin,

If I understand you correctly, you want to construct TimeSeries objects with the non-null segments of your data. I suggest you to take a look at the utils for [handling missing values](https://unit8co.github.io/darts/generated_api/darts.utils.missing_values.html) , in particular I recommend for this case the `extract_subseries` function. It receives a TimeSeries object and partitions the series into a list of sub-series (also TimeSeries objects) by using 
 gaps of missing values:
 ```
from darts.utils.missing_values import extract_subseries
from darts import TimeSeries

series = TimeSeries.from_dataframe(df, 'time', ['target'])
 list_of_series = extract_subseries(series)
```

When it comes to training a model on these sequences  of TimeSeries, you can use global models, as they support [training on multiple series](https://github.com/unit8co/darts/blob/master/examples/02-multi-time-series-and-covariates.ipynb). For the time being, there are 4 global models:
- RNNs
- Temporal Convolutional Networks (TCNs)
- N-Beats
- Transformer model

**Comment by hrzn** [comment]
@szncoin to complement on what @camilaagw said, basically what you described should probably be represented by several TimeSeries objects (one instance per segment)

**Comment by szncoin** [comment]
@hrzn @camilaagw thanks for the answers.
