### ISSUE TITLE
[BUG] Torch Models fit: ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by vl2376** [unit8co/darts#276]
**Describe the bug**

I get the following error when trying to run a `torch` model (I have tried RNN, NBEATS):

```
  File "darts\models\torch_forecasting_model.py", line 292, in fit
    logger.info('Train dataset contains {} samples.'.format(len(train_dataset)))

ValueError: __len__() should return >= 0
```

**To Reproduce**
```
from darts.models import RNNModel, NBEATSModel

model = RNNModel(model = "RNN",
                  input_chunk_length = len(train),
                  output_chunk_length = len(test))

model.fit(series = train)
```

**System (please complete the following information):**
 - Python version: 3.6
 - darts version 0.6.1

**Comment by mustafaaydn** [comment]
Hi, you are supplying the whole series' length as the  `input_chunk_length` here:
>`input_chunk_length = len(train)`,
and therefore there remains no target value to form the "labels" in the supervised setting for the RNN! The figure [here](https://unit8co.github.io/darts/examples/02-multi-time-series-and-covariates.html#Training-Process-(behind-the-scenes)) i think will clarify things.

**Comment by hrzn** [comment]
Thanks for the answer @mustafaaydn, that's correct.
