### ISSUE TITLE
ModuleNotFoundError: No module named 'darts'

### ISSUE THREAD

**Issue by cosmerodolfo** [unit8co/darts#281]
Message appears on Anaconda console: _ModuleNotFoundError: No module named 'darts_'

**To Reproduce**
- Create a New environment. In my case I used Anaconda Navigator;
- Confirm that the Python version is above 3.6
- Using CMD Prompt of Anaconda, execute: pip install u8darts[all];
- Use the following model call procedure:
        _from darts.models import NBEATSModel
        model_PLDHorario = NBEATSModel(input_chunk_length = 48, output_chunk_length = 24)_

**Expected behavior**
It is expected that NBEATS model is recognized.

**System (please complete the following information):**
 - Python version: [3.7.10]
 - u8darts version [0.6.1]

**Additional context**
![image](https://user-images.githubusercontent.com/34916389/109677593-94e05380-7b58-11eb-9d2e-e83a3760c379.png)

**Comment by tneuer** [comment]
Thanks for bringing this to our attention. I tried to reproduce the issue in your specified environment and for me it worked (on macOS Big Sur). I don't see it in your output but I assume you chose the correct conda env where everything is installed, so maybe it's an issue on Windows? 
I'll try to reproduce it on a different OS as soon as I can.

**Comment by cosmerodolfo** [comment]
Hello,

Yesterday I could solve the problem.
The solution was the insertion of my virtual environment path on PYTHONPATH.

Thanks for the prompt answer!


Em sex, 5 de mar de 2021 08:37, tneuer <notifications@github.com> escreveu:

**Comment by tneuer** [comment]
Awesome! Glad to hear that, so we consider the issue to be closed.
