### ISSUE TITLE
Implement DeepAR model and DeepMAR model

### ISSUE THREAD

**Issue by venergiac** [unit8co/darts#283]
**Is your feature request related to a current problem? Please describe.**
Build DeepAR model

**Describe proposed solution**
https://arxiv.org/abs/1704.04110

**Describe potential alternatives**
Eg.

https://github.com/husnejahan/DeepAR-pytorch

**Comment by tneuer** [comment]
Thanks a lot for the suggestion! We're currently planning to implement a lot of new features in upcoming releases, but we're always eager to check out new state-of-the-art models. We'll take a closer look at it and then prioritise accordingly :)
