### ISSUE TITLE
Parallelise gridsearch computation

### ISSUE THREAD

**Issue by whiletruelearn** [unit8co/darts#287]
**Is your feature request related to a current problem? Please describe.**
Great library. Can we think of running different models in parallel while doing `gridsearch`.
Current search is sequential and takes a lot of time.

**Describe proposed solution**
Bring in some multiprocessing logic for efficient gridsearch operation.

**Describe potential alternatives**
we can thinking of using `ray.tune` , `joblib` or simple `multiprocessing`  for this feature.

**Additional context**

This will be a useful enhancement IMHO

**Comment by tneuer** [comment]
Great suggestion! That would indeed be useful and speed up things. We'll see if we manage to implement this in the next release and keep you updated.
Thanks for the input and we're glad you like the library :)

**Comment by hrzn** [comment]
+1, good idea

**Comment by hrzn** [comment]
This is now part of v0.9.0.
