### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found - Windows Pycharm

### ISSUE THREAD

**Issue by louisgrimaldi** [unit8co/darts#297]
**Describe the bug**
udarts8 installation crashes config on previously installed packages [Pycharm, Windows]

**To Reproduce**
On a Windows machine :
1. `conda create --name udarts_bug`
2. `conda activate udarts_bug`
3. `(udarts_bug) conda install python=3.7.9`
4. `(udarts_bug) pip install seaborn`

Now in Pycharm : 
1. create a `darts.py` file :
```
import seaborn as sns
print('foo bar')
```
2. Select the `udarts_bug` conda environment in the configuration 
3. run `darts.py`
4. `> foo bar`

Now with u8darts :
1. `(udarts_bug) pip install u8darts`
2. run `darts.py`
3. `OSError: [WinError 126] The specified module could not be found`
![image](https://user-images.githubusercontent.com/24357652/111450463-51651800-8708-11eb-8d18-416be5956434.png)

**Expected behavior**
The code should run fine on Pycharm.

**System (please complete the following information):**
 - Python 3.7.9
 - darts 0.6.1
 - Pycharm 2019.1.1
 - Windows 10
 
**Additional context**
Note that the code works fine when run from the command line.

![image](https://user-images.githubusercontent.com/24357652/111450011-dc91de00-8707-11eb-91ce-0f66e11bf5ad.png)

**Comment by hrzn** [comment]
This looks like an issue with scipy (seabordn relies on scipy, and Darts is forcing scipy==1.5.0 which perhaps causes an issue in your case). Could you try updating scipy? `pip install scipy -U`

**Comment by louisgrimaldi** [comment]
Just tried, that works ! 
Still confused as of why it would run fine in Pycharm vs command line with the same virtual environment and packages.
Oh well, thank you very much @hrzn
