### ISSUE TITLE
Using multiple covariates in LSTM model throws error when fitting.

### ISSUE THREAD

**Issue by TahaSha** [unit8co/darts#299]
**Describe the bug**
When adding the list of covariates I get this error :
`ValueError: The provided sequence of target series must have the same length as the provided sequence of covariate series.`

**To Reproduce**

```
import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import RNNModel
from darts.dataprocessing.transformers import Scaler

# Create toy dataset
idx = pd.date_range(start=pd.Timestamp('2020-01-01'), freq='MS', periods=10 )
df = pd.DataFrame({
    'target':np.random.randint(100, 10000, size=10,),
    'var1' :np.random.randint(100, 10000, size=10,),
    'var2' :np.random.randint(100, 10000, size=10,),
    'var3' :np.random.randint(100, 10000, size=10,)
}, index= idx)

# Creating Time series target and variables
series_target = TimeSeries.from_dataframe(df,value_cols=['target'])
series_var1 = TimeSeries.from_dataframe(df,value_cols=['var1'])
series_var2 = TimeSeries.from_dataframe(df, value_cols = ['var2'])
series_var3 = TimeSeries.from_dataframe(df, value_cols = ['var3'])

# Scaling the series
scaler_target = Scaler()
scaler_var1 =  Scaler()
scaler_var2 = Scaler()
scaler_var3 = Scaler()
series_target_scaled = scaler_target.fit_transform(series_target)
series_var1_scaled = scaler_var1.fit_transform(series_var1)
series_var2_scaled = scaler_var2.fit_transform(series_var2)
series_var3_scaled = scaler_var3.fit_transform(series_var3)

# Training and Validation Split
split_time = pd.Timestamp('2020-07-01')
train_target, val_target = series_target_scaled.split_after(split_time) 
train_var1, val_var1 = series_var1_scaled.split_after(split_time) 
train_var2, val_var2 = series_var2_scaled.split_after(split_time) 
train_var3, val_var3 = series_var3_scaled.split_after(split_time) 

# Create model
model = RNNModel(
    model='LSTM',
    input_chunk_length=6,
    output_chunk_length=3,
    hidden_size=32,
    n_rnn_layers=1,
    dropout=0.2,
    batch_size=8,
    n_epochs=200,
    optimizer_kwargs={'lr': 1e-3},
    model_name='test_lstm',
    log_tensorboard=True,
    random_state=42
)

# Fitting with covariates  (error here)
model.fit(series=train_target, 
          covariates=[train_var1, train_var2, train_var3], 
          verbose=True)
```

**Expected behavior**
Model to fit so I can later predict using:

```
# Predicting With Covariate 
pred_cov = model.predict(n=3, 
                         series= train_target, 
                         covariates= [train_var1, train_var2 , train_var2 ])
```

**System (please complete the following information):**
 - Python version: [e.g. Python 3.7.10]
 - darts version --> I'm not sure but I used `!pip install 'u8darts[all]'` 

**Additional context**
I'm unsure about the difference of covariate vs. multivariate. To make it work, I have to fit the same number of series and covariates in the `.fit()` and `.predict() ` I only care about predicting the `target` and only using `var1, var2, var3` to help predict the `target`.

**Comment by hrzn** [comment]
That's because the model expects one covariate TimeSeries per target TimeSeries. Here you specify 1 target series (`series=train_target`), so you should specify one covariate TimeSeries (instead of 3). If you'd like to capture 3 dimensions in your covariates you can provide a multivariate TimeSeries containing 3 dimensions (instead of 3 TimeSeries).

**Comment by phellstrand77** [comment]
@hrzn would you be so kind as to help explain how one create a 'multivariate TimeSeries'? I'm experiencing the same issue?

**Comment by TahaSha** [comment]
@phellstrand77 Hey, you should probably start on their website. They explain Darts' interpretation of covariates and how to use them [here](https://unit8co.github.io/darts/userguide/covariates.html).

Alternatively, you can join their discord channel to ask questions [here](https://discord.gg/GKH22Hc9nw).

**Comment by phellstrand77** [comment]
@TahaSha I've read everything there is on Darts and experimented extensively, and haven't come across the answer. Do you know it?

**Comment by hrzn** [comment]
Hi @phellstrand77, there are several ways to build a multivariate series. For example:
* From a Pandas DataFrame containing multiple columns (one per dimension), you can do `TimeSeries.from_dataframe(df, time_col, value_cols)` where `value_cols` is the list of columns that you want to integrate.
* From several univariate `TimeSeries`, you can do
```
from darts import concatenate
my_multivariate_series = concatenate([series1, series2, ...], axis=1)
```

I hope this helps.

**Comment by phellstrand77** [comment]
@hrzn This is super helpful, thank you! Separately: Regarding the length of Series and Covariates, I understand that a ‘set’ of series and covariates (univariate or multivariate) need to be of the same length, I.e. Series_1 and Covariate_1 need to match. However can the ’set’ of Series_2 and Covariate_2 be of a different lengths and/or resolution (day vs week) than the set of Series_1 and Covariate_1?

**Comment by phellstrand77** [comment]
@hrzn to elaborate, which is why I asked about above; I get a “ValueError: all input arrays must have the same shape” when trying to fit two series with two covariates. Series 1 is univariate and Covariate 1 is multivariate (2x value columns); dates and lengths match. Series 2 is also univariate and Covariate 2 is multivariate (4x value columns); dates and lengths also match, although different lengths from Series 1 and Covariate 1. Would you be so kind to explain where I’m violating the rules?

**Comment by phellstrand77** [comment]
@hrzn if I limit Covariate 2 to 2x value columns (match the number of columns in Covariate 1) vs 4x value columns it works… Any way to get around this ‘problem’ so I can have Covariate series with different number of columns? I’ve tried stacking in a few sequences vs concatenation to see if that’s the issue, but it’s not. The arrays look fine either way.

**Comment by hrzn** [comment]
@phellstrand77 In fact the target series and the covariates need not be aligned in time. All that's required is that the covariate has a sufficient time span. Darts then takes care of slicing the covariates in time by looking at the time indexes of the target and corresponding covariate.
All the covariates provided (for multiple targets time series) have to have the same number of dimensions/components. This is because all models have fixed input/output dimensionalities. For instance, a neural net with input dimension N always expects samples of dimension N (for both training and inference). There might be, in the future, some forecasting models appearing that work on a dynamic number of dimensions, but so far AFAIK such models don't really exist, and so this requirement holds for all models currently in Darts.

**Comment by phellstrand77** [comment]
@hrzn thank you very much, I now understand the constraints.

**Comment by chartsengrafs** [comment]
Hi. I have been reading this thread and  the documentation. However, I am still confused about the case where you have multiple targets and multiple covariates. By that I mean I have a list of target series `y1,y2` . I also have the first covariate with `x1,x2`. But on top of that I have another group of covariates `x1_1 , x2_2`. How do I combine all the X's so they have the matching length?

**Comment by chartsengrafs** [comment]
> Hi. I have been reading this thread and the documentation. However, I am still confused about the case where you have multiple targets and multiple covariates. By that I mean I have a list of target series `y1,y2` . I also have the first covariate with `x1,x2`. But on top of that I have another group of covariates `x1_1 , x2_2`. How do I combine all the X's so they have the matching length? If I stack the two sets of covariates won't I have a length of while the target series is still just 2?

Here is an example where I get an error "ValueError: all input arrays must have the same shape":
`search_train_scaled_ts_19 = search_train_scaled_ts_19.stack(sales_train_ts_19)
search_train_scaled_ts_24 = search_train_scaled_ts_24.stack(sales_train_ts_24)
NHITS_GLOBAL  = NHiTSModel(input_chunk_length =52, output_chunk_length =1, num_stacks=3, num_blocks=1, num_layers=2, 
           layer_widths=512, pooling_kernel_sizes=None, 
           n_freq_downsample=None, dropout=0.1, activation='ReLU', MaxPool1d=True, pl_trainer_kwargs={
      "accelerator": "gpu", 
      "devices": [3]}, n_epochs =100)
import time
start_time = time.time()
NHITS_GLOBAL.fit(series=[train_scaled_ts_19, train_scaled_ts_24], 
                         past_covariates=[search_train_scaled_ts_19,search_train_scaled_ts_24],
                         verbose=True)
print("--- %s seconds ---" % (time.time() - start_time))`

**Comment by hrzn** [comment]
@chartsengrafs all your covariates must have the same dimension (say, N), and all your targets must have the same dimension (say, M). It is OK if N != M though. Could you check whether those conditions are respected? If you still run into an issue, please post a fully self-contained code snippet so we can try and reproduce your issue.

**Comment by snaiws** [comment]
> Hi @phellstrand77, there are several ways to build a multivariate series. For example:
> 
> * From a Pandas DataFrame containing multiple columns (one per dimension), you can do `TimeSeries.from_dataframe(df, time_col, value_cols)` where `value_cols` is the list of columns that you want to integrate.
> * From several univariate `TimeSeries`, you can do
> 
> ```
> from darts import concatenate
> my_multivariate_series = concatenate([series1, series2, ...], axis=1)
> ```
> 
> I hope this helps.

This quote must be included in Darts docs. 👍
