### ISSUE TITLE
[BUG] Documentation typo

### ISSUE THREAD

**Issue by giordafrancis** [unit8co/darts#340]
**Describe the bug**
https://unit8co.github.io/darts/#contact-us

Lower end of the page  page "To build documantation locally just run" should read "To build documentation..."

PS: Thank you for the great library :)

**Comment by hrzn** [comment]
Thanks for the feedback :) But I don't really understand what's the issue here?

**Comment by giordafrancis** [comment]
it's just a typo in the page documentation page link above. Where it says to "To build documantation locally just run" should read "To build documentation..."

I'm a bit of a newbie on contribution, not sure if this shoudl be here as an issue or how to fix this myself :)

**Comment by hrzn** [comment]
Oh yeah I got the typo now. Thanks! We'll correct this soon.
