### ISSUE TITLE
Forecasting models not utilizing all GPU's available.

### ISSUE THREAD

**Issue by TahaSha** [unit8co/darts#343]
**Describe the bug**
I have a script that runs multiple global models (RNN's, TCN's, Theta, Exp) and I am running the script on a GCE VM with 2 GPU's. 
When I ran the script. I got this warning (below):

**Expected behavior**
I would like to use all the GPU's available (in my case, 2)

**System (please complete the following information):**
 - Python version: 3.9.5
 - darts version 0.8.1

**Additional context**
The warning I got said this:
```
/home/<VMname>/.local/lib/python3.7/site-packages/torch/random.py:107: UserWarning: CUDA reports that you have 2 available devices, and you have used fork_rng without explicitly specifying which devices are being used. For safety, we
 initialize *every* CUDA device by default, which can be quite slow if you have a lot of GPUs.  If you know that you are only making use of a few CUDA devices, set the environment variable CUDA_VISIBLE_DEVICES or the 'devices' ke
yword argument of fork_rng with the set of devices you are actually using.  For example, if you are using CPU only, set CUDA_VISIBLE_DEVICES= or devices=[]; if you are using GPU 0 only, set CUDA_VISIBLE_DEVICES=0 or devices=[0]. 
 To initialize all devices and suppress this warning, set the 'devices' keyword argument to `range(torch.cuda.device_count())`.
  ).format(num_devices=num_devices, caller=_caller, devices_kw=_devices_kw))
```

Do I need to add a specific `**kwarg` or something when instantiating the models I use?

Thank you.

**Comment by GregoryCrysler** [comment]
@TahaSha I'm in exactly the same situation.  I'm grateful for the DARTS library, but is there any update on this?
