### ISSUE TITLE
[Question] - Install Darts without use of PIP

### ISSUE THREAD

**Issue by jnews5** [unit8co/darts#348]
Hello,

Bit a silly question but is there a guide on how to install Darts without the use of PIP? I don't see Darts able to be installed using conda install so a manual install instruction is appreciated.

**Comment by pennfranc** [comment]
Hey @jnews5, currently we only recommend installing Darts using pip. Adding the possibility to install Darts using conda is on our roadmap, but as you noticed this is currently not supported.

**Comment by hrzn** [comment]
Duplicate of https://github.com/unit8co/darts/issues/136

**Comment by tomasvanpottelbergh** [comment]
@jnews5 please see the update [here](https://github.com/unit8co/darts/issues/136#issuecomment-891703175). It would be great if you could test the packages and report any issues there.
