### ISSUE TITLE
[BUG] 'TimeSeries' object has no attribute 'pd_data_frame'

### ISSUE THREAD

**Issue by kusumy** [unit8co/darts#352]
**Describe the bug**
'TimeSeries' object has no attribute 'pd_data_frame'

**To Reproduce**
Tried to run 06-TCN-examples.ipynb, the error shows when executed this line:
df3 = EnergyDataset().load().pd_data_frame()

**Expected behavior**
Return DataFrame object

**System (please complete the following information):**
 - Python version: 3.7
 - darts version : 0.8.1

**Comment by pennfranc** [comment]
Ah yes, this is an error in the notebook. Try changing `df3 = EnergyDataset().load().pd_data_frame()` to `df3 = EnergyDataset().load().pd_dataframe()` (removing the underscore).  Also, you will have to change the subsequent line to `df3_day_avg = df3.groupby(df3.index.astype(str).str.split(" ").str[0]).mean().reset_index()`.
Sorry about this, we will fix this in the next release!

**Comment by hrzn** [comment]
Fixed in v0.9.0
