### ISSUE TITLE
Relax version number requirements for dependencies?

### ISSUE THREAD

**Issue by tcbegley** [unit8co/darts#360]
Hello,

Thanks for your work on this great library!

Would it be possible to relax the version number requirements when installing darts? Currently it seems that all dependencies are pinned to exact versions, but this means it can be a little tricky to integrate into existing workflows / environments.

**Comment by hrzn** [comment]
This will come in the next release.

**Comment by hrzn** [comment]
We have dropped the exact version numbers in the dependencies, starting in v0.9.1 that was released today => closing.
