### ISSUE TITLE
model.predict(...) with absolute forecast horizon/a datetime index

### ISSUE THREAD

**Issue by lumpi101** [unit8co/darts#365]
**Is your feature request related to a current problem? Please describe.**
The `.predict` method of any darts model expects an integer as first argument which is the forecast horizon in steps from the end of the train series. It would be great if it would also be possible to provide an "absolute" forecast horizon as a e.g. pandas DatetimeIndex (or some equivalent darts object), presupposed the time frequency of this absolute forecast horizon corresponds to that of the time series used for the fitting. With that, it would be possible to forecast any time span, with a starting point not fixed to the end of the time series used for fitting but also before or after it.

**Describe proposed solution**
A predict method which also accepts a time index
`def predict(self, n: Union[int, pd.DatetimeIndex], exog: Optional[TimeSeries] = None)` for the base class of the typical models (ARIMA etc.). Of course if darts provides some own datetime object, use this instead.
This datetime object must have the same frequency as the time series used for fitting, so internally, the absolute datetime index can converted into steps again (a start and end point in steps relative to the end of the fitting time series) if necessary.

**Additional context**
The sktime package has a similar functionality in its predict method: https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/base/_base.py#L126
And it has also a ForecastHorizon class for the purpose of "absolute forecast horizons": https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/base/_fh.py#L117

**Comment by pennfranc** [comment]
Hi @lumpi101, sorry for the late reply! You are right that our current API is limited to n steps after the end of the training series. However, given that it is quite easy to index the resulting forecast with any desired forecasting horizon time span, we don't think that it's necessary to change the interface of our predict method. At the same time, introducing it as an additional data type that is supported and gets converted internally would also do no harm. If you're up for it we would be happy to accept your contribution!

**Comment by hrzn** [comment]
Currently, you can do this fairly easily as follows. Assume you have an `index` which is either a `pandas.DatetimeIndex` (for datetime-indexed series) or `pandas.Int64Index` (for integer-indexed series). You should be able to do something something like this:
```
N = int((index.end_time() - my_series.end_time()) / my_series.freq)

my_model.predict(n=N)[index]
```

**Comment by lumpi101** [comment]
Hi @pennfranc @hrzn, thanks for your response. The actual problem is that in the project I am working on it may happen that we want a "forecast" which begins before `my_series.end_time()` and ends after `my_series.end_time()`. Of course there is the option to replace the part of the forecast which is before `my_series.end_time()` with the actual data of `my_series` but that's not the way we are going right now.

Thus, we would need some kind of "backcast" (a forecast with negative steps - and then combine it aftwerwards with the acutal forecast) or the requested feature with the absolute forecast horizon.

Unfortunately, I have no time to dig into the code and make contributions myself. But in the end, it's only a feature request which you can decline ;)

**Comment by hrzn** [comment]
Hi @lumpi101 . If you are using our global models (neural networks, or `RegressionModel`'s), then this is trivial. You can ask these models to predict the future of any series, so you could do as follows:
```
my_model.fit(my_series_or_list_of_series)
pred = my_model.predict(series=my_series[:my_timestam], n=N)
```

where `my_timestamp` is the time after which you want to forecast, and `N` is some long-enough horizon.

If you are not using global models, you can try using `my_model.fitted_values` (on Theta models), or check what is offered by statsmodels itself on statsmodels-based models using `my_model.model`.

Hope this helps

**Comment by lumpi101** [comment]
Hi @hrzn, sorry for the delay...
Thanks for the answer, this is indeed the feature I asked for :)

As you said, this works (only?) for global models (I tried the RegressionModel which worked) but for others not (e.g. AutoARIMA, which gives a type error `predict() got an unexpected keyword argument 'series'`). Is there a way to achieve this also for non-global models?

**Comment by hrzn** [comment]
Hi @lumpi101 no at the moment this is not possible out of the box unfortunately. We have it on our roadmap to add it when/where possible though.
