### ISSUE TITLE
Adding DeepTCN model

### ISSUE THREAD

**Issue by vpozdnyakov** [unit8co/darts#366]
This issue is created for my future PR.

It would be great to add the probabilistic DeepTCN model described in https://arxiv.org/pdf/1906.04397.pdf

Mention #288

**Comment by pennfranc** [comment]
Sounds great! Please take a look at the recent version of `RNNModel` in the develop branch to check out how we implemented our first probabilistic deep learning model. If possible, it would be cool if you could follow the same idea of overriding the `_compute_loss` and `_produce_predict_output` methods while utilizing the new `LikelihoodModel` class from `utils.likelihood_models`.

**Comment by hrzn** [comment]
I would also add that you can propose a change to our current `TCNModel` if you judge it can be reused.
(Don't forget to branch off `develop` and not `master`).
Thanks!

**Comment by pennfranc** [comment]
I merged merged your PR into develop, DeepTCN is going to be part of our next release :)
