### ISSUE TITLE
[BUG] Slowness with Timeseries functions v .9

### ISSUE THREAD

**Issue by rmenzie** [unit8co/darts#382]
after upgrading to version 0.9 all the functionality for timeseries has taken a drastic hit to speed. I have a timeseries with 2 hr increments over 3 years  and running datetime_attribute_timeseries has slowed 20+% from prior execution times. and just appending series together seems to has taken an equivalent hit.

**Comment by hrzn** [comment]
Hi @rmenzie the TimeSeries class has been completely rewritten (it is now probabilistic), so it is possible that some functions have taken a hit; however I wouldn't expect anything really significant. If you observe big discrepancies with before (eg 20% more or so), could you please share with us the code to replicate? We'll see if any optimisation can be done.

**Comment by hrzn** [comment]
Just a quick update: we have identified the likely cause of slowness with new TimeSeries and we are fixing it; we'll soon make a minor release to fix the issue.

**Comment by rmenzie** [comment]
> Just a quick update: we have identified the likely cause of slowness with new TimeSeries and we are fixing it; we'll soon make a minor release to fix the issue.

Thank you, sorry i did not get back to you with code. I was just experiencing slowness with TimeSeries and all the functions of the class. Glad u found the solution!

**Comment by hrzn** [comment]
This should now be solved by upgrading to v0.9.1 (`pip install -U darts`)
