### ISSUE TITLE
[BUG] TimeSeries creation does not accept time index with odd hours

### ISSUE THREAD

**Issue by rmenzie** [unit8co/darts#383]
when using a time range that has an offset of 1, i.e. (2-1-2020 1:00, 2-1-2020 3:00,  2-1-2020 5:00) the darts TimeSeries becomes (2-1-2020 2:00, 2-1-2020 4:00,  2-1-2020 6:00). Possible solution is adding an optional parameter for offset or forcing the index times to be equal to the times provided.

**Comment by hrzn** [comment]
@rmenzie could you please 
* Run `pip install -U darts`
* Try again
* Report if you still have the issue. If yes, please post a code snippet so we can try to reproduce.

**Comment by dennisbader** [comment]
Tested this and works with current darts version darts=0.11.0
Will regard this issue as closed due to inactivity.
