### ISSUE TITLE
[BUG] TimeSeries.plot() not showing plot

### ISSUE THREAD

**Issue by RychenerLorenz** [unit8co/darts#408]
**Describe the bug**
When creating a TimeSeries "ts" object and trying to plot it with ts.plot() no plot is showing up. I am running the code snippet below in a Jupyter Notebook.

**To Reproduce**
```
df = pd.DataFrame(data={'First': [0,1,2,3,4,4.5,4,3,2,1]}))
inds = [f'2021-01-{day}' for day in range(1, 11)]
df.index = pd.to_datetime(inds)
ts = TimeSeries.from_dataframe(df)
ts.plot()
```

**Expected behavior**
A plot showing the values of my component "First"

**System:**
 - Python version: [e.g. 3.7.5]
 - darts version [e.g. 0.9.1]

**Additional context**
I fixed the issue with a overwriting of the ```TimeSeries.plot()``` function and adding a ```plt.show()``` 
There is a big chance that I just use the functions wrong, since I am a very new user to the library.

**Comment by hrzn** [comment]
Hi @RychenerLorenz , I just copy-pasted your snippet and for me it works. I just had to remove the last `)` on the first line though.
![image](https://user-images.githubusercontent.com/4806678/126781230-cb726ad3-e1f4-400a-a450-94316d2cba22.png)

Could you confirm you still have the issue?

**Comment by RychenerLorenz** [comment]
I am pretty confidant that the additional bracket ")" is just me trying to edit code in the comment field.

I tried again and it does not display the plot in the jupyter notebook. Again it is very well possible that I just have some other issue over here. Can maybe somebody else confirm?

**Comment by hrzn** [comment]
This looks like an issue with your plotting backend (e.g. local matplotlib config). Feel free to re-open if you think it's really an issue with Darts for some reason (and if you do so, try to indicate what error message you get).

**Comment by RychenerLorenz** [comment]
Just a quick update: 

Reinstalling the ipykernel fixed the issue.

I will no walk away in embarrassment.

**Comment by hrzn** [comment]
No worries, glad you fixed it!

**Comment by mokandil** [comment]
I faced a similar issue with the plotting function. I found that adding `%matplotlib inline` would solve the problem.
