### ISSUE TITLE
Sliding Window Backtest

### ISSUE THREAD

**Issue by ajayganti3** [unit8co/darts#418]
In Backtest we have 2 strategies named Expanding window and Sliding Window. As per my understanding currently Darts support Expanding window backtest. If Sliding window backtest is implemented as a new feature, then it would be really helpful because expanding window backtest over a 100K timeseries would be too much of compute intensive when compared to Sliding window backtest. 
Sliding window visual representation is given in the below image.

![image](https://user-images.githubusercontent.com/29137349/127953830-b41341e7-1eff-437f-b31d-d9fa23653010.png)

**Comment by pennfranc** [comment]
Hi @ajayganti3, thanks for your suggestion, this addition is definitely on our radar! For now, to speed-up your backtesting, you can also consider setting `retrain=False` in case you are using `TorchForecastingModel` instances. You can also increase the `stride` parameter for some linear speed-ups. But a sliding window would definitely be nice, we agree. Please stay tuned!

**Comment by pabuta88** [comment]
Any news here regarding this feature? It would be really nice if you could add this.

**Comment by hrzn** [comment]
Closing as this is now implemented.
