### ISSUE TITLE
Access to the values within the plot (forecasting vals, upper and lower quantiles)

### ISSUE THREAD

**Issue by bilalmussaukfd** [unit8co/darts#432]
Is it possible to add a method within the prediction method to extract the forecast value, upper and lower quantiles that are presented on the plot or better yet have a method that is plot.values so that its easy to lift the data points out and use them elsewhere?

currently we have
prediction.plot(label='forecast', low_quantile=0.05, high_quantile=0.95)
 whch produces the plot.

I am thinking something like this
prediction.plot(label='forecast', low_quantile=0.05, high_quantile=0.95).values or .to_dataframe 

what do you think? Is this possible already? if so, how?

**Comment by pennfranc** [comment]
Hey @bilalmussaukfd, 
You can get the upper and lower quantile bounds using the `TimeSeries.quantile_timeseries()` method without having to produce a plot. You just have to specify the exact quantile you are interested in.
Let me know if this solves your problem!

**Comment by bilalmussaukfd** [comment]
Hi Francesco,
I tried the below

pred_vals = TimeSeries.quantile_timeseries(prediction, quantile=0.5)

However, I cant the values. Can you help?

B

**Comment by hrzn** [comment]
Hi @bilalmussaukfd ,
`TimeSeries.quantile_timeseries()` returns another `TimeSeries` object.
To obtain the values from a `TimeSeries` object, you can (for instance) use`my_series.pd_dataframe()` to get a Pandas Dataframe.
The documentation for `TimeSeries` is available here: https://unit8co.github.io/darts/generated_api/darts.timeseries.html

Hope this helps.

**Comment by bilalmussaukfd** [comment]
Hiya
That’s helpful thank you.
I have done the following

pred_vals = TimeSeries.quantile_timeseries(prediction, quantile=0.5).pd_dataframe()

If I wanted lower 5% and upper 95% would I have to use the quantiles_df instead?

Thanks,

**Comment by hrzn** [comment]
Yes, `TimeSeries.quantile_timeseries(prediction, quantile=0.5)` gives you one quantile.

If you want several quantiles, directly in a DataFrame, call `TimeSeries.quantiles_df()`. Copying from the docs (https://unit8co.github.io/darts/generated_api/darts.timeseries.html):
```
Returns a Pandas DataFrame containing the desired quantiles of each component (over the samples). Each of the series components will appear as a column in the DataFrame. The column will be named “<component>_X”, where “<component>” is the column name corresponding to this component, and “X” is the quantile value. The quantiles represent the marginal distributions of the components of this series.
```
