### ISSUE TITLE
Can't install on Windows P3.9 or ARM Ubuntu P3.8[BUG]

### ISSUE THREAD

**Issue by trurebel** [unit8co/darts#433]
I had a look in "closed" issues, could not find a configuration known to work for Windows, I guess most users would be on Linux but still my ARM Ubuntu would not work.

I took a hint from several Windows errors during installation, and pip installed wheel as well as "MS Build Tools" 2019, opened a "Developer Prompt", also a "Native tools x64" prompt, and pystan is the first culprit

`Collecting pystan<3.0.0.0,>=2.19.1.1
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\senti\\AppData\\Local\\Temp\\pip-install-8zdf6352\\pystan_034a78f15d1a43f983ba39348c63aae3\\setup.py'"'"'; __file__='"'"'C:\\Users\\senti\\AppData\\Local\\Temp\\pip-install-8zdf6352\\pystan_034a78f15d1a43f983ba39348c63aae3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\senti\AppData\Local\Temp\pip-pip-egg-info-kh2s29ds'
         cwd: C:\Users\senti\AppData\Local\Temp\pip-install-8zdf6352\pystan_034a78f15d1a43f983ba39348c63aae3\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\senti\AppData\Local\Temp\pip-install-8zdf6352\pystan_034a78f15d1a43f983ba39348c63aae3\setup.py", line 122, in <module>
        from Cython.Build.Inline import _get_build_extension
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/10/9f/dcecf31ac08842a675ec337a14439b37d75f6da42f034b1fd5eb90b10b84/pystan-2.19.1.1.tar.gz#sha256=fa8bad8dbc0da22bbe6f36af56c9abbfcf10f92df8ce627d59a36bd8d25eb038 (from https://pypi.org/simple/pystan/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

On ARM with build-essential installed the first error is 
` ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rq3vfnai/pmdarima/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rq3vfnai/pmdarima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kqwxh_1j
       cwd: /tmp/pip-install-rq3vfnai/pmdarima/
  Complete output (23 lines):
  Partial import of pmdarima during the build process.
  Requirements: ['joblib>=0.11', 'Cython>=0.29,!=0.29.18', 'numpy~=1.19.0', 'pandas>=0.19', 'scikit-learn>=0.22', 'scipy>=1.3.2', 'statsmodels>=0.11,!=0.12.0', 'urllib3', 'setuptools>=38.6.0,!=50.0.0']
  Adding extra setuptools args
  Traceback (most recent call last):
    File "/tmp/pip-install-rq3vfnai/pmdarima/setup.py", line 189, in check_package_status
      module = importlib.import_module(package)
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'numpy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rq3vfnai/pmdarima/setup.py", line 335, in <module>
      do_setup()
    File "/tmp/pip-install-rq3vfnai/pmdarima/setup.py", line 322, in do_setup
      check_package_status('numpy', '1.16')
    File "/tmp/pip-install-rq3vfnai/pmdarima/setup.py", line 209, in check_package_status
      raise ImportError("{} is not "
  ImportError: numpy is not installed.
  pmdarima requires numpy >= 1.16.

  ----------------------------------------
  ERROR: Failed building wheel for pmdarima
  Running setup.py clean for pmdarima
  Building wheel for pystan (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rq3vfnai/pystan/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rq3vfnai/pystan/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gm_mluzs
       cwd: /tmp/pip-install-rq3vfnai/pystan/
  Complete output (1 lines):
  Cython>=0.22 and NumPy are required.
  ----------------------------------------
  ERROR: Failed building wheel for pystan
  Running setup.py clean for pystan
  Building wheel for prophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rq3vfnai/prophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rq3vfnai/prophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lar649r5
       cwd: /tmp/pip-install-rq3vfnai/prophet/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/prophet
  creating build/lib/prophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rq3vfnai/prophet/setup.py", line 123, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-rq3vfnai/prophet/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-rq3vfnai/prophet/setup.py", line 36, in build_models
      from prophet.models import StanBackendEnum
    File "/tmp/pip-install-rq3vfnai/prophet/prophet/__init__.py", line 8, in <module>
      from prophet.forecaster import Prophet
    File "/tmp/pip-install-rq3vfnai/prophet/prophet/forecaster.py", line 14, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for prophet
  Running setup.py clean for prophet
`

That's a very mystifying message about numpy, possibly connected to some (other) package demanding a specific numpy version, not sure. Of course a couple of lines later I get the message about numpy version but from what I can see prophet should have succeeded with "my" numpy. Anyway, is all that version locking necessary really? It doesn't inspire much confidence for the future of Python! 

`Failed to build pmdarima pystan prophet
ERROR: pmdarima 1.8.2 has requirement numpy~=1.19.0, but you'll have numpy 1.21.1 which is incompatible.
ERROR: prophet 1.0.1 has requirement python-dateutil>=2.8.0, but you'll have python-dateutil 2.7.3 which is incompatible.
`

Anyway, Ubuntu and Windows inform me "Successfully installed darts", is this reliable or is it going to bomb out because of the previous errors? At this point I would settle for a "known working" configuration, something like : get Ubuntu X, run this and that, get a darts without errors. 

Thanks!

**Comment by hrzn** [comment]
Hi,
ARM is not supported at the moment. Nevertheless you could to try some lighter installs removing some of the potentially tricky dependencies:

* `pip install u8darts` (installs core only, without Prophet, pmdarima and PyTorch)
* `pip install 'u8darts[torch]'` (installs core + PyTorch)

Let us know if any of these works on ARM.
