### ISSUE TITLE
[BUG] RegressionEnsemble Model renaming of columns makes it break

### ISSUE THREAD

**Issue by rafmacalaba** [unit8co/darts#437]
**Describe the bug**
When creating a regression ensemble model and fitting it to a TimeSeries data, it breaks when calling the function in pandas

```
series = TimeSeries.from_dataframe(series.pd_dataframe().rename({target_column: "Target"}))
```

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.
just re-run the intro notebook https://github.com/unit8co/darts/blob/master/examples/01-darts-intro.ipynb

**Expected behavior**
the model with proceed with training (fit)

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.5.0]

**Additional context**
I don't know if this is the fix but, I tried to solve it by just explicitly adding `columns` in the code above

`series = TimeSeries.from_dataframe(series.pd_dataframe().rename(columns={target_column: "Target"}))`

let me know if you want to ask for further info

**Comment by rafmacalaba** [comment]
Update: the suggestion above really solves the problem 🗡️

**Comment by hrzn** [comment]
It seems that this was an issue with `pandas.DataFrame.rename()` => closing.
