### ISSUE TITLE
Using a custom model should be easier and more flexible for PyTorch-based models

### ISSUE THREAD

**Issue by novinsh** [unit8co/darts#445]
**The problem.**

Right now the documentation is a bit confusing when it comes to the `model` parameter. For instance, in RNNModel, for the model parameter, it says that "PyTorch module with the same specifications as darts.models.rnn_model.RNNModule".

- Does it mean class `_RNNModule`, because that is the one that inherits from PyTorch module. I think there is a typo and "_" is missing, so it should be `darts.models.rnn_model._RNNModule`
- Assuming that it was meant `_RNNModule` then it is not clear how the `input_dim` and `target_size` should be determined, especially that this is something dynamic in the library. The obvious is that it should be inferred outside of the library by the user but makes the library usage complicated.

**Proposed solution**

Users should be able to pass a custom PyTorch model architecture class and darts library calls it back and passing parameters such as input_dim and target_size. At the moment it seems that the package requires to receive the object and not the class for the custom module. As a reference [line 237](https://github.com/unit8co/darts/blob/9715c9f7273e44b6b6a8a37c6b5e5981dc6fe9ea/darts/models/rnn_model.py#L237) of RNN model could be checked. So in short, the library should have access to the class definition of a model similar to "_RNNModule" and the call on line 237 would become similar to line 230.

**Potential alternatives**
- The alternative is to have a possibility to inquire input_dim and target_size from the library but that makes everything complicated because these are not determined at initialization of the model.
- It could be the case that the documentation has been poor on this and there is a misunderstanding in the usage in which case the problem could be resolved by clarifying the usage.

**Additional context**

The [documentation for RNNModel](https://unit8co.github.io/darts/generated_api/darts.models.rnn_model.html) could be referred.

**Comment by pennfranc** [comment]
Hi @novinsh, thanks a lot for your comments!
First, you are right that we meant `darts.models.rnn_model._RNNModule` in the sentence that you mentioned. And I think you are also right in pointing out that Darts should pass the relevant parameters to the user-defined model. The proposed solution you mention sounds reasonable! We will try to address this ASAP.

**Comment by hrzn** [comment]
This has now been fixed in v0.11.0
