### ISSUE TITLE
Stride must be adjustable in gridsearch

### ISSUE THREAD

**Issue by novinsh** [unit8co/darts#446]
**Problem**
At the moment stride is set to 1 for the expanding window mode of the `gridsearch` and that is very limiting.

**Proposed solution**
Make it possible for the user to adjust the stride directly by passing a parameter to the `gridsearch` function.

**Potential alternatives**
In general, it would be ideal if any underlying mechanism e.g. backtesting could be run in the way that user wishes by passing a kwargs for the corresponding subprocesses of the gridsearch.

**Additional context**
[Forecasting_model.py Line 565](https://github.com/unit8co/darts/blob/9715c9f7273e44b6b6a8a37c6b5e5981dc6fe9ea/darts/models/forecasting_model.py#L565) (v 0.10.1)

**Comment by pennfranc** [comment]
Good catch! This should be quite an easy fix. We will update this soon. Thanks for reporting!

**Comment by hrzn** [comment]
This has now been released in v0.11.0
