### ISSUE TITLE
Fit params are skipped for internal model in RegressionModel

### ISSUE THREAD

**Issue by labdmitriy** [unit8co/darts#452]
Hi,

In RegressionModel we have the method fit(), which accepts **kwargs, and at the end _fit_model is called with 4 parameters:
https://github.com/unit8co/darts/blob/9715c9f7273e44b6b6a8a37c6b5e5981dc6fe9ea/darts/models/regression_model.py#L361

This method _fit_model() also can accept **kwargs, which is passed to internal regression model (like fit_params for sklearn-compatible model):
https://github.com/unit8co/darts/blob/9715c9f7273e44b6b6a8a37c6b5e5981dc6fe9ea/darts/models/regression_model.py#L291
https://github.com/unit8co/darts/blob/9715c9f7273e44b6b6a8a37c6b5e5981dc6fe9ea/darts/models/regression_model.py#L299

It seems that the initial intention was to call _fit_model() with **kwargs and pass all these params to the internal regression model, for example - to specify the list of categorical features for gradient boosting.

Is **kwargs skipped intentionally from the _fit_model call?

Thank you.

**Comment by pennfranc** [comment]
You're absolutely right, this is a mistake, we fixed it in #457. Thanks a lot for reporting!

**Comment by hrzn** [comment]
The fix has now been released in v0.11.0
