### ISSUE TITLE
Error using timeseries.shift(): "The time index of the provided DataArray is missing the freq attribute."

### ISSUE THREAD

**Issue by timraiswell** [unit8co/darts#454]
**Describe the bug**
Trying to shift a time series using `ts.shift(n=1)` but getting the error in the title: `The time index of the provided DataArray is missing the freq attribute.`

**To Reproduce**

```
from darts import TimeSeries

ts_df = pd.DataFrame({"week": ["2016-08-21","2016-08-28","2016-09-04","2016-09-11","2016-09-18"],
           "sales": ["10", "20", "10", "25", "15"]
           })

ts_df.week = pd.to_datetime(ts_df.week)
ts_df.set_index("week", inplace=True)
ts = TimeSeries.from_dataframe(ts_df, freq="W")
ts.shift(n=1)
```

**Expected behavior**
Expect the axis of the time series to shift by 1 period.

**System (please complete the following information):**
 - Python version: 3.8.11
 - darts version: 0.9.0

**Comment by pennfranc** [comment]
Could you try updating to the most recent version of darts? I ran your script with darts 0.10.1 and it seems to work fine. Let us know if this helps!

**Comment by timraiswell** [comment]
Ach, my apologies. I thought I had updated to the latest version. I was running 0.9.0.  Works fine now.
