### ISSUE TITLE
Extracting corresponding coefficients for regression_model, where lags are used on covariates.

### ISSUE THREAD

**Issue by ggerogiokas** [unit8co/darts#458]
**Is your feature request related to a current problem? Please describe.**

The coef_ of the regression_model has no labels so it's unclear which lag and covariate each coefficient is associated with.

**Describe proposed solution**

Pull out labels and associated lag per coefficient (not possible if multivariate time-series is not labelled).  Or make clear what the order of the covariates and their lags are.

**Comment by hrzn** [comment]
Linked to https://github.com/unit8co/darts/issues/192

**Comment by madtoinou** [comment]
Closed by #1679, the name of the features are accessible for the RegressionModel in the `_lagged_feature_names` attribute (`List[str]`).
