### ISSUE TITLE
[BUG] Accept linewidth and lw interchangeably as the input of the Timeseries plot

### ISSUE THREAD

**Issue by novinsh** [unit8co/darts#466]
**Description**
This is a minor issue, but at the moment it seems that the plot method of Timeseries is passing `lw` to the `matplotlib` library as the argument for the width of the line while an alternative argument is `linewidth` but if one passes this it would give an error as follows:

`
TypeError: Got both 'linewidth' and 'lw', which are aliases of one another
`

A full backtrace of the error could be found here: https://paste.ubuntu.com/p/Cs9wZF8Sz4/

**To Reproduce**
Just pass `linewidth` instead of `lw` to the plot method of Timeseries

**Expected behavior**
It shouldn't matter for the end-user whether to pass lw or linewidth

**System (please complete the following information):**
 - Python version: Python 3.8.5
 - darts version: '0.9.1'

**Comment by dennisbader** [comment]
Hi novinsh,

You are right, thanks! The bug will be fixed with #477.
