### ISSUE TITLE
[Feature request] More transformer-based model (i.e. Informer)

### ISSUE THREAD

**Issue by IncubatorShokuhou** [unit8co/darts#467]
I noticed that a `TransformerModel` is now in `darts`.

I am wondering if I can help add more transformer-based models (i.e. [Informer](https://github.com/zhouhaoyi/Informer2020)) to `darts`. The new transformer-based time-series-forecasting models often have a better performance compared with traditional models, and I believe it will help if `Informer` is added to `darts`.

BTW, I am also wondering if it is necessary to change the `TransformerModel` to an another alternative name (for example, `NativeTransformerModel`, to reduce misunderstanding because nowadays the name `transformer`  is more often used a structure or component of neural network than a `model`.

**Comment by hrzn** [comment]
Hi @IncubatorShokuhou we would be very glad to receive your contribution if you want to implement the Informer.
I didn't (yet) read the paper, but I would recommend you first identify if the model is a PastCovariatesTorchModel, FutureCovariatesTorchModel, DualCovariatesTorchModel or MixedCovariatesTorchModel, depending on the kinds of external data it can (or cannot) use in inputs.

Let us know if you need help or guidance :)

Concerning changing the name of `TransformerModel`, it is true that it's a bit of a misnomer, we'll think of maybe changing this in the future.

**Comment by IncubatorShokuhou** [comment]
@hrzn Thank you for your explaination. But I am still a little confused  about some details.
1. In my understanding, a `FutureCovariatesTorchModel` is for an autoregressive model (use the most recent predict as the input of the next prediction), and `PastCovariatesTorchModel` is for non-autoregressive model (all future predictions are made of the origin input data). Is my understanding correct?
2. I cannot see any reference of `DualCovariatesTorchModel` or `MixedCovariatesTorchModel` . Did I missed it, or have they not yet been referenced?

**Comment by hrzn** [comment]
Hi @IncubatorShokuhou 
1. That's not quite correct; `FutureCovariatesTorchModel` only specifies that the model consumes "future" covariates (i.e. values of covariates after the prediction time). It does not constrain the model to be used auto-regressively or not. In practice auto-regressive models are quite a natural way of consuming future values though. In Darts we have `RNNModel` which is a `DualCovariatesTorchModel` (meaning it consumers both future and past values of the covariates for producing predictions), which also happens to be auto-regressive, but we could imagine in the future another `DualCovariatesTorchModel` that would not be auto-regressive.
2. We don't yet have a `MixedCovariatesTorchModel` in Darts (although the super-class is ready :D), for `DualCovariatesTorchModel` you can look at `RNNModel`.

**Comment by hrzn** [comment]
@IncubatorShokuhou OK thank you for the answer. Let us know if you're able to progress. It would be an awesome addition to the library, and there's a possibility we'll try to implement it in the coming weeks (unless you're hopeful you'll complete it). Thanks :)

**Comment by IncubatorShokuhou** [comment]
@hrzn Well, I suppose that I may finish it as early as mid November (if I do not meet any difficulties in implement) . Would it be too late regarding of your schedule ?

**Comment by hrzn** [comment]
Closing this one as it is tracked here: https://github.com/unit8co/darts/issues/658
