### ISSUE TITLE
[BUG] Extra convolutions in TCN

### ISSUE THREAD

**Issue by vpozdnyakov** [unit8co/darts#470]
**Describe the bug**
There are extra 1x1 convolutions in the first and the last residual blocks in a case of the fixed number of channels, say input_dim=4, num_filters=4, output_dim=4. There are no need to add such convolutions because the residual summation can be directly performed to the output of the second convolution.

**To Reproduce**
```python
from numpy.random import randn
from darts.models import TCNModel
train_sample = (randn(10, 4), None, randn(10, 4))
model = TCNModel(input_chunk_length=10, output_chunk_length=9, num_layers=2, num_filters=4)
model._create_model(train_sample)
```
<img src='https://user-images.githubusercontent.com/12996098/132572236-13ca3d6b-72f2-4de1-a7af-b07d0284c0b9.png' width=500>

**Expected behavior**
There are no extra convolutions

**System**
 - darts version 0.11.0

**Comment by pennfranc** [comment]
Nice catch!
