### ISSUE TITLE
[BUG] Confusing example 02

### ISSUE THREAD

**Issue by danieleongari** [unit8co/darts#472]
Hi,
thank you very much for this nice open source package.

I would like to report what I think are confusing statements in the last part of example 02, **Training with Covariates**.

The section builds a `BlockRNNModel` which uses `past_covariates` because, as said in a previous section, this method does not support `future_covariates`, only `RNNModel` does.
However, the example goes on saying:

> Now, to train the model with covariates, it is as simple as providing the covariates (in form of a list matching the target series) as `future_covariates` argument to the `fit()` function. The argument is named `future_covariates` to remind us that the model can use future values of these covariates in order to make a prediction.

which is **totally out of context**, since we are not using `future_covariates`.
The final part stresses that we are using `past_covariates` which are anyhow very predictable for the future:

>  If these past covariates happen to also be known into the future, then these models are also able to produce forecasts for n > output_chunk_length (as shown above for BlockRNNModel) in an auto-regressive way.

Indeed, I tried to compare `BlockRNNModel` (`model_cov`) with `RNNModel` and `future_covariates` (`model_futcov`), and as you can see in the picture, the first does perform slightly better:

![image](https://user-images.githubusercontent.com/25899092/132823290-1a473352-eede-4d7a-aef6-fcf010f6d749.png)

I would kindly suggest to fix the statement in the cell "*Now, to train the model with covariates, ...*", or better to include an example for both `BlockRNNModel` and `RNNModel` to clarify the topic.

Thanks for your attention!

**Comment by hrzn** [comment]
Thanks for reporting @danieleongari , we'll fix this.
