### ISSUE TITLE
[BUG] Can't pickle <class 'darts.models.transformer_model.TransformerModel'>

### ISSUE THREAD

**Issue by jvalansi** [unit8co/darts#473]
**Describe the bug**
Trying to save a transformer model fails:

**To Reproduce**
Run:
my_model._save_model(False, 'models', 0)

**Expected behavior**
Model should be saves under the given path.

**System (please complete the following information):**
 - Python version: 3.6
 - darts version 0.6.1

**Additional context**

**Comment by pennfranc** [comment]
Hi @jvalansi, thanks for reporting. Could you also provide the error message you obtained? Also, it seems you are using an older version of Darts. Could you try to update to the most recent version and running the code again?

**Comment by hrzn** [comment]
I'm closing this one. The recommended way to save and load torch models is to call `my_model.save_model(path)` and the static method `MyModelClass.load_model(path)`.
