### ISSUE TITLE
[Question] Warm training a time series

### ISSUE THREAD

**Issue by dagap** [unit8co/darts#476]
Is there a way in Darts to copy the model state from a previously fitted model? 

I would like to do warm training i.e. fit a model and then use the model state to initialize another model for subsequent fitting. 

Something like:

```
old_model = ExponentialSmoothing()
old_model.fit(some_time_series)

....
new_model = ExponentialSmoothing()
new_model.init(old__model)
new_model.fit(some_new_time_series)
```

I wonder if I call `fit` multiple times, would it train from scratch or use the old state of the model? What is the right way to do this in darts?

**Comment by pennfranc** [comment]
Hi @dagap, what you are suggesting is possible with our neural net forecasting models (`TorchForecastingModel` instances), for example `RNNModel`. Check-out the documentation for the `fit` and `load_from_checkpoint` functions [here](https://unit8co.github.io/darts/generated_api/darts.models.rnn_model.html) to do this. `ExponentialSmoothing` does not support a functionality like this. Let me know if you need more information!
