### ISSUE TITLE
Add method to add "add_seasonality" method to Prophet model

### ISSUE THREAD

**Issue by ethantjones97** [unit8co/darts#491]
Darts does not currently incorporate the "add_seasonality" method in the Prophet model. For example, in the base Prophet model you can add a custom seasonality like the below. Is there some way to do this in Darts that I am missing? 
```
m = Prophet(weekly_seasonality=False)
m.add_seasonality(name='monthly', period=30.5, fourier_order=5)
forecast = m.fit(df).predict(future)
fig = m.plot_components(forecast)
```

I am new to contributing to open source code, but this doesn't seem that hard to add. 

An example of adding custom seasonalities can be found here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#specifying-custom-seasonalities

Let me know how I can support.

**Comment by dennisbader** [comment]
Hi @ethantjones97 and thanks for writing. We are currently working on expanding Prophet support and this is in our backlog.
For now, to use the full functionality of this feature, you would have to use the base Prophet model.

**Comment by ethantjones97** [comment]
Great - thank you!

**Comment by dennisbader** [comment]
@ethantjones97 adding seasonalities will be supported after merging #495 .
You can then add seasonalities either at model creation with the `add_seasonality` argument or pre-fit with `model.add_seasonality()`.
We added a small twist to Prophet's `add_seasonality` where you do not have to care anymore about frequencies and `period` conversion to number of days. Instead, you only have to say after how many timesteps your seasonal cycle repeats.

Some examples for this:
- If you have an hourly TimeSeries (frequency='H') and after every 48 hours the pattern repeats, 
you have to set `seasonal_periods=48`. 
- If you have a daily TimeSeries (frequency='D') and after every 7 days the pattern repeats, 
you have to set `seasonal_periods=7`.
