### ISSUE TITLE
[BUG] ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by JulianNyarko** [unit8co/darts#496]
**Describe the bug**
When using `val_series` with `RNNModel`, I am getting an error. When running the exact same code with `NBEATS`, it works. The error occurs unless my `val_series` has at least a lengh of `25`. I have tried training series of different length and different `input_chunk_length` and `output_chunk_length` without success. I at least think this is not expected.

**To Reproduce**
This produces an error:
```
model_RNN = RNNModel(input_chunk_length=10, output_chunk_length=1, n_epochs=250,
                          batch_size=1024, torch_device_str="cuda:0")
model_RNN.fit(series=ts_list_train, val_series=ts_list_val
                )
```
This does not produce an error:
```
model_NBEATS = NBEATSModel(input_chunk_length=10, output_chunk_length=1, n_epochs=250,
                          batch_size=1024, torch_device_str="cuda:0")
model_NBEATS.fit(series=ts_list_train, val_series=ts_list_val
                )
```

**Additional context**
Traceback below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_12641/796312022.py in <module>
      1 model_RNN = RNNModel(input_chunk_length=10, output_chunk_length=1, n_epochs=250,
      2                           batch_size=1024, torch_device_str="cuda:0")
----> 3 model_RNN.fit(series=ts_list_train, verbose=True, val_series=ts_list_val
      4                 )

~/darts/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             return decorated(self, *args, **kwargs)
     66     return decorator

~/darts/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py in fit(self, series, past_covariates, future_covariates, val_series, val_past_covariates, val_future_covariates, verbose, epochs)
    429         logger.info('Train dataset contains {} samples.'.format(len(train_dataset)))
    430 
--> 431         self.fit_from_dataset(train_dataset, val_dataset, verbose, epochs)
    432 
    433     @random_method

~/darts/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             return decorated(self, *args, **kwargs)
     66     return decorator

~/darts/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py in fit_from_dataset(self, train_dataset, val_dataset, verbose, epochs)
    465                  'The provided training time series dataset is too short for obtaining even one training point.',
    466                  logger)
--> 467         raise_if(val_dataset is not None and len(val_dataset) == 0,
    468                  'The provided validation time series dataset is too short for obtaining even one training point.',
    469                  logger)

~/darts/lib/python3.8/site-packages/darts/utils/data/shifted_dataset.py in __len__(self)
    212 
    213     def __len__(self):
--> 214         return len(self.ds_past)
    215 
    216     def __getitem__(self, idx) -> Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray], np.ndarray]:

ValueError: __len__() should return >= 0
```

**Comment by dennisbader** [comment]
Hi @JulianNyarko and thanks for writing.

`RNNModel` takes an optional parameter `training_length` which defaults to 24.

From our RNNModel docs (see [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.rnn_model.html#recurrent-neural-networks)):
"The length of both input (target and covariates) and output (target) time series used during training. Generally speaking, training_length should have a higher value than input_chunk_length because otherwise during training the RNN is never run for as many iterations as it will during training. For more information on this parameter, please see darts.utils.data.ShiftedDataset"

`ShiftedDataset` additionally shifts the data by +1 time step. So in total, the length of your `val_series` TimeSeries should be >= 25.

I agree that it might be a bit hard to identify what is causing this Error.
@hrzn, @pennfranc couldn't we check for correct input at the beginning of fit?

**Comment by hrzn** [comment]
Yes I agree, this error is too opaque; we could probably more explicitly check the data upfront and give a more informative error message.

**Comment by FarhangAmaji** [comment]
Iam having the same issue but on NBEATSModel!!

**Comment by dennisbader** [comment]
For NBEATSModel your target (and covariate) series must have at least `input_chunk_length + output_chunk_length` time steps. This also applies to your validation sequence.

**Comment by madhuyadu** [comment]
Hi team,
I see that there is lot of confusion when we are trying to give time series input for TARGET and FEATURES during .fit() and .predict() methods. And the guidelines changes for each type of DARTS model -- NBeats, TFT_model, TFT_model & so on.
I have also faced similar issues, looked for help but in vain. Hope I get a solution here for this. Below is my use case:
output_chunk_length= 3
 input_chunk_length = 12
model = NBEATSModel(
    input_chunk_length = input_chunk_length,
    output_chunk_length = output_chunk_length,
    generic_architecture=True,
    num_stacks=10,
    num_blocks=1,
    num_layers=4,
    layer_widths=512,
    n_epochs = n_epochs,
    nr_epochs_val_period = 1,
    batch_size = batch_size, force_reset = True, 
    model_name = model_name, save_checkpoints=True
)
model.fit(series = target_train, past_covariates = past_cov_train,
            val_series = target_test, val_past_covariates = past_cov_val,
            verbose=True)

predictions = model.predict(n = forecast_horizon, 
                             past_covariates = past_cov_train, verbose = True, n_jobs = -1)

When I run this code  I get error "ValueError: __len__() should return >= 0"
Now my question is what should be length of my train and test target and covariates?
Specifically, what should be length of the below time series types: 
target_train, target_test, past_cov_train, past_cov_val

Assuming my train data has 80 rows, test data has 20 rows.
Any help would be appreciated. Thanks.

**Comment by madhuyadu** [comment]
Hi ,
Thanks for the reply. I will give you some more details.
forecast_horizon = 3
output_chunk_length = 3
input_chunk_length = 12
n_epochs = 1
batch_size = 64
train period = 39 months
validation period =  3 months

model = NBEATSModel(
    input_chunk_length = input_chunk_length,
    output_chunk_length = output_chunk_length,
    generic_architecture=True,
    num_stacks=10,
    num_blocks=1,
    num_layers=4,
    layer_widths=512,
    n_epochs = n_epochs,
    nr_epochs_val_period = 1,
    batch_size = batch_size, force_reset = True, 
    model_name = model_name, save_checkpoints=True
)
model.fit(series = ts_trn_target, 
            past_covariates = ts_full_past_covariates,  #u can give TRAIN or FULL past covariates here 
            max_samples_per_ts = 20,                   
            val_series = ts_val_target, 
            val_past_covariates = ts_full_past_covariates , 
            verbose=True)
Here, tr_trn_target has length 39 timesteps per series
         ts_val_target has length 3 timesteps per series
         ts_trn_past_covariates has length 39 timesteps per series
         ts_val_past_covariates has length 3 timesteps per series
         ts_full_past_covariates has length 42 (39+3) timesteps per series

When I run this code, it throws error: "ValueError: The dataset contains some time series that are too short to contain `max(self.input_chunk_length, self.shift + self.output_chunk_length)` (0-th series)"

The covariate/target length that I have followed is exactly same as in this article : https://towardsdatascience.com/n-beats-unleashed-deep-forecasting-using-neural-basis-expansion-analysis-in-python-343dd6307010
But in my case its not working
-------------------------------------------------------------------------------------------------------------------------------
I am pretty clear now about how to declare these in .predict() method:
predictions = model.predict(n = forecast_horizon, 
                              series = ts_trn_target,                  
                              n_jobs = 1, 
                              past_covariates = ts_trn_past_covariates, 
                              verbose = True)
Here under series, I can give target series (past train values) & under past_covariates I can give either ts_trn_past_covariates or ts_full_past_covariates --- Hope I am right here

**Comment by hrzn** [comment]
The error message was improved in 0.21.0
