### ISSUE TITLE
[BUG] spelling mistake in time_series.py

### ISSUE THREAD

**Issue by mosheliv** [unit8co/darts#498]
**Describe the bug**
fill_missing_date->fill_missing_dates

as people are cut and paste from the error, this is a bit annoying

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

**Expected behavior**

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.5.0]

**Additional context**

**Comment by dennisbader** [comment]
Hi @mosheliv and thanks for reporting the spelling mistake.

Is #499 the only occurence where you saw this mistake?

**Comment by mosheliv** [comment]
Yes
