### ISSUE TITLE
[BUG] Some global forecasting models seem to produce the same values for all samples

### ISSUE THREAD

**Issue by rmitsch** [unit8co/darts#501]
**Describe the bug**
Some global forecasting models produce the same value for all samples when predicting with multiple samples.

**To Reproduce**
Run the example provided on the start page, but exchange `ExponentialSmoothing` for e.g. `TransformerModel`, `NBeatsModel`:
```python
import pandas as pd
from darts import TimeSeries

# Read a pandas DataFrame
df = pd.read_csv('AirPassengers.csv', delimiter=",")

# Create a TimeSeries, specifying the time and value columns
series = TimeSeries.from_dataframe(df, 'Month', '#Passengers')

# Set aside the last 36 months as a validation series
train, val = series[:-36], series[-36:]

from darts.models import ExponentialSmoothing, TransformerModel, NBEATSModel

# model = ExponentialSmoothing()
model = NBEATSModel(3, 3, n_epochs=1)
model.fit(train)
prediction = model.predict(len(val), num_samples=1000)
print(prediction)

import matplotlib.pyplot as plt

series.plot()
prediction.plot(label='forecast', low_quantile=0.05, high_quantile=0.95)
plt.legend()
plt.show()

```
The printed prediction shows that all produced predicted samples are of the same value.

**Expected behavior**
The produced samples should diverge in value.

**System (please complete the following information):**
 - Python version: 3.7.10
 - darts version: 0.12.0

**Additional context**
Not sure whether this is a bug or incorrect usage on my part, but couldn't find anything in the documentation w.r.t. this.

**Comment by dennisbader** [comment]
Hi @rmitsch and thanks for writing.

`NBEATSModel` and `TransformerModel` do not support true stochastic/probabilistic forecasting.
You can check which models support this in the [Darts docs](https://unit8co.github.io/darts/README.html#forecasting-models). 

You could pass a likelihood model to `TransformerModel` to sample a distribution around the predicted deterministic values. Note that this is independent of the model itself and just applies a distribution on the output.

**Comment by rmitsch** [comment]
Ah, thanks for pointing this out. Missed that one. Is there an example for the alternative using an likelihood model?

**Comment by dennisbader** [comment]
Yes, you can choose one of the likelihood models from [here](https://unit8co.github.io/darts/generated_api/darts.utils.likelihood_models.html#likelihood-models). 
The description of the likelihood models will tell you if the model is applicable for your use case (i.e. univariate/multivariate predictions, ...).

Let's say you choose the `GaussianLikelihood`:
```
from darts.utils.likelihood_models import GaussianLikelihood
model = TransformerModel(3, 3, n_epochs=1, likelihood=GaussianLikelihood())
```
You can adjust the likelihood also by changing it's default parameters.

The rest of your example should work fine to produce the samples.
