### ISSUE TITLE
Citing / Referencing darts?

### ISSUE THREAD

**Issue by williamgilpin** [unit8co/darts#502]
Thank you for this incredible library! It was incredibly helpful to me for running forecasting benchmarks. 
I would like to cite the library in my [preprint](https://openreview.net/forum?id=enYjtbjYJrf)
Do you have a recommended citation or reference that I should use to make sure that the library is properly credited? Right now I am using the following:

```
@misc{unit8co2020darts,
  author       = {{Unit8 Inc.}},
  title        = {Darts: Time Series Made Easy in Python},
  month        = {June},
  year         = {2020},
  publisher    = {GitHub},
  url          = {https://github.com/unit8co/darts}
}
```

Thanks again for this incredible package!

**Comment by hrzn** [comment]
Hi @williamgilpin , thanks a lot for the feedback, and for your attempt at citing us properly :)
We have actually written a short journal paper on Darts, which we'll soon upload to Arxiv as a pre-print. We'll thus have a proper way to cite it soon (in a matter of days, I expect). If you cannot wait let me know and I can try to already cook a bibtex entry.

**Comment by williamgilpin** [comment]
Hi @hrzn thank you very much---I was hoping to post a preprint next week as well. Please let me know once your preprint goes up and I will update it. Thanks again for this amazing package!

**Comment by hrzn** [comment]
Hi @williamgilpin , here's the link to our preprint: https://arxiv.org/abs/2110.03224

Could you reference this one?
Thanks!
