### ISSUE TITLE
How to remove target as an input variable?

### ISSUE THREAD

**Issue by ammad-visionrd** [unit8co/darts#509]
![image](https://user-images.githubusercontent.com/91890404/136999060-db7fa5b3-50f6-47b5-ac96-414d77460305.png)

Hello

1) I am working on a time series problem where I need to predict the m.s to the failure of a machine. My question is how to remove the past targets as an input to the time series model. I want my model to learn from past covariates only since I won't have past targets.
2) I have 100 events. Each event has 10 time series of features [f1,f2,f2...,f10]. How to combine all data and train. (Given that there is no relation between Event1, Event2,... i.e All events are independent.

**Comment by dennisbader** [comment]
@visionrd-ai do you need further help or can we close this issue?

**Comment by harrylojames** [comment]
@dennisbader Thank you for the example this was incredibly helpful! Is it possible to train a single model on multiple time series without past targets as input to the model?
