### ISSUE TITLE
Train a model, but don't save model artifacts

### ISSUE THREAD

**Issue by jonhilgart22** [unit8co/darts#510]
**Is your feature request related to a current problem? Please describe.**
A clear and concise description of what the problem is.

I'd like to train a Nbeats and TCN model but not save the model artifacts. I'm running this code on AWS Lambda which has size restrictions for these model files.

**Describe proposed solution**
A clear and concise description of what the library should provide to solve missing functionality.

Can we pass in a param here https://github.com/unit8co/darts/blob/484a184a97be37e64ed62f6fa6fad2bdef898adf/darts/models/forecasting/torch_forecasting_model.py#L859 indicating whether save=True or save=False ?

**Describe potential alternatives**
A clear and concise description of any alternative solutions or existing features that might solve it.

**Additional context**

**Comment by dennisbader** [comment]
Hi @jonhilgart22 and thanks for pointing this out.

Currently, the models are saved automatically without the option to bypass it.

We added this feature to our to-do list!

**Comment by hrzn** [comment]
Since v0.13.0, checkpoints are not saved by default anymore (you can still save them by passing `save_checkpoints=True` to the model).
