### ISSUE TITLE
[BUG] u8darts[pmdarima] package also has torch dependency

### ISSUE THREAD

**Issue by katharinarafetseder** [unit8co/darts#517]
**To Reproduce**
Install darts via `pip install 'u8darts[pmdarima]'`

`from darts.models import NaiveSeasonal`
returns: `ModuleNotFoundError: No module named 'torch'`

**Expected behavior**
Lightweight darts installation without torch models should work without torch.

**System (please complete the following information):**
 - Python version 3.9
 - darts version 0.12.0

**Comment by hrzn** [comment]
Thanks for reporting! We'll fix. https://github.com/unit8co/darts/pull/539

**Comment by hrzn** [comment]
Fixed in v0.13.1.
