### ISSUE TITLE
How to show Probability with forecasted value ?

### ISSUE THREAD

**Issue by karndeepsingh** [unit8co/darts#528]
Hi,
I want to get probability of the forecasted value for “n” time step. Please help me to understand how this can achieved while forecasting and how these confidence band can be shown up with forecasted value on plot. 

Please provide some suggestions on this.

thanks

**Comment by dennisbader** [comment]
Hi @karndeepsingh.

You can find which of Darts' models support probabilistic forecasting here:
https://github.com/unit8co/darts#forecasting-models

First, let's say you want to predict `n_prediction_steps` into the future and want to sample `n_probabilistic_samples` from the probabilistic distribution at each predicted time step.

Depending on the model, there is a difference on how you can do probabilistic forecasting:
- all models in the table above `RNNModel` (without `RNNModel`) that support probabilistic forecasting:
```
model = MyModel(...)
model.fit(...)
pred = model.predict(n=n_prediction_steps, num_samples=n_probabilistic_samples)
```

- all models in the table below and including `RNNModel` that support probabilistic forecasting:
They use likelihood models for probabilistic forecasting. You can choose one of the likelihood models from [here](https://unit8co.github.io/darts/generated_api/darts.utils.likelihood_models.html#likelihood-models).
The description of the likelihood models will tell you if the model is applicable for your use case (i.e. univariate/multivariate predictions, ...).

Let's say you choose the GaussianLikelihood:

```
from darts.utils.likelihood_models import GaussianLikelihood

model = MyModel(..., likelihood=GaussianLikelihood())
model.fit(...)
pred = model.predict(n=n_prediction_steps, num_samples=n_probabilistic_samples)
```

The probabilistic samples are saved in your `pred` TimeSeries in dimension `sample`

### Plotting
[This example](https://unit8co.github.io/darts/examples/01-darts-intro.html#Probabilistic-Forecasts) shows you how you can plot specific intervals:
