### ISSUE TITLE
What is the difference between Backtest and Historical_forecasting method?

### ISSUE THREAD

**Issue by karndeepsingh** [unit8co/darts#529]
Hi,
I was going through the documentation of Darts. I found two methods backtest and historical_forecasting. Please, help me to understand the difference between these two methods.

thanks

**Comment by dennisbader** [comment]
Hi @karndeepsingh and thanks for writing.

From Darts' documentation on [`historical_forecasts()`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.transformer_model.html#darts.models.forecasting.transformer_model.TransformerModel.historical_forecasts):
- It computes the historical forecasts the model would have produced with an expanding training window and (by default) returns a time series created from the last point of each of these individual forecasts. (...)
- Let's say you started using your model 2 years ago. Then the model will only have training data up to that date from 2 years ago. Over time, new data points are added to your training set. `historical_forecasts()` will give you the forecasts it would have produced from 2 years ago until "today" with an expanding training window (length).

From Darts' documentation on [`backtest()`](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.transformer_model.html#darts.models.forecasting.transformer_model.TransformerModel.backtest):
- Computes error scores between the historical forecasts (...) and the actual values.

**Comment by karndeepsingh** [comment]
@dennisbader  Awesome! Thanks for such a wonderful answer.
