### ISSUE TITLE
How to Inverse the differencing of timeseries ?

### ISSUE THREAD

**Issue by karndeepsingh** [unit8co/darts#530]
Hello,
I have been using Darts for time series analysis and performing a few analyses on time series, I found that differencing the time series would detrend the time series and would help in better modeling. So, for differencing I used the .diff() method on time series but was unable to inverse the difference for my prediction.
Please, help me to understand how I can inverse the differencing on time-series data.

Thanks.

**Comment by hrzn** [comment]
At the moment there's no out-of-the-box to reverse-diff a series; you'd have to use something like `cumsum()` with Numpy (you can get Numpy array of values of a univariate series calling `series.values()` or all data of a multivariate series calling `all_values()`).

**Comment by karndeepsingh** [comment]
Hi @hrzn,
Please, share some code showing differencing and reversing the difference on a Darts Time series .

Thanks

**Comment by brunnedu** [comment]
Hi @karndeepsingh,

I hope this is helpful:

```import numpy as np
from matplotlib import pyplot as plt

from darts import TimeSeries
from darts.datasets import AirPassengersDataset

# loading example timeseries
ts = AirPassengersDataset().load()

values = ts.values()

# differencing timeseries
ts_diff = ts.diff()

values_diff = ts_diff.values()

# OPTIONAL: because the value of the first timestep is lost during differencing we can insert it back in to get the correct y-offset if we know it
# values_diff = np.insert(values_diff, 0, values[0])

# use np.cumsum to calculate the cumulative sum of the differenced values (inverting differencing)
values_undiff = np.cumsum(values_diff)

# build the reconstructed timeseries from the values_undiff and the time_index of the differenced series
ts_undiff = TimeSeries.from_times_and_values(ts_diff.time_index, values_undiff)

# OPTIONAL: build the reconstructed timeseries from the values_undiff and the original time_index
# ts_undiff = TimeSeries.from_times_and_values(ts.time_index, values_undiff)

# plot both series to check for equivalence
ts_undiff.plot()
ts.plot()
plt.show()

**Comment by karndeepsingh** [comment]
I ran the above code. Still, I can see the shift in the data. How would I make them overlap each other because that would make them equal to the original series.

![image](https://user-images.githubusercontent.com/49562460/139837883-dbe34022-9cc1-474a-a787-d4c72e44c6e4.png)

**Comment by brunnedu** [comment]
Hi @karndeepsingh,
Please read through my code snippet once more. This is what I was referring to in my `# OPTIONAL` comments. But in order to reconstruct the original time series, you need to know the value of the first time step, as this information is thrown away when differencing.
