### ISSUE TITLE
Unable to obtain the MAPE value

### ISSUE THREAD

**Issue by vageeshmaiya** [unit8co/darts#541]
**Describe the issue:**
I am trying to fit the dataset attached below but i am unable to obtain the mape value while plotting.
**[test_20values.csv](https://github.com/unit8co/darts/files/7496945/test_20values.csv)**

I am getting the following error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14768/3134006011.py in <module>
      7     plt.legend();
      8 
----> 9 eval_model(my_model)

~\AppData\Local\Temp/ipykernel_14768/3134006011.py in eval_model(model)
      4     series_transformed.plot(label='actual')
      5     pred_series.plot(label='forecast')
----> 6     plt.title('MAPE: {:.2f}%'.format(mape(pred_series, val_transformed)))
      7     plt.legend();
      8 

D:\anaconda\envs\time_series\lib\site-packages\darts\metrics\metrics.py in wrapper_multi_ts_support(*args, **kwargs)
     67                                         total=len(actual_series))
     68 
---> 69         value_list = _parallel_apply(iterator=iterator,
     70                                      fn=func,
     71                                      n_jobs=n_jobs,

D:\anaconda\envs\time_series\lib\site-packages\darts\utils\utils.py in _parallel_apply(iterator, fn, n_jobs, fn_args, fn_kwargs)
    234     """
    235 
--> 236     returned_data = Parallel(n_jobs=n_jobs)(delayed(fn)(*sample, *fn_args, **fn_kwargs)
    237                                             for sample in iterator)
    238     return returned_data

D:\anaconda\envs\time_series\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1041             # remaining jobs.
   1042             self._iterating = False
-> 1043             if self.dispatch_one_batch(iterator):
   1044                 self._iterating = self._original_iterator is not None
   1045 

D:\anaconda\envs\time_series\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    859                 return False
    860             else:
--> 861                 self._dispatch(tasks)
    862                 return True
    863 

D:\anaconda\envs\time_series\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    777         with self._lock:
    778             job_idx = len(self._jobs)
--> 779             job = self._backend.apply_async(batch, callback=cb)
    780             # A job can complete so quickly than its callback is
    781             # called before we get here, causing self._jobs to

D:\anaconda\envs\time_series\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    206     def apply_async(self, func, callback=None):
    207         """Schedule a func to be run"""
--> 208         result = ImmediateResult(func)
    209         if callback:
    210             callback(result)

D:\anaconda\envs\time_series\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    570         # Don't delay the application, to avoid keeping the input
    571         # arguments in memory
--> 572         self.results = batch()
    573 
    574     def get(self):

D:\anaconda\envs\time_series\lib\site-packages\joblib\parallel.py in __call__(self)
    260         # change the default number of processes to -1
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
--> 262             return [func(*args, **kwargs)
    263                     for func, args, kwargs in self.items]
    264 

D:\anaconda\envs\time_series\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    260         # change the default number of processes to -1
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
--> 262             return [func(*args, **kwargs)
    263                     for func, args, kwargs in self.items]
    264 

D:\anaconda\envs\time_series\lib\site-packages\darts\metrics\metrics.py in wrapper_multivariate_support(*args, **kwargs)
    106         value_list = []
    107         for i in range(actual_series.width):
--> 108             value_list.append(func(actual_series.univariate_component(i), pred_series.univariate_component(i),
    109                               *args[2:], **kwargs))  # [2:] since we already know the first two arguments are the series
    110         if 'reduction' in kwargs:

D:\anaconda\envs\time_series\lib\site-packages\darts\metrics\metrics.py in mape(actual_series, pred_series, intersect, reduction, inter_reduction, n_jobs, verbose)
    514     """
    515 
--> 516     y_true, y_hat = _get_values_or_raise(actual_series, pred_series, intersect, remove_nan_union=True)
    517     raise_if_not((y_true != 0).all(), 'The actual series must be strictly positive to compute the MAPE.', logger)
    518     return 100. * np.mean(np.abs((y_true - y_hat) / y_true))

D:\anaconda\envs\time_series\lib\site-packages\darts\metrics\metrics.py in _get_values_or_raise(series_a, series_b, intersect, stochastic_quantile, remove_nan_union)
    163     raise_if_not(isinstance(intersect, bool), "The intersect parameter must be a bool")
    164 
--> 165     series_a_common = series_a.slice_intersect(series_b) if intersect else series_a
    166     series_b_common = series_b.slice_intersect(series_a) if intersect else series_b
    167 

D:\anaconda\envs\time_series\lib\site-packages\darts\timeseries.py in slice_intersect(self, other)
   1217         """
   1218         time_index = self.time_index.intersection(other.time_index)
-> 1219         return self[time_index]
   1220 
   1221     def strip(self) -> 'TimeSeries':

D:\anaconda\envs\time_series\lib\site-packages\darts\timeseries.py in __getitem__(self, key)
   2216             _set_freq_in_xa(xa_)
   2217 
-> 2218             return TimeSeries(xa_)
   2219         elif isinstance(key, pd.Int64Index):
   2220             _check_range()

D:\anaconda\envs\time_series\lib\site-packages\darts\timeseries.py in __init__(self, xa)
     37                                                    'TimeSeries.from_xarray(), TimeSeries.from_values()'
     38                                                    'TimeSeries.from_times_and_values(), etc...).', logger)
---> 39         raise_if_not(xa.size > 0, 'The time series array must not be empty.', logger)
     40         raise_if_not(len(xa.shape) == 3, 'TimeSeries require DataArray of dimensionality 3 ({}).'.format(DIMS), logger)
     41 

D:\anaconda\envs\time_series\lib\site-packages\darts\logging.py in raise_if_not(condition, message, logger)
     52     if (not condition):
     53         logger.error("ValueError: " + message)
---> 54         raise ValueError(message)
     55 
     56 

ValueError: The time series array must not be empty.`

**To Reproduce**
Here is a part code that I used
`ser = TimeSeries.from_dataframe(df=df,time_col="Date_Time")

series = ser
train, val = series.split_after(pd.Timestamp('1/28/2018  8:26:10 AM')) 
transformer = Scaler()
train_transformed = transformer.fit_transform(series)
val_transformed = transformer.transform(val)
series_transformed = transformer.transform(series)
year_series = datetime_attribute_timeseries(pd.date_range(start=series.start_time(), freq=series.freq_str, periods=1000),
                                             attribute='year', one_hot=False)
year_series = Scaler().fit_transform(year_series)
month_series = datetime_attribute_timeseries(year_series, attribute='month', one_hot=True)
covariates = year_series.stack(month_series)
cov_train, cov_val = covariates.split_after(pd.Timestamp('1/28/2018  8:26:10 AM'))

my_model = RNNModel(
    model='LSTM',
    hidden_dim=20,
    dropout=0,
    batch_size=16,
    n_epochs=10,
    optimizer_kwargs={'lr': 1e-3}, 
    model_name='Air_RNN',
    log_tensorboard=True,
    random_state=42,
    training_length=20,
    input_chunk_length=14,
    force_reset=True
)

my_model.fit(train_transformed, 
             verbose=True)
def eval_model(model):
    pred_series = model.predict(n=210)
    plt.figure(figsize=(8,5))
    series_transformed.plot(label='actual')
    pred_series.plot(label='forecast')
    plt.title('MAPE: {:.2f}%'.format(mape(pred_series, val_transformed)))
    plt.legend();
    
eval_model(my_model)`

**Expected behaviour**
To obtain the mape value while plotting

**System (please complete the following information):**
Python version: 3.8.12
Darts version:  I'm not sure but I used `pip install darts`

**Comment by dennisbader** [comment]
Hi @vageeshmaiya,

The problem is this line in your code:

```
train_transformed = transformer.fit_transform(series)
```
Here, instead of transforming the `train` series, you use all data from `series`.

This means your validation set ended before the start of your prediction and the `mape()` cannot find any common dates between `pred_series` and `val_transformed`.

With this it should work:
```
train_transformed = transformer.fit_transform(train)
```

**Comment by vageeshmaiya** [comment]
Thank you @dennisbader 
I have made the necessary changes to the program and have gotten the prediction. But the MAPE value is too high.
Could you suggest any further changes I have to make in the program to reduce the error.

**Comment by dennisbader** [comment]
Try following the example notebook on RNNModel from [here](https://unit8co.github.io/darts/examples/05-RNN-examples.html).

What you want to do is:
- check the frequency of your data with `series.freq`: in your case it's `2 * min` so one time-stamp every 2 minutes.
- check if your data has seasonal patterns for example with `check_seasonality()` and `plot_acf()`.
  - if I remember correctly, your data repeats every 81 time steps
  - you can try to generate a time series that captures this seasonality and supply it as a future covariate to the model.  This can greatly improve predictions
- adjust the model's `input_chunk_length` to capture at least one season. As a start, try setting it to `162` (two seasons)
- set the `training_length` for example to include `input_chunk_length` + another season = 243 timesteps.
- raise the number of epochs. Try `n_epochs=300`
- consider using another metric than `mape` as your validation set contains values almost equal to `0` making the `mape` a bad choice.
  - for example the Mean Absolute Error: `mae(val_transformed, pred_series, train_transformed)` 

with the values from above you can get a good start (see image below).

![image](https://user-images.githubusercontent.com/84317528/141473211-31f4e495-7bc6-4704-8c36-9b93d10baafc.png)
