### ISSUE TITLE
modelling trend in lightgbm model

### ISSUE THREAD

**Issue by sharabhshukla** [unit8co/darts#551]
How can I model trend in a lightgbm model ? 

Are there some utilities in darts package that can make my job easier. Any hints and suggestions are appreciated 

I was thinking on training a small sklearn linear model thats sits besides the lightgbm model

**Comment by hrzn** [comment]
Hi, I see mostly two ways this could happen:
* If you put sufficient lags into your LightGBMModel, it should be able to pick up some trend (as visibile via those lags) by itself.
* If you have knowledge about the trend (e.g. you know it's linear, or quadratic), you can build a `future_covariates` series. You can use `darts.utils.timeseries_generation` module for this.

Hope this helps.

**Comment by sharabhshukla** [comment]
I like #2, thanks for the reply. I will try #2,  for now I will close the issue now
