### ISSUE TITLE
NaN in the prediction array

### ISSUE THREAD

**Issue by pabuta88** [unit8co/darts#558]
I have two time series and when training one model for each of them, the models run through and I get predictions. However, as soon as I try to train on both series (following exactly the traffic/milk example), the predictions are always nan, independent of what model I use. Both weekly series cover the period 2017-03-01 until 2021-11-01 and there are no missing values. How should I interpret this result?

**Comment by hrzn** [comment]
Hi, could you please send a code snippet so we can reproduce the issue? Thanks.

**Comment by pabuta88** [comment]
Unfortunately, I cannot share the data. However, there are two pandas datasets (series1_pd and series2_pd) including weekly data. Then I do the following steps:

`
import pandas as pd
from darts import TimeSeries
from sklearn.preprocessing import MinMaxScaler
from darts.models import NBEATSModel
`

`min_max_scaler = MinMaxScaler()`

`series1 = TimeSeries.from_dataframe(
    series1_pd
    .assign(quantity_sold=lambda x: min_max_scaler.fit_transform(x[['quantity']]))
    , time_col = 'date'
    , value_cols='quantity', 
    fill_missing_dates=True, freq='W-TUE'
    )`

`series2 = TimeSeries.from_dataframe(
    series2_pd
    .assign(quantity_sold=lambda x: min_max_scaler.fit_transform(x[['quantity']]))
    , time_col = 'date'
    , value_cols='quantity', 
    fill_missing_dates=True, freq='W-TUE'
    )`

`
series1_train, series1_val = series1.split_after(pd.Timestamp('2021-01-01'))
series2_train, series2_val = series2.split_after(pd.Timestamp('2021-01-01'))
`

`model_air = NBEATSModel(input_chunk_length=24, output_chunk_length=12, n_epochs=100, random_state=0)
model_air.fit([series1_train, series2_train], verbose=True)
pred = model_air.predict(n=36)
`

**Comment by dennisbader** [comment]
Hi @pabuta88.

When training on multiple time series, you must specify the `series` you want to forecast in `model.predict()`. For example to make predictions after `series1_train`:

```
pred = model.predict(n=36, series=series1_train)
```

Usually, you should get an error when trying to predict without specifying `series`:
```
ValueError: Input series has to be provided after fitting on multiple series.
```
Which darts version are you using?

**Comment by pabuta88** [comment]
Hi @dennisbader 

Thank you very much for taking the time. Unfortunately, specifying the series does not change the outcome. Currently, I am using the version 0.13.1.

**Comment by dennisbader** [comment]
Ahh okay, then it probably comes from missing values in your `series1` and/or `series2`.

Can you check:
```
import numpy as np
print(np.isnan(series1.values()).sum())
print(np.isnan(series2.values()).sum())
```

If you have any missing values, try filling them for example with Darts' `fill_missing_values()` (see docs [here](https://unit8co.github.io/darts/generated_api/darts.utils.missing_values.html#darts.utils.missing_values.fill_missing_values))

For exmaple:
```
series1 = fill_missing_values(series1, 'auto')
```

**Comment by pabuta88** [comment]
That's exactly it! Thank you so much for your help :-)

**Comment by dennisbader** [comment]
You're welcome :)
