### ISSUE TITLE
[BUG] ERROR when running 14-TFT-examples  notebook

### ISSUE THREAD

**Issue by edwardhamilton** [unit8co/darts#559]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-653f3ea560ff> in <module>()
     17                     likelihood=QuantileRegression(quantiles=quantiles),  # QuantileRegression is set per default
     18                     # loss_fn=MSELoss(),
---> 19                     random_state=42)

3 frames
/usr/local/lib/python3.7/dist-packages/darts/models/forecasting/torch_forecasting_model.py in __init__(self, likelihood, **kwargs)
   1031             The likelihood model to be used for probabilistic forecasts.
   1032         """
-> 1033         super().__init__(**kwargs)
   1034         self.likelihood = likelihood
   1035 

TypeError: __init__() got an unexpected keyword argument 'add_relative_time_index'

**Comment by dennisbader** [comment]
Hi @edwardhamilton 
Did you install darts from the github repo or using pip/conda?


We updated `TFTModel` for darts version 13.2.0 which has not yet been released.
Could you try `add_relative_index` instead?
