### ISSUE TITLE
ValueError: The dataset contains some covariates that do not have a sufficient time span to obtain a slice of length input_chunk_length matching the target

### ISSUE THREAD

**Issue by varunlakshmanan** [unit8co/darts#560]
I'm using the BlockRNNModel and passing in data for the `series`, `past_covariates`, `val_series`, and `val_past_covariates` parameters when calling `fit()`. When calling `predict()` with data passed in for `past_covariates` and `n = 1`, I'm getting this error:

`ValueError: The dataset contains some covariates that do not have a sufficient time span to obtain a slice of length input_chunk_length matching the target
`

This is my code: 

```
model = BlockRNNModel(model='LSTM', input_chunk_length=1, output_chunk_length=1)
model.fit(series=train_y, past_covariates=train_x, val_series=val_y, val_past_covariates=val_x, verbose=True)
y_predictions = model.predict(n=1, past_covariates=test_x)
```

How can I fix this error? The length of `train_x` is 21, the length of `val_x` is 6, and the length of `test_x` is 2, so I'm not sure what the problem is because they all should have a sufficient time span to get a slice of length 1.

**Comment by dennisbader** [comment]
Hi @varunlakshmanan, try replacing `test_x` with `train_x` in the last line:
```
y_predictions = model.predict(n=1, past_covariates=train_x)
```

Some additional info:
Your `train_x` must contain the same time steps as `train_y` (it can also contain more than that). The same applies to `val_x` and `val_y`.

You can use the same `train_x` for `fit()` and `predict()` if it contains all required time steps.

Now for your prediction with `n=1`, the model wants covariates that lie in the past (your `train_x`). If you wanted to predict for `n>1` you will need to supply additional values of past covariates that cover these future time stamps.
