### ISSUE TITLE
Don't force to install PyTorch by default

### ISSUE THREAD

**Issue by JavierLopezT** [unit8co/darts#562]
Hello. We are using darts without deep learning features and hence we don't use at all PyTorch. However, it still has to be downloaded every time we recreate a docker container or virtual environment with darts. It takes more than 5 minutes because the library has around 800 mb of size. 

It would be nice to have it optionally installed. For instance, it could be disabled automatically and added as an extra, so that if you want to install it, you would type:

`pip install darts[pytorch]`

or something like that.

**Comment by hrzn** [comment]
Hi, such installs options are already available, as explained in the [installation instructions](https://github.com/unit8co/darts#from-pypi).

Install core only (without neural networks, Prophet or AutoARIMA): pip install u8darts
Install core + neural networks (PyTorch): pip install "u8darts[torch]"
Install core + Facebook Prophet: pip install "u8darts[prophet]"
Install core + AutoARIMA: pip install "u8darts[pmdarima]"

**Comment by JavierLopezT** [comment]
🤦 

I am sorry. Thanks for answering
