### ISSUE TITLE
Train on GPU, but load_model on CPU

### ISSUE THREAD

**Issue by kpiaskowski** [unit8co/darts#570]
We need to add support to directly map model to a specific torch device in TorchForecastingModel.load_model()

Original issue text:

All the following relates to NBEATS, but most probably also to other DL models.

Would it be possible to train a model on GPU (and consequently save all model checkpoints with information about CUDA usage), but then load the model on CPU? In other words, it would be nice to have a load_model() method that mimics torch.load(map_location=device), where we can explicitly specify device for loaded model. I know that I could theoretically dig down to torch.load() in darts, since it's a wrapper around pytorch (at least in case of NBEATS), but it'd be nice to have this at the library level.

**Comment by dennisbader** [comment]
Hi @kpiaskowski and thanks for writing. 

Our current `load_model()` method doesn't support direct mapping to another torch device device. It loads the model in the same state as it was saved.

This is a good point and I will add it to our back log.

**Comment by hrzn** [comment]
+1, good point

**Comment by YannickLehr** [comment]
Any news here? i tried to implement it by myself, however haven't found the time yet to take a serious look at it.

So far I just tried loading the model using the torch load function with the mapL_location parameter set to cpu and updating the trainer_params of the loaded model.

```
device = torch.device('cpu')

with open("model.pth.tar", "rb") as fin:
    model = torch.load(fin, map_location=device)

params = model.trainer_params
params.update({'accelerator': 'cpu','auto_select_gpus': False})
model.trainer_params = test_model.trainer_params
```

Unfortunately it does not work as soon as i try to predict it. For some reason it leads to an recursion error.

**Comment by nikobenho** [comment]
This is how I've done it thus far (Darts 0.21.00):

```
# load the model state that performed best on validation set
model_nhits = NHiTSModel.load_from_checkpoint(
    model_name='model',
    best=True,
)

model_nhits.trainer_params['accelerator'] = 'cpu'
del model_nhits.trainer_params['gpus']
```

After that I can go ahead and do predictions without the GPU the model was trained on.

**Comment by hrzn** [comment]
Thanks @nikobenho. I think we should keep this task on our backlog and eventually offer a way to make this switch slightly more user friendly.

**Comment by hrzn** [comment]
This should now work better starting in v0.23.0. See e.g. `load()` method documentation to map a GPU-trained model to CPU: https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html#darts.models.forecasting.nbeats.NBEATSModel.load

**Comment by lk1983823** [comment]
> del model_nhits.trainer_params['gpus']

for version 0.21.0, it shoud be 

```
model.trainer_params['accelerator'] = 'cpu' 
del model.trainer_params['devices']
```

**Comment by dennisbader** [comment]
@lk1983823, this should work:

```

from darts.models import RNNModel

model_loaded = RNNModel.load(path, map_location="cpu")
model_loaded.to_cpu()
```
