### ISSUE TITLE
Make it easier to specify float32 data for PyTorch models

### ISSUE THREAD

**Issue by alexkyllo** [unit8co/darts#572]
**Is your feature request related to a current problem? Please describe.**

I'm trying to train PyTorch forecasting models from Darts using the float32 type, because training on GPU is significantly faster with float32. However, Darts automatically converts integer and boolean columns in my DataFrame to float64, and some of the feature generation functions like `datetime_attribute_timeseries` return float64 type.

**Describe proposed solution**
A clear and concise description of what the library should provide to solve missing functionality.

Improve the API, possibly by adding `dtype` arguments, to give users an easy way to specify we want the time series (and covariates) to be converted to a torch float32 tensor.

I'm currently working around this by assigning the private `_xa` attribute of the `TimeSeries` class, like:

```python
series._xa = series._xa.astype("float32")
```

**Comment by dennisbader** [comment]
Hi @alexkyllo and thanks for writing.

We added this feature in #545 which will be released soon with the next darts version.

**Comment by alexkyllo** [comment]
Excellent, thank you!

**Comment by hrzn** [comment]
Yes, in v0.14.0 you will be able to call `my_series.astype(np.float32)` :)
