### ISSUE TITLE
how to load best model from nbeats ?

### ISSUE THREAD

**Issue by maheshs11** [unit8co/darts#581]
![image](https://user-images.githubusercontent.com/7268915/143815478-ef91088d-18de-4fdb-8a21-06be8cddbc79.png)
![image](https://user-images.githubusercontent.com/7268915/143815614-f74d0bfe-c93d-40dc-811e-4bc59c4d3853.png)

got this error
FileNotFoundError: There is no file matching prefix model_best_* in new2\checkpoints\mahesh_scaled

**Comment by maheshs11** [comment]
should give this parameter val_series = "validation data"
to get best models
my_model.fit(series=train_scaled, val_series=val_scaled, verbose=True)

**Comment by utkuarslan5** [comment]
Hi,

I'm experiencing the same issue. Cannot recover the best model while optimizing with Optuna, it happens rarely and running hyperparameter optimization again seem to work. But I am curious why it happens. (fyi I pass the val_series parameter)
