### ISSUE TITLE
fill_missing_dates

### ISSUE THREAD

**Issue by maheshs11** [unit8co/darts#582]
how to get in this format freq = B ? 2011-01-01

series = TimeSeries.from_dataframe(df,fill_missing_dates=True, freq='B')
![image](https://user-images.githubusercontent.com/7268915/143840540-406124ff-85a7-4d85-bb9e-d994b390a4fa.png)
i get time component this format

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

if half the time format is filled and if it has to continue in the same pattern 
![image](https://user-images.githubusercontent.com/7268915/143841253-bdf60d4e-05c5-4a1a-a97d-5e494d37fa10.png)
for the same code i get this error

series = TimeSeries.from_dataframe(df,time_col=['Month'],fill_missing_dates=True,freq = 'QS')
time continuation for certain time after empty
![image](https://user-images.githubusercontent.com/7268915/143842075-090eb64d-5b92-4569-b458-d5a62fe1248d.png)

**Comment by dennisbader** [comment]
Hi @maheshs11, and thanks for writing.

If I understand the first part of your question correctly (for getting `freq='B'`):
- the generated series has a time index of type `pd.Int64Index` and not `pd.DatetimeIndex`. If you don't specify a `time_col` in `TimeSeries.from_dataframe()`, it will try to generate the time index from the index of your pandas DataFrame. So you have two options:
  - make sure the index of your `df` is the actual `pd.DatetimeIndex` and don't pass `time_col` to `TimeSeries.from_dataframe()`
  - if your dates are stored in a column of your `df`, pass `time_col=your_time_column` to `TimeSeries.from_dataframe()`

for your second question:
- `time_col` must be a string. Try replacing `time_col=['Month']` with `time_col='Month'`.
