### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#589]
Need

- [ ] Add Apple M1 support to Prophet on conda-forge (https://github.com/conda-forge/prophet-feedstock/pull/25)
- [x] Add Apple M1 support to pmdarima

See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by sbhatti2009** [comment]
While I was trying to install Darts on M1, the following steps worked for me:

1. `brew install llvm@11`
2. `echo 'export PATH="/opt/homebrew/opt/llvm@11/bin:$PATH"' >> ~/.zshrc`
3. `echo 'export LLVM_CONFIG="/opt/homebrew/Cellar/llvm@11/11.1.0_4/bin/llvm-config"' >> ~/.zshrc`
4. `pip install darts`
5. `pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite`
6. `pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple numba`

llvmlite python wheels: numba/llvmlite#799

**Comment by martinb-bb** [comment]
I still cannot train NBEATs with M1 but easily can with linux. Any suggestions? 

for reference I am using the following command to install darts.
`conda install -c conda-forge -c pytorch u8darts-torch` 

Then to train:
`model_nbeats.fit(train, val_series=val, verbose=True)`

`File ~/miniforge3/envs/gst/lib/python3.8/site-packages/pytorch_lightning/plugins/environments/torchelastic_environment.py:65, in TorchElasticEnvironment.detect()
     63 """Returns ``True`` if the current process was launched using the torchelastic command."""
     64 if _TORCH_GREATER_EQUAL_1_9_1:
---> 65     return torch.distributed.is_torchelastic_launched()
     66 required_env_vars = {"RANK", "GROUP_RANK", "LOCAL_RANK", "LOCAL_WORLD_SIZE"}
     67 return required_env_vars.issubset(os.environ.keys())

**AttributeError: module 'torch.distributed' has no attribute 'is_torchelastic_launched'`**

**Comment by sbhatti2009** [comment]
> While I was trying to install Darts on M1, the following steps worked for me:
> 
> 1. `brew install llvm@11`
> 2. `echo 'export PATH="/opt/homebrew/opt/llvm@11/bin:$PATH"' >> ~/.zshrc`
> 3. `echo 'export LLVM_CONFIG="/opt/homebrew/Cellar/llvm@11/11.1.0_4/bin/llvm-config"' >> ~/.zshrc`
> 4. `pip install darts`
> 5. `pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite`
> 6. `pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple numba`
> 
> llvmlite python wheels: [numba/llvmlite#799](https://github.com/numba/llvmlite/issues/799)

Did you try following these steps @martinb-bb?

**Comment by martinb-bb** [comment]
hi @sbhatti2009 , thanks for the suggestion.

But sadly no.. seems like it is a pytorch lightning issue.

```
 if _TORCH_GREATER_EQUAL_1_9_1:
---> 65 return torch.distributed.is_torchelastic_launched()
**AttributeError: module 'torch.distributed' has no attribute 'is_torchelastic_launched'`**

```

**Comment by martinb-bb** [comment]
Update - there is a bug with MacOS: https://github.com/PyTorchLightning/pytorch-lightning/issues/13118

**Comment by martinb-bb** [comment]
> Update - there is a bug with MacOS: [PyTorchLightning/pytorch-lightning#13118](https://github.com/PyTorchLightning/pytorch-lightning/issues/13118)

Closed [#13118](https://github.com/PyTorchLightning/pytorch-lightning/issues/13118) as completed via [#13142](https://github.com/PyTorchLightning/pytorch-lightning/pull/13142).

**Comment by hrzn** [comment]
Closing as I believe this is fixed. If anyone runs into issues again feel free to re-open.

**Comment by M-123-456** [comment]
Hello, I have a problem with darts and need really help.
Darts installation could be done successfully with the guide https://github.com/unit8co/darts/blob/master/INSTALL.md (I referred the part for Enabling Support for LightGBM according to the error log).
I've tested ExponentialSmoothing and it is no problem to use it.
However, if I try to do backtest on that model, it says that the parameters start, forecast_horizon etc. don't exist and I cannot run the code (That means I receive also no error). 
I have 
- uninstalled and re-installed
- installed with pip install 'u8darts[all]'
But it doesn't work.

**Comment by M-123-456** [comment]
Hi @hrzn , thanks for reply.
Here's the code.

```
from darts import TimeSeries
import pandas as pd
from darts.models import ExponentialSmoothing
import matplotlib.pyplot as plt
from pylab import rcParams
from darts.metrics import mape
from darts.metrics import mase
import numpy as np
df = pd.read_csv('../../../data/prepared/df_energy_climate_2020.csv')
series = TimeSeries.from_dataframe(df, 
                                   time_col="datetime",
                                   value_cols=["energy_price"])

splitting_point = (int(len(series)*0.20))

# Set aside the second half of series as a validation series
train, val = series[:-splitting_point], series[-splitting_point:]

model_es = ExponentialSmoothing()
# The parameters start, forecast_horizon and verbose are underlined with red, by hovering they show this error: 
start: Unknown
No parameter named "start"Pylance[reportGeneralTypeIssues]

historical_fcast_es = model_es.historical_forecasts(
    series, start=0.95, forecast_horizon=168, verbose=True)

series.plot(label='data')
historical_fcast_es.plot(label='backtest (Exp. Smoothing)')
print(f'MAPE = {mape(historical_fcast_es, series):.2f}%')
model.fit(train)
prediction = model.predict(len(val))
```
