### ISSUE TITLE
[HOWTO] Multi-step prediction with covariates for RegressionModel

### ISSUE THREAD

**Issue by owoshch** [unit8co/darts#595]
I'm going through the file https://github.com/unit8co/darts/blob/b6f8b1c1ad46936d3fc216ef11f45a3645e57813/darts/tests/test_regression_models.py to understand whether RegressionModel can be used to predict multiple timesteps using the past covariates.

I see that it's possible to initialize the `MixedCovariatesSequentialDataset` with  `output_chunk_length` larger than 1.

`lags_1 = [-5, -3, -1]
lags_past_covariates_1 = [-4, -2]

model_instance = RegressionModel(
    lags=lags_1,
    lags_past_covariates=lags_past_covariates_1
)

input_chunk_length = -model_instance.min_lag
training_output_chunk_length = max(model_instance.max_lag + 1, 1)

training_dataset = MixedCovariatesSequentialDataset(
                target_series=train_series_scaled_list,
                past_covariates=train_covariates_scaled_series_list,
                input_chunk_length=input_chunk_length,
                output_chunk_length=training_output_chunk_length
            )
training_samples, training_labels = model_instance._get_training_data(training_dataset=training_dataset)`

However, it's still not clear how can I specify the forecasting horizon while fitting the model.
The code below forces model to predict only one step ahead:
`model_instance = RegressionModel(lags=50, lags_past_covariates=50)
model_instance.fit(series=train_series_scaled_list, past_covariates=train_covariates_scaled_series_list)`

Is it possible to train the RegressionModel to predict multistep time series with past covariates?

**Comment by hrzn** [comment]
Short answer: yes it is possible, by specifying an appropriate `output_chunk_length` parameter.
