### ISSUE TITLE
Extend backtesting and gridsearch methods to work on multiple series (i.e. for GlobalModels)

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#615]
Also we could improve gridsearch substantially, using kinds of random search or even Bayesian optimization.

**Comment by pabuta88** [comment]
Is this already realized? I would love to use gridsearch on multiple series.

**Comment by hrzn** [comment]
Not yet but we would be happy to receive a pull request around this if you feel like contributing :)

**Comment by pabuta88** [comment]
@hrzn I'not sure that my programming skills are advanced enough 😐 But I'm trying to implement it on my own for my project and if it works, I'll get in touch :-)

**Comment by Beerstabr** [comment]
Is anybody working on this issue yet? If not, I would be interested in giving it a go!

**Comment by hrzn** [comment]
An initial support for multiple TimeSeries in backtest and historical_forecasts() has been released in v0.23.0
