### ISSUE TITLE
Models for intermittent time series

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#626]
See e.g.: https://www.lancaster.ac.uk/pg/waller/pdfs/Intermittent_Demand_Forecasting.pdf

**Comment by adamkells** [comment]
@hrzn I am interested in contributing to the darts package and am thinking to try this as a first issue. Can you give any additional details? I see Croston method is already implemented, is the objective to add the Adjusted Croston from the above pdf? Thanks!

**Comment by hrzn** [comment]
Hi @adamkells and thanks for your interest! This is a somewhat old issue that we should have closed once we added Croston - both Croston and adjusted Croston (corresponding to the `sba` version) are now in Darts. Sorry for this!
However if you are up for it, we also do have other issues to work on :)
