### ISSUE TITLE
Issues when plotting a series made of 1 point

### ISSUE THREAD

**Issue by hrzn** [unit8co/darts#650]
Currently plotting series of length 1 is not working.

**Comment by ephsmith** [comment]
Referencing the following in timeseries.py:

https://github.com/unit8co/darts/blob/508d60ae0d801cb2619e1cc1d304d7493c9d8ea6/darts/timeseries.py#L2363

`TimeSeries.plot()` wraps `xarray.DataArray.plot()` which calls `DataArray.squeeze()` ( see [ref](https://github.com/pydata/xarray/blob/d47cf0c850cb70429373782b3c1e0329d14fd05a/xarray/plot/plot.py#L295) ) which in turn strips dims for a series of length 1.  With empty dims, `DataArray.plot()` defaults to a histogram plot. 

A simple workaround may be to call `xarray.DataArray.plot.line` in `TimeSeries.plot()`.  This would force a line plot and bypass the xarray logic for determining the type of plot to use. 

Looking into potential issues.

**Comment by madtoinou** [comment]
I think that this bug has been solved with #1209, the issue should be closed.
