### ISSUE TITLE
[BUG] Getting RuntimeError when loading model that has been trained on GPU on a new machine that only has CPU

### ISSUE THREAD

**Issue by pelekhs** [unit8co/darts#669]
**Describe the bug**
Let's suppose that a model is trained inside a virtual environment with torch and cudatoolkit installed. If I attempt to load this model from another virtual environment without cudatoolkit installed, using darts.models.RNNModel.load_from_checkpoint(), then I receive the error following: 
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
This is a pytorch error that needs attention as it informs the user on how to act given that they use torch.load insted of darts.models.RNNModel.load_from_checkpoint(). Therefore, this error is not valid.

One partial solution is indeed to load the model as pytorch model but then not all darts features are anymore available. Otherwise there should be a darts-wise way to be able to load_from_checkpoint() with changing the runtime device. Is that feasible somehow?

**To Reproduce**

-  Inside a python environment with torch.cuda.is_available=True, train and store a model for example as follows:
```
m/y_model = darts.models.RNNModel(
    save_checkpoints=True,
    log_tensorboard=True,
    torch_device_str='cuda',
    optimizer_kwargs={'lr': 0.005},
    model_name='MyLSTM',
    model='LSTM',
    n_rnn_layers=1
    hidden_dim=128
    n_epochs=200
    input_chunk_length=120
    training_length=120 # should be >= input_chunk
    random_state=42
 
)

my_model.fit(train_transformed, 
             future_covariates=future_cov_train,
             val_series=val_transformed,
             val_future_covariates=future_cov_val, 
             verbose=True)
```
Then try to load it back inside a different python environment where torch.cuda.is_available=False, as follows:
```
best_model = RNNModel.load_from_checkpoint(work_dir='.darts', model_name=model_name)
```
**Expected behavior**
- The error that is thrown is irrelevant as it refers to the torch.load() method that runs in the backend. In any case, the main behaviour expected is that darts provides an option to change the runtime of the model during loading instead of throwing an error at all (even if the error message is corrected).

**System (please complete the following information):**
 - Python version: [3.7.10]
 - darts version [0.14.0]

**Additional context**
Nope

**Comment by dennisbader** [comment]
Hi @pelekhs and thanks for writing.
We already have this on our to-do list with #570.

Closing this as duplicate.
