### ISSUE TITLE
[BUG] `longest_contiguous_slice` throws TypeError if `max_gap_size` is greater or equal than `'gap_size'`

### ISSUE THREAD

**Issue by TahaSha** [unit8co/darts#716]
**Describe the bug**
I am trying to use the `longest_contiguous_slice` method on a `TimeSeries` object with a `freq` of `'W-MON'` but I get this error.
`TypeError: Cannot add Timedelta to Week`

**To Reproduce**
```
# Simulating random data
idx = pd.date_range(start='2018-01-01', periods=100, freq='W-MON')
values = np.random.uniform(low=1, high=300, size=(100))
values.ravel()[np.random.choice(values.size, 40, replace=False)] = np.nan
s = pd.Series(values, index=idx)
# Creating TimeSeries Object
ts = TimeSeries.from_series(s)
# Returning the largest TimeSeries slice that contains no gaps larger than 2
ts.longest_contiguous_slice(max_gap_size=2)
```

**Expected behavior**
Returning the largest TimeSeries slice that contains no gaps larger than 2

**System (please complete the following information):**
 - Python version: [e.g. 3.9.5]
 - darts version [e.g. 0.15.0]

**Additional context**
I noticed that the method would work if I set the `max_gap_size` to a number greater than or equal to 
`ts.gaps()['gap_size'].max()`

**Comment by TahaSha** [comment]
I'm not sure if this can pass the tests for all cases, but I fixed this issue by monkey patching this [line](https://github.com/unit8co/darts/blob/9933d29151218f5c3d30efa42ce049ee20cb4640/darts/timeseries.py#L1412)

to this:
`size = row['gap_start'] - curr_slice_start` (just removing the - self._freq)

**Comment by dennisbader** [comment]
Hi @TahaSha and thanks for reporting this issue.

#725 should fix it.
