### ISSUE TITLE
Transformer attention weights

### ISSUE THREAD

**Issue by pauliusrauba** [unit8co/darts#727]
Is there a current way of extracting how much attention each input receives in multivariate transformers in dart? 

The output of a transformer (the last layer) should provide those attention weights. Currently, they are aggregated to produce the output/prediction, but it would be useful to be able to extract the attention weights, too.

**Comment by dennisbader** [comment]
Hi @pauliusrauba, not yet but it's in our backlog. See #675.

**Comment by pauliusrauba** [comment]
Any existing workaround in place for this?

**Comment by hrzn** [comment]
closing this one as a duplicate of #675
