### ISSUE TITLE
Extending pre-commit functionality and linting 

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#739]
**Is your feature request related to a current problem? Please describe.**
no

**Describe proposed solution**
including more git pre-commit hooks can increase code clarity and prevent bugs.

**Describe potential alternatives**
N/A

**Additional context**
- flake8 can enforce code formatting not automatically fixed by black
- the pre-commit-hook repo can fix many basic annoyance
- pyupgrade can update deprecated methods
- mypy is a static typing 
- isort  or reorder_python_imports improves imports

**example**
```
repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3.7
        args: [--safe, "--line-length", "100"]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']

-    repo: https://github.com/pre-commit/mirrors-mypy
     rev: v0.910-1
     hooks:
     -   id: mypy
         args: [--ignore-missing-imports]
         additional_dependencies: [types-PyYAML, types-requests, types-PyMySQL]


-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]

#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.9.3
#    hooks:
#    -   id: isort
#        args: [-e, "--profile", "black"]
```

I would be willing to work on it but want to know if it would be merged

**Comment by hrzn** [comment]
Hi @gdevos010 , thanks for your proposal! In general we would be very open to add more pre-commit hooks. Could you quickly synchronise with @tomasvanpottelbergh ? He was looking into adding flake8 to our CI pipeline.

**Comment by gdevos010** [comment]
@tomasvanpottelbergh let me know how I can help.

here's a .flake8 config file that works well with black
```
[flake8]
ignore = E203, E266, E501, F401
max-line-length = 100
max-complexity = 18
select = B,C,E,F,W,T4,B9
```

**Comment by tomasvanpottelbergh** [comment]
Hi @gdevos010, thanks a lot for the suggestions and wanting to contribute to this!

I think we should start with flake8 and add other functionality later (isort should probably be next). I would prefer to keep the flake8 ignore list to a minimum. Do you see any reason for us to extend it beyond `E203` [as recommended by Black](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8)?

**Comment by gdevos010** [comment]
[E266](https://www.flake8rules.com/rules/E266.html) I find having more than one # can add to organization and therefore readability 
[E501](https://www.flake8rules.com/rules/E501.html) Is for line length over 80 characters. Many projects have increased this to 100 or 120.
[F401](https://www.flake8rules.com/rules/F401.html) is for module imported but unused. 

These are of course personal preference, but ones that I have found useful.

**Comment by tomasvanpottelbergh** [comment]
Thanks for that! I'm currently fixing flake8 warnings in the code, and E501 seems to be the most problematic, because our docstrings don't respect the 88 character line length. Do you have experience with a tool for autoformatting docstrings?

**Comment by gdevos010** [comment]
I don't know of an automated tool.

For reference [PyTorch](https://github.com/pytorch/pytorch/blob/master/.flake8) uses 120

**Comment by hrzn** [comment]
We could maybe enforce 120. WDYT @tomasvanpottelbergh ?

**Comment by gdevos010** [comment]
@tomasvanpottelbergh I'm going to work on adding isort
