### ISSUE TITLE
how to use GenericShiftedDataset

### ISSUE THREAD

**Issue by Jinwen321** [unit8co/darts#742]
**Describe the bug**
I want to use a shifted dataset for training. The related usage is the class GenericShiftedDataset. However, I could not find any example to use it. I tried many times but all failed.

**To Reproduce**
my_model = BlockRNNModel(
    input_chunk_length=100,
    output_chunk_length=50,
    model='GRU',
    hidden_size=50,
    n_rnn_layers = 1,
    dropout = 0.2,
    random_state=42,
    batch_size= 32,
    n_epochs= 200,
    optimizer_kwargs={'lr': 1e-3},
    model_name='GRU',
    log_tensorboard=True,
    force_reset = True,
    torch_device_str = 'cpu',
    save_checkpoints = True,
    work_dir = 'F:/timeSeriesForecasting/GRU/poz_trial'
)
my_model.fit(series= GenericShiftedDataset(train,input_chunk_length = 100,output_chunk_length=50,shift = 150), 
             val_series= GenericShiftedDataset(val,input_chunk_length = 100,output_chunk_length=50,shift = 150),  verbose=True)

**reported error**
File "C:\Users\Jinwen\AppData\Roaming\Python\Python38\site-packages\darts\models\forecasting\torch_forecasting_model.py", line 423, in fit
    match = (series[0].width == val_series[0].width and

AttributeError: 'tuple' object has no attribute 'width'

**System (please complete the following information):**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.14.0]

**Additional context**

**Comment by brunnedu** [comment]
Hi @Jinwen321, the `GenericShiftedDataset`s `__getitem__` method is returning a tuple, and since the `width` attribute is specific to Darts `TimeSeries` objects, this results in an attribute error. 

Try it instead with `my_model.fit(series=train, val_series=val)`

**Comment by Jinwen321** [comment]
Hi @brunnedu, thanks for your suggestion. I have tried my_model.fit(series=train, val_series=val), and it worked. But as I know, it used a sequential dataset for training by default, namely output series will alway follow input series consecutively in training samples. What I would like to do is to predict future points by skipping some lags. For example, I want to predict data from October to December using data from January to June. To this end, the best way I could think of is to use a shifted dataset, which seemed to correspond GenericShiftedDataset in Darts. Could you give me more suggestions?

**Comment by dennisbader** [comment]
Hi @Jinwen321, you can use BlockRNNModel's `fit_from_dataset()` and `predict_from_dataset()` methods for this.
Check out the docs [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.block_rnn_model.html#darts.models.forecasting.block_rnn_model.BlockRNNModel.fit_from_dataset).

**Comment by Jinwen321** [comment]
Hi @dennisbader, thanks for your reminder. I tried `fit_from_dataset` but got this error:

ValueError: expected type <class 'darts.utils.data.training_dataset.PastCovariatesTrainingDataset'>, got: <class 'darts.utils.data.shifted_dataset.GenericShiftedDataset'>

It seemed that `fit_from_dataset` could only process PastCovariatesTrainingDataset? I read that the docs also presented the example of PastCovariatesTrainingDataset:
train_dataset (TrainingDataset) – A training dataset with a type matching this model (e.g. PastCovariatesTrainingDataset for PastCovariatesTorchModel).

Could you please tell me how to use a shifted dataset? Thanks in advance.

**Comment by dennisbader** [comment]
Yes, this is to make sure that internally we deal with a past covariates model and thus a past covariates training datatset.

There is already a `PastCovariatesShiftedDataset` implemented which calls a `GenericShiftedDataset`, see the docs [here](https://unit8co.github.io/darts/generated_api/darts.utils.data.shifted_dataset.html#darts.utils.data.shifted_dataset.PastCovariatesShiftedDataset).

If this class doesn't do what you want, you can implement your own:

```
from darts.utils.data.training_dataset import PastCovariatesTrainingDataset

class MyPastCovariatesShiftedDataset(PastCovariatesTrainingDataset):
    def __init__(self, ...):
        ...
    def __len__(self):
        ...
    def __getitem__(self, ...):
        ...
```

You can take the source code of `PastCovariatesShiftedDataset` as guide line.

Hope this helps.

**Comment by dennisbader** [comment]
@Jinwen321 can we close this?

**Comment by Jinwen321** [comment]
Sorry, I just saw this. Yes, we can close this. Thank you very much.

Dennis Bader ***@***.***> 于2022年1月21日周五 16:05写道：
