### ISSUE TITLE
ValueError: point (int) should be a valid index in series

### ISSUE THREAD

**Issue by alitirmizi23** [unit8co/darts#758]
Trying to backtest a very simple RNN (LSTM) on a univariate series. Keeps throwing this error: `ValueError: point (int) should be a valid index in series`

Any idea why this would be happening? It fits fine and predicts fine, but backtest doesn't work.
Below is the code: 

```

`my_model = RNNModel(
    model="LSTM",
    hidden_dim=10,
    batch_size=5,
    n_epochs=10,
    optimizer_kwargs={"lr": 1e-3},
    random_state=0,
    training_length=2,
    input_chunk_length=2,
    likelihood=GaussianLikelihood(),
    torch_device_str='cpu'
)
my_model.fit(target_train,verbose=True)
pred = my_model.predict(n=5, 
                        num_samples=50 
                       )

target_val.plot(label="target")
pred.plot(label="prediction")
target_train.plot()
backtest= my_model.backtest(series = scaled_series)`
```

Ends  up into: `ValueError: point (int) should be a valid index in series`

Also, if likelihood is set to Gaussian in case of RNNs, the forecasts come from a distribution and hence won't be deterministic every time we make a forecast?

**Comment by hrzn** [comment]
Hi, could you please embed in your snippet a way to reproduce the issue on the same data (i.e., a way to build `scaled_series`)? Thanks.

> Also, if likelihood is set to Gaussian in case of RNNs, the forecasts come from a distribution and hence won't be deterministic every time we make a forecast?

The forecasts will be stochastic if you specify `num_samples > 1` when calling `predict()`. You can ensure that the (pseudo-)random are always the same by setting the `random_state` of the model (but they will still differ between two consecutive calls to `predict()`).

**Comment by alitirmizi23** [comment]
> Hi, could you please embed in your snippet a way to reproduce the issue on the same data (i.e., a way to build `scaled_series`)? Thanks.
> 
> > Also, if likelihood is set to Gaussian in case of RNNs, the forecasts come from a distribution and hence won't be deterministic every time we make a forecast?
> 
> The forecasts will be stochastic if you specify `num_samples > 1` when calling `predict()`. You can ensure that the (pseudo-)random are always the same by setting the `random_state` of the model (but they will still differ between two consecutive calls to `predict()`).

Sorry for the delay. I actually solved - the issue was because I was instantiating the series using `TimeSeries.from_series` without explicitly passing in the dates/time column. `TimeSeries.from_dataframe` solved it (previously, weird index values were being picked up like 10106 etc). 
I still think though this should not happen and not specifying index/dates/time col should enforce an index in the range `[0,N)`
