### ISSUE TITLE
[BUG] tensorboard does not work with gridsearch when model_name is provided 

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#759]
**Describe the bug**
providing a model name when using gridsearch puts all files under the same folder `./darts/runs/MODEL_NAME`
this breaks tensorboard 

**To Reproduce**
```
NBEATS_params = {
        "log_tensorboard": [True],
        "model_name": ["NBEATS_gs"],
        "layer_widths": [256, 512, 1024],
}

best_model, dict_params = NBEATSModel.gridsearch(NBEATS_params, train_air, val_series=val_air, metric=mape, n_jobs=3, verbose=True)
```

**Expected behavior**
each run should have its own dir

**System (please complete the following information):**
 - Python version: 3.7
 - darts version 0.16.0

**Additional context**

**Comment by hrzn** [comment]
Thanks for flagging. Indeed currently gridsearch was not really meant to work with Tensorboard. Anyway we have a bit of refactoring to do around gridsearch. Leaving this one open for the time being.
