### ISSUE TITLE
[BUG] MASE does not work on backtesting

### ISSUE THREAD

**Issue by ryota113** [unit8co/darts#766]
**Describe the bug**
Getting error while using backtest method if we specify MASE metric that requires insample parameter

**To Reproduce**
code
`raw_errors = prophet_model.backtest(
    train, start=0.5, forecast_horizon=len(test), stride=5, metric=mase, reduction=None, verbose=True)
`

Error screenshot
![image](https://user-images.githubusercontent.com/97139166/152281674-47265389-6f0a-4f67-adbc-ec52af94d293.png)

**System**

- Python 3.9
- Darts 0.16.1

**Comment by hrzn** [comment]
MASE is not supported for backtesting as it requires the insamples. We won't fix this one => closing.
