### ISSUE TITLE
[QUESTION] Modelling prediction of not-nearest future, treatment of past covariates

### ISSUE THREAD

**Issue by edvinsav** [unit8co/darts#770]
I have a situation which I'm uncertain on how to model and treat correctly using the darts interface. This might be more of a modelling question than a darts question, but I'm happy for any response.

I have a series with hourly values for which I want to make daily predictions of the 24 values for the day after the next, see attached figure. At the time of prediction the series and past covariates are known up to the start of day D-1. I'm not interested in predicting the nearest future (the 24 values of 'D-1'), but instead the 24 values after that. 

I'm wondering

- How should I adapt my training so that I minimise with respect to the particular predictions I want to make (as described above)? I don't want to fit my model to make predictions at the very end of the training series. I suppose one possible way is to use lags and `past_covariates` lags which go up to, but not further than, 48 steps before the target, say `lags=[-50, -49, -48]`, This way I connect the target value with the values 48 hours into the past (and further back, if I want to). 
- What is the correct way of doing the predictions: should I call `predict(48)` and drop the first 24 values?

![bild-tidslinje](https://user-images.githubusercontent.com/94692340/152515043-563f7ed7-3a1a-4877-8798-0666c5bd1749.png)

**Comment by hrzn** [comment]
Hi,
You would have to predict the 48 next values and drop the first 24 values. 
With the deep learning models, you can train your models to pay more attention to the last 24 points of the output chunks by, say, having `output_chunk_length=48` and specifying a custom `loss_fn`. You can give your own loss function, which for instance ignores (or puts only little weight) on the first 24 values out of the 48 values; for instance, in pseudo-code something like this for an MSE loss
```
my_loss_fn = lambda x, y: (x[-24:] - y[-24:])**2
```

**Comment by edvinsav** [comment]
Ah I see, thanks! What about linear regression? Do I understand correctly the lags if I say that I should use `lags` (and `lags_past_covariates`) `= [-..., -51, -50, -49, -48]` to get the correct X matrix and thus the correct loss function there?
