### ISSUE TITLE
Predicting Nan with Stock Data (regardless of model)

### ISSUE THREAD

**Issue by orthosku** [unit8co/darts#772]
Hi there, 

running into trouble with predicting Nan Values. Initially thought that this could be from using a weekday timeseries (working with stock data). I saw the post about changing Freq='B' for a business day time index. Even with doing this, the prediction array still has Nan values. I tried using this data with NBEATs as well as RNN model - both have yielded the same results. Would love some help!

Below is the data I'm using as well as the prediction array readout. 

```
 close
timestamp             
1999-11-19  142.500000
1999-11-22  142.468704
1999-11-23  141.218704
1999-11-24  141.968704
1999-11-26  141.437500
1999-11-29  140.937500
1999-11-30  139.281204
1999-12-01  140.406204
1999-12-02  141.250000
1999-12-03  143.843704

[5589 rows x 1 columns]
100%|██████████| 100/100 [27:40<00:00, 16.60s/it]
100%|██████████| 229/229 [00:09<00:00, 24.62it/s]
<TimeSeries (DataArray) (time: 229, component: 1, sample: 1)>
array([[[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

...

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]],

       [[nan]]])
Coordinates:
  * time       (time) datetime64[ns] 2017-09-11 2017-09-18 ... 2022-01-24
  * component  (component) <U1 '0'
Dimensions without coordinates: sample
```

**Comment by dennisbader** [comment]
Hi @orthosku. This seems like you have missing values already in your training data.
Can you check the following on your input TimeSeries (where `ts` is any of your TimeSeries)?
```
ts.pd_dataframe().isna().any()
```

**Comment by dennisbader** [comment]
That is good, and yes, you should use `freq='B'` for business day frequency.
Parameter `fill_missing_dates` will only insert the missing business days (the dates) as rows with Nan values into your TimeSeries object. 

Now to fill the missing values you can take a look at our `MissingValuesFiller` (https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.missing_values_filler.html)

**Comment by dennisbader** [comment]
To copy @hrzn:

Let's say you have daily data with a missing date:
```
Mon --> 1
Tue --> 2
Thu --> 4
Fri --> 5
```

Then`fill_missing_dates=True` will insert the date with Nan values (in the columns)

```
Mon --> 1
Tue --> 2
Wed --> NaN
Thu --> 4
Fri --> 5
```

Finally by filling the missing values:

```
Mon --> 1
Tue --> 2
Wed --> 3
Thu --> 4
Fri --> 5
```

**Comment by MRV1N2** [comment]
Hello orthosku, I've also been dealing with darts for a few days to predict Stock Prices, would you like to exchange experience, my Discord name is MRV1N#1905
