### ISSUE TITLE
Gridsearch should return metric score along with the best untrained model and parameters.

### ISSUE THREAD

**Issue by nlhkh** [unit8co/darts#776]
**Is your feature request related to a current problem? Please describe.**
When performing gridsearch, we also want to know how good the best parameters can perform. I can have this insight if I can access the score as the result of gridsearch. It is redundant to have to run backtest again to get the score.

**Describe proposed solution**
In the `gridsearch` method, return the metric score in addition to the model and parameters.

**Describe potential alternatives**
Create another method `gridsearch_with_score`, so that it won't affect existing code.

**Additional context**
The score is needed to evaluate how much I should trust the best parameter. If is it not good, then perhaps it can hint that we should use a different forecasting approach.

**Comment by hrzn** [comment]
It could be a good idea. I would vote for doing this in the origin `gridsearch` method. Would you be up for opening a PR?

**Comment by nlhkh** [comment]
> It could be a good idea. I would vote for doing this in the origin `gridsearch` method. Would you be up for opening a PR?

Yes, I can do this. I'm a little slow but I will find time.

**Comment by nlhkh** [comment]
> It could be a good idea. I would vote for doing this in the origin `gridsearch` method. Would you be up for opening a PR?

Do you think I should make the returned score optional so as not to break existing projects?
