### ISSUE TITLE
[BUG] Cannot install darts in colab notebook

### ISSUE THREAD

**Issue by Shibina6** [unit8co/darts#778]
**Describe the bug**
I tried to install darts in colab using the code !pip install darts. But everytime its getting stuck while collecting statsmodels. The installation doesn't go further. I also tried installing with following codes: 
!pip3 install darts
!pip install u8darts
But its the same issue as above.

**To Reproduce**
![image](https://user-images.githubusercontent.com/92287502/153255947-c83d77ea-35e9-4624-bcb4-131f1547d575.png)

**System (please complete the following information):**
 - Python version: 3.7.12
 - darts version [e.g. 0.14.0]

**Comment by hrzn** [comment]
Could you try again and let us know if it works? I have installed darts multiple times without issues in colab.

**Comment by nikkisingh111333** [comment]
i m getting the same error please help me

**Comment by Shibina6** [comment]
The issue from my side was resolved later by installing statsmodels version 0.13.0 using the code : 
!pip install statsmodels==0.13.0, before installing darts,when i found that installing the statsmodels version 0.13.2 was having difficulties.
Also when i tried to install darts now it worked smoothly by installing the statsmodels version 0.13.2.
