### ISSUE TITLE
Get parameters trained model

### ISSUE THREAD

**Issue by Khanifsaleh** [unit8co/darts#783]
is it possible to get dictionary of parameters from trained model?
like get_params() function in sklean.
Or it's fine if I run .fit twice or more?
And calling fit() more than once will overwrite what was learned by any previous fit()?

**Comment by hrzn** [comment]
> is it possible to get dictionary of parameters from trained model? like get_params() function in sklean. Or it's fine if I run .fit twice or more? And calling fit() more than once will overwrite what was learned by any previous fit()?

Hi, for all `RegressionModel`s (the ones wrapping around e.g. sklearn models), accessing `my_model.model` will return the underlying estimator. So for instance in the case of a linear regressor you can do something like `my_model.model. coef_` to get the coefficients.

On `RegressionModel`s running `fit()` twice will re-fit the model from scratch, but on all the deep learning models, it will just keep training, starting off from where it left.

Hope this helps.
