### ISSUE TITLE
[BUG] Incorrect hash string while loading dataset

### ISSUE THREAD

**Issue by Johari-Kritika** [unit8co/darts#788]
**Describe the bug**
DatasetLoadingException: Expected hash for /.darts/datasets/monthly_milk.csv: 4784443e696da45d7082e76a67687b93, got: 80421de65dfdafc965743bbc417427e1

**To Reproduce**
from darts.datasets import AirPassengersDataset, MonthlyMilkDataset

series_air = AirPassengersDataset().load().astype(np.float32)
series_milk = MonthlyMilkDataset().load().astype(np.float32)

**Expected behavior**
Load the dataset into variables.

**System (please complete the following information):**
 - Python version: 3.7.11
 - darts version : 0.16.1

**Additional context**
The issue gets resolved on running the import command separately for each dataset-

from darts.datasets import AirPassengersDataset
from darts.datasets import MonthlyMilkDataset

**Comment by dennisbader** [comment]
We fixed this with #791 and #792
