### ISSUE TITLE
It's possible to Handle Many Times Series Simultaneously ? (in the same dataset)

### ISSUE THREAD

**Issue by Alex891** [unit8co/darts#790]
I have a dataset containing data from multiple clients (about 2 million), and I was wondering if with darts could handle them simultaneously. Each timeseries is in the univariate form.

**Comment by hrzn** [comment]
Hi @Alex891, in principles yes - that should be doable. The main question I think will be whether those 2 millions `TimeSeries` objects fit into memory. If they do not, I would recommend you to focus on deep learning models only, write your own Python `Sequence` (to be provided e.g. to `fit()`), where you can do lazy loading of your series (e.g. from disk). It is then possible to parallelise loading of the data with the actual training by specifying e.g. some `num_loader_workers >= 1`. A GPU would probably greatly help. I recommend you take a look [here for some performance tuning recommendation](https://unit8co.github.io/darts/userguide/performance.html).

Is this by any chance a publicly-available dataset?

**Comment by Alex891** [comment]
Thank you very much for the timely reply.

Unfortunately it is a dataset that I am building with the data I have available. As a guideline, the structure is this:

![image](https://user-images.githubusercontent.com/29921525/154083749-ec3c65ad-be18-42dc-98fd-99bee605065d.png)

**Comment by hrzn** [comment]
OK, I'll close then. Let us know if you have more questions.
Also if you have experiences to share, don't hesitate to join our Discord server.
