### ISSUE TITLE
[BUG] NBEATS seasonality generator wrong basis

### ISSUE THREAD

**Issue by vladimir-chernykh** [unit8co/darts#803]
**Describe the bug**
When creating the interpretable NBEATS model, the seasonality stack should contain Fourier-type basis vectors. It is described in the [original paper](https://arxiv.org/pdf/1905.10437.pdf):

![Screenshot 2022-02-16 at 15 34 31](https://user-images.githubusercontent.com/6755162/154265558-e78c5e39-07eb-4903-9560-4017515c4474.jpg)

The timesteps in **t** vector should be **normalized** by the horizon length for both trend and seasonality generators.

In DARTS implementation they are **not normalized** in `_SeasonalityGenerator`
https://github.com/unit8co/darts/blob/cd361e37ab57d74e02787d2a29cb8fa759febaf8/darts/models/forecasting/nbeats.py#L48-L69

It leads to the fact that interpretable models **do not learn seasonality at all**.

**To Reproduce**
Train any interpretable model and see that the seasonality is not learnt. Example: simplest `sin` function as data.

```python
import numpy as np
import matplotlib.pyplot as plt

from darts.models import NBEATSModel
from darts import TimeSeries

model_nbeats = NBEATSModel(
    input_chunk_length=100, 
    output_chunk_length=10,
    generic_architecture=False,
    n_epochs=1,
    batch_size=200,
)

series = TimeSeries.from_values(np.sin(np.arange(1000)))
series_train = series[:-10]
series_valid = series[-10:]

model_nbeats.fit(series_train)

forecast = model_nbeats.predict(10)

plt.figure(figsize=(20, 8))
series_train[-10:].plot(label="Real data")
series_valid.plot(label="Real data")
forecast.plot(label="Predictions")
```

![Screenshot 2022-02-16 at 15 56 59](https://user-images.githubusercontent.com/6755162/154269214-f7d96aed-c0dd-46b9-9129-e2a53d19598b.jpg)

One can also look at the first basis vector (which should be cosine function).

```python
first_basis_vector = model_nbeats.model.stacks[1].blocks[0].forecast_g.basis[1].cpu().numpy()
print(first_basis_vector)
# [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```

**Expected behavior**
The seasonality should be learnt as described in the paper. One needs to fix the basis vectors to achieve that.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.16.1 as well as latest master commit https://github.com/unit8co/darts/commit/cd361e37ab57d74e02787d2a29cb8fa759febaf8

**Additional context**

--

**Comment by dennisbader** [comment]
Thanks for this investigation, it's really appreciated!
Let's further discuss in #804

**Comment by vladimir-chernykh** [comment]
Fixed with https://github.com/unit8co/darts/pull/804
