### ISSUE TITLE
[BUG] Cannot install Darts on my colab Notebook

### ISSUE THREAD

**Issue by nikkisingh111333** [unit8co/darts#818]
Hello i m new here I m following YouTubers tutorial on darts ....by Krish naik...i tried darts on Colab 
i m getting this error by using this dataset import
`from darts.datasets import AirPassengersDataset, MonthlyMilkDataset
AirPassengersDataset().load().pd_series()`

Getting this Error:
**TypeError: load() missing 1 required positional argument: 'Loader'**

Why this is happening ? please reply me some solution

**Comment by dennisbader** [comment]
Hi can you run `!pip install pyyaml==5.4.1` before installing darts and try again?

Have a look at the accepted answer here: https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col
