### ISSUE TITLE
Print Pytorch Model Summary

### ISSUE THREAD

**Issue by hemasunder** [unit8co/darts#823]
Is there an option available in Darts to print out the pytorch model architecture like torchsummary or tensorflow's model summary?

I'm trying to use the Transformers model in version `0.16.0` and didn't find any reference to this feature in the documentation.

**Comment by dennisbader** [comment]
If you upgrade to version `0.17.1` it should print the model summary by default

**Comment by DeastinY** [comment]
I'm on `0.17.1` and even manually set `"enable_model_summary": True` in `pl_trainer_kwargs` but it still doesn't print a summary for me with `TFTModel`

**Comment by hrzn** [comment]
Closing as this should work now.
