### ISSUE TITLE
[Question] Cannot overfit TCN and Transformer model 

### ISSUE THREAD

**Issue by leyp1** [unit8co/darts#828]
I have been trying overfit the darts models on my dataset by only training on one sample of the dataset. This worked for both the RNN model and the NBEATS model, however the TCN and Transformer models have not followed in the same behavoir. I am training the models using the fit() function using a validation/training split based on a set date. 
**TCN Model on one datasample**
![image](https://user-images.githubusercontent.com/100677791/156136608-e5fd4dd8-df3b-4757-8e82-4edc305c44f0.png)
**Transformer Model on one datasample**
![image](https://user-images.githubusercontent.com/100677791/156136746-32a9d47e-4214-43c5-8361-af3be3614b57.png)

**What I expected: (RNN Model)**
![image](https://user-images.githubusercontent.com/100677791/156136912-147fe6ad-85ee-44c2-9c2d-3f822535e709.png)

**System:**
 - Python version: [e.g. 3.7]
 - darts version [e.g. 0.14.0]
 
 I am uncertain if I used the package incorrectly or if it could be another issue here, I would be happy about any response. If there is any more information you need I would happily provide this.

**Comment by leyp1** [comment]
Thank you for your quick answer. I get an "RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation" error when setting dropout to 0 for the TCN model, but when setting the dropout to a very small value I indeed manage to overfit it.

However the transformer model still has trouble:
![image](https://user-images.githubusercontent.com/100677791/156409323-80ffdc3b-2af2-43ec-bae7-9c82c17133e5.png)
I am only training it on one time series so I don't think it could be a capacity problem. But I can't really explain the behavior ...

**Comment by dennisbader** [comment]
You need to upgrade your darts version, then it should work
