### ISSUE TITLE
How to Serialise Models and Pass X_test during inference time?

### ISSUE THREAD

**Issue by barmanroys** [unit8co/darts#835]
It is an amazing library, and cannot thank the developers enough. The questions I have are more about understanding the API rather than feature request/bug report, so if there is any other darts specific user forum more suited for these questions, please point it out. 

- A crucial difference with the models (supervised classification or time series etc.) is the absence of any feature input in the `predict` method. I mean the standard API across tensorflow or sklearn is `model.predict(x=feature)`. How to incorporate a similar idea in darts? Suppose in a time time series, with an input chunk length (or lookback window) of 5, I want to predict the next 3 steps. Then should not I pass the previous five steps (suppose a 1024x5 matrix where 1024 is the batch size) to get a 1024x3 matrix? Without this input, what preceding values are the model prediction outputs based on? Seems I have a big conceptual gap here in terms of how time series works for supervised regression. 
- How to serialise the model into disk, load and make predictions using it? I am looking for something like the `model.save(filepath='multilayer_attention') `from tensorflow.

**Comment by dennisbader** [comment]
Hi @barmanroys.
In Darts we have two types of models which differ in their predicition API:
- LocalForecastingModel (LFMs, mostly simpler statistical models): when calling `predict(...)` the forecast starts one time step after the end of the target series you used to train the model. These models do not accept passing a arbitrary target series at prediction time.
- GlobalForecastingModel (GFMs, our regression and deep learning models): calling `predict(...)` without passing a `series` is similar to LFMs. When calling `predict(series=my_arbitrary_target, ...)` the forecast starts one time step after the end of `my_arbitrary_target`.

Our guide on covariates from [here](https://unit8co.github.io/darts/userguide/covariates.html) describes this in more detail. It also states which models are LFMs/GFMs.

For your first point: the batches in our deep learning models are directly extracted from the time series (targets and covariates) you use when calling `fit()` or `predict()`. I recommend you to read our guide on TorchForecastingModels from [here](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html) (our deep learning models) for a better understanding of how your input data is used under the hood.

For your second point: Our TorchForecastingModels support either automatic checkpointing or manual saving. Have a look for example at the `TFTModel.save_model()` documentation from [here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.save_model).
