### ISSUE TITLE
Nbeats Foreccasting Future Series?

### ISSUE THREAD

**Issue by nikkisingh111333** [unit8co/darts#842]
Hello i m using N-Beats for Energy dataset i want to forecast Future series rather than Historical_forecast..How Can i do that ?
i want to predict Future time series by providing future time Date..Please Guide me through ?

**Comment by gdevos010** [comment]
you can use the `.predict` to forecast the future. 


if you are looking for future covariates, that is still on the to-do list 
https://github.com/unit8co/darts/issues/812

**Comment by nikkisingh111333** [comment]
Can you please share me a small code snippet of. `.predict` method because i have tried it on colab but dont getting the required parameters to predict the series please share me how to use predict function.

**Comment by hrzn** [comment]
You can have a look at the examples section of the documentation, it contains an example with obtaining a prediction using an N-BEATS model.

**Comment by nikkisingh111333** [comment]
its only showing example for Historical_forecast() method..Not predict() function..please share a code snippet for Prediction using
`.predict()`

**Comment by hrzn** [comment]
See for example here: https://unit8co.github.io/darts/quickstart/00-quickstart.html#Training-forecasting-models-and-making-predictions

And the API doc here: https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html#darts.models.forecasting.nbeats.NBEATSModel.predict

**Comment by nikkisingh111333** [comment]
ok thanks a lot i will check it out ..
