### ISSUE TITLE
[BUG] ARIMA future covariates not working

### ISSUE THREAD

**Issue by Japsz** [unit8co/darts#843]
**Describe the bug**
ARIMA model is not letting me introduce exogenous variables into the model.

**To Reproduce**
```
df = pd.DataFrame([[1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [2,3], [3,4], [4,5], [5, 4], [3, 5], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4], [4,5], [5, 4], [3, 5], [1,2], [2,3], [3,4`], [4,`5], [5, 4], [3, 5]], columns=['target', 'covar'])
df.index = pd.RangeIndex(start=0, stop=len(df))

series = TimeSeries.from_dataframe(df, None, ['target', 'covar'])
train, test = train_test_split(series, test_size=0.2)

arima = ARIMA(p=1, d=1, q=1)
arima.fit(train['target'], future_covariates=series['covar'])
preds = arima.predict(len(test['target']), future_covariates=series['covar'])
```

```
[2022-03-11 17:07:28,770] ERROR | darts.models.forecasting.forecasting_model | ValueError: For the given forecasting horizon 'n=10', the provided 'future_covariates' series must contain at least the next 'n=10' time steps/indices after the end of the target 'series' that was used to train the model.
```
**Expected behavior**
I'm expecting this to work since I'm making sure that there's already at least n point after the training series ends.

**System (please complete the following information):**
 - Python version: 3.8.5
 - darts version 0.17.1

**Additional context**
I've been debugging a lot and seems that the internal slicing will always give a future covariate series that's one less than the prediction needs (when freq is 1), hence throwing the error.
in darts/models/forecasting/forecasting_model.py line 1183
```
future_covariates = future_covariates[
                start : start + (n - 1) * self.training_series.freq
            ]`
```

**Comment by Japsz** [comment]
Can someone confirm if this is intended or not? Just wanna make sure I'm not doing something wrong with my code

**Comment by dennisbader** [comment]
Hi @Japsz and thanks for pointing this out.

You are right, the slicing only correctly works for DatetimeIndex and not a RangeIndex.

We need to fix this

**Comment by DeastinY** [comment]
I've run into the same error today. Good timing 😁

**Comment by parshinsh** [comment]
I'm still getting the error of RangeIndex for ARIMA and VARIMA.

**Comment by dennisbader** [comment]
Which darts version are you using? 
Please share the error message along with a minimal code snippet to reproduce the issue, thanks!

**Comment by yigitcancomlek** [comment]
Seems like this issue still persists for the ARIMA (ARMA) Model. I am still getting the same error with the below code

train_ts, val_ts= target_ts.split_before(train_cutoff)
train_val_cov  = covariates_ts; 

model = ARIMA(p=1,d = 0,q=1)
model.fit(series = train_ts,future_covariates = covariates_ts)
