### ISSUE TITLE
handle multiple Timeseries object at the same time

### ISSUE THREAD

**Issue by yowgwowang** [unit8co/darts#844]
**Is your feature request related to a current problem? Please describe.**
I have a dataset (1M rows) consisted with ~1000 different time series. I want to process them into time series object then train them using the deep learning model. However, I need to process the time series one at a time, every time right before I do model training. It would be great if I can save these ~1000 time series'  TimeSeries object into a single file so I can reuse it later. Currently the class of timeseries supports saving the object, but it doesn't handle the case if I want to save multiple of them into the same file.

**Describe proposed solution**
For example, if TimeSeries.from_dataframe() and TimeSeries.to_dataframe()   can add one more optional input like key to handle multiple time series saved in the same dataframe.

**Comment by hrzn** [comment]
Hi, if you load all the TimeSeries for instance in a list (or some other structure), you can try pickling that directly. We have observed that loading lists containing several thousands of TimeSeries instance from a pickle file can be very fast. Also keep in mind that some processing tools in Darts (such as Scalers, metrics, and of course all global models) are designed to act on Sequence [TimeSeries] (e.g. a list of TimeSeries) and can often parallelize processing.
