### ISSUE TITLE
[BUG] Import error while loading required library in aws sagemaker jupyterlab

### ISSUE THREAD

**Issue by rahul4tripathi2** [unit8co/darts#846]
Hi Team,

I'm getting the below error while trying to run this notebook in jupyterlab
https://github.com/unit8co/darts/blob/master/examples/01-multi-time-series-and-covariates.ipynb

ERROR
ImportError: cannot import name 'BlockRNNModel'
ModuleNotFoundError: No module named 'darts.datasets'

Regards
Rahul

**Comment by dennisbader** [comment]
Hi @rahul4tripathi2, how did you install darts?
Can you verify that your kernel has darts installed by executing the code below? 
Which version is printed?

```
import darts

print(darts.__version__)
```

**Comment by rahul4tripathi2** [comment]
Hi Dennis,

using pip install darts i'm installing darts. 
it installed successfully but still it is not able to print the version.

<img width="484" alt="darts_import_error" src="https://user-images.githubusercontent.com/20778899/158635245-360a43c9-8c84-4db2-9b2b-cc9e024f891e.PNG">

**Comment by dennisbader** [comment]
Can you try installing version 0.17.1 specifically?

`pip install darts==0.17.1`

Also try to restart your kernel as suggested.

**Comment by rahul4tripathi2** [comment]
even with the given version getting attached error
<img width="858" alt="classic_jupyter" src="https://user-images.githubusercontent.com/20778899/158819163-94830270-9ec9-4fe3-9103-2c3957628421.PNG">
<img width="716" alt="darts_install_issue" src="https://user-images.githubusercontent.com/20778899/158819175-81eb8bf1-9e59-47db-8cd2-2ed1c38587de.PNG">

**Comment by dennisbader** [comment]
Which python version are you using? Darts is for 3.7+

**Comment by rahul4tripathi2** [comment]
I'm using python 3.7. Dropping the idea to use dart because of multiple dependency issue

**Comment by hrzn** [comment]
Hi, there's an issue with your setup apparently. Something in your cache/network/pip config is preventing pip from seeing recent versions of Darts. It really looks like an issue with your settings.
