### ISSUE TITLE
Question: How to use  multiple covariate TimeSeries in a global model?

### ISSUE THREAD

**Issue by pabuta88** [unit8co/darts#850]
Let's assume I have 10 different time series over the same time span, for wich I know they have an impact on each other. For all those time series I have the same covariates (in the past and in the future). My goal is to use an LSTM to make a prediction for all those time series using the information I have from the others.

I started training a global model on all those series and validate it on one single series to find the optimal parameters. However, using this approach, I can only use one future covariate TimeSeries to make predictions and loose the information on the other 9 future covariate TimeSeries. 

While reading your introduction, I noticed that maybe multivariate TimeSeries are what I'm looking for. In my case I would have a multivariate TimeSeries containing 10 dimensions.

Does this make sense? Is it possible to combine both approaches?

**Comment by dennisbader** [comment]
Yes, doing a multivariate target prediction makes sense.

If you really want to combine both you could do something like this:

- You pass your 10 target series as a list/sequence to fit/predict.
- For each target series in your list, you could stack the other 9 targets to your target specific past covariates. Pass all 10 past covariates as a list/sequence to fit/predict.
- pass list/sequence of your 10 future covariates to fit/predict.
- note that with this approach you can only directly predict n<=output_chunk_length points as you lack the predictions for the other 9 targets which are now used as past covariates

**Comment by dennisbader** [comment]
All GlobalForecastingModels (GFM) also support multivariate target time series. There are other non-GFMs which support multivariate target series (like VARIMA).

GFMs can train and predict on a list/sequence of target (and past and past and/or future covariate) series. We call this Multiple-TS (time series).

The difference is:
- Multiple-TS support target series of different lengths, time spans, ... If you have 10 target series with covariates, your model trains/predicts "sequentially/non-jointly" on those. This is useful if you have independent target series.

- multivariate: all target components must be in the same target series, they all must have the same index, ... If you have n=10 target components, the models will train/predict on them jointly. This is especially useful if your components are related to each other somehow).

You can also combine the two :)

**Comment by pabuta88** [comment]
@dennisbader Thanks a lot for your explanation and for taking the time. It makes perfectly sense now!
