### ISSUE TITLE
Error using gridsearch for BlockRNNModel[BUG]

### ISSUE THREAD

**Issue by Anoshmedea** [unit8co/darts#852]
# Code:

### Base model default

my_model = BlockRNNModel(
    model="LSTM",
    input_chunk_length=16,
    output_chunk_length=12,
    hidden_size=20,
    n_rnn_layers=1,
    batch_size=13,
    n_epochs=300,
    dropout=0,
    model_name="Air_Block_RNN",
    optimizer_kwargs={"lr": 1e-3},
    random_state=42,
    force_reset=True,
)

my_model.fit(
    train_transformed,
    past_covariates = covariates,
    val_series=val_transformed,
    val_past_covariates=covariates,
    verbose=True)

### Hyper parameter tunning

parameters = {
    'hidden_dim':[20,30],
    'batch_size':[16,32],
    'dropout':[0,0.2],
    'n_rnn_layers':[1,2]    
}

best_model = my_model.gridsearch(parameters, 
                                 series= train_transformed,
                                 val_series = val_transformed,
                                 past_covariates = covariates,
                                 verbose = True,
                                 metric= mape)

best_model

### Error:
TypeError: __init__() missing 2 required positional arguments: 'input_chunk_length' and 'output_chunk_length'

It doesn't work even after giving  'input_chunk_length' and 'output_chunk_length'

**Comment by mlap** [comment]
@Anoshmedea I am running into this same problem, did you resolve this?

**Comment by Anoshmedea** [comment]
@mlap Yes I solved the problem. Check the code below.

**Hyper parameter tunning**

parameters = {
    'hidden_size':[20,30],
    'batch_size':[16,32],
    'dropout':[0,0.2],
    'input_chunk_length':[16,20,24],
    'output_chunk_length':[12,14,18],
    'n_rnn_layers':[1,2]    
}

best_model = my_mo.gridsearch(parameters, 
                              series= train_transformed,
                              val_series = val_transformed,
                              past_covariates = covariates,
                              verbose = True,
                              metric= mape)

best_model
