### ISSUE TITLE
Question: How to use covariates when predicting global models?

### ISSUE THREAD

**Issue by pabuta88** [unit8co/darts#859]
I'm not sure what the correct way of using covariates in the predict method is when fitting a global model. Let's say I fit the following model:

```
modelLR = LinearRegression()

modelLR.fit(
    [target_series_1_train, target_series_2_train]
    ,past_covariates=[covariate_series_1, covariate_series_2]
    ,future_covariates=[covariate_series_1, covariate_series_2]
)
```

My ultimate goal is to make predictions for target_series_1 based on its history, its covariates (past and future) and on target_series_2 and its covariates, respectively. When I make a forecast, I see two different ways of doing it:

1. Using only series_1, the series I want to predict:

```
predictions = modelLR.predict(
    n=100
    ,series=target_series_1_train
    ,past_covariates=covariate_series_1
    ,future_covariates=covariate_series_1
)
```

2. Using both series:

```
predictions = modelLR.predict(
    n=100
    ,series=[target_series_1_train, target_series_2_train]
    ,past_covariates=[covariate_series_1, covariate_series_2]
    ,future_covariates=[covariate_series_1, covariate_series_2]
)
```

Both approaches give me one TimeSeries containing the predictions. What is the correct and intended approach? What do I actually get when using the second approach?

**Comment by hrzn** [comment]
Hi, both would work. With the first approach you forecast each of your series, one at a time. With the second approach, predict() will forecast both series and return you a list of two series (your two forecasts). The advantage of the second approach is that the computation can be vectorized over multiple series which for some models will be faster.

**Comment by pabuta** [comment]
@hrzn Thank you for your quick reply. That makes absolutely sense. I was wrong when saying that both return one forecast. Thanks for clarifying and explaining the idea behind it.
