### ISSUE TITLE
Question: Is it natural that the results vary according to the order of the past_covariates?

### ISSUE THREAD

**Issue by KimChangHyeon111** [unit8co/darts#870]
Hello, I always appreciate that your darts library makes time series analysis easier.

I was learning about the library through the example in the link below, but I had a question in the fast_covariates section.

If you look at the code at the bottom, there is the 'past_covariates=melting.stack(rainfalls)' part. Melting and rainfalls are both data generated by darts.utils.timeseries_generation. According to the description, it is a code that uses two pieces of historical data as covariates at once.

```
def eval_model(model, past_covariates=None, future_covariates=None):
    # Past and future covariates are optional because they won't always be used in our tests
    
    # We backtest the model on the last 20% of the flow series, with a horizon of 10 steps:
    backtest = model.historical_forecasts(series=flow, 
                                          past_covariates=past_covariates,
                                          future_covariates=future_covariates,
                                          start=0.8, 
                                          retrain=False,
                                          verbose=True, 
                                          forecast_horizon=10)
    
    flow[-len(backtest)-100:].plot()
    backtest.plot(label='backtest (n=10)')
    print('Backtest RMSE = {}'.format(rmse(flow, backtest)))

```

```
brnn_melting_and_rain = BlockRNNModel(input_chunk_length=30, 
                                      output_chunk_length=10, 
                                      n_rnn_layers=2)
brnn_melting_and_rain.fit(flow_train, 
                          past_covariates=melting.stack(rainfalls), 
                          epochs=100, 
                          verbose=True)
eval_model(brnn_melting_and_rain, 
           past_covariates=melting.stack(rainfalls))
```
In the process of personal learning, I was wondering if changing the order of these two would produce the same result, so I transformed melting.stack(rainfalls) into rainfalls.stack(melting). As a result, even if the same random_state (42) was specified, different MAPEs were returned.

Therefore, I wonder if this is simply a negligible problem caused by a different order of data stacks (i.e., whether the order of the stack of variables does not matter), or whether the order of the variables actually affects it.

you can check the original code from here

https://unit8.com/resources/time-series-forecasting-using-past-and-future-external-data-with-darts/

Thank you.

**Comment by hrzn** [comment]
Hi, in terms of modelling, the order does not make a difference. However, in practice, due to the random initialisation of the neural networks weights, making 2 different experiments with the dimensions placed in different orders will in general produce different results, even if the random seed is the same.
I hope that answers the question.
