### ISSUE TITLE
[BUG] Discrepancy between historical_forecasts() and predict()

### ISSUE THREAD

**Issue by mlap** [unit8co/darts#875]
**Describe the bug**
I've noticed that when I give an LSTM probabilistic model the exact same input -- like giving both the same time series that is the length of the input window --, I get very different results for `historical_forecasts()`, with `retrain=False`, and `predict()`. I have not quite dug through the repo here as to find out why this is so, but intuitively I would think that I should be getting the same output here. If this is not a bug, can someone explain why this is happening?

**To Reproduce**
Train an LSTM model with a Laplace Likelihood on a collection of 1-D time series. Plot forecasts from `predict()` and `historical_forecasts()` on a test time series.  (Will update with code or a colab notebook when I have the time)

**Expected behavior**
I would have expected the plots from `predict()` and `historical_forecasts()` to be the same

**System (please complete the following information):**
 - Python version: 3.8.5
 - darts version: 0.17.1

**Additional context**
None

**Comment by dennisbader** [comment]
Hi @mlap, could you provide a code snippet to reproduce this? 

In short: Historical forecasts predict with a moving window until the end of the underlying target series. It uses the actual target values as input.

Predict starts at the end of the target series and predicts into the future. For longer forecast horizons, the model consumes its own prediction as the input for the next forward pass (our TorchForecastingModels such as LSTM).

**Comment by mlap** [comment]
Figured out the issue! Did not realize that `historical_forecasts` uses a default output horizon of 1, assumed it used the horizon given to the model during training.
