### ISSUE TITLE
[QUESTION] Is there a generic way to save and load DARTS models

### ISSUE THREAD

**Issue by pamparana34** [unit8co/darts#878]
I am really struggling to figure out what is the best strategy for saving and loading DARTS models. We have models which are based on pytorch and simple models like exponential smoothing and just want to know what is the best strategy to generically save and load DARTS models.

**Comment by dennisbader** [comment]
Hey, have a look at #696

**Comment by pamparana34** [comment]
Thanks! This is great. Would it also work with the deep learning models i.e. can they be used instead of the `save_model`? My main interest is basically creating the underlying DARTS model object along with all its hyper parameters in a generic way.
