### ISSUE TITLE
Adding of a TimeSeries .drop() method

### ISSUE THREAD

**Issue by rokkian** [unit8co/darts#880]
**Is your feature request related to a current problem? Please describe.**
I haven't found in the TimeSeries documentation anything similar to a pd.DataFrame .drop() method and I think it would be compfy to have such.
Surely It ait't something critical, but in order to remove some componentes from multivariate TimeSeries, would be more comfy to my opinion.

**Describe proposed solution**
At the moment I worked around it using `set()` differences between the set of components of the TimeSeries and the compinent I want to remove:
```ts[list(set(ts.columns) - set(['stop_time']))] ```

**Describe potential alternatives**
I hope not to be wasting your time if such operation is already implemented through slicing operations `[ ]`

**Comment by hrzn** [comment]
This is a good idea - adding to our backlog. @rokkian let us know if you would be willing to work on adding such a method to the `TimeSeries` class.

**Comment by hrzn** [comment]
Awesome! Then I'd redirect you to our [contributing guidelines](https://github.com/unit8co/darts/blob/master/CONTRIBUTING.md) as a place to start. Then, for this issue, I think a good place to start would be to check how other `TimeSeries` methods are implemented, for instance some of the methods below [this line](https://github.com/unit8co/darts/blob/e3f33094ba0b02a96b25db9101b2be6def2d9fc7/darts/timeseries.py#L1331). Once you feel ready about the approach, just go ahead and open a PR. Let me know if you need help :)
