### ISSUE TITLE
RNN Model --> fit() --> loss=nan

### ISSUE THREAD

**Issue by lcjr86** [unit8co/darts#881]
Hello unit8co team,

I'm trying to `fit()` a `RNNModel()` but I'm having a `loss=nan` straight at the beginning of the training phase. I tried to change/calibrate a few parameters, thinking that is related to a vanish/exploding gradient but I didn't have any success so far.
Is there a way to 'debug' or get more info, like a `--verbose` or something like that?

Many thanks in advance and best regards,

Luiz

**Comment by dennisbader** [comment]
The first guess when you have nan values in your loss is that you have nan values in your input data.

If that is not the case, please send a code snippet to reproduce the issue.

**Comment by lcjr86** [comment]
Hey @dennisbader !

Amazing insight ;-) That was definitely that! Thank you very much!
