### ISSUE TITLE
Whether the program considers missing time ？ 

### ISSUE THREAD

**Issue by mavarick** [unit8co/darts#883]
**Is your feature request related to a current problem? Please describe.**
for example, time series with specified time window by day, but some days are missing.

**Describe proposed solution**
one way is checking time continuity before training/predicting, and fill empty dates with some values.

I want to know if there are some advanced or automatic ways to tackle this problem.

**Comment by ichsan2895** [comment]
I think you can use this way : 
```
series = TimeSeries.from_dataframe(DF, 'your date column name', 'your target column name', fillna_value=a number)
```
