### ISSUE TITLE
Group series creation.

### ISSUE THREAD

**Issue by timmermansjoy** [unit8co/darts#884]
**Is your feature request related to a current problem? Please describe.**
A clear and concise description of what the problem is.

Wanting to train a model based on energy consumption of different homes.

**Describe proposed solution**
A clear and concise description of what the library should provide to solve missing functionality.

 I would like there to be `group_ids` tag like in PyTorch forecasting [TimeSeriesDataSet](https://pytorch-forecasting.readthedocs.io/en/stable/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html). This so every household could be included into the time series dataset

**Additional context**

example you can see on their website [with Nbeats](https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/ar.html)

**Comment by hrzn** [comment]
Hi, Darts does not use any `group_ids` tag, but you can build multiple `TimeSeries`, for instance by doing something like:
```
my_time_series_dataset = []
for i in range(len(groups)):
    series = TimeSeries.from_XX(data[i])  # Create your TimeSeries for i-th group using factory method of your choice
    my_time_series_dataset.append(series)
    
my_model = NBEATS(...)
my_model.fit(my_time_series_dataset)
```

I hope this helps.

**Comment by timmermansjoy** [comment]
Thanks for the response. this does help a little. dont I have to create a train and validate set for the model or does it do that automatically if there is not one given?
