### ISSUE TITLE
[BUG] Darts matplotlib style settings should be optional

### ISSUE THREAD

**Issue by zgana** [unit8co/darts#892]
**Describe the bug**
Importing anything from darts results in significant changes to the global matplotlib configuration.  The style is pretty good, but it should be optional.

**To Reproduce**
```python
import matplotlib.pyplot as plt
import darts
plt.figure()
```

**Expected behavior**
There is a way to make the figure reflect the user's personal matplotlibrc without manually undoing everything listed in `darts/__init__.py`.

**System (please complete the following information):**
 - Python version: 3.7.9
 - darts==0.17.1

**Additional context**
A possible fix would be to suppress [this call](https://github.com/unit8co/darts/blob/d5dd29611221ccceb35236f018e94cd7dd918043/darts/__init__.py#L40) if something like `export DARTS_CONFIGURE_MATPLOTLIB=0` is set.

**Comment by hrzn** [comment]
Agree. Would you be willing to work on such a fix?

**Comment by zgana** [comment]
@hrzn Yes. Does this need to be added to the project board or should I go straight to submitting a PR?

**Comment by hrzn** [comment]
@zgana, I just moved it to "in progress". Feel free to focus on the PR and open it once it's ready. Let me know if you have any question. Here are our [contribution guidelines](https://github.com/unit8co/darts/blob/master/CONTRIBUTING.md). Don't forget to add an entry to the change log :)

**Comment by swertz** [comment]
I was looking for a way to avoid this global style change when importing darts, and I'm happy to see that there is a way to disable it. However, I think the better solution would be to have darts produce all plots whithin a context manager. This way, darts-produced plots could still follow the darts style (unless disabled by the `DARTS_CONFIGURE_MATPLOTLIB=0`, but without affecting the style chosen by the user.

If you think this is acceptable, I could look into making a PR.
