### ISSUE TITLE
[DISCUSSION] Using irregular pandas time series for Darts

### ISSUE THREAD

**Issue by ichsan2895** [unit8co/darts#900]
Hello, I already use darts since 2021 and I lovin it

Now I am facing a problem.
It's not a bug. But, I don't find any solution from **stackoverflow** 

I have stock time series price which has frequency of business day (monday-friday), but with every 5 minutes in working hours (09:00 - 15:00). Call this a pandas dataframe called `aali_ETS_pred`

![image](https://user-images.githubusercontent.com/60387342/162498350-f747e1d3-e42e-4f34-87e7-a807e45ea562.png)

Then I convert it to darts time series.

`series = TimeSeries.from_dataframe(aali_ETS_pred, 'ds', 'y', freq='5min')`

Just for curiousity, I convert back series to pandas dataframe
![image](https://user-images.githubusercontent.com/60387342/162500235-7d0cdec6-8e6f-45db-9d91-dc84723a126b.png)

I got bigger table, it automatically insert new rows which is week days and non-working hour. It also has NaN values

Now the question : 
1. How to handle NaN values from Darts series? I know it can be filled with some value or just zero (`fillna_value=0`). 
 
But, I think it will decrease the quality of input training data. It was strange if you has stock price in weekend+non working hours which has zero value or frugally averaging all value in that time series

4. Training with ExponentialSmoothing failed with this error. Already fill this series with `fillna_value=0`
![image](https://user-images.githubusercontent.com/60387342/162501348-014f91e5-ec42-4ab3-a3c5-b853afbe1a87.png)

5. Training with `Theta` failed with this error
```
# Search for the best theta parameter, by trying 50 different values
thetas = 2 - np.linspace(-10, 10, 50)

best_mape = float('inf')
best_theta = 0

for theta in thetas:
    model = Theta(theta)
    model.fit(train)
    pred_theta = model.predict(len(val))
    res = mape(val, pred_theta)
    
    if res < best_mape:
        best_mape = res
        best_theta = theta
        
best_theta
```
![image](https://user-images.githubusercontent.com/60387342/162502093-d8ed8ad7-f7dc-48cb-aa3c-b058c6fd555b.png)

Thank you for any kind of help and sorry for my bad english

**Comment by hrzn** [comment]
Hi, in your case the simplest solution might perhaps be to revert to using an integer index instead of a datetime index. So basically drop all the dates from your index, and build your series doing something like
```
my_series = TimeSeries.from_values(my_df['y'].values)
```
