### ISSUE TITLE
[BUG] Inability to Load and Evaluate a RNNModel

### ISSUE THREAD

**Issue by mlap** [unit8co/darts#902]
**Describe the bug**
When I attempt to use `load_model()` to restore a trained RNN model then call `predict()` on this model, I am getting the error:

> [/usr/local/lib/python3.7/dist-packages/darts/models/forecasting/torch_forecasting_model.py](https://localhost:8080/#) in _basic_compare_sample(train_sample, predict_sample)
>    1473     that training/inference datasets have target and a covariate in first and second position to do the checks.
>    1474     """
> -> 1475     tgt_train, cov_train = train_sample[:2]
>    1476     tgt_pred, cov_pred = predict_sample[:2]
>    1477     raise_if_not(
> 
> TypeError: 'NoneType' object is not subscriptable

**To Reproduce**

> from darts import TimeSeries
> from darts.datasets import AirPassengersDataset
> from darts.models import RNNModel
> from darts.dataprocessing.transformers import Scaler
> 
> series = AirPassengersDataset().load()
> scaler = Scaler()
> series_scaled = scaler.fit_transform(series)
> 
> model = RNNModel(
>     input_chunk_length=12,
>     output_chunk_length=4,
>     n_epochs=200,
>     hidden_dim=256,
> )
> 
> model.fit(series_scaled,
>           verbose=True,
>           )
> 
> model.save_model("trash.pth.tar")
> del model
> 
> model = RNNModel(
>     input_chunk_length=12,
>     output_chunk_length=4,)
> model.load_model("trash.pth.tar")
> predicts = model.predict(len(series_scaled), series_scaled)

**Expected behavior**
I am expecting the model to return a prediction on the inputted time series.

**System (please complete the following information):**
 - Python version: 3.7.13
 - darts version: 0.18.0

**Additional context**
None

**Comment by dennisbader** [comment]
You need to load the model like below 

`model = RNNModer.load_model(...)`
