### ISSUE TITLE
Can't install on docker from conda-forge

### ISSUE THREAD

**Issue by sh-cho** [unit8co/darts#904]
**Describe the bug**

```Dockerfile
FROM continuumio/miniconda3:latest

RUN mkdir /notebooks
WORKDIR /notebooks
COPY . /notebooks/

ENV CONDA_ALWAYS_YES=true

RUN conda install -c conda-forge -c pytorch u8darts-all \
    && conda install -c conda-forge jupyterlab

EXPOSE 8888

# ...
```

I'm trying to install darts on docker with conda, following [install guide](https://github.com/unit8co/darts/blob/master/INSTALL.md#from-conda-forge)

```
 => ERROR [5/5] RUN conda install -c conda-forge -c pytorch u8darts-all     && conda install -c conda-forge jupyterlab         35.4s
------
 > [5/5] RUN conda install -c conda-forge -c pytorch u8darts-all     && conda install -c conda-forge jupyterlab:
#0 0.281 Collecting package metadata (current_repodata.json): ...working... done
#0 2.988 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#0 4.770 Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
#0 6.799 Collecting package metadata (repodata.json): ...working... done
#0 14.35 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

#0 34.19 Found conflicts! Looking for incompatible packages.
#0 34.19 This can take several minutes.  Press CTRL-C to abort.
#0 34.19 failed
#0 34.20
#0 34.20 UnsatisfiableError: The following specifications were found
#0 34.20 to be incompatible with the existing python installation in your environment:
#0 34.20
#0 34.20 Specifications:
#0 34.20
#0 34.20   - u8darts-all -> python[version='>=3.7,<3.9']
#0 34.20
#0 34.20 Your python: python=3.9
#0 34.20
#0 34.20 If python is on the left-most side of the chain, that's the version you've asked for.
#0 34.20 When python appears to the right, that indicates that the thing on the left is somehow
#0 34.20 not available for the python version you are constrained to. Note that conda will not
#0 34.20 change your python version to a different minor version unless you explicitly specify
#0 34.20 that.
#0 34.20
#0 34.20
#0 34.20
```

But conda says python version is 3.9 so it's incompatible for `u8darts-all`.

Should I change python other than 3.9? Any advice would be helpful :)

**To Reproduce**

With Dockerfile above, run `docker build .`

**Expected behavior**

Successfully install darts

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.18.0

**Additional context**

**Comment by Yue-Li-atBain** [comment]
I encountered the same issue. When trying to build a docker image and use conda forge to install u8darts-all, it failed. 
I also tried to install u8darts[all] from pip, and it runs fine, but could not import autoarima model

**Comment by tomasvanpottelbergh** [comment]
Sorry for the late reply. I can reproduce it, but I don't know what the issue is unfortunately. I suspect there is a system library in the image that is not compatible with the requirements of some of the packages?

You could try to install the dependencies of u8darts-all one-by-one using conda to see if there is one that fails. As a workaround, installing conda on another Docker base image might work?

**Comment by sh-cho** [comment]
I used `continuumio/miniconda3:4.8.3` image which uses python 3.8 as a workaround, and I think it worked fine.

For now, I'm using `condaforge/mambaforge` (python 3.9.13) docker image and it also works fine.
