### ISSUE TITLE
[BUG] Regression Model Does Not Work With Grid Search

### ISSUE THREAD

**Issue by GitDoctor1996** [unit8co/darts#907]
**Describe the bug**
I am trying to train a simple univariate model using Regression Model with either Linear Regression, Random Forest, or Light GBM. We can stick with Random Forest as an example of this. When I try to do Gridsearch to find the optimal model for training, no matter what I do to instantiate lags, it gives me an error saying basically that I need to instantiate lags, which I already did. I put the lag parameter in the model class and in the grid search procedure in separate instances and it still gives me this error, without any recommendations on how to troubleshoot. 

ValueError: At least one of `lags`, `lags_future_covariates` or `lags_past_covariates` must be not None.

**To Reproduce**
rf_hyperparameters={'n_estimators':[100, 150, 200], 'max_depth':[3, 5, 7, 10, 15], 'lags': [-1, -2, -3, -4, -5, -6]}
m_random_forest=RandomForest(random_state=2).gridsearch(parameters=rf_hyperparameters, 
                                                                               series=train, 
                                                                                val_series=val, n_jobs = None)

**Expected behavior**
I expect the grid search procedure to work with every other model and return an untrained model class with the optimal hyperparameters included. 

**System (please complete the following information):**
 - Python version: 3.8
 - darts version 0.18.0

**Comment by kabirmdasraful** [comment]
It almost duplicates to following [ticket](https://github.com/unit8co/darts/issues/863)

Check there if you find your answer

**Comment by GitDoctor1996** [comment]
@kabirmdasraful I had looked over this ticket before and I wound up coming up with a for loop process that I intend to use multiprocessing for. If there is not a solution that allows grid search for Regression Model then I suppose we will have to come up with workarounds for the time being.

**Comment by GitDoctor1996** [comment]
> Hi, there are three things to note here:
> 
> * `gridsearch()` is a static `classmethod`, so you should call it like `RandomForest.gridsearch(...)` and not `my_rf_instance.gridsearch(...)`.
> * When creating a `RandomForest` instance, you should provide at least one of `lags`, `lags_future_covariates` or `lags_past_covariates`. Here, you are creating doing `RandomForest(random_state=2)`, so some argument is missing, like the error message says.
> * When given as a single integer, the parameter `lags` should be a positive integer. Here you have negative values in your list, which would produce issues down the line.
> 
> So all in all, you should do something like this:
> 
> ```python
> rf_hyperparameters={'n_estimators':[100, 150, 200], 
>                     'max_depth':[3, 5, 7, 10, 15], 
>                     'lags': [1, 2, 3, 4, 5, 6]}
> 
> m_random_forest = RandomForest.gridsearch(parameters=rf_hyperparameters, 
>                                           series=train, 
>                                           val_series=val, 
>                                           n_jobs = None)
> ```
> 
> I hope this helps, and I'm closing this issue as it's not a bug.

Thank you I will try this out and let you know if I have any other issues.
