### ISSUE TITLE
 Question：How to apply darts' models on non-continuous time series data？

### ISSUE THREAD

**Issue by guang7400613** [unit8co/darts#910]
In darts, the training data is in the form of TimeSeries, and TimeSeries requires continuous time, but some time series data are discontinuous, such as photovoltaic power data, because photovoltaic time series data only has power output during the daytime from 7:00 to 18:00, The rest of the time is output 0, so the photovoltaic power prediction is generally performed by extracting the data from 7:00 to 18:00, and the data in the rest of the time is meaningless for the entire training process and will cause interference. So even using the fill_missing_dates and fillna_value attributes to fill in discontinuous times and missing values will only have a bad impact on time series forecasting. So how do I apply this type of time series dataset on darts?

**Comment by hrzn** [comment]
Hi, there are several ways to go about this:
* Use actual 0's to denote the fact that power is 0 between 18:00 and 7:00 (some models might be very fine with that!)
* Create separate `TimeSeries` objects, one per day, with timestamps between 7:00 and 18:00; that would be regarding each day as a separate "observation" of the process you're trying to forecast.
* Ignore the timestamps and build a single `TimeSeries` that is integer-indexed, and contains the contiguous slices between 7:00 and 18:00 on consecutive days (meaning the observation at 07:00 at day d+1 would immediately follow the observation at 18:00 at day d in the series).

Which approach is right is more of a data science / modelling problem that will probably require some experimentation.

Hope this helps.

**Comment by hrzn** [comment]
> I have a similar problem. There are multiple experiments on a reactor, for each experiment data is observed for 30 days with constant covariates each time. I guess the best approach to have a separate Timeseries object for each experiment and train using the list of Timeseries.

Yes, what you describe typically sounds like a case for creating multiple TimeSeries (one per experiment / observation). 
I'm closing this issue for now, but don't hesitate to re-open if needed.
