### ISSUE TITLE
Multi-step forecasting

### ISSUE THREAD

**Issue by mandar-avhad** [unit8co/darts#923]
Hi all, I'm having a use case where I think multi-step forecasting would be useful.
Currently, I have no idea how to perform multi-step forecasting using Darts.
Can anyone suggest if Darts supports multi-step forecast and if yes, how can we do it?
Please share examples/code.

Thank you.

**Comment by hrzn** [comment]
Hi, yes, Darts supports multi-step forecasting. I would suggest you take a look at the [quickstart guide](https://unit8co.github.io/darts/quickstart/00-quickstart.html) which contains many examples of multi-step forecasts.
