### ISSUE TITLE
Question about TFT examples

### ISSUE THREAD

**Issue by heury** [unit8co/darts#926]
**Describe the bug**

I wonder why "covariates" is used in scaler_covs.transform()
I think it shuld be "cov_train".

covariates_transformed = scaler_covs.transform(**covariates**)

    cov_train, cov_val = covariates.split_after(training_cutoff)
    scaler_covs.fit(cov_train)
    covariates_transformed = scaler_covs.transform(**covariates**)
    covs.append(covariates_transformed)

**System (please complete the following information):**
 - Python version: 3.8
 - darts version: 0.19.0

**Additional context**

**Comment by dennisbader** [comment]
This is fine. We only fit the transformer based on the training covariate data. We can then transform all covariates (including the validation covariate data). In this example we use a MinMaxScaler, so training data will have values between 0 and 1 whereas the validation part of the covariates can have values exceeding this range.

Darts' models automatically extract the corresponding training/validation parts of the complete covariate series `covariates_transformed` in the background.
Does this answer your question?

**Comment by heury** [comment]
Yes. Thanks for your kind response.

**Comment by heury** [comment]
Yes. Thanks for your kind response.
