### ISSUE TITLE
Remove the warnings upfront when importing the light-weight versions

### ISSUE THREAD

**Issue by aaronsl-hku** [unit8co/darts#927]
**Is your feature request related to a current problem? Please describe.**
Yes. Currently using the "u8darts[torch]" version (for all the chaos for installing prophet but that's another story), every time I run my program with darts imported, I would received the warnings from [darts.models.__init__.py](https://github.com/unit8co/darts/blob/master/darts/models/__init__.py).  

It would not be a problem if the logger is instantiated directly from `logging` module, but with levels, format and `addHandler` hardcoded in `darts.logging.get_logger()` there's basically nothing I can do.

**Describe proposed solution**
The best solution would be completely replace the `darts.logging.get_logger()` function with standard `logging.getLogger()` (unless there're any very special reasons).

**Describe potential alternatives**
- Do not add handlers other than `NullHandler` as mentioned [here](https://docs.python.org/3/howto/logging.html#library-config)
- Raise the warnings in a lazy manner, if that is plausible.

**Comment by brunnedu** [comment]
Hi @aaronsl-hku, we would really like to help you resolve this issue. At the same time, we think that it is important to inform our users about missing modules. 

Therefore we would suggest giving you the option to opt-out of those warnings. Would it be possible for you to set an environment variable such as `DISABLE_DARTS_WARNINGS` in your terminal? We could then use this environment variable to adjust the logging behavior of darts.

**Comment by aaronsl-hku** [comment]
Hello @brunnedu . Nice to receive your reply.

We might have some misunderstanding here: I am **not** looking into disable all warnings as a whole. What I am proposing is not to hardcode the handler and formatter into the `get_logger` function. 

Long story short, if my project has a logging config and the formatting is not the same darts, my log would be easily screwed by the hardcoded formatter.

May I know if there is any particular reason not to use the standard logging.get_logger as-is?

> Hi @aaronsl-hku, we would really like to help you resolve this issue. At the same time, we think that it is important to inform our users about missing modules. 
> 
> 
> 
> Therefore we would suggest giving you the option to opt-out of those warnings. Would it be possible for you to set an environment variable such as `DISABLE_DARTS_WARNINGS` in your terminal? We could then use this environment variable to adjust the logging behavior of darts.

**Comment by martinb-bb** [comment]
> @martinb-bb WDYT of this solution?

I think this could work.

**Comment by brunnedu** [comment]
Thanks for your suggestions, everyone! 

I just added another commit: ad7a40422e8652c8abcfc879df55d36ec1bd971c
