### ISSUE TITLE
[BUG]Runing ARIMA, gets: ValueError: In models with integration (d > 0) or seasonal integration (D > 0)

### ISSUE THREAD

**Issue by zhangxjohn** [unit8co/darts#929]
ValueError: In models with integration (`d > 0`) or seasonal integration (`D > 0`), trend terms of lower order than `d + D` cannot be (as they would be eliminated due to the differencing operation). For example, a constant cannot be included in an ARIMA(1, 1, 1) model, but including a linear trend, which would have the same effect as fitting a constant to the differenced data, is allowed.

**Comment by hrzn** [comment]
Hi, I don't think that's a bug. It's a limitation of the ARIMA model, which the error message states quite clearly. I'm closing the issue, as this is expected. Feel free to re-open if you have spotted a behaviour that should not occur.
