### ISSUE TITLE
Question: How to implement an estimator\observer using darts?

### ISSUE THREAD

**Issue by TamerAbdelmigid** [unit8co/darts#930]
I have a data frame of shape (2400600, 3) I want to use the first two columns to estimate the third value.
in scikit syntax:
`X = df.iloc[:,:-1],
y = df.iloc[:,-1]` 

by estimate, I mean to deduce the current time step value of the third column, using the first two.

My question is, how to implement this using darts?

**Comment by hrzn** [comment]
Hi, in that case, I'd recommend to use a `RegressionModel`. Specify the first two columns as future covariates with a lag of 0, and that will do it. Optionally you can also provide other lags, if you think e.g. historic values (of the target or of the covariates) might help to predict future ones.
Hope this helps.
