### ISSUE TITLE
Question: How can I calculate the flops and params of each model?

### ISSUE THREAD

**Issue by DomineeringDragon** [unit8co/darts#932]
I want to calculate flops and params of each model, I tried thop and ptflops in the NBEATs Model but nothing can be calculate....

**Comment by dennisbader** [comment]
We currently don't have a way to calculate flops for our TorchForecastingModels. Maybe PyTorch Lightning will add this in the future, see [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/12567).

The number of model paramaters is printed in the model summary when calling `model.fit()`.
