### ISSUE TITLE
Add generic save/load functions to all darts models

### ISSUE THREAD

**Issue by sotte** [unit8co/darts#936]
**Is your feature request related to a current problem? Please describe.**
`darts` offers a nice interface to train/evaluate models independent of the implementation (`statsmodels`, `torch`, `prophet`, etc.), but it does not offer the same interface for serializing/deserializing models. It would be great if darts models offered generic save/load functions.

Right now only (?) the `pyroch` models have the save/load feature, other models mostly rely on pickling the models.

**Describe proposed solution**
`darts` implements save/load for each model framework that it supports.

* use the current implementation for pytorch models
* joblib pickle for the sklearn like models ([details](https://scikit-learn.org/stable/modules/model_persistence.html))
* pickle for statsmodels (?)
* etc.

**Additional context**
This feature would make it easier to add `darts` to framework independent model serving tools like `bentoml`, see https://github.com/bentoml/BentoML/issues/2368 for details.

**Comment by hrzn** [comment]
+1
Thanks for raising! Adding to our backlog :)
Would you want to contribute something around this?

**Comment by sotte** [comment]
As usual there are time constraints regarding contributions :(

Also right now this issue is not well defined yet. Do we just want to use existing serialization formats? Do we want to define wrap existing formats into a darts format (just a fancy name, but maybe all serialized models look like `model.darts` instead of framework specific names)? Do we want to save additional meta data? Do we want to create just one file or a folder?
Do you @hrzn and your folks have any opinions on this?

**Comment by hrzn** [comment]
@sotte https://github.com/unit8co/darts/pull/1070 introduced generic `save()` and `load()` methods for all forecasting models. PyTorch models rely on `torch.save()` and other models rely on pickle by default. Hopefully we're in a better state than before already.
