### ISSUE TITLE
[BUG] TCN model.predict_from_dataset expects PastCovariatesInferenceDataset instead of InferenceDataset

### ISSUE THREAD

**Issue by maxkazmsft** [unit8co/darts#939]
**Describe the bug**
When calling `model.predict_from_dataset`, input parameter `input_series_dataset` is of type `InferenceDataset`, but later the function produces `ValueError: expected type <class 'darts.utils.data.inference_dataset.PastCovariatesInferenceDataset'>` for some reason.

**To Reproduce**
Run the script https://github.com/maxkazmsft/darts/blob/maxkazmsft/test_tcn/examples/05-TCN-series-loader-custom_TrainingDataset.py - the error is on line 126 and is also pasted starting on line 127.

**Expected behavior**
I expect to pass in an instantiated test set class derived from `InferenceDataset` to `model.predict_from_dataset` and for the function `model.predict_from_dataset` to work properly.

**System (please complete the following information):**
- python=3.7
- u8darts-torch==0.17.1

**Additional context**
Pretty easy to repro - just run the script which I linked above.

**Comment by hrzn** [comment]
Hi, yes, the handling of types and error messages could be a bit better. But basically `PastCovariatesInferenceDataset` is an `InferenceDataset`. All the torch models expect (some subclass of) `InferenceDataset`. We ideally should use something like type parameters to handle this in a cleaner way (open to ideas :) )
