### ISSUE TITLE
[BUG]"generic_architecture = False" and "num_stacks = 3" confict

### ISSUE THREAD

**Issue by bingblackbean** [unit8co/darts#946]
For **NBeatsModel**, if **generic_architecture** is True, then **num_stacks**  input from user is not valid any more as we have below code: 
```
if not generic_architecture:
       self.num_stacks = 2
if isinstance(layer_widths, int):
       self.layer_widths = [layer_widths] * num_stacks
```
In this case beblow, maybe we don't need to check and raise an error.
```

- generic_architecture  == True
- layer_widths = [48,56]
- num_stacks= 3 ( I know 3 is wrong input, but it is not used in case generic_architecture  == True)
```

Since num_stacks  from user is not used any more, better not to raise the error in below code:
```
        raise_if_not(
            isinstance(layer_widths, int) or len(layer_widths) == num_stacks,
            "Please pass an integer or a list of integers with length `num_stacks`"
            "as value for the `layer_widths` argument.",
            logger,
        )
```

**Comment by hrzn** [comment]
Hi, I do not understand this issue. Could you please explain what model you refer to, what is the issue when you use it, what behaviour you expect, and a self-contained code snippet to reproduce the issue? Thanks.

**Comment by gdevos010** [comment]
you have this backward, `num_stacks` is only used when `generic_architecture` is set to `True`. 
The `interpretable architecture`, i.e., when `generic_architecture` is `False`, only has two stacks 

https://github.com/unit8co/darts/blob/155c653a5243af3dd56faad9ffa539bd58c8e050/darts/models/forecasting/nbeats.py#L566-L568
