### ISSUE TITLE
Inconsistencies in model documentation

### ISSUE THREAD

**Issue by shaido987** [unit8co/darts#948]
Thanks for maintaining an excellent forecasting library.  
I've recently been trying out a number of different models and noticed a number of inconsistencies in the model documentation. Refer to the documentation pages that can be found here: https://unit8co.github.io/darts/generated_api/darts.models.html

There are two clear formatting issues for these two forecasting models:

- LightGBM: the `likelihood` parameter.
- Linear Regression Model: the `random_state` parameter.

Below is a list of the other smaller issues that I found:

- Arima/Varima/Kalman Filter (both forecast and filtering): the argument types are missing code formatting, i.e., "``".
- Regression ensemble model: the parameters are missing dots at the end of sentences.
- RNN/Block RNN/N-BEATS/N-HiTS/TCN/TFT/Transformer: 
  - A lot of arguments are missing type information.
  - Some arguments has an additional empty row (`add_encoders`, `torch_device_str` and `pl_trainer_kwargs`). 
  - `show_warnings` starts with lower case. 
  - TFT: argument types do not use code formatting.
  - N-HiTS: refers to `generic_architecture` which is not available (probably copied from N-BEATS).
- References to other parameters/methods are mixed, either with `` or italics. For example:
  - For N-BEATS `num_stacks` uses italics and `loss_fn` uses code formatting to refer to other parameters.
  - Theta and exponential smoothing use different formatting for SeasonalityMode.ADDITIVE, SeasonalityMode.MULTIPLICATIVE, SeasonalityMode.NONE. 
  
For the last formatting issue, most model documentation pages seem to use italics relatively consistent so maybe all could be changed to use that.

**Comment by shaido987** [comment]
I'm open to try to fix these if wanted.

**Comment by dennisbader** [comment]
Hi @shaido987 and thanks for pointing out these inconsistencies!
S
That would be great, we're always happy about contributions :) If you need any help, let us know.

@hrzn for paramater references, should we go with "``" consistently?

**Comment by hrzn** [comment]
Hi @shaido987 yes please do not hesitate to fix & open a PR :)
Concerning the way to use quotes, let's follow [numpydoc recommendations](https://numpydoc.readthedocs.io/en/latest/format.html)
