### ISSUE TITLE
[QUESTION] Best way of using TFT for spatio-temporal prediction?

### ISSUE THREAD

**Issue by YannickLehr** [unit8co/darts#949]
I am wondering what is the best appraoch when trying to make a spatio temporal prediction with darts using a TFT.

Some background information: i am trying to predict demand in a clustered areas, similiar to the popular ny-yellow-taxis use-case.

From my understanding it should be sufficient to just creata a TimeSeries for every given area and than just train the model using those Multiple Time-Series. If i understood everything right, the model should now learn the relationship between the areas. However, i am wondering if i need (or if it makes a big difference in theory) if i feed the model addentional static information for the given area, or use a one-hot encoding in the covariates for each time series to differentiate between the areas.

**Comment by dennisbader** [comment]
Hi @YannickLehr and sorry for the late response.

Currently, the TFT model would not learn the rleationship between the areas but it will learn based on evoluation of each time series. Meaning: if for inference the model receives a similar timeseries as for let's say temperature in London (which it was already trained on), then it might yield better predictions as if you predict for an unobserved city that has quite a unique/unseen temperature history.

We are currently working on integrating static covariates to Darts. Trough static covariates, the TFT will be able to regard the spatial information during training.

**Comment by ricardobarroslourenco** [comment]
@dennisbader , any update on the static covariates? (sorry if this was answered in another thread - I am also working on the geospatial domain)

**Comment by dennisbader** [comment]
Hi @ricardobarroslourenco. Yes, static covariates are now supported in Darts and the TFTModel.
You can find an example of how to use them [here](https://unit8co.github.io/darts/examples/15-static-covariates.html).

**Comment by ricardobarroslourenco** [comment]
Thanks @dennisbader , highly appreciated!
