### ISSUE TITLE
GLU Variants Improve Transformer

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#959]
**Is your feature request related to a current problem? Please describe.**
[GLU Variants Improve Transformer](https://arxiv.org/abs/2002.05202)
[labml.ai implementation](https://nn.labml.ai/transformers/glu_variants/simple.html)

**Describe proposed solution**
I thought these would be worth adding since I'm adding other activations. 
I can work on it once #954 is merged.

**Comment by hrzn** [comment]
Nice - adding this to the project backlog :)
Thanks
