### ISSUE TITLE
Suppressing Warnings

### ISSUE THREAD

**Issue by martinb-bb** [unit8co/darts#964]
Hello,

This repo is fantastic and the documentation is stellar. Job well done 😄 

One question - I installed Darts with NN's but not the other (ARIMA/Prophet) 
I now get the following lines on my terminal constantly: 
`WARNING | darts.models | Support for AutoARIMA, BATS and TBATS is not available.To enable it, install u8darts[pmdarima] or u8darts[all].`

Do you have any recommendations on suppressing these warnings?

**Comment by gdevos010** [comment]
#927

**Comment by hrzn** [comment]
Thanks for the feedback :) Closing this one as indeed it's tracked by #927

**Comment by hrzn** [comment]
Thanks for the feedback :) Closing this one as indeed it's tracked by #927
