### ISSUE TITLE
Training is very untransparent

### ISSUE THREAD

**Issue by strakehyr** [unit8co/darts#965]
**Is your feature request related to a current problem? Please describe.**
The training loading bar does not return anything, even with verbose set to True. On top of that, the fact that the number of epochs trained is set during model design makes it a very inflexible process.

**Describe proposed solution**
Please, fix the progress bar, and add error feedback (I am not getting any from training TFTs). I should be able to see error on train/val. On the other issue, I don't understand n_epochs not being an argument of fit instead of the model.

**Comment by hrzn** [comment]
> **Is your feature request related to a current problem? Please describe.** The training loading bar does not return anything, even with verbose set to True. On top of that, the fact that the number of epochs trained is set during model design makes it a very inflexible process.
> 
> **Describe proposed solution** Please, fix the progress bar, and add error feedback (I am not getting any from training TFTs). I should be able to see error on train/val. On the other issue, I don't understand n_epochs not being an argument of fit instead of the model.

Hi, could you share a code snippet to reproduce the progress bar issue?
Concerning specifying the number of epochs, you can also specify it at `fit()` time using the `epochs` parameters - see [the API doc](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html#darts.models.forecasting.nbeats.NBEATSModel.fit)

**Comment by strakehyr** [comment]
From what I understand, this should give proper progress feedback:
```

model = TFTModel(
input_chunk_length = input_chunk_length,
output_chunk_length = forecast_horizon,
hidden_size = 1,
lstm_layers = 1,
num_attention_heads = 4,
dropout = 0.1,
batch_size = 64,
n_epochs = 3,
add_relative_index = False,
add_encoders = None,
pl_trainer_kwargs = {"accelerator": "gpu", "gpus": [0], 
                     "enable_progress_bar" : True, "enable_model_summary" : True},
likelihood = QuantileRegression(
    quantiles = quantiles
),
random_state = 42,
optimizer_cls = torch.optim.SGD,
optimizer_kwargs = {'lr':0.001}
)

model.fit(train_transformed, future_covariates = future_covariates_tf, 
             past_covariates = past_covariates_tf,
             verbose=True)
```
