### ISSUE TITLE
[QUESTION] Infer on CPU while model is trained in GPU

### ISSUE THREAD

**Issue by gsamaras** [unit8co/darts#971]
I had trained an N-Beats model in GPU and now I want to use to do predictions in CPU.

```
from darts.models.forecasting.nbeats import NBEATSModel

model_nbeats = NBEATSModel(input_chunk_length=3,  output_chunk_length=1, generic_architecture=True)
model_nbeats.save_model("nbeats_model.pth.tar") # Save on GPU
```
Then on a CPU machine I do:
```
model_nbeats = NBEATSModel.load_model("nbeats_model.pth.tar")
```
and get this error:
```
RuntimeError: Attempting to deserialize object on a CUDA device
```

---

My attempt was to follow this [SO question](https://stackoverflow.com/questions/56369030/runtimeerror-attempting-to-deserialize-object-on-a-cuda-device), like:
```
model_nbeats = load_model("nbeats_model.pth.tar", map_location=torch.device('cpu'))
```
but this [method](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html?highlight=nbeats#darts.models.forecasting.nbeats.NBEATSModel.load_model) doesn't accept any such parameter.

If I then use `torch.load()`, like:
```
import torch
model_nbeats = torch.load("nbeats_model.pth.tar", map_location=torch.device('cpu'))
```
it works but then the predict method doesn't work:
```
current_pred_series = model_nbeats.predict( series = test_series, n = 1)
```
because it's a Torch model and not a Darts one.

Can you please help?

---

I cannot use the `Trainer` parameter in `predict()`, because I am using Darts 0.16.1 and cannot change at this time, which has this signature:
```
(n: int, series: Union[darts.timeseries.TimeSeries, Sequence[darts.timeseries.TimeSeries], NoneType] = None, past_covariates: Union[darts.timeseries.TimeSeries, Sequence[darts.timeseries.TimeSeries], NoneType] = None, future_covariates: Union[darts.timeseries.TimeSeries, Sequence[darts.timeseries.TimeSeries], NoneType] = None, batch_size: Union[int, NoneType] = None, verbose: bool = False, n_jobs: int = 1, roll_size: Union[int, NoneType] = None, num_samples: int = 1, num_loader_workers: int = 0) -> Union[darts.timeseries.TimeSeries, Sequence[darts.timeseries.TimeSeries]]
```

**Comment by gsamaras** [comment]
Hi @dennisbader, so you mean, with Darts 0.16.1, in the GPU machine use `NBEATSModel.save_checkpoints()` ([ref](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html?highlight=nbeats#darts.models.forecasting.nbeats.NBEATSModel)), and then in the CPU machine use `NBEATSModel.load_from_checkpoint()`?

Yes currently upgrading is not an option for my project-related-internal-reasons. :/

**Comment by dennisbader** [comment]
You should activate checkpointing at model creation on the GPU machine ([see model docs here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html#n-beats)): 

```
model = NBEATSModel(..., model_name="my_model", work_dir=my_work_dir, save_checkpoints=True)
``` 

And then on the CPU machine load from checkpoint [see here](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nbeats.html#darts.models.forecasting.nbeats.NBEATSModel.load_from_checkpoint) 

```
model = NBEATSModel.load_from_checkpoint(model_name="my_model", work_dir=my_work_dir, best=False)
```

(I can't say for certain that it will work though)

**Comment by gsamaras** [comment]
It didn't. On load I got:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
If you have other ideas please let me know. Otherwise, when time permits in the future, I will upgrade Darts and revisit this.

**Comment by dennisbader** [comment]
Then you would have to adapt the code:
- fork the repo
- branch out of master
- reset the head to where it was in your specific darts version
- adapt the loading methods to pass the device mapping to the internal torch loading
- install darts locally from this branch

**Comment by gsamaras** [comment]
Thank you, I'll see if I manage to modify darts or if I'll be able to update Darts later.
