### ISSUE TITLE
beta-NLL

### ISSUE THREAD

**Issue by gdevos010** [unit8co/darts#972]
**Is your feature request related to a current problem? Please describe.**
beta-NLL from the paper ["On the Pitfalls of Heteroscedastic Uncertainty Estimation with Probabilistic Neural Networks"](https://arxiv.org/abs/2203.09168)

**Describe proposed solution**
 We could create a new likelihood

or 

It could be added to the `_nlloss()` method
https://github.com/unit8co/darts/blob/155c653a5243af3dd56faad9ffa539bd58c8e050/darts/utils/likelihood_models.py#L126-L132

**Comment by hrzn** [comment]
Nice! Seems like a great addition indeed. Adding to the backlog.

**Comment by hrzn** [comment]
Nice! Seems like a great addition indeed. Adding to the backlog.

**Comment by gdevos010** [comment]
I think it would look something like this 

```python 
nll = -out_distr.log_prob(target).mean() 
        if self.beta > 0.0:
            variance = out_distr.variance
            nll = nll * (variance.detach() ** self.beta)
        return nll
```
