### ISSUE TITLE
New installer version - Removing LightGBM dependancy

### ISSUE THREAD

**Issue by martinb-bb** [unit8co/darts#976]
## Is your feature request related to a current problem? Please describe.

MacOS Issues with LightGBM
At the time of writing, there is an issue with libomp 12.0.1 that results in https://github.com/microsoft/LightGBM/issues/4229. Here's the procedure to downgrade the libomp library (from the https://github.com/microsoft/LightGBM/issues/4229#issue-867528353):

[Install brew](https://brew.sh/) if you don't already have it.
Install wget if you don't already have it : brew install wget.
Run the commands below:
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/fb8323f2b170bd4ae97e1bac9bf3e2983af3fdb0/Formula/libomp.rb
brew unlink libomp
brew install libomp.rb
```
This works great if you have a command line, but not if you have an installer.
We would like to have this work out of the box. 

## Describe proposed solution
Would it be possible to provide a pip and conda installer that does not use LightGBM models? (until libomp issue is solved on microsoft's side for macs) 

Install core + neural networks (PyTorch) (without LightGMB): `pip install "u8darts[torch-nolight]"`
Install core + neural networks (PyTorch): `conda install -c conda-forge -c pytorch u8darts-torch-nolight`

## Additional context
We would like to use Darts packaged with an installer (on all platforms including Mac), and cannot put brew commands with this install on Mac. 
We will forfeit use of LightGMB for the short time being until Microsoft resolves https://github.com/microsoft/LightGBM/issues/4229

There is also mention in the issue that:
"Please, anyone subscribed to this issue, check whether the error occurs with the most recent libomp version 13.0.1." 
I do not know if it works still because I installed all packages last week on a new machine and still ran into issues with this library. 

Please let me know if I am wrong on something. 😄 
Thank you!

**Comment by hrzn** [comment]
Hi @martinb-bb, unfortunately we cannot add such a new flavour, because flavours can only *add* dependencies with respect to core dependencies, and LightGBM is already in our core dependencies. However, I would expect the LigthGBM issue to manifest itself only at runtime (preventing the use of `LightGBMModel`), but not otherwise affecting Darts capabilities. Could you confirm this is the case? If yes, I guess there shouldn't be any big issue as long as you don't use this model in OpenBB. Is my understanding correct?

**Comment by martinb-bb** [comment]
That makes sense!

So can I ask why there is a problem with `libomp`? Say I don't use LightGBM...why do I have to revert the version of `libomp`? I have never used it once, but I couldnt run darts without errors until I downgraded the version. 

Many Mac users are having issues setting up and running the dart lib due to dependency issues (which is not your fault at all). 

One did the following to get Darts to run on his x86 machine (they could not downgrade `libomp`??...)

```
 conda update git
 conda update pip
 conda install -c conda-forge -c pytorch u8darts-torch
 conda install -c conda-forge lightgbm
 conda install -c conda-forge pystan
 conda install -c conda-forge ephem
pip install u8darts[arima]
 pip install u8darts[prophet]
```

Which in my eyes makes no sense. 

I guess, the only thing I'm looking for is a standardized way to install some subset of darts that works well on all OS. 

Linux and windows is easy...but mac has been quite a struggle.
