### ISSUE TITLE
[BUG] Pass past covariates list for grid search RandomForest

### ISSUE THREAD

**Issue by albin02t** [unit8co/darts#985]
Hi, 
I am trying to train a RandomForest Regressor model for forecasting and then apply hyper parameter tuning on it using Gridsearch.
When passing the past_covariates series in the grid search it gives me a ValueError.

To Reproduce:
```
model = RandomForest(lags, lags_past_covariates =lags_cov, output_chunk_length= 53)
model.fit(series = target_list, past_covariates=covariates_list)
output = model.predict(n_forecasts, series=target_list, past_covariates=covariates_list)

model.gridsearch(parameters={'lags':[5,10,15,20]}, series = a[0], past_covariates=d[0], val_series = b[0])
```
ValueError: `past_covariates` not None in `fit()` method call, but `lags_past_covariates` is None in constructor.

Being a static class i had tried the below as well

`RandomForest.gridsearch(parameters={'lags':[5,10,15,20]}, series = a[0], past_covariates=d[0], val_series = b[0])`
ValueError: `past_covariates` not None in `fit()` method call, but `lags_past_covariates` is None in constructor.

So how do i pass the past_covariates list for grid search?

Expected behavior:
It should allow for gridsearch and return the best parameters

System (please complete the following information):
 - Python version: 3.7.11
 - darts version: 0.18.0

**Comment by dennisbader** [comment]
Hi @albin02t, two things:
- `gridsearch` is a class method and you shouldn't use it on a trained model instance. Best is to call it from the model class itself
- you have to add the `lags_past_covariates` to gridsearch as well to use your past covariates. If you want a fixed value for the past cov lags simple give a single element list: {..., `'lags_past_covariates': [5]`} 

```
# gives you an untrained model created from best `best_params` and and the best parameters found 
model_untrained, best_params = RandomForest.gridsearch(parameters={'lags':[5,10,15,20], 'lags_past_covariates': [...]}, series = a[0], past_covariates=d[0], val_series = b[0])
```
