### ISSUE TITLE
[BUG] Passing metric for grid search evaluation for series containing 0

### ISSUE THREAD

**Issue by albin02t** [unit8co/darts#987]
Hi,

i want to apply grid search tuning using RandomForest but my train or val data may contain 0s in them in which case the default MAPE would fail. MASE can be used for calculating errrors in training data containing 0.
But passing the mase function gives errors that i am not able to solve

To Reproduce:
```
        from darts.models.forecasting.random_forest import RandomForest
        from darts.metrics import mase
        rf_hyperparameters={'n_estimators':[100, 150, 200], 'lags': [5, 10, 15, 20, 25, 30]}
        m_random_forest = RandomForest.gridsearch(parameters=rf_hyperparameters, 
                                                  series=train,
                                                  val_series=val, metric=mase())
```
It gives the following error:
`TypeError: mase() missing 1 required positional argument: 'insample'`

How can i use MASE for RandomForest gridsearch metric

System (please complete the following information):

    Python version: 3.7.11
    darts version: 0.18.0

**Comment by dennisbader** [comment]
Hi @albin02t , the `metric` must be a callable accepting 2 TimeSeries as input arguments and that returns a float value. 

When you pass `metric=mase()` as a metric, this is not a callable/function anymore, but ready already what is returned by MASE. You get the error because you call the MASE function without giving the required positional arguments.

Instead, pass `metric=mase` which will give the actual callable/function to gridsearch. Within the gridseach method the MASE function is then be accessed with `metric(target, preds)`.

**Comment by albin02t** [comment]
Hi @dennisbader I had passed the metric the way you had mentioned as:
```
        m_random_forest = RandomForest.gridsearch(parameters=rf_hyperparameters, 
                                                  series=train,
                                                  val_series=val, metric=mase)
```
but got the following error:
`TypeError: mase() missing 1 required positional argument: 'insample'`

**Comment by albin02t** [comment]
Hi @dennisbader I had passed the metric the way you had mentioned as:

        m_random_forest = RandomForest.gridsearch(parameters=rf_hyperparameters, 
                                                  series=train,
                                                  val_series=val, metric=mase)

but got the following error:
TypeError: mase() missing 1 required positional argument: 'insample'

**Comment by dennisbader** [comment]
You can with any other metrics that accepts two poisitonal input arguments (see all metrics [here](https://unit8co.github.io/darts/generated_api/darts.metrics.metrics.html), like rmse, mse, mae, marre, ..)
