### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zora-no** [unit8co/darts#988]
**Describe the bug**
When fitting a `darts.models.forecasting.rnn_model.RNNModel` without gridsearch, there is no error. However, when performing a gridsearch with the same parameter (I had other parameters but removed them since this caused the problem), `model.fit` throws an error. This also happens with `input_chunk_length < 10`, and also with smaller `training_ and input_chunck_length`. **Why does this only happen with gridsearch and not when simply calling `model.fit()`, while the parameters are exactly the same?**

**To Reproduce**
**With gridsearch**
```
model = RNNModel(input_chunk_length=10,
                 output_chunk_length=13,
                 model='LSTM', 
                 batch_size=16,
                 n_epochs=150,
                 optimizer_kwargs={"lr": 1e-3},
                 hidden_dim=25, 
                 n_rnn_layers=2,
                 dropout=0.2, 
                 loss_fn=RMSELoss(),
                 training_length=12)

parameters = {"input_chunk_length": [10]}

model, param, score = model.gridsearch(parameters, series_scaled, future_covariates=future_cov, forecast_horizon=13, stride=np.floor(13/2), start=0.5, metric=rmse)

model.fit(
    train, # multivariate TimeSeries with 5 components and 91 time points
    future_covariates=future_cov, # extends very far into the future
    val_series=val, # 13 time points
    val_future_covariates=future_cov,
    verbose=False,
)
forecast = model.predict(13)
```

--> Error:
```
ValueError                                Traceback (most recent call last)
[<ipython-input-28-f9b6e9d313c2>](https://localhost:8080/#) in <module>
     24     val_series=val,
     25     val_future_covariates=future_cov,
---> 26     verbose=False,
     27 )
     28 forecast = model.predict(n_val)

4 frames
[/usr/local/lib/python3.7/dist-packages/darts/utils/torch.py](https://localhost:8080/#) in decorator(self, *args, **kwargs)
     68         with fork_rng():
     69             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 70             return decorated(self, *args, **kwargs)
     71 
     72     return decorator

[/usr/local/lib/python3.7/dist-packages/darts/models/forecasting/torch_forecasting_model.py](https://localhost:8080/#) in fit(self, series, past_covariates, future_covariates, val_series, val_past_covariates, val_future_covariates, trainer, verbose, epochs, max_samples_per_ts, num_loader_workers)
    770 
    771         return self.fit_from_dataset(
--> 772             train_dataset, val_dataset, trainer, verbose, epochs, num_loader_workers
    773         )
    774 

[/usr/local/lib/python3.7/dist-packages/darts/utils/torch.py](https://localhost:8080/#) in decorator(self, *args, **kwargs)
     68         with fork_rng():
     69             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 70             return decorated(self, *args, **kwargs)
     71 
     72     return decorator

[/usr/local/lib/python3.7/dist-packages/darts/models/forecasting/torch_forecasting_model.py](https://localhost:8080/#) in fit_from_dataset(self, train_dataset, val_dataset, trainer, verbose, epochs, num_loader_workers)
    839         )
    840         raise_if(
--> 841             val_dataset is not None and len(val_dataset) == 0,
    842             "The provided validation time series dataset is too short for obtaining even one training point.",
    843             logger,

[/usr/local/lib/python3.7/dist-packages/darts/utils/data/shifted_dataset.py](https://localhost:8080/#) in __len__(self)
    235 
    236     def __len__(self):
--> 237         return len(self.ds_past)
    238 
    239     def __getitem__(

ValueError: __len__() should return >= 0
```

**Same parameter, without gridsearch**
```
model = RNNModel(input_chunk_length=10,
                 output_chunk_length=n_val,
                 model='LSTM', 
                 batch_size=16,
                 n_epochs=150,
                 optimizer_kwargs={"lr": 1e-3},
                 hidden_dim=25, 
                 n_rnn_layers=2,
                 dropout=0.2, 
                 loss_fn=RMSELoss(),
                 training_length=12)

model.fit(
    train, # multivariate TimeSeries with 5 components and 91 time points
    future_covariates=future_cov, # extends very far into the future
    val_series=val, # 13 time points
    val_future_covariates=future_cov,
    verbose=False,
)

forecast = model.predict(n_val)
```
-->  no error

**System:**
 - Running on Google Colab
 - darts version 0.19.0

**Comment by hrzn** [comment]
Hi, although the error message is not very useful, this comes from the fact that the series is being fed series that are too short during training when doing grid search. It does not happen during "regular" training because it uses the full series. Grid-searching does backtesting and so uses shorter historic series. Try on a longer series, reducing the sum of input+output chunk lengths, or increasing the `start` parameter.

**Comment by zora-no** [comment]
Thanks for your response. Then why do I not get this error if I run the code with even larger input_chunk_length and therefore even shorter training series? By the logic in your comment, the same error should happen, since the training series is even shorter, but it doesn't?
If I do output_chunk_length=13, train_length=91 --> error
output_chunk_length=26, train_length=78 --> no error (only change: training_length=26)
output_chunk_length=39, train_length=65 --> no error (only change: training_length=26)

**Comment by hrzn** [comment]
> Thanks for your response. Then why do I not get this error if I run the code with even larger input_chunk_length and therefore even shorter training series? By the logic in your comment, the same error should happen, since the training series is even shorter, but it doesn't? If I do output_chunk_length=13, train_length=91 --> error output_chunk_length=26, train_length=78 --> no error (only change: training_length=26) output_chunk_length=39, train_length=65 --> no error (only change: training_length=26)

I think it comes from the `train_length` parameter which is shorter and (for RNNModel) this is what determines whether the series is long enough.

**Comment by zora-no** [comment]
input_chunk_length=[12, 16, 20, 24]
output_chunk_length=13
I have now tried several values for training_length, up to 40. Still, I always get the same error.  I also tried decreasing input_chunk_length down to 12, or increasing the start parameter to increase the length of the series - didn't help.

For my other models with output_chunk_length=26 and output_chunk_length=39, everything works well when i set training_length to max(input_chunk_length)+2, start=0.5, and input_chunk_length=[12, 16, 20, 24].  It's only for this lower output_chunk_length that nothing seems to work. Do you have any more ideas?

**Comment by zora-no** [comment]
I figured out that the error came from 
```
model.fit(
    train, # len 91
    future_covariates=future_cov,
    val_series=val, # len 13
    val_future_covariates=future_cov,
    verbose=False,
)
```

after removing the arguments val_series and val_future_covariates, it worked.
