### ISSUE TITLE
[QUESTION][BUG] Error in importing models from darts.models

### ISSUE THREAD

**Issue by mad-stat** [unit8co/darts#990]
I am trying to import the Transformers, NBEATS, TCN and BlockRNN models in python using darts.models. However, the error indicating "No module named 'holidays.financial' " is popping up. 

Can you suggest a possible solution for this?

**Comment by hrzn** [comment]
Hi, I think there was an issue with a recent release of `holidays`, which got fixed soon afterwards yesterday. Could you try doing `pip install -U holidays` and try again?
